# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdt/SerialPort/../../translations/mdtserialport_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdt/SerialPort/../../translations/mdtserialport_de.ts
