
branches:
 only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/  # Also build tags

environment:

  BOOST_ROOT: 'C:\Libraries'

  matrix:
    # MinGW
    - CMAKE_GENERATOR: "MinGW Makefiles"
      QT_PREFIX_PATH: 'C:\Qt\5.9\mingw53_32'
      MINGW_PREFIX_PATH: 'C:\Qt\Tools\mingw530_32'

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  # Thanks to: http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
  - set PATH=%PATH:C:\Program Files\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%QT_PREFIX_PATH%\bin;%MINGW_PREFIX_PATH%\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -C ..\cmake\caches\ReleaseGcc.cmake -G "%CMAKE_GENERATOR%" ..\
  - cmake --build . -- -j4

test_script:
  - ctest --output-on-failure .

after_build:
  - cpack -G ZIP .

artifacts:
  - path: build\Mdt*.zip
    name: MdtZipDistribution

deploy:
  provider: GitHub
  auth_token:
    secure: YnLpfRJ3an3UULcagmbxw9gqAquwEqJZ2Vj/glhhG0bC4VOzSTMsSyxnP9dR7Z2I
  description: "Mdt release"
  artifact: MdtZipDistribution
  on:
    appveyor_repo_tag: true
