/****************************************************************************
 **
 ** Copyright (C) 2011-2016 Philippe Steinmann.
 **
 ** This file is part of multiDiagTools library.
 **
 ** multiDiagTools is free software: you can redistribute it and/or modify
 ** it under the terms of the GNU Lesser General Public License as published by
 ** the Free Software Foundation, either version 3 of the License, or
 ** (at your option) any later version.
 **
 ** multiDiagTools is distributed in the hope that it will be useful,
 ** but WITHOUT ANY WARRANTY; without even the implied warranty of
 ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 ** GNU Lesser General Public License for more details.
 **
 ** You should have received a copy of the GNU Lesser General Public License
 ** along with multiDiagTools.  If not, see <http://www.gnu.org/licenses/>.
 **
 ****************************************************************************/
#ifndef MDT_SQL_COPIER_DATABASE_MAPPING_H
#define MDT_SQL_COPIER_DATABASE_MAPPING_H

#include "DatabaseCopierTableMapping.h"
#include "mdtError.h"
#include "mdtExpected.h"
#include <QSqlDatabase>
#include <QVector>
#include <QStringList>
#include <memory>

namespace mdt{ namespace sql{ namespace copier{

  /*! \brief Store SQL database copy mapping
   */
  class DatabaseMapping
  {
   public:

    /*! \brief Get count of table mapping
     */
    int tableMappingCount() const
    {
      return pvTableMappingList.size();
    }

    /*! \brief Set source database
     *
     * Will also reset table mapping.
     *
     * \sa resetMapping()
     */
    mdtExpected<bool> setSourceDatabase(const QSqlDatabase & db);

    /*! \brief Get source database
     */
    QSqlDatabase sourceDatabase() const
    {
      return pvSourceDatabase;
    }

    /*! \brief Set destination database
     *
     * Will also reset mapping.
     *
     * \sa resetMapping()
     */
    mdtExpected<bool> setDestinationDatabase(const QSqlDatabase & db);

    /*! \brief Get destination database
     */
    QSqlDatabase destinationDatabase() const
    {
      return pvDestinationDatabase;
    }

    /*! \brief Reset mapping
     *
     * Will clear mapping,
     *  then, generate it for each available table in destination database.
     *  After that, no valid mapping is set to source database.
     */
    mdtExpected<bool> resetMapping();

    /*! \brief Generate table mapping by name
     *
     * Will first reset table mapping.
     *  Then, for each table in destination database,
     *  source table is defined by destination table name.
     *  For each mapped table, field mapping is alos generated by field names.
     *
     * \todo Checks + get mapping state of each item
     */
    mdtExpected<bool> generateTableMappingByName();

    /*! \brief Clear mapping
     *
     * \todo Define what is the utility of this function (should be obseleted..)
     */
    void clearMapping();

    /*! \brief Get source table name for given mapping index
     *
     * \pre index must be in a valid range
     */
    QString sourceTableName(int index) const
    {
      Q_ASSERT(index >= 0);
      Q_ASSERT(index < pvTableMappingList.size());
      return pvTableMappingList.at(index)->sourceTableName();
    }

    /*! \brief Get destination table name for given mapping index
     *
     * \pre index must be in a valid range
     */
    QString destinationTableName(int index) const
    {
      Q_ASSERT(index >= 0);
      Q_ASSERT(index < pvTableMappingList.size());
      return pvTableMappingList.at(index)->destinationTableName();
    }

    /*! \brief Get table mapping at given index
     *
     * \pre index must be in a valid range
     */
    const std::shared_ptr<DatabaseCopierTableMapping> tableMapping(int index) const
    {
      Q_ASSERT(index >= 0);
      Q_ASSERT(index < pvTableMappingList.size());
      return pvTableMappingList.at(index);
    }

   private:

    QSqlDatabase pvSourceDatabase;
    QSqlDatabase pvDestinationDatabase;
    QVector<std::shared_ptr<mdt::sql::copier::DatabaseCopierTableMapping>> pvTableMappingList;
  };

}}} // namespace mdt{ namespace sql{ namespace copier{

#endif // MDT_SQL_COPIER_DATABASE_MAPPING_H
