Multi diag tools: mdtClPathGraphicsConnection Class Reference
mdtClPathGraphicsConnection Class Reference
Item that represent a connection (circle and text) in a graphics scene.
#include <mdtClPathGraphicsConnection.h>
Public Types
enum { Type = UserType + 1 }
GraphicsItem specific type.
enum ConnectionType { Terminal, Pin, Socket }
Connection type.
Public Member Functions
mdtClPathGraphicsConnection ()
Constructor.
~mdtClPathGraphicsConnection ()
Destructor.
void setConnectionType (ConnectionType t)
Set connection type.
ConnectionType connectionType () const
Get connections type.
void setText (const QString &text)
Set text.
void setTerminalDiameter (qreal diameter)
Set the circle diameter.
void setPinSize (qreal width, qreal height)
Set pin size.
void setSocketSize (qreal width, qreal height)
Set socket size.
QPointF nextPos (bool reverse=false, qreal linkLength=200.0, qreal dAlpha=0.785398163397) const
Get the position for next connection (node)
void addLink (mdtClPathGraphicsLink *link)
Add a link.
QList< mdtClPathGraphicsLink * > links () const
Get related links.
int type () const
Get type.
QRectF boundingRect () const
Get bounding rect.
QPainterPath shape () const
Get shape.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Paint the item.
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Change handler - Will update links.
Detailed Description
Item that represent a connection (circle and text) in a graphics scene.
Definition at line 39 of file mdtClPathGraphicsConnection.h.
Member Enumeration Documentation
anonymous enum
GraphicsItem specific type.
Enumerator
Type
Definition at line 45 of file mdtClPathGraphicsConnection.h.
enum mdtClPathGraphicsConnection::ConnectionType
Connection type.
Enumerator
Terminal
Terminal
Pin
Pin (male)
Socket
Socket (female)
Definition at line 49 of file mdtClPathGraphicsConnection.h.
Constructor & Destructor Documentation
mdtClPathGraphicsConnection::mdtClPathGraphicsConnection ()
Constructor.
Will set connection type to Terminal
Definition at line 39 of file mdtClPathGraphicsConnection.cpp.
References setConnectionType(), and Terminal.
mdtClPathGraphicsConnection::~mdtClPathGraphicsConnection ()
Destructor.
Definition at line 49 of file mdtClPathGraphicsConnection.cpp.
Member Function Documentation
void mdtClPathGraphicsConnection::addLink (mdtClPathGraphicsLink * link)
Add a link.
Definition at line 187 of file mdtClPathGraphicsConnection.cpp.
References mdtClPathGraphicsLink::adjust().
Referenced by mdtClPathGraphicsLink::mdtClPathGraphicsLink().
QRectF mdtClPathGraphicsConnection::boundingRect () const
Get bounding rect.
Definition at line 206 of file mdtClPathGraphicsConnection.cpp.
ConnectionType mdtClPathGraphicsConnection::connectionType () const inline
Get connections type.
Definition at line 71 of file mdtClPathGraphicsConnection.h.
QVariant mdtClPathGraphicsConnection::itemChange (GraphicsItemChange change, const QVariant & value) protected
Change handler - Will update links.
Definition at line 236 of file mdtClPathGraphicsConnection.cpp.
QList< mdtClPathGraphicsLink * > mdtClPathGraphicsConnection::links () const
Get related links.
Definition at line 195 of file mdtClPathGraphicsConnection.cpp.
QPointF mdtClPathGraphicsConnection::nextPos (bool reverse = false, qreal linkLength = 200.0, qreal dAlpha = 0.785398163397) const
Get the position for next connection (node)
This is a helper method to place connection on a scene. This will not alter current connection's position.
Parameters
reverse If true, next position will be searched from right to left
linkLength The expected length of link
dAlpha Angle increment (default is approx pi/4, 45°)
Definition at line 125 of file mdtClPathGraphicsConnection.cpp.
References M_PI.
void mdtClPathGraphicsConnection::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
Paint the item.
Definition at line 220 of file mdtClPathGraphicsConnection.cpp.
void mdtClPathGraphicsConnection::setConnectionType (mdtClPathGraphicsConnection::ConnectionType t)
Set connection type.
Definition at line 53 of file mdtClPathGraphicsConnection.cpp.
References Pin, setPinSize(), setSocketSize(), setTerminalDiameter(), Socket, and Terminal.
Referenced by mdtClPathGraphicsConnection().
void mdtClPathGraphicsConnection::setPinSize (qreal width, qreal height)
Set pin size.
Definition at line 105 of file mdtClPathGraphicsConnection.cpp.
References setText().
Referenced by setConnectionType().
void mdtClPathGraphicsConnection::setSocketSize (qreal width, qreal height)
Set socket size.
Definition at line 115 of file mdtClPathGraphicsConnection.cpp.
References setText().
Referenced by setConnectionType().
void mdtClPathGraphicsConnection::setTerminalDiameter (qreal diameter)
Set the circle diameter.
void mdtClPathGraphicsConnection::setCircleDiameter(qreal diameter)
void setCircleDiameter(qreal diameter);
Set the terminal diameter
Definition at line 94 of file mdtClPathGraphicsConnection.cpp.
References setText().
Referenced by setConnectionType().
void mdtClPathGraphicsConnection::setText (const QString & text)
Set text.
Definition at line 69 of file mdtClPathGraphicsConnection.cpp.
Referenced by setPinSize(), setSocketSize(), and setTerminalDiameter().
QPainterPath mdtClPathGraphicsConnection::shape () const
Get shape.
Definition at line 211 of file mdtClPathGraphicsConnection.cpp.
int mdtClPathGraphicsConnection::type () const
Get type.
Definition at line 201 of file mdtClPathGraphicsConnection.cpp.
References Type.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClPathGraphicsConnection.h
src/mdttools/mdttesttool/mdtcablelist/mdtClPathGraphicsConnection.cpp