Multi diag tools: mdtFrameCodecScpiU3606A Class Reference
mdtFrameCodecScpiU3606A Class Reference
Decode Agilent U3606A SCPI data.
#include <mdtFrameCodecScpiU3606A.h>
Public Types
enum measure_type_t {
MT_UNKNOW, MT_VOLTAGE_DC, MT_VOLTAGE_AC, MT_CURRENT_DC,
MT_CURRENT_AC, MT_RESISTANCE, MT_CONTINUITY, MT_LRESISTANCE,
MT_CAPACITANCE, MT_DIODE, MT_FREQUENCY, MT_PWIDTH,
MT_DCYCLE
}
Measure type.
Public Types inherited from mdtFrameCodecScpi
enum query_type_t {
QT_UNKNOW = 0, QT_VALUE, QT_SINGLE_VALUE_FLT, QT_IDN,
QT_ERR, QT_CONF
}
Query type.
enum waveform_format_t { WORD, BYTE, ASCII }
Format of waveform data.
Public Member Functions
mdtFrameCodecScpiU3606A ()
bool decodeConfigure (const QByteArray &data)
Decode CONFigure? reply.
measure_type_t measureType () const
Get the measure type.
QString measureUnit () const
Get measure unit.
mdtValue measureRange () const
Get the measure range.
mdtValue resolution () const
Get the measure resolution.
Public Member Functions inherited from mdtFrameCodecScpi
mdtFrameCodecScpi ()
virtual ~mdtFrameCodecScpi ()
bool decodeValues (const QByteArray &data, QString sep=":")
Decode SCPI value(s)
mdtValue decodeSingleValueDouble (const QByteArray &data)
Decode a signle value in double floating format.
mdtValue checkFloatingValueValidity (double x) const
Check the validity of a floating value.
bool decodeFunctionParameters (const QByteArray &data)
Decode reply of type function/parameter.
bool decodeIdn (const QByteArray &data)
Decode the IDN answer.
bool decodeScpiVersion (const QByteArray &data)
Decode the SCPI version returned by SYSTem:VERSion? query.
bool decodeError (const QByteArray &data)
Decode error answer.
bool decodeIEEEblock (const QByteArray &data, waveform_format_t format)
Decode a IEEE block.
Public Member Functions inherited from mdtFrameCodecAscii
mdtFrameCodecAscii ()
~mdtFrameCodecAscii ()
void setEofSeq (QByteArray &eofSeq)
Set the Eond Of Frame Sequence.
void trim ()
Remove whitespaces at begin and end of data frame.
void setCaseUpper ()
Set frame's data to upper case.
QVariant convertData (const QString &data) const
Convert a string to first matching type.
Public Member Functions inherited from mdtFrameCodec
mdtFrameCodec ()
~mdtFrameCodec ()
const QList< QVariant > & values () const
Get the decoded values.
Additional Inherited Members
Protected Member Functions inherited from mdtFrameCodecScpi
bool decodeIEEEdataAscii (const QByteArray &data)
Decode a array of ASCII values.
bool decodeIEEEdataByte (const QByteArray &data)
Decode a array of BYTE values.
Protected Attributes inherited from mdtFrameCodecAscii
QString pvAsciiData
QByteArray pvEofSeq
QStringList pvNodes
Detailed Description
Decode Agilent U3606A SCPI data.
Definition at line 28 of file mdtFrameCodecScpiU3606A.h.
Member Enumeration Documentation
enum mdtFrameCodecScpiU3606A::measure_type_t
Measure type.
Enumerator
MT_UNKNOW
Unknow measure type
MT_VOLTAGE_DC
Measure type DC voltage
MT_VOLTAGE_AC
Measure type AC voltage
MT_CURRENT_DC
Measure type DC current
MT_CURRENT_AC
Measure type AC current
MT_RESISTANCE
Measure type resistance
MT_CONTINUITY
Measure type continuity
MT_LRESISTANCE
Measure type low value reistance
MT_CAPACITANCE
Measure type capacitance
MT_DIODE
Measure type diode
MT_FREQUENCY
Measure type frequency
MT_PWIDTH
Measure type pulse width
MT_DCYCLE
Measure type duty cycle
Definition at line 34 of file mdtFrameCodecScpiU3606A.h.
Constructor & Destructor Documentation
mdtFrameCodecScpiU3606A::mdtFrameCodecScpiU3606A ()
Definition at line 27 of file mdtFrameCodecScpiU3606A.cpp.
References MT_UNKNOW.
Member Function Documentation
bool mdtFrameCodecScpiU3606A::decodeConfigure (const QByteArray & data)
Decode CONFigure? reply.
Definition at line 32 of file mdtFrameCodecScpiU3606A.cpp.
References mdtValue::clear(), mdtError::commit(), mdtFrameCodecScpi::decodeFunctionParameters(), mdtError::Error, MDT_ERROR_SET_SRC, MT_CAPACITANCE, MT_CONTINUITY, MT_CURRENT_AC, MT_CURRENT_DC, MT_DCYCLE, MT_DIODE, MT_FREQUENCY, MT_LRESISTANCE, MT_PWIDTH, MT_RESISTANCE, MT_UNKNOW, MT_VOLTAGE_AC, MT_VOLTAGE_DC, mdtFrameCodecAscii::pvNodes, and mdtFrameCodec::pvValues.
mdtValue mdtFrameCodecScpiU3606A::measureRange () const
Get the measure range.
Definition at line 142 of file mdtFrameCodecScpiU3606A.cpp.
mdtFrameCodecScpiU3606A::measure_type_t mdtFrameCodecScpiU3606A::measureType () const
Get the measure type.
Definition at line 109 of file mdtFrameCodecScpiU3606A.cpp.
Referenced by mdtDeviceU3606A::getMeasureConfiguration().
QString mdtFrameCodecScpiU3606A::measureUnit () const
Get measure unit.
Definition at line 114 of file mdtFrameCodecScpiU3606A.cpp.
References MT_CAPACITANCE, MT_CONTINUITY, MT_CURRENT_AC, MT_CURRENT_DC, MT_DCYCLE, MT_DIODE, MT_FREQUENCY, MT_LRESISTANCE, MT_PWIDTH, MT_RESISTANCE, MT_UNKNOW, MT_VOLTAGE_AC, and MT_VOLTAGE_DC.
mdtValue mdtFrameCodecScpiU3606A::resolution () const
Get the measure resolution.
Definition at line 147 of file mdtFrameCodecScpiU3606A.cpp.
The documentation for this class was generated from the following files:
src/mdtutils/mdtFrameCodecScpiU3606A.h
src/mdtutils/mdtFrameCodecScpiU3606A.cpp