Multi diag tools: mdtPortInfo Class Reference
mdtPortInfo Class Reference
Contains informations about a port.
#include <mdtPortInfo.h>
Public Member Functions
mdtPortInfo ()
mdtPortInfo (const mdtPortInfo &other)
~mdtPortInfo ()
void setPortName (const QString &name)
Set the port name.
QString portName () const
Get the port name.
void addDevice (mdtDeviceInfo *device)
Add a device.
QList< mdtDeviceInfo * > & deviceInfoList ()
Get the list of devices informations.
void setDisplayText (const QString &text)
Set the display text.
QString displayText () const
Get the display text.
mdtPortInfo & operator= (const mdtPortInfo &other)
Copy operator.
bool operator== (const mdtPortInfo &other)
Comparaison operator.
bool operator!= (const mdtPortInfo &other)
Comparaison operator.
Detailed Description
Contains informations about a port.
Used by mdtPortManager in scan() method.
Definition at line 33 of file mdtPortInfo.h.
Constructor & Destructor Documentation
mdtPortInfo::mdtPortInfo ()
Definition at line 26 of file mdtPortInfo.cpp.
mdtPortInfo::mdtPortInfo (const mdtPortInfo & other)
Definition at line 30 of file mdtPortInfo.cpp.
mdtPortInfo::~mdtPortInfo ()
Definition at line 42 of file mdtPortInfo.cpp.
Member Function Documentation
void mdtPortInfo::addDevice (mdtDeviceInfo * device)
Add a device.
Definition at line 57 of file mdtPortInfo.cpp.
Referenced by mdtUsbPortManager::scan().
QList< mdtDeviceInfo * > & mdtPortInfo::deviceInfoList ()
Get the list of devices informations.
Note that content of returned list is not a copy, and that all items becomes ivalid after this (mdtPortInfo) object was deleted.
Definition at line 62 of file mdtPortInfo.cpp.
Referenced by mdtUsbPortManager::scan().
QString mdtPortInfo::displayText () const
Get the display text.
Returns a text that can be displayed to the user. (F.ex. in a combo box)
Definition at line 72 of file mdtPortInfo.cpp.
Referenced by mdtPortInfoCbHandler::addPortInfo().
bool mdtPortInfo::operator!= (const mdtPortInfo & other)
Comparaison operator.
Definition at line 119 of file mdtPortInfo.cpp.
mdtPortInfo & mdtPortInfo::operator= (const mdtPortInfo & other)
Copy operator.
Definition at line 77 of file mdtPortInfo.cpp.
bool mdtPortInfo::operator== (const mdtPortInfo & other)
Comparaison operator.
Note that display text is not compared.
Definition at line 95 of file mdtPortInfo.cpp.
QString mdtPortInfo::portName () const
Get the port name.
Definition at line 52 of file mdtPortInfo.cpp.
Referenced by mdtDeviceModbusWago::connectToDevice(), mdtPortManager::portName(), and mdtPortManager::setPortInfo().
void mdtPortInfo::setDisplayText (const QString & text)
Set the display text.
Set a text that can be displayed to the user. (F.ex. in a combo box)
Definition at line 67 of file mdtPortInfo.cpp.
Referenced by mdtSerialPortManager::scan(), mdtUsbPortManager::scan(), and mdtModbusTcpPortManager::scan().
void mdtPortInfo::setPortName (const QString & name)
Set the port name.
Definition at line 47 of file mdtPortInfo.cpp.
Referenced by mdtSerialPortManager::scan(), mdtUsbPortManager::scan(), and mdtModbusTcpPortManager::scan().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortInfo.h
src/mdtport/mdtPortInfo.cpp