Multi diag tools: mdtSerialPortManager Class Reference
mdtSerialPortManager Class Reference
Serial port manager class.
#include <mdtSerialPortManager.h>
Public Member Functions
mdtSerialPortManager (QObject *parent=0)
Construct a serial port manager.
~mdtSerialPortManager ()
Destructor.
QList< mdtPortInfo * > scan ()
Scan for available serial ports.
mdtSerialPortConfig & config ()
Get the config object.
mdtAbstractSerialPort & port ()
Get the serial port instance.
mdtSerialPortCtlThread * ctlThread ()
Get the modem lines thread object.
Public Member Functions inherited from mdtPortManager
mdtPortManager (QObject *parent=0)
Contruct a port manager.
virtual ~mdtPortManager ()
Destructor.
virtual void setPort (mdtAbstractPort *port)
Set port object.
void lockPortMutex ()
Lock the port's mutex.
void unlockPortMutex ()
Unlock port's mutex.
void detachPort (bool deletePort, bool deleteThreads)
Detach port.
void addThread (mdtPortThread *thread)
Add a thread and assign it to port.
mdtPortThread * readThread ()
Returns instance of reader thread.
mdtPortThread * writeThread ()
Returns instance of writer thread.
void removeThreads (bool releaseMemory)
Detach threads from port and remove threads.
virtual bool start ()
Start port manager.
void stop ()
Stop port manager.
void setPortName (const QString &portName)
Set port name.
void setPortInfo (mdtPortInfo info)
Set port info.
mdtPortInfo portInfo ()
Get current port info.
QString portName () const
Get current port name.
mdtPortConfig & config () const
Get the port's config object.
void setKeepTransactionsDone (bool keep)
Force transactions done to be keeped.
bool keepTransactionsDone () const
Get the keepTransactionsDone flag.
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
virtual int sendData (mdtPortTransaction *transaction)
Send data on port.
virtual int sendData (const QByteArray &data, bool queryReplyMode=false)
Send data to port.
bool waitTransactionDone (int id)
Wait until a transaction is done.
bool waitOneTransactionDone ()
Wait until current transaction is done.
void wait (int ms)
Wait for some time.
QByteArray readenFrame (int id)
Get data by frame ID.
QList< QByteArray > readenFrames ()
Get all readen data.
virtual void flushIn (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush input buffers.
void flushIn ()
Flush input buffers.
virtual void flushOut (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush output buffers.
void flushOut ()
Flush output buffers.
void flush (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush I/O buffers.
void flush ()
Flush I/O buffers.
state_t currentState () const
Get current state.
void notifyCurrentState ()
Notify the current state.
virtual bool isReady () const
Check if port manager is ready.
bool isClosed () const
Check if port is closed.
Additional Inherited Members
Public Types inherited from mdtPortManager
enum state_t {
PortClosed = 0, Stopped, Starting, Stopping,
Running, PortError, PortReady, Disconnected,
Connecting, Connected, Ready, Busy
}
State of device.
Public Slots inherited from mdtPortManager
virtual void abort ()
Cancel read and write operations.
Signals inherited from mdtPortManager
void newTransactionDone (mdtPortTransaction *transaction)
Emitted each time a transaction is done.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
void stateChanged (int stateId)
Emitted each time the state changed.
void stateChangedForUi (int stateId, const QString &stateText, int ledColorId, bool ledIsOn)
Emitted only if a state that must be notified is entered.
void pmPortClosedEvent ()
Sent when port was closed.
void pmStartThreadsEvent ()
Sent when threads must be started.
void pmStopThreadsEvent ()
Sent when threads must be stopped.
void pmAllThreadsReadyEvent ()
Sent when all threads are ready.
void pmAllThreadsStoppedEvent ()
Sent when all threads are stopped.
void pmUnhandledErrorEvent ()
Sent when a unhandled error occured.
void pmConnectingEvent ()
Sent when connection with device beginns.
void pmConnectedEvent ()
Sent when connection with device is established.
void pmDisconnectedEvent ()
Sent when connection with device was lost/closed.
void pmConnectionFailedEvent ()
Sent when connection failed on startup or after max try.
void pmBusyEvent ()
Sent when device is busy (or other slow down reason..)
void pmReadyEvent ()
Sent when device and communication becomes ready again.
void pmTransactionTimeoutEvent ()
Sent when a transaction timeout occured.
Protected Slots inherited from mdtPortManager
virtual void fromThreadNewFrameReaden ()
Called by the read thread whenn a complete frame was readen.
virtual void onThreadsErrorOccured (int error)
Manage errors comming from port threads.
Protected Member Functions inherited from mdtPortManager
virtual bool openPort ()
Open the port.
void closePort ()
Close the port.
void setCurrentTransactionId (int id)
Set the current transaction ID.
int currentTransactionId () const
Get the current transaction ID.
void incrementCurrentTransactionId (int min=0, int max=INT_MAX)
Increment current transaction ID.
bool waitTransactionPossible ()
Wait until transaction pending queue has less than maximum possible items.
void addTransactionPending (mdtPortTransaction *transaction)
Add a transaction to pending queue.
mdtPortTransaction * transactionPending (int id)
Take pending transaction matching id.
void flushTransactionsPending ()
Restore all transactions pending to pool.
void addTransactionDone (mdtPortTransaction *transaction)
Add a transaction to the DONE queue.
bool transactionsDoneContains (int id) const
Check if a transaction with given ID exists in done queue.
mdtPortTransaction * transactionDone (int id)
Take transaction from DONE queue matching id.
void flushTransactionsDone ()
Restore all transactions done to pool.
void startTransactionTimer (int timeout)
Start transaction timer.
void stopTransactionTimer ()
Stop transaction timer.
bool transactionTimeoutOccured () const
Check if a transaction timeout occured.
void commitFrames ()
Emit signals for each done transactions.
Protected Attributes inherited from mdtPortManager
mdtAbstractPort * pvPort
QList< mdtPortThread * > pvThreads
Detailed Description
Serial port manager class.
This is the easiest way to use the serial port API.
All needed object are created by constructor. To alter configuration, use config(). To access the serial port object, use port().
Use start() to begin read/write and stop to end.
Definition at line 46 of file mdtSerialPortManager.h.
Constructor & Destructor Documentation
mdtSerialPortManager::mdtSerialPortManager (QObject * parent = 0)
Construct a serial port manager.
Creates a mdtSerialPortConfig, a mdtSerialPort, and threads objects.
Definition at line 32 of file mdtSerialPortManager.cpp.
References mdtPortManager::addThread(), config(), port(), mdtAbstractPort::setConfig(), and mdtPortManager::setPort().
mdtSerialPortManager::~mdtSerialPortManager ()
Destructor.
Stop the manager (if running), and close the port (if open). All internal objects (port, config and threads) are deleted here.
Definition at line 48 of file mdtSerialPortManager.cpp.
References mdtAbstractPort::config(), mdtPortManager::detachPort(), and mdtPortManager::pvPort.
Member Function Documentation
mdtSerialPortConfig & mdtSerialPortManager::config () virtual
Get the config object.
Usefull to alter internal port configuration
Reimplemented from mdtPortManager.
Definition at line 135 of file mdtSerialPortManager.cpp.
References mdtAbstractSerialPort::config(), and mdtPortManager::pvPort.
Referenced by mdtSerialPortManager().
mdtSerialPortCtlThread * mdtSerialPortManager::ctlThread ()
Get the modem lines thread object.
Definition at line 156 of file mdtSerialPortManager.cpp.
mdtAbstractSerialPort & mdtSerialPortManager::port ()
Get the serial port instance.
Precondition
Port must be set with a mdtAbstractSerialPort instance (not mdtAbstractPort)
Definition at line 146 of file mdtSerialPortManager.cpp.
References mdtPortManager::pvPort.
Referenced by mdtSerialPortCtlWidget::makeConnections(), mdtSerialPortManager(), and scan().
QList< mdtPortInfo * > mdtSerialPortManager::scan () virtual
Scan for available serial ports.
Try to open available ports on system and get some attributes. If both steps works, the found port is considered existing.
Precondition
Manager must no running.
Returns
List of available serial ports on system (f.ex: /dev/ttyS0 on Unix , or COM1 on Windows)
Reimplemented from mdtPortManager.
Definition at line 56 of file mdtSerialPortManager.cpp.
References mdtAbstractSerialPort::close(), mdtError::Error, mdtPortManager::isClosed(), MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, mdtAlgorithms::naturalSort(), mdtAbstractPort::NoError, mdtAbstractPort::open(), port(), mdtPortManager::portInfo(), mdtPortInfo::setDisplayText(), mdtPortInfo::setPortName(), mdtAbstractPort::setPortName(), mdtAbstractSerialPort::uartType(), and mdtAbstractSerialPort::UT_UNKNOW.
The documentation for this class was generated from the following files:
src/mdtserialport/mdtSerialPortManager.h
src/mdtserialport/mdtSerialPortManager.cpp