Multi diag tools: mdtUsbtmcPortSetupDialog Class Reference
mdtUsbtmcPortSetupDialog Class Reference
#include <mdtUsbtmcPortSetupDialog.h>
Public Member Functions
mdtUsbtmcPortSetupDialog (QWidget *parent=0)
~mdtUsbtmcPortSetupDialog ()
Public Member Functions inherited from mdtAbstractPortSetupDialog
mdtAbstractPortSetupDialog (QWidget *parent=0)
Constructor.
~mdtAbstractPortSetupDialog ()
Destructor.
void setPortManager (mdtPortManager *portManager)
Set the port manager.
mdtPortManager * portManager ()
Get port manager.
Additional Inherited Members
Protected Slots inherited from mdtAbstractPortSetupDialog
void showStatusMessage (const QString &message, int timeout=0)
Used to show a message in status widget.
void showStatusMessage (const QString &message, const QString &details, int timeout=0)
Used to show a message and details in status widget.
Protected Member Functions inherited from mdtAbstractPortSetupDialog
void setHeaderWidget (QWidget *w)
Set the header widget.
void addOptionsTabWidget (QWidget *w, const QString &label)
Add a widget to the options tab.
void setOkButtonEnabled (bool enabled)
Enable/disable Ok button.
void setApplyButtonEnabled (bool enabled)
Enable/disable Apply button.
void setCancelButtonEnabled (bool enabled)
Enable/disable Cancel button.
Detailed Description
Definition at line 37 of file mdtUsbtmcPortSetupDialog.h.
Constructor & Destructor Documentation
mdtUsbtmcPortSetupDialog::mdtUsbtmcPortSetupDialog (QWidget * parent = 0)
Definition at line 33 of file mdtUsbtmcPortSetupDialog.cpp.
References mdtAbstractPortSetupDialog::addOptionsTabWidget(), mdtPortInfoCbHandler::setDevicesComboBox(), mdtAbstractPortSetupDialog::setHeaderWidget(), and mdtPortInfoCbHandler::setPortsComboBox().
mdtUsbtmcPortSetupDialog::~mdtUsbtmcPortSetupDialog ()
Definition at line 75 of file mdtUsbtmcPortSetupDialog.cpp.
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbtmcPortSetupDialog.h
src/mdtport/mdtUsbtmcPortSetupDialog.cpp