Multi diag tools: mdtSqlTableSelection Class Reference
mdtSqlTableSelection Class Reference
Handle selection of model indexes in a QTableView.
#include <mdtSqlTableSelection.h>
Public Member Functions
mdtSqlTableSelection ()
Constructor.
void clear ()
Clear selection (will not affect any model, view or selection model)
void setIndexList (const QModelIndexList &indexList, const QStringList &fieldList, QSqlQueryModel *model)
Set model index list.
int rowCount () const
Get row count.
bool isEmpty () const
Check if selection is empty.
QVariant data (int row, const QString &fieldName) const
Get data for given row and field name.
QStringList fields (int row) const
Get a list of fields contained in given row.
QList< QVariant > dataList (const QString &fieldName) const
Get a list of data for given field.
Detailed Description
Handle selection of model indexes in a QTableView.
Qt offers some classes to handle selections in item view/model classes.
But, in database applications, it's common that the user can select one or many items, and we want to get a result for selected rows, and only some fields.
For example, say we have a table:
Id_PK Name Remarks
1 User 1 A remark on User 1
2 User 2 A remark on User 2
This table is displayed in a QTableView and data are handled by a QSqlTableModel. For commodity, we let the user select individual items (not complete rows). Now, its possible to edit a user by double clicking on a row. Or, it's also possible to remove several users by selecting corresponding rows, and clicking a push button (or a menu item, ...). The data we need, is in Id_PK field, witch is probably not shown to the user. If hi wants to edit, hi will probably double click on "User 1" item in view. Here, we need to get value of Id_PK of row 0 (=1).
This class is used by mdtSqlTableWidget, mdtSqlSelectionDialog.
Definition at line 58 of file mdtSqlTableSelection.h.
Constructor & Destructor Documentation
mdtSqlTableSelection::mdtSqlTableSelection ()
Constructor.
Definition at line 26 of file mdtSqlTableSelection.cpp.
Member Function Documentation
void mdtSqlTableSelection::clear ()
Clear selection (will not affect any model, view or selection model)
Definition at line 30 of file mdtSqlTableSelection.cpp.
Referenced by setIndexList().
QVariant mdtSqlTableSelection::data (int row, const QString & fieldName) const
Get data for given row and field name.
Note: row does not match any model index, it's a row index of internally stored selection rows.
Precondition
row must be in a valid range (0 <= row < rowCount()).
Definition at line 70 of file mdtSqlTableSelection.cpp.
Referenced by mdtTtAbstractTester::createTest(), mdtTtAbstractTester::openTest(), mdtTtBase::removeData(), mdtClLinkBeam::removeLinks(), mdtClLink::removeLinks(), mdtTtTestModel::removeTestModelItems(), and mdtTtTestNode::setTestNodeUnitIoRange().
QList< QVariant > mdtSqlTableSelection::dataList (const QString & fieldName) const
Get a list of data for given field.
Definition at line 90 of file mdtSqlTableSelection.cpp.
Referenced by mdtClUnit::removeConnections(), and mdtTtTestNodeUnit::removeNodeUnits().
QStringList mdtSqlTableSelection::fields (int row) const
Get a list of fields contained in given row.
Precondition
row must be in a valid range (0 <= row < rowCount()).
Definition at line 82 of file mdtSqlTableSelection.cpp.
Referenced by mdtTtBase::removeData().
bool mdtSqlTableSelection::isEmpty () const inline
Check if selection is empty.
Definition at line 88 of file mdtSqlTableSelection.h.
Referenced by mdtTtAbstractTester::createTest(), mdtTtAbstractTester::openTest(), and mdtTtBase::removeData().
int mdtSqlTableSelection::rowCount () const inline
Get row count.
Definition at line 84 of file mdtSqlTableSelection.h.
Referenced by mdtTtAbstractTester::createTest(), mdtTtAbstractTester::openTest(), mdtTtBase::removeData(), mdtClLinkBeam::removeLinks(), mdtClLink::removeLinks(), mdtTtTestModel::removeTestModelItems(), and mdtTtTestNode::setTestNodeUnitIoRange().
void mdtSqlTableSelection::setIndexList (const QModelIndexList & indexList, const QStringList & fieldList, QSqlQueryModel * model)
Set model index list.
Parameters
indexList Typically a result returned from QItemSelectionModel::selectedIndexes()
fieldList List of fields that are needed
model Needed to get some informations (typically field names related to a model index)
Precondition
model must be a valid pointer
Each model index in indexList must point to given model
Note: calling this method will clear previous data.
Definition at line 35 of file mdtSqlTableSelection.cpp.
References mdtSqlTableSelectionRow::addIndex(), mdtSqlTableSelectionRow::clear(), and clear().
Referenced by mdtSqlTableWidget::currentSelection(), and mdtSqlSelectionDialog::selection().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlTableSelection.h
src/mdtdatabase/mdtSqlTableSelection.cpp