Multi diag tools: mdtValueDouble Class Reference
mdtValueDouble Class Reference
Contains a floating (double) value with some attributes.
#include <mdtValue.h>
Public Member Functions
mdtValueDouble () noexcept
Construct a null value.
mdtValueDouble (double value, bool isOl=false) noexcept
Construct a value.
void clear () noexcept
Clear value.
void setValue (double value, bool isOl=false) noexcept
Set value.
bool isNull () const noexcept
Check if value is null.
double value () const noexcept
Get value.
bool isMinusOl () const noexcept
Check if value is -OL.
bool isPlusOl () const noexcept
Check if value is +OL.
bool isNaN () const noexcept
Check if value is NaN.
bool operator== (const mdtValueDouble &other) const noexcept
Comparaison operator.
bool operator!= (const mdtValueDouble &other) const noexcept
Comparaison operator.
bool operator< (const mdtValueDouble &other) const noexcept
Comparison operator.
bool operator<= (const mdtValueDouble &other) const noexcept
Comparison operator.
bool operator> (const mdtValueDouble &other) const noexcept
Comparison operator.
bool operator>= (const mdtValueDouble &other) const noexcept
Comparison operator.
mdtValueDouble operator+ (const mdtValueDouble &other) const noexcept
Addition operator.
mdtValueDouble operator- (const mdtValueDouble &other) const noexcept
Subtraction operator.
mdtValueDouble operator* (const mdtValueDouble &other) const noexcept
Multiplication operator.
mdtValueDouble operator/ (const mdtValueDouble &other) const noexcept
Division operator.
Detailed Description
Contains a floating (double) value with some attributes.
Most of cases, using standard C++ types are sufficent.
When dealing with instruments, some additionnal flags are needed:
+OL, -OL: to tell, for example, that a measure is out of instrument's range.
Null: for example, if a error occured, a Null value could be returned (from a function).
Note: Null and NaN is not the same. A Null mdtValueDouble contains a NaN value, but a non Null mdtValue can also contain a NaN value. For example, if a communication error occured, a function should return a Null value.
Definition at line 38 of file mdtValue.h.
Constructor & Destructor Documentation
mdtValueDouble::mdtValueDouble () noexcept
Construct a null value.
Definition at line 32 of file mdtValue.cpp.
Referenced by operator*(), operator+(), operator-(), and operator/().
mdtValueDouble::mdtValueDouble (double value, bool isOl = false) noexcept
Construct a value.
Parameters
value Value to store
isOl Force OL flag to be set. If value is >= 0.0 , +OL is set, else -OL will be set
Definition at line 38 of file mdtValue.cpp.
Member Function Documentation
void mdtValueDouble::clear () noexcept
Clear value.
After this call, value will be null
Definition at line 43 of file mdtValue.cpp.
bool mdtValueDouble::isMinusOl () const noexcept
Check if value is -OL.
Definition at line 64 of file mdtValue.cpp.
Referenced by operator<<().
bool mdtValueDouble::isNaN () const noexcept
Check if value is NaN.
Definition at line 80 of file mdtValue.cpp.
Referenced by operator<<().
bool mdtValueDouble::isNull () const inline noexcept
Check if value is null.
Definition at line 68 of file mdtValue.h.
Referenced by mdtCodecScpi::decodeFunctionParameters(), mdtDeviceU3606A::getMeasureValue(), operator<<(), and mdtTtTestCableOffsetTool::runOffsetReset().
bool mdtValueDouble::isPlusOl () const noexcept
Check if value is +OL.
Definition at line 72 of file mdtValue.cpp.
Referenced by operator<<().
bool mdtValueDouble::operator!= (const mdtValueDouble & other) const inline noexcept
Comparaison operator.
Definition at line 102 of file mdtValue.h.
mdtValueDouble mdtValueDouble::operator* (const mdtValueDouble & other) const inline noexcept
Multiplication operator.
Note:
If one (or both) value is null, a null value will be returned (Same rule as IEEE 754 NaN)
For all other cases, including OL flags (wich are stored as infinity values), follows standard floating point arithmetic rules
Definition at line 203 of file mdtValue.h.
References mdtValueDouble().
mdtValueDouble mdtValueDouble::operator+ (const mdtValueDouble & other) const inline noexcept
Addition operator.
Note:
If one (or both) value is null, a null value will be returned (Same rule as IEEE 754 NaN)
For all other cases, including OL flags (wich are stored as infinity values), follows standard floating point arithmetic rules
Definition at line 175 of file mdtValue.h.
References mdtValueDouble().
mdtValueDouble mdtValueDouble::operator- (const mdtValueDouble & other) const inline noexcept
Subtraction operator.
Note:
If one (or both) value is null, a null value will be returned (Same rule as IEEE 754 NaN)
For all other cases, including OL flags (wich are stored as infinity values), follows standard floating point arithmetic rules
Definition at line 189 of file mdtValue.h.
References mdtValueDouble().
mdtValueDouble mdtValueDouble::operator/ (const mdtValueDouble & other) const inline noexcept
Division operator.
Note:
If one (or both) value is null, a null value will be returned (Same rule as IEEE 754 NaN)
For all other cases, including OL flags (wich are stored as infinity values), follows standard floating point arithmetic rules
Definition at line 217 of file mdtValue.h.
References mdtValueDouble().
bool mdtValueDouble::operator< (const mdtValueDouble & other) const inline noexcept
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Todo:
Use functions from cmath !
Definition at line 113 of file mdtValue.h.
bool mdtValueDouble::operator<= (const mdtValueDouble & other) const inline noexcept
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Todo:
Use functions from cmath !
Definition at line 127 of file mdtValue.h.
bool mdtValueDouble::operator== (const mdtValueDouble & other) const noexcept
Comparaison operator.
Notes:
Both values are equal if value and flags are equal.
if one (or both) value is null, they are not considered equal (Same rule as IEEE 754 NaN)
Todo:
Use functions from cmath !
Definition at line 86 of file mdtValue.cpp.
bool mdtValueDouble::operator> (const mdtValueDouble & other) const inline noexcept
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Todo:
Use functions from cmath !
Definition at line 144 of file mdtValue.h.
bool mdtValueDouble::operator>= (const mdtValueDouble & other) const inline noexcept
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Todo:
Use functions from cmath !
Definition at line 158 of file mdtValue.h.
void mdtValueDouble::setValue (double value, bool isOl = false) noexcept
Set value.
Parameters
value Value to store
isOl Force OL flag to be set. If value is >= 0.0 , +OL is set, else -OL will be set
Todo:
Use functions from cmath !
Definition at line 50 of file mdtValue.cpp.
Referenced by mdtCodecScpi::decodeValueDouble().
double mdtValueDouble::value () const inline noexcept
Get value.
Definition at line 75 of file mdtValue.h.
Referenced by mdtCodecScpi::decodeFunctionParameters(), mdtTtAbstractTestNodeCalibrationTool::isInRange(), operator<<(), and mdtTtTestCableOffsetTool::runOffsetReset().
The documentation for this class was generated from the following files:
src/mdtutils/mdtValue.h
src/mdtutils/mdtValue.cpp