Multi diag tools: mdtMvColumnSelectionDialog Class Reference
mdtMvColumnSelectionDialog Class Reference
Let the user manage fields to display in table view.
#include <mdtMvColumnSelectionDialog.h>
Public Member Functions
mdtMvColumnSelectionDialog (QWidget *parent, QAbstractTableModel *model, QTableView *view)
Constructor.
void accept ()
Apply new setup and close dialog.
Public Member Functions inherited from mdtItemsSelectorDialog
mdtItemsSelectorDialog (QWidget *parent=0)
Constructor.
~mdtItemsSelectorDialog ()
Destructor.
void clear ()
Clear dialog.
void setSortOptionEnabled (bool enabled)
Enable/diseable sort option.
void setAvailableItemsLabelText (const QString &text)
Set the Available items label text.
void setAvailableItems (const QList< mdtItemsSelectorDialogItem > &items)
Set the Available items.
void setSelectedItemsLabelText (const QString &text)
Set the selected items label text.
void setSelectedItems (const QList< mdtItemsSelectorDialogItem > &items)
Set the Available items.
const QList
< mdtItemsSelectorDialogItem > & selectedItems () const
Get list of selected items.
QStringList selectedItemsTexts () const
Get list of selected items texts.
QStringList selectedItemsNames () const
Get list of selected items names.
const QList
< mdtItemsSelectorDialogItem > & notSelectedItems () const
Get list of not selected items.
Detailed Description
Let the user manage fields to display in table view.
Definition at line 32 of file mdtMvColumnSelectionDialog.h.
Constructor & Destructor Documentation
mdtMvColumnSelectionDialog::mdtMvColumnSelectionDialog (QWidget * parent, QAbstractTableModel * model, QTableView * view)
Constructor.
Precondition
model and view must be valid.
Definition at line 34 of file mdtMvColumnSelectionDialog.cpp.
References mdtItemsSelectorDialog::setAvailableItemsLabelText(), mdtItemsSelectorDialog::setSelectedItemsLabelText(), and mdtItemsSelectorDialog::setSortOptionEnabled().
Member Function Documentation
void mdtMvColumnSelectionDialog::accept ()
Apply new setup and close dialog.
Definition at line 51 of file mdtMvColumnSelectionDialog.cpp.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtMvColumnSelectionDialog.h
src/mdtutilsgui/mdtMvColumnSelectionDialog.cpp