Multi diag tools: mdtDeviceModbusWagoModule Class Reference
mdtDeviceModbusWagoModule Class Reference
Helper class for Wago modules detection and setup.
#include <mdtDeviceModbusWagoModule.h>
Public Types
enum type_t {
Unknown, AnalogInputs, AnalogOutputs, DigitalInputs,
DigitalOutputs, DigitalInputsOutputs
}
Module type.
Public Member Functions
mdtDeviceModbusWagoModule (bool autoDeleteIos, mdtDeviceModbusWago *device)
Constructor.
virtual ~mdtDeviceModbusWagoModule ()
Destructor.
void clear (bool forceDeleteIos=false)
Clear I/O module.
bool setupFromRegisterWord (quint16 word)
Setup module.
virtual void updateAddresses (int firstAiAddress, int firstAoAddressRead, int firstAoAddressWrite, int firstDiAddress, int firstDoAddressRead, int firstDoAddressWrite)
Update addresses of the module.
int firstAiAddress () const
Get first address of module's analog inputs process image.
virtual int lastAiAddress () const
Get last address of module's analog inputs process image.
virtual int nextModuleFirstAiAddress () const
Get first address for next module in analog inputs process image.
int firstAoAddressRead () const
Get first address of module's analog outputs process image for read access.
virtual int lastAoAddressRead () const
Get last address of module's analog outputs process image for read access.
virtual int nextModuleFirstAoAddressRead () const
Get first address for next module in analog outputs process image for read access.
int firstAoAddressWrite () const
Get first address of module's analog outputs process image for write access.
virtual int lastAoAddressWrite () const
Get last address of module's analog outputs process image for write access.
virtual int nextModuleFirstAoAddressWrite () const
Get first address for next module in digital outputs process image for write access.
int firstDiAddress () const
Get first address of module's digital inputs process image.
virtual int lastDiAddress () const
Get last address of module's digital inputs process image.
virtual int nextModuleFirstDiAddress () const
Get first address for next module in digital inputs process image.
int firstDoAddressRead () const
Get first address of module's digital outputs process image for read access.
virtual int lastDoAddressRead () const
Get last address of module's digital outputs process image for read access.
virtual int nextModuleFirstDoAddressRead () const
Get first address for next module in digital outputs process image for read access.
int firstDoAddressWrite () const
Get first address of module's digital outputs process image for write access.
virtual int lastDoAddressWrite () const
Get last address of module's digital outputs process image for write access.
virtual int nextModuleFirstDoAddressWrite () const
Get first address for next module in digital outputs process image for write access.
const QList< mdtAnalogIo * > & analogInputs ()
Access internal analog inputs.
const QList< mdtAnalogIo * > & analogOutputs ()
Access internal analog outputs.
const QList< mdtDigitalIo * > & digitalInputs ()
Access internal digital inputs.
const QList< mdtDigitalIo * > & digitalOutputs ()
Access internal digital outputs.
type_t type () const
Get module type.
int partNumber () const
QString typeText() const;.
QString partNumberText () const
Get text version of part number.
QString deviceName ()
Get device name.
Protected Member Functions
void addAnalogInput (mdtAnalogIo *aio)
Add a analog input.
void addAnalogOutput (mdtAnalogIo *aio)
Add a analog output.
void addDigitalInput (mdtDigitalIo *dio)
Add a digital input.
void addDigitalOutput (mdtDigitalIo *dio)
Add a digital output.
void addRegisters (int channelCount, int firstAddressRead, int firstAddressWrite)
Add registers.
void clearRegisters ()
Clear registers.
int channelCountRegisters () const
Get number of channels regarding registers.
quint8 statusByte (int channel) const
Get the status byte for given channel.
void setControlByte (int channel, quint8 byte)
Set the control byte for given channel.
quint8 controlByte (int channel) const
Get the control byte for given channel.
void setRegisterDataWord (int channel, quint16 word)
Set register data word for given channel.
quint16 registerDataWord (int channel) const
Get register data word for given channel.
void setRegisterDataBytes (int channel, quint8 byteD1, quint8 byteD0)
Set register data bytes for given channel.
quint8 registerDataByteD1 (int channel)
Get register data byte D1 or D3 or ...
quint8 registerDataByteD0 (int channel)
Get register data byte D0 or D2 or ...
bool readRegisters (int firstChannel, int lastChannel, bool needDeviceSetupState)
Read register bytes for given range of channels.
bool writeRegisters (int firstChannel, int lastChannel, bool needDeviceSetupState)
Write register bytes for given range of channels.
bool readStatusBytes (int firstChannel, int lastChannel, bool needDeviceSetupState)
Read status byte for given range of channels.
bool writeControlBytes (int firstChannel, int lastChannel, bool needDeviceSetupState)
Write control byte for given range of channels.
void wait (int ms)
Wait some time.
virtual QVariant analogInputValueMin (int partNumber, int channel) const
Get the min value of a range of analog inputs.
virtual QVariant analogOutputValueMin (int partNumber, int channel) const
Get the min value of a range of analog outputs.
virtual QVariant analogInputValueMax (int partNumber, int channel) const
Get the max value of a range of analog inputs.
virtual QVariant analogOutputValueMax (int partNumber, int channel) const
Get the max value of a range of analog outputs.
virtual int analogInputValueBitsCount (int partNumber, int channel) const
Get the number of bits (including sign bit) used to represent a value of analog inputs.
virtual int analogOutputValueBitsCount (int partNumber, int channel) const
Get the number of bits (including sign bit) used to represent a value of analog outputs.
virtual int analogInputValueLsbIndex (int partNumber, int channel) const
Get index of the first bit (LSB) that represents the value of analog inputs.
virtual int analogOutputValueLsbIndex (int partNumber, int channel) const
Get index of the first bit (LSB) that represents the value of analog outputs.
virtual QVariant analogInputValueSigned (int partNumber, int channel) const
Check if a analog inputs returns a signed value or not.
virtual QVariant analogOutputValueSigned (int partNumber, int channel) const
Check if a analog outputs returns a signed value or not.
virtual QVariant analogInputValueScaledFromMinToMax (int partNumber, int channel) const
Check if analog input's value is scaled from minimum to maximum.
virtual QVariant analogOutputValueScaledFromMinToMax (int partNumber, int channel) const
Check if analog output's value is scaled from minimum to maximum.
virtual QVariant analogInputValueConversionFactor (int partNumber, int channel) const
Get analog input's conversion factor.
virtual QVariant analogOutputValueConversionFactor (int partNumber, int channel) const
Get analog output's conversion factor.
virtual int analogInputsCount (int partNumber) const
Get number of analog inputs.
virtual int analogOutputsCount (int partNumber) const
Get number of analog outputs.
virtual QString analogInputUnit (int partNumber, int channel) const
Get unit of a analog inputs (V, A, ...)
virtual QString analogOutputUnit (int partNumber, int channel) const
Get unit of a analog outputs (V, A, ...)
int digitalInputsProcessImageSize (quint16 word) const
Get size of digital inputs process image.
virtual int digitalInputsCount (quint16 word) const
Get the number of digital inputs.
int digitalOutputsProcessImageSize (quint16 word) const
Get size of digital outputs process image.
virtual int digitalOutputsCount (quint16 word) const
Get the number of digital outputs.
Detailed Description
Helper class for Wago modules detection and setup.
Definition at line 35 of file mdtDeviceModbusWagoModule.h.
Member Enumeration Documentation
enum mdtDeviceModbusWagoModule::type_t
Module type.
Enumerator
Unknown
Unknown module type
AnalogInputs
Analog inputs module
AnalogOutputs
Analog outputs module
DigitalInputs
Digital inputs module
DigitalOutputs
Digital outputs module
DigitalInputsOutputs
Module with digital inputs and outputs
Definition at line 41 of file mdtDeviceModbusWagoModule.h.
Constructor & Destructor Documentation
mdtDeviceModbusWagoModule::mdtDeviceModbusWagoModule (bool autoDeleteIos, mdtDeviceModbusWago * device)
Constructor.
The module will have all addresses set to 0.
Parameters
autoDeleteIos If true, internally created I/O's are deleted when this object is destroyed
device Pointer to device (used for register service access)
Precondition
device must be a valid pointer
Definition at line 30 of file mdtDeviceModbusWagoModule.cpp.
References Unknown.
mdtDeviceModbusWagoModule::~mdtDeviceModbusWagoModule () virtual
Destructor.
If autoDeleteIos is true, internal I/O's are deleted
Definition at line 46 of file mdtDeviceModbusWagoModule.cpp.
References clear().
Member Function Documentation
void mdtDeviceModbusWagoModule::addAnalogInput (mdtAnalogIo * aio) protected
Add a analog input.
Precondition
aio must be a valid pointer
Definition at line 308 of file mdtDeviceModbusWagoModule.cpp.
void mdtDeviceModbusWagoModule::addAnalogOutput (mdtAnalogIo * aio) protected
Add a analog output.
Precondition
aio must be a valid pointer
Definition at line 315 of file mdtDeviceModbusWagoModule.cpp.
void mdtDeviceModbusWagoModule::addDigitalInput (mdtDigitalIo * dio) protected
Add a digital input.
Precondition
dio must be a valid pointer
Definition at line 322 of file mdtDeviceModbusWagoModule.cpp.
void mdtDeviceModbusWagoModule::addDigitalOutput (mdtDigitalIo * dio) protected
Add a digital output.
Precondition
dio must be a valid pointer
Definition at line 329 of file mdtDeviceModbusWagoModule.cpp.
void mdtDeviceModbusWagoModule::addRegisters (int channelCount, int firstAddressRead, int firstAddressWrite) protected
Add registers.
Will add control byte, status byte and register data for given channelCount
Definition at line 336 of file mdtDeviceModbusWagoModule.cpp.
const QList< mdtAnalogIo * > & mdtDeviceModbusWagoModule::analogInputs ()
Access internal analog inputs.
Definition at line 263 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos(), and mdtDeviceModbusWagoModuleRtd::setIoCount().
int mdtDeviceModbusWagoModule::analogInputsCount (int partNumber) const protected virtual
Get number of analog inputs.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
Returns
Number of I/O's or -1 for unknown module.
Definition at line 786 of file mdtDeviceModbusWagoModule.cpp.
QString mdtDeviceModbusWagoModule::analogInputUnit (int partNumber, int channel) const protected virtual
Get unit of a analog inputs (V, A, ...)
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
channel Some special module supports different data per channel, so channel must be given here
Returns
Unit of module, or a empty string for unknown module.
Definition at line 818 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::analogInputValueBitsCount (int partNumber, int channel) const protected virtual
Get the number of bits (including sign bit) used to represent a value of analog inputs.
The resolution of each analog module is not the same. For example, the 750-457 has a resolution of 13 bits.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
channel Some special module supports different data per channel, so channel must be given here
Returns
bits count used for value, or -1 for a unknown module.
Definition at line 666 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogInputValueConversionFactor (int partNumber, int channel) const protected virtual
Get analog input's conversion factor.
For example, RTD module 750-464 has a conversion factor of 0.1 for channel configured as Pt100
Parameters
partNumber The right part of Wago part number (f.ex. 464 if module is a 750-464).
channel Some special module supports different data per channel, so channel must be given here
Returns
Scale factor for given input. For a unknown module, a invalid QVariant is returned.
Definition at line 762 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::analogInputValueLsbIndex (int partNumber, int channel) const protected virtual
Get index of the first bit (LSB) that represents the value of analog inputs.
Some modules have bits used for other purprose than value. At exemple, for module 750-457, the LSB index is 3.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
channel Some special module supports different data per channel, so channel must be given here
Returns
Index of LSB of value, or -1 for unknown module.
Definition at line 690 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogInputValueMax (int partNumber, int channel) const protected virtual
Get the max value of a range of analog inputs.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
channel Some special module supports different data per channel, so channel must be given here
Returns
The max. value in floating format. If partNumber is unknow, a invalid QVariant is returned.
Definition at line 642 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogInputValueMin (int partNumber, int channel) const protected virtual
Get the min value of a range of analog inputs.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
channel Some special module supports different data per channel, so channel must be given here
Returns
The min. value in floating format. If partNumber is unknow, a invalid QVariant is returned.
Definition at line 618 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogInputValueScaledFromMinToMax (int partNumber, int channel) const protected virtual
Check if analog input's value is scaled from minimum to maximum.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
channel Some special module supports different data per channel, so channel must be given here
Returns
True if module's representation is scaled from minimum to maximum, false if not. For a unknown module, a invalid QVariant is returned.
Definition at line 738 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogInputValueSigned (int partNumber, int channel) const protected virtual
Check if a analog inputs returns a signed value or not.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
channel Some special module supports different data per channel, so channel must be given here
Returns
True if module's representation is signed, false if not. For a unknown module, a invalid QVariant is returned.
Definition at line 714 of file mdtDeviceModbusWagoModule.cpp.
const QList< mdtAnalogIo * > & mdtDeviceModbusWagoModule::analogOutputs ()
Access internal analog outputs.
Definition at line 268 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::analogOutputsCount (int partNumber) const protected virtual
Get number of analog outputs.
Parameters
partNumber The right part of Wago part number (f.ex. 457 if module is a 750-457).
Returns
Number of I/O's or -1 for unknown module.
Definition at line 802 of file mdtDeviceModbusWagoModule.cpp.
QString mdtDeviceModbusWagoModule::analogOutputUnit (int partNumber, int channel) const protected virtual
Get unit of a analog outputs (V, A, ...)
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
Unit of module, or a empty string for unknown module.
Definition at line 832 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::analogOutputValueBitsCount (int partNumber, int channel) const protected virtual
Get the number of bits (including sign bit) used to represent a value of analog outputs.
The resolution of each analog module is not the same. For example, the 750-550 has a resolution of 12 bits.
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
bits count used for value, or -1 for a unknown module.
Definition at line 680 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogOutputValueConversionFactor (int partNumber, int channel) const protected virtual
Get analog output's conversion factor.
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
Scale factor for given output. For a unknown module, a invalid QVariant is returned.
Definition at line 776 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::analogOutputValueLsbIndex (int partNumber, int channel) const protected virtual
Get index of the first bit (LSB) that represents the value of analog outputs.
Some modules have bits used for other purprose than value. At exemple, for module 750-550, the LSB index is 3.
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
Index of LSB of value, or -1 for unknown module.
Definition at line 704 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogOutputValueMax (int partNumber, int channel) const protected virtual
Get the max value of a range of analog outputs.
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
The max. value in floating format. If partNumber is unknow, a invalid QVariant is returned.
Definition at line 656 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogOutputValueMin (int partNumber, int channel) const protected virtual
Get the min value of a range of analog outputs.
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
The min. value in floating format. If partNumber is unknow, a invalid QVariant is returned.
Definition at line 632 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogOutputValueScaledFromMinToMax (int partNumber, int channel) const protected virtual
Check if analog output's value is scaled from minimum to maximum.
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
True if module's representation is scaled from minimum to maximum, false if not. For a unknown module, a invalid QVariant is returned.
Definition at line 752 of file mdtDeviceModbusWagoModule.cpp.
QVariant mdtDeviceModbusWagoModule::analogOutputValueSigned (int partNumber, int channel) const protected virtual
Check if a analog outputs returns a signed value or not.
Parameters
partNumber The right part of Wago part number (f.ex. 550 if module is a 750-550).
channel Some special module supports different data per channel, so channel must be given here
Returns
True if module's representation is signed, false if not. For a unknown module, a invalid QVariant is returned.
Definition at line 728 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::channelCountRegisters () const protected
Get number of channels regarding registers.
During I/O detection or channel count setup, register count can be incoherent with I/O count.
This method will return channel count only regarding number of control/status/data register sizes.
Definition at line 361 of file mdtDeviceModbusWagoModule.cpp.
void mdtDeviceModbusWagoModule::clear (bool forceDeleteIos = false)
Clear I/O module.
If autoDeleteIos is set, memory is freed for internal I/O (mdtAbstractIo pointers will also become invalid)
Note that all addresses will be reset to 0 after a clear.
Parameters
forceDeleteIos Will delete I/O's undependant of autoDeleteIos flag.
Definition at line 51 of file mdtDeviceModbusWagoModule.cpp.
References clearRegisters(), and Unknown.
Referenced by mdtDeviceModbusWago::detectIos(), setupFromRegisterWord(), and ~mdtDeviceModbusWagoModule().
void mdtDeviceModbusWagoModule::clearRegisters () protected
Clear registers.
Will remove control bytes, status bytes and data registers.
Definition at line 354 of file mdtDeviceModbusWagoModule.cpp.
Referenced by clear().
quint8 mdtDeviceModbusWagoModule::controlByte (int channel) const protected
Get the control byte for given channel.
See Also
setControlByte()
Precondition
channel must be in a valid range
Definition at line 385 of file mdtDeviceModbusWagoModule.cpp.
QString mdtDeviceModbusWagoModule::deviceName ()
Get device name.
Definition at line 301 of file mdtDeviceModbusWagoModule.cpp.
References mdtDevice::name().
const QList< mdtDigitalIo * > & mdtDeviceModbusWagoModule::digitalInputs ()
Access internal digital inputs.
Definition at line 273 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::digitalInputsCount (quint16 word) const protected virtual
Get the number of digital inputs.
This implementation returns value from digitalInputsProcessImageSize() . This method can be re-implemented for special modules.
Definition at line 852 of file mdtDeviceModbusWagoModule.cpp.
References digitalInputsProcessImageSize().
int mdtDeviceModbusWagoModule::digitalInputsProcessImageSize (quint16 word) const protected
Get size of digital inputs process image.
For common digital inputs modules, this will match with the number of digital inputs. For special modules that have status/iformation mapped in porecess image, these are also include in the result.
Parameters
word The identification word (see Wago fieldbus coupler doc, part of register 0x2030 for details).
Returns
Digital inputs process image size [bits] or -1 on unknown description.
Definition at line 842 of file mdtDeviceModbusWagoModule.cpp.
Referenced by digitalInputsCount().
const QList< mdtDigitalIo * > & mdtDeviceModbusWagoModule::digitalOutputs ()
Access internal digital outputs.
Definition at line 278 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::digitalOutputsCount (quint16 word) const protected virtual
Get the number of digital outputs.
This implementation returns value from digitalOutputsProcessImageSize() . This method can be re-implemented for special modules.
Definition at line 867 of file mdtDeviceModbusWagoModule.cpp.
References digitalOutputsProcessImageSize().
int mdtDeviceModbusWagoModule::digitalOutputsProcessImageSize (quint16 word) const protected
Get size of digital outputs process image.
For common digital outputs modules, this will match with the number of digital outputs. For special modules that have status/iformation mapped in porecess image, these are also include in the result.
Parameters
word The identification word (see Wago fieldbus coupler doc, part of register 0x2030 for details).
Returns
Digital outputs process image size [bits] or -1 on unknown description.
Definition at line 857 of file mdtDeviceModbusWagoModule.cpp.
Referenced by digitalOutputsCount().
int mdtDeviceModbusWagoModule::firstAiAddress () const
Get first address of module's analog inputs process image.
Definition at line 149 of file mdtDeviceModbusWagoModule.cpp.
Referenced by updateAddresses().
int mdtDeviceModbusWagoModule::firstAoAddressRead () const
Get first address of module's analog outputs process image for read access.
Definition at line 168 of file mdtDeviceModbusWagoModule.cpp.
Referenced by updateAddresses().
int mdtDeviceModbusWagoModule::firstAoAddressWrite () const
Get first address of module's analog outputs process image for write access.
Definition at line 187 of file mdtDeviceModbusWagoModule.cpp.
Referenced by updateAddresses().
int mdtDeviceModbusWagoModule::firstDiAddress () const
Get first address of module's digital inputs process image.
Definition at line 206 of file mdtDeviceModbusWagoModule.cpp.
Referenced by updateAddresses().
int mdtDeviceModbusWagoModule::firstDoAddressRead () const
Get first address of module's digital outputs process image for read access.
Definition at line 225 of file mdtDeviceModbusWagoModule.cpp.
Referenced by updateAddresses().
int mdtDeviceModbusWagoModule::firstDoAddressWrite () const
Get first address of module's digital outputs process image for write access.
Definition at line 244 of file mdtDeviceModbusWagoModule.cpp.
Referenced by updateAddresses().
int mdtDeviceModbusWagoModule::lastAiAddress () const virtual
Get last address of module's analog inputs process image.
Definition at line 154 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::lastAoAddressRead () const virtual
Get last address of module's analog outputs process image for read access.
Definition at line 173 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::lastAoAddressWrite () const virtual
Get last address of module's analog outputs process image for write access.
Definition at line 192 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::lastDiAddress () const virtual
Get last address of module's digital inputs process image.
Definition at line 211 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::lastDoAddressRead () const virtual
Get last address of module's digital outputs process image for read access.
Definition at line 230 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::lastDoAddressWrite () const virtual
Get last address of module's digital outputs process image for write access.
Definition at line 249 of file mdtDeviceModbusWagoModule.cpp.
int mdtDeviceModbusWagoModule::nextModuleFirstAiAddress () const virtual
Get first address for next module in analog inputs process image.
Definition at line 163 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::nextModuleFirstAoAddressRead () const virtual
Get first address for next module in analog outputs process image for read access.
Definition at line 182 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::nextModuleFirstAoAddressWrite () const virtual
Get first address for next module in digital outputs process image for write access.
Definition at line 201 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::nextModuleFirstDiAddress () const virtual
Get first address for next module in digital inputs process image.
Definition at line 220 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::nextModuleFirstDoAddressRead () const virtual
Get first address for next module in digital outputs process image for read access.
Definition at line 239 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::nextModuleFirstDoAddressWrite () const virtual
Get first address for next module in digital outputs process image for write access.
Definition at line 258 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
int mdtDeviceModbusWagoModule::partNumber () const
QString typeText() const;.
Get module's part number
Part number is the 3 last digits of wago article number. F.ex. : for the 750-457 , this method will return 457. Note: part number is only available for analog I/O module.
Definition at line 288 of file mdtDeviceModbusWagoModule.cpp.
QString mdtDeviceModbusWagoModule::partNumberText () const
Get text version of part number.
See Also
partNumber()
Definition at line 293 of file mdtDeviceModbusWagoModule.cpp.
bool mdtDeviceModbusWagoModule::readRegisters (int firstChannel, int lastChannel, bool needDeviceSetupState) protected
Read register bytes for given range of channels.
Will read status (Sx) and data (Dx) bytes from physical module and update internally cached values.
Note: this method will not send a specific query. For this, control byte must be setup regarding specific module and sent to device with writeControlBytes() first.
Precondition
firstChannel and lastChannel must be in a valid range
Todo:
Implement needDeviceSetupState
Definition at line 433 of file mdtDeviceModbusWagoModule.cpp.
References mdtError::Error, mdtDeviceModbus::getRegisterValues(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtDevice::name(), and mdtDeviceModbus::registerValues().
bool mdtDeviceModbusWagoModule::readStatusBytes (int firstChannel, int lastChannel, bool needDeviceSetupState) protected
Read status byte for given range of channels.
Will read status byte (Sx) from physical module and update internally cached value.
See Also
statusByte()
Precondition
firstChannel and lastChannel must be in a valid range
Todo:
Implement needDeviceSetupState
Definition at line 533 of file mdtDeviceModbusWagoModule.cpp.
References mdtError::Error, mdtDeviceModbus::getRegisterValues(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtDevice::name(), and mdtDeviceModbus::registerValues().
quint8 mdtDeviceModbusWagoModule::registerDataByteD0 (int channel) protected
Get register data byte D0 or D2 or ...
See Also
setRegisterDataBytes()
Precondition
channel must be in a valid range
Definition at line 424 of file mdtDeviceModbusWagoModule.cpp.
quint8 mdtDeviceModbusWagoModule::registerDataByteD1 (int channel) protected
Get register data byte D1 or D3 or ...
See Also
setRegisterDataBytes()
Precondition
channel must be in a valid range
Definition at line 416 of file mdtDeviceModbusWagoModule.cpp.
quint16 mdtDeviceModbusWagoModule::registerDataWord (int channel) const protected
Get register data word for given channel.
See Also
setRegisterDataWord()
Definition at line 400 of file mdtDeviceModbusWagoModule.cpp.
void mdtDeviceModbusWagoModule::setControlByte (int channel, quint8 byte) protected
Set the control byte for given channel.
For channel 0, control byte C0 is set, for channel 1, control byte C1 is set , ...
See Wago documentation about register communication for details.
Note: this method set only the cached control byte, to set value to physical module, use writeControlBytes().
Precondition
channel must be in a valid range
Definition at line 376 of file mdtDeviceModbusWagoModule.cpp.
void mdtDeviceModbusWagoModule::setRegisterDataBytes (int channel, quint8 byteD1, quint8 byteD0) protected
Set register data bytes for given channel.
For channel 0, byteD0 is set to byte D0, byteD1 to byte D1, for channel 1, byteD0 to byte D2, byteD1 to byte D3, ...
See Wago documentation about register communication for details.
Note: this method only set cached register data bytes, to set them to physical module, use writeRegisters() .
Precondition
channel must be in a valid range
Definition at line 408 of file mdtDeviceModbusWagoModule.cpp.
References setRegisterDataWord().
void mdtDeviceModbusWagoModule::setRegisterDataWord (int channel, quint16 word) protected
Set register data word for given channel.
For channel 0, register data bytes D0 and D1 are set, for channel 1, register data bytes D2 and D3 are set, ...
See Wago documentation about register communication for details.
Note: this method only set cached register data bytes, to set them to physical module, use writeRegisters() .
Precondition
channel must be in a valid range
Definition at line 392 of file mdtDeviceModbusWagoModule.cpp.
Referenced by setRegisterDataBytes().
bool mdtDeviceModbusWagoModule::setupFromRegisterWord (quint16 word)
Setup module.
During I/O detection, the fieldbus coupler give a word for each module attached on its KBUS. This word contains several informations such as a part number (for analog I/O module) or flag bits (for digital I/O module).
This method will use this word do create internally I/O's based on mdtAbstractIo and setup them on the base of known parameters (range, type, etc...).
Note that no absolute addressing is done at this step. Call updateAddresses() for this.
Some special modules need to communicate with fieldbus coupler to access register service. To get setup during I/O detection, use getSpecialModuleSetup() instead of this method.
Todo:
Adapt
Parameters
word Word that contains I/O informations.
Definition at line 74 of file mdtDeviceModbusWagoModule.cpp.
References clear().
Referenced by mdtDeviceModbusWago::detectIos().
quint8 mdtDeviceModbusWagoModule::statusByte (int channel) const protected
Get the status byte for given channel.
For channel 0, status byte S0 is returned, for channel 1, status byte S1 , ...
See Wago documentation about register communication for details.
Note: this method returns only the cached status byte, to get value from physical module, use readStatusBytes() first.
Precondition
channel must be in a valid range
Definition at line 369 of file mdtDeviceModbusWagoModule.cpp.
mdtDeviceModbusWagoModule::type_t mdtDeviceModbusWagoModule::type () const
Get module type.
Definition at line 283 of file mdtDeviceModbusWagoModule.cpp.
Referenced by mdtDeviceModbusWago::detectIos(), and mdtDeviceModbusWagoModuleRtd::setSensorType().
void mdtDeviceModbusWagoModule::updateAddresses (int firstAiAddress, int firstAoAddressRead, int firstAoAddressWrite, int firstDiAddress, int firstDoAddressRead, int firstDoAddressWrite) virtual
Update addresses of the module.
If no I/O was set, this method will store given addresses. This can be usefull for some special modules witch needs to communicate with fieldbus during setup.
However, the normal way is to stup the module with setupFromRegisterWord() first, then call this method to address I/Os.
This default implementation will address all present I/Os in a linear way.
Parameters
firstAiAddress First address in the analog inputs process image.
firstAoAddressRead First address in the analog outputs process image for read access.
firstAoAddressWrite First address in the analog outputs process image for write access.
firstDiAddress First address in the digital inputs process image.
firstDoAddressRead First address in the digital outputs process image for read access.
firstDoAddressWrite First address in the digital outputs process image for write access.
Definition at line 94 of file mdtDeviceModbusWagoModule.cpp.
References firstAiAddress(), firstAoAddressRead(), firstAoAddressWrite(), firstDiAddress(), firstDoAddressRead(), and firstDoAddressWrite().
Referenced by mdtDeviceModbusWago::detectIos().
void mdtDeviceModbusWagoModule::wait (int ms) protected
Wait some time.
See Also
mdtDevice::wait()
Definition at line 611 of file mdtDeviceModbusWagoModule.cpp.
References mdtDevice::wait().
bool mdtDeviceModbusWagoModule::writeControlBytes (int firstChannel, int lastChannel, bool needDeviceSetupState) protected
Write control byte for given range of channels.
Will write cached control byte (Cx) to physical module.
See Also
setControlByte()
Precondition
firstChannel and lastChannel must be in a valid range
Todo:
Implement needDeviceSetupState
Definition at line 577 of file mdtDeviceModbusWagoModule.cpp.
References mdtError::Error, MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtDevice::name(), and mdtDeviceModbus::setRegisterValues().
bool mdtDeviceModbusWagoModule::writeRegisters (int firstChannel, int lastChannel, bool needDeviceSetupState) protected
Write register bytes for given range of channels.
Will write cached control (Cx) and data (Dx) bytes to physical module.
Precondition
firstChannel and lastChannel must be in a valid range
Todo:
Implement needDeviceSetupState
Definition at line 493 of file mdtDeviceModbusWagoModule.cpp.
References mdtError::Error, MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtDevice::name(), and mdtDeviceModbus::setRegisterValues().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceModbusWagoModule.h
src/mdtdevice/mdtDeviceModbusWagoModule.cpp