Multi diag tools: mdtSqlRecord Class Reference
mdtSqlRecord Class Reference
Database record container class.
#include <mdtSqlRecord.h>
Public Member Functions
mdtSqlRecord ()
Constructor.
mdtSqlRecord (const QSqlRecord &sqlRecord)
Build a mdtSqlRecord on the base of a QSqlRecord.
virtual ~mdtSqlRecord ()
Destructor.
operator QSqlRecord ()
Get QSqlRecord version.
bool addField (const QString &fieldName, const QString &tableName, const QSqlDatabase &db)
Add a field to record.
bool addAllFields (const QString &tableName, const QSqlDatabase &db)
Add all fields of given table to record.
int count () const
Returns the number of fields in the record.
bool isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
QSqlField field (int index) const
Returns the field at position index.
QSqlField field (const QString &name) const
Returns the field called name.
int indexOf (const QString &name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
bool contains (const QString &name) const
Returns true if there is a field in the record called name; otherwise returns false.
QStringList fieldNames () const
Get a list with all field names.
bool hasValue (int fieldIndex) const
Check if a value was set.
bool hasValue (const QString &fieldName) const
Check if a value was set.
void setValue (int fieldIndex, const QVariant &val)
Set value.
void setValue (const QString &fieldName, const QVariant &val)
Set value.
QVariant value (int index) const
Returns the value of the field located at position index in the record.
QVariant value (const QString &name) const
Returns the value of the field called name in the record.
virtual void clear ()
Removes all the record's fields.
virtual void clearValues ()
Clear values.
mdtError lastError () const
Get last error.
QVector< int > fieldIndexesWithValue () const
Get a list with field indexes that have a value.
QString sqlForInsert (const QString &tableName) const
Get SQL statement for insertion with QSqlQuery.
QString sqlForUpdate (const QString &tableName, const QSqlRecord &matchData) const
Get SQL statement for update with QSqlQuery.
QString dataToUpdateInfo () const
Get information about data that has a value to update (for debug)
Static Public Member Functions
static QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes
mdtError pvLastError
Detailed Description
Database record container class.
This class can be useful to create data storage classes in application.
Based on QSqlRecord , all field attributes and values are stored as QSqlField objects.
To set a value, use setValue(int, const QVariant &) or setValue(const QString &, const QVariant &). To check if a value was set, use hasValue(int) or hasValue(const QString &). To clear values and hasValue flags, use clearValues().
A possible way to create a sub class could be:
Create fields that are relevant, using addField() , or addAllFields().
On error, use clear() (from QSqlRecord).
The user can also check if data record instance is valid by using isEmpty() (from QSqlRecord) and lastError().
Definition at line 49 of file mdtSqlRecord.h.
Constructor & Destructor Documentation
mdtSqlRecord::mdtSqlRecord ()
Constructor.
Definition at line 27 of file mdtSqlRecord.cpp.
Referenced by mdtClConnectorData::contactData().
mdtSqlRecord::mdtSqlRecord (const QSqlRecord & sqlRecord)
Build a mdtSqlRecord on the base of a QSqlRecord.
Definition at line 31 of file mdtSqlRecord.cpp.
mdtSqlRecord::~mdtSqlRecord () virtual
Destructor.
Definition at line 36 of file mdtSqlRecord.cpp.
Member Function Documentation
bool mdtSqlRecord::addAllFields (const QString & tableName, const QSqlDatabase & db)
Add all fields of given table to record.
Parameters
tableName Name of table in database.
db Database to use.
See Also
addField()
Definition at line 77 of file mdtSqlRecord.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtClArticle::addCableLink(), mdtClArticleLinkDialog::mdtClArticleLinkDialog(), mdtTtTestLinkData::setup(), mdtTtTestNodeUnitData::setup(), mdtClConnectorData::setup(), mdtClArticleConnectorData::setup(), mdtClArticleConnectionData::setup(), mdtClUnitConnectorData::setup(), mdtClLinkData::setup(), and mdtClUnitConnectionData::setup().
bool mdtSqlRecord::addField (const QString & fieldName, const QString & tableName, const QSqlDatabase & db)
Add a field to record.
Will use given db object and tableName to get requested fieldName attributes, and add it to fields list using QSqlRecord::append() method.
Parameters
fieldName Name of the field to add.
tableName Name of table in database (used to get fields attributes).
db Database to use. Pass a empty object (QSqlDatabase()) to use default database. (This parameter is used to get fields attributes).
Returns
False if database is closed, if the table or field does not exists. Error is also available with lastError().
Definition at line 46 of file mdtSqlRecord.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtClArticle::editLink(), and mdtTtBase::updateRecord().
void mdtSqlRecord::clear () virtual
Removes all the record's fields.
Reimplemented in mdtClUnitConnectorData, and mdtClArticleConnectorData.
Definition at line 134 of file mdtSqlRecord.cpp.
References mdtError::clear(), and pvLastError.
Referenced by mdtClArticleConnectorData::clear(), mdtClUnitConnectorData::clear(), mdtTtTestLinkData::setup(), and mdtClLinkData::setup().
void mdtSqlRecord::clearValues () virtual
Clear values.
Will clear value and hasValue flag for all fields.
Reimplemented in mdtClUnitConnectorData, mdtClLinkData, mdtClArticleConnectorData, and mdtTtTestNodeUnitData.
Definition at line 140 of file mdtSqlRecord.cpp.
References count().
Referenced by mdtClArticle::addConnectionDataListFromConnectorContactIdList(), mdtClUnit::addConnectionDataListFromConnectorContactIdList(), mdtTtTestNodeUnitData::clearValues(), mdtClArticleConnectorData::clearValues(), mdtClLinkData::clearValues(), mdtClUnitConnectorData::clearValues(), and mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList().
bool mdtSqlRecord::contains (const QString & name) const inline
Returns true if there is a field in the record called name; otherwise returns false.
Definition at line 117 of file mdtSqlRecord.h.
Referenced by mdtClArticleConnectorData::addConnectionData(), mdtClUnitConnectorData::addConnectionData(), mdtClConnectorData::addContactData(), mdtClArticleConnectorData::mdtClArticleConnectorData(), mdtClConnectorData::mdtClConnectorData(), mdtClUnitConnectionData::mdtClUnitConnectionData(), mdtClUnitConnectorData::mdtClUnitConnectorData(), mdtTtTestLinkData::mdtTtTestLinkData(), mdtTtTestNodeUnitData::mdtTtTestNodeUnitData(), mdtClArticleConnectionDialog::setData(), and mdtTtTestNodeUnitData::setUnitData().
int mdtSqlRecord::count () const inline
Returns the number of fields in the record.
Definition at line 93 of file mdtSqlRecord.h.
Referenced by clearValues(), fieldIndexesWithValue(), and fieldNames().
QString mdtSqlRecord::dataToUpdateInfo () const
Get information about data that has a value to update (for debug)
Definition at line 239 of file mdtSqlRecord.cpp.
References fieldIndexesWithValue().
Referenced by mdtTtBase::addRecord().
QSqlField mdtSqlRecord::field (int index) const inline
Returns the field at position index.
If the index is out of range, function returns a default-constructed value.
Definition at line 103 of file mdtSqlRecord.h.
Referenced by sqlForUpdate().
QSqlField mdtSqlRecord::field (const QString & name) const inline
Returns the field called name.
Definition at line 107 of file mdtSqlRecord.h.
QVector< int > mdtSqlRecord::fieldIndexesWithValue () const
Get a list with field indexes that have a value.
Note: each time this method is called, the list will be generated.
See Also
hasValue()
Definition at line 155 of file mdtSqlRecord.cpp.
References count(), and hasValue().
Referenced by mdtTtBase::addRecord(), dataToUpdateInfo(), sqlForInsert(), sqlForUpdate(), and mdtTtBase::updateRecord().
QStringList mdtSqlRecord::fieldNames () const
Get a list with all field names.
Definition at line 111 of file mdtSqlRecord.cpp.
References count().
bool mdtSqlRecord::hasValue (int fieldIndex) const inline
Check if a value was set.
By insertion or edition in database, it can be important to know if a field must be updated or not. Because a Null value can be valid, it's not possible to use this flag. This method returns true once a value was set in given field.
To clear this flag, use clearValues().
Note: internally, QSqlRecord::isGenerated() is used.
Definition at line 134 of file mdtSqlRecord.h.
Referenced by fieldIndexesWithValue().
bool mdtSqlRecord::hasValue (const QString & fieldName) const inline
Check if a value was set.
See Also
hasValue(int)
Definition at line 140 of file mdtSqlRecord.h.
int mdtSqlRecord::indexOf (const QString & name) const inline
Returns the position of the field called name within the record, or -1 if it cannot be found.
Field names are not case-sensitive. If more than one field matches, the first one is returned.
Definition at line 113 of file mdtSqlRecord.h.
Referenced by mdtClArticleConnectionData::mdtClArticleConnectionData(), mdtClLinkData::mdtClLinkData(), and mdtClUnitConnectionData::mdtClUnitConnectionData().
bool mdtSqlRecord::isEmpty () const inline
Returns true if there are no fields in the record; otherwise returns false.
Definition at line 97 of file mdtSqlRecord.h.
mdtError mdtSqlRecord::lastError () const
Get last error.
Definition at line 150 of file mdtSqlRecord.cpp.
References pvLastError.
Referenced by mdtClArticle::addCableLink(), mdtClArticle::addConnectionDataListFromConnectorContactIdList(), mdtClUnit::addConnectionDataListFromConnectorContactIdList(), mdtClArticle::editLink(), mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList(), mdtClArticleLinkDialog::mdtClArticleLinkDialog(), mdtTtTestLinkDialog::mdtTtTestLinkDialog(), mdtTtTestNodeUnitData::setup(), and mdtTtBase::updateRecord().
mdtSqlRecord::operator QSqlRecord ()
Get QSqlRecord version.
Definition at line 40 of file mdtSqlRecord.cpp.
void mdtSqlRecord::setValue (int fieldIndex, const QVariant & val)
Set value.
Set the hasValue flag and set value.
Definition at line 123 of file mdtSqlRecord.cpp.
Referenced by mdtClUnit::addArticleConnectorData(), mdtClArticle::addCableLink(), mdtClUnit::addConnection(), mdtClArticleConnectorData::addConnectionData(), mdtClArticle::addConnectionDataListFromConnectorContactIdList(), mdtClUnit::addConnectionDataListFromConnectorContactIdList(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtClConnectorData::addContactData(), mdtClArticle::editConnectorName(), mdtClUnit::editConnectorName(), mdtClArticle::editLink(), mdtClLink::getConnectionLinkListByName(), mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList(), mdtClUnitConnectionData::setArticleConnectionData(), mdtClUnitConnectorData::setArticleConnectorData(), mdtClArticleConnectorData::setConnectorData(), mdtClUnitConnectorData::setConnectorData(), mdtTtTestLinkDialog::setDutConnection(), mdtClLinkData::setEndConnectionData(), mdtClArticleLinkDialog::setEndConnectionId(), mdtClArticleLinkDialog::setLinkDirectionCode(), mdtClArticleLinkDialog::setLinkTypeCode(), mdtClLinkData::setStartConnectionData(), mdtClArticleLinkDialog::setStartConnectionId(), mdtTtTestLinkDialog::setTestConnection(), mdtTtTestNodeUnitData::setTestConnectionData(), mdtTtTestNodeUnitData::setUnitData(), mdtClArticleLinkDialog::setValue(), setValue(), and mdtTtBase::updateRecord().
void mdtSqlRecord::setValue (const QString & fieldName, const QVariant & val)
Set value.
See Also
setValue(int)
Definition at line 129 of file mdtSqlRecord.cpp.
References setValue().
QString mdtSqlRecord::sqlDataDelimiter (QVariant::Type type) static
Get SQL data delimiter for given data type.
Definition at line 229 of file mdtSqlRecord.cpp.
Referenced by mdtTtBase::sqlDataDelimiter(), and sqlForUpdate().
QString mdtSqlRecord::sqlForInsert (const QString & tableName) const
Get SQL statement for insertion with QSqlQuery.
Will generate SQL statement for insertion in given table name. The statement works with QSqlQuery values binding with positional placeholders. Example of a returned statement: INSERT INTO table (Id_PK, Name) VALUES (?, ?).
Only fields that have a value are added in SQL statement.
Definition at line 169 of file mdtSqlRecord.cpp.
References fieldIndexesWithValue().
Referenced by mdtTtBase::addRecord().
QString mdtSqlRecord::sqlForUpdate (const QString & tableName, const QSqlRecord & matchData) const
Get SQL statement for update with QSqlQuery.
Will generate SQL statement for update in given table name. The statement works with QSqlQuery values binding with positional placeholders. Example of a returned statement: UPDATE table SET Id_PK=?,Name=?.
Only fields that have a value are added in SQL statement.
Parameters
tableName Name of table to update.
matchData For each field in matchData, a condition of type fieldName=fieldValue is added. This will determine witch row to update.
Definition at line 195 of file mdtSqlRecord.cpp.
References field(), fieldIndexesWithValue(), and sqlDataDelimiter().
Referenced by mdtTtBase::updateRecord().
QVariant mdtSqlRecord::value (int index) const inline
Returns the value of the field located at position index in the record.
If index is out of bounds, an invalid QVariant is returned.
Definition at line 158 of file mdtSqlRecord.h.
Referenced by mdtClUnit::addArticleConnectorData(), mdtClUnit::addConnection(), mdtClArticleConnectorData::addConnectionData(), mdtClUnit::addConnectionDataListFromArticleConnectionIdList(), mdtClArticle::addConnectionDataListFromConnectorContactIdList(), mdtClUnit::addConnectionDataListFromConnectorContactIdList(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtClConnectorData::addContactData(), mdtTtBase::addRecord(), mdtClLinkData::addVehicleTypeLinkData(), mdtClLink::connectByContactName(), mdtClUnit::editConnection(), mdtClLink::getConnectionLinkListByName(), mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList(), mdtClUnitConnectionData::isBasedOnArticleConnection(), mdtClUnitConnectorData::isBasedOnArticleConnector(), mdtClArticleConnectorData::isBasedOnConnector(), mdtClUnitConnectorData::isBasedOnConnector(), mdtClUnit::removeConnection(), mdtClUnitConnectionData::setArticleConnectionData(), mdtClUnitConnectorData::setArticleConnectorData(), mdtClArticleConnectorData::setConnectorData(), mdtClUnitConnectorData::setConnectorData(), mdtClUnitConnectionDialog::setData(), mdtClLinkData::setEndConnectionData(), mdtClUnitLinkDialog::setLinkData(), mdtClLinkData::setStartConnectionData(), mdtTtTestNodeUnitData::setTestConnectionData(), mdtTtTestNodeUnitData::setUnitData(), and mdtTtBase::updateRecord().
QVariant mdtSqlRecord::value (const QString & name) const inline
Returns the value of the field called name in the record.
If field name does not exist an invalid variant is returned.
Definition at line 164 of file mdtSqlRecord.h.
Member Data Documentation
mdtError mdtSqlRecord::pvLastError protected
Definition at line 227 of file mdtSqlRecord.h.
Referenced by addAllFields(), addField(), clear(), lastError(), mdtClArticleConnectorData::setConnectionData(), mdtClUnitConnectorData::setConnectionData(), mdtClConnectorData::setContactData(), and mdtTtTestNodeUnitData::setup().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlRecord.h
src/mdtdatabase/mdtSqlRecord.cpp