Multi diag tools: mdtTtTestItemNodeSetupData Class Reference
mdtTtTestItemNodeSetupData Class Reference
Store setup data related to a test item.
#include <mdtTtTestItemNodeSetupData.h>
Public Member Functions
mdtTtTestItemNodeSetupData ()
Constructor.
void addNodeSetupData (const mdtTtTestNodeSetupData &data)
Add test node setup data.
void addNodeSetupData (int stepNumber, const QList< mdtTtTestNodeSetupData > &nodeSetupDataList)
Add a list of node setup data for given step.
void clear ()
Add test node unit setup data.
bool hasMoreStep () const
Check if more step is available.
mdtTtTestNodeSetupData getNextStep ()
Get next step.
QVariant currentDeviceIdentification () const
Get device identification for current step.
Detailed Description
Store setup data related to a test item.
Setup data are stored in TestNodeUnitSetup_tbl, and each entry is related to a test item.
Many setup data can be related to one test item.
Each setup data is related to a node unit, and also to a node.
To apply a setup for one test item, it can be necessary to configure nodes in a given order. For this, TestNodeUnitSetup_tbl contains a field (StepNumber).
Example of a setup:
Test item Node Node unit Value Step
1 Multimeter Source OFF 0
1 I/O module K1 ON 1
1 I/O module K2 ON 1
1 I/O module K5 ON 1
1 I/O module K6 ON 1
1 Multimeter Source 12V 1
1 Multimeter Source ON 2
In this example, we need to disable source first. Next, we setup the nodes. Finally, we enable source output.
To add setup data, use addNodeSetupData() or addNodeUnitSetupData().
To get setup data, use hasMoreStep() and getNextStep().
Definition at line 65 of file mdtTtTestItemNodeSetupData.h.
Constructor & Destructor Documentation
mdtTtTestItemNodeSetupData::mdtTtTestItemNodeSetupData ()
Constructor.
Definition at line 26 of file mdtTtTestItemNodeSetupData.cpp.
Member Function Documentation
void mdtTtTestItemNodeSetupData::addNodeSetupData (const mdtTtTestNodeSetupData & data)
Add test node setup data.
Will add node setup data, regarding deviceIdentification and stepNumber of each unit setup stored inside.
Deprecated:
Todo:
Obselete !
Definition at line 33 of file mdtTtTestItemNodeSetupData.cpp.
References mdtTtTestNodeSetupData::addUnitSetup(), mdtTtTestNodeSetupData::deviceIdentification(), mdtTtTestNodeSetupData::nodeIdentification(), mdtTtTestNodeSetupData::setDeviceIdentification(), mdtTtTestNodeSetupData::setNodeIdentification(), and mdtTtTestNodeSetupData::unitSetupList().
Referenced by mdtTtTest::getSetupData().
void mdtTtTestItemNodeSetupData::addNodeSetupData (int stepNumber, const QList< mdtTtTestNodeSetupData > & nodeSetupDataList)
Add a list of node setup data for given step.
Definition at line 70 of file mdtTtTestItemNodeSetupData.cpp.
void mdtTtTestItemNodeSetupData::clear ()
Add test node unit setup data.
void addNodeUnitSetupData(const mdtTtTestNodeUnitSetupData & data);
Clear data
void mdtTtTestItemNodeSetupData::addNodeUnitSetupData(const mdtTtTestNodeUnitSetupData & data) { }
Definition at line 87 of file mdtTtTestItemNodeSetupData.cpp.
References mdtTtTestNodeSetupData::clear().
QVariant mdtTtTestItemNodeSetupData::currentDeviceIdentification () const
Get device identification for current step.
Definition at line 105 of file mdtTtTestItemNodeSetupData.cpp.
References mdtTtTestNodeSetupData::deviceIdentification().
mdtTtTestNodeSetupData mdtTtTestItemNodeSetupData::getNextStep ()
Get next step.
Definition at line 95 of file mdtTtTestItemNodeSetupData.cpp.
bool mdtTtTestItemNodeSetupData::hasMoreStep () const inline
Check if more step is available.
Definition at line 96 of file mdtTtTestItemNodeSetupData.h.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestItemNodeSetupData.h
src/mdttools/mdttesttool/mdtTtTestItemNodeSetupData.cpp