Multi diag tools: mdtAbstractIoWidget Class Reference
mdtAbstractIoWidget Class Reference
Base class for I/O widgets.
#include <mdtAbstractIoWidget.h>
Public Member Functions
mdtAbstractIoWidget (QWidget *parent=0)
Constructor.
virtual ~mdtAbstractIoWidget ()
Protected Member Functions
void setIo (mdtAbstractIo *io)
Set the I/O object.
Protected Attributes
QLabel * lbLabel
QPushButton * pbDetails
Detailed Description
Base class for I/O widgets.
Definition at line 33 of file mdtAbstractIoWidget.h.
Constructor & Destructor Documentation
mdtAbstractIoWidget::mdtAbstractIoWidget (QWidget * parent = 0)
Constructor.
Note for subclass: Some widgets will be created in this consructor:
lbLabel: a QLabel wich display the short label of I/O and the label of I/O as tool tip
pbDetails: a QPushButton that will call a dialog wich displays details of I/O The subclass must place these labels into a layout.
Definition at line 29 of file mdtAbstractIoWidget.cpp.
References lbLabel, and pbDetails.
mdtAbstractIoWidget::~mdtAbstractIoWidget () virtual
Definition at line 48 of file mdtAbstractIoWidget.cpp.
Member Function Documentation
void mdtAbstractIoWidget::setIo (mdtAbstractIo * io) protected
Set the I/O object.
Make all needed connections with the I/O base object, so that widget is allways updated.
Used only by subclass.
Precondition
io must be a valid pointer.
Definition at line 53 of file mdtAbstractIoWidget.cpp.
References mdtAbstractIo::addressRead(), mdtAbstractIo::addressWrite(), mdtAbstractIo::details(), mdtAbstractIo::label(), and mdtAbstractIo::labelShort().
Referenced by mdtDigitalOutWidget::setIo(), mdtDigitalInWidget::setIo(), mdtAnalogInWidget::setIo(), and mdtAnalogOutWidget::setIo().
Member Data Documentation
QLabel* mdtAbstractIoWidget::lbLabel protected
Definition at line 65 of file mdtAbstractIoWidget.h.
Referenced by mdtAbstractIoWidget(), mdtAnalogInWidget::mdtAnalogInWidget(), mdtAnalogOutWidget::mdtAnalogOutWidget(), mdtDigitalInWidget::mdtDigitalInWidget(), and mdtDigitalOutWidget::mdtDigitalOutWidget().
QPushButton* mdtAbstractIoWidget::pbDetails protected
Definition at line 66 of file mdtAbstractIoWidget.h.
Referenced by mdtAbstractIoWidget(), mdtAnalogInWidget::mdtAnalogInWidget(), mdtAnalogOutWidget::mdtAnalogOutWidget(), mdtDigitalInWidget::mdtDigitalInWidget(), and mdtDigitalOutWidget::mdtDigitalOutWidget().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtAbstractIoWidget.h
src/mdtutilsgui/mdtAbstractIoWidget.cpp