Multi diag tools: mdtPortThreadHelperPort Class Reference
mdtPortThreadHelperPort Class Reference
Helper class for mdtPortThread and subclasses.
#include <mdtPortThreadHelperPort.h>
Public Member Functions
mdtPortThreadHelperPort (QObject *parent=0)
Constructor.
~mdtPortThreadHelperPort ()
Destructor.
mdtAbstractPort::error_t reconnect (bool notify)
Reconnect.
int readFromPort (bool emitNewFrameReaden)
Read data from port.
int writeDataToPort (int maxSize)
Write data to port.
mdtAbstractPort::error_t writeToPort (bool bytePerByteWrite, int interByteTime, int maxWriteTry=10)
Write a complete frame to port.
Public Member Functions inherited from mdtPortThreadHelper
mdtPortThreadHelper (QObject *parent=0)
Constructor.
virtual ~mdtPortThreadHelper ()
Destructor.
void setPort (mdtAbstractPort *port)
Set the port instance.
void setThread (mdtPortThread *thread)
Set the thread instance.
mdtAbstractPort::error_t handleCommonReadErrors (mdtAbstractPort::error_t portError)
Handle common read errors.
mdtAbstractPort::error_t handleCommonWriteErrors (mdtAbstractPort::error_t portError)
Handle common write errors.
mdtAbstractPort::error_t handleCommonReadWriteErrors (mdtAbstractPort::error_t portError)
Handle common read and write errors.
bool getNewFrameRead ()
Get a new frame for reading data from port.
void submitCurrentReadFrame (bool notify)
Submit current read frame.
void restoreCurrentReadFrameToPool ()
Restore current read frame to pool.
int submitReadenData (const char *data, int size, bool emitNewFrameReaden)
Store readen data into frame.
bool getNewFrameWrite ()
Get a new frame for writing data to port.
void restoreCurrentWriteFrameToPool ()
Restore current write frame to pool.
void setCurrentReadFrame (mdtFrame *frame)
Set current read frame.
mdtFrame * currentReadFrame ()
Get current read frame.
void setCurrentWriteFrame (mdtFrame *frame)
Set current write frame.
mdtFrame * currentWriteFrame ()
Get current write frame.
Additional Inherited Members
Signals inherited from mdtPortThreadHelper
void readProcessBegin ()
Emitted when a read process begins.
void writeProcessBegin ()
Emitted when a write process begins.
void newFrameReaden ()
Emited when a new frame is available.
Protected Slots inherited from mdtPortThreadHelper
virtual void requestWrite ()
Protected Member Functions inherited from mdtPortThreadHelper
void notifyError (mdtAbstractPort::error_t error, bool renotifySameError=false)
Calls mdtPortThread::notifyError()
Protected Attributes inherited from mdtPortThreadHelper
mdtAbstractPort * pvPort
mdtPortThread * pvThread
Detailed Description
Helper class for mdtPortThread and subclasses.
This class is helpfull for blocking API based only on mdtAbstractPort.
Definition at line 31 of file mdtPortThreadHelperPort.h.
Constructor & Destructor Documentation
mdtPortThreadHelperPort::mdtPortThreadHelperPort (QObject * parent = 0)
Constructor.
Definition at line 38 of file mdtPortThreadHelperPort.cpp.
mdtPortThreadHelperPort::~mdtPortThreadHelperPort ()
Destructor.
Definition at line 45 of file mdtPortThreadHelperPort.cpp.
Member Function Documentation
int mdtPortThreadHelperPort::readFromPort (bool emitNewFrameReaden)
Read data from port.
This is a helper method to read data from port and to store chunk of data into a frame.
Note about port mutex handling:
The port mutex must be locked before calling this method. Internally, it will be unlocked during wait, and will be locked again. So, the port mutex is allways locked when this method returns.
Parameters
emitNewFrameReaden If true, newFrameReaden() will be emitted each time a complete frame was generated.
Returns
The number of frames completed during the process. This can be helpful for query/reply protocols in witch the standard reply should be one frame. On error, one of the mdtAbstractPort::error_t is returned and thread must handle error itself.
Precondition
Port must be set with mdtPortThreadHelper::setPort().
Thread must be set with mdtPortThreadHelper::setThread().
Definition at line 60 of file mdtPortThreadHelperPort.cpp.
References mdtError::commit(), mdtPortThreadHelper::currentReadFrame(), mdtError::Error, mdtPortThreadHelper::getNewFrameRead(), MDT_ERROR_SET_SRC, MDT_MEMORY_ALLOC_ERROR, mdtPortThreadHelper::pvPort, mdtPortThreadHelper::pvThread, mdtAbstractPort::read(), mdtAbstractPort::ReadPoolEmpty, and mdtPortThreadHelper::submitReadenData().
mdtAbstractPort::error_t mdtPortThreadHelperPort::reconnect (bool notify) virtual
Reconnect.
This implementation calls mdtAbstractPort::reconnect() .
Precondition
Port must be set with mdtPortThreadHelper::setPort().
Thread must be set with mdtPortThreadHelper::setThread().
Reimplemented from mdtPortThreadHelper.
Definition at line 51 of file mdtPortThreadHelperPort.cpp.
References mdtPortThreadHelper::pvPort, mdtPortThreadHelper::pvThread, and mdtAbstractPort::reconnect().
int mdtPortThreadHelperPort::writeDataToPort (int maxSize)
Write data to port.
This is a helper method to write some data from a frame to the port.
Signal writeProcessBegin() is emitted.
Parameters
maxSize If >= 0, maxSize will be written, else the frame size will be considered.
Returns
Amount of bytes written or a mdtAbstractPort::error_t error.
Precondition
Port must be set with mdtPortThreadHelper::setPort().
Thread must be set with mdtPortThreadHelper::setThread().
Definition at line 95 of file mdtPortThreadHelperPort.cpp.
References mdtPortThreadHelper::currentWriteFrame(), mdtPortThreadHelper::pvPort, mdtPortThreadHelper::pvThread, mdtFrame::take(), mdtAbstractPort::write(), and mdtPortThreadHelper::writeProcessBegin().
Referenced by writeToPort().
mdtAbstractPort::error_t mdtPortThreadHelperPort::writeToPort (bool bytePerByteWrite, int interByteTime, int maxWriteTry = 10)
Write a complete frame to port.
This is a helper method to write a frame to the port. Internally, it will call mdtAbstractPort::waitEventWriteReady() before writing.
Note that frame will be put back to write pool after complete write, cancel, flush or error. That says that frame will not be valid after call of this method.
Note about port mutex handling:
The port mutex must be locked before calling this method. Internally, it will be unlocked during wait, and will be locked again. So, the port mutex is allways locked when this method returns.
Parameters
bytePerByteWrite If true, one byte will be written once.
interByteTime Time between each byte write [ms] (has only effect if bytePerByteWrite is true)
maxWriteTry Some port can return 0 byte or a timeout error if busy. If this happens, this method will sleep some time an try a write call again until write call works successfull or maxWriteTry is reached.
Returns
NoError on success or a mdtAbstractPort::error_t error (See also mdtPortThreadHelper::handleCommonWriteErrors()).
Precondition
Port must be set with mdtPortThreadHelper::setPort().
Thread must be set with mdtPortThreadHelper::setThread().
Definition at line 125 of file mdtPortThreadHelperPort.cpp.
References mdtError::commit(), mdtPortThreadHelper::currentWriteFrame(), mdtError::Error, mdtAbstractPort::ErrorHandled, mdtAbstractPort::flushOutRequestPending(), mdtPortThreadHelper::handleCommonWriteErrors(), mdtAbstractPort::lockMutex(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, msleep, mdtAbstractPort::NoError, mdtPortThreadHelper::notifyError(), mdtPortThreadHelper::pvPort, mdtPortThreadHelper::pvThread, mdtPortThreadHelper::restoreCurrentWriteFrameToPool(), mdtPortThread::runningFlagSet(), mdtAbstractPort::unlockMutex(), mdtAbstractPort::waitEventWriteReady(), writeDataToPort(), and mdtAbstractPort::WriteTimeout.
The documentation for this class was generated from the following files:
src/mdtport/mdtPortThreadHelperPort.h
src/mdtport/mdtPortThreadHelperPort.cpp