Multi diag tools: QtLocalPeer Class Reference
QtLocalPeer Class Reference
#include <qtlocalpeer.h>
Signals
void messageReceived (const QString &message)
Public Member Functions
QtLocalPeer (QObject *parent=0, const QString &appId=QString())
bool isClient ()
bool sendMessage (const QString &message, int timeout)
QString applicationId () const
Protected Slots
void receiveConnection ()
Protected Attributes
QString id
QString socketName
QLocalServer * server
QtLockedFile lockFile
QtLP_Private::QtLockedFile lockFile;.
Detailed Description
Definition at line 49 of file qtlocalpeer.h.
Constructor & Destructor Documentation
QtLocalPeer::QtLocalPeer (QObject * parent = 0, const QString & appId = QString())
Definition at line 69 of file qtlocalpeer.cpp.
References id, lockFile, QtLockedFile::open(), server, and socketName.
Member Function Documentation
QString QtLocalPeer::applicationId () const inline
Definition at line 57 of file qtlocalpeer.h.
References id.
Referenced by QtSingleApplication::id().
bool QtLocalPeer::isClient ()
Definition at line 112 of file qtlocalpeer.cpp.
References QtLockedFile::isLocked(), QtLockedFile::lock(), lockFile, receiveConnection(), server, socketName, and QtLockedFile::WriteLock.
Referenced by QtSingleApplication::isRunning(), and sendMessage().
void QtLocalPeer::messageReceived (const QString & message) signal
Referenced by receiveConnection().
void QtLocalPeer::receiveConnection () protected slot
Definition at line 173 of file qtlocalpeer.cpp.
References messageReceived(), and server.
Referenced by isClient().
bool QtLocalPeer::sendMessage (const QString & message, int timeout)
Definition at line 136 of file qtlocalpeer.cpp.
References isClient(), and socketName.
Referenced by QtSingleApplication::sendMessage().
Member Data Documentation
QString QtLocalPeer::id protected
Definition at line 67 of file qtlocalpeer.h.
Referenced by applicationId(), and QtLocalPeer().
QtLockedFile QtLocalPeer::lockFile protected
QtLP_Private::QtLockedFile lockFile;.
Definition at line 71 of file qtlocalpeer.h.
Referenced by isClient(), and QtLocalPeer().
QLocalServer* QtLocalPeer::server protected
Definition at line 69 of file qtlocalpeer.h.
Referenced by isClient(), QtLocalPeer(), and receiveConnection().
QString QtLocalPeer::socketName protected
Definition at line 68 of file qtlocalpeer.h.
Referenced by isClient(), QtLocalPeer(), and sendMessage().
The documentation for this class was generated from the following files:
src/qt-solutions/qtsingleapplication/qtlocalpeer.h
src/qt-solutions/qtsingleapplication/qtlocalpeer.cpp