Multi diag tools: mdtDigitalIo Class Reference
mdtDigitalIo Class Reference
Representation of a digital I/O.
#include <mdtDigitalIo.h>
Public Slots
void setValue (const mdtValue &value, bool emitValueChanged=false)
Set the value to update display.
Public Slots inherited from mdtAbstractIo
virtual void setValue (const mdtValue &value, bool emitValueChanged=false)
Set the value to update display.
Public Member Functions
mdtDigitalIo (QObject *parent=0)
~mdtDigitalIo ()
Public Member Functions inherited from mdtAbstractIo
mdtAbstractIo (QObject *parent=0)
Construct a empty I/O.
virtual ~mdtAbstractIo ()
void setAddress (int address)
Set the I/O address.
int address () const
Get the I/O address.
void setAddressRead (int address)
Set the I/O address for read.
int addressRead () const
Get the I/O address for read.
void setAddressWrite (int address)
Set the I/O address for write.
int addressWrite () const
Get the I/O address for write.
void setLabelShort (const QString &text)
Set the short I/O label.
QString labelShort () const
Get the short I/O label.
void setLabel (const QString &text)
Set the complete I/O label.
QString label () const
Get the complete I/O label.
void setDetails (const QString &text)
Set details about the I/O.
QString details () const
Get details about the I/O.
bool hasValidData () const
Returns true if a valid value or state was set.
void setEnabled (bool enabled)
Set enabled state.
const mdtValue & value () const
Get current value.
Additional Inherited Members
Signals inherited from mdtAbstractIo
void addressChangedForUi (int addressRead, int addressWrite)
void labelShortChangedForUi (const QString &text)
void labelChangedForUi (const QString &text)
void detailsChangedForUi (const QString &text)
void enabledStateChangedForUi (bool enabled)
void valueChanged (const mdtValue &value)
This signal is emitted whenever the value is changed.
void valueChanged (mdtAnalogIo *io)
This signal is emitted whenever the value is changed.
void valueChanged (mdtDigitalIo *io)
void valueChangedForUi (const mdtValue &value)
This signal is emitted whenever the value is changed.
Protected Attributes inherited from mdtAbstractIo
mdtValue pvValue
bool pvNotifyUi
Detailed Description
Representation of a digital I/O.
On wide range of automation applications, it is usefull to display a digital I/O to the user. For example, a digital I/O can be displayed by using this class together with mdtDigitalInWidget or mdtDigitalOutWidget
Definition at line 33 of file mdtDigitalIo.h.
Constructor & Destructor Documentation
mdtDigitalIo::mdtDigitalIo (QObject * parent = 0)
Definition at line 25 of file mdtDigitalIo.cpp.
mdtDigitalIo::~mdtDigitalIo ()
Definition at line 30 of file mdtDigitalIo.cpp.
Member Function Documentation
void mdtDigitalIo::setValue (const mdtValue & value, bool emitValueChanged = false) slot
Set the value to update display.
See Also
mdtAbstractIo::setValue(const mdtValue&, bool)
Definition at line 34 of file mdtDigitalIo.cpp.
References mdtValue::clear(), mdtValue::isValid(), mdtAbstractIo::pvValue, mdtValue::setValue(), mdtValue::valueBool(), mdtAbstractIo::valueChanged(), and mdtAbstractIo::valueChangedForUi().
Referenced by mdtDevice::getDigitalInputValue(), mdtDevice::getDigitalOutputValue(), and mdtDevice::setDigitalOutputValue().
The documentation for this class was generated from the following files:
src/mdtutils/mdtDigitalIo.h
src/mdtutils/mdtDigitalIo.cpp