Multi diag tools: mdtPortThread Class Reference
mdtPortThread Class Reference
#include <mdtPortThread.h>
Signals
void readProcessBegin ()
Emitted when a read process begins.
void writeProcessBegin ()
Emitted when a write process begins.
void newFrameReaden ()
Emited when a new frame is available.
void errorOccured (int error)
Emitted on error.
void ready (mdtPortThread *thread)
Emitted when thread is started and ready.
void finished (mdtPortThread *thread)
Emitted when thread has finished executing.
void connected ()
Emitted when connection with device is done.
Public Member Functions
mdtPortThread (QObject *parent=0)
virtual ~mdtPortThread ()
virtual void setPort (mdtAbstractPort *port)
Set the port instance.
mdtAbstractPort * port ()
Get port instance.
virtual void detachPort (bool releaseMemory)
Detach the port from thread.
void start ()
Start the thread.
virtual void stop ()
Stop the running thread.
void waitReady ()
Wait until thread is ready.
void waitFinished ()
Wait until thread is finished.
bool isRunning () const
Returns true if the thread is running.
void setRunningFlag (bool running)
Set the running flag.
bool runningFlagSet () const
Get the running flag.
bool isFinished () const
Returns false if the thread is running.
virtual bool isReader () const
Returns true if this thread reads data and send the newFrameReaden() signal.
virtual bool isWriter () const
Returns true if this thread writes date.
virtual bool handlesTimeout () const
Returns true is thread handles timeout(s) itself.
void notifyError (mdtAbstractPort::error_t error, bool renotifySameError=false)
Emit the errorOccured() signal if new error is different from current.
mdtAbstractPort::error_t currentError () const
Get current error.
Protected Member Functions
mdtAbstractPort::error_t reconnect (bool notify=true)
Try to reconnect to device/peer.
Static Protected Member Functions
static void sigactionHandle (int signum)
Protected Attributes
volatile bool pvRunning
mdtAbstractPort * pvPort
pthread_t pvNativePthreadObject
struct sigaction pvSigaction
Detailed Description
Definition at line 36 of file mdtPortThread.h.
Constructor & Destructor Documentation
mdtPortThread::mdtPortThread (QObject * parent = 0)
Definition at line 30 of file mdtPortThread.cpp.
References finished(), pvNativePthreadObject, pvPort, pvRunning, pvSigaction, sigactionHandle(), and mdtAbstractPort::UnhandledError.
mdtPortThread::~mdtPortThread () virtual
Definition at line 50 of file mdtPortThread.cpp.
References isRunning(), and stop().
Member Function Documentation
void mdtPortThread::connected () signal
Emitted when connection with device is done.
Notes:
Disconnection, connection, etc... are notified as error
Some threads does not send this signal, because device connection is not handled directly by port protocol.
Referenced by reconnect().
mdtAbstractPort::error_t mdtPortThread::currentError () const
Get current error.
This is used by mdtPortManager.
Port's mutex is not handled by this method.
Definition at line 225 of file mdtPortThread.cpp.
void mdtPortThread::detachPort (bool releaseMemory) virtual
Detach the port from thread.
Parameters
releaseMemory If true, the port object that was set with setPort() will be deleted.
Precondition
The thread must not running
Reimplemented in mdtUsbPortThread.
Definition at line 70 of file mdtPortThread.cpp.
References pvPort.
Referenced by mdtUsbPortThread::detachPort().
void mdtPortThread::errorOccured (int error) signal
Emitted on error.
Todo:
Adapt threads + port managers
When a error occurs, this signal is emited.
The error is one of the mdtAbstractPort::error_t.
mdtPortManager uses this signal.
Referenced by notifyError().
void mdtPortThread::finished (mdtPortThread * thread) signal
Emitted when thread has finished executing.
Referenced by mdtPortThread().
bool mdtPortThread::handlesTimeout () const virtual
Returns true is thread handles timeout(s) itself.
For example, mdtUsbPortThread and subclasses handles timeout itself. mdtPortReadThread does not.
mdtPortManager uses this flag to know how to deal with timeouts.
This implementation returns false.
Reimplemented in mdtUsbPortThread, mdtPortReadThread, and mdtTcpSocketThread.
Definition at line 211 of file mdtPortThread.cpp.
Referenced by mdtPortManager::addThread().
bool mdtPortThread::isFinished () const
Returns false if the thread is running.
See Also
isRunning()
Definition at line 185 of file mdtPortThread.cpp.
References mdtAbstractPort::lockMutex(), pvPort, pvRunning, and mdtAbstractPort::unlockMutex().
Referenced by waitFinished().
bool mdtPortThread::isReader () const virtual
Returns true if this thread reads data and send the newFrameReaden() signal.
mdtPortManager can handle many threads. It needs to know wich one will send the newFrameReaden() signal, so it can connect it to his slot.
Default implementation returns allways false.
This method should be implemented in reader subclass.
Reimplemented in mdtUsbPortThread, mdtPortReadThread, mdtUsbtmcPortThread, mdtPortWriteThread, mdtTcpSocketThread, and mdtSerialPortCtlThread.
Definition at line 201 of file mdtPortThread.cpp.
Referenced by mdtPortManager::addThread(), and mdtPortManager::removeThreads().
bool mdtPortThread::isRunning () const
Returns true if the thread is running.
This function overloads the QThread::isRunning() function. Note for subclass: when the thread is started and ready, the private member pvRunning must be set to true.
Definition at line 157 of file mdtPortThread.cpp.
References mdtAbstractPort::lockMutex(), pvPort, pvRunning, and mdtAbstractPort::unlockMutex().
Referenced by waitReady(), and ~mdtPortThread().
bool mdtPortThread::isWriter () const virtual
Returns true if this thread writes date.
Is used by mdtPortThread::stop() to know if mdtAbstractPort::abortFrameToWriteWait() must be called.
Default implementation returns false
Reimplemented in mdtUsbPortThread, mdtUsbtmcPortThread, mdtPortWriteThread, and mdtTcpSocketThread.
Definition at line 206 of file mdtPortThread.cpp.
Referenced by mdtPortManager::addThread(), and stop().
void mdtPortThread::newFrameReaden () signal
Emited when a new frame is available.
This signal is emited when a new frame is available.
To get the frame, the simplest way is to use a mdtPortManager.
It's also possible to use mdtPort, but this solution needs to handle the mutex, verify the readen queue state, ...
See Also
mdtPortManager
mdtPort
void mdtPortThread::notifyError (mdtAbstractPort::error_t error, bool renotifySameError = false)
Emit the errorOccured() signal if new error is different from current.
Parameters
renotifySameError For some cases, the same error must be notified each time it happens. If this flag is true, signal is emitted without checking previous error.
Definition at line 216 of file mdtPortThread.cpp.
References errorOccured().
Referenced by mdtPortThreadHelper::notifyError(), and reconnect().
mdtAbstractPort * mdtPortThread::port ()
Get port instance.
Returns
Port instance, or a null pointer if it was not set
Definition at line 65 of file mdtPortThread.cpp.
References pvPort.
Referenced by setPort(), and mdtUsbPortThread::setPort().
void mdtPortThread::readProcessBegin () signal
Emitted when a read process begins.
This can be used to display read state. Please consider that this signal is emitted each time the read process begins, and not when it ends. This is because asynch I/O calls are fast, and nothing will be seen from user if we update state before/after I/O call. To handle this, use this signal as trigger, and hold the state some stime (f.ex. 100 [ms])
void mdtPortThread::ready (mdtPortThread * thread) signal
Emitted when thread is started and ready.
mdtAbstractPort::error_t mdtPortThread::reconnect (bool notify = true) protected
Try to reconnect to device/peer.
This is a helper method for subclass. When a port method returns a Disconnected error, the thread can call this method, wich will try to reconnect (using mdtAbstractPort::reconnect()) until max retry was reached.
Reconnect timeout and max try are readen from port config, in start() method.
Parameters
notify If true, error will be notified (with errorOccured()), and failure after maxTry will be reported with mdtError.
Returns
NoError if reconnection worked or UnhandledError else.
Precondition
Port must be set with setPort() before using this method.
Definition at line 230 of file mdtPortThread.cpp.
References mdtError::commit(), connected(), mdtAbstractPort::Connecting, mdtAbstractPort::ConnectionFailed, mdtAbstractPort::Disconnected, mdtError::Error, MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, mdtAbstractPort::NoError, notifyError(), pvPort, pvRunning, mdtAbstractPort::reconnect(), mdtAbstractPort::UnhandledError, and mdtError::Warning.
bool mdtPortThread::runningFlagSet () const
Get the running flag.
This method is used by mdtPortThreadHelper and should not be used directly.
Port's mutex is not handled in this method.
Definition at line 180 of file mdtPortThread.cpp.
References pvRunning.
Referenced by mdtPortThreadHelper::getNewFrameRead(), mdtPortThreadHelper::getNewFrameWrite(), mdtPortThreadHelper::handleCommonReadErrors(), mdtPortThreadHelper::handleCommonWriteErrors(), and mdtPortThreadHelperPort::writeToPort().
void mdtPortThread::setPort (mdtAbstractPort * port) virtual
Set the port instance.
Precondition
port must be a valid pointer
The thread must not running
Definition at line 57 of file mdtPortThread.cpp.
References port(), and pvPort.
Referenced by mdtPortManager::addThread(), and mdtUsbPortThread::setPort().
void mdtPortThread::setRunningFlag (bool running)
Set the running flag.
This method is used by mdtPortThreadHelper and should not be used directly.
Port's mutex is not handled in this method.
Definition at line 175 of file mdtPortThread.cpp.
References pvRunning.
void mdtPortThread::sigactionHandle (int signum) static protected
Definition at line 281 of file mdtPortThread.cpp.
Referenced by mdtPortThread().
void mdtPortThread::start ()
Start the thread.
This method will not wait until thread is running and ready. Once thread is ready, ready() signal is emitted.
Precondition
Port instance must be defined.
Port must have a valid configuration.
Definition at line 80 of file mdtPortThread.cpp.
References mdtAbstractPort::config(), mdtPortConfig::connectMaxTry(), mdtPortConfig::connectTimeout(), pvPort, and mdtAbstractPort::UnhandledError.
void mdtPortThread::stop () virtual
Stop the running thread.
This method will not wait until thread is stopped. Once thread is stopped, finished() signal is emitted.
Precondition
Port instance must be defined with setPort().
Reimplemented in mdtPortWriteThread.
Definition at line 92 of file mdtPortThread.cpp.
References mdtAbstractPort::abortFrameToWriteWait(), mdtError::commit(), mdtError::Error, isWriter(), mdtAbstractPort::lockMutex(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, pvNativePthreadObject, pvPort, pvRunning, mdtError::setSystemError(), mdtAbstractPort::UnhandledError, and mdtAbstractPort::unlockMutex().
Referenced by mdtPortWriteThread::stop(), and ~mdtPortThread().
void mdtPortThread::waitFinished ()
Wait until thread is finished.
This is a conveniance method, mainly used by test suite. Port manager, for example, use the finished signal ensteatd of this method.
Definition at line 148 of file mdtPortThread.cpp.
References isFinished(), and msleep.
void mdtPortThread::waitReady ()
Wait until thread is ready.
This is a conveniance method, mainly used by test suite. Port manager, for example, use the ready signal ensteatd of this method.
Definition at line 139 of file mdtPortThread.cpp.
References isRunning(), and msleep.
void mdtPortThread::writeProcessBegin () signal
Emitted when a write process begins.
This can be used to display write state. Please consider that this signal is emitted each time the write process begins, and not when it ends. This is because asynch I/O calls are fast, and nothing will be seen from user if we update state before/after I/O call. To handle this, use this signal as trigger, and hold the state some stime (f.ex. 100 [ms])
Member Data Documentation
pthread_t mdtPortThread::pvNativePthreadObject protected
Definition at line 270 of file mdtPortThread.h.
Referenced by mdtPortThread(), and stop().
mdtAbstractPort* mdtPortThread::pvPort protected
Definition at line 264 of file mdtPortThread.h.
Referenced by detachPort(), isFinished(), isRunning(), mdtPortThread(), port(), reconnect(), setPort(), start(), mdtPortWriteThread::stop(), and stop().
volatile bool mdtPortThread::pvRunning protected
Definition at line 263 of file mdtPortThread.h.
Referenced by isFinished(), isRunning(), mdtPortThread(), reconnect(), runningFlagSet(), mdtUsbPortThread::sendControlQuery(), setRunningFlag(), stop(), and mdtUsbPortThread::waitOnControlTransferPossible().
struct sigaction mdtPortThread::pvSigaction protected
Definition at line 271 of file mdtPortThread.h.
Referenced by mdtPortThread().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortThread.h
src/mdtport/mdtPortThread.cpp