Multi diag tools: mdtSqlDialogOld Class Reference
mdtSqlDialogOld Class Reference
Dialog for a database table view/editor.
#include <mdtSqlDialogOld.h>
Public Slots
void accept ()
Overloads QDialog::accept()
void reject ()
Overloads QDialog::reject()
Public Member Functions
mdtSqlDialogOld (QWidget *parent=0)
Constructor.
~mdtSqlDialogOld ()
Destructor.
void setSqlWidget (mdtAbstractSqlWidget *sqlWidget)
Set form/table view/editor.
void addChildWidget (QWidget *widget, const QString &label)
Add a child (details) widget.
void setCurrentRow (int row)
Set row (record) to edit (in main table)
bool setCurrentRow (const QString &fieldName, const QVariant &matchData)
Set the first record that matches given criteria as row (record) to edit (in main table)
bool setCurrentRow (const QList< QPair< QString, QVariant > > &matchList)
Not implemented yet.
Detailed Description
Dialog for a database table view/editor.
This class offers some functionnality for the GUI part.
It was designed to work with a subclass of mdtAbstractSqlWidget.
Definition at line 42 of file mdtSqlDialogOld.h.
Constructor & Destructor Documentation
mdtSqlDialogOld::mdtSqlDialogOld (QWidget * parent = 0)
Constructor.
Will construct a empty window. Use setSqlWidget() to set central widget, setCurrentRow() to edit a existing row, insertRow() to create and edit a new row.
Definition at line 31 of file mdtSqlDialogOld.cpp.
References accept(), and reject().
mdtSqlDialogOld::~mdtSqlDialogOld ()
Destructor.
Definition at line 59 of file mdtSqlDialogOld.cpp.
Member Function Documentation
void mdtSqlDialogOld::accept () slot
Overloads QDialog::accept()
Definition at line 112 of file mdtSqlDialogOld.cpp.
References mdtAbstractSqlWidget::allDataAreSaved().
Referenced by mdtSqlDialogOld().
void mdtSqlDialogOld::addChildWidget (QWidget * widget, const QString & label)
Add a child (details) widget.
Parameters
widget Will be added to the childs tab
label Will be displayed in tab of tab widget
Precondition
Parent (main) widget must be set with setSqlWidget() before using this method
widget must be a valid pointer
Definition at line 80 of file mdtSqlDialogOld.cpp.
void mdtSqlDialogOld::reject () slot
Overloads QDialog::reject()
Definition at line 119 of file mdtSqlDialogOld.cpp.
References mdtAbstractSqlWidget::allDataAreSaved().
Referenced by mdtSqlDialogOld().
void mdtSqlDialogOld::setCurrentRow (int row)
Set row (record) to edit (in main table)
Precondition
Parent (main) widget must be set with setSqlWidget() before using this method
Definition at line 93 of file mdtSqlDialogOld.cpp.
References mdtAbstractSqlWidget::setCurrentIndex().
bool mdtSqlDialogOld::setCurrentRow (const QString & fieldName, const QVariant & matchData)
Set the first record that matches given criteria as row (record) to edit (in main table)
Parameters
fieldName Field that must contain searched value
matchData Value that must matche
Returns
True if matching record was found
Precondition
Parent (main) widget must be set with setSqlWidget() before using this method
Definition at line 100 of file mdtSqlDialogOld.cpp.
References mdtAbstractSqlWidget::setCurrentRecord().
bool mdtSqlDialogOld::setCurrentRow (const QList< QPair< QString, QVariant > > & matchList)
Not implemented yet.
Todo:
Implement in mdtAbstractSqlWidget and here
Definition at line 107 of file mdtSqlDialogOld.cpp.
void mdtSqlDialogOld::setSqlWidget (mdtAbstractSqlWidget * sqlWidget)
Set form/table view/editor.
Will make some signal/slot connection, then place sqlWidget in central area of dialog.
Precondition
sqlWidget must be a valid pointer.
Definition at line 63 of file mdtSqlDialogOld.cpp.
Referenced by mdtSqlFormDialog::mdtSqlFormDialog().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSqlDialogOld.h
src/mdtutilsgui/mdtSqlDialogOld.cpp