Multi diag tools: mdtTtBasicTesterWindow Class Reference
mdtTtBasicTesterWindow Class Reference
#include <mdtTtBasicTesterWindow.h>
Public Member Functions
mdtTtBasicTesterWindow (QSqlDatabase db, QWidget *parent)
Constructor.
bool init ()
Init.
mdtError lastError () const
Get last error.
Detailed Description
Definition at line 36 of file mdtTtBasicTesterWindow.h.
Constructor & Destructor Documentation
mdtTtBasicTesterWindow::mdtTtBasicTesterWindow (QSqlDatabase db, QWidget * parent)
Constructor.
Definition at line 33 of file mdtTtBasicTesterWindow.cpp.
References mdtDeviceContainerWidget::setContainer(), and mdtTtAbstractTester::testNodeManager().
Member Function Documentation
bool mdtTtBasicTesterWindow::init ()
Init.
Todo:
Error dialog !!
Definition at line 62 of file mdtTtBasicTesterWindow.cpp.
References mdtTtAbstractTester::setTestUiWidget(), mdtTtBasicTester::setup(), and mdtTtAbstractTester::start().
mdtError mdtTtBasicTesterWindow::lastError () const
Get last error.
Definition at line 86 of file mdtTtBasicTesterWindow.cpp.
References mdtTtBasicTester::lastError().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtBasicTesterWindow.h
src/mdttools/mdttesttool/mdtTtBasicTesterWindow.cpp