Multi diag tools: mdtSerialPortConfigWidget Class Reference
mdtSerialPortConfigWidget Class Reference
#include <mdtSerialPortConfigWidget.h>
Public Member Functions
mdtSerialPortConfigWidget (QWidget *parent=0)
void setAvailableBaudRates (QList< int > &baudRates)
Set the list of available baud rates.
void displayConfig (mdtSerialPortConfig &config)
Read the config instance and update GUI.
void updateConfig (mdtSerialPortConfig &config)
Get GUI's selected options and update config.
Additional Inherited Members
Public Attributes inherited from Ui_mdtSerialPortConfigWidget
QGridLayout * gridLayout
QLabel * lbBaudRate
QComboBox * cbBaudRate
QGroupBox * gbDataBitCount
QVBoxLayout * verticalLayout
QRadioButton * rbDataBit5
QRadioButton * rbDataBit6
QRadioButton * rbDataBit7
QRadioButton * rbDataBit8
QGroupBox * gbStopBitCount
QVBoxLayout * verticalLayout_3
QRadioButton * rbStopBit1
QRadioButton * rbStopBit2
QGroupBox * gbParity
QVBoxLayout * verticalLayout_2
QRadioButton * rbParityNone
QRadioButton * rbParityEven
QRadioButton * rbParityOdd
QGroupBox * gbFlowCtl
QVBoxLayout * verticalLayout_4
QRadioButton * rbFlowCtlNone
QRadioButton * rbFlowCtlXonXoff
QHBoxLayout * horizontalLayout
QLabel * lbXonChar
QComboBox * cbXonChar
QHBoxLayout * horizontalLayout_2
QLabel * lbXoffChar
QComboBox * cbXoffChar
QRadioButton * rbFlowCtlRtsCts
QSpacerItem * verticalSpacer
Detailed Description
Definition at line 29 of file mdtSerialPortConfigWidget.h.
Constructor & Destructor Documentation
mdtSerialPortConfigWidget::mdtSerialPortConfigWidget (QWidget * parent = 0)
Definition at line 26 of file mdtSerialPortConfigWidget.cpp.
References Ui_mdtSerialPortConfigWidget::setupUi().
Member Function Documentation
void mdtSerialPortConfigWidget::displayConfig (mdtSerialPortConfig & config)
Read the config instance and update GUI.
Definition at line 40 of file mdtSerialPortConfigWidget.cpp.
References mdtSerialPortConfig::baudRate(), Ui_mdtSerialPortConfigWidget::cbBaudRate, Ui_mdtSerialPortConfigWidget::cbXoffChar, Ui_mdtSerialPortConfigWidget::cbXonChar, mdtSerialPortConfig::dataBitsCount(), mdtSerialPortConfig::flowCtlRtsCtsEnabled(), mdtSerialPortConfig::flowCtlXonXoffEnabled(), mdtSerialPortConfig::NoParity, mdtSerialPortConfig::parity(), mdtSerialPortConfig::ParityEven, mdtSerialPortConfig::ParityOdd, Ui_mdtSerialPortConfigWidget::rbDataBit5, Ui_mdtSerialPortConfigWidget::rbDataBit6, Ui_mdtSerialPortConfigWidget::rbDataBit7, Ui_mdtSerialPortConfigWidget::rbDataBit8, Ui_mdtSerialPortConfigWidget::rbFlowCtlNone, Ui_mdtSerialPortConfigWidget::rbFlowCtlRtsCts, Ui_mdtSerialPortConfigWidget::rbFlowCtlXonXoff, Ui_mdtSerialPortConfigWidget::rbParityEven, Ui_mdtSerialPortConfigWidget::rbParityNone, Ui_mdtSerialPortConfigWidget::rbParityOdd, Ui_mdtSerialPortConfigWidget::rbStopBit1, Ui_mdtSerialPortConfigWidget::rbStopBit2, mdtSerialPortConfig::stopBitsCount(), mdtSerialPortConfig::xoffChar(), and mdtSerialPortConfig::xonChar().
Referenced by updateConfig().
void mdtSerialPortConfigWidget::setAvailableBaudRates (QList< int > & baudRates)
Set the list of available baud rates.
Definition at line 32 of file mdtSerialPortConfigWidget.cpp.
References Ui_mdtSerialPortConfigWidget::cbBaudRate.
void mdtSerialPortConfigWidget::updateConfig (mdtSerialPortConfig & config)
Get GUI's selected options and update config.
Once done, the config is read again and displayed, so the user can see what was really applied.
Definition at line 112 of file mdtSerialPortConfigWidget.cpp.
References Ui_mdtSerialPortConfigWidget::cbBaudRate, Ui_mdtSerialPortConfigWidget::cbXoffChar, Ui_mdtSerialPortConfigWidget::cbXonChar, mdtSerialPortConfig::diseableFlowCtlRtsCts(), mdtSerialPortConfig::diseableFlowCtlXonXoff(), displayConfig(), mdtSerialPortConfig::enableFlowCtlRtsCts(), mdtSerialPortConfig::enableFlowCtlXonXoff(), mdtSerialPortConfig::NoParity, mdtSerialPortConfig::ParityEven, mdtSerialPortConfig::ParityOdd, Ui_mdtSerialPortConfigWidget::rbDataBit5, Ui_mdtSerialPortConfigWidget::rbDataBit6, Ui_mdtSerialPortConfigWidget::rbDataBit7, Ui_mdtSerialPortConfigWidget::rbFlowCtlNone, Ui_mdtSerialPortConfigWidget::rbFlowCtlRtsCts, Ui_mdtSerialPortConfigWidget::rbFlowCtlXonXoff, Ui_mdtSerialPortConfigWidget::rbParityEven, Ui_mdtSerialPortConfigWidget::rbParityNone, Ui_mdtSerialPortConfigWidget::rbStopBit1, mdtSerialPortConfig::setBaudRate(), mdtSerialPortConfig::setDataBitsCount(), mdtSerialPortConfig::setParity(), and mdtSerialPortConfig::setStopBitsCount().
The documentation for this class was generated from the following files:
src/mdtserialport/mdtSerialPortConfigWidget.h
src/mdtserialport/mdtSerialPortConfigWidget.cpp