Multi diag tools: mdtDigitalInWidget Class Reference
mdtDigitalInWidget Class Reference
Representation of a digital input.
#include <mdtDigitalInWidget.h>
Public Member Functions
mdtDigitalInWidget (QWidget *parent=0)
~mdtDigitalInWidget ()
void setIo (mdtDigitalIo *io)
Set the I/O object.
Public Member Functions inherited from mdtAbstractIoWidget
mdtAbstractIoWidget (QWidget *parent=0)
Constructor.
virtual ~mdtAbstractIoWidget ()
Additional Inherited Members
Protected Member Functions inherited from mdtAbstractIoWidget
void setIo (mdtAbstractIo *io)
Set the I/O object.
Protected Attributes inherited from mdtAbstractIoWidget
QLabel * lbLabel
QPushButton * pbDetails
Detailed Description
Representation of a digital input.
On wide range of automation application, it is usefull to display a input to the user.
Definition at line 36 of file mdtDigitalInWidget.h.
Constructor & Destructor Documentation
mdtDigitalInWidget::mdtDigitalInWidget (QWidget * parent = 0)
Definition at line 28 of file mdtDigitalInWidget.cpp.
References mdtAbstractIoWidget::lbLabel, mdtAbstractIoWidget::pbDetails, and mdtLed::setFixedSize().
mdtDigitalInWidget::~mdtDigitalInWidget ()
Definition at line 45 of file mdtDigitalInWidget.cpp.
Member Function Documentation
void mdtDigitalInWidget::setIo (mdtDigitalIo * io)
Set the I/O object.
Make all needed connections with the I/O object, so that widget is allways updated.
Precondition
io must be a valid pointer.
Definition at line 49 of file mdtDigitalInWidget.cpp.
References mdtAbstractIoWidget::setIo(), and mdtAbstractIo::value().
Referenced by mdtDeviceIosWidget::setDeviceIos().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtDigitalInWidget.h
src/mdtutilsgui/mdtDigitalInWidget.cpp