Multi diag tools: mdtApplication Class Reference
mdtApplication Class Reference
Main application.
#include <mdtApplication.h>
Public Slots
void changeLanguage (const QLocale &locale=QLocale())
Change the application language.
void changeLanguage (QAction *action)
Change the application language (overload)
Public Slots inherited from QtSingleApplication
bool sendMessage (const QString &message, int timeout=5000)
void activateWindow ()
Signals
void languageChanged ()
Emitted when language was changed using changeLanguage()
Signals inherited from QtSingleApplication
void messageReceived (const QString &message)
Public Member Functions
mdtApplication (int &argc, char **argv, bool GUIenabled=true)
~mdtApplication ()
bool init (bool allowMultipleInstances=false, int dialogErrorLevelsMask=0)
Some initializations.
void setApplicationVersion (int versionMajor, int versionMinor, int versionMicro)
Build the application version with numeric values.
void addTranslationsDirectory (const QString &directory)
Add a directory that contains translations files in search paths.
QMap< QString, QString > & availableTranslations ()
Get the list of available translations.
QString & currentTranslationKey ()
Get the current translation key.
void installTranslator (QTranslator *translator)
Adds the translator to the list of translators to be used for translations.
void removeCurrentTranslators ()
Remove installed translators.
Public Member Functions inherited from QtSingleApplication
QtSingleApplication (int &argc, char **argv, bool GUIenabled=true)
QtSingleApplication (const QString &id, int &argc, char **argv)
QtSingleApplication (int &argc, char **argv, Type type)
bool isRunning ()
QString id () const
void setActivationWindow (QWidget *aw, bool activateOnMessage=true)
QWidget * activationWindow () const
void initialize (bool dummy=true)
Static Public Member Functions
static mdtApplication * instance ()
Get the instance of mdtApplication.
static QString systemDataDirPath ()
Get data dir path.
static const QDir cacheDir ()
Get cache directory.
static QString mdtLibVersion ()
Get the multi diag tools library version.
Detailed Description
Main application.
NOTE: manage directories better (with, f.ex, a member containing search paths ..) NOTE: Mutex for static members..
See Also
QApplication
QtSingleApplication
Definition at line 47 of file mdtApplication.h.
Constructor & Destructor Documentation
mdtApplication::mdtApplication (int & argc, char ** argv, bool GUIenabled = true)
Definition at line 31 of file mdtApplication.cpp.
mdtApplication::~mdtApplication ()
Definition at line 37 of file mdtApplication.cpp.
References mdtErrorOut::destroy().
Member Function Documentation
void mdtApplication::addTranslationsDirectory (const QString & directory)
Add a directory that contains translations files in search paths.
If given directory exists (and is accessible), it will be added to search paths.
Precondition
The mdtErrorOut system must be initialized before using this method, this is done by init().
Definition at line 149 of file mdtApplication.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, MDT_QM_FILE_LOAD_ERROR, and mdtError::Warning.
Referenced by init().
QMap< QString, QString > & mdtApplication::availableTranslations ()
Get the list of available translations.
The key contains the language suffix, like en , that can be reused with changeLanguage(). The list is built during init().
Definition at line 162 of file mdtApplication.cpp.
const QDir mdtApplication::cacheDir () static
Get cache directory.
Definition at line 139 of file mdtApplication.cpp.
References instance().
Referenced by mdtModbusTcpPortManager::readScanResult(), and mdtModbusTcpPortManager::saveScanResult().
void mdtApplication::changeLanguage (const QLocale & locale = QLocale()) slot
Change the application language.
This will remove installed translators, and install language speficifed translators. Whenn translation files could not be loaded, the application should fall back to source code's language. If no parameters are given, system's language will be used. By default, the .qm translation files are searched in system's data directory. It's possible to add other search paths using otherQmDirectories parameter.
Precondition
The error system must be initalized before using this method (this is done by init()).
Definition at line 191 of file mdtApplication.cpp.
References mdtError::commit(), languageChanged(), MDT_ERROR_SET_SRC, MDT_QM_FILE_LOAD_ERROR, removeCurrentTranslators(), and mdtError::Warning.
Referenced by changeLanguage(), and init().
void mdtApplication::changeLanguage (QAction * action) slot
Change the application language (overload)
To make this slot work, the QAction must contain the language key (like en, fr, de, ...) in the data section.
Precondition
action must be a valid pointer.
Definition at line 210 of file mdtApplication.cpp.
References changeLanguage().
QString & mdtApplication::currentTranslationKey ()
Get the current translation key.
The translation key could be en, de, fr, ...
Definition at line 167 of file mdtApplication.cpp.
bool mdtApplication::init (bool allowMultipleInstances = false, int dialogErrorLevelsMask = 0)
Some initializations.
Several things are done here:
Check if another instance is running (if allowMultipleInstances Instance is false)
Search the system data directory
Init the home directories structure
Init the error system
Load translation files and set language according system settings.
Parameters
allowMultipleInstances If true, multiple instance of application is allowed (but NOT multiple instance of mdtApplication in program !)
dialogErrorLevelsMask Set the mask of errors that are displayed as dialogs in GUI. By default, no error (geven by mdtErrorOut) are displayed in GUI.
See Also
mdtErrorOut::setDialogLevelsMask()
mdtErrorOut
Definition at line 44 of file mdtApplication.cpp.
References addTranslationsDirectory(), changeLanguage(), mdtErrorOut::init(), mdtLibVersion(), QtSingleApplication::sendMessage(), and mdtErrorOut::setDialogLevelsMask().
void mdtApplication::installTranslator (QTranslator * translator)
Adds the translator to the list of translators to be used for translations.
Note: this method overloads QCoreApplication::installTranslator() . The difference is that it adds new translator to a list, and delete it all in destructor. Internally, it calls QApplication::installTranslator(). To keep trace of installed translators, you should allways use this method, and never mix calls with, for example, qApp->installTranslator() or QCoreApplication::installTranslator()
Precondition
translator must point to a valid object.
Definition at line 172 of file mdtApplication.cpp.
mdtApplication * mdtApplication::instance () static
Get the instance of mdtApplication.
This function, and returned pointer, should be used with care in multi-thread applicatopn !
Definition at line 126 of file mdtApplication.cpp.
Referenced by cacheDir(), and systemDataDirPath().
void mdtApplication::languageChanged () signal
Emitted when language was changed using changeLanguage()
Definition at line 106 of file moc_mdtApplication.cxx.
Referenced by changeLanguage().
QString mdtApplication::mdtLibVersion () static
Get the multi diag tools library version.
Definition at line 144 of file mdtApplication.cpp.
References MDTLIB_VERSION_MAJOR, MDTLIB_VERSION_MICRO, and MDTLIB_VERSION_MINOR.
Referenced by init().
void mdtApplication::removeCurrentTranslators ()
Remove installed translators.
This will romove all translators installed with installTranslator().
See Also
installTranslator()
Definition at line 180 of file mdtApplication.cpp.
Referenced by changeLanguage().
void mdtApplication::setApplicationVersion (int versionMajor, int versionMinor, int versionMicro)
Build the application version with numeric values.
Create a string with versionMajor.versionMinor.versionMicro , and calls QApplication::setApplicationVersion().
Definition at line 112 of file mdtApplication.cpp.
QString mdtApplication::systemDataDirPath () static
Get data dir path.
Definition at line 133 of file mdtApplication.cpp.
References instance().
The documentation for this class was generated from the following files:
src/mdtutils/mdtApplication.h
src/mdtutils/mdtApplication.cpp
src/mdtutils/moc_mdtApplication.cxx