Multi diag tools: mdtClUnit Class Reference
mdtClUnit Class Reference
Helper class to manage unit and related data.
#include <mdtClUnit.h>
Public Member Functions
mdtClUnit (QObject *parent, QSqlDatabase db)
Constructor.
~mdtClUnit ()
Destructor.
QString sqlForComponentSelection (const QVariant &unitId) const
Get SQL statement for component selection.
QString sqlForConnectorContactSelection (const QVariant &connectorId) const
Get SQL statement for connector contacts selection.
QString sqlForArticleConnectorSelection (const QVariant &articleId, const QVariant &unitId) const
Get SQL statement for article connector selection.
QString sqlForFreeArticleConnectionSelection (const QVariant &articleId, const QVariant &unitId) const
Get SQL statement free for article connection selection.
QString sqlForArticleConnectionLinkedToArticleConnectorSelection (const QVariant &articleConnectorId, const QVariant &unitId) const
Get SQL statement for article connection selection.
QString sqlForArticleConnectionLinkedToArticleSelection (const QVariant &articleId, const QVariant &unitId) const
Get SQL statement for article connection selection.
mdtClUnitConnectionData getConnectionData (const QVariant &unitConnectionId, bool includeArticleConnectionData, bool *ok)
Get unit connection data for given unit connection ID.
mdtClUnitConnectorData getConnectorData (const QVariant &unitConnectorId, bool *ok, bool includeConnectionData, bool includeArticleConnectorData, bool includeBaseConnectorData)
Get unit connector data.
QList< QVariant > getConnectionIdListPartOfConnectorId (const QVariant &unitConnectorId, bool *ok)
Get a list of unit connection ID that are part of given unit connector ID.
QVariant getConnectorIdOfConnectionId (const QVariant &unitConnectionId, bool *ok)
Get unit connector ID of given unit connection ID.
bool addConnectionDataListFromConnectorContactIdList (mdtClUnitConnectorData &data, const QList< QVariant > &connectorContactIdList)
Add unit connections into unit connector data based on a list of given connector contact ID list.
bool addArticleConnectorData (mdtClUnitConnectorData &data, const QVariant &articleConnectorId, bool copyConnectorName)
Add article connector data part into unit connector.
QVariant getUnitConnectorIdBasedOnArticleConnectorId (const QVariant &articleConnectorId, const QVariant &unitId, bool *ok)
Get unit connector ID witch is based on given article connector ID and that is used in given unit ID.
QList< mdtClUnitConnectionData > getUnitConnectionDataListFromArticleConnectionIdList (const QVariant &unitId, const QList< QVariant > &articleConnectionIdList, bool copyContactName, bool *ok)
Get a list of unit connections based on article connection ID list.
QList< mdtClUnitConnectionData > getUnitConnectionDataListFromArticleConnectionIdList (const QVariant &unitId, const QVariant &unitConnectorId, const QList< QVariant > &articleConnectionIdList, bool copyContactName, bool *ok)
Get a list of unit connections based on article connection ID list.
bool addConnectionDataListFromArticleConnectionIdList (mdtClUnitConnectorData &data, const QList< QVariant > &articleConnectionIdList, bool copyContactName)
Add unit connections into unit connector data based on given article connection ID list.
bool addComponent (const QVariant &unitId, const QVariant &componentId)
Add a unit as component.
bool removeComponent (const QVariant &componentId)
Remove a single component.
bool removeComponents (const QList< QVariant > &componentIdList)
Remove a list of components.
bool removeComponents (const QModelIndexList &indexListOfSelectedRows)
Remove each component that is contained in selection.
int toUnitRelatedArticleConnectionCount (const QVariant &unitId)
Return the number unit connections that are related to article connections.
QStringList toUnitRelatedLinksList (const QVariant &unitId, const QList< QVariant > &unitConnectionIdList, bool *ok)
Get a list of links that are related to given unit ID.
QString toUnitRelatedLinksListStr (const QVariant &unitId, const QList< QVariant > &unitConnectionIdList, bool *ok)
Get a list of links that are related to given unit ID.
bool addConnection (const mdtClUnitConnectionData &data, bool singleTransaction=true)
Add unit connection.
bool addConnections (const QList< mdtClUnitConnectionData > &dataList, bool singleTransaction=true)
Add unit connections.
bool editConnection (const QVariant &connectionId, const mdtClUnitConnectionData &data)
Edit a unit connection.
bool removeConnection (const QVariant &unitConnectionId, bool handleTransaction=true)
Remove a single unit connection.
bool removeConnections (const mdtSqlTableSelection &s)
Remove each unit connection that is contained in selection.
bool addConnector (const mdtClUnitConnectorData &data)
Add a unit connector.
bool editConnectorName (const QVariant &unitConnectorId, const QVariant &name)
Edit connector name.
bool removeConnector (const QVariant &unitConnectorId)
Remove a unit connector and its contacts.
bool removeConnectors (const QModelIndexList &indexListOfSelectedRows)
Remove each unit connector that is contained in selection.
bool addRange (const QVariant &baseUnitConnectionId, const mdtClUnitConnectionData &rangeData)
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
bool addRecordList (const QList< mdtSqlRecord > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class to manage unit and related data.
Definition at line 42 of file mdtClUnit.h.
Constructor & Destructor Documentation
mdtClUnit::mdtClUnit (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 31 of file mdtClUnit.cpp.
mdtClUnit::~mdtClUnit ()
Destructor.
Definition at line 36 of file mdtClUnit.cpp.
Member Function Documentation
bool mdtClUnit::addArticleConnectorData (mdtClUnitConnectorData & data, const QVariant & articleConnectorId, bool copyConnectorName)
Add article connector data part into unit connector.
Will update some value in data (UnitConnector_tbl):
Connector_Id_FK : will be copied from article connector data
ArticleConnector_Id_FK : will be copied from article connector data
Parameters
data Unit connector data to update
articleConnectorId ID of article connector
copyConnectorName If true, unit connector name will be copied from article connector name
Note: will only update given data, nothing is written to database.
Definition at line 232 of file mdtClUnit.cpp.
References mdtTtBase::database(), mdtClArticle::getConnectorData(), mdtTtBase::lastError(), mdtTtBase::pvLastError, mdtClUnitConnectorData::setArticleConnectorData(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
bool mdtClUnit::addComponent (const QVariant & unitId, const QVariant & componentId)
Add a unit as component.
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 401 of file mdtClUnit.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtClUnit::addConnection (const mdtClUnitConnectionData & data, bool singleTransaction = true)
Add unit connection.
Definition at line 589 of file mdtClUnit.cpp.
References mdtTtBase::addRecord(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtTtBase::rollbackTransaction(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
Referenced by addConnections(), and addConnector().
bool mdtClUnit::addConnectionDataListFromArticleConnectionIdList (mdtClUnitConnectorData & data, const QList< QVariant > & articleConnectionIdList, bool copyContactName)
Add unit connections into unit connector data based on given article connection ID list.
Todo:
What is better ? 2 methods ?? Should coherence between article connection and article connector be done ? Or let addConnector() do it ?
Will also set some values to newly created unit connections (UnitConnection_tbl):
Unit_Id_FK : will be copied from unit connector data
UnitConnector_Id_FK : will be copied from unit connector data
ArticleConnection_Id_FK : will be copied from articleConnectionIdList
UnitContactName : if copyContactName is true, it will be copied from article connection data
Parameters
data Unit connector data to update
articleConnectionIdList For each ID in list, a unit connection is created on base of article connection data.
copyContactName If true, unit contact name will be copied from article contact name.
Definition at line 384 of file mdtClUnit.cpp.
References mdtClUnitConnectorData::addConnectionData(), getUnitConnectionDataListFromArticleConnectionIdList(), and mdtSqlRecord::value().
bool mdtClUnit::addConnectionDataListFromConnectorContactIdList (mdtClUnitConnectorData & data, const QList< QVariant > & connectorContactIdList)
Add unit connections into unit connector data based on a list of given connector contact ID list.
Will also get some values from data (UnitConnector_tbl) and set it to created connections (UnitConnection_tbl):
UnitConnector_tbl.Id_PK -> UnitConnection_tbl.UnitConnector_Id_FK
UnitConnector_tbl.Article_Id_FK -> UnitConnection_tbl.Unit_Id_FK
Note: will only update given data, nothing is written to database.
Definition at line 202 of file mdtClUnit.cpp.
References mdtClUnitConnectorData::addConnectionData(), mdtSqlRecord::clearValues(), mdtTtBase::database(), mdtClArticle::getConnectorContactDataList(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtClUnitConnectionData::setup(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
bool mdtClUnit::addConnections (const QList< mdtClUnitConnectionData > & dataList, bool singleTransaction = true)
Add unit connections.
Definition at line 625 of file mdtClUnit.cpp.
References addConnection(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), and mdtTtBase::rollbackTransaction().
bool mdtClUnit::addConnector (const mdtClUnitConnectorData & data)
Add a unit connector.
If data contains connections, they will be added.
Note: in connection data (contained in data), Unit_Id_FK and UnitConnector_Id_FK are not relevant, because they are token from data directly.
Definition at line 720 of file mdtClUnit.cpp.
References addConnection(), mdtTtBase::addRecord(), mdtTtBase::beginTransaction(), mdtError::commit(), mdtTtBase::commitTransaction(), mdtClUnitConnectorData::connectionDataList(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtTtBase::rollbackTransaction(), mdtError::setError(), mdtError::setSystemError(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
bool mdtClUnit::addRange (const QVariant & baseUnitConnectionId, const mdtClUnitConnectionData & rangeData)
Definition at line 837 of file mdtClUnit.cpp.
bool mdtClUnit::editConnection (const QVariant & connectionId, const mdtClUnitConnectionData & data)
Edit a unit connection.
Returns
True on success, false else. To get reason of failure, use lastError().
Definition at line 649 of file mdtClUnit.cpp.
References mdtTtBase::updateRecord(), and mdtSqlRecord::value().
bool mdtClUnit::editConnectorName (const QVariant & unitConnectorId, const QVariant & name)
Edit connector name.
Definition at line 773 of file mdtClUnit.cpp.
References getConnectorData(), mdtSqlRecord::setValue(), and mdtTtBase::updateRecord().
mdtClUnitConnectionData mdtClUnit::getConnectionData (const QVariant & unitConnectionId, bool includeArticleConnectionData, bool * ok)
Get unit connection data for given unit connection ID.
If given unit connection is based on a article connection, the article connection data part will also be set.
Definition at line 125 of file mdtClUnit.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::Warning.
Referenced by removeConnection().
QList< QVariant > mdtClUnit::getConnectionIdListPartOfConnectorId (const QVariant & unitConnectorId, bool * ok)
Get a list of unit connection ID that are part of given unit connector ID.
Definition at line 161 of file mdtClUnit.cpp.
References mdtTtBase::getData().
Referenced by mdtClDirectLink::addLinksByUnitConnector(), and mdtClPathGraph::getLinkedConnectorIdList().
mdtClUnitConnectorData mdtClUnit::getConnectorData (const QVariant & unitConnectorId, bool * ok, bool includeConnectionData, bool includeArticleConnectorData, bool includeBaseConnectorData)
Get unit connector data.
Parameters
unitConnectorId Unit connector ID
includeConnectionData If true, and SQL statement points to a unit connector that contains unit connections, result will be populated with these unit connection data. For each unit connection data that is based on a article connection, article connection data will be included.
includeArticleConnectorData If true, article connector data will be included. Note: article connection data related to article connector are not included. To get article connection data, set the includeConnectionData flag to true, so it's possible to get article connection data related to unit connection data.
includeBaseConnectorData If true, and SQL statement points to a unit connector that is based on a connector (from Connector_tbl), result will be populated with these connector data.
Note: if both includeArticleConnectorData and includeBaseConnectorData are set, and UnitConnector_tbl.Connector_Id_FK is different from ArticleConnector_tbl.Connector_Id_FK, an error will be generated and this method will fail, because this is not coherent.
Precondition
Given SQL statement must return 1 unit connector row
ok must be valid
Definition at line 143 of file mdtClUnit.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::Warning.
Referenced by mdtClLink::canConnectConnectors(), mdtClLink::connectByContactName(), and editConnectorName().
QVariant mdtClUnit::getConnectorIdOfConnectionId (const QVariant & unitConnectionId, bool * ok)
Get unit connector ID of given unit connection ID.
Definition at line 182 of file mdtClUnit.cpp.
References mdtTtBase::getData().
Referenced by mdtClDirectLink::addLinksByUnitConnector(), and mdtClPathGraph::getLinkedConnectorIdList().
QList< mdtClUnitConnectionData > mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList (const QVariant & unitId, const QList< QVariant > & articleConnectionIdList, bool copyContactName, bool * ok)
Get a list of unit connections based on article connection ID list.
Will also set some values to newly created unit connections (UnitConnection_tbl):
Unit_Id_FK : will be copied from given unitId
UnitConnector_Id_FK : will be set by calling getUnitConnectorIdBasedOnArticleConnectorId()
ArticleConnection_Id_FK : will be copied from articleConnectionIdList
UnitContactName : if copyContactName is true, it will be copied from article connection data
Definition at line 299 of file mdtClUnit.cpp.
References mdtSqlRecord::clearValues(), mdtTtBase::database(), mdtClArticle::getConnectionDataListFromConnectionIdList(), getUnitConnectorIdBasedOnArticleConnectorId(), mdtTtBase::lastError(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtClUnitConnectionData::setArticleConnectionData(), mdtClUnitConnectionData::setup(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
Referenced by addConnectionDataListFromArticleConnectionIdList().
QList< mdtClUnitConnectionData > mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList (const QVariant & unitId, const QVariant & unitConnectorId, const QList< QVariant > & articleConnectionIdList, bool copyContactName, bool * ok)
Get a list of unit connections based on article connection ID list.
Will also set some values to newly created unit connections (UnitConnection_tbl):
Unit_Id_FK : will be copied from given unitId
UnitConnector_Id_FK : will be copied from given unitConnectorId (can also be Null if unit connection is free, i.e. not based on a unit connector)
ArticleConnection_Id_FK : will be copied from articleConnectionIdList
UnitContactName : if copyContactName is true, it will be copied from article connection data
Definition at line 344 of file mdtClUnit.cpp.
References mdtSqlRecord::clearValues(), mdtTtBase::database(), mdtClArticle::getConnectionDataListFromConnectionIdList(), mdtTtBase::lastError(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtClUnitConnectionData::setArticleConnectionData(), mdtClUnitConnectionData::setup(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
QVariant mdtClUnit::getUnitConnectorIdBasedOnArticleConnectorId (const QVariant & articleConnectorId, const QVariant & unitId, bool * ok)
Get unit connector ID witch is based on given article connector ID and that is used in given unit ID.
If given article connector is not used in given unit, a Null will be returned. If given article connector is used more than once, this method fails (returns Null and ok will be false).
Definition at line 253 of file mdtClUnit.cpp.
References mdtError::commit(), mdtError::Error, mdtTtBase::getData(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, and mdtError::setError().
Referenced by getUnitConnectionDataListFromArticleConnectionIdList().
bool mdtClUnit::removeComponent (const QVariant & componentId)
Remove a single component.
Definition at line 433 of file mdtClUnit.cpp.
References removeComponents().
bool mdtClUnit::removeComponents (const QList< QVariant > & componentIdList)
Remove a list of components.
Definition at line 442 of file mdtClUnit.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by removeComponent(), and removeComponents().
bool mdtClUnit::removeComponents (const QModelIndexList & indexListOfSelectedRows)
Remove each component that is contained in selection.
This is usefull used together with mdtSqlTableWidget .
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 476 of file mdtClUnit.cpp.
References removeComponents().
bool mdtClUnit::removeConnection (const QVariant & unitConnectionId, bool handleTransaction = true)
Remove a single unit connection.
Definition at line 656 of file mdtClUnit.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), getConnectionData(), mdtTtBase::removeData(), mdtTtBase::rollbackTransaction(), and mdtSqlRecord::value().
Referenced by removeConnections(), and removeConnector().
bool mdtClUnit::removeConnections (const mdtSqlTableSelection & s)
Remove each unit connection that is contained in selection.
This is usefull used together with mdtSqlTableWidget .
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 698 of file mdtClUnit.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtSqlTableSelection::dataList(), removeConnection(), and mdtTtBase::rollbackTransaction().
bool mdtClUnit::removeConnector (const QVariant & unitConnectorId)
Remove a unit connector and its contacts.
Definition at line 787 of file mdtClUnit.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::getData(), removeConnection(), mdtTtBase::removeData(), and mdtTtBase::rollbackTransaction().
Referenced by removeConnectors().
bool mdtClUnit::removeConnectors (const QModelIndexList & indexListOfSelectedRows)
Remove each unit connector that is contained in selection.
This is usefull used together with mdtSqlTableWidget .
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 823 of file mdtClUnit.cpp.
References removeConnector().
QString mdtClUnit::sqlForArticleConnectionLinkedToArticleConnectorSelection (const QVariant & articleConnectorId, const QVariant & unitId) const
Get SQL statement for article connection selection.
List all article connections for a given article connector ID, and that are not used by a given unit ID .
Definition at line 94 of file mdtClUnit.cpp.
QString mdtClUnit::sqlForArticleConnectionLinkedToArticleSelection (const QVariant & articleId, const QVariant & unitId) const
Get SQL statement for article connection selection.
List all article connections for a given article ID, and that are not used by a given unit ID .
Definition at line 109 of file mdtClUnit.cpp.
QString mdtClUnit::sqlForArticleConnectorSelection (const QVariant & articleId, const QVariant & unitId) const
Get SQL statement for article connector selection.
List all article connectors for given articleId wich are not used by given unitId .
Definition at line 61 of file mdtClUnit.cpp.
QString mdtClUnit::sqlForComponentSelection (const QVariant & unitId) const
Get SQL statement for component selection.
List all units, expected those that are allready component of given unitId
Definition at line 40 of file mdtClUnit.cpp.
QString mdtClUnit::sqlForConnectorContactSelection (const QVariant & connectorId) const
Get SQL statement for connector contacts selection.
List all connector contacts for given connector ID (from Connector_tbl).
Definition at line 52 of file mdtClUnit.cpp.
QString mdtClUnit::sqlForFreeArticleConnectionSelection (const QVariant & articleId, const QVariant & unitId) const
Get SQL statement free for article connection selection.
List all article connections that are not based on a article connector for given article ID, and that are not used by a given unit ID.
Definition at line 78 of file mdtClUnit.cpp.
int mdtClUnit::toUnitRelatedArticleConnectionCount (const QVariant & unitId)
Return the number unit connections that are related to article connections.
Returns
A number >= 0 on success, a value < 0 on error. On error, use lastError() to check what goes wrong.
Definition at line 488 of file mdtClUnit.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QStringList mdtClUnit::toUnitRelatedLinksList (const QVariant & unitId, const QList< QVariant > & unitConnectionIdList, bool * ok)
Get a list of links that are related to given unit ID.
This is a helper method to display a message to the user in a simple way. Do not use the result for technical processing.
Definition at line 517 of file mdtClUnit.cpp.
References mdtTtBase::getData().
Referenced by toUnitRelatedLinksListStr().
QString mdtClUnit::toUnitRelatedLinksListStr (const QVariant & unitId, const QList< QVariant > & unitConnectionIdList, bool * ok)
Get a list of links that are related to given unit ID.
This is a helper method to display a message to the user in a simple way. Do not use the result for technical processing.
Definition at line 570 of file mdtClUnit.cpp.
References toUnitRelatedLinksList().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClUnit.h
src/mdttools/mdttesttool/mdtcablelist/mdtClUnit.cpp