Multi diag tools: mdtSqlTableViewController Class Reference
mdtSqlTableViewController Class Reference
Table view controller.
#include <mdtSqlTableViewController.h>
Public Member Functions
mdtSqlTableViewController (QObject *parent=0)
Constructor.
~mdtSqlTableViewController ()
Destructor.
void setTableView (QTableView *tv, QAbstractItemDelegate *delegate=0)
Set table view to control.
void setDefaultColumnToSelect (int column)
Set default column to select.
void setDefaultColumnToSelect (const QString &fieldName)
Set default column to select.
int firstVisibleColumnIndex ()
Get column index of first visible column.
mdtSqlTableSelection currentSelection (const QStringList &fieldList)
Get current selection.
mdtSqlTableSelection currentSelection (const QString &field)
Get current selection.
Public Member Functions inherited from mdtAbstractSqlTableController
mdtAbstractSqlTableController (QObject *parent=0)
Constructor.
virtual ~mdtAbstractSqlTableController ()
Destructor.
void setMessageHandler (std::shared_ptr< mdtUiMessageHandler > handler)
Set message handler.
bool hasMessageHandler () const
Check if a message handler was allready set.
void setTableName (const QString &tableName, QSqlDatabase db, const QString &userFriendlyTableName=QString())
Set table name.
void setModel (std::shared_ptr< QSqlTableModel > m, const QString &userFriendlyTableName=QString())
Set table model.
void setCanWriteToDatabase (bool canWrite)
Set the canWriteToDatabase flag.
bool canWriteToDatabase () const
Set the canWriteToDatabase flag.
int fieldIndex (const QString &fieldName) const
Get index of field with fieldName.
void setHeaderData (const QString &fieldName, const QString &data)
Set a user friendly name for a column.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get header data of given section.
QVariant headerData (int column, int role=Qt::DisplayRole) const
Get header data of given column.
QVariant headerData (const QString &fieldName, int role=Qt::DisplayRole) const
Get header data of given field name.
QList< QVariant > headerRowData (const std::vector< int > &columns, int role=Qt::DisplayRole) const
Get header row data of given columns.
QList< QVariant > headerRowData (const QStringList &fieldNames, int role=Qt::DisplayRole) const
Get header row data of given field names.
QStringList headerRowDataStr (const std::vector< int > &columns, int role=Qt::DisplayRole) const
Get header row data of given columns.
QStringList headerRowDataStr (const QStringList &fieldNames, int role=Qt::DisplayRole) const
Get header row data of given field names.
template<typename T >
bool addChildController (const mdtSqlRelationInfo &relationInfo, QSqlDatabase db, const QString &userFriendlyChildTableName=QString())
Add a child controller.
template<typename T >
bool addChildController (const mdtSqlRelationInfo &relationInfo, const QString &userFriendlyChildTableName=QString())
Add a child controller.
template<typename T >
std::shared_ptr< T > childController (const QString &tableName)
Get a child controller.
bool select ()
Select data in main table.
bool setFilter (const QString &filter)
Set a filter on main table.
bool setFilter (const QString &fieldName, const QVariant &matchData)
Set a filter on main table.
bool setFilter (const QString &fieldName, const QList< QVariant > &matchDataList)
Set a filter on main table.
void clearFilter ()
Clear filter.
const std::shared_ptr
< QSqlTableModel > model () const
Get model (read only access)
std::shared_ptr< QSqlTableModel > model ()
Get model (write access)
QString tableName () const
Get (technical) table name.
void setUserFriendlyTableName (const QString &name)
Set user friendly table name.
QString userFriendlyTableName () const
Get user friendly table name.
void start ()
Start internal state machine.
void stop ()
Stop internal state machine.
State_t currentState () const
Get current state.
void addDataValidator (std::shared_ptr< mdtSqlDataValidator > validator, bool putAtTopPriority=false, bool setInternalMessageHandler=true)
Add a data validator.
void addColumnToSortOrder (const QString &fieldName, Qt::SortOrder order=Qt::AscendingOrder)
Add a column to columns sort order.
void clearColumnsSortOrder ()
Clear columns sort order.
void sort ()
Sort data.
bool setCurrentData (const QString &fieldName, const QVariant &data, bool submit=true)
Set current data for given field name.
bool setData (int row, const QString &fieldName, const QVariant &data, bool submit=true)
Set data for given row and field name.
bool setData (const QString &matchFieldName, const QVariant &matchData, const QString &dataFieldName, const QVariant &data, bool submit=true)
Set data for given match and field name.
bool setData (const QString &matchFieldName1, const QVariant &key1, const QString &matchFieldName2, const QVariant &key2, const QString &dataFieldName, const QVariant &data, bool submit=true)
Set data for given match and field name.
QVariant currentData (const QString &fieldName)
Get current data for given field name.
QVariant currentData (const QString &fieldName, bool &ok)
Get current data for given field name.
QString currentFormatedValue (const QString &fieldName)
Get formated current value for SQL query.
QString currentFormatedValue (const QString &fieldName, bool &ok)
Get formated current value for SQL query.
QVariant data (const QModelIndex &index)
Get data for given index.
QVariant data (const QModelIndex &index, bool &ok)
Get data for given index.
QVariant data (int row, int column)
Get data for given row and column.
QVariant data (int row, int column, bool &ok)
Get data for given row and column.
QVariant data (int row, const QString &fieldName)
Get data for given row and field name.
QVariant data (int row, const QString &fieldName, bool &ok)
Get data for given row and field name.
QVariant data (const QString &matchFieldName, const QVariant &matchData, const QString &dataFieldName, bool &ok)
Get data for given match and field name.
QVariant data (const QString &matchFieldName, const QVariant &matchData, const QString &dataFieldName)
Get data for given match and field name.
QVariant data (const QString &matchFieldName1, const QVariant &key1, const QString &matchFieldName2, const QVariant &key2, const QString &dataFieldName, bool &ok)
Get data for given match and field name.
QVariant data (const QString &matchFieldName1, const QVariant &key1, const QString &matchFieldName2, const QVariant &key2, const QString &dataFieldName)
Get data for given match and field name.
QList< QVariant > rowData (int row, const std::vector< int > &columns, int role=Qt::DisplayRole) const
Get row data of given row and columns list.
QList< QVariant > rowData (int row, const QStringList &fieldNames, int role=Qt::DisplayRole) const
Get row data of given row and field names.
QStringList rowDataStr (int row, const std::vector< int > &columns, int role=Qt::DisplayRole) const
Get row data of given row and field names.
QStringList rowDataStr (int row, const QStringList &fieldNames, int role=Qt::DisplayRole) const
Get row data of given row and field names.
mdtSqlRecord record (int row, const QStringList &fieldNames)
Get a record that contains given field names for given row.
mdtSqlRecord record (int row, const QStringList &fieldNames, bool &ok)
Get a record that contains given field names for given row.
mdtSqlRecord record (const QString &matchFieldName, const QVariant &matchData, const QStringList &fieldNames, bool &ok)
Get a record for given match and that contains given field names.
mdtSqlRecord record (const QString &matchFieldName, const QVariant &matchData, const QStringList &fieldNames)
Get a record for given match and that contains given field names.
mdtSqlRecord currentRecord (const QStringList &fieldNames, bool &ok)
Get a record that contains given field names for current row.
mdtSqlRecord currentRecord (const QStringList &fieldNames)
Get a record that contains given field names for current row.
QList< QVariant > dataList (const QString &fieldName, bool fetchAll=true)
Get a list of data for given field name.
QList< QVariant > dataList (const QString &fieldName, bool &ok, bool fetchAll=true)
Get a list of data for given field name.
QString formatedValue (int row, const QString &fieldName)
Get formated value for SQL query.
QString formatedValue (int row, const QString &fieldName, bool &ok)
Get formated value for SQL query.
QString formatValue (const QString &fieldName, const QVariant &value)
Get formated value for SQL query.
QString formatValue (const QString &fieldName, const QVariant &value, bool &ok)
Get formated value for SQL query.
QString formatValue (const QSqlField &field)
Get formated value for SQL query.
int columnCount () const
Get column count.
int rowCount (bool fetchAll=true) const
Get row count.
bool setCurrentRow (int row)
Set current row.
bool setCurrentRow (const QString &fieldName, const QVariant &matchData)
Set current row.
int currentRow () const
Get current row.
void update ()
Update controllers with data for current row.
bool allDataAreSaved (bool checkAboutDirtyIndex=false)
Check if all data are saved.
mdtError lastError () const
Get last error.
bool submitAndWait ()
Submit and wait until success or failure.
bool removeAndWait ()
Remove and wait until success or failure.
Additional Inherited Members
Public Types inherited from mdtAbstractSqlTableController
enum State_t {
Stopped = 0, Selecting, Visualizing, Reverting,
Editing, Submitting, Inserting, EditingNewRow,
RevertingNewRow, SubmittingNewRow, Removing
}
State of edit/view widget.
Public Slots inherited from mdtAbstractSqlTableController
void submit ()
Submit data.
void revert ()
Revert current record from model.
void insert ()
Insert a new row to model.
void remove ()
Remove a row from model.
void setLastError (const mdtError &error)
Set last error.
Signals inherited from mdtAbstractSqlTableController
void mainWidgetEnableStateChanged (bool enabled)
Emitted when the entier widget enable state changes.
void childWidgetEnableStateChanged (bool enabled)
Emitted when the entier widget enable state changes for a child widget.
void submitEnabledStateChanged (bool enabled)
Emitted when submit() function goes enabled/disabled.
void revertEnabledStateChanged (bool enabled)
Emitted when revert() function goes enabled/disabled.
void insertEnabledStateChanged (bool enabled)
Emitted when insert() function goes enabled/disabled.
void removeEnabledStateChanged (bool enabled)
Emitted when remove() function goes enabled/disabled.
void selectTriggered ()
Emitted when select() or setFilter() was called.
void submitTriggered ()
Emitted when submit() was called.
void revertTriggered ()
Emitted when revert() was called.
void insertTriggered ()
Emitted when insert() was called.
void removeTriggered ()
Emitted when remove() was called.
void errorOccured ()
Emitted when a error occured.
void operationSucceed ()
Emitted when a operation succeed.
void dataEdited ()
Emitted when data was edited.
void stateEditingExited ()
Emitted when Editing state was exited.
void stateEditingNewRowExited ()
Emitted when Editing state was exited.
Protected Slots inherited from mdtAbstractSqlTableController
void onStateSelectingEntered ()
Activity after Selecting state entered.
virtual void onStateVisualizingEntered ()
Activity after Visualizing state entered.
virtual void onStateVisualizingExited ()
Activity after Visualizing state entered.
virtual void onStateEditingEntered ()
Activity after Editing state entered.
void onStateEditingExited ()
Activity after Editing state exited.
void onStateSubmittingEntered ()
Activity after Submitting state entered.
void onStateRevertingEntered ()
Activity after Reverting state entered.
virtual void onStateInsertingEntered ()
Activity after Inserting state entered.
virtual void onStateEditingNewRowEntered ()
Activity after EditingNewRow state entered.
void onStateEditingNewRowExited ()
Activity after Editing state exited.
void onStateSubmittingNewRowEntered ()
Activity after SubmittingNewRow state entered.
void onStateRevertingNewRowEntered ()
Activity after RevertingNewRow state entered.
void onStateRemovingEntered ()
Activity after Removing state entered.
Protected Member Functions inherited from mdtAbstractSqlTableController
std::shared_ptr
< mdtUiMessageHandler > messageHandler ()
Get message handler.
std::shared_ptr
< mdtSortFilterProxyModel > proxyModel ()
Get internal proxy model.
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
bool setCurrentRowPv (int row)
Set current row - For internal use.
bool submitToDatabase ()
Submit data from model to database.
Protected Attributes inherited from mdtAbstractSqlTableController
mdtError pvLastError
Last error (for write access)
Detailed Description
Table view controller.
Definition at line 73 of file mdtSqlTableViewController.h.
Constructor & Destructor Documentation
mdtSqlTableViewController::mdtSqlTableViewController (QObject * parent = 0)
Constructor.
Definition at line 65 of file mdtSqlTableViewController.cpp.
mdtSqlTableViewController::~mdtSqlTableViewController ()
Destructor.
Definition at line 74 of file mdtSqlTableViewController.cpp.
Member Function Documentation
mdtSqlTableSelection mdtSqlTableViewController::currentSelection (const QStringList & fieldList)
Get current selection.
The returned selection will only contain data related to given field list.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 130 of file mdtSqlTableViewController.cpp.
References mdtAbstractSqlTableController::model(), and mdtAbstractSqlTableController::proxyModel().
Referenced by currentSelection().
mdtSqlTableSelection mdtSqlTableViewController::currentSelection (const QString & field)
Get current selection.
The returned selection will only contain data related to given field.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 158 of file mdtSqlTableViewController.cpp.
References currentSelection(), mdtAbstractSqlTableController::model(), and mdtAbstractSqlTableController::proxyModel().
int mdtSqlTableViewController::firstVisibleColumnIndex ()
Get column index of first visible column.
Definition at line 114 of file mdtSqlTableViewController.cpp.
References mdtAbstractSqlTableController::model().
void mdtSqlTableViewController::setDefaultColumnToSelect (int column)
Set default column to select.
Some methods have to update selection in table view. Here it's possible to define witch column must be selected in such case.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 96 of file mdtSqlTableViewController.cpp.
References mdtAbstractSqlTableController::columnCount(), and mdtAbstractSqlTableController::model().
Referenced by setDefaultColumnToSelect().
void mdtSqlTableViewController::setDefaultColumnToSelect (const QString & fieldName)
Set default column to select.
Same as setDefaultColumnToSelect(int), but you can give a field name.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 107 of file mdtSqlTableViewController.cpp.
References mdtAbstractSqlTableController::fieldIndex(), mdtAbstractSqlTableController::model(), and setDefaultColumnToSelect().
void mdtSqlTableViewController::setTableView (QTableView * tv, QAbstractItemDelegate * delegate = 0)
Set table view to control.
To handle states correctly during edition, a item delegate that emits some signals is needed:
void dataEditionBegins() : when data editing beginns
void dataEditionDone() : when data editing is finished
If no delegate is given, a default will be created.
Definition at line 78 of file mdtSqlTableViewController.cpp.
References mdtAbstractSqlTableController::dataEdited(), and mdtAbstractSqlTableController::proxyModel().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlTableViewController.h
src/mdtdatabase/mdtSqlTableViewController.cpp