Multi diag tools: mdtModbusHwNodeId Class Reference
mdtModbusHwNodeId Class Reference
MODBUS hardware node ID.
#include <mdtModbusHwNodeId.h>
Public Member Functions
mdtModbusHwNodeId ()
Construct a null ID.
mdtModbusHwNodeId (int id, int bitsCount, int firstBit)
Construct a ID.
bool isNull () const
Check if ID is null.
void clear ()
Clear.
void setId (int id, int bitsCount, int firstBit)
Set ID.
void setId (const std::vector< bool > &bits, int bitsCount)
Set ID.
void setId (const std::vector< bool > &bits)
Set ID.
int id () const
Get ID.
int bitsCount () const
Get bits count.
int firstBit () const
Get first bit position.
bool operator== (int id) const
ID comparison operator.
bool operator!= (int id) const
ID comparison operator.
Detailed Description
MODBUS hardware node ID.
The concept of node ID is specific to MultiDiagTools. It was introduced to solve the problem of network IP configurations.
Take a example: We have a application that needs several MODBUS/TCP nodes. Each node has several I/O's. Say that digital output 1 of node 1 is used to activate a lamp and output 1 of node 2 must activate heating register. We could choose to have static IP addresses in the network and configure the application to activate the correct output of correct node. But, this can be a problem when a node must be replaced. More cumbersome case is a modular application that could manage several nodes, and change his I/Os layout in a dynamic way regarding a context.
A easy way to solve such problems is to have a DHCP server in the network and all nodes configured as DHCP clients (static addressing can still be a solution, but we not depend on it). Then, for a given application, we can fix a number of digital inputs to play the role of node ID. Then, instead of using IP address as identification (as in the example), we use node ID.
Definition at line 49 of file mdtModbusHwNodeId.h.
Constructor & Destructor Documentation
mdtModbusHwNodeId::mdtModbusHwNodeId () inline
Construct a null ID.
Definition at line 55 of file mdtModbusHwNodeId.h.
mdtModbusHwNodeId::mdtModbusHwNodeId (int id, int bitsCount, int firstBit) inline
Construct a ID.
Definition at line 64 of file mdtModbusHwNodeId.h.
Member Function Documentation
int mdtModbusHwNodeId::bitsCount () const inline
Get bits count.
Definition at line 162 of file mdtModbusHwNodeId.h.
Referenced by mdtModbusTcpPortManager::scan(), setId(), and mdtDeviceAddress::setModbusTcpIdentification().
void mdtModbusHwNodeId::clear () inline
Clear.
Definition at line 84 of file mdtModbusHwNodeId.h.
Referenced by mdtDeviceAddress::clear().
int mdtModbusHwNodeId::firstBit () const inline
Get first bit position.
Definition at line 169 of file mdtModbusHwNodeId.h.
Referenced by mdtModbusTcpPortManager::scan(), setId(), and mdtDeviceAddress::setModbusTcpIdentification().
int mdtModbusHwNodeId::id () const inline
Get ID.
Definition at line 155 of file mdtModbusHwNodeId.h.
Referenced by mdtModbusHwNodeIdList::contains(), mdtModbusTcpPortManager::findMatchingToHostModebusHwNodeId(), mdtModbusTcpPortManager::scan(), setId(), and mdtDeviceAddress::setModbusTcpIdentification().
bool mdtModbusHwNodeId::isNull () const inline
Check if ID is null.
Definition at line 77 of file mdtModbusHwNodeId.h.
Referenced by mdtModbusHwNodeIdList::append(), mdtModbusHwNodeIdList::contains(), mdtModbusTcpPortManager::findMatchingToHostModebusHwNodeId(), operator==(), and mdtModbusTcpPortManager::scan().
bool mdtModbusHwNodeId::operator!= (int id) const inline
ID comparison operator.
See Also
operator==()
Definition at line 193 of file mdtModbusHwNodeId.h.
References operator==().
bool mdtModbusHwNodeId::operator== (int id) const inline
ID comparison operator.
Note: will only compare id, other attributes like bistCount and firstBit are ignored.
If current node ID is null, this function returns allways false.
Definition at line 181 of file mdtModbusHwNodeId.h.
References isNull().
Referenced by operator!=().
void mdtModbusHwNodeId::setId (int id, int bitsCount, int firstBit) inline
Set ID.
Parameters
id The hardware node ID
bitsCount Number of bits that represent the ID
firstBit First bit, i.e. first digital input, that represent the node ID, starting from offset 0 (is the LSB)
Definition at line 97 of file mdtModbusHwNodeId.h.
References bitsCount(), firstBit(), and id().
Referenced by mdtModbusTcpPortManager::getHardwareNodeAddress(), and setId().
void mdtModbusHwNodeId::setId (const std::vector< bool > & bits, int bitsCount) inline
Set ID.
Set node ID from binary representation given in bits. Will also update bitsCount attribute, but firstBit is keeped unchanged.
Parameters
bits Binary representation of node ID The first element in the vector (index 0) is the LSB
bitsCount Limit of element to consider in bits
Precondition
bistCount must be >= 0 and <= bits size.
Definition at line 120 of file mdtModbusHwNodeId.h.
References bitsCount(), and id().
void mdtModbusHwNodeId::setId (const std::vector< bool > & bits) inline
Set ID.
Set node ID from binary representation given in bits. Will also update bitsCount attribute, but firstBit is keeped unchanged.
Parameters
bits Binary representation of node ID The first element in the vector (index 0) is the LSB
Definition at line 148 of file mdtModbusHwNodeId.h.
References setId().
The documentation for this class was generated from the following file:
src/mdtport/mdtModbusHwNodeId.h