Multi diag tools: mdtDeviceModbus Class Reference
mdtDeviceModbus Class Reference
Represent a MODBUS device.
#include <mdtDeviceModbus.h>
Public Member Functions
mdtDeviceModbus (QObject *parent=0)
virtual ~mdtDeviceModbus ()
mdtPortManager * portManager ()
Get internal port manager instance.
mdtModbusTcpPortManager * modbusTcpPortManager ()
Get internal port manager instance.
virtual mdtAbstractPort::error_t connectToDevice (const mdtPortInfo &portInfo)
Set hardware node id.
mdtAbstractPort::error_t connectToDevice (const mdtDeviceInfo &devInfo)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice (const QList< mdtPortInfo * > &scanResult, int hardwareNodeId, int bitsCount, int startFrom=0)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice (const QList< int > &existingHwNodeIdList)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice ()
Search and connect to physical device.
bool getRegisterValues (int address, int n)
Helper method for register service.
const QList< int > & registerValues () const
Helper method for register service.
bool setRegisterValues (int startAddress, QList< int > &values)
Helper method for register service.
Public Member Functions inherited from mdtMultiIoDevice
mdtMultiIoDevice (QObject *parent=0)
Construct a multi I/O device object.
virtual ~mdtMultiIoDevice ()
Destructor.
void addInput (mdtAnalogIo *analogInput)
Add a analog input.
void addInputs (const QList< mdtAnalogIo * > &analogInputs)
Add a list of analog inputs.
void addOutput (mdtAnalogIo *analogOutput)
Add a analog output.
void addOutputs (const QList< mdtAnalogIo * > &analogOutputs)
Add a list of analog outputs.
void addInput (mdtDigitalIo *digitalInput)
Add a digital input.
void addInputs (const QList< mdtDigitalIo * > &digitalInputs)
Add a list of digital inputs.
void addOutput (mdtDigitalIo *digitalOutput)
Add a digital output.
void addOutputs (const QList< mdtDigitalIo * > &digitalOutputs)
Add a list of digital outputs.
void deleteIos ()
Delete all I/O in container.
std::shared_ptr< mdtDeviceIos > ios ()
Access internal I/Os container.
mdtValue getAnalogInputValue (mdtAnalogIo *analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (int address, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogInputs (bool waitOnReply)
Read all analog inputs on physical device and update (G)UI representation.
mdtValue getAnalogOutputValue (mdtAnalogIo *analogOutput, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogOutputs (bool waitOnReply)
Read all analog outputs on physical device and update (G)UI representation.
int setAnalogOutputValue (mdtAnalogIo *analogOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
int setAnalogOutputs (bool waitOnReply)
Write all analog outputs on physical device and update (G)UI representation.
mdtValue getDigitalInputValue (mdtDigitalIo *digitalInput, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (int address, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalInputs (bool waitOnReply)
Read all digital inputs on physical device and update (G)UI representation.
mdtValue getDigitalOutputValue (mdtDigitalIo *digitalOutput, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalOutputs (bool waitOnReply)
Read all digital outputs on physical device and update (G)UI representation.
int setDigitalOutputValue (mdtDigitalIo *digitalOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a digital output value.
int setDigitalOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputsValue (const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a value and validity for all digital outputs.
int setDigitalOutputs (bool waitOnReply)
Write all digital outputs to physical device and update (G)UI representation.
Public Member Functions inherited from mdtDevice
mdtDevice (QObject *parent=0)
Construct a device object.
virtual ~mdtDevice ()
Destructor.
void setName (const QString &name)
Set the device name.
QString name () const
Get device name.
void setIdentification (const QVariant &id)
Set device identification.
QVariant identification () const
Get device identification.
virtual bool connectToDevice (const mdtDeviceAddress &address)
Search and connect to physical device.
void disconnectFromDevice ()
Disconnect from device.
void setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
virtual bool isReady ()
Check if device is ready.
void start (int queryInterval)
Start periodic device querying.
void stop ()
Stop periodic device querying.
void wait (int t)
Wait some time without breaking main event loop.
mdtError lastError () const
Get last error.
State_t currentState () const
Get current state.
Protected Member Functions
int readAnalogInput (mdtPortTransaction *transaction)
Read one analog input on physical device.
int readAnalogInputs (mdtPortTransaction *transaction)
Read all analog inputs on physical device.
int readAnalogOutput (mdtPortTransaction *transaction)
Read one analog output on physical device.
int readAnalogOutputs (mdtPortTransaction *transaction)
Read all analog outputs on physical device.
int writeAnalogOutput (int value, mdtPortTransaction *transaction)
Write value on a analog output to physical device.
int writeAnalogOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all analog outputs to physical device.
int readDigitalInput (mdtPortTransaction *transaction)
Read one digital input on physical device.
int readDigitalInputs (mdtPortTransaction *transaction)
Read all digital inputs on physical device.
int readDigitalOutput (mdtPortTransaction *transaction)
Read one digital output on physical device.
int readDigitalOutputs (mdtPortTransaction *transaction)
Read all digital outputs on physical device.
int writeDigitalOutput (bool state, mdtPortTransaction *transaction)
Write state on a digital output to physical device.
int writeDigitalOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all digital outputs to physical device.
bool queriesSequence ()
Sequence of queries to send periodically.
Protected Member Functions inherited from mdtMultiIoDevice
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
bool waitTransactionDone (int id)
Wait until a transaction is done without break the GUI's event loop.
void stateChangedEvent (State_t newState)
Called when current state has changed.
Protected Member Functions inherited from mdtDevice
QString deviceIdString () const
Get device identification string.
void setCurrentState (State_t state)
Set current state.
virtual void nameChangedEvent (const QString &newName)
Called by setName()
Protected Attributes
mdtModbusTcpPortManager * pvTcpPortManager
mdtFrameCodecModbus * pvCodec
Protected Attributes inherited from mdtDevice
mdtError pvLastError
Last error object.
Additional Inherited Members
Public Types inherited from mdtDevice
enum State_t { State_t::Disconnected, State_t::Connecting, State_t::Ready, State_t::Error }
State of device.
Public Slots inherited from mdtMultiIoDevice
void setAnalogOutputValue (mdtAnalogIo *analogOutput)
Set value on a analog output on physical device.
void setDigitalOutputValue (mdtDigitalIo *digitalOutput)
Set value on a digital output on physical device.
Public Slots inherited from mdtDevice
void runQueries ()
Queries to send periodically.
Signals inherited from mdtDevice
void stateChanged (State_t state)
Emitted when state has changed.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
Detailed Description
Represent a MODBUS device.
References:
MODBUS Application Protocol Specification V1.1b
http://www.Modbus-IDA.org
Definition at line 41 of file mdtDeviceModbus.h.
Constructor & Destructor Documentation
mdtDeviceModbus::mdtDeviceModbus (QObject * parent = 0)
Todo:
Provisoire !
Definition at line 34 of file mdtDeviceModbus.cpp.
References mdtPortManager::config(), mdtPortManager::notifyCurrentState(), pvCodec, pvTcpPortManager, mdtPortConfig::readTimeout(), mdtDevice::setBackToReadyStateTimeout(), mdtDevice::stateChanged(), mdtDevice::statusMessageChanged(), and mdtPortConfig::writeTimeout().
mdtDeviceModbus::~mdtDeviceModbus () virtual
Definition at line 56 of file mdtDeviceModbus.cpp.
References pvCodec, pvTcpPortManager, and mdtPortManager::stop().
Member Function Documentation
mdtAbstractPort::error_t mdtDeviceModbus::connectToDevice (const mdtPortInfo & portInfo) virtual
Set hardware node id.
Parameters
hardwareNodeId See mdtModbusTcpPortManager::getHardwareNodeAddress() .
bitsCount See mdtModbusTcpPortManager::getHardwareNodeAddress() .
startFrom See mdtModbusTcpPortManager::getHardwareNodeAddress() .void setHardwareNodeId(int hwNodeId, int bitsCount, int startFrom = 0);
Clear hardware node id
See Also
setHardwareNodeId() .void clearHardwareNodeId();
Get hardware node id
See Also
setHardwareNodeId() .QVariant hardwareNodeId() const;
Connect to physical device
This method can be reimplemented in subclass if specific tasks must be done during connection .
Parameters
portInfo mdtPortInfo object . The portName attribute of portInfo must contain host:port format (or ip:port) .
Returns
A error listed in mdtAbstractPort::error_t (NoError on success) .
void mdtDeviceModbus::setHardwareNodeId(int hwNodeId, int bitsCount, int startFrom) { pvHardwareNodeId = hwNodeId; pvHardwareNodeIdBitsCount = bitsCount; pvHardwareNodeIdBitsStartFrom = startFrom; } void mdtDeviceModbus::clearHardwareNodeId() { pvHardwareNodeId.clear(); pvHardwareNodeIdBitsCount = 0; pvHardwareNodeIdBitsStartFrom = 0; }
QVariant mdtDeviceModbus::hardwareNodeId() const { return pvHardwareNodeId; }
Reimplemented in mdtDeviceModbusWago.
Definition at line 98 of file mdtDeviceModbus.cpp.
References mdtPortManager::isClosed(), mdtAbstractPort::NoError, mdtAbstractPort::PortNotFound, pvTcpPortManager, mdtPortManager::setPortInfo(), mdtPortManager::start(), and mdtPortManager::stop().
mdtAbstractPort::error_t mdtDeviceModbus::connectToDevice (const mdtDeviceInfo & devInfo)
Search and connect to physical device.
Will scan available ports and open the first port that has device attached maching request.
See Also
connectToDevice(mdtPortInfo&) .
Parameters
devInfo Requested device's informations (can be empty, no information is used in current version).
Returns
A error listed in mdtAbstractPort::error_t (NoError on success)
Definition at line 112 of file mdtDeviceModbus.cpp.
References connectToDevice(), mdtPortManager::isClosed(), mdtAbstractPort::NoError, mdtAbstractPort::PortNotFound, pvTcpPortManager, mdtModbusTcpPortManager::saveScanResult(), and mdtPortManager::stop().
mdtAbstractPort::error_t mdtDeviceModbus::connectToDevice (const QList< mdtPortInfo * > & scanResult, int hardwareNodeId, int bitsCount, int startFrom = 0)
Search and connect to physical device.
Will try to connect to device listed in scanResult until hardwareNodeId is found.
Parameters
scanResult List of mdtPortInfo containing a port name in format host:port .
hardwareNodeId See mdtModbusTcpPortManager::getHardwareNodeAddress() .
bitsCount See mdtModbusTcpPortManager::getHardwareNodeAddress() .
startFrom See mdtModbusTcpPortManager::getHardwareNodeAddress() .
Returns
A error listed in mdtAbstractPort::error_t (NoError on success) .
Precondition
scanResult must contain valid pointers .
Definition at line 153 of file mdtDeviceModbus.cpp.
References connectToDevice(), mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtPortManager::isClosed(), mdtAbstractPort::NoError, mdtAbstractPort::PortNotFound, pvTcpPortManager, and mdtPortManager::stop().
mdtAbstractPort::error_t mdtDeviceModbus::connectToDevice (const QList< int > & existingHwNodeIdList)
Search and connect to physical device.
Will connect to device with hardwareNodeId set with setHardwareNodeId() . This method will beginn to scan hosts in cache file (if exists) . If expcted device was not found, the network is also scanned .
Parameters
existingHwNodeIdList A list of hardwareNodeId to consider during scan . Once all devices contained in existingHwNodeIdList, and device with hardwareNodeId, are found, scan will break .
Returns
A error listed in mdtAbstractPort::error_t (NoError on success) .
Definition at line 188 of file mdtDeviceModbus.cpp.
References mdtPortManager::isClosed(), mdtAbstractPort::NoError, pvTcpPortManager, mdtModbusTcpPortManager::saveScanResult(), and mdtPortManager::stop().
mdtAbstractPort::error_t mdtDeviceModbus::connectToDevice ()
Search and connect to physical device.
Will connect to device with hardwareNodeId set with setHardwareNodeId() . This method will beginn to scan hosts in cache file (if exists) . If expcted device was not found, the network is also scanned .
If all devices that must be scanned have a known hardwareNodeId, please consider using connectToDevice(const QList<int>&) , wtch can be faster .
Returns
A error listed in mdtAbstractPort::error_t (NoError on success) .
Todo:
Not implemented yet .
Definition at line 236 of file mdtDeviceModbus.cpp.
References mdtAbstractPort::UnhandledError.
Referenced by mdtDeviceModbusWago::connectToDevice(), and connectToDevice().
bool mdtDeviceModbus::getRegisterValues (int address, int n)
Helper method for register service.
Usefull to get resgister values (f.ex. configurations regsisters, ...).
Note: to get analog I/O values, the mdtDevice API should be used.
Returns
True on success. Values are the available with registerValues()
Precondition
address and n must be > 0
See Also
mdtModbusTcpPortManager::getRegisterValues()
Definition at line 242 of file mdtDeviceModbus.cpp.
References mdtModbusTcpPortManager::getRegisterValues(), and pvTcpPortManager.
Referenced by mdtDeviceModbusWago::analogInputsCount(), mdtDeviceModbusWago::analogOutputsCount(), mdtDeviceModbusWago::detectIos(), mdtDeviceModbusWago::digitalInputsCount(), mdtDeviceModbusWago::digitalOutputsCount(), mdtDeviceModbusWago::isWago750(), mdtDeviceModbusWagoModule::readRegisters(), and mdtDeviceModbusWagoModule::readStatusBytes().
mdtModbusTcpPortManager * mdtDeviceModbus::modbusTcpPortManager ()
Get internal port manager instance.
Definition at line 70 of file mdtDeviceModbus.cpp.
References pvTcpPortManager.
Referenced by mdtModbusIoTool::mdtModbusIoTool().
mdtPortManager * mdtDeviceModbus::portManager () virtual
Get internal port manager instance.
Reimplemented from mdtMultiIoDevice.
Definition at line 65 of file mdtDeviceModbus.cpp.
References pvTcpPortManager.
Referenced by mdtModbusIoTool::mdtModbusIoTool().
bool mdtDeviceModbus::queriesSequence () protected virtual
Sequence of queries to send periodically.
This method is called from runQueries().
Returns
true if all queries are sent successfully.
Subclass notes:
This default implementation does nothing and allways returns false.
This method can be reimplemented periodic queries must be sent to device.
Reimplemented from mdtDevice.
Definition at line 481 of file mdtDeviceModbus.cpp.
References mdtMultiIoDevice::getAnalogInputs(), and mdtMultiIoDevice::getDigitalInputs().
int mdtDeviceModbus::readAnalogInput (mdtPortTransaction * transaction) protected virtual
Read one analog input on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogInput().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details).
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 494 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadInputRegisters(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::readAnalogInputs (mdtPortTransaction * transaction) protected virtual
Read all analog inputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogInputs().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 511 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadInputRegisters(), mdtPortTransaction::ioCount(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::readAnalogOutput (mdtPortTransaction * transaction) protected virtual
Read one analog output on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogOutputValue().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 528 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadHoldingRegisters(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::readAnalogOutputs (mdtPortTransaction * transaction) protected virtual
Read all analog outputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogOutputValue().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
Reimplemented from mdtMultiIoDevice.
Definition at line 545 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadHoldingRegisters(), mdtPortTransaction::ioCount(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::readDigitalInput (mdtPortTransaction * transaction) protected virtual
Read one digital input on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital inputs, this method should be implemented.
This method is called from getDigitalInputState().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 598 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadDiscreteInputs(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::readDigitalInputs (mdtPortTransaction * transaction) protected virtual
Read all digital inputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital inputs, this method should be implemented.
This method is called from getDigitalInputs().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 615 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadDiscreteInputs(), mdtPortTransaction::ioCount(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::readDigitalOutput (mdtPortTransaction * transaction) protected virtual
Read one digital output on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from getDigitalOutputState().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 632 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadCoils(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::readDigitalOutputs (mdtPortTransaction * transaction) protected virtual
Read all digital outputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from getDigitalOutputs().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 649 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeReadCoils(), mdtPortTransaction::ioCount(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
const QList< int > & mdtDeviceModbus::registerValues () const
Helper method for register service.
Return result set by getRegisterValues(). Note that values are keeped until next call of getRegisterValues().
See Also
mdtModbusTcpPortManager::registerValues()
Definition at line 247 of file mdtDeviceModbus.cpp.
References pvTcpPortManager, and mdtModbusTcpPortManager::registerValues().
Referenced by mdtDeviceModbusWago::analogInputsCount(), mdtDeviceModbusWago::analogOutputsCount(), mdtDeviceModbusWago::detectIos(), mdtDeviceModbusWago::digitalInputsCount(), mdtDeviceModbusWago::digitalOutputsCount(), mdtDeviceModbusWago::isWago750(), mdtDeviceModbusWagoModule::readRegisters(), and mdtDeviceModbusWagoModule::readStatusBytes().
bool mdtDeviceModbus::setRegisterValues (int startAddress, QList< int > & values)
Helper method for register service.
Usefull to set register values (f.ex. configurations regsisters, ...).
Note: to set analog I/O values, the mdtDevice API should be used.
Returns
True on success.
Precondition
startAddress must be >= 0
See Also
mdtModbusTcpPortManager::setRegisterValues()
Definition at line 252 of file mdtDeviceModbus.cpp.
References pvTcpPortManager, and mdtModbusTcpPortManager::setRegisterValues().
Referenced by mdtDeviceModbusWagoModule::writeControlBytes(), and mdtDeviceModbusWagoModule::writeRegisters().
int mdtDeviceModbus::writeAnalogOutput (int value, mdtPortTransaction * transaction) protected virtual
Write value on a analog output to physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog outputs, this method should be implemented.
This method is called from setAnalogOutputValue().
Parameters
value Value encoded regarding device format.
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
Reimplemented from mdtMultiIoDevice.
Definition at line 562 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeWriteSingleRegister(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::writeAnalogOutputs (mdtPortTransaction * transaction, mdtDeviceIosSegment * segment) protected virtual
Write all analog outputs to physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog outputs, this method should be implemented.
This method is called from setAnalogOutputs().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 579 of file mdtDeviceModbus.cpp.
References mdtFrameCodecModbus::encodeWriteMultipleRegisters(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), mdtPortTransaction::setData(), mdtDeviceIosSegment::startAddressWrite(), and mdtDeviceIosSegment::valuesInt().
int mdtDeviceModbus::writeDigitalOutput (bool state, mdtPortTransaction * transaction) protected virtual
Write state on a digital output to physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from setDigitalOutputState().
Parameters
state State (ON/OFF).
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 666 of file mdtDeviceModbus.cpp.
References mdtPortTransaction::address(), mdtFrameCodecModbus::encodeWriteSingleCoil(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), and mdtPortTransaction::setData().
int mdtDeviceModbus::writeDigitalOutputs (mdtPortTransaction * transaction, mdtDeviceIosSegment * segment) protected virtual
Write all digital outputs to physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from setDigitalOutputs().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented from mdtMultiIoDevice.
Definition at line 683 of file mdtDeviceModbus.cpp.
References mdtFrameCodecModbus::encodeWriteMultipleCoils(), mdtMultiIoDevice::ios(), pvCodec, pvTcpPortManager, mdtModbusTcpPortManager::sendData(), mdtPortTransaction::setData(), mdtDeviceIosSegment::startAddressWrite(), and mdtDeviceIosSegment::valuesBool().
Member Data Documentation
mdtFrameCodecModbus* mdtDeviceModbus::pvCodec protected
Definition at line 372 of file mdtDeviceModbus.h.
Referenced by mdtDeviceModbus(), readAnalogInput(), readAnalogInputs(), readAnalogOutput(), readAnalogOutputs(), readDigitalInput(), readDigitalInputs(), readDigitalOutput(), readDigitalOutputs(), writeAnalogOutput(), writeAnalogOutputs(), writeDigitalOutput(), writeDigitalOutputs(), and ~mdtDeviceModbus().
mdtModbusTcpPortManager* mdtDeviceModbus::pvTcpPortManager protected
Definition at line 371 of file mdtDeviceModbus.h.
Referenced by mdtDeviceModbusWago::connectToDevice(), connectToDevice(), getRegisterValues(), mdtDeviceModbus(), modbusTcpPortManager(), portManager(), readAnalogInput(), readAnalogInputs(), readAnalogOutput(), readAnalogOutputs(), readDigitalInput(), readDigitalInputs(), readDigitalOutput(), readDigitalOutputs(), registerValues(), setRegisterValues(), writeAnalogOutput(), writeAnalogOutputs(), writeDigitalOutput(), writeDigitalOutputs(), and ~mdtDeviceModbus().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceModbus.h
src/mdtdevice/mdtDeviceModbus.cpp