Multi diag tools: mdtPortLock Class Reference
mdtPortLock Class Reference
NOTE:
#include <mdtPortLock.h>
Public Member Functions
mdtPortLock ()
~mdtPortLock ()
int openLocked (const QString &portName, int flags)
Open a port locked.
void unlock ()
Unlock the port.
bool isLocked ()
Returns true if port is locked by current instance.
bool isLockedByAnother ()
Returns true if port is locked by another instance.
Detailed Description
NOTE:
Todo:
Implement UUCP format in LCK.. files
Open a port and lock it
On Linux (or all POSIX ?) system, file locking is avaliable with fcntl(). But several applications uses LCK..name for locking.
This class will try to find if a port is allready locked using LCK..name system in several directories (/var/lock, /tmp, ...).
If nothing is found, then port will be opened, and several lockfiles created. The port is then locked with fcntl().
Definition at line 45 of file mdtPortLock.h.
Constructor & Destructor Documentation
mdtPortLock::mdtPortLock ()
Definition at line 30 of file mdtPortLock.cpp.
mdtPortLock::~mdtPortLock ()
Definition at line 39 of file mdtPortLock.cpp.
References unlock().
Member Function Documentation
bool mdtPortLock::isLocked ()
Returns true if port is locked by current instance.
Definition at line 127 of file mdtPortLock.cpp.
bool mdtPortLock::isLockedByAnother ()
Returns true if port is locked by another instance.
Definition at line 132 of file mdtPortLock.cpp.
int mdtPortLock::openLocked (const QString & portName, int flags)
Open a port locked.
At first, the lock file name will be buit for each lock directories found (searching in /tmp, /var/lock). Then, if no lock file is found, the port will be opened with open(). Just after open, the port will be locked with fcntl().
Parameters
portName Path to port to open (f.ex. /dev/ttyS0)
flags Flags are simply passed to open() syscall (see open() man for details).
Returns
File descriptor returned by open() , or -1 on error.
Definition at line 44 of file mdtPortLock.cpp.
References mdtError::commit(), mdtError::Error, mdtError::Info, MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, and mdtError::setSystemError().
void mdtPortLock::unlock ()
Unlock the port.
Will remove lockfiles and unlock port with fcntl().
Note: use close() if file is not used later, this is not done by this method.
Definition at line 113 of file mdtPortLock.cpp.
Referenced by ~mdtPortLock().
The documentation for this class was generated from the following files:
src/mdtport/linux/mdtPortLock.h
src/mdtport/linux/mdtPortLock.cpp