Multi diag tools: mdtUsbPortManager Class Reference
mdtUsbPortManager Class Reference
Helper class that simplify access to USB port API.
#include <mdtUsbPortManager.h>
Public Slots
void fromThreadControlResponseReaden ()
Called from USB thread when a control reply was received.
void fromThreadMessageInReaden ()
Called from USB thread when a message IN was received (on additionnal interrupt IN endpoint).
void fromThreadReadUntilShortPacketReceivedFinished ()
Called by thread when the read until a short packet process is finished.
Public Slots inherited from mdtPortManager
virtual void abort ()
Cancel read and write operations.
Public Member Functions
mdtUsbPortManager (QObject *parent=0)
Contruct a USB port manager.
virtual ~mdtUsbPortManager ()
Destructor.
virtual QList< mdtPortInfo * > scan ()
Get a list of attached USB devices.
QList< mdtPortInfo * > scan (int bDeviceClass, int bDeviceSubClass, int bDeviceProtocol)
Get a list of attached USB devices.
bool start ()
Open the port.
void readUntilShortPacketReceived ()
Check if port manager is ready.
virtual int sendControlRequest (const mdtFrameUsbControl &request, bool setwIndexAsbInterfaceNumber=false)
Send a control request by copy.
bool waitReadenControlResponse ()
Wait until a control response is readen.
QList< mdtFrameUsbControl > readenControlResponses ()
Get all readen control responses.
void flushIn (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush input buffers.
void flushOut (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush output buffers.
Public Member Functions inherited from mdtPortManager
mdtPortManager (QObject *parent=0)
Contruct a port manager.
virtual ~mdtPortManager ()
Destructor.
virtual void setPort (mdtAbstractPort *port)
Set port object.
void lockPortMutex ()
Lock the port's mutex.
void unlockPortMutex ()
Unlock port's mutex.
void detachPort (bool deletePort, bool deleteThreads)
Detach port.
void addThread (mdtPortThread *thread)
Add a thread and assign it to port.
mdtPortThread * readThread ()
Returns instance of reader thread.
mdtPortThread * writeThread ()
Returns instance of writer thread.
void removeThreads (bool releaseMemory)
Detach threads from port and remove threads.
void stop ()
Stop port manager.
void setPortName (const QString &portName)
Set port name.
void setPortInfo (mdtPortInfo info)
Set port info.
mdtPortInfo portInfo ()
Get current port info.
QString portName () const
Get current port name.
virtual mdtPortConfig & config ()
Get the port's config object.
mdtPortConfig & config () const
Get the port's config object.
void setKeepTransactionsDone (bool keep)
Force transactions done to be keeped.
bool keepTransactionsDone () const
Get the keepTransactionsDone flag.
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
virtual int sendData (mdtPortTransaction *transaction)
Send data on port.
virtual int sendData (const QByteArray &data, bool queryReplyMode=false)
Send data to port.
bool waitTransactionDone (int id)
Wait until a transaction is done.
bool waitOneTransactionDone ()
Wait until current transaction is done.
void wait (int ms)
Wait for some time.
QByteArray readenFrame (int id)
Get data by frame ID.
QList< QByteArray > readenFrames ()
Get all readen data.
void flushIn ()
Flush input buffers.
void flushOut ()
Flush output buffers.
void flush (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush I/O buffers.
void flush ()
Flush I/O buffers.
state_t currentState () const
Get current state.
void notifyCurrentState ()
Notify the current state.
virtual bool isReady () const
Check if port manager is ready.
bool isClosed () const
Check if port is closed.
Protected Slots
void onThreadsErrorOccured (int error)
Manage errors comming from usb port thread.
Protected Slots inherited from mdtPortManager
virtual void fromThreadNewFrameReaden ()
Called by the read thread whenn a complete frame was readen.
virtual void onThreadsErrorOccured (int error)
Manage errors comming from port threads.
Additional Inherited Members
Public Types inherited from mdtPortManager
enum state_t {
PortClosed = 0, Stopped, Starting, Stopping,
Running, PortError, PortReady, Disconnected,
Connecting, Connected, Ready, Busy
}
State of device.
Signals inherited from mdtPortManager
void newTransactionDone (mdtPortTransaction *transaction)
Emitted each time a transaction is done.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
void stateChanged (int stateId)
Emitted each time the state changed.
void stateChangedForUi (int stateId, const QString &stateText, int ledColorId, bool ledIsOn)
Emitted only if a state that must be notified is entered.
void pmPortClosedEvent ()
Sent when port was closed.
void pmStartThreadsEvent ()
Sent when threads must be started.
void pmStopThreadsEvent ()
Sent when threads must be stopped.
void pmAllThreadsReadyEvent ()
Sent when all threads are ready.
void pmAllThreadsStoppedEvent ()
Sent when all threads are stopped.
void pmUnhandledErrorEvent ()
Sent when a unhandled error occured.
void pmConnectingEvent ()
Sent when connection with device beginns.
void pmConnectedEvent ()
Sent when connection with device is established.
void pmDisconnectedEvent ()
Sent when connection with device was lost/closed.
void pmConnectionFailedEvent ()
Sent when connection failed on startup or after max try.
void pmBusyEvent ()
Sent when device is busy (or other slow down reason..)
void pmReadyEvent ()
Sent when device and communication becomes ready again.
void pmTransactionTimeoutEvent ()
Sent when a transaction timeout occured.
Protected Member Functions inherited from mdtPortManager
virtual bool openPort ()
Open the port.
void closePort ()
Close the port.
void setCurrentTransactionId (int id)
Set the current transaction ID.
int currentTransactionId () const
Get the current transaction ID.
void incrementCurrentTransactionId (int min=0, int max=INT_MAX)
Increment current transaction ID.
bool waitTransactionPossible ()
Wait until transaction pending queue has less than maximum possible items.
void addTransactionPending (mdtPortTransaction *transaction)
Add a transaction to pending queue.
mdtPortTransaction * transactionPending (int id)
Take pending transaction matching id.
void flushTransactionsPending ()
Restore all transactions pending to pool.
void addTransactionDone (mdtPortTransaction *transaction)
Add a transaction to the DONE queue.
bool transactionsDoneContains (int id) const
Check if a transaction with given ID exists in done queue.
mdtPortTransaction * transactionDone (int id)
Take transaction from DONE queue matching id.
void flushTransactionsDone ()
Restore all transactions done to pool.
void startTransactionTimer (int timeout)
Start transaction timer.
void stopTransactionTimer ()
Stop transaction timer.
bool transactionTimeoutOccured () const
Check if a transaction timeout occured.
void commitFrames ()
Emit signals for each done transactions.
Protected Attributes inherited from mdtPortManager
mdtAbstractPort * pvPort
QList< mdtPortThread * > pvThreads
Detailed Description
Helper class that simplify access to USB port API.
Based on mdtPortManager, some USB specific methods are added. The internal configuration (a mdtPortConfig object) is keeped default.
Definition at line 33 of file mdtUsbPortManager.h.
Constructor & Destructor Documentation
mdtUsbPortManager::mdtUsbPortManager (QObject * parent = 0)
Contruct a USB port manager.
Will create mdtUsbPort and setup. Thread will be created at first call of openPort().
Definition at line 34 of file mdtUsbPortManager.cpp.
References mdtPortManager::config(), mdtAbstractPort::setConfig(), and mdtPortManager::setPort().
mdtUsbPortManager::~mdtUsbPortManager () virtual
Destructor.
Stop the manager (if running), and close the port (if open). All internal objects (port, config and threads) are deleted here.
Definition at line 47 of file mdtUsbPortManager.cpp.
References mdtAbstractPort::config(), mdtPortManager::detachPort(), mdtPortManager::pvPort, and mdtPortManager::stop().
Member Function Documentation
void mdtUsbPortManager::flushIn (bool flushPortManagerBuffers, bool flushPortBuffers) virtual
Flush input buffers.
Parameters
flushPortManagerBuffers If true, port manager buffers will be cleared.
flushPortBuffers If true, port's buffers will be cleared.
Precondition
Port must be set with setPort() before calling this method.
Reimplemented from mdtPortManager.
Definition at line 342 of file mdtUsbPortManager.cpp.
References mdtPortManager::flushIn(), and mdtPortManager::pvPort.
void mdtUsbPortManager::flushOut (bool flushPortManagerBuffers, bool flushPortBuffers) virtual
Flush output buffers.
Parameters
flushPortManagerBuffers If true, port manager buffers will be cleared. (Has no effect in this implementation, but some subclass can have output buffers).
flushPortBuffers If true, port's buffers will be cleared.
Precondition
Port must be set with setPort() before calling this method.
Reimplemented from mdtPortManager.
Definition at line 353 of file mdtUsbPortManager.cpp.
References mdtPortManager::flushOut(), and mdtPortManager::pvPort.
void mdtUsbPortManager::fromThreadControlResponseReaden () slot
Called from USB thread when a control reply was received.
Will add a copy of received control responses to internal queue and restore frame back to port's pool.
Definition at line 360 of file mdtUsbPortManager.cpp.
References mdtError::commit(), mdtUsbPort::controlFramesPool(), mdtUsbPort::controlResponseFrames(), mdtError::Error, mdtPortManager::lockPortMutex(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtPortManager::pvPort, and mdtPortManager::unlockPortMutex().
Referenced by start().
void mdtUsbPortManager::fromThreadMessageInReaden () slot
Called from USB thread when a message IN was received (on additionnal interrupt IN endpoint).
Definition at line 394 of file mdtUsbPortManager.cpp.
void mdtUsbPortManager::fromThreadReadUntilShortPacketReceivedFinished () slot
Called by thread when the read until a short packet process is finished.
Definition at line 399 of file mdtUsbPortManager.cpp.
void mdtUsbPortManager::onThreadsErrorOccured (int error) protected slot
Manage errors comming from usb port thread.
This implementation will handle some USB specific errors, change the current state emiting transistion signal. If state has changed, stateChanged() signal is emited.
Some errors are handled here. For others, mdtPortManager::onThreadsErrorOccured() is called.
Definition at line 405 of file mdtUsbPortManager.cpp.
References mdtAbstractPort::ControlCanceled, mdtAbstractPort::ControlTimeout, mdtPortManager::onThreadsErrorOccured(), mdtPortManager::pmUnhandledErrorEvent(), and mdtAbstractPort::UnhandledError.
QList< mdtFrameUsbControl > mdtUsbPortManager::readenControlResponses ()
Get all readen control responses.
Note that calling this methode will clear the internal queue. (A second call will return a empty list).
Definition at line 332 of file mdtUsbPortManager.cpp.
void mdtUsbPortManager::readUntilShortPacketReceived ()
Check if port manager is ready.
Because mdtUsbPortManager is a base class, it acts like mdtPortManager::isReady() . A specific subclass (like mdtUsbtmcPortManager will reimplement isReady()).
Request port to read until a short frame is received
This is, for example, used by USBTMC bulk in abort process. If such request is pending, thread will read until a short frame is received.
Will send the request and wait until it is finished (will not break GUI event loop).
Precondition
Port must be set with setPort() with a mdtUsbPort (or subclass) before use of this method.
Definition at line 206 of file mdtUsbPortManager.cpp.
References mdtPortManager::isClosed(), mdtPortManager::lockPortMutex(), mdtPortManager::pvPort, mdtUsbPort::requestReadUntilShortPacketReceived(), and mdtPortManager::unlockPortMutex().
QList< mdtPortInfo * > mdtUsbPortManager::scan () virtual
Get a list of attached USB devices.
Note that returned list must be freed by user after usage. (for.ex. with qDeletAll() and QList::clear()).
Precondition
Port manager must be closed
Reimplemented from mdtPortManager.
Reimplemented in mdtUsbtmcPortManager.
Definition at line 56 of file mdtUsbPortManager.cpp.
References mdtPortManager::isClosed(), and scan().
Referenced by scan(), and mdtUsbtmcPortManager::scan().
QList< mdtPortInfo * > mdtUsbPortManager::scan (int bDeviceClass, int bDeviceSubClass, int bDeviceProtocol)
Get a list of attached USB devices.
Note that returned list must be freed by user after usage. (for.ex. with qDeletAll() and QList::clear()).
Parameters
bDeviceClass If >= 0, only devices with matching bDeviceClass are listed
bDeviceSubClass If >= 0, only devices with matching bDeviceSubClass are listed
bDeviceProtocol If >= 0, only devices with matching bDeviceProtocol are listed
Precondition
Port manager must be closed
Definition at line 63 of file mdtUsbPortManager.cpp.
References mdtPortInfo::addDevice(), mdtUsbInterfaceDescriptor::bInterfaceClass(), mdtUsbInterfaceDescriptor::bInterfaceProtocol(), mdtUsbInterfaceDescriptor::bInterfaceSubClass(), mdtError::commit(), mdtUsbDeviceDescriptor::configurations(), mdtPortInfo::deviceInfoList(), mdtError::Error, mdtUsbDeviceDescriptor::fetchAttributes(), mdtUsbDeviceDescriptor::idProduct(), mdtUsbDeviceDescriptor::idVendor(), mdtUsbConfigDescriptor::interfaces(), mdtPortManager::isClosed(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtPortManager::portInfo(), mdtPortManager::portName(), mdtDeviceInfo::productId(), mdtUsbDeviceDescriptor::productName(), mdtUsbDeviceDescriptor::serialNumber(), mdtPortInfo::setDisplayText(), mdtPortInfo::setPortName(), mdtDeviceInfo::setProductId(), mdtDeviceInfo::setProtocolId(), mdtDeviceInfo::setSerialId(), mdtDeviceInfo::setVendorId(), mdtDeviceInfo::vendorId(), and mdtUsbDeviceDescriptor::vendorName().
int mdtUsbPortManager::sendControlRequest (const mdtFrameUsbControl & request, bool setwIndexAsbInterfaceNumber = false) virtual
Send a control request by copy.
Request will be passed to the mdtPort's control request queue by copy. This method returns immediatly after enqueue, and don't wait until data was written.
Parameters
frame Frame containing request to send.
setwIndexAsbInterfaceNumber If true, wIndex will be set with USB port's current bInterfaceNumber
Returns
0 on success or value < 0 on error. In this implementation, the only possible error is mdtAbstractPort::WriteQueueEmpty . Some subclass can return a frame ID on success, or a other error. See subclass documentation for details.
Precondition
Port must be set with setPort() with a mdtUsbPort (or subclass) before use of this method.
Subclass notes:
This method can be reimplemented in subclass if needed. Typically usefull if a frame ID must be generated for each request (f.ex. bTag on USBTMC). A frame must be taken from port's request frames pool with mdtAbstractPort::controlFramesPool() dequeue() method (see Qt's QQueue documentation for more details on dequeue()), then added to port's request queue with mdtAbstractPort::addControlRequest() . If protocol supports frame identification (like USBTMC's bTag), it should be returned here and incremented.
Definition at line 236 of file mdtUsbPortManager.cpp.
References mdtUsbPort::addControlRequest(), mdtFrameUsbControl::bmRequestType(), mdtFrameUsbControl::bRequest(), mdtFrame::clear(), mdtFrameUsbControl::clearSub(), mdtAbstractPort::ControlCanceled, mdtUsbPort::controlFramesPool(), mdtFrameUsbControl::directionIsDeviceToHost(), mdtFrameUsbControl::encode(), mdtPortManager::isClosed(), mdtPortManager::isReady(), mdtPortManager::lockPortMutex(), mdtPortManager::pvPort, mdtFrameUsbControl::setbmRequestType(), mdtFrameUsbControl::setbRequest(), mdtFrameUsbControl::setDirectionDeviceToHost(), mdtFrameUsbControl::setwIndex(), mdtFrameUsbControl::setwLength(), mdtFrameUsbControl::setwValue(), mdtPortManager::unlockPortMutex(), mdtFrameUsbControl::wIndex(), mdtFrameUsbControl::wLength(), and mdtFrameUsbControl::wValue().
Referenced by mdtUsbtmcPortManager::sendReadStatusByteRequest().
bool mdtUsbPortManager::start () virtual
Open the port.
Overloads mdtPortManager::start().
Will construct the thread if not allready exists. This is because mdtUsbtmcPortManager uses a different thread, so this task can not be done in constructor.
Internally, mdtPortManager::start() is called.
Reimplemented from mdtPortManager.
Definition at line 181 of file mdtUsbPortManager.cpp.
References mdtPortManager::addThread(), fromThreadControlResponseReaden(), mdtPortManager::pvPort, mdtPortManager::pvThreads, mdtUsbPortThread::setPort(), mdtPortManager::start(), and mdtUsbPortThread::usbPort().
bool mdtUsbPortManager::waitReadenControlResponse ()
Wait until a control response is readen.
This method will return when a control response was readen.
Internally, a couple of sleep and process event are called, so Qt's event loop will not be broken.
This method can return if timeout occurs, or for other reason depending on specific port (port timeout, read canceled, ...).
Returns
True if Ok, false on timeout
Todo:
Adapt using internal timeouts + errors system
Definition at line 293 of file mdtUsbPortManager.cpp.
References mdtPortManager::isClosed(), and mdtPortManager::pvPort.
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbPortManager.h
src/mdtport/mdtUsbPortManager.cpp