Multi diag tools: mdtCodecScpi Class Reference
mdtCodecScpi Class Reference
SCPI codec.
#include <mdtCodecScpi.h>
Public Member Functions
mdtCodecScpi ()
Constructor.
mdtScpiIdnResponse decodeIdn (const QByteArray &data)
Decode *IDN? response.
mdtValueBool decodeValueBool (const QByteArray &data)
Decode a boolean value.
mdtValueInt decodeValueInt (const QByteArray &data)
Decode a integer value.
mdtValueDouble decodeValueDouble (const QByteArray &data)
Decode a decimal value.
mdtError decodeDeviceError (const QByteArray &data, const QString &errorText=QString())
Decode device error.
mdtScpiFunctionFarameter decodeFunctionParameters (const QByteArray &data)
Decode <function> <parameters> response.
mdtError lastError () const
Get last error.
Protected Attributes
mdtError pvLastError
Detailed Description
SCPI codec.
Definition at line 113 of file mdtCodecScpi.h.
Constructor & Destructor Documentation
mdtCodecScpi::mdtCodecScpi () inline
Constructor.
Definition at line 119 of file mdtCodecScpi.h.
Member Function Documentation
mdtError mdtCodecScpi::decodeDeviceError (const QByteArray & data, const QString & errorText = QString())
Decode device error.
See SCPI 1999.0 , volume 2, section 21.8 Note: this function supports only 1 error
Parameters
data data returned from device
errorText Text to set in error. If empty, a default text will be set.
Returns
Error that contains device error as system error. If parsing failed, a empty error is returned (error level will be NoError)
Definition at line 203 of file mdtCodecScpi.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtError::setSystemError(), and mdtAlgorithms::splitString().
Referenced by mdtDeviceScpi::getDeviceError().
mdtScpiFunctionFarameter mdtCodecScpi::decodeFunctionParameters (const QByteArray & data)
Decode <function> <parameters> response.
See SCPI 1999.0 , volume 2, section 3
Definition at line 237 of file mdtCodecScpi.cpp.
References mdtError::commit(), decodeValueDouble(), mdtError::Error, mdtScpiFunctionFarameter::functionRaw, mdtValueDouble::isNull(), MDT_ERROR_SET_SRC, mdtScpiFunctionFarameter::parametersDouble, mdtScpiFunctionFarameter::parametersRaw, pvLastError, mdtError::setError(), and mdtValueDouble::value().
Referenced by mdtDeviceU3606A::getMeasureConfiguration().
mdtScpiIdnResponse mdtCodecScpi::decodeIdn (const QByteArray & data)
Decode *IDN? response.
Definition at line 104 of file mdtCodecScpi.cpp.
References mdtError::commit(), mdtError::Error, mdtScpiIdnResponse::firmwareLevel, mdtScpiIdnResponse::manufacturer, MDT_ERROR_SET_SRC, mdtScpiIdnResponse::model, pvLastError, mdtScpiIdnResponse::serial, and mdtError::setError().
mdtValueBool mdtCodecScpi::decodeValueBool (const QByteArray & data)
Decode a boolean value.
Will interpret 1 as true, 0 as false
Definition at line 124 of file mdtCodecScpi.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
mdtValueDouble mdtCodecScpi::decodeValueDouble (const QByteArray & data)
Decode a decimal value.
See SCPI 1999.0 , volume 3, section 3.4.1, 3.4.2 3.4.4, 3.4.5 and 3.4.6 Note: this function assumes decimal format, not octal and not hexadecimal.
If data contains a value <= -9.9e37 or >= 9.9e37, returned value will have OL flag set, and also contains a infinity value. If data contains a value == 9.91e37, returned value will be NaN See SCPI 1999.0 , volume 1, section 7.2.1.4 and 7.2.1.5 for details.
Definition at line 162 of file mdtCodecScpi.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtValueDouble::setValue().
Referenced by decodeFunctionParameters(), and mdtDeviceU3606A::getMeasureValue().
mdtValueInt mdtCodecScpi::decodeValueInt (const QByteArray & data)
Decode a integer value.
See SCPI 1999.0 , volume 3, section 3.4.4, 3.4.5 and 3.4.6
Definition at line 140 of file mdtCodecScpi.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
mdtError mdtCodecScpi::lastError () const inline
Get last error.
Definition at line 168 of file mdtCodecScpi.h.
References pvLastError.
Referenced by mdtDeviceU3606A::getMeasureValue().
Member Data Documentation
mdtError mdtCodecScpi::pvLastError protected
Definition at line 175 of file mdtCodecScpi.h.
Referenced by decodeDeviceError(), decodeFunctionParameters(), decodeIdn(), decodeValueBool(), decodeValueDouble(), decodeValueInt(), and lastError().
The documentation for this class was generated from the following files:
src/mdtutils/mdtCodecScpi.h
src/mdtutils/mdtCodecScpi.cpp