Multi diag tools: mdtTtAbstractTestWidget Class Reference
mdtTtAbstractTestWidget Class Reference
Base to create a test widget.
#include <mdtTtAbstractTestWidget.h>
Public Slots
virtual void createTest ()
Create a new test.
virtual void openTest ()
Open a existing test.
virtual void saveTest ()
Save current test.
Signals
void testItemTableSet ()
Emited when test item table was set and select was successfull.
void testDataChanged (const QSqlRecord &data)
Emited when test data has changed.
Public Member Functions
mdtTtAbstractTestWidget (QSqlDatabase db, QWidget *parent=0)
Constructor.
virtual bool init ()
Do some initialization.
void setTestUiWidget (QWidget *widget)
All childs contained in widget that have a name prefixed fld_ will be mapped to corresponding fields in Test_tbl.
QSqlDatabase database ()
Get database instance.
std::shared_ptr< QSqlTableModel > testItemViewTableModel ()
Get table model to access data in TestItem_view.
std::shared_ptr
< mdtTtTestNodeManager > testNodeManager ()
Get test node manager object.
std::shared_ptr< mdtTtTest > test ()
Get test object.
mdtTtTestData testData () const
Get test data.
bool testIsEmpty () const
Check if a test is empty.
bool testIsSaved () const
Check if test is saved.
Protected Member Functions
bool removeTestIfEmpty ()
Remove current test if it is empty.
void displayLastError ()
Display last error to the user.
Protected Attributes
mdtError pvLastError
Contains last error that occured.
Detailed Description
Base to create a test widget.
Definition at line 42 of file mdtTtAbstractTestWidget.h.
Constructor & Destructor Documentation
mdtTtAbstractTestWidget::mdtTtAbstractTestWidget (QSqlDatabase db, QWidget * parent = 0)
Constructor.
Definition at line 33 of file mdtTtAbstractTestWidget.cpp.
References mdtAbstractSqlWidget::setAskUserBeforRevert(), mdtAbstractSqlWidget::setModel(), and testDataChanged().
Member Function Documentation
void mdtTtAbstractTestWidget::createTest () virtual slot
Create a new test.
This default implmementation will first check if current test is clean (saved, ...), and warn the user if not. Then (if test is clean, or user choosed to not keep it), user can select a test model to use. Finaly, test is created, based on selected test model.
Definition at line 82 of file mdtTtAbstractTestWidget.cpp.
References mdtSqlTableSelection::data(), database(), displayLastError(), mdtSqlTableSelection::isEmpty(), pvLastError, removeTestIfEmpty(), mdtAbstractSqlWidget::revert(), mdtSqlTableSelection::rowCount(), mdtSqlFormWidget::setCurrentIndex(), testIsSaved(), and mdtSqlFormWidget::toFirst().
QSqlDatabase mdtTtAbstractTestWidget::database () inline
Get database instance.
Definition at line 69 of file mdtTtAbstractTestWidget.h.
Referenced by createTest(), and openTest().
void mdtTtAbstractTestWidget::displayLastError () protected
Display last error to the user.
Definition at line 227 of file mdtTtAbstractTestWidget.cpp.
References mdtError::levelIcon(), pvLastError, mdtError::systemText(), and mdtError::text().
Referenced by createTest(), openTest(), and saveTest().
bool mdtTtAbstractTestWidget::init () virtual
Do some initialization.
Will setup test data and table models for test item view and table.
If testUiWidget is valid,
Definition at line 45 of file mdtTtAbstractTestWidget.cpp.
References pvLastError, and mdtSqlFormWidget::setCurrentIndex().
Referenced by mdtTtBasicTester::setup().
void mdtTtAbstractTestWidget::openTest () virtual slot
Open a existing test.
This default implmementation will first check if current test is clean (saved, ...), and warn the user if not. Then (if test is clean, or user choosed to not keep it), user can select a test. Finaly, selected test is set as current test.
Definition at line 132 of file mdtTtAbstractTestWidget.cpp.
References mdtSqlTableSelection::data(), database(), displayLastError(), mdtSqlTableSelection::isEmpty(), removeTestIfEmpty(), mdtAbstractSqlWidget::revert(), mdtSqlTableSelection::rowCount(), testIsSaved(), and mdtSqlFormWidget::toFirst().
bool mdtTtAbstractTestWidget::removeTestIfEmpty () protected
Remove current test if it is empty.
see testIsEmpty()
void mdtTtAbstractTestWidget::setDutSerialNumber(const QString & value) { QString str = value.trimmed(); if(str.isEmpty()){ setTestDataValue("DutSerialNumber", QVariant()); }else{ setTestDataValue("DutSerialNumber", str); } }
Definition at line 215 of file mdtTtAbstractTestWidget.cpp.
References pvLastError, and testIsEmpty().
Referenced by createTest(), and openTest().
void mdtTtAbstractTestWidget::saveTest () virtual slot
Save current test.
Definition at line 188 of file mdtTtAbstractTestWidget.cpp.
References displayLastError(), pvLastError, and mdtAbstractSqlWidget::submitAndWait().
void mdtTtAbstractTestWidget::setTestUiWidget (QWidget * widget)
All childs contained in widget that have a name prefixed fld_ will be mapped to corresponding fields in Test_tbl.
Definition at line 58 of file mdtTtAbstractTestWidget.cpp.
References mdtSqlFormWidget::mapFormWidgets(), mdtSqlFormWidget::setCurrentIndex(), and mdtAbstractSqlWidget::start().
Referenced by mdtTtBasicTesterWindow::init().
std::shared_ptr<mdtTtTest> mdtTtAbstractTestWidget::test () inline
Get test object.
Definition at line 81 of file mdtTtAbstractTestWidget.h.
mdtTtTestData mdtTtAbstractTestWidget::testData () const inline
Get test data.
Note: return cached data (will not get them from database).
Definition at line 87 of file mdtTtAbstractTestWidget.h.
void mdtTtAbstractTestWidget::testDataChanged (const QSqlRecord & data) signal
Emited when test data has changed.
date comes from Test_view
Referenced by mdtTtAbstractTestWidget().
bool mdtTtAbstractTestWidget::testIsEmpty () const
Check if a test is empty.
When creating a new test, it must be directly stored in database. This is because test items must allways be created.
A test is empty if:
In Test_tbl: only Id_PK, TestModel_Id_FK and Date are set
In each related item in Test_tbl: only Id_PK, Test_Id_FK and TestModelItem_Id_FK are set
Definition at line 66 of file mdtTtAbstractTestWidget.cpp.
References mdtAbstractSqlWidget::allDataAreSaved().
Referenced by removeTestIfEmpty().
bool mdtTtAbstractTestWidget::testIsSaved () const
Check if test is saved.
A test is saved if all cached data regarding Test_tbl and TestItem_tbl are stored in database.
Definition at line 74 of file mdtTtAbstractTestWidget.cpp.
References mdtAbstractSqlWidget::allDataAreSaved().
Referenced by createTest(), and openTest().
void mdtTtAbstractTestWidget::testItemTableSet () signal
Emited when test item table was set and select was successfull.
This can be used to setup a QTableView, a mdtSqlTableWidget, or what else (f.ex. resize or rename columns, etc...).
std::shared_ptr<QSqlTableModel> mdtTtAbstractTestWidget::testItemViewTableModel () inline
Get table model to access data in TestItem_view.
Definition at line 73 of file mdtTtAbstractTestWidget.h.
Referenced by mdtTtBasicTesterWindow::mdtTtBasicTesterWindow().
std::shared_ptr<mdtTtTestNodeManager> mdtTtAbstractTestWidget::testNodeManager () inline
Get test node manager object.
Definition at line 77 of file mdtTtAbstractTestWidget.h.
Referenced by mdtTtBasicTesterWindow::mdtTtBasicTesterWindow().
Member Data Documentation
mdtError mdtTtAbstractTestWidget::pvLastError protected
Contains last error that occured.
Definition at line 157 of file mdtTtAbstractTestWidget.h.
Referenced by createTest(), displayLastError(), init(), mdtTtBasicTester::lastError(), removeTestIfEmpty(), and saveTest().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtAbstractTestWidget.h
src/mdttools/mdttesttool/mdtTtAbstractTestWidget.cpp