Multi diag tools: mdtPortConfigWidget Class Reference
mdtPortConfigWidget Class Reference
#include <mdtPortConfigWidget.h>
Public Member Functions
mdtPortConfigWidget (QWidget *parent=0)
void displayConfig (mdtPortConfig &config)
Read the config instance and update GUI.
void updateConfig (mdtPortConfig &config)
Get GUI's selected options and update config.
Additional Inherited Members
Public Attributes inherited from Ui_mdtPortConfigWidget
QGridLayout * gridLayout_3
QLabel * lbFrameType
QComboBox * cbFrameType
QSpacerItem * horizontalSpacer_2
QLabel * lbEndOfFrameSeq
QComboBox * cbEndOfFrameSeq
QSpacerItem * horizontalSpacer
QHBoxLayout * horizontalLayout
QGroupBox * gbReadOptions
QVBoxLayout * verticalLayout
QFormLayout * formLayout
QLabel * lbReadFrameSize
QSpinBox * sbReadFrameSize
QLabel * lbReadQueueSize
QSpinBox * sbReadQueueSize
QLabel * lbReadTimeout
QSpinBox * sbReadTimeout
QCheckBox * cbUseReadTimeoutProtocol
QSpacerItem * verticalSpacer
QGroupBox * gbWriteOptions
QVBoxLayout * verticalLayout_2
QFormLayout * formLayout_2
QLabel * lbWriteFrameSize
QSpinBox * sbWriteFrameSize
QLabel * lbWriteQueueSize
QSpinBox * sbWriteQueueSize
QLabel * lbWriteTimeout
QSpinBox * sbWriteTimeout
QLabel * lbWriteInterbyteWaitTime
QSpinBox * sbWriteInterbyteWaitTime
QLabel * lbWriteInterframeTime
QSpinBox * sbWriteInterframeTime
QCheckBox * cbBytePerByteWrite
QSpacerItem * verticalSpacer_2
Detailed Description
Definition at line 28 of file mdtPortConfigWidget.h.
Constructor & Destructor Documentation
mdtPortConfigWidget::mdtPortConfigWidget (QWidget * parent = 0)
Definition at line 28 of file mdtPortConfigWidget.cpp.
References Ui_mdtPortConfigWidget::setupUi().
Member Function Documentation
void mdtPortConfigWidget::displayConfig (mdtPortConfig & config)
Read the config instance and update GUI.
Definition at line 34 of file mdtPortConfigWidget.cpp.
References mdtPortConfig::bytePerByteWrite(), Ui_mdtPortConfigWidget::cbBytePerByteWrite, Ui_mdtPortConfigWidget::cbEndOfFrameSeq, Ui_mdtPortConfigWidget::cbFrameType, Ui_mdtPortConfigWidget::cbUseReadTimeoutProtocol, mdtPortConfig::endOfFrameSeq(), mdtPortConfig::frameType(), mdtFrame::FT_ASCII, mdtFrame::FT_MODBUS_TCP, mdtFrame::FT_RAW, mdtFrame::FT_RAW_TOP, mdtFrame::FT_USBTMC, mdtPortConfig::readFrameSize(), mdtPortConfig::readQueueSize(), mdtPortConfig::readTimeout(), Ui_mdtPortConfigWidget::sbReadFrameSize, Ui_mdtPortConfigWidget::sbReadQueueSize, Ui_mdtPortConfigWidget::sbReadTimeout, Ui_mdtPortConfigWidget::sbWriteFrameSize, Ui_mdtPortConfigWidget::sbWriteInterbyteWaitTime, Ui_mdtPortConfigWidget::sbWriteInterframeTime, Ui_mdtPortConfigWidget::sbWriteQueueSize, Ui_mdtPortConfigWidget::sbWriteTimeout, mdtPortConfig::useReadTimeoutProtocol(), mdtPortConfig::writeFrameSize(), mdtPortConfig::writeInterbyteTime(), mdtPortConfig::writeInterframeTime(), mdtPortConfig::writeQueueSize(), and mdtPortConfig::writeTimeout().
Referenced by updateConfig().
void mdtPortConfigWidget::updateConfig (mdtPortConfig & config)
Get GUI's selected options and update config.
Once done, the config is read again and displayed, so the user can see what was really applied.
Definition at line 88 of file mdtPortConfigWidget.cpp.
References Ui_mdtPortConfigWidget::cbBytePerByteWrite, Ui_mdtPortConfigWidget::cbEndOfFrameSeq, Ui_mdtPortConfigWidget::cbFrameType, Ui_mdtPortConfigWidget::cbUseReadTimeoutProtocol, displayConfig(), mdtPortConfig::frameType(), mdtFrame::FT_ASCII, mdtFrame::FT_MODBUS_TCP, mdtFrame::FT_RAW, mdtFrame::FT_RAW_TOP, Ui_mdtPortConfigWidget::sbReadFrameSize, Ui_mdtPortConfigWidget::sbReadQueueSize, Ui_mdtPortConfigWidget::sbReadTimeout, Ui_mdtPortConfigWidget::sbWriteFrameSize, Ui_mdtPortConfigWidget::sbWriteInterbyteWaitTime, Ui_mdtPortConfigWidget::sbWriteInterframeTime, Ui_mdtPortConfigWidget::sbWriteQueueSize, Ui_mdtPortConfigWidget::sbWriteTimeout, mdtPortConfig::setBytePerByteWrite(), mdtPortConfig::setEndOfFrameSeq(), mdtPortConfig::setFrameType(), mdtPortConfig::setReadFrameSize(), mdtPortConfig::setReadQueueSize(), mdtPortConfig::setReadTimeout(), mdtPortConfig::setUseReadTimeoutProtocol(), mdtPortConfig::setWriteFrameSize(), mdtPortConfig::setWriteInterframeTime(), mdtPortConfig::setWriteQueueSize(), and mdtPortConfig::setWriteTimeout().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortConfigWidget.h
src/mdtport/mdtPortConfigWidget.cpp