Multi diag tools: mdtPortConfig Class Reference
mdtPortConfig Class Reference
#include <mdtPortConfig.h>
Public Member Functions
mdtPortConfig ()
virtual ~mdtPortConfig ()
virtual void setDefault ()
Set default configuration.
void setReadFrameSize (int size)
Set the read frame size.
int readFrameSize () const
Get the read frame size.
void setReadQueueSize (int size)
Set the read Queue size.
int readQueueSize () const
Get the read Queue size.
void setUseReadTimeoutProtocol (bool use)
Use the read timeout protocol.
bool useReadTimeoutProtocol () const
Know if read timeout protocol must be used.
void setReadTimeout (int timeout)
Set the read timeout.
int readTimeout () const
Get read timeout.
void setWriteInterframeTime (int time)
Set the write interframe time.
int writeInterframeTime () const
Get the write interframe time [ms].
void setWriteTimeout (int timeout)
Set the write timeout.
int writeTimeout () const
Get write timeout.
void setWriteFrameSize (int size)
Set the write frame size.
int writeFrameSize () const
Get the read frame size.
void setWriteQueueSize (int size)
Set the read Queue size.
int writeQueueSize () const
Get the write Queue size.
void setFrameType (const mdtFrame::type_t type)
Set frame type.
mdtFrame::type_t frameType () const
Get frame type.
void setEndOfFrameSeq (const QByteArray &seq)
Set the end of frame sequence (applies on ASCII frames)
void setEndOfFrameSeq (char c)
Set the end of frame sequence (applies on ASCII frames)
QByteArray endOfFrameSeq () const
Get the end of frame sequence.
void setBytePerByteWrite (bool on, int waitTime)
Set the byte per byte write On/Off.
bool bytePerByteWrite () const
Get byte per byte write flag (On/Off)
int writeInterbyteTime () const
Get the write time between bytes [ms].
void setConnectTimeout (int timeout)
Set the connection timeout.
int connectTimeout () const
Get the connection timeout.
void setConnectMaxTry (int maxTry)
Set the maximum connection try.
int connectMaxTry () const
Get the maximum connection try.
bool operator== (const mdtPortConfig &other)
bool operator!= (const mdtPortConfig &other)
Protected Member Functions
bool matches (const mdtPortConfig &other)
Protected Attributes
int pvReadFrameSize
int pvReadQueueSize
bool pvUseReadTimeoutProtocol
int pvReadTimeout
int pvWriteFrameSize
int pvWriteQueueSize
int pvWriteInterbyteTime
int pvWriteInterframeTime
int pvWriteTimeout
mdtFrame::type_t pvFrameType
QByteArray pvEndOfFrameSeq
bool pvBytePerByteWrite
int pvConnectMaxTry
int pvConnectTimeout
Detailed Description
Definition at line 28 of file mdtPortConfig.h.
Constructor & Destructor Documentation
mdtPortConfig::mdtPortConfig ()
Definition at line 23 of file mdtPortConfig.cpp.
References setDefault().
mdtPortConfig::~mdtPortConfig () virtual
Definition at line 28 of file mdtPortConfig.cpp.
Member Function Documentation
bool mdtPortConfig::bytePerByteWrite () const
Get byte per byte write flag (On/Off)
See Also
setBytePerByteWrite()
Definition at line 170 of file mdtPortConfig.cpp.
References pvBytePerByteWrite.
Referenced by mdtPortConfigWidget::displayConfig().
int mdtPortConfig::connectMaxTry () const
Get the maximum connection try.
See setConnectMaxTry().
Definition at line 195 of file mdtPortConfig.cpp.
References pvConnectMaxTry.
Referenced by mdtPortThreadHelperSocket::setSocket(), and mdtPortThread::start().
int mdtPortConfig::connectTimeout () const
Get the connection timeout.
See setConnectTimeout().
Definition at line 185 of file mdtPortConfig.cpp.
References pvConnectTimeout.
Referenced by mdtPortThreadHelperSocket::setSocket(), and mdtPortThread::start().
QByteArray mdtPortConfig::endOfFrameSeq () const
Get the end of frame sequence.
See Also
setEndOfFrameSeq()
Definition at line 159 of file mdtPortConfig.cpp.
References pvEndOfFrameSeq.
Referenced by mdtPortConfigWidget::displayConfig(), and mdtAbstractPort::initQueues().
mdtFrame::type_t mdtPortConfig::frameType () const
Get frame type.
See Also
setFrameType()
Definition at line 143 of file mdtPortConfig.cpp.
References pvFrameType.
Referenced by mdtPortConfigWidget::displayConfig(), mdtAbstractPort::initQueues(), and mdtPortConfigWidget::updateConfig().
bool mdtPortConfig::matches (const mdtPortConfig & other) protected
Definition at line 210 of file mdtPortConfig.cpp.
References pvConnectMaxTry, pvConnectTimeout, pvEndOfFrameSeq, pvFrameType, pvReadFrameSize, pvReadQueueSize, pvReadTimeout, pvWriteFrameSize, pvWriteInterbyteTime, pvWriteQueueSize, and pvWriteTimeout.
Referenced by operator!=(), and operator==().
bool mdtPortConfig::operator!= (const mdtPortConfig & other)
Definition at line 205 of file mdtPortConfig.cpp.
References matches().
bool mdtPortConfig::operator== (const mdtPortConfig & other)
Definition at line 200 of file mdtPortConfig.cpp.
References matches().
int mdtPortConfig::readFrameSize () const
Get the read frame size.
See Also
setReadFrameSize()
Definition at line 57 of file mdtPortConfig.cpp.
References pvReadFrameSize.
Referenced by mdtPortConfigWidget::displayConfig().
int mdtPortConfig::readQueueSize () const
Get the read Queue size.
See Also
setReadQueueSize()
Definition at line 69 of file mdtPortConfig.cpp.
References pvReadQueueSize.
Referenced by mdtPortConfigWidget::displayConfig(), and mdtAbstractPort::initQueues().
int mdtPortConfig::readTimeout () const
Get read timeout.
Returns
Read timout [ms]
Definition at line 89 of file mdtPortConfig.cpp.
References pvReadTimeout.
Referenced by mdtPortConfigWidget::displayConfig(), mdtDeviceModbus::mdtDeviceModbus(), mdtDeviceScpi::mdtDeviceScpi(), mdtPortThreadHelperSocket::setSocket(), and mdtAbstractPort::waitForReadyRead().
void mdtPortConfig::setBytePerByteWrite (bool on, int waitTime)
Set the byte per byte write On/Off.
It can happen that a (very) slow device needs time after any received byte.
Enable this function in this situation.
Parameters
on True will enable this mode.
waitTime Wait time between two bytes write [ms]
See Also
mdtPortWriteThread
Definition at line 164 of file mdtPortConfig.cpp.
References pvBytePerByteWrite, and pvWriteInterbyteTime.
Referenced by mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setConnectMaxTry (int maxTry)
Set the maximum connection try.
This is used by port witch support disconnection (USB, TCP socket)
Definition at line 190 of file mdtPortConfig.cpp.
References pvConnectMaxTry.
void mdtPortConfig::setConnectTimeout (int timeout)
Set the connection timeout.
Parameters
timeout [ms]
This is used by port witch support disconnection (USB, TCP socket)
Definition at line 180 of file mdtPortConfig.cpp.
References pvConnectTimeout.
void mdtPortConfig::setDefault () virtual
Set default configuration.
Default configuration is:
Read and write frame size: 1024
Read and write queue size: 10
Use read timeout protocol: false
Read timout: 5000 [ms]
Write timout: -1 (infinite)
Frame type: RAW
En of frame sequence: LF (ASCII 0x0A)
Write interframe time: 0 [ms]
Byte per byte write: Off
Write interbyte time: 0 [ms]
Connect timeout: 5000 [ms]
Connect max try: 10
Reimplemented in mdtSerialPortConfig.
Definition at line 31 of file mdtPortConfig.cpp.
References mdtFrame::FT_RAW, pvBytePerByteWrite, pvConnectMaxTry, pvConnectTimeout, pvEndOfFrameSeq, pvFrameType, pvReadFrameSize, pvReadQueueSize, pvReadTimeout, pvUseReadTimeoutProtocol, pvWriteFrameSize, pvWriteInterbyteTime, pvWriteInterframeTime, pvWriteQueueSize, and pvWriteTimeout.
Referenced by mdtPortConfig(), and mdtSerialPortConfig::setDefault().
void mdtPortConfig::setEndOfFrameSeq (const QByteArray & seq)
Set the end of frame sequence (applies on ASCII frames)
Definition at line 148 of file mdtPortConfig.cpp.
References pvEndOfFrameSeq.
Referenced by mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setEndOfFrameSeq (char c)
Set the end of frame sequence (applies on ASCII frames)
This is an overloaded method
See Also
setEndOfFrameSeq(const QByteArray &)
Definition at line 153 of file mdtPortConfig.cpp.
References pvEndOfFrameSeq.
void mdtPortConfig::setFrameType (const mdtFrame::type_t type)
Set frame type.
Frame type can be an ASCII frame, binary frame, ...
See Also
mdtFrame
Definition at line 138 of file mdtPortConfig.cpp.
References pvFrameType.
Referenced by mdtModbusTcpPortManager::mdtModbusTcpPortManager(), mdtUsbtmcPortManager::mdtUsbtmcPortManager(), and mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setReadFrameSize (int size)
Set the read frame size.
Frame size is the maximum number of bytes that can be stored before a frame is full. A full frame that never received a EOF condition is considered invalid
See Also
mdtFrame
Precondition
size must be a positive value
Definition at line 50 of file mdtPortConfig.cpp.
References pvReadFrameSize.
Referenced by mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceU3606A::mdtDeviceU3606A(), mdtModbusTcpPortManager::mdtModbusTcpPortManager(), and mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setReadQueueSize (int size)
Set the read Queue size.
A queue contain several frames. This parameter gives a limit of the number of frame that can be received before they are threated
Precondition
size must be a positive value
Definition at line 62 of file mdtPortConfig.cpp.
References pvReadQueueSize.
Referenced by mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceU3606A::mdtDeviceU3606A(), and mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setReadTimeout (int timeout)
Set the read timeout.
Parameters
timeout Read timout [ms]
Definition at line 84 of file mdtPortConfig.cpp.
References pvReadTimeout.
Referenced by mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceScpi::mdtDeviceScpi(), mdtDeviceU3606A::mdtDeviceU3606A(), mdtModbusTcpPortManager::mdtModbusTcpPortManager(), mdtUsbtmcPortManager::mdtUsbtmcPortManager(), and mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setUseReadTimeoutProtocol (bool use)
Use the read timeout protocol.
An example of read timeout protocol is MODBUS (over serial lines) RTU mode The mdtPortReadThread will use this parameter.
Parameters
use If true, read timeout protocol will be used.
Definition at line 74 of file mdtPortConfig.cpp.
References pvUseReadTimeoutProtocol.
Referenced by mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setWriteFrameSize (int size)
Set the write frame size.
Frame size is the maximum number of bytes that can be stored before a frame is full.
See Also
mdtFrame
Precondition
size must be a positive value
Definition at line 114 of file mdtPortConfig.cpp.
References pvWriteFrameSize.
Referenced by mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceU3606A::mdtDeviceU3606A(), mdtModbusTcpPortManager::mdtModbusTcpPortManager(), and mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setWriteInterframeTime (int time)
Set the write interframe time.
If this time is > 0 , the mdtPortWriteThread will wait defined time before sending a new frame. This is usefull in timeout based protocols, like Modbus RTU.
Parameters
time Interframe time [ms]
Definition at line 94 of file mdtPortConfig.cpp.
References pvWriteInterframeTime.
Referenced by mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setWriteQueueSize (int size)
Set the read Queue size.
A queue contain several frames. This parameter gives a limit of the number of frame that can be enqueued to serial port output.
Precondition
size must be a positive value
Definition at line 126 of file mdtPortConfig.cpp.
References pvWriteQueueSize.
Referenced by mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceU3606A::mdtDeviceU3606A(), mdtModbusTcpPortManager::mdtModbusTcpPortManager(), and mdtPortConfigWidget::updateConfig().
void mdtPortConfig::setWriteTimeout (int timeout)
Set the write timeout.
Parameters
timeout Write timout [ms]
Definition at line 104 of file mdtPortConfig.cpp.
References pvWriteTimeout.
Referenced by mdtPortConfigWidget::updateConfig().
bool mdtPortConfig::useReadTimeoutProtocol () const
Know if read timeout protocol must be used.
See Also
setUseReadTimeoutProtocol()
Definition at line 79 of file mdtPortConfig.cpp.
References pvUseReadTimeoutProtocol.
Referenced by mdtPortConfigWidget::displayConfig().
int mdtPortConfig::writeFrameSize () const
Get the read frame size.
See Also
setWriteFrameSize()
Definition at line 121 of file mdtPortConfig.cpp.
References pvWriteFrameSize.
Referenced by mdtPortConfigWidget::displayConfig().
int mdtPortConfig::writeInterbyteTime () const
Get the write time between bytes [ms].
See Also
setBytePerByteWrite()
Definition at line 175 of file mdtPortConfig.cpp.
References pvWriteInterbyteTime.
Referenced by mdtPortConfigWidget::displayConfig().
int mdtPortConfig::writeInterframeTime () const
Get the write interframe time [ms].
See Also
setWriteInterframeTime()
Definition at line 99 of file mdtPortConfig.cpp.
References pvWriteInterframeTime.
Referenced by mdtPortConfigWidget::displayConfig().
int mdtPortConfig::writeQueueSize () const
Get the write Queue size.
See Also
setWriteQueueSize()
Definition at line 133 of file mdtPortConfig.cpp.
References pvWriteQueueSize.
Referenced by mdtPortConfigWidget::displayConfig(), mdtAbstractPort::initQueues(), and mdtPortManager::openPort().
int mdtPortConfig::writeTimeout () const
Get write timeout.
Returns
Write timout [ms]
Definition at line 109 of file mdtPortConfig.cpp.
References pvWriteTimeout.
Referenced by mdtPortConfigWidget::displayConfig(), mdtDeviceModbus::mdtDeviceModbus(), mdtDeviceScpi::mdtDeviceScpi(), and mdtPortThreadHelperSocket::setSocket().
Member Data Documentation
bool mdtPortConfig::pvBytePerByteWrite protected
Definition at line 271 of file mdtPortConfig.h.
Referenced by bytePerByteWrite(), setBytePerByteWrite(), and setDefault().
int mdtPortConfig::pvConnectMaxTry protected
Definition at line 272 of file mdtPortConfig.h.
Referenced by connectMaxTry(), matches(), setConnectMaxTry(), and setDefault().
int mdtPortConfig::pvConnectTimeout protected
Definition at line 273 of file mdtPortConfig.h.
Referenced by connectTimeout(), matches(), setConnectTimeout(), and setDefault().
QByteArray mdtPortConfig::pvEndOfFrameSeq protected
Definition at line 270 of file mdtPortConfig.h.
Referenced by endOfFrameSeq(), matches(), setDefault(), and setEndOfFrameSeq().
mdtFrame::type_t mdtPortConfig::pvFrameType protected
Definition at line 269 of file mdtPortConfig.h.
Referenced by frameType(), matches(), setDefault(), and setFrameType().
int mdtPortConfig::pvReadFrameSize protected
Definition at line 260 of file mdtPortConfig.h.
Referenced by matches(), readFrameSize(), setDefault(), and setReadFrameSize().
int mdtPortConfig::pvReadQueueSize protected
Definition at line 261 of file mdtPortConfig.h.
Referenced by matches(), readQueueSize(), setDefault(), and setReadQueueSize().
int mdtPortConfig::pvReadTimeout protected
Definition at line 263 of file mdtPortConfig.h.
Referenced by matches(), readTimeout(), setDefault(), and setReadTimeout().
bool mdtPortConfig::pvUseReadTimeoutProtocol protected
Definition at line 262 of file mdtPortConfig.h.
Referenced by setDefault(), setUseReadTimeoutProtocol(), and useReadTimeoutProtocol().
int mdtPortConfig::pvWriteFrameSize protected
Definition at line 264 of file mdtPortConfig.h.
Referenced by matches(), setDefault(), setWriteFrameSize(), and writeFrameSize().
int mdtPortConfig::pvWriteInterbyteTime protected
Definition at line 266 of file mdtPortConfig.h.
Referenced by matches(), setBytePerByteWrite(), setDefault(), and writeInterbyteTime().
int mdtPortConfig::pvWriteInterframeTime protected
Definition at line 267 of file mdtPortConfig.h.
Referenced by setDefault(), setWriteInterframeTime(), and writeInterframeTime().
int mdtPortConfig::pvWriteQueueSize protected
Definition at line 265 of file mdtPortConfig.h.
Referenced by matches(), setDefault(), setWriteQueueSize(), and writeQueueSize().
int mdtPortConfig::pvWriteTimeout protected
Definition at line 268 of file mdtPortConfig.h.
Referenced by matches(), setDefault(), setWriteTimeout(), and writeTimeout().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortConfig.h
src/mdtport/mdtPortConfig.cpp