Multi diag tools: mdtSqlFieldHandlerLabel Class Reference
mdtSqlFieldHandlerLabel Class Reference
Public Member Functions
mdtSqlFieldHandlerLabel ()
void setLabel (QLabel *lb)
void setData (const QVariant &data)
QVariant data () const
bool isNull () const
void clear ()
QWidget * widget ()
void setReadOnly (bool readOnly)
Public Member Functions inherited from mdtSqlFieldHandlerAbstractDataWidget
virtual ~mdtSqlFieldHandlerAbstractDataWidget ()
virtual void setMaxLength (int maxLength)
virtual void setRange (qreal min, qreal max)
Detailed Description
Todo:
Implement other data editors
Definition at line 46 of file mdtSqlFieldHandler.cpp.
Constructor & Destructor Documentation
mdtSqlFieldHandlerLabel::mdtSqlFieldHandlerLabel ()
Definition at line 62 of file mdtSqlFieldHandler.cpp.
Member Function Documentation
void mdtSqlFieldHandlerLabel::clear () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 111 of file mdtSqlFieldHandler.cpp.
QVariant mdtSqlFieldHandlerLabel::data () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 99 of file mdtSqlFieldHandler.cpp.
Referenced by isNull(), and setData().
bool mdtSqlFieldHandlerLabel::isNull () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 105 of file mdtSqlFieldHandler.cpp.
References data().
void mdtSqlFieldHandlerLabel::setData (const QVariant & data) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 73 of file mdtSqlFieldHandler.cpp.
References data().
void mdtSqlFieldHandlerLabel::setLabel (QLabel * lb)
Definition at line 67 of file mdtSqlFieldHandler.cpp.
Referenced by mdtSqlFieldHandler::setDataWidget().
void mdtSqlFieldHandlerLabel::setReadOnly (bool readOnly) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 123 of file mdtSqlFieldHandler.cpp.
QWidget * mdtSqlFieldHandlerLabel::widget () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 117 of file mdtSqlFieldHandler.cpp.
The documentation for this class was generated from the following file:
src/mdtutilsgui/mdtSqlFieldHandler.cpp