Multi diag tools: mdtModbusHwNodeIdList Class Reference
mdtModbusHwNodeIdList Class Reference
List of mdtModbusHwNodeId.
#include <mdtModbusHwNodeId.h>
Public Member Functions
mdtModbusHwNodeIdList ()
Construct a empty ID list.
bool isEmpty () const
Check if ID list is empty.
int size () const
Get ID list size.
void clear ()
Clear.
void append (const mdtModbusHwNodeId &nid)
Append a ID at the end of the list.
const std::vector
< mdtModbusHwNodeId > & internalVector () const
Access internal vector.
bool contains (int id)
Check if given ID exists in list.
bool contains (const mdtModbusHwNodeId &mid)
Check if given ID exists in list.
Detailed Description
List of mdtModbusHwNodeId.
Todo:
Vu que l'on peut avoir plusieurs noeuds different, bitsCount et firstBit peuvent être différents. -> Adapter
Definition at line 211 of file mdtModbusHwNodeId.h.
Constructor & Destructor Documentation
mdtModbusHwNodeIdList::mdtModbusHwNodeIdList () inline
Construct a empty ID list.
Definition at line 217 of file mdtModbusHwNodeId.h.
Member Function Documentation
void mdtModbusHwNodeIdList::append (const mdtModbusHwNodeId & nid) inline
Append a ID at the end of the list.
Definition at line 242 of file mdtModbusHwNodeId.h.
References mdtModbusHwNodeId::isNull().
Referenced by mdtDeviceModbus::connectToDevice().
void mdtModbusHwNodeIdList::clear () inline
Clear.
Definition at line 235 of file mdtModbusHwNodeId.h.
bool mdtModbusHwNodeIdList::contains (int id) inline
Check if given ID exists in list.
Definition at line 269 of file mdtModbusHwNodeId.h.
Referenced by contains().
bool mdtModbusHwNodeIdList::contains (const mdtModbusHwNodeId & mid) inline
Check if given ID exists in list.
Definition at line 276 of file mdtModbusHwNodeId.h.
References contains(), mdtModbusHwNodeId::id(), and mdtModbusHwNodeId::isNull().
const std::vector<mdtModbusHwNodeId>& mdtModbusHwNodeIdList::internalVector () const inline
Access internal vector.
Can be used, for example, to iterate all IDs:
for(const auto & nid : list.internalVector()){
  if(nid.id() == 24){
    doSomeStuff(nid);
  }
}
Please take in accound that returned reference become invalid as soon as this mdtModbusHwNodeIdList object is destroyed.
Definition at line 262 of file mdtModbusHwNodeId.h.
Referenced by mdtModbusTcpPortManager::findMatchingToHostModebusHwNodeId().
bool mdtModbusHwNodeIdList::isEmpty () const inline
Check if ID list is empty.
Definition at line 221 of file mdtModbusHwNodeId.h.
Referenced by mdtModbusTcpPortManager::scan().
int mdtModbusHwNodeIdList::size () const inline
Get ID list size.
Definition at line 228 of file mdtModbusHwNodeId.h.
Referenced by mdtModbusTcpPortManager::scan().
The documentation for this class was generated from the following file:
src/mdtport/mdtModbusHwNodeId.h