Multi diag tools: mdtFrameCodecModbus Class Reference
mdtFrameCodecModbus Class Reference
Encode and decode MODBUS PDU NOTE: stockage des adresses durant Q/R ?
#include <mdtFrameCodecModbus.h>
Public Types
enum modbus_error_code_t {
UNKNOW_ERROR, ILLEGAL_FUNCTION = 1, ILLEGAL_DATA_ADDRESS, ILLEGAL_DATA_VALUE,
SLAVE_DEVICE_FAILURE, ACKNOWLEDGE, SLAVE_DEVICE_BUSY, RESERVE_ERROR_7,
MEMORY_PARITY_ERROR, RESERVE_ERROR_9, GATEWAY_PATH_UNAVAILABLE, GATEWAY_TARGET_RESPONSE
}
MODBUS response error code.
Public Member Functions
mdtFrameCodecModbus ()
#include <QDebug>
~mdtFrameCodecModbus ()
QByteArray encodeReadCoils (quint16 startAddress, quint16 n)
Encode a PDU according the ReadCoils function (FC 1, 0x01)
QByteArray encodeReadDiscreteInputs (quint16 startAddress, quint16 n)
Encode a PDU according the ReadDiscreteInputs function (FC 2, 0x02)
QByteArray encodeReadHoldingRegisters (quint16 startAddress, quint16 n)
Encode a PDU according the ReadHoldingRegisters function (FC 3, 0x03)
QByteArray encodeReadInputRegisters (quint16 startAddress, quint16 n)
Encode a PDU according the ReadInputRegisters function (FC 4, 0x04)
QByteArray encodeWriteSingleCoil (quint16 address, bool state)
Encode a PDU according the WriteSingleCoil function (FC 5, 0x05)
QByteArray encodeWriteSingleRegister (quint16 address, quint16 value)
Encode a PDU according the WriteSingleRegister function (FC 6, 0x06)
QByteArray encodeWriteMultipleCoils (quint16 startAddress, const QList< bool > &states)
Encode a PDU according the WriteMultipleCoils function (FC 15, 0x0F)
QByteArray encodeWriteMultipleRegisters (quint16 startAddress, const QList< int > &values)
Encode a PDU according the WriteMultipleRegisters function (FC 16, 0x10)
QByteArray encodeReadDeviceIdentification (quint8 objectId, bool individualAccess)
Encode a PDU according the ReadDeviceIdentification function (FC 43, 0x2B)
int decode (const QByteArray &pdu)
Decode a MODBUS PDU.
modbus_error_code_t lastModbusError ()
Get the last MODBUS error code returned.
Public Member Functions inherited from mdtFrameCodec
mdtFrameCodec ()
~mdtFrameCodec ()
const QList< QVariant > & values () const
Get the decoded values.
Additional Inherited Members
Protected Attributes inherited from mdtFrameCodec
QList< QVariant > pvValues
Detailed Description
Encode and decode MODBUS PDU NOTE: stockage des adresses durant Q/R ?
This class works only on MODBUS PDU. To transmit MODBUS/TCP frame, the resulting PDU can be sent using mdtFrameModbusTcp class, or received PDU decoded here.
References:
MODBUS Application Protocol Specification V1.1b
http://www.Modbus-IDA.org
See Also
mdtFrameCodec
mdtFrameModbusTcp
Definition at line 41 of file mdtFrameCodecModbus.h.
Member Enumeration Documentation
enum mdtFrameCodecModbus::modbus_error_code_t
MODBUS response error code.
Enumerator
UNKNOW_ERROR
Error is unknow from codec
ILLEGAL_FUNCTION
Code 0x01: Function is not allowed for the server
ILLEGAL_DATA_ADDRESS
Code 0x02: Request address is not in range of the server
ILLEGAL_DATA_VALUE
Code 0x03: Request value is not in allowed from server
SLAVE_DEVICE_FAILURE
Code 0x04: Unrecoverable failue on server
ACKNOWLEDGE
Code 0x05: Request accepted, but mor time is needed (server side) for response
SLAVE_DEVICE_BUSY
Code 0x06: Server busy, client should try to resend the query later
RESERVE_ERROR_7
Not used in current specification
MEMORY_PARITY_ERROR
Code 0x08: Parity error related to code function 20 and 21
RESERVE_ERROR_9
Not used in current specification
GATEWAY_PATH_UNAVAILABLE
Code 0x0A: Error from a gateway (misconfigured or overloaded)
GATEWAY_TARGET_RESPONSE
Code 0x0B: Error from a gateway: target device not present on network
Definition at line 47 of file mdtFrameCodecModbus.h.
Constructor & Destructor Documentation
mdtFrameCodecModbus::mdtFrameCodecModbus ()
#include <QDebug>
Definition at line 27 of file mdtFrameCodecModbus.cpp.
References UNKNOW_ERROR.
mdtFrameCodecModbus::~mdtFrameCodecModbus ()
Definition at line 32 of file mdtFrameCodecModbus.cpp.
Member Function Documentation
int mdtFrameCodecModbus::decode (const QByteArray & pdu)
Decode a MODBUS PDU.
This should reconize the function code in PDU, and call the appropriate decode methode (internal). Once decode is done, the values are available with mdtFrameCodec::values(). To know what was decoded, the function code is returned.
The values are stored in a QList<QVariant> , with format depending of the function code:
FC 1 (0x01), ReadCoils reply: digital outputs (coils) states as bool, sorted by ascending addresses. Note: the PDU contains the number of bytes returned by device, it's also not possible to know how many coils are concerned. For example, if a request was made for 5 coils, 1 byte is returned from device, values() will also contain 8 items.
FC 2 (0x02), ReadDiscreteInputs reply: digital input states as bool, sorted by ascending addresses.
FC 3 (0x03), ReadHoldingRegisters reply: analog output values as quint16, sorted by ascending addresses.
FC 4 (0x04), ReadInputRegisters reply: analog input values as quint16, sorted by ascending addresses.
FC 5 (0x05), WriteSingleCoil reply: first value is address as quint16, second value is the output state as bool.
FC 6 (0x06), WriteSingleRegister reply: analog output address and value, as quint16.
FC 15 (0x0F), WriteMultipleCoils reply: first value is starting address as quint16, second value is the number of output as quint16.
FC 16 (0x10), WriteMultipleRegisters reply: first value is starting address as quint16, second value is the number of output as quint16.
FC 43 (0x2B), ReadDeviceIdentification reply: first: more follows (bool), second: next Object Id (int), then couples of Object ID followed by Object value (f.ex: false, 0, 0, "Vendor Name", 1, "Product code", ...)
If PDU contains a error code, the list of values will be empty, and this error code will be returned.
If a MODBUS error code is decoded, this error code is returned as in frame (for. ex: 0x81 for a ReadCoils error) To know whitch MODBUS error was returned, use lastModbusError()
Parameters
pdu The MODBUS PDU to decode
Returns
Decoded function code, MODBUS error code or value < 0 on other error.
Definition at line 283 of file mdtFrameCodecModbus.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_FRAME_DECODE_ERROR, mdtFrameCodec::pvValues, and UNKNOW_ERROR.
Referenced by mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtModbusTcpPortManager::getRegisterValues(), and mdtModbusTcpPortManager::setRegisterValues().
QByteArray mdtFrameCodecModbus::encodeReadCoils (quint16 startAddress, quint16 n)
Encode a PDU according the ReadCoils function (FC 1, 0x01)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 36 of file mdtFrameCodecModbus.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FRAME_ENCODE_ERROR.
Referenced by mdtDeviceModbus::readDigitalOutput(), and mdtDeviceModbus::readDigitalOutputs().
QByteArray mdtFrameCodecModbus::encodeReadDeviceIdentification (quint8 objectId, bool individualAccess)
Encode a PDU according the ReadDeviceIdentification function (FC 43, 0x2B)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 256 of file mdtFrameCodecModbus.cpp.
QByteArray mdtFrameCodecModbus::encodeReadDiscreteInputs (quint16 startAddress, quint16 n)
Encode a PDU according the ReadDiscreteInputs function (FC 2, 0x02)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 60 of file mdtFrameCodecModbus.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FRAME_ENCODE_ERROR.
Referenced by mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtDeviceModbus::readDigitalInput(), and mdtDeviceModbus::readDigitalInputs().
QByteArray mdtFrameCodecModbus::encodeReadHoldingRegisters (quint16 startAddress, quint16 n)
Encode a PDU according the ReadHoldingRegisters function (FC 3, 0x03)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 84 of file mdtFrameCodecModbus.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FRAME_ENCODE_ERROR.
Referenced by mdtDeviceModbus::readAnalogOutput(), and mdtDeviceModbus::readAnalogOutputs().
QByteArray mdtFrameCodecModbus::encodeReadInputRegisters (quint16 startAddress, quint16 n)
Encode a PDU according the ReadInputRegisters function (FC 4, 0x04)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 108 of file mdtFrameCodecModbus.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FRAME_ENCODE_ERROR.
Referenced by mdtModbusTcpPortManager::getRegisterValues(), mdtDeviceModbus::readAnalogInput(), and mdtDeviceModbus::readAnalogInputs().
QByteArray mdtFrameCodecModbus::encodeWriteMultipleCoils (quint16 startAddress, const QList< bool > & states)
Encode a PDU according the WriteMultipleCoils function (FC 15, 0x0F)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 168 of file mdtFrameCodecModbus.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FRAME_ENCODE_ERROR.
Referenced by mdtDeviceModbus::writeDigitalOutputs().
QByteArray mdtFrameCodecModbus::encodeWriteMultipleRegisters (quint16 startAddress, const QList< int > & values)
Encode a PDU according the WriteMultipleRegisters function (FC 16, 0x10)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 222 of file mdtFrameCodecModbus.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FRAME_ENCODE_ERROR.
Referenced by mdtModbusTcpPortManager::setRegisterValues(), and mdtDeviceModbus::writeAnalogOutputs().
QByteArray mdtFrameCodecModbus::encodeWriteSingleCoil (quint16 address, bool state)
Encode a PDU according the WriteSingleCoil function (FC 5, 0x05)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 132 of file mdtFrameCodecModbus.cpp.
Referenced by mdtDeviceModbus::writeDigitalOutput().
QByteArray mdtFrameCodecModbus::encodeWriteSingleRegister (quint16 address, quint16 value)
Encode a PDU according the WriteSingleRegister function (FC 6, 0x06)
Please take a look at MODBUS specifications for more details.
Returns
A QByteArray containing the PDU, or a empty QByteArray on error.
Definition at line 152 of file mdtFrameCodecModbus.cpp.
Referenced by mdtDeviceModbus::writeAnalogOutput().
mdtFrameCodecModbus::modbus_error_code_t mdtFrameCodecModbus::lastModbusError ()
Get the last MODBUS error code returned.
Returns the error code according to the specification, part function/error codes (same value).
See Also
decode()
Definition at line 381 of file mdtFrameCodecModbus.cpp.
The documentation for this class was generated from the following files:
src/mdtutils/mdtFrameCodecModbus.h
src/mdtutils/mdtFrameCodecModbus.cpp