Multi diag tools: mdtDeviceContainer Class Reference
mdtDeviceContainer Class Reference
Contains different type of devices.
#include <mdtDeviceContainer.h>
Signals
void deviceAdded (std::shared_ptr< mdtDevice > device)
Emited when a new device was added.
void cleared ()
Emited when container was cleared.
Public Member Functions
mdtDeviceContainer (QObject *parent=0)
Construct a empty container.
template<typename T >
std::shared_ptr< T > addDevice (const QVariant &identification, const QString &name)
Create and add a new device.
template<typename T >
std::shared_ptr< T > device (const QVariant &identification)
Get device of type T and that has given identification.
int deviceCount () const
Get number of contained devices.
void clear ()
Remove all devices.
QList< std::shared_ptr
< mdtDevice > > allDevices ()
Get a list of all devices.
void disconnectFromDevices ()
Disconnect frome devices.
Detailed Description
Contains different type of devices.
For some applications, many devices of different type must be handled.
This class helps for this.
Definition at line 39 of file mdtDeviceContainer.h.
Constructor & Destructor Documentation
mdtDeviceContainer::mdtDeviceContainer (QObject * parent = 0)
Construct a empty container.
Definition at line 30 of file mdtDeviceContainer.cpp.
Member Function Documentation
template<typename T > std::shared_ptr<T> mdtDeviceContainer::addDevice (const QVariant & identification, const QString & name) inline
Create and add a new device.
Definition at line 51 of file mdtDeviceContainer.h.
References deviceAdded().
QList< shared_ptr< mdtDevice > > mdtDeviceContainer::allDevices ()
Get a list of all devices.
Note: list is rebuilt at each call of this method.
Definition at line 41 of file mdtDeviceContainer.cpp.
void mdtDeviceContainer::clear ()
Remove all devices.
Definition at line 35 of file mdtDeviceContainer.cpp.
References cleared().
void mdtDeviceContainer::cleared () signal
Emited when container was cleared.
Referenced by clear().
template<typename T > std::shared_ptr<T> mdtDeviceContainer::device (const QVariant & identification) inline
Get device of type T and that has given identification.
Definition at line 63 of file mdtDeviceContainer.h.
void mdtDeviceContainer::deviceAdded (std::shared_ptr< mdtDevice > device) signal
Emited when a new device was added.
Referenced by addDevice().
int mdtDeviceContainer::deviceCount () const inline
Get number of contained devices.
Definition at line 81 of file mdtDeviceContainer.h.
void mdtDeviceContainer::disconnectFromDevices ()
Disconnect frome devices.
Definition at line 54 of file mdtDeviceContainer.cpp.
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceContainer.h
src/mdtdevice/mdtDeviceContainer.cpp