Multi diag tools: mdtTtAbstractTester Class Reference
mdtTtAbstractTester Class Reference
Base to create a tester.
#include <mdtTtAbstractTester.h>
Public Slots
virtual void createTest ()
Create a new test.
virtual void openTest ()
Open a existing test.
virtual void saveTest ()
Save current test.
Signals
void testDataChanged (const QSqlRecord &data)
Emited when test data has changed.
Public Member Functions
mdtTtAbstractTester (QSqlDatabase db, QObject *parent=0)
Constructor.
virtual bool setup ()
Do setup.
bool setTestUiWidget (QWidget *widget)
All childs contained in widget that have a name prefixed fld_ will be mapped to corresponding fields in Test_view. They cann be written, but internally used mdtAbstractSqlTableController's submit() slot will not work. Data will be really stored in Test_tbl by saveTest().
bool start ()
Start state machines.
QSqlDatabase database ()
Get database instance.
std::shared_ptr
< mdtSqlDataWidgetController > testViewController ()
Access controller that acts on Test_view.
std::shared_ptr
< mdtSqlTableViewController > testItemViewController ()
Access controller that acts on TestItem_view.
std::shared_ptr
< mdtTtTestNodeManager > testNodeManager ()
Get test node manager object.
std::shared_ptr< mdtTtTest > test ()
Get test object.
bool testIsEmpty () const
Check if a test is empty.
bool testIsSaved () const
Check if test is saved.
Protected Member Functions
bool removeTestIfEmpty ()
Remove current test if it is empty.
bool removeCurrentTestPv ()
Remove current test.
void displayLastError ()
Display last error to the user.
Protected Attributes
mdtError pvLastError
Contains last error that occured.
Detailed Description
Base to create a tester.
Typical usage:
Do base initialization with setup()
Do signal/slot connections
Set GUI widget with setTestUiWidget()
Load data from database and start state machines with start()
Definition at line 50 of file mdtTtAbstractTester.h.
Constructor & Destructor Documentation
mdtTtAbstractTester::mdtTtAbstractTester (QSqlDatabase db, QObject * parent = 0)
Constructor.
Definition at line 36 of file mdtTtAbstractTester.cpp.
Member Function Documentation
void mdtTtAbstractTester::createTest () virtual slot
Create a new test.
This default implmementation will first check if current test is clean (saved, ...), and warn the user if not. Then (if test is clean, or user choosed to not keep it), user can select a test model to use. Finaly, test is created, based on selected test model.
Definition at line 132 of file mdtTtAbstractTester.cpp.
References mdtSqlTableSelection::data(), database(), displayLastError(), mdtSqlTableSelection::isEmpty(), pvLastError, removeCurrentTestPv(), removeTestIfEmpty(), mdtSqlTableSelection::rowCount(), and testIsSaved().
QSqlDatabase mdtTtAbstractTester::database () inline
Get database instance.
Definition at line 91 of file mdtTtAbstractTester.h.
Referenced by createTest(), and openTest().
void mdtTtAbstractTester::displayLastError () protected
Display last error to the user.
Definition at line 346 of file mdtTtAbstractTester.cpp.
References mdtError::levelIcon(), pvLastError, mdtError::systemText(), and mdtError::text().
Referenced by createTest(), openTest(), saveTest(), and setTestUiWidget().
void mdtTtAbstractTester::openTest () virtual slot
Open a existing test.
This default implmementation will first check if current test is clean (saved, ...), and warn the user if not. Then (if test is clean, or user choosed to not keep it), user can select a test. Finaly, selected test is set as current test.
Definition at line 192 of file mdtTtAbstractTester.cpp.
References mdtSqlTableSelection::data(), database(), displayLastError(), mdtSqlTableSelection::isEmpty(), pvLastError, removeCurrentTestPv(), removeTestIfEmpty(), mdtSqlTableSelection::rowCount(), and testIsSaved().
bool mdtTtAbstractTester::removeCurrentTestPv () protected
Remove current test.
Definition at line 323 of file mdtTtAbstractTester.cpp.
References pvLastError.
Referenced by createTest(), and openTest().
bool mdtTtAbstractTester::removeTestIfEmpty () protected
Remove current test if it is empty.
see testIsEmpty()
Definition at line 299 of file mdtTtAbstractTester.cpp.
References pvLastError, and testIsEmpty().
Referenced by createTest(), and openTest().
void mdtTtAbstractTester::saveTest () virtual slot
Save current test.
Definition at line 248 of file mdtTtAbstractTester.cpp.
References displayLastError(), pvLastError, and mdtSqlRecord::value().
bool mdtTtAbstractTester::setTestUiWidget (QWidget * widget)
All childs contained in widget that have a name prefixed fld_ will be mapped to corresponding fields in Test_view. They cann be written, but internally used mdtAbstractSqlTableController's submit() slot will not work. Data will be really stored in Test_tbl by saveTest().
Todo:
Update if method takes another name..
Given widget will also be used as parent for dialogs that are displayed (selection dialogs, message boxes).
Definition at line 67 of file mdtTtAbstractTester.cpp.
References displayLastError(), and pvLastError.
Referenced by mdtTtBasicTesterWindow::init().
bool mdtTtAbstractTester::setup () virtual
Do setup.
Will setup internal SQL table controllers to access Test_view and TestItem_view.
Reimplemented in mdtTtBasicTester.
Definition at line 46 of file mdtTtAbstractTester.cpp.
References mdtSqlRelationInfo::addRelation(), pvLastError, and mdtSqlRelationInfo::setChildTableName().
Referenced by mdtTtBasicTester::setup().
bool mdtTtAbstractTester::start ()
Start state machines.
Will load data from database and start internal state machines. After this call, use setCurrentTest() to go to a existing test, or createTest() to create a new one.
See Also
mdtTtTest::start().
Definition at line 81 of file mdtTtAbstractTester.cpp.
References pvLastError.
Referenced by mdtTtBasicTesterWindow::init().
std::shared_ptr<mdtTtTest> mdtTtAbstractTester::test () inline
Get test object.
Definition at line 116 of file mdtTtAbstractTester.h.
void mdtTtAbstractTester::testDataChanged (const QSqlRecord & data) signal
Emited when test data has changed.
date comes from Test_view
bool mdtTtAbstractTester::testIsEmpty () const
Check if a test is empty.
When creating a new test, it must be directly stored in database. This is because test items must allways be created.
A test is empty if:
In Test_tbl: only Id_PK, TestModel_Id_FK and Date are set
In each related item in Test_tbl: only Id_PK, Test_Id_FK and TestModelItem_Id_FK are set
Definition at line 98 of file mdtTtAbstractTester.cpp.
References mdtSqlRecord::count(), and mdtSqlRecord::value().
Referenced by removeTestIfEmpty().
bool mdtTtAbstractTester::testIsSaved () const inline
Check if test is saved.
A test is saved if all cached data regarding Test_tbl and TestItem_tbl are stored in database. If no test was set (Test_tbl.Id_PK is NULL), test is considered saved.
Todo:
Toujours vrais ? Note: each call of this method will check all test items.
Definition at line 135 of file mdtTtAbstractTester.h.
Referenced by createTest(), and openTest().
std::shared_ptr<mdtSqlTableViewController> mdtTtAbstractTester::testItemViewController () inline
Access controller that acts on TestItem_view.
Precondition
init() must be done before calling this method.
Definition at line 104 of file mdtTtAbstractTester.h.
std::shared_ptr<mdtTtTestNodeManager> mdtTtAbstractTester::testNodeManager () inline
Get test node manager object.
Definition at line 112 of file mdtTtAbstractTester.h.
Referenced by mdtTtBasicTesterWindow::mdtTtBasicTesterWindow().
std::shared_ptr<mdtSqlDataWidgetController> mdtTtAbstractTester::testViewController () inline
Access controller that acts on Test_view.
Definition at line 95 of file mdtTtAbstractTester.h.
Member Data Documentation
mdtError mdtTtAbstractTester::pvLastError protected
Contains last error that occured.
Definition at line 188 of file mdtTtAbstractTester.h.
Referenced by createTest(), displayLastError(), mdtTtBasicTester::lastError(), openTest(), removeCurrentTestPv(), removeTestIfEmpty(), saveTest(), setTestUiWidget(), setup(), and start().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtAbstractTester.h
src/mdttools/mdttesttool/mdtTtAbstractTester.cpp