Multi diag tools: mdtDeviceWindow Class Reference
mdtDeviceWindow Class Reference
#include <mdtDeviceWindow.h>
Public Member Functions
mdtDeviceWindow (QWidget *parent=0)
Construct a device window.
~mdtDeviceWindow ()
void setDevice (mdtDevice *device)
Set the device.
void setIosWidget (QWidget *widget)
Set the I/O's widget.
mdtPortStatusWidget * statusWidget ()
Get status widget.
void enableTranslations ()
Enable translations.
void setAvailableTranslations (QMap< QString, QString > &avaliableTranslations, const QString &currentTranslationKey)
Build the translations menu.
Protected Slots
void retranslate ()
Retranslate.
Additional Inherited Members
Public Attributes inherited from Ui_mdtDeviceWindow
QAction * action_Quit
QWidget * centralwidget
QVBoxLayout * verticalLayout
QScrollArea * saIos
QWidget * scrollAreaWidgetContents
QMenuBar * menubar
QMenu * menu_File
QMenu * menu_Language
QStatusBar * statusbar
Detailed Description
Definition at line 34 of file mdtDeviceWindow.h.
Constructor & Destructor Documentation
mdtDeviceWindow::mdtDeviceWindow (QWidget * parent = 0)
Construct a device window.
Will create a new mdtPortStatusWidget and add it as status bar.
Definition at line 27 of file mdtDeviceWindow.cpp.
References Ui_mdtDeviceWindow::setupUi().
mdtDeviceWindow::~mdtDeviceWindow ()
Definition at line 37 of file mdtDeviceWindow.cpp.
Member Function Documentation
void mdtDeviceWindow::enableTranslations ()
Enable translations.
Will use mdtApplication to get the list of available translations and connect to retranslate slot.
Precondition
The loop must be started with a mdtApplication instance (mdtApp must be valid).
Definition at line 66 of file mdtDeviceWindow.cpp.
References mdtApp, retranslate(), and setAvailableTranslations().
void mdtDeviceWindow::retranslate () protected slot
Retranslate.
This slot is called by mdtApplication when language has changed
Definition at line 97 of file mdtDeviceWindow.cpp.
References Ui_mdtDeviceWindow::retranslateUi().
Referenced by enableTranslations().
void mdtDeviceWindow::setAvailableTranslations (QMap< QString, QString > & avaliableTranslations, const QString & currentTranslationKey)
Build the translations menu.
Definition at line 74 of file mdtDeviceWindow.cpp.
References mdtApp, and Ui_mdtDeviceWindow::menu_Language.
Referenced by enableTranslations().
void mdtDeviceWindow::setDevice (mdtDevice * device)
Set the device.
If device contains a port manager, mdtPortManager::stateChanged() and mdtPortManager::statusMessageChanged() signals are connected to status widget.
Precondition
device must be a valid pointer.
Definition at line 41 of file mdtDeviceWindow.cpp.
References mdtDevice::portManager().
void mdtDeviceWindow::setIosWidget (QWidget * widget)
Set the I/O's widget.
Definition at line 53 of file mdtDeviceWindow.cpp.
References Ui_mdtDeviceWindow::saIos.
mdtPortStatusWidget * mdtDeviceWindow::statusWidget ()
Get status widget.
Usefull for setup
Definition at line 59 of file mdtDeviceWindow.cpp.
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceWindow.h
src/mdtdevice/mdtDeviceWindow.cpp