Multi diag tools: mdtSqlDataValidator Class Reference
mdtSqlDataValidator Class Reference
Helper class for data validation.
#include <mdtSqlDataValidator.h>
Public Member Functions
mdtSqlDataValidator (QSqlTableModel *model, QObject *parent=0)
Constructor.
virtual ~mdtSqlDataValidator ()
Destructor.
QSqlTableModel * model ()
Get model.
virtual bool checkBeforeSubmit ()
Checks to be done before data are submitted.
void displayWarning (const QString &text, const QString &informativeText, const QSqlError &sqlError=QSqlError())
Display a warning to the user.
void displayError (const QString &text, const QString &informativeText, const QSqlError &sqlError=QSqlError())
Display a error to the user.
Detailed Description
Helper class for data validation.
The SQL widget classes witch are usefull to create database GUI are event driven. A internal state machine tries to keep GUI coherent. When, f.ex., the user wants to save data, a trigger is activated and state changes (if current state permit it) to a sort of saving state. The drawback of this solution is that there is no way to handle the save steps. This class was made to help on such process.
For example, if you need to do some check before the real submit beginns, you can subclass mdtSqlDataValidator and reimplement checkBeforeSubmit(). If this method fails, the submit is not done.
See Also
mdtAbstractSqlWidget
mdtSqlFormWidget
mdtSqlTableWidget
Definition at line 48 of file mdtSqlDataValidator.h.
Constructor & Destructor Documentation
mdtSqlDataValidator::mdtSqlDataValidator (QSqlTableModel * model, QObject * parent = 0)
Constructor.
Precondition
model must be a valid pointer.
Definition at line 26 of file mdtSqlDataValidator.cpp.
References model().
mdtSqlDataValidator::~mdtSqlDataValidator () virtual
Destructor.
Definition at line 34 of file mdtSqlDataValidator.cpp.
Member Function Documentation
bool mdtSqlDataValidator::checkBeforeSubmit () virtual
Checks to be done before data are submitted.
Returns
This default implementation does nothing and returns allways false.
Reimplemented in mdtSqlFormWidgetDataValidator.
Definition at line 45 of file mdtSqlDataValidator.cpp.
void mdtSqlDataValidator::displayError (const QString & text, const QString & informativeText, const QSqlError & sqlError = QSqlError())
Display a error to the user.
text and informativeText text are the same meaning as Qt's QMessageBox. Error will be logged with mdtError system.
If sqlError is valid, it will be added in the detailed text of QMessageBox, and as system error in mdtError log.
Definition at line 71 of file mdtSqlDataValidator.cpp.
References mdtError::commit(), mdtError::Error, MDT_DATABASE_ERROR, MDT_ERROR_SET_SRC, and mdtError::setSystemError().
void mdtSqlDataValidator::displayWarning (const QString & text, const QString & informativeText, const QSqlError & sqlError = QSqlError())
Display a warning to the user.
text and informativeText text are the same meaning as Qt's QMessageBox. Warning will be logged with mdtError system.
If sqlError is valid, it will be added in the detailed text of QMessageBox, and as system error in mdtError log.
Definition at line 50 of file mdtSqlDataValidator.cpp.
References mdtError::commit(), MDT_DATABASE_ERROR, MDT_ERROR_SET_SRC, mdtError::setSystemError(), and mdtError::Warning.
Referenced by mdtSqlFormWidgetDataValidator::checkBeforeSubmit().
QSqlTableModel * mdtSqlDataValidator::model ()
Get model.
Postcondition
Returned pointer is allways valid.
Definition at line 38 of file mdtSqlDataValidator.cpp.
Referenced by mdtSqlDataValidator().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSqlDataValidator.h
src/mdtutilsgui/mdtSqlDataValidator.cpp