Multi diag tools: mdtTtAbstractTestNodeCalibrationTool Class Reference
mdtTtAbstractTestNodeCalibrationTool Class Reference
#include <mdtTtAbstractTestNodeCalibrationTool.h>
Public Member Functions
mdtTtAbstractTestNodeCalibrationTool (QSqlDatabase db, QObject *parent=0)
Constructor.
virtual bool setup (QWidget *testNodeFormWidget)
Do setup.
bool setTestNode (const QVariant &testNodeId)
Set test node to calibrate.
QSqlDatabase database ()
Get database instance.
std::shared_ptr
< mdtSqlTableViewController > testNodeUnitViewTableController ()
Get table controller to access data in TestNodeUnit_view.
std::shared_ptr
< mdtTtTestNodeManager > testNodeManager ()
Get test node manager object.
std::shared_ptr< mdtTtTest > test ()
Get test object.
QVariant currentTestNodeData (const QString &fieldName)
Get current test node data for given field.
QVariant testNodeUnitData (int testNodeUnitId, const QString &fieldName)
Get test node unit data for given test node unit ID and field name.
QVariant testNodeUnitData (const QString &schemaPosition, const QString &fieldName)
Get test node unit data for given test node unit schema position and field name.
bool setTestNodeUnitData (int testNodeUnitId, const QString &fieldName, const QVariant &data)
Set test node unit data for given test node unit ID and field name.
bool setTestNodeUnitData (const QString &schemaPosition, const QString &fieldName, const QVariant &data)
Set test node unit data for given test node unit schemaPosition and field name.
bool setTestNodeUnitCalibrationOffset (int testNodeUnitId, double offset)
Set calibration offset for given testNodeUnitId.
bool setTestNodeUnitCalibrationOffset (const QString &schemaPosition, double offset)
Set calibration offset for given test node unit schemaPosition.
bool saveTestNodeUnitCalibrationOffsets ()
Save calibration results to TestNodeUnit_tbl.
Protected Member Functions
void displayLastError ()
Display last error to the user.
void displayMessage (const QString &text, const QString &informativeText=QString(), QMessageBox::Icon icon=QMessageBox::Information)
Display a message to the user.
bool promptUser (const QString &text, const QString &informativeText=QString(), QMessageBox::Icon icon=QMessageBox::Information, QMessageBox::StandardButtons buttons=(QMessageBox::Ok|QMessageBox::Cancel))
Prompt the user to do a action.
bool askUser (const QString &text, const QString &informativeText=QString(), QMessageBox::Icon icon=QMessageBox::Question, QMessageBox::StandardButtons buttons=(QMessageBox::Ok|QMessageBox::No|QMessageBox::Cancel))
Ask a question to the user.
bool isInRange (const mdtValueDouble &value, double min, double max=std::numeric_limits< double >::max())
Check if x is in range.
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
Protected Attributes
mdtError pvLastError
Contains last error that occured.
Detailed Description
Test node calibration tool base class
Definition at line 45 of file mdtTtAbstractTestNodeCalibrationTool.h.
Constructor & Destructor Documentation
mdtTtAbstractTestNodeCalibrationTool::mdtTtAbstractTestNodeCalibrationTool (QSqlDatabase db, QObject * parent = 0)
Constructor.
Definition at line 39 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
Member Function Documentation
bool mdtTtAbstractTestNodeCalibrationTool::askUser (const QString & text, const QString & informativeText = QString(), QMessageBox::Icon icon = QMessageBox::Question, QMessageBox::StandardButtons buttons = (QMessageBox::Ok | QMessageBox::No | QMessageBox::Cancel)) protected
Ask a question to the user.
Returns
True if user accepted the message box (typically if he clicked Ok, Yes, ..), false if he rejected it (typically if Cancel, No, ... was clicked).
Definition at line 239 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
Referenced by promptUser().
bool mdtTtAbstractTestNodeCalibrationTool::beginTransaction () protected
Beginn manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 291 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by saveTestNodeUnitCalibrationOffsets().
bool mdtTtAbstractTestNodeCalibrationTool::commitTransaction () protected
Commit manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 317 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by saveTestNodeUnitCalibrationOffsets().
QVariant mdtTtAbstractTestNodeCalibrationTool::currentTestNodeData (const QString & fieldName) inline
Get current test node data for given field.
Definition at line 93 of file mdtTtAbstractTestNodeCalibrationTool.h.
QSqlDatabase mdtTtAbstractTestNodeCalibrationTool::database () inline
Get database instance.
Definition at line 75 of file mdtTtAbstractTestNodeCalibrationTool.h.
Referenced by setTestNode(), and setup().
void mdtTtAbstractTestNodeCalibrationTool::displayLastError () protected
Display last error to the user.
Definition at line 210 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References mdtError::informativeText(), mdtError::levelIcon(), pvLastError, mdtError::systemText(), and mdtError::text().
Referenced by mdtTtBasicTestNodeCalibrationTool::runCalibration(), mdtTtBasicTestNodeCalibrationTool::saveCalibration(), and setTestNode().
void mdtTtAbstractTestNodeCalibrationTool::displayMessage (const QString & text, const QString & informativeText = QString(), QMessageBox::Icon icon = QMessageBox::Information) protected
Display a message to the user.
Definition at line 222 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
bool mdtTtAbstractTestNodeCalibrationTool::isInRange (const mdtValueDouble & value, double min, double max = std::numeric_limits<double>::max()) protected
Check if x is in range.
Return true if value is in [min;max] If value is out of range, a descriptive text is stored to pvLastError You can use pvLastError.updateText() to set the main error text.
Note: if value has -OL or +OL flag set, -infinity, respecively +infinity value is considered.
Definition at line 262 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References mdtError::commit(), mdtError::Error, mdtTtTest::isInRange(), MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtError::setInformativeText(), and mdtValueDouble::value().
bool mdtTtAbstractTestNodeCalibrationTool::promptUser (const QString & text, const QString & informativeText = QString(), QMessageBox::Icon icon = QMessageBox::Information, QMessageBox::StandardButtons buttons = (QMessageBox::Ok | QMessageBox::Cancel)) protected
Prompt the user to do a action.
Returns
True if user accepted the message box (typically if he clicked Ok, Yes, ..), false if he rejected it (typically if Cancel, No, ... was clicked).
Definition at line 234 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References askUser().
Referenced by mdtTtBasicTestNodeCalibrationTool::runCalibration().
bool mdtTtAbstractTestNodeCalibrationTool::rollbackTransaction () protected
Rollback manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 304 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by saveTestNodeUnitCalibrationOffsets().
bool mdtTtAbstractTestNodeCalibrationTool::saveTestNodeUnitCalibrationOffsets ()
Save calibration results to TestNodeUnit_tbl.
Precondition
setup() must be called first.
Definition at line 144 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References mdtSqlRecord::addField(), beginTransaction(), mdtSqlRecord::clearValues(), commitTransaction(), mdtSqlRecord::lastError(), pvLastError, rollbackTransaction(), and mdtSqlRecord::setValue().
Referenced by mdtTtBasicTestNodeCalibrationTool::saveCalibration().
bool mdtTtAbstractTestNodeCalibrationTool::setTestNode (const QVariant & testNodeId)
Set test node to calibrate.
Todo:
Add a Key field or something similar.
Definition at line 95 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References database(), displayLastError(), and pvLastError.
Referenced by mdtTtBasicTestNodeCalibrationWindow::init().
bool mdtTtAbstractTestNodeCalibrationTool::setTestNodeUnitCalibrationOffset (int testNodeUnitId, double offset)
Set calibration offset for given testNodeUnitId.
Note: calibration offset and date are cached in models only, not sent to database.
Definition at line 108 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References setTestNodeUnitData().
bool mdtTtAbstractTestNodeCalibrationTool::setTestNodeUnitCalibrationOffset (const QString & schemaPosition, double offset)
Set calibration offset for given test node unit schemaPosition.
Notes:
Calibration offset and date are cached in models only, not sent to database.
The first test node unit that matches schemaPosition in current test node is considered.
Definition at line 126 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References setTestNodeUnitData().
bool mdtTtAbstractTestNodeCalibrationTool::setTestNodeUnitData (int testNodeUnitId, const QString & fieldName, const QVariant & data) inline
Set test node unit data for given test node unit ID and field name.
Note: data are cached in models only, not sent to database.
Precondition
setup() must be called first.
Definition at line 127 of file mdtTtAbstractTestNodeCalibrationTool.h.
Referenced by setTestNodeUnitCalibrationOffset().
bool mdtTtAbstractTestNodeCalibrationTool::setTestNodeUnitData (const QString & schemaPosition, const QString & fieldName, const QVariant & data) inline
Set test node unit data for given test node unit schemaPosition and field name.
Notes:
Data are cached in models only, not sent to database.
The first test node unit that matches schemaPosition in current test node is considered.
Precondition
setup() must be called first.
Definition at line 141 of file mdtTtAbstractTestNodeCalibrationTool.h.
bool mdtTtAbstractTestNodeCalibrationTool::setup (QWidget * testNodeFormWidget) virtual
Do setup.
Will setup database controllers and map widgets contained in testNodeFormWidget. All childs contained in widget that have a name prefixed fld_ will be mapped to corresponding fields in TestNode_view. Note that this for a read only access.
Note: connect signals and slots before calling this method, else UI will be incoherent at initial state.
Reimplemented in mdtTtBasicTestNodeCalibrationTool.
Definition at line 49 of file mdtTtAbstractTestNodeCalibrationTool.cpp.
References mdtSqlRelationInfo::addRelation(), database(), pvLastError, and mdtSqlRelationInfo::setChildTableName().
Referenced by mdtTtBasicTestNodeCalibrationTool::setup().
std::shared_ptr<mdtTtTest> mdtTtAbstractTestNodeCalibrationTool::test () inline
Get test object.
Definition at line 89 of file mdtTtAbstractTestNodeCalibrationTool.h.
std::shared_ptr<mdtTtTestNodeManager> mdtTtAbstractTestNodeCalibrationTool::testNodeManager () inline
Get test node manager object.
Definition at line 85 of file mdtTtAbstractTestNodeCalibrationTool.h.
QVariant mdtTtAbstractTestNodeCalibrationTool::testNodeUnitData (int testNodeUnitId, const QString & fieldName) inline
Get test node unit data for given test node unit ID and field name.
Precondition
setup() must be called first.
Definition at line 102 of file mdtTtAbstractTestNodeCalibrationTool.h.
QVariant mdtTtAbstractTestNodeCalibrationTool::testNodeUnitData (const QString & schemaPosition, const QString & fieldName) inline
Get test node unit data for given test node unit schema position and field name.
Will return the data for first test node unit that matches given schemaPosition, in current test node.
Precondition
setup() must be called first.
Definition at line 115 of file mdtTtAbstractTestNodeCalibrationTool.h.
std::shared_ptr<mdtSqlTableViewController> mdtTtAbstractTestNodeCalibrationTool::testNodeUnitViewTableController () inline
Get table controller to access data in TestNodeUnit_view.
Will be invalid until setup was done with setup().
Definition at line 81 of file mdtTtAbstractTestNodeCalibrationTool.h.
Referenced by mdtTtBasicTestNodeCalibrationWindow::init().
Member Data Documentation
mdtError mdtTtAbstractTestNodeCalibrationTool::pvLastError protected
Contains last error that occured.
Definition at line 171 of file mdtTtAbstractTestNodeCalibrationTool.h.
Referenced by beginTransaction(), commitTransaction(), displayLastError(), isInRange(), rollbackTransaction(), mdtTtBasicTestNodeCalibrationTool::runCalibration(), saveTestNodeUnitCalibrationOffsets(), setTestNode(), and setup().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtAbstractTestNodeCalibrationTool.h
src/mdttools/mdttesttool/mdtTtAbstractTestNodeCalibrationTool.cpp