Multi diag tools: mdtDeviceAddress Class Reference
mdtDeviceAddress Class Reference
Common device identification.
#include <mdtDeviceAddress.h>
Public Types
enum PortType_t { PortType_t::NONE, PortType_t::TCPIP, PortType_t::USB, PortType_t::ASRL }
Port type.
enum DeviceType_t { DeviceType_t::NONE, DeviceType_t::INSTR, DeviceType_t::SOCKET, DeviceType_t::MODBUS }
Device type.
Public Member Functions
mdtDeviceAddress ()
Construct a invalid device address.
bool isValid () const
Check if device address is valid.
mdtError lastError () const
Get last error.
void clear ()
Clear device address.
PortType_t portType () const
Get port type.
QString portTypeStr () const
Get port type string.
DeviceType_t deviceType () const
Get device type.
QString deviceTypeStr () const
Get device type string.
bool setAddressString (const QString &as)
Set address string.
QString addressString () const
Get address string.
void setAlias (const QString &alias)
Set alias.
QString alias () const
Get alias.
void setUsbIdentification (uint16_t idVendor, uint16_t idProduct, const QString &deviceSerialNumber, uint8_t bInterfaceNumber, DeviceType_t devType=DeviceType_t::INSTR)
Set USB identification.
uint16_t usbIdVendor () const
Get USB idVendor.
uint16_t usbIdProduct () const
Get USB idProduct.
QString usbDeviceSerialNumber () const
Get USB device serial number.
uint8_t usbInterfaceNumber () const
Get USB bInterfaceNumber.
void setTcpIpIdentification (const QString &hostName, uint16_t port, DeviceType_t devType)
Set TCP/IP identification.
void setModbusTcpIdentification (const QString &hostName, uint16_t port, const mdtModbusHwNodeId &nid)
Set MODBUS/TCP identification.
QString tcpIpHostName () const
Get TCP/IP host name.
uint16_t tcpIpPort () const
Get TCP/IP port.
mdtModbusHwNodeId modbusHwNodeId () const
Get MODBUS hardware node id.
Detailed Description
Common device identification.
In multiDiagTools library, each port or device class has its own methods to open a ressource.
In some case, it's necessary to identify, f.ex. a device, in a common way. Storing this identification in a databse or a file can also be usefull.
To resole above problems, this class is inspired from VISA (Virtual Instrument Software Architecture) library specifications. The most important part is in VPP-4.3: The VISA Library, revision 5.4 , chapiter 4.3.1 Address String. This specification is available by the IVI Foundation: http://www.ivifoundation.org
Note: current version has only a partial support (USB and part of TCPIP)
Definition at line 70 of file mdtDeviceAddress.h.
Member Enumeration Documentation
enum mdtDeviceAddress::DeviceType_t strong
Device type.
Refers to resource class described in VPP-4.3 revision 5.4 , chapiter 5.
Some devices type are also not from VPP-4.3 specifications.
Enumerator
NONE
No device type. Set by default for a invalid device address
INSTR
Device that supports block data exchange, clear and trigger commands, status registers. Example can be a SCPI instrument. See VPP-4.3 revision 5.4 , chapiter 5.1 .
SOCKET
Raw socket connection using TCP/IP, See VPP-4.3 revision 5.4 , chapiter 5.6 .
MODBUS
Device that support MODBUS protocol. Not sepcified in VPP-4.3 revision 5.4
Definition at line 97 of file mdtDeviceAddress.h.
enum mdtDeviceAddress::PortType_t strong
Port type.
In VPP-4.3 revision 5.4 , chapiter 4.3.1, the term Interface is used. To avoid confusions, f.ex. with USB interface, and to match mith multiDiagTools library class names, it was choosen to name it port.
Enumerator
NONE
No port. Set by default for a invalid device address
TCPIP
TCPIP port type
USB
USB port type
ASRL
Asynchronous serial line (f.ex. RS232)
Definition at line 82 of file mdtDeviceAddress.h.
Constructor & Destructor Documentation
mdtDeviceAddress::mdtDeviceAddress () inline
Construct a invalid device address.
Definition at line 110 of file mdtDeviceAddress.h.
References mdtUsbDeviceAddress::bInterfaceNumber, mdtUsbDeviceAddress::idProduct, mdtUsbDeviceAddress::idVendor, mdtTcpipDeviceAddress::port, pvTcpipDeviceAddress, and pvUsbDeviceAddress.
Member Function Documentation
QString mdtDeviceAddress::addressString () const inline
Get address string.
Return the address string as described in VPP-4.3 revision 5.4 , chapiter 4.3.1 for supported port type (named interface in specification) and device type (named resource in specification).
MODBUS device is not from VPP-4.3 specification, and has also a concept of hardware node ID that is specific to multiDiagTools. A device connected by a TCPIP port will be represented as: "TCPIP::hostName::port::MODBUS::HWNID,bitsCount,firstBit" . The hostName part can be a IP address or a host name. The hardware node ID is as follow:
HWNID: Hardware ID of the MODBUS node
bitsCount: number of bits, i.e. the number of digital inputs, that represent the node ID
firstBit: the first bit that represent the node ID, starting from 0 (f.ex. if digital input 1 is the first, first bit will be 0)
Definition at line 206 of file mdtDeviceAddress.h.
QString mdtDeviceAddress::alias () const inline
Get alias.
If no alias was set, addressString is returned.
See Also
setAlias()
Definition at line 231 of file mdtDeviceAddress.h.
Referenced by setAlias().
void mdtDeviceAddress::clear ()
Clear device address.
Definition at line 28 of file mdtDeviceAddress.cpp.
References mdtUsbDeviceAddress::bInterfaceNumber, mdtModbusHwNodeId::clear(), mdtUsbDeviceAddress::idProduct, mdtUsbDeviceAddress::idVendor, NONE, mdtTcpipDeviceAddress::port, pvTcpipDeviceAddress, and pvUsbDeviceAddress.
Referenced by setAddressString(), setModbusTcpIdentification(), setTcpIpIdentification(), and setUsbIdentification().
DeviceType_t mdtDeviceAddress::deviceType () const inline
Get device type.
Definition at line 151 of file mdtDeviceAddress.h.
QString mdtDeviceAddress::deviceTypeStr () const
Get device type string.
Definition at line 60 of file mdtDeviceAddress.cpp.
References INSTR, MODBUS, NONE, and SOCKET.
Referenced by setTcpIpIdentification(), and setUsbIdentification().
bool mdtDeviceAddress::isValid () const inline
Check if device address is valid.
Definition at line 122 of file mdtDeviceAddress.h.
References NONE.
mdtError mdtDeviceAddress::lastError () const inline
Get last error.
Definition at line 129 of file mdtDeviceAddress.h.
Referenced by mdtDeviceAddressList::readFromFile().
mdtModbusHwNodeId mdtDeviceAddress::modbusHwNodeId () const inline
Get MODBUS hardware node id.
Definition at line 344 of file mdtDeviceAddress.h.
PortType_t mdtDeviceAddress::portType () const inline
Get port type.
Definition at line 140 of file mdtDeviceAddress.h.
QString mdtDeviceAddress::portTypeStr () const
Get port type string.
Definition at line 44 of file mdtDeviceAddress.cpp.
References ASRL, NONE, TCPIP, and USB.
bool mdtDeviceAddress::setAddressString (const QString & as) inline
Set address string.
See Also
addressString()
Definition at line 164 of file mdtDeviceAddress.h.
References clear(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and mdtError::setError().
Referenced by mdtDeviceAddressList::readFromFile().
void mdtDeviceAddress::setAlias (const QString & alias) inline
Set alias.
Alias is a technical name that can be used, f.ex. in a programm that handle many devices. This gives a way to find device, say in a device container, in less cumbersome ways than having to type the full address string.
Precondition
alias must not contain \t
Definition at line 220 of file mdtDeviceAddress.h.
References alias().
Referenced by mdtDeviceAddressList::readFromFile().
void mdtDeviceAddress::setModbusTcpIdentification (const QString & hostName, uint16_t port, const mdtModbusHwNodeId & nid) inline
Set MODBUS/TCP identification.
Definition at line 310 of file mdtDeviceAddress.h.
References mdtModbusHwNodeId::bitsCount(), clear(), mdtModbusHwNodeId::firstBit(), mdtModbusHwNodeId::id(), MODBUS, mdtTcpipDeviceAddress::port, pvTcpipDeviceAddress, and TCPIP.
Referenced by mdtModbusTcpPortManager::scan().
void mdtDeviceAddress::setTcpIpIdentification (const QString & hostName, uint16_t port, DeviceType_t devType) inline
Set TCP/IP identification.
Definition at line 298 of file mdtDeviceAddress.h.
References clear(), deviceTypeStr(), mdtTcpipDeviceAddress::port, pvTcpipDeviceAddress, and TCPIP.
void mdtDeviceAddress::setUsbIdentification (uint16_t idVendor, uint16_t idProduct, const QString & deviceSerialNumber, uint8_t bInterfaceNumber, DeviceType_t devType = DeviceType_t::INSTR) inline
Set USB identification.
Definition at line 241 of file mdtDeviceAddress.h.
References mdtUsbDeviceAddress::bInterfaceNumber, clear(), deviceTypeStr(), mdtUsbDeviceAddress::idProduct, mdtUsbDeviceAddress::idVendor, pvUsbDeviceAddress, and USB.
QString mdtDeviceAddress::tcpIpHostName () const inline
Get TCP/IP host name.
Definition at line 324 of file mdtDeviceAddress.h.
References TCPIP.
uint16_t mdtDeviceAddress::tcpIpPort () const inline
Get TCP/IP port.
Definition at line 334 of file mdtDeviceAddress.h.
References mdtTcpipDeviceAddress::port, pvTcpipDeviceAddress, and TCPIP.
QString mdtDeviceAddress::usbDeviceSerialNumber () const inline
Get USB device serial number.
Definition at line 278 of file mdtDeviceAddress.h.
References USB.
uint16_t mdtDeviceAddress::usbIdProduct () const inline
Get USB idProduct.
Definition at line 268 of file mdtDeviceAddress.h.
References mdtUsbDeviceAddress::idProduct, pvUsbDeviceAddress, and USB.
uint16_t mdtDeviceAddress::usbIdVendor () const inline
Get USB idVendor.
Definition at line 258 of file mdtDeviceAddress.h.
References mdtUsbDeviceAddress::idVendor, pvUsbDeviceAddress, and USB.
uint8_t mdtDeviceAddress::usbInterfaceNumber () const inline
Get USB bInterfaceNumber.
Definition at line 288 of file mdtDeviceAddress.h.
References mdtUsbDeviceAddress::bInterfaceNumber, pvUsbDeviceAddress, and USB.
Member Data Documentation
mdtAsrlDeviceAddress mdtDeviceAddress::pvAsrlDeviceAddress
Definition at line 386 of file mdtDeviceAddress.h.
mdtTcpipDeviceAddress mdtDeviceAddress::pvTcpipDeviceAddress
Definition at line 385 of file mdtDeviceAddress.h.
Referenced by clear(), mdtDeviceAddress(), setModbusTcpIdentification(), setTcpIpIdentification(), and tcpIpPort().
mdtUsbDeviceAddress mdtDeviceAddress::pvUsbDeviceAddress
Definition at line 384 of file mdtDeviceAddress.h.
Referenced by clear(), mdtDeviceAddress(), setUsbIdentification(), usbIdProduct(), usbIdVendor(), and usbInterfaceNumber().
The documentation for this class was generated from the following files:
src/mdtport/mdtDeviceAddress.h
src/mdtport/mdtDeviceAddress.cpp