Multi diag tools: mdtUsbPortThreadNew Class Reference
mdtUsbPortThreadNew Class Reference
Thread for USB.
#include <mdtUsbPortThreadNew.h>
Public Types
enum State_t {
State_t::Stopped = 0, State_t::Starting, State_t::Running, State_t::Stopping,
State_t::Error
}
USB port thread state.
Signals
void threadStateChanged ()
Emitted by port thread when state has changed.
void errorOccured (const mdtError &error)
Emitted when a error occured (see specific subclass for details)
Public Member Functions
mdtUsbPortThreadNew (libusb_context *ctx, QObject *parent=0)
Constructor.
virtual ~mdtUsbPortThreadNew ()
Destructor.
mdtUsbPortThreadNew (const mdtUsbPortThreadNew &rhs)=delete
mdtUsbPortThreadNew & operator= (const mdtUsbPortThreadNew &rhs)=delete
bool start (const mdtUsbDeviceDescriptor &deviceDescriptor, uint8_t bInterfaceNumber)
Start thread.
void stop ()
Stop thread.
mdtError lastError ()
Get last error.
Protected Member Functions
void setCurrentState (State_t s)
Set current state.
State_t currentState () const
Get current state.
libusb_context * usbContext ()
Access libusb context.
libusb_device_handle * deviceHandle ()
Access libusb device handle.
const mdtUsbDeviceDescriptor & deviceDescriptor () const
Access device descriptor.
uint8_t bInterfaceNumber () const
Get requested bInterfaceNumber.
bool waitOnState (State_t s, int timeout=0)
Wait until a state is reached or timeout without breacking main event loop.
bool waitOnStateElseThan (State_t s, int timeout=0)
Wait until state is exited or timeout without breacking main event loop.
bool openDevice ()
Open device.
virtual void aboutToClose ()
Actions to perform before device closes.
virtual void run ()
Called from port thread.
Protected Attributes
mdtError pvLastError
Last error object.
std::mutex pvLastErrorMutex
Mutext to serialize pvLastError access.
Detailed Description
Thread for USB.
Handle USB event in a other thread than GUI one.
Definition at line 38 of file mdtUsbPortThreadNew.h.
Member Enumeration Documentation
enum mdtUsbPortThreadNew::State_t strong
USB port thread state.
Enumerator
Stopped
Thread is stopped
Starting
Thread is staring
Running
Thread is running (ready for I/O)
Stopping
Thread is stopping
Error
Thread is stopped due to a error
Definition at line 46 of file mdtUsbPortThreadNew.h.
Constructor & Destructor Documentation
mdtUsbPortThreadNew::mdtUsbPortThreadNew (libusb_context * ctx, QObject * parent = 0)
Constructor.
Callable from GUI thread.
Precondition
ctx must be a valid pointer.
Definition at line 29 of file mdtUsbPortThreadNew.cpp.
References threadStateChanged().
mdtUsbPortThreadNew::~mdtUsbPortThreadNew () virtual
Destructor.
Callable from GUI thread.
Definition at line 40 of file mdtUsbPortThreadNew.cpp.
References stop().
mdtUsbPortThreadNew::mdtUsbPortThreadNew (const mdtUsbPortThreadNew & rhs) delete
Member Function Documentation
void mdtUsbPortThreadNew::aboutToClose () protected virtual
Actions to perform before device closes.
This function is called from stop(), and is executed in GUI thread. Should be non blocking.
This default implementation does nothing.
Definition at line 156 of file mdtUsbPortThreadNew.cpp.
Referenced by stop().
uint8_t mdtUsbPortThreadNew::bInterfaceNumber () const inline protected
Get requested bInterfaceNumber.
Definition at line 146 of file mdtUsbPortThreadNew.h.
Referenced by start().
State_t mdtUsbPortThreadNew::currentState () const inline protected
Get current state.
Definition at line 116 of file mdtUsbPortThreadNew.h.
References mdtBasicStateMachine< S >::currentState().
Referenced by run(), waitOnState(), and waitOnStateElseThan().
const mdtUsbDeviceDescriptor& mdtUsbPortThreadNew::deviceDescriptor () const inline protected
Access device descriptor.
Definition at line 139 of file mdtUsbPortThreadNew.h.
Referenced by start().
libusb_device_handle* mdtUsbPortThreadNew::deviceHandle () inline protected
Access libusb device handle.
Note: will be valid after successfull start(), and null after stop().
Definition at line 132 of file mdtUsbPortThreadNew.h.
void mdtUsbPortThreadNew::errorOccured (const mdtError & error) signal
Emitted when a error occured (see specific subclass for details)
mdtError mdtUsbPortThreadNew::lastError () inline
Get last error.
Definition at line 87 of file mdtUsbPortThreadNew.h.
References pvLastError, and pvLastErrorMutex.
bool mdtUsbPortThreadNew::openDevice () protected
Open device.
Will open device that was passed to start(). Subclass can use this helper function.
Should be called from port thread (in run()).
Definition at line 116 of file mdtUsbPortThreadNew.cpp.
References mdtError::commit(), mdtError::Error, mdtUsbDeviceDescriptor::isEmpty(), mdtUsbDeviceDescriptor::lastError(), MDT_ERROR_SET_SRC, mdtUsbDeviceDescriptor::open(), pvLastError, pvLastErrorMutex, mdtError::setError(), mdtError::setSystemError(), and mdtError::Warning.
Referenced by run().
mdtUsbPortThreadNew& mdtUsbPortThreadNew::operator= (const mdtUsbPortThreadNew & rhs) delete
void mdtUsbPortThreadNew::run () protected virtual
Called from port thread.
Specific sub-class must implement this function.
Default implementation is minimal and does nothing really interresting (just used for unit testing).
Definition at line 160 of file mdtUsbPortThreadNew.cpp.
References mdtError::commit(), currentState(), Error, mdtError::Error, MDT_ERROR_SET_SRC, openDevice(), pvLastError, pvLastErrorMutex, Running, setCurrentState(), mdtError::setError(), mdtError::setSystemError(), and Stopped.
Referenced by start().
void mdtUsbPortThreadNew::setCurrentState (State_t s) inline protected
Set current state.
Will also emit threadStateChanged() signal.
Definition at line 109 of file mdtUsbPortThreadNew.h.
References mdtBasicStateMachine< S >::setCurrentState(), and threadStateChanged().
Referenced by run(), and stop().
bool mdtUsbPortThreadNew::start (const mdtUsbDeviceDescriptor & deviceDescriptor, uint8_t bInterfaceNumber)
Start thread.
Callable from GUI thread.
Definition at line 45 of file mdtUsbPortThreadNew.cpp.
References bInterfaceNumber(), mdtBasicStateMachine< S >::currentState(), deviceDescriptor(), run(), Running, mdtBasicStateMachine< S >::setCurrentState(), Starting, stop(), and waitOnStateElseThan().
Referenced by mdtUsbtmcPort::openDevice().
void mdtUsbPortThreadNew::stop ()
Stop thread.
Callable from GUI thread.
Definition at line 63 of file mdtUsbPortThreadNew.cpp.
References aboutToClose(), mdtError::commit(), MDT_ERROR_SET_SRC, pvLastError, pvLastErrorMutex, setCurrentState(), mdtError::setError(), mdtError::setSystemError(), Stopping, and mdtError::Warning.
Referenced by mdtUsbtmcPort::close(), start(), and ~mdtUsbPortThreadNew().
void mdtUsbPortThreadNew::threadStateChanged () signal
Emitted by port thread when state has changed.
Referenced by mdtUsbPortThreadNew(), and setCurrentState().
libusb_context* mdtUsbPortThreadNew::usbContext () inline protected
Access libusb context.
Definition at line 123 of file mdtUsbPortThreadNew.h.
bool mdtUsbPortThreadNew::waitOnState (mdtUsbPortThreadNew::State_t s, int timeout = 0) protected
Wait until a state is reached or timeout without breacking main event loop.
Parameters
s state to wait on
timeout Timeout [ms]. 0 means infinite timeout.
Returns
True if state was reached, false on timeout
Definition at line 86 of file mdtUsbPortThreadNew.cpp.
References currentState().
bool mdtUsbPortThreadNew::waitOnStateElseThan (mdtUsbPortThreadNew::State_t s, int timeout = 0) protected
Wait until state is exited or timeout without breacking main event loop.
Parameters
s state to wait on
timeout Timeout [ms]. 0 means infinite timeout.
Returns
True if state was reached, false on timeout
Definition at line 101 of file mdtUsbPortThreadNew.cpp.
References currentState().
Referenced by start().
Member Data Documentation
mdtError mdtUsbPortThreadNew::pvLastError protected
Last error object.
See mdtError documentation for details. A lock_guard that acts on pvLastErrorMutex should be used before modifying the error.
Definition at line 200 of file mdtUsbPortThreadNew.h.
Referenced by lastError(), openDevice(), run(), and stop().
std::mutex mdtUsbPortThreadNew::pvLastErrorMutex protected
Mutext to serialize pvLastError access.
Definition at line 204 of file mdtUsbPortThreadNew.h.
Referenced by lastError(), openDevice(), run(), and stop().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbPortThreadNew.h
src/mdtport/mdtUsbPortThreadNew.cpp