Multi diag tools: mdtTtTestData Class Reference
mdtTtTestData Class Reference
#include <mdtTtTestData.h>
Public Member Functions
mdtTtTestData ()
Construct a empty mdtTtTestData.
mdtTtTestData (const QSqlRecord &record)
Contruct a mdtTtTestData from a QSqlRecord.
bool setup (const QSqlDatabase &db, bool setupModelData)
Setup fields from TestModel_tbl.
void clearValues ()
Clear values.
void setModelData (const mdtTtTestModelData &data)
Set model data.
const mdtTtTestModelData & modelData () const
Get model data.
Public Member Functions inherited from mdtSqlRecord
mdtSqlRecord ()
Constructor.
mdtSqlRecord (const QSqlRecord &sqlRecord)
Build a mdtSqlRecord on the base of a QSqlRecord.
virtual ~mdtSqlRecord ()
Destructor.
operator QSqlRecord () const
Get QSqlRecord version.
bool addField (const QString &fieldName, const QString &tableName, const QSqlDatabase &db)
Add a field to record.
bool addAllFields (const QString &tableName, const QSqlDatabase &db)
Add all fields of given table to record.
int count () const
Returns the number of fields in the record.
bool isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
QSqlField field (int index) const
Returns the field at position index.
QSqlField field (const QString &name) const
Returns the field called name.
int indexOf (const QString &name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
bool contains (const QString &name) const
Returns true if there is a field in the record called name; otherwise returns false.
QStringList fieldNames () const
Get a list with all field names.
bool hasValue (int fieldIndex) const
Check if a value was set.
bool hasValue (const QString &fieldName) const
Check if a value was set.
void setHasValue (int fieldIndex, bool hv)
Set the hasValue flag manually.
void setHasValue (const QString &fieldName, bool hv)
Set the hasValue flag manually.
void clearHasValueFlags ()
Clear the hasValue flags.
void setValue (int fieldIndex, const QVariant &val)
Set value.
void setValue (const QString &fieldName, const QVariant &val)
Set value.
QVariant value (int index) const
Returns the value of the field located at position index in the record.
QVariant value (const QString &name) const
Returns the value of the field called name in the record.
virtual void clear ()
Removes all the record's fields.
mdtError lastError () const
Get last error.
QVector< int > fieldIndexesWithValue () const
Get a list with field indexes that have a value.
QString sqlForInsert (const QString &tableName) const
Get SQL statement for insertion with QSqlQuery.
QString sqlForUpdate (const QString &tableName, const QSqlRecord &matchData) const
Get SQL statement for update with QSqlQuery.
QString dataToUpdateInfo () const
Get information about data that has a value to update (for debug)
Additional Inherited Members
Static Public Member Functions inherited from mdtSqlRecord
static QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtSqlRecord
mdtError pvLastError
Detailed Description
Todo:
Check if not obselete ?
Definition at line 29 of file mdtTtTestData.h.
Constructor & Destructor Documentation
mdtTtTestData::mdtTtTestData ()
Construct a empty mdtTtTestData.
Definition at line 23 of file mdtTtTestData.cpp.
mdtTtTestData::mdtTtTestData (const QSqlRecord & record)
Contruct a mdtTtTestData from a QSqlRecord.
Note: if this method is used, setup is not relevant.
Precondition
All fields from Test_tbl must exist in record
Definition at line 28 of file mdtTtTestData.cpp.
References mdtSqlRecord::contains().
Member Function Documentation
void mdtTtTestData::clearValues () virtual
Clear values.
Reimplemented from mdtSqlRecord.
Definition at line 47 of file mdtTtTestData.cpp.
References mdtSqlRecord::clearValues().
const mdtTtTestModelData& mdtTtTestData::modelData () const inline
Get model data.
Definition at line 61 of file mdtTtTestData.h.
void mdtTtTestData::setModelData (const mdtTtTestModelData & data)
Set model data.
Will also update TestModel_Id_FK
Definition at line 53 of file mdtTtTestData.cpp.
References mdtSqlRecord::contains(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
bool mdtTtTestData::setup (const QSqlDatabase & db, bool setupModelData)
Setup fields from TestModel_tbl.
Definition at line 37 of file mdtTtTestData.cpp.
References mdtSqlRecord::addAllFields(), and mdtTtTestModelData::setup().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestData.h
src/mdttools/mdttesttool/mdtTtTestData.cpp