Multi diag tools: mdtFrameCodecAscii Class Reference
mdtFrameCodecAscii Class Reference
#include <mdtFrameCodecAscii.h>
Public Member Functions
mdtFrameCodecAscii ()
~mdtFrameCodecAscii ()
void setEofSeq (QByteArray &eofSeq)
Set the Eond Of Frame Sequence.
void trim ()
Remove whitespaces at begin and end of data frame.
void setCaseUpper ()
Set frame's data to upper case.
QVariant convertData (const QString &data) const
Convert a string to first matching type.
Public Member Functions inherited from mdtFrameCodec
mdtFrameCodec ()
~mdtFrameCodec ()
const QList< QVariant > & values () const
Get the decoded values.
Protected Member Functions
bool clean ()
Clean frame.
bool removeEofSeq ()
Remove the End Of Frame Sequence.
Protected Attributes
QString pvAsciiData
QByteArray pvEofSeq
QStringList pvNodes
Protected Attributes inherited from mdtFrameCodec
QList< QVariant > pvValues
Detailed Description
Definition at line 29 of file mdtFrameCodecAscii.h.
Constructor & Destructor Documentation
mdtFrameCodecAscii::mdtFrameCodecAscii ()
Definition at line 25 of file mdtFrameCodecAscii.cpp.
References pvEofSeq.
mdtFrameCodecAscii::~mdtFrameCodecAscii ()
Definition at line 30 of file mdtFrameCodecAscii.cpp.
Member Function Documentation
bool mdtFrameCodecAscii::clean () protected
Clean frame.
Helper method that removes white spaces at beginning and end of internal data (see QString::trimmed()). Next, the EOF seuqence is removed.
If a step fails, a message is added to mdtError system.
Returns
true if EOF could be removed, and data size is > 0 after clean.
Definition at line 92 of file mdtFrameCodecAscii.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_FRAME_DECODE_ERROR, pvAsciiData, and removeEofSeq().
Referenced by mdtFrameCodecScpi::decodeError(), mdtFrameCodecScpi::decodeIdn(), mdtFrameCodecScpi::decodeScpiVersion(), and mdtFrameCodecScpi::decodeValues().
QVariant mdtFrameCodecAscii::convertData (const QString & data) const
Convert a string to first matching type.
Definition at line 59 of file mdtFrameCodecAscii.cpp.
Referenced by mdtFrameCodecScpi::decodeFunctionParameters(), and mdtFrameCodecScpi::decodeValues().
bool mdtFrameCodecAscii::removeEofSeq () protected
Remove the End Of Frame Sequence.
Note: this method does nothing if EofSeq was not set
Definition at line 111 of file mdtFrameCodecAscii.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_FRAME_DECODE_ERROR, pvAsciiData, and pvEofSeq.
Referenced by clean(), mdtFrameCodecScpi::decodeFunctionParameters(), and mdtFrameCodecScpi::decodeSingleValueDouble().
void mdtFrameCodecAscii::setCaseUpper ()
Set frame's data to upper case.
Definition at line 54 of file mdtFrameCodecAscii.cpp.
References pvAsciiData.
void mdtFrameCodecAscii::setEofSeq (QByteArray & eofSeq)
Set the Eond Of Frame Sequence.
When using mdtLibrary's communication classes, the endOfFrame sequence is allready removed. So, this setup is optional.
See Also
mdtFrame
mdtPort
mdtPortManager
Definition at line 34 of file mdtFrameCodecAscii.cpp.
References pvEofSeq.
void mdtFrameCodecAscii::trim ()
Remove whitespaces at begin and end of data frame.
Definition at line 49 of file mdtFrameCodecAscii.cpp.
References pvAsciiData.
Referenced by mdtFrameCodecScpi::decodeFunctionParameters(), and mdtFrameCodecScpi::decodeSingleValueDouble().
Member Data Documentation
QString mdtFrameCodecAscii::pvAsciiData protected
Definition at line 79 of file mdtFrameCodecAscii.h.
Referenced by clean(), mdtFrameCodecScpi::decodeError(), mdtFrameCodecScpi::decodeFunctionParameters(), mdtFrameCodecScpi::decodeIdn(), mdtFrameCodecScpi::decodeScpiVersion(), mdtFrameCodecScpi::decodeSingleValueDouble(), mdtFrameCodecScpi::decodeValues(), removeEofSeq(), setCaseUpper(), and trim().
QByteArray mdtFrameCodecAscii::pvEofSeq protected
Definition at line 80 of file mdtFrameCodecAscii.h.
Referenced by mdtFrameCodecAscii(), removeEofSeq(), and setEofSeq().
QStringList mdtFrameCodecAscii::pvNodes protected
Definition at line 81 of file mdtFrameCodecAscii.h.
Referenced by mdtFrameCodecScpiU3606A::decodeConfigure(), mdtFrameCodecScpi::decodeError(), mdtFrameCodecScpi::decodeFunctionParameters(), mdtFrameCodecScpi::decodeIdn(), mdtFrameCodecScpi::decodeScpiVersion(), and mdtFrameCodecScpi::decodeValues().
The documentation for this class was generated from the following files:
src/mdtutils/mdtFrameCodecAscii.h
src/mdtutils/mdtFrameCodecAscii.cpp