Multi diag tools: mdtItemsSelectorDialog Class Reference
mdtItemsSelectorDialog Class Reference
Provide the user a dialog in witch he can choose items.
#include <mdtItemsSelectorDialog.h>
Public Member Functions
mdtItemsSelectorDialog (QWidget *parent=0)
Constructor.
~mdtItemsSelectorDialog ()
Destructor.
void clear ()
Clear dialog.
void setSortOptionEnabled (bool enabled)
Enable/diseable sort option.
void setAvailableItemsLabelText (const QString &text)
Set the Available items label text.
void setAvailableItems (const QList< mdtItemsSelectorDialogItem > &items)
Set the Available items.
void setSelectedItemsLabelText (const QString &text)
Set the selected items label text.
void setSelectedItems (const QList< mdtItemsSelectorDialogItem > &items)
Set the Available items.
const QList
< mdtItemsSelectorDialogItem > & selectedItems () const
Get list of selected items.
QStringList selectedItemsTexts () const
Get list of selected items texts.
QStringList selectedItemsNames () const
Get list of selected items names.
const QList
< mdtItemsSelectorDialogItem > & notSelectedItems () const
Get list of not selected items.
Additional Inherited Members
Private Member Functions inherited from Ui_mdtItemsSelectorDialog
void setupUi (QDialog *mdtItemsSelectorDialog)
void retranslateUi (QDialog *mdtItemsSelectorDialog)
Private Attributes inherited from Ui_mdtItemsSelectorDialog
QVBoxLayout * verticalLayout_4
QHBoxLayout * horizontalLayout_4
QVBoxLayout * verticalLayout
QHBoxLayout * horizontalLayout
QLabel * lbSelectedItems
QPushButton * pbSelectAllSelectedItems
QPushButton * pbUnselectAllSelectedItems
QHBoxLayout * horizontalLayout_3
QPushButton * pbDown
QPushButton * pbUp
QPushButton * pbTop
QLabel * lbSortOrder
QComboBox * cbSortOrder
QSpacerItem * horizontalSpacer
QListView * lwSelectedItems
QVBoxLayout * verticalLayout_3
QSpacerItem * verticalSpacer_2
QPushButton * pbRight
QPushButton * pbLeft
QSpacerItem * verticalSpacer
QVBoxLayout * verticalLayout_2
QHBoxLayout * horizontalLayout_2
QLabel * lbAvailableItems
QPushButton * pbSelectAllAvailableItems
QPushButton * pbUnselectAllAvailableItems
QListView * lwAvailableItems
QDialogButtonBox * buttonBox
Detailed Description
Provide the user a dialog in witch he can choose items.
Definition at line 38 of file mdtItemsSelectorDialog.h.
Constructor & Destructor Documentation
mdtItemsSelectorDialog::mdtItemsSelectorDialog (QWidget * parent = 0)
Constructor.
Definition at line 31 of file mdtItemsSelectorDialog.cpp.
References Ui_mdtItemsSelectorDialog::cbSortOrder, Ui_mdtItemsSelectorDialog::lwAvailableItems, Ui_mdtItemsSelectorDialog::lwSelectedItems, Ui_mdtItemsSelectorDialog::pbDown, Ui_mdtItemsSelectorDialog::pbLeft, Ui_mdtItemsSelectorDialog::pbRight, Ui_mdtItemsSelectorDialog::pbSelectAllAvailableItems, Ui_mdtItemsSelectorDialog::pbSelectAllSelectedItems, Ui_mdtItemsSelectorDialog::pbTop, Ui_mdtItemsSelectorDialog::pbUnselectAllAvailableItems, Ui_mdtItemsSelectorDialog::pbUnselectAllSelectedItems, Ui_mdtItemsSelectorDialog::pbUp, and Ui_mdtItemsSelectorDialog::setupUi().
mdtItemsSelectorDialog::~mdtItemsSelectorDialog ()
Destructor.
Definition at line 61 of file mdtItemsSelectorDialog.cpp.
Member Function Documentation
void mdtItemsSelectorDialog::clear ()
Clear dialog.
Definition at line 65 of file mdtItemsSelectorDialog.cpp.
const QList< mdtItemsSelectorDialogItem > & mdtItemsSelectorDialog::notSelectedItems () const
Get list of not selected items.
Definition at line 142 of file mdtItemsSelectorDialog.cpp.
const QList< mdtItemsSelectorDialogItem > & mdtItemsSelectorDialog::selectedItems () const
Get list of selected items.
Definition at line 113 of file mdtItemsSelectorDialog.cpp.
QStringList mdtItemsSelectorDialog::selectedItemsNames () const
Get list of selected items names.
Definition at line 130 of file mdtItemsSelectorDialog.cpp.
QStringList mdtItemsSelectorDialog::selectedItemsTexts () const
Get list of selected items texts.
Definition at line 118 of file mdtItemsSelectorDialog.cpp.
void mdtItemsSelectorDialog::setAvailableItems (const QList< mdtItemsSelectorDialogItem > & items)
Set the Available items.
Definition at line 96 of file mdtItemsSelectorDialog.cpp.
void mdtItemsSelectorDialog::setAvailableItemsLabelText (const QString & text)
Set the Available items label text.
Definition at line 91 of file mdtItemsSelectorDialog.cpp.
References Ui_mdtItemsSelectorDialog::lbAvailableItems.
Referenced by mdtMvColumnSelectionDialog::mdtMvColumnSelectionDialog(), and mdtMvSortingSetupDialog::mdtMvSortingSetupDialog().
void mdtItemsSelectorDialog::setSelectedItems (const QList< mdtItemsSelectorDialogItem > & items)
Set the Available items.
Definition at line 107 of file mdtItemsSelectorDialog.cpp.
void mdtItemsSelectorDialog::setSelectedItemsLabelText (const QString & text)
Set the selected items label text.
Definition at line 102 of file mdtItemsSelectorDialog.cpp.
References Ui_mdtItemsSelectorDialog::lbSelectedItems.
Referenced by mdtMvColumnSelectionDialog::mdtMvColumnSelectionDialog(), and mdtMvSortingSetupDialog::mdtMvSortingSetupDialog().
void mdtItemsSelectorDialog::setSortOptionEnabled (bool enabled)
Enable/diseable sort option.
Definition at line 73 of file mdtItemsSelectorDialog.cpp.
References Ui_mdtItemsSelectorDialog::cbSortOrder, Ui_mdtItemsSelectorDialog::lbSortOrder, and Ui_mdtItemsSelectorDialog::lwSelectedItems.
Referenced by mdtMvColumnSelectionDialog::mdtMvColumnSelectionDialog(), and mdtMvSortingSetupDialog::mdtMvSortingSetupDialog().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtItemsSelectorDialog.h
src/mdtutilsgui/mdtItemsSelectorDialog.cpp