Multi diag tools: mdtValue Class Reference
mdtValue Class Reference
Conatins a value with some attributes.
#include <mdtValue.h>
Public Member Functions
mdtValue ()
Construct a invalid value.
mdtValue (double value, bool isMinusOl=false, bool isPlusOl=false)
Construct a valid value with double format.
mdtValue (int value, bool isMinusOl=false, bool isPlusOl=false)
Construct a valid value with int format.
mdtValue (bool value)
Construct a valid value with bool format.
void clear ()
Clear values (set default values) and unset validity flag.
void setDefaultValue (double value)
Set default value for double format.
void setDefaultValue (int value)
Set default value for int format.
void setDefaultValue (bool value)
Set default value for bool format.
void setValue (double value, bool isMinusOl=false, bool isPlusOl=false)
Set value with double format.
bool hasValueDouble () const
Check if value as double format is available.
double valueDouble () const
Get the value stored in double format.
void setValue (int value, bool isMinusOl=false, bool isPlusOl=false)
Set value with int format.
bool hasValueInt () const
Check if value as int format is available.
int valueInt () const
Get the value stored in int format.
bool isMinusOl () const
Check if value is -OL.
bool isPlusOl () const
Check if value is +OL.
void setValue (bool value)
Set value with bool format.
bool hasValueBool () const
Check if value as bool format is available.
bool valueBool () const
Get the value stored in bool format.
bool isValid () const
Get the validity flag.
bool operator== (const mdtValue &other) const
Comparaison operator.
bool operator!= (const mdtValue &other) const
Comparaison operator.
Detailed Description
Conatins a value with some attributes.
Most of cases, using standard C++ types are sufficent. If a value must be stored in different way, Qt offers QVariant, witch can convert values between different types, has a validity flag and more.
When dealing with instruments, some other data are needed, for example:
+OL, -OL
For case of invalid data: is a convertion error occured, a communication error or something else ?
Storing data in many format, typical: double and/or int (see mdtAnalogIo for details)
Note that this class does no convertion, but is a simple container.
Note about -OL/+OL flags: the last setter (setValue(double, bool, bool) or setValue(int, bool, bool)) will overwrite this flags. The setValue(bool) does not affect this flags.
Definition at line 490 of file mdtValue.h.
Constructor & Destructor Documentation
mdtValue::mdtValue ()
Construct a invalid value.
Definition at line 148 of file mdtValue.cpp.
References clear(), and setDefaultValue().
mdtValue::mdtValue (double value, bool isMinusOl = false, bool isPlusOl = false)
Construct a valid value with double format.
Parameters
value Value to store
isMinusOl -OL flag
isPlusOl +OL flag
Definition at line 156 of file mdtValue.cpp.
References clear(), setDefaultValue(), and setValue().
mdtValue::mdtValue (int value, bool isMinusOl = false, bool isPlusOl = false)
Construct a valid value with int format.
Parameters
value Value to store
isMinusOl -OL flag
isPlusOl +OL flag
Definition at line 165 of file mdtValue.cpp.
References clear(), setDefaultValue(), and setValue().
mdtValue::mdtValue (bool value)
Construct a valid value with bool format.
Parameters
value Value to store
Definition at line 174 of file mdtValue.cpp.
References clear(), setDefaultValue(), and setValue().
Member Function Documentation
void mdtValue::clear ()
Clear values (set default values) and unset validity flag.
Definition at line 183 of file mdtValue.cpp.
Referenced by mdtFrameCodecScpiU3606A::decodeConfigure(), mdtValue(), mdtAnalogIo::setRange(), and mdtDigitalIo::setValue().
bool mdtValue::hasValueBool () const
Check if value as bool format is available.
Definition at line 266 of file mdtValue.cpp.
bool mdtValue::hasValueDouble () const
Check if value as double format is available.
Definition at line 220 of file mdtValue.cpp.
Referenced by mdtAnalogIo::setValue().
bool mdtValue::hasValueInt () const
Check if value as int format is available.
Definition at line 239 of file mdtValue.cpp.
bool mdtValue::isMinusOl () const
Check if value is -OL.
Definition at line 249 of file mdtValue.cpp.
Referenced by operator<<(), and setValue().
bool mdtValue::isPlusOl () const
Check if value is +OL.
Definition at line 254 of file mdtValue.cpp.
Referenced by operator<<(), and setValue().
bool mdtValue::isValid () const
Get the validity flag.
A mdtValue is considered valid if one value was set (double, int or bool). After a call of clear(), the validity flag becomes false.
Note: if -OL or +OL flag is set, the value is considered as valid.
Definition at line 276 of file mdtValue.cpp.
Referenced by mdtAbstractIo::hasValidData(), operator<<(), and mdtDigitalIo::setValue().
bool mdtValue::operator!= (const mdtValue & other) const
Comparaison operator.
Definition at line 313 of file mdtValue.cpp.
References operator==().
bool mdtValue::operator== (const mdtValue & other) const
Comparaison operator.
If all members are equal (values and flags), true is returned.
Definition at line 281 of file mdtValue.cpp.
Referenced by operator!=().
void mdtValue::setDefaultValue (double value)
Set default value for double format.
Parameters
value Value to store as default
Definition at line 196 of file mdtValue.cpp.
Referenced by mdtValue(), and mdtAnalogIo::setRange().
void mdtValue::setDefaultValue (int value)
Set default value for int format.
Parameters
value Value to store as default
Definition at line 201 of file mdtValue.cpp.
void mdtValue::setDefaultValue (bool value)
Set default value for bool format.
Parameters
value Value to store as default
Definition at line 206 of file mdtValue.cpp.
void mdtValue::setValue (double value, bool isMinusOl = false, bool isPlusOl = false)
Set value with double format.
Parameters
value Value to store
isMinusOl -OL flag
isPlusOl +OL flag
Definition at line 211 of file mdtValue.cpp.
References isMinusOl(), and isPlusOl().
Referenced by mdtFrameCodecScpi::checkFloatingValueValidity(), mdtFrameCodecScpi::decodeValues(), mdtValue(), mdtDigitalIo::setValue(), and mdtAnalogIo::setValueInt().
void mdtValue::setValue (int value, bool isMinusOl = false, bool isPlusOl = false)
Set value with int format.
Parameters
value Value to store
isMinusOl -OL flag
isPlusOl +OL flag
Definition at line 230 of file mdtValue.cpp.
References isMinusOl(), and isPlusOl().
void mdtValue::setValue (bool value)
Set value with bool format.
Parameters
value Value to store
Definition at line 259 of file mdtValue.cpp.
bool mdtValue::valueBool () const
Get the value stored in bool format.
Definition at line 271 of file mdtValue.cpp.
Referenced by operator<<(), mdtDevice::setDigitalOutputValue(), and mdtDigitalIo::setValue().
double mdtValue::valueDouble () const
Get the value stored in double format.
Definition at line 225 of file mdtValue.cpp.
Referenced by operator<<(), and mdtAnalogIo::setRange().
int mdtValue::valueInt () const
Get the value stored in int format.
Definition at line 244 of file mdtValue.cpp.
Referenced by operator<<(), mdtDevice::setAnalogOutputValue(), and mdtAnalogIo::setRange().
The documentation for this class was generated from the following files:
src/mdtutils/mdtValue.h
src/mdtutils/mdtValue.cpp