Multi diag tools: mdtDataTableManager Class Reference
mdtDataTableManager Class Reference
Create/manage data sets.
#include <mdtDataTableManager.h>
Public Member Functions
mdtDataTableManager (QObject *parent=0, QSqlDatabase db=QSqlDatabase())
~mdtDataTableManager ()
Note: this will delete internal model. Be avare when referencing pointer returned by model().
mdtError lastError () const
Get last error.
void close ()
Close.
bool setDataSetDirectory (const QDir &dir)
Set dataset directory.
QDir dataSetDirectory () const
Set dataset directory.
const QString dataSetTableName () const
Get dataset table name.
bool createDataSet (const QDir &dir, const QString &name, mdtSqlSchemaTable &table, mdtSqlDatabaseManager::createMode_t mode)
Create database and table.
QSqlDatabase database () const
Get internal database instance.
void enableProgressDialog (bool enable)
Enable/disable progress dialog.
void setCsvFormat (const QString &separator, const QString &dataProtection, const QString &comment, const QChar &escapeChar, QByteArray eol=MDT_NATIVE_EOL, const QByteArray &encoding="UTF-8")
Set CSV import/export format.
bool exportToCsvFile (const QString &filePath, mdtSqlDatabaseManager::createMode_t mode)
Export data to a CSV file.
bool importFromCsvFile (const QString &csvFilePath, mdtSqlDatabaseManager::createMode_t mode, const QString &dir=QString(), const QStringList &pkFields=QStringList())
Import a CSV file.
bool copyTable (const QString &sourceTableName, const QString &destinationTableName, mdtSqlDatabaseManager::createMode_t mode, QSqlDatabase sourceDatabase=QSqlDatabase(), QSqlDatabase destinationDatabase=QSqlDatabase())
Copy a source table to a destination table.
void addFieldMapping (const QString &csvHeaderItem, const QString &fieldName, const QString &displayText, QVariant::Type dataType, int csvDataItemStartOffset=-1, int csvDataItemEndOffset=-1)
Add a mapping between CSV header part (item) and model field.
void clearFieldMap ()
Clear fields mapping.
QStringList sourceHeader () const
Get the source header.
const QStringList databaseHeader () const
Get database header.
void setDatabaseHeaderToModel (QAbstractTableModel *model)
Set database header to model.
QHash< QString, QString > displayTextsByFieldNames () const
Get display texts referenced by field names.
Static Public Member Functions
static QString getTableName (const QString &dataSetName)
Remove unalowed chars and suffixe _tbl to name to give a table name.
Detailed Description
Create/manage data sets.
Definition at line 47 of file mdtDataTableManager.h.
Constructor & Destructor Documentation
mdtDataTableManager::mdtDataTableManager (QObject * parent = 0, QSqlDatabase db = QSqlDatabase())
Definition at line 40 of file mdtDataTableManager.cpp.
References MDT_NATIVE_EOL, setCsvFormat(), and mdtSqlDatabaseManager::setDatabase().
mdtDataTableManager::~mdtDataTableManager ()
Note: this will delete internal model. Be avare when referencing pointer returned by model().
Definition at line 50 of file mdtDataTableManager.cpp.
Member Function Documentation
void mdtDataTableManager::addFieldMapping (const QString & csvHeaderItem, const QString & fieldName, const QString & displayText, QVariant::Type dataType, int csvDataItemStartOffset = -1, int csvDataItemEndOffset = -1)
Add a mapping between CSV header part (item) and model field.
Field mapping is used for relationship between CSV header, model's field name and texts to display in model's header. Internally, mdtFieldMap class is used for this.
During CSV import, all unspecified maps are automatically created as follow:
Data are imported as string (type: QVariant::String)
Field name is based on CSV header item, but unalowed chars are replaced by '_'
Display text is the CSV header item.
One field is created in model for one CSV header item (column).
If some of this default behaviour is not what is needed for some fields, it's possible to add a mapping with this method befor calling importFromCsvFile().
It's also possible to split a CSV header item to many model fields. To do this, add several mapping with same csvHeaderItem, but using each time another fieldName. To know wich part of a CSV data item must be stored in witch field, csvDataItemStartOffset and csvDataItemEndOffset must be specified.
Parameters
csvHeaderItem CSV heaer part (column).
fieldName Model's field name to create.
displayText Text to display in model's header.
dataType Data will be converted to this data type during import.
csvDataItemStartOffset If >= 0, only data starting at this offset will be imported from CSV data item into model's field.
csvDataItemEndOffset If >= 0, only data until this offset will be imported from CSV data item into model's field.
See Also
mdtFieldMap
mdtFieldMapItem
Definition at line 530 of file mdtDataTableManager.cpp.
References mdtFieldMap::addItem(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtFieldMapItem::setDataType(), mdtFieldMapItem::setDestinationFieldDisplayText(), mdtFieldMapItem::setDestinationFieldName(), mdtError::setError(), mdtFieldMapItem::setSourceFieldDataEndOffset(), mdtFieldMapItem::setSourceFieldDataStartOffset(), and mdtFieldMapItem::setSourceFieldName().
void mdtDataTableManager::clearFieldMap ()
Clear fields mapping.
See Also
addFieldMapping()
Definition at line 550 of file mdtDataTableManager.cpp.
References mdtFieldMap::clear().
Referenced by mdtTtDatabaseSchema::importDatabase().
void mdtDataTableManager::close ()
Close.
Will close database.
Definition at line 59 of file mdtDataTableManager.cpp.
References mdtSqlDatabaseManager::database().
Referenced by copyTable(), and importFromCsvFile().
bool mdtDataTableManager::copyTable (const QString & sourceTableName, const QString & destinationTableName, mdtSqlDatabaseManager::createMode_t mode, QSqlDatabase sourceDatabase = QSqlDatabase(), QSqlDatabase destinationDatabase = QSqlDatabase())
Copy a source table to a destination table.
Parameters
sourceTableName Name of the source table .
destinationTableName Name of the destination table .
mode Behaviour to adopt if destination table allready exists .
sourceDatabase Instance of source database .
destinationDatabase Instance of destination database .
Returns
True on success, false if a error occured . Use lastError() to know what gone wrong in second case .
Definition at line 373 of file mdtDataTableManager.cpp.
References mdtSqlSchemaTable::addField(), mdtFieldMap::addItem(), close(), mdtError::commit(), mdtSqlDatabaseManager::createTable(), mdtFieldMap::destinationDataRow(), mdtError::Error, mdtFieldMap::itemsAtSourceFieldName(), mdtSqlDatabaseManager::lastError(), mdtFieldMap::mappedDestinationFields(), mdtFieldMap::mappedSourceFields(), MDT_ERROR_SET_SRC, mdtSqlDatabaseManager::setDatabase(), mdtFieldMapItem::setDestinationField(), mdtFieldMapItem::setDestinationFieldIndex(), mdtError::setError(), mdtFieldMapItem::setSourceField(), mdtFieldMapItem::setSourceFieldIndex(), mdtFieldMap::setSourceFields(), mdtFieldMapField::setSqlField(), mdtError::setSystemError(), mdtSqlSchemaTable::setTableName(), mdtError::text(), and mdtError::updateText().
Referenced by mdtTtDatabaseSchema::importDatabase().
bool mdtDataTableManager::createDataSet (const QDir & dir, const QString & name, mdtSqlSchemaTable & table, mdtSqlDatabaseManager::createMode_t mode)
Create database and table.
Internally, Sqlite is used to store data.
Note: this will delete internal model and create a new one. Be avare when referencing pointer returned by model().
Parameters
dir Path or QDir object to directory in witch to store data.
table Schema of the table to create .
name Name of the database, connection name (see QSqlDatabase) and file.
mode Behaviour to adopt during database/file creation.
Returns
True on success.
Definition at line 125 of file mdtDataTableManager.cpp.
References mdtSqlDatabaseManager::createDatabaseSqlite(), mdtSqlDatabaseManager::createTable(), getTableName(), mdtSqlDatabaseManager::lastError(), and mdtSqlSchemaTable::setTableName().
Referenced by importFromCsvFile().
QSqlDatabase mdtDataTableManager::database () const
Get internal database instance.
Definition at line 155 of file mdtDataTableManager.cpp.
References mdtSqlDatabaseManager::database().
const QStringList mdtDataTableManager::databaseHeader () const
Get database header.
Definition at line 560 of file mdtDataTableManager.cpp.
QDir mdtDataTableManager::dataSetDirectory () const
Set dataset directory.
Todo:
Not used yet.
Definition at line 78 of file mdtDataTableManager.cpp.
const QString mdtDataTableManager::dataSetTableName () const
Get dataset table name.
Definition at line 83 of file mdtDataTableManager.cpp.
QHash< QString, QString > mdtDataTableManager::displayTextsByFieldNames () const
Get display texts referenced by field names.
Returns
QHash with fieldName as key and displayText as value.
Definition at line 579 of file mdtDataTableManager.cpp.
References mdtFieldMap::displayTextsByFieldNames().
void mdtDataTableManager::enableProgressDialog (bool enable)
Enable/disable progress dialog.
If progress dialog is enabled, some methods will show her progress in a dialog.
Definition at line 160 of file mdtDataTableManager.cpp.
Referenced by mdtTtDatabaseSchema::importDatabase().
bool mdtDataTableManager::exportToCsvFile (const QString & filePath, mdtSqlDatabaseManager::createMode_t mode)
Export data to a CSV file.
Parameters
filePath Path to CSV file
mode Behaviour to adopt if CSV file allready exists.
Returns
True on successfull export.
Todo:
Add: separator, data protection, escape char, EOL
Implement ...
Definition at line 184 of file mdtDataTableManager.cpp.
QString mdtDataTableManager::getTableName (const QString & dataSetName) static
Remove unalowed chars and suffixe _tbl to name to give a table name.
Definition at line 88 of file mdtDataTableManager.cpp.
Referenced by createDataSet().
bool mdtDataTableManager::importFromCsvFile (const QString & csvFilePath, mdtSqlDatabaseManager::createMode_t mode, const QString & dir = QString(), const QStringList & pkFields = QStringList())
Import a CSV file.
Note: this will delete internal model and create a new one. Be avare when referencing pointer returned by model().
Parameters
csvFilePath Path to the CSV file.
mode Behaviour to adopt when data table allready exists.
dir Destination of the database file. If not defined, csvFilePath's directory is used.
pkFields List of fields to considere as part of primary key. If list is empty, one named id_PK will be created.
Precondition
All given CSV header items to use as part of primary key must exit in CSV file (See pkFields argument).
Definition at line 189 of file mdtDataTableManager.cpp.
References mdtSqlSchemaTable::addField(), mdtFieldMap::addItem(), mdtCsvFile::close(), close(), mdtError::commit(), createDataSet(), mdtFieldMap::destinationDataRow(), mdtFieldMap::destinationHeader(), mdtError::Error, mdtSqlSchemaTable::fieldCount(), mdtFieldMapField::getFieldName(), mdtCsvFile::hasMoreLines(), mdtFieldMap::itemsAtSourceFieldName(), mdtFieldMap::mappedDestinationFields(), MDT_ERROR_SET_SRC, mdtCsvFile::readHeader(), mdtCsvFile::readLine(), mdtFieldMapItem::setDataType(), mdtFieldMapItem::setDestinationFieldDisplayText(), mdtFieldMapItem::setDestinationFieldIndex(), mdtFieldMapItem::setDestinationFieldName(), mdtError::setError(), mdtFieldMapItem::setSourceFieldIndex(), mdtFieldMapItem::setSourceFieldName(), and mdtError::Warning.
mdtError mdtDataTableManager::lastError () const
Get last error.
Definition at line 54 of file mdtDataTableManager.cpp.
Referenced by mdtTtDatabaseSchema::importDatabase().
void mdtDataTableManager::setCsvFormat (const QString & separator, const QString & dataProtection, const QString & comment, const QChar & escapeChar, QByteArray eol = MDT_NATIVE_EOL, const QByteArray & encoding = "UTF-8")
Set CSV import/export format.
Parameters
separator Separator to use (typical: ;)
dataProtection Data protection (typical: ")
comment Comment (typical: #)
escapeChar Escape char (typical: \). Note: has only effect to escape dataProtection.
eol End of line sequence. Usefull if given file was not written from running platform.
encoding Name of the encoding format, for example, UTF-8 If given encoding is not available, UTF-8 is choosen.
Definition at line 165 of file mdtDataTableManager.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, mdtError::setError(), and mdtError::Warning.
Referenced by mdtDataTableManager().
void mdtDataTableManager::setDatabaseHeaderToModel (QAbstractTableModel * model)
Set database header to model.
Definition at line 565 of file mdtDataTableManager.cpp.
bool mdtDataTableManager::setDataSetDirectory (const QDir & dir)
Set dataset directory.
Parameters
dir Path or QDir object to directory.
Returns
True if directory exists.
Todo:
Not used yet.
Definition at line 65 of file mdtDataTableManager.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and mdtError::setError().
QStringList mdtDataTableManager::sourceHeader () const
Get the source header.
Definition at line 555 of file mdtDataTableManager.cpp.
References mdtFieldMap::sourceHeader().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtDataTableManager.h
src/mdtdatabase/mdtDataTableManager.cpp