Multi diag tools: mdtAbstractSqlWidget Class Reference
mdtAbstractSqlWidget Class Reference abstract
Base class to create database table GUI.
#include <mdtAbstractSqlWidget.h>
Public Types
enum state_t {
Visualizing = 0, Reverting, Editing, Submitting,
Inserting, EditingNewRow, RevertingNewRow, SubmittingNewRow,
Removing
}
State of edit/view widget.
Public Slots
void submit ()
Submit current record to model.
void revert ()
Revert current record from model.
void insert ()
Insert a new row to model.
void remove ()
Remove a row from model.
virtual void toFirst ()=0
Set first record as current record.
virtual void toLast ()=0
Set last record as current record.
virtual void toPrevious ()=0
Set previous record as current record.
virtual void toNext ()=0
Set next record as current record.
virtual void setCurrentIndex (int row)=0
Set row as current record.
bool setCurrentRecord (const QString &fieldName, const QVariant &value)
Set the first record that matches given criteria as current record (index).
bool reEnterVisualizingState ()
Re-enter in visualizing state.
Signals
void toFirstEnabledStateChanged (bool enabled)
Emitted when toFirst() function goes enabled/disabled.
void toLastEnabledStateChanged (bool enabled)
Emitted when toLast() function goes enabled/disabled.
void toNextEnabledStateChanged (bool enabled)
Emitted when toNext() function goes enabled/disabled.
void toPreviousEnabledStateChanged (bool enabled)
Emitted when toPrevious() function goes enabled/disabled.
void submitEnabledStateChanged (bool enabled)
Emitted when submit() function goes enabled/disabled.
void revertEnabledStateChanged (bool enabled)
Emitted when revert() function goes enabled/disabled.
void insertEnabledStateChanged (bool enabled)
Emitted when insert() function goes enabled/disabled.
void removeEnabledStateChanged (bool enabled)
Emitted when remove() function goes enabled/disabled.
void submitTriggered ()
Emitted when submit() was called.
void revertTriggered ()
Emitted when revert() was called.
void insertTriggered ()
Emitted when insert() was called.
void removeTriggered ()
Emitted when remove() was called.
void errorOccured ()
Emitted when a error occured.
void operationSucceed ()
Emitted when a operation succeed.
void dataEdited ()
Emitted when data was edited.
void stateVisualizingEntered ()
Emitted when Visualizing state was entered.
void stateVisualizingExited ()
Emitted when Visualizing state was exited.
void stateEditingExited ()
Emitted when Editing state was exited.
void stateEditingNewRowExited ()
Emitted when Editing state was exited.
void currentRowChanged (int row)
Emitted when current row has changed.
void modelSelected ()
Emitted when select() or setQuery() was called on (parent) model.
Public Member Functions
mdtAbstractSqlWidget (QWidget *parent=0)
Constructor.
virtual ~mdtAbstractSqlWidget ()
Destructor.
void setModel (QSqlTableModel *model)
Set the table model.
QSqlTableModel * model ()
Get current model.
void addDataValidator (mdtSqlDataValidator *validator, bool putAtTopPriority=false)
Add a data validator.
void setUserFriendlyTableName (const QString &name)
Set the user friendly table name.
QString userFriendlyTableName () const
Get the user friendly table name.
void addChildWidget (mdtAbstractSqlWidget *widget, mdtSqlRelation *relation)
Add a child (details) widget and relation.
QList< mdtAbstractSqlWidget * > sqlWidgets ()
Get a list of all SQL widgets.
virtual int currentRow () const =0
Get the current row.
bool setCurrentData (const QString &fieldName, const QVariant &data, bool submit=true)
Set (update) data of current row (record) for given field name.
QVariant currentData (const QString &fieldName) const
Get current data for given field name.
QVariant data (int row, const QString &fieldName) const
Get data for given row and field name.
int rowCount () const
Get row count.
state_t currentState () const
Get current state.
virtual void enableLocalNavigation ()
Enable local navigation.
virtual void enableLocalEdition ()
Enable local edition.
bool allDataAreSaved ()
Check if all data are saved.
void clearColumnsSortOrder ()
Clear columns sort order.
void addColumnToSortOrder (const QString &fieldName, Qt::SortOrder order=Qt::AscendingOrder)
Add a column to columns sort order.
virtual void sort ()
Sort data.
Protected Member Functions
virtual void doSetModel (QSqlTableModel *model)=0
Set the table model.
virtual bool doSubmit ()=0
Submit current row to model.
virtual bool doRevert ()=0
Revert current row from model.
virtual bool doInsert ()=0
Insert a row row to model.
virtual bool doSubmitNewRow ()=0
Submit new row to model.
virtual bool doRevertNewRow ()=0
Revert new row.
virtual bool doRemove ()=0
Remove current row from model.
void displayDatabaseError (QSqlError error)
Display a message to the user regarding error.
QString getUserReadableTextFromSqliteError (const QSqlError &error)
Get message for the user regarding SQLite error number.
QString getUserReadableTextFromMysqlError (const QSqlError &error)
Get message for the user regarding MySql error number.
bool childWidgetsAreInVisaluzingState ()
Check that child widgtes have no pending data.
void warnUserAboutUnsavedRow (const QString &tableName)
Show a message box to the user to warn him that it should save/revert data.
bool restorePrimaryKeyDataToModel (const QSqlRecord &previousRecord)
Restore primary key data to (parent) model.
mdtSortFilterProxyModel * proxyModel ()
Get internal proxy model.
const mdtSortFilterProxyModel * proxyModel () const
Get internal proxy model.
Detailed Description
Base class to create database table GUI.
Main goal is to provide a standard way to use GUI object for database table.
Definition at line 54 of file mdtAbstractSqlWidget.h.
Member Enumeration Documentation
enum mdtAbstractSqlWidget::state_t
State of edit/view widget.
This state is set by internal state machine.
Enumerator
Visualizing
Visualizing state
Reverting
Reverting state
Editing
Editing state
Submitting
Submitting state
Inserting
Inserting state
EditingNewRow
Editing a new row
RevertingNewRow
RevertingNewRow state
SubmittingNewRow
SubmittingNewRow state
Removing
Removing state
Definition at line 64 of file mdtAbstractSqlWidget.h.
Constructor & Destructor Documentation
mdtAbstractSqlWidget::mdtAbstractSqlWidget (QWidget * parent = 0)
Constructor.
Will initialize internal state machine.
Definition at line 40 of file mdtAbstractSqlWidget.cpp.
mdtAbstractSqlWidget::~mdtAbstractSqlWidget () virtual
Destructor.
Definition at line 48 of file mdtAbstractSqlWidget.cpp.
Member Function Documentation
void mdtAbstractSqlWidget::addChildWidget (mdtAbstractSqlWidget * widget, mdtSqlRelation * relation)
Add a child (details) widget and relation.
Needed signal/slot connection between widget and relation is done internally.
Precondition
(Parent) model must be set with setModel() before using this method.
widget must be a valid pointer
relation must be a valid pointer. Note: relation will be reparented, so it will be deleted automatically by Qt.
Definition at line 107 of file mdtAbstractSqlWidget.cpp.
References currentRow(), currentRowChanged(), and mdtSqlRelation::setParentCurrentIndex().
Referenced by mdtSqlForm::addChildTable().
void mdtAbstractSqlWidget::addColumnToSortOrder (const QString & fieldName, Qt::SortOrder order = Qt::AscendingOrder)
Add a column to columns sort order.
Columns sort order is similar meaning than SQL ORDER BY clause.
Internally, mdtSortFilterProxyModel is used, witch provide a natural sort for strings.
For example, to sort columns in order "Id_PK", "FirstName", "LastName", all ascending, call:
clearColumnsSortOrder();
addColumnToSortOrder("Id_PK", Qt::AscendingOrder);
addColumnToSortOrder("FirstName", Qt::AscendingOrder);
addColumnToSortOrder("LastName", Qt::AscendingOrder);
Note: if given field not exists, it will simply be ignored.
Note: to apply sorting, call sort()
Precondition
Model must be set with setModel() before using this method.
Definition at line 259 of file mdtAbstractSqlWidget.cpp.
References mdtSortFilterProxyModel::addColumnToSortOrder().
void mdtAbstractSqlWidget::addDataValidator (mdtSqlDataValidator * validator, bool putAtTopPriority = false)
Add a data validator.
Parameters
validator A instance of mdtSqlDataValidator or subclass.
putAtTopPriority If true, validator will be called before allready stored ones. (validators are put into a queue).
Note: validator will be reparented, so it will be destroyed automatically when this class is destroyed.
Precondition
(Parent) model must be set with setModel() before using this method.
validator must be a valid pointer.
Definition at line 77 of file mdtAbstractSqlWidget.cpp.
Referenced by mdtSqlFormWidget::mapFormWidgets().
bool mdtAbstractSqlWidget::allDataAreSaved ()
Check if all data are saved.
This will check state of main SQL widget (this widget) and state of all assigned child widgets. If one of them is not in Visualizing state, some data are not saved. In this case, a message box is displayed to the user.
This is used by mdtSqlWindow and mdtSqlDialog to check if it can close the window.
Returns
true if all data are saved, false if a SQL widget has pending data.
Definition at line 236 of file mdtAbstractSqlWidget.cpp.
References childWidgetsAreInVisaluzingState(), currentState(), userFriendlyTableName(), and Visualizing.
Referenced by mdtSqlDialog::accept(), mdtSqlForm::allDataAreSaved(), childWidgetsAreInVisaluzingState(), and mdtSqlDialog::reject().
bool mdtAbstractSqlWidget::childWidgetsAreInVisaluzingState () protected
Check that child widgtes have no pending data.
Definition at line 406 of file mdtAbstractSqlWidget.cpp.
References allDataAreSaved().
Referenced by allDataAreSaved(), mdtSqlFormWidget::setCurrentIndex(), mdtSqlFormWidget::toFirst(), mdtSqlFormWidget::toLast(), mdtSqlFormWidget::toNext(), and mdtSqlFormWidget::toPrevious().
void mdtAbstractSqlWidget::clearColumnsSortOrder ()
Clear columns sort order.
See Also
addColumnToSortOrder()
Definition at line 252 of file mdtAbstractSqlWidget.cpp.
References mdtSortFilterProxyModel::clearColumnsSortOrder().
QVariant mdtAbstractSqlWidget::currentData (const QString & fieldName) const
Get current data for given field name.
Precondition
(Parent) model must be set with setModel() before using this method.
Definition at line 176 of file mdtAbstractSqlWidget.cpp.
References currentRow(), and data().
Referenced by mdtSqlForm::currentData().
virtual int mdtAbstractSqlWidget::currentRow () const pure virtual
Get the current row.
Current row can be the currently selected row (case of a table view), or simply the current row that is displayed in a form view.
Subclass must implement this method.
Implemented in mdtSqlFormWidget, and mdtSqlTableWidget.
Referenced by addChildWidget(), currentData(), mdtSqlForm::currentRow(), restorePrimaryKeyDataToModel(), and setCurrentData().
void mdtAbstractSqlWidget::currentRowChanged (int row) signal
Emitted when current row has changed.
This is usefull, for example, in master/detail forms, to update child models filter.
Subclass must emit this signal each time the user selects a new row.
Referenced by addChildWidget().
mdtAbstractSqlWidget::state_t mdtAbstractSqlWidget::currentState () const
Get current state.
Definition at line 219 of file mdtAbstractSqlWidget.cpp.
References mdtStateMachine::currentState().
Referenced by allDataAreSaved(), reEnterVisualizingState(), mdtSqlFormWidget::setCurrentIndex(), mdtSqlFormWidget::toFirst(), mdtSqlFormWidget::toLast(), mdtSqlFormWidget::toNext(), and mdtSqlFormWidget::toPrevious().
QVariant mdtAbstractSqlWidget::data (int row, const QString & fieldName) const
Get data for given row and field name.
Precondition
(Parent) model must be set with setModel() before using this method.
Definition at line 183 of file mdtAbstractSqlWidget.cpp.
References mdtError::Error, MDT_DATABASE_ERROR, and MDT_ERROR_SET_SRC.
Referenced by currentData(), and mdtSqlForm::data().
void mdtAbstractSqlWidget::dataEdited () signal
Emitted when data was edited.
Referenced by mdtSqlFormWidget::mapFormWidgets(), and setCurrentData().
void mdtAbstractSqlWidget::displayDatabaseError (QSqlError error) protected
Display a message to the user regarding error.
Internally, error will be logged with mdtError system.
Precondition
Model must be set with setModel() before using this method.
Definition at line 330 of file mdtAbstractSqlWidget.cpp.
References mdtError::Error, getUserReadableTextFromMysqlError(), getUserReadableTextFromSqliteError(), MDT_DATABASE_ERROR, MDT_ERROR_SET_SRC, mdtError::setSystemError(), and userFriendlyTableName().
Referenced by setCurrentData().
virtual bool mdtAbstractSqlWidget::doInsert () protected pure virtual
Insert a row row to model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
virtual bool mdtAbstractSqlWidget::doRemove () protected pure virtual
Remove current row from model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
virtual bool mdtAbstractSqlWidget::doRevert () protected pure virtual
Revert current row from model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
Depending on subclass choosen EditStrategy, this method has potentially no effect.
virtual bool mdtAbstractSqlWidget::doRevertNewRow () protected pure virtual
Revert new row.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
virtual void mdtAbstractSqlWidget::doSetModel (QSqlTableModel * model) protected pure virtual
Set the table model.
Subclass must implement this method.
Precondition
model must be a valid pointer
Referenced by setModel().
virtual bool mdtAbstractSqlWidget::doSubmit () protected pure virtual
Submit current row to model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
Depending on subclass choosen EditStrategy, this method has potentially no effect.
virtual bool mdtAbstractSqlWidget::doSubmitNewRow () protected pure virtual
Submit new row to model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
void mdtAbstractSqlWidget::enableLocalEdition () virtual
Enable local edition.
Will add insert/revert/save/delete buttons.
In normal way, when using mdtSqlWindow, local navigation is not needed. In master/detail forms, if this widget is a details (child) widget and edition is needed, then call this method.
This default implementation does nothing.
Reimplemented in mdtSqlTableWidget.
Definition at line 232 of file mdtAbstractSqlWidget.cpp.
void mdtAbstractSqlWidget::enableLocalNavigation () virtual
Enable local navigation.
Will build a navigation bar with |<< < > >>| buttons.
In normal way, when using mdtSqlWindow, local navigation is not needed. In master/detail forms, if this widget is a details (child) widget and navigation is needed, then call this method.
This default implementation does nothing.
Definition at line 228 of file mdtAbstractSqlWidget.cpp.
void mdtAbstractSqlWidget::errorOccured () signal
Emitted when a error occured.
QString mdtAbstractSqlWidget::getUserReadableTextFromMysqlError (const QSqlError & error) protected
Get message for the user regarding MySql error number.
Definition at line 394 of file mdtAbstractSqlWidget.cpp.
Referenced by displayDatabaseError().
QString mdtAbstractSqlWidget::getUserReadableTextFromSqliteError (const QSqlError & error) protected
Get message for the user regarding SQLite error number.
Definition at line 369 of file mdtAbstractSqlWidget.cpp.
Referenced by displayDatabaseError().
void mdtAbstractSqlWidget::insert () slot
Insert a new row to model.
Internally, insertTriggered() signal will be emitted.
Definition at line 280 of file mdtAbstractSqlWidget.cpp.
References insertTriggered().
Referenced by mdtSqlTableWidget::enableLocalEdition(), and mdtSqlForm::insert().
void mdtAbstractSqlWidget::insertEnabledStateChanged (bool enabled) signal
Emitted when insert() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by mdtSqlTableWidget::enableLocalEdition().
void mdtAbstractSqlWidget::insertTriggered () signal
Emitted when insert() was called.
Referenced by insert().
QSqlTableModel * mdtAbstractSqlWidget::model ()
Get current model.
Can return a null pointer if model was not set.
Definition at line 72 of file mdtAbstractSqlWidget.cpp.
Referenced by mdtSqlForm::addChildTable(), mdtSqlTableWidget::currentSelection(), mdtSqlTableWidget::indexListOfSelectedRows(), mdtSqlTableWidget::indexListOfSelectedRowsByRowsList(), mdtSqlFormWidget::mapFormWidgets(), mdtSqlForm::model(), mdtSqlForm::select(), mdtSqlTableWidget::setColumnHidden(), mdtSqlTableWidget::setCurrentIndex(), setCurrentRecord(), mdtSqlTableWidget::setDefaultColumnToSelect(), mdtSqlTableWidget::setHeaderData(), mdtSqlForm::setMainTable(), mdtSqlForm::setMainTableFilter(), setModel(), and mdtSqlTableWidget::sort().
void mdtAbstractSqlWidget::modelSelected () signal
Emitted when select() or setQuery() was called on (parent) model.
Notes: QSqlTableModel does not provide such signal. Here, the rowsRemoved() and rowsInserted() signal are used. It's also possible that this signal is emitted two times when model is updated with select(), setQuery() or setFilter().
Referenced by mdtSqlFormWidget::mapFormWidgets(), mdtSqlTableWidget::mdtSqlTableWidget(), and setModel().
void mdtAbstractSqlWidget::operationSucceed () signal
Emitted when a operation succeed.
mdtSortFilterProxyModel * mdtAbstractSqlWidget::proxyModel () protected
Get internal proxy model.
Can be used by subclass to setup his view.
Note: returned proxy model is allways valid, but has no valid source model until model was set with setModel().
Definition at line 467 of file mdtAbstractSqlWidget.cpp.
Referenced by mdtSqlTableWidget::currentRow(), mdtSqlTableWidget::currentSelection(), and mdtSqlTableWidget::sort().
const mdtSortFilterProxyModel * mdtAbstractSqlWidget::proxyModel () const protected
Get internal proxy model.
Definition at line 472 of file mdtAbstractSqlWidget.cpp.
bool mdtAbstractSqlWidget::reEnterVisualizingState () slot
Re-enter in visualizing state.
Will call onStateVisualizingEntered(), witch will emit some signals (like submitEnabledStateChanged()). This method will fail if currentState is not really Visualizing.
This functionnality is used by mdtSqlWindow and mdtSqlDialog.
Definition at line 320 of file mdtAbstractSqlWidget.cpp.
References currentState(), and Visualizing.
Referenced by mdtSqlDialog::enableEdition(), mdtSqlWindow::enableEdition(), mdtSqlTableWidget::enableLocalEdition(), and mdtSqlWindow::enableNavigation().
void mdtAbstractSqlWidget::remove () slot
Remove a row from model.
Internally, removeTriggered() signal will be emitted.
Definition at line 285 of file mdtAbstractSqlWidget.cpp.
References removeTriggered().
void mdtAbstractSqlWidget::removeEnabledStateChanged (bool enabled) signal
Emitted when remove() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by mdtSqlTableWidget::enableLocalEdition().
void mdtAbstractSqlWidget::removeTriggered () signal
Emitted when remove() was called.
Referenced by remove().
bool mdtAbstractSqlWidget::restorePrimaryKeyDataToModel (const QSqlRecord & previousRecord) protected
Restore primary key data to (parent) model.
Parameters
previousRecord Record that contains data in witch primary key data will be token, and sotred again into model if they differ.
Precondition
(Parent) model must be set with setModel() before calling this method.
Definition at line 439 of file mdtAbstractSqlWidget.cpp.
References currentRow().
void mdtAbstractSqlWidget::revert () slot
Revert current record from model.
Depending on subclass choosen EditStrategy, this method has potentially no effect.
Internally, revertTriggered() signal will be emitted.
Definition at line 275 of file mdtAbstractSqlWidget.cpp.
References revertTriggered().
Referenced by mdtSqlTableWidget::enableLocalEdition().
void mdtAbstractSqlWidget::revertEnabledStateChanged (bool enabled) signal
Emitted when revert() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by mdtSqlTableWidget::enableLocalEdition().
void mdtAbstractSqlWidget::revertTriggered () signal
Emitted when revert() was called.
Referenced by revert().
int mdtAbstractSqlWidget::rowCount () const
Get row count.
Precondition
Model must be set with setModel() before using this method.
Definition at line 212 of file mdtAbstractSqlWidget.cpp.
Referenced by mdtSqlFormWidget::mapFormWidgets(), setCurrentRecord(), and mdtSqlTableWidget::sort().
bool mdtAbstractSqlWidget::setCurrentData (const QString & fieldName, const QVariant & data, bool submit = true)
Set (update) data of current row (record) for given field name.
Precondition
(Parent) model must be set with setModel() before using this method.
Definition at line 138 of file mdtAbstractSqlWidget.cpp.
References currentRow(), dataEdited(), displayDatabaseError(), and setCurrentIndex().
Referenced by mdtSqlForm::setCurrentData().
virtual void mdtAbstractSqlWidget::setCurrentIndex (int row) pure virtual slot
Set row as current record.
Subclass must implement this method. Errors and user interactions must be handled by subclass.
Referenced by setCurrentData(), and setCurrentRecord().
bool mdtAbstractSqlWidget::setCurrentRecord (const QString & fieldName, const QVariant & value) slot
Set the first record that matches given criteria as current record (index).
Parameters
fieldName Field that must contain searched value
value Value that must matche
Returns
True if matching record was found (in this case, setCurrentIndex() is called to update currentRow), false else.
Definition at line 290 of file mdtAbstractSqlWidget.cpp.
References model(), rowCount(), and setCurrentIndex().
Referenced by mdtSqlForm::setCurrentRecord().
void mdtAbstractSqlWidget::setModel (QSqlTableModel * model)
Set the table model.
Will call doSetModel() , then start the internall state machine.
Precondition
model must be a valid pointer
Internal state machine must not running.
Definition at line 52 of file mdtAbstractSqlWidget.cpp.
References doSetModel(), model(), modelSelected(), Visualizing, and mdtStateMachine::waitOnState().
Referenced by mdtSqlForm::addChildTable(), and mdtSqlForm::setMainTable().
void mdtAbstractSqlWidget::setUserFriendlyTableName (const QString & name)
Set the user friendly table name.
Definition at line 90 of file mdtAbstractSqlWidget.cpp.
Referenced by mdtSqlForm::addChildTable(), and mdtSqlForm::setMainTable().
void mdtAbstractSqlWidget::sort () virtual
Sort data.
See Also
addColumnToSortOrder()
Reimplemented in mdtSqlTableWidget.
Definition at line 266 of file mdtAbstractSqlWidget.cpp.
QList< mdtAbstractSqlWidget * > mdtAbstractSqlWidget::sqlWidgets ()
Get a list of all SQL widgets.
Returned list will contain the parent SQL widget and all child SQL widgets
Definition at line 124 of file mdtAbstractSqlWidget.cpp.
Referenced by mdtSqlForm::sqlWidget().
void mdtAbstractSqlWidget::stateEditingExited () signal
Emitted when Editing state was exited.
Referenced by mdtSqlFormWidget::mapFormWidgets().
void mdtAbstractSqlWidget::stateEditingNewRowExited () signal
Emitted when Editing state was exited.
Referenced by mdtSqlFormWidget::mapFormWidgets().
void mdtAbstractSqlWidget::stateVisualizingEntered () signal
Emitted when Visualizing state was entered.
void mdtAbstractSqlWidget::stateVisualizingExited () signal
Emitted when Visualizing state was exited.
void mdtAbstractSqlWidget::submit () slot
Submit current record to model.
Depending on subclass choosen EditStrategy, this method has potentially no effect.
Internally, submitTriggered() signal will be emitted.
Definition at line 270 of file mdtAbstractSqlWidget.cpp.
References submitTriggered().
Referenced by mdtSqlTableWidget::enableLocalEdition().
void mdtAbstractSqlWidget::submitEnabledStateChanged (bool enabled) signal
Emitted when submit() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by mdtSqlTableWidget::enableLocalEdition().
void mdtAbstractSqlWidget::submitTriggered () signal
Emitted when submit() was called.
Referenced by submit().
virtual void mdtAbstractSqlWidget::toFirst () pure virtual slot
Set first record as current record.
Subclass must implement this method. Errors and user interactions must be handled by subclass.
void mdtAbstractSqlWidget::toFirstEnabledStateChanged (bool enabled) signal
Emitted when toFirst() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
virtual void mdtAbstractSqlWidget::toLast () pure virtual slot
Set last record as current record.
Subclass must implement this method. Errors and user interactions must be handled by subclass.
void mdtAbstractSqlWidget::toLastEnabledStateChanged (bool enabled) signal
Emitted when toLast() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
virtual void mdtAbstractSqlWidget::toNext () pure virtual slot
Set next record as current record.
Subclass must implement this method. Errors and user interactions must be handled by subclass.
void mdtAbstractSqlWidget::toNextEnabledStateChanged (bool enabled) signal
Emitted when toNext() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
virtual void mdtAbstractSqlWidget::toPrevious () pure virtual slot
Set previous record as current record.
Subclass must implement this method. Errors and user interactions must be handled by subclass.
void mdtAbstractSqlWidget::toPreviousEnabledStateChanged (bool enabled) signal
Emitted when toPrevious() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
QString mdtAbstractSqlWidget::userFriendlyTableName () const
Get the user friendly table name.
If the user friendly table name was not set, the database table name is returned. If model was not set, a empty string is returned.
Definition at line 95 of file mdtAbstractSqlWidget.cpp.
Referenced by mdtSqlForm::addChildTable(), allDataAreSaved(), displayDatabaseError(), and mdtSqlForm::select().
void mdtAbstractSqlWidget::warnUserAboutUnsavedRow (const QString & tableName) protected
Show a message box to the user to warn him that it should save/revert data.
Definition at line 428 of file mdtAbstractSqlWidget.cpp.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtAbstractSqlWidget.h
src/mdtutilsgui/mdtAbstractSqlWidget.cpp