Multi diag tools: mdtMultiIoDevice Class Reference
mdtMultiIoDevice Class Reference
Base class for a device that contains multiple I/Os.
#include <mdtMultiIoDevice.h>
Public Slots
void setAnalogOutputValue (mdtAnalogIo *analogOutput)
Set value on a analog output on physical device.
void setDigitalOutputValue (mdtDigitalIo *digitalOutput)
Set value on a digital output on physical device.
Public Slots inherited from mdtDevice
void runQueries ()
Queries to send periodically.
Public Member Functions
mdtMultiIoDevice (QObject *parent=0)
Construct a multi I/O device object.
virtual ~mdtMultiIoDevice ()
Destructor.
virtual mdtPortManager * portManager ()
Get internal port manager instance.
void addInput (mdtAnalogIo *analogInput)
Add a analog input.
void addInputs (const QList< mdtAnalogIo * > &analogInputs)
Add a list of analog inputs.
void addOutput (mdtAnalogIo *analogOutput)
Add a analog output.
void addOutputs (const QList< mdtAnalogIo * > &analogOutputs)
Add a list of analog outputs.
void addInput (mdtDigitalIo *digitalInput)
Add a digital input.
void addInputs (const QList< mdtDigitalIo * > &digitalInputs)
Add a list of digital inputs.
void addOutput (mdtDigitalIo *digitalOutput)
Add a digital output.
void addOutputs (const QList< mdtDigitalIo * > &digitalOutputs)
Add a list of digital outputs.
void deleteIos ()
Delete all I/O in container.
std::shared_ptr< mdtDeviceIos > ios ()
Access internal I/Os container.
mdtValue getAnalogInputValue (mdtAnalogIo *analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (int address, bool queryDevice, bool waitOnReply=true)
Get analog input value.
mdtValue getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply=true)
Get analog input value.
mdtValue getAnalogInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply=true)
bool getAnalogInputs (bool waitOnReply=true)
Read all analog inputs on physical device and update (G)UI representation.
mdtValue getAnalogOutputValue (mdtAnalogIo *analogOutput, bool queryDevice, bool waitOnReply=true)
Get analog output value.
mdtValue getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply=true)
Get analog output value.
mdtValue getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply=true)
Get analog output value.
mdtValue getAnalogOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply=true)
bool getAnalogOutputs (bool waitOnReply=true)
Read all analog outputs on physical device and update (G)UI representation.
bool setAnalogOutputValue (mdtAnalogIo *analogOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set analog output value.
bool setAnalogOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set analog output value.
bool setAnalogOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set analog output value.
bool setAnalogOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
bool setAnalogOutputs (bool waitOnReply=true)
Write all analog outputs on physical device and update (G)UI representation.
mdtValue getDigitalInputValue (mdtDigitalIo *digitalInput, bool queryDevice, bool waitOnReply=true)
Get digital input value.
mdtValue getDigitalInputValue (int address, bool queryDevice, bool waitOnReply=true)
Get digital input value.
mdtValue getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply=true)
Get digital input value.
mdtValue getDigitalInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply=true)
bool getDigitalInputs (bool waitOnReply=true)
Read all digital inputs on physical device and update (G)UI representation.
mdtValue getDigitalOutputValue (mdtDigitalIo *digitalOutput, bool queryDevice, bool waitOnReply=true)
Get digital output value.
mdtValue getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply=true)
Get digital output value.
mdtValue getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply=true)
Get digital output value.
mdtValue getDigitalOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply=true)
bool getDigitalOutputs (bool waitOnReply=true)
Read all digital outputs on physical device and update (G)UI representation.
bool setDigitalOutputValue (mdtDigitalIo *digitalOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set a digital output value.
bool setDigitalOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set digital output value.
bool setDigitalOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set digital output value.
bool setDigitalOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set digital output value.
bool setDigitalOutputsValue (const mdtValue &value, bool sendToDevice, bool waitOnReply=true)
Set a value and validity for all digital outputs.
bool setDigitalOutputs (bool waitOnReply=true)
Write all digital outputs to physical device and update (G)UI representation.
Public Member Functions inherited from mdtDevice
mdtDevice (QObject *parent=0)
Construct a device object.
virtual ~mdtDevice ()
Destructor.
void setDeviceAddress (const mdtDeviceAddress &address, const QString &alias=QString())
Set device address.
mdtDeviceAddress deviceAddress () const
Get device address.
QString alias () const
Get device alias.
virtual bool connectToDevice ()
Connect to physical device.
void disconnectFromDevice ()
Disconnect from device.
void setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
virtual bool isReady ()
Check if device is ready.
void start (int queryInterval)
Start periodic device querying.
void stop ()
Stop periodic device querying.
void wait (int t)
Wait some time without breaking main event loop.
mdtError lastError () const
Get last error.
State_t currentState () const
Get current state.
Protected Member Functions
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
bool waitTransactionDone (int id)
Wait until a transaction is done without break the GUI's event loop.
virtual int readAnalogInput (mdtPortTransaction *transaction)
Read one analog input on physical device.
virtual int readAnalogInputs (mdtPortTransaction *transaction)
Read all analog inputs on physical device.
virtual int readAnalogOutput (mdtPortTransaction *transaction)
Read one analog output on physical device.
virtual int readAnalogOutputs (mdtPortTransaction *transaction)
Read all analog outputs on physical device.
virtual int writeAnalogOutput (int value, mdtPortTransaction *transaction)
Write value on a analog output to physical device.
virtual int writeAnalogOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all analog outputs to physical device.
virtual int readDigitalInput (mdtPortTransaction *transaction)
Read one digital input on physical device.
virtual int readDigitalInputs (mdtPortTransaction *transaction)
Read all digital inputs on physical device.
virtual int readDigitalOutput (mdtPortTransaction *transaction)
Read one digital output on physical device.
virtual int readDigitalOutputs (mdtPortTransaction *transaction)
Read all digital outputs on physical device.
virtual int writeDigitalOutput (bool state, mdtPortTransaction *transaction)
Write state on a digital output to physical device.
virtual int writeDigitalOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all digital outputs to physical device.
void stateChangedEvent (State_t newState)
Called when current state has changed.
Protected Member Functions inherited from mdtDevice
QString deviceIdString () const
Get device identification string.
virtual bool queriesSequence ()
Sequence of queries to send periodically.
void setCurrentState (State_t state)
Set current state.
virtual void disconnectFromDeviceEvent ()
Called by disconnectFromDevice()
virtual void deviceAddressChangedEvent (const mdtDeviceAddress &address)
Called by setDeviceAddress()
Additional Inherited Members
Public Types inherited from mdtDevice
enum State_t { State_t::Disconnected, State_t::Connecting, State_t::Ready, State_t::Error }
State of device.
Signals inherited from mdtDevice
void stateChanged (State_t state)
Emitted when state has changed.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
Protected Attributes inherited from mdtDevice
mdtError pvLastError
Last error object.
Detailed Description
Base class for a device that contains multiple I/Os.
Notes about I/O container: In first version of mdtDevice, I/O container (mdtDeviceIos object) was handled by caller. Experience showed that this was a bad solution. Now, the container is created, and destroyed, by mdtDevice itself. To deal with I/O container, some methods are available:
addInput(mdtAnalogIo *) : add a analog input.
addInputs(QList<mdtAnalogIo*> &) : add a list of analog inputs.
addOutput(mdtAnalogIo *) : add a analog output.
addOutputs(QList<mdtAnalogIo*> &) : add a list of analog outputs.
addInput(mdtDigitalIo *) : add a digital input.
addInputs(QList<mdtDigitalIo*> &) : add a list of digital inputs.
addOutput(mdtDigitalIo *) : add a digital output.
addOutputs(QList<mdtDigitalIo*> &) : add a list of digital outputs.
ios() : access I/O container.
deleteIos() : delete all I/O in container.
Definition at line 51 of file mdtMultiIoDevice.h.
Constructor & Destructor Documentation
mdtMultiIoDevice::mdtMultiIoDevice (QObject * parent = 0)
Construct a multi I/O device object.
Definition at line 26 of file mdtMultiIoDevice.cpp.
mdtMultiIoDevice::~mdtMultiIoDevice () virtual
Destructor.
Definition at line 33 of file mdtMultiIoDevice.cpp.
Member Function Documentation
void mdtMultiIoDevice::addInput (mdtAnalogIo * analogInput)
Add a analog input.
Definition at line 37 of file mdtMultiIoDevice.cpp.
void mdtMultiIoDevice::addInput (mdtDigitalIo * digitalInput)
Add a digital input.
Definition at line 74 of file mdtMultiIoDevice.cpp.
void mdtMultiIoDevice::addInputs (const QList< mdtAnalogIo * > & analogInputs)
Add a list of analog inputs.
Definition at line 45 of file mdtMultiIoDevice.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
void mdtMultiIoDevice::addInputs (const QList< mdtDigitalIo * > & digitalInputs)
Add a list of digital inputs.
Definition at line 82 of file mdtMultiIoDevice.cpp.
void mdtMultiIoDevice::addOutput (mdtAnalogIo * analogOutput)
Add a analog output.
Definition at line 52 of file mdtMultiIoDevice.cpp.
References setAnalogOutputValue().
void mdtMultiIoDevice::addOutput (mdtDigitalIo * digitalOutput)
Add a digital output.
Definition at line 89 of file mdtMultiIoDevice.cpp.
References setDigitalOutputValue().
void mdtMultiIoDevice::addOutputs (const QList< mdtAnalogIo * > & analogOutputs)
Add a list of analog outputs.
Definition at line 61 of file mdtMultiIoDevice.cpp.
References setAnalogOutputValue().
Referenced by mdtDeviceModbusWago::detectIos().
void mdtMultiIoDevice::addOutputs (const QList< mdtDigitalIo * > & digitalOutputs)
Add a list of digital outputs.
Definition at line 98 of file mdtMultiIoDevice.cpp.
References setDigitalOutputValue().
void mdtMultiIoDevice::deleteIos ()
Delete all I/O in container.
All I/O's will be deleted, but I/O container itself will remain valid.
Definition at line 111 of file mdtMultiIoDevice.cpp.
References setAnalogOutputValue(), and setDigitalOutputValue().
Referenced by mdtDeviceModbusWago::detectIos().
bool mdtMultiIoDevice::getAnalogInputs (bool waitOnReply = true)
Read all analog inputs on physical device and update (G)UI representation.
Will call readAnalogInputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogInputs() for details).
Once results are available or error occured, the internal analog inputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Definition at line 238 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getNewTransaction(), mdtDeviceIosSegment::ioCount(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, readAnalogInputs(), mdtPortTransaction::setAddress(), mdtError::setError(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
Referenced by mdtDeviceModbus::queriesSequence().
mdtMultiIoDevice::getAnalogInputValue (mdtAnalogIo * analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
Get device or internal analog value. Internal value is updated if queryDevice is set.
Parameters
analogInput Pointer to a analog input object.
queryDevice If true, value is readen from device by calling readAnalogInput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogInput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Returns
A mdtValue with valueDouble as real value and valueInt as device specific encoded fromat (if available). See mdtValue documentation for details about validity and other flags.
Precondition
analogInput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtAnalogIo for details).
Definition at line 132 of file mdtMultiIoDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readAnalogInput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtAnalogIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getAnalogInputValue(), and getAnalogInputValueAt().
mdtValue mdtMultiIoDevice::getAnalogInputValue (int address, bool queryDevice, bool waitOnReply = true)
Get analog input value.
Parameters
address Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a input number, etc...
See Also
getAnalogInputValue(mdtAnalogIo*, bool, bool)
Definition at line 174 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getAnalogInputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getAnalogInputValue (const QString & labelShort, bool queryDevice, bool waitOnReply = true)
Definition at line 219 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getAnalogInputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply = true)
Get analog input value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getAnalogInputValue(mdtAnalogIo*, bool, bool)
Definition at line 193 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getAnalogInputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
bool mdtMultiIoDevice::getAnalogOutputs (bool waitOnReply = true)
Read all analog outputs on physical device and update (G)UI representation.
Will call readAnalogOutputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogOutputs() for details).
Once results are available or error occured, the internal analog outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Definition at line 392 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getNewTransaction(), mdtDeviceIosSegment::ioCount(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, readAnalogOutputs(), mdtPortTransaction::setAddress(), mdtError::setError(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
mdtMultiIoDevice::getAnalogOutputValue (mdtAnalogIo * analogOutput, bool queryDevice, bool waitOnReply = true)
Get analog output value.
Get device or internal analog value. Internal value is updated if queryDevice is set.
Parameters
analogOutput Pointer to a analog output object.
queryDevice If true, value is readen from device by calling readAnalogOutput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Returns
A mdtValue with valueDouble as real value and valueInt as device specific encoded fromat (if available). See mdtValue documentation for details about validity and other flags.
Precondition
analogOutput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtAnalogIo for details).
Definition at line 286 of file mdtMultiIoDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readAnalogOutput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtAnalogIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getAnalogOutputValue(), and getAnalogOutputValueAt().
mdtValue mdtMultiIoDevice::getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply = true)
Get analog output value.
Parameters
addressRead Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
getAnalogOutputValue(mdtAnalogIo*, bool, bool)
Definition at line 328 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getAnalogOutputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getAnalogOutputValue (const QString & labelShort, bool queryDevice, bool waitOnReply = true)
Definition at line 373 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getAnalogOutputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply = true)
Get analog output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getAnalogOutputValue(mdtAnalogIo*, bool, bool)
Definition at line 347 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getAnalogOutputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
bool mdtMultiIoDevice::getDigitalInputs (bool waitOnReply = true)
Read all digital inputs on physical device and update (G)UI representation.
Will call readDigitalInputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalInputs() for details).
Once results are available, the internal digital inputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Definition at line 700 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getNewTransaction(), mdtDeviceIosSegment::ioCount(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, readDigitalInputs(), mdtPortTransaction::setAddress(), mdtError::setError(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
Referenced by mdtDeviceModbus::queriesSequence().
mdtMultiIoDevice::getDigitalInputValue (mdtDigitalIo * digitalInput, bool queryDevice, bool waitOnReply = true)
Get digital input value.
Get device or internal digital value. Internal value is updated if queryDevice is set.
Parameters
digitalInput Pointer to a digital input.
queryDevice If true, value is readen from device by calling readDigitalInput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalInput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Returns
A mdtValue with valueBool. See mdtValue documentation for details about validity and other flags.
Precondition
digitalInput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtDigitalIo for details).
Definition at line 594 of file mdtMultiIoDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readDigitalInput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtDigitalIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getDigitalInputValue(), and getDigitalInputValueAt().
mdtValue mdtMultiIoDevice::getDigitalInputValue (int address, bool queryDevice, bool waitOnReply = true)
Get digital input value.
Parameters
address Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a input number, etc...
See Also
getDigitalInputValue(mdtDigitalIo*, bool, bool)
Definition at line 636 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getDigitalInputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getDigitalInputValue (const QString & labelShort, bool queryDevice, bool waitOnReply = true)
Definition at line 681 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getDigitalInputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply = true)
Get digital input value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getDigitalInputValue(mdtDigitalIo*, bool, bool)
Definition at line 655 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getDigitalInputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
bool mdtMultiIoDevice::getDigitalOutputs (bool waitOnReply = true)
Read all digital outputs on physical device and update (G)UI representation.
Will call readDigitalOutputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalOutputs() for details).
Once results are available, the internal digital outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Definition at line 852 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getNewTransaction(), mdtDeviceIosSegment::ioCount(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, readDigitalOutputs(), mdtPortTransaction::setAddress(), mdtError::setError(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
mdtMultiIoDevice::getDigitalOutputValue (mdtDigitalIo * digitalOutput, bool queryDevice, bool waitOnReply = true)
Get digital output value.
Parameters
digitalOutput Pointer to a digital output.
queryDevice If true, value is readen from device by calling readDigitalOutput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Returns
A mdtValue with valueBool. See mdtValue documentation for details about validity and other flags.
Precondition
digitalOutput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtDigitalIo for details).
Definition at line 749 of file mdtMultiIoDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readDigitalOutput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtDigitalIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getDigitalOutputValue(), and getDigitalOutputValueAt().
mdtValue mdtMultiIoDevice::getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply = true)
Get digital output value.
Parameters
addressRead Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
getDigitalOutputValue(mdtDigitalIo*, bool, bool)
Definition at line 791 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getDigitalOutputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getDigitalOutputValue (const QString & labelShort, bool queryDevice, bool waitOnReply = true)
Definition at line 834 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getDigitalOutputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtValue mdtMultiIoDevice::getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply = true)
Get digital output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getDigitalOutputValue(mdtDigitalIo*, bool, bool)
Definition at line 809 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getDigitalOutputValue(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, and mdtError::setError().
mdtPortTransaction * mdtMultiIoDevice::getNewTransaction () protected
Get a new transaction.
See Also
mdtPortManager::getNewTransaction()
Precondition
portManager must be set before calling this method
Definition at line 1097 of file mdtMultiIoDevice.cpp.
References mdtPortManager::getNewTransaction(), and portManager().
Referenced by getAnalogInputs(), getAnalogInputValue(), getAnalogOutputs(), getAnalogOutputValue(), getDigitalInputs(), getDigitalInputValue(), getDigitalOutputs(), getDigitalOutputValue(), setAnalogOutputs(), setAnalogOutputValue(), setDigitalOutputs(), and setDigitalOutputValue().
std::shared_ptr<mdtDeviceIos> mdtMultiIoDevice::ios () inline
Access internal I/Os container.
Definition at line 117 of file mdtMultiIoDevice.h.
Referenced by mdtDeviceModbusWago::detectIos(), mdtDeviceModbus::readAnalogInput(), mdtDeviceModbus::readAnalogInputs(), mdtDeviceModbus::readAnalogOutput(), mdtDeviceModbus::readAnalogOutputs(), mdtDeviceModbus::readDigitalInput(), mdtDeviceModbus::readDigitalInputs(), mdtDeviceModbus::readDigitalOutput(), mdtDeviceModbus::readDigitalOutputs(), mdtDeviceModbus::writeAnalogOutput(), mdtDeviceModbus::writeAnalogOutputs(), mdtDeviceModbus::writeDigitalOutput(), and mdtDeviceModbus::writeDigitalOutputs().
virtual mdtPortManager* mdtMultiIoDevice::portManager () inline virtual
Get internal port manager instance.
Note that port manager is set by subclass, and that a Null pointer can be returned. (See subclass documentation for details)
Reimplemented in mdtDeviceModbus.
Definition at line 71 of file mdtMultiIoDevice.h.
Referenced by getNewTransaction(), restoreTransaction(), and waitTransactionDone().
int mdtMultiIoDevice::readAnalogInput (mdtPortTransaction * transaction) protected virtual
Read one analog input on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogInputValue() .
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details).
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1132 of file mdtMultiIoDevice.cpp.
Referenced by getAnalogInputValue().
int mdtMultiIoDevice::readAnalogInputs (mdtPortTransaction * transaction) protected virtual
Read all analog inputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogInputs() .
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1137 of file mdtMultiIoDevice.cpp.
Referenced by getAnalogInputs().
int mdtMultiIoDevice::readAnalogOutput (mdtPortTransaction * transaction) protected virtual
Read one analog output on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogOutputValue().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1142 of file mdtMultiIoDevice.cpp.
Referenced by getAnalogOutputValue().
int mdtMultiIoDevice::readAnalogOutputs (mdtPortTransaction * transaction) protected virtual
Read all analog outputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address (for read access) to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1147 of file mdtMultiIoDevice.cpp.
Referenced by getAnalogOutputs().
int mdtMultiIoDevice::readDigitalInput (mdtPortTransaction * transaction) protected virtual
Read one digital input on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital inputs, this method should be implemented.
This method is called from getDigitalInputValue().
Parameters
transaction Contains:
digitalIo object
QueryReplyMode flag
address
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1162 of file mdtMultiIoDevice.cpp.
Referenced by getDigitalInputValue().
int mdtMultiIoDevice::readDigitalInputs (mdtPortTransaction * transaction) protected virtual
Read all digital inputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital inputs, this method should be implemented.
This method is called from getDigitalInputs().
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1167 of file mdtMultiIoDevice.cpp.
Referenced by getDigitalInputs().
int mdtMultiIoDevice::readDigitalOutput (mdtPortTransaction * transaction) protected virtual
Read one digital output on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from getDigitalOutputValue().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1172 of file mdtMultiIoDevice.cpp.
Referenced by getDigitalOutputValue().
int mdtMultiIoDevice::readDigitalOutputs (mdtPortTransaction * transaction) protected virtual
Read all digital outputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from getDigitalOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address (for read access) to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1177 of file mdtMultiIoDevice.cpp.
Referenced by getDigitalOutputs().
void mdtMultiIoDevice::restoreTransaction (mdtPortTransaction * transaction) protected
Restore a transaction into pool.
See Also
mdtPortManager::restoreTransaction()
Precondition
portManager must be set before calling this method
Definition at line 1104 of file mdtMultiIoDevice.cpp.
References portManager(), and mdtPortManager::restoreTransaction().
bool mdtMultiIoDevice::setAnalogOutputs (bool waitOnReply = true)
Write all analog outputs on physical device and update (G)UI representation.
To send the analog outputs values once, it's possible to set them without sending query. See mdtDeviceIos and mdtAnalogIo for details. Then, call this method to sent all analog outputs values to device.
writeAnalogOutputs() will be called, witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeAnalogOutputs() for details).
Once results are available or on error, the internal analog outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Definition at line 544 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getNewTransaction(), mdtDeviceIosSegment::ioCount(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, mdtPortTransaction::setAddress(), mdtError::setError(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressWrite(), waitTransactionDone(), and writeAnalogOutputs().
mdtMultiIoDevice::setAnalogOutputValue (mdtAnalogIo * analogOutput, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set analog output value.
Set device or internal analog value. Internal value is updated if queryDevice is set.
Parameters
analogOutput Pointer to a analog output object.
value Value to send/store.
sendToDevice If true, value is sent device by calling writeAnalogOutput(), else value is only cached. Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeAnalogOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Precondition
analogOutput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtAnalogIo for details).
Definition at line 440 of file mdtMultiIoDevice.cpp.
References mdtAbstractIo::addressWrite(), getNewTransaction(), mdtPortTransaction::setAddress(), mdtAbstractIo::setEnabled(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtAnalogIo::setValue(), mdtAbstractIo::value(), mdtValue::valueInt(), waitTransactionDone(), and writeAnalogOutput().
Referenced by addOutput(), addOutputs(), deleteIos(), setAnalogOutputValue(), and setAnalogOutputValueAt().
bool mdtMultiIoDevice::setAnalogOutputValue (int addressWrite, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set analog output value.
Parameters
addressWrite Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
setAnalogOutputValue(mdtAnalogIo*, const mdtValue&, bool, bool)
Definition at line 483 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, MDT_ERROR_SET_SRC, mdtDevice::pvLastError, setAnalogOutputValue(), and mdtError::setError().
bool mdtMultiIoDevice::setAnalogOutputValue (const QString & labelShort, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Definition at line 526 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, MDT_ERROR_SET_SRC, mdtDevice::pvLastError, setAnalogOutputValue(), and mdtError::setError().
void mdtMultiIoDevice::setAnalogOutputValue (mdtAnalogIo * analogOutput) slot
Set value on a analog output on physical device.
Checks device's state and send request if Ready.
This slot is used by mdtDeviceIos to notify that a value has changed.
See setAnalogOutputValue(mdtAnalogIo*, const mdtValue&, bool, bool) for details.
Definition at line 1075 of file mdtMultiIoDevice.cpp.
References mdtDevice::currentState(), mdtDevice::Ready, setAnalogOutputValue(), and mdtAbstractIo::value().
bool mdtMultiIoDevice::setAnalogOutputValueAt (int position, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set analog output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
setAnalogOutputValue(mdtAnalogIo*, const mdtValue&, bool, bool)
Definition at line 501 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, MDT_ERROR_SET_SRC, mdtDevice::pvLastError, setAnalogOutputValue(), and mdtError::setError().
bool mdtMultiIoDevice::setDigitalOutputs (bool waitOnReply = true)
Write all digital outputs to physical device and update (G)UI representation.
To send the digital outputs values once. It's possible to use setDigitalOutputValue() without sending the query to device, then using this method to commit all values once.
See mdtDeviceIos and mdtDigitalIo for details.
writeDigitalOutputs() will be called, witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeDigitalOutputs() for details).
Once results are available, the internal digital outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Returns
0 or a ID on success. If no I/O's are set, on timeout ar other error, a value < 0 is returned.
Definition at line 1025 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, getNewTransaction(), mdtDeviceIosSegment::ioCount(), MDT_ERROR_SET_SRC, mdtDevice::pvLastError, mdtPortTransaction::setAddress(), mdtError::setError(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressWrite(), waitTransactionDone(), and writeDigitalOutputs().
Referenced by setDigitalOutputsValue().
bool mdtMultiIoDevice::setDigitalOutputsValue (const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set a value and validity for all digital outputs.
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 1005 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, MDT_ERROR_SET_SRC, mdtDevice::pvLastError, setDigitalOutputs(), and mdtError::setError().
bool mdtMultiIoDevice::setDigitalOutputValue (mdtDigitalIo * digitalOutput, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set a digital output value.
Set device or internal digital value. Depending on subclass implementation, if queryDevice is set, output can be updated regarding device response.
Parameters
digitalOutput Pointer to a digital output object.
value Value to send/store.
sendToDevice If true, value is sent to device by calling writeDigitalOutput(), else value is only cached. Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeDigitalOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Deprecated:
waitOnReply must not be used anymore
Precondition
digitalOutput must be valid.
Definition at line 901 of file mdtMultiIoDevice.cpp.
References mdtAbstractIo::addressWrite(), getNewTransaction(), mdtPortTransaction::setAddress(), mdtAbstractIo::setEnabled(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtDigitalIo::setValue(), mdtValue::valueBool(), waitTransactionDone(), and writeDigitalOutput().
Referenced by addOutput(), addOutputs(), deleteIos(), setDigitalOutputValue(), and setDigitalOutputValueAt().
bool mdtMultiIoDevice::setDigitalOutputValue (int addressWrite, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set digital output value.
Parameters
addressWrite Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 944 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, MDT_ERROR_SET_SRC, mdtDevice::pvLastError, setDigitalOutputValue(), and mdtError::setError().
bool mdtMultiIoDevice::setDigitalOutputValue (const QString & labelShort, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set digital output value.
Parameters
labelShort Short label set in I/O (see mdtDigitalIo for details).
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 987 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, MDT_ERROR_SET_SRC, mdtDevice::pvLastError, setDigitalOutputValue(), and mdtError::setError().
void mdtMultiIoDevice::setDigitalOutputValue (mdtDigitalIo * digitalOutput) slot
Set value on a digital output on physical device.
Checks device's state and send request if Ready.
This slot is used by mdtDeviceIos to notify that a value has changed.
See setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool) for details.
Definition at line 1086 of file mdtMultiIoDevice.cpp.
References mdtDevice::currentState(), mdtDevice::Ready, setDigitalOutputValue(), and mdtAbstractIo::value().
bool mdtMultiIoDevice::setDigitalOutputValueAt (int position, const mdtValue & value, bool sendToDevice, bool waitOnReply = true)
Set digital output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 962 of file mdtMultiIoDevice.cpp.
References mdtError::commit(), mdtDevice::deviceIdString(), mdtError::Error, MDT_ERROR_SET_SRC, mdtDevice::pvLastError, setDigitalOutputValue(), and mdtError::setError().
void mdtMultiIoDevice::stateChangedEvent (mdtDevice::State_t newState) protected virtual
Called when current state has changed.
Reimplemented from mdtDevice.
Definition at line 1192 of file mdtMultiIoDevice.cpp.
References mdtDevice::Ready.
bool mdtMultiIoDevice::waitTransactionDone (int id) protected
Wait until a transaction is done without break the GUI's event loop.
Todo:
Adapt, comment
This is a helper method that provide a blocking wait. Internally, a couple of sleep and event processing is done, avoiding freezing the GUI.
Internally, mdtPortManager::waitTransactionDone() is called.
Parameters
id Id returned by query method
Returns
True on success, false on timeout. If id was not found in transactions list, a warning will be generated in mdtError system, and false will be returned.
Precondition
granularity must be > 0.
Definition at line 1112 of file mdtMultiIoDevice.cpp.
References portManager(), mdtPortManager::readenFrame(), and mdtPortManager::waitTransactionDone().
Referenced by getAnalogInputs(), getAnalogInputValue(), getAnalogOutputs(), getAnalogOutputValue(), getDigitalInputs(), getDigitalInputValue(), getDigitalOutputs(), getDigitalOutputValue(), setAnalogOutputs(), setAnalogOutputValue(), setDigitalOutputs(), and setDigitalOutputValue().
int mdtMultiIoDevice::writeAnalogOutput (int value, mdtPortTransaction * transaction) protected virtual
Write value on a analog output to physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog outputs, this method should be implemented.
This method is called from setAnalogOutputValue().
Parameters
value Value encoded regarding device format.
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1152 of file mdtMultiIoDevice.cpp.
Referenced by setAnalogOutputValue().
int mdtMultiIoDevice::writeAnalogOutputs (mdtPortTransaction * transaction, mdtDeviceIosSegment * segment) protected virtual
Write all analog outputs to physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog outputs, this method should be implemented.
This method is called from setAnalogOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to set
address : first I/O address (for write access) to considere
QueryReplyMode flag
segment Contains contiguous outputs to write.
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1157 of file mdtMultiIoDevice.cpp.
Referenced by setAnalogOutputs().
int mdtMultiIoDevice::writeDigitalOutput (bool state, mdtPortTransaction * transaction) protected virtual
Write state on a digital output to physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from setDigitalOutputState().
Parameters
state State (ON/OFF).
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1182 of file mdtMultiIoDevice.cpp.
Referenced by setDigitalOutputValue().
int mdtMultiIoDevice::writeDigitalOutputs (mdtPortTransaction * transaction, mdtDeviceIosSegment * segment) protected virtual
Write all digital outputs to physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from setDigitalOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to set
address : first I/O address (for write access) to considere
QueryReplyMode flag
segment Contains contiguous outputs to write.
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1187 of file mdtMultiIoDevice.cpp.
Referenced by setDigitalOutputs().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtMultiIoDevice.h
src/mdtdevice/mdtMultiIoDevice.cpp