Multi diag tools: mdtUiMessageHandler Class Reference
mdtUiMessageHandler Class Reference
Helper class for interaction with the user.
#include <mdtUiMessageHandler.h>
Public Types
enum Type_t { Information = 0, Question, Warning, Error }
Message type.
Public Member Functions
mdtUiMessageHandler (QWidget *parent=0)
Constructor.
void clear ()
Clear.
void setType (Type_t t)
Set type.
Type_t type () const
Get type.
void setText (const QString &txt)
Set text.
QString text () const
Get text.
void setInformativeText (const QString &txt)
Set informative text.
QString informativeText () const
Get informative text.
void setDetailedText (const QString &txt)
Set detailed text.
QString detailedText () const
Get detailed text.
void setError (const mdtError &err)
Set error.
virtual void displayToUser ()
Display message to the user.
virtual bool promptUser ()
Prompt the user to do a action.
virtual bool askUser ()
Ask a question to the user.
Detailed Description
Helper class for interaction with the user.
Definition at line 31 of file mdtUiMessageHandler.h.
Member Enumeration Documentation
enum mdtUiMessageHandler::Type_t
Message type.
Enumerator
Information
Message is a information
Question
Message is a question
Warning
Message is a warning
Error
Message is a error
Definition at line 37 of file mdtUiMessageHandler.h.
Constructor & Destructor Documentation
mdtUiMessageHandler::mdtUiMessageHandler (QWidget * parent = 0)
Constructor.
Parameters
parent Parent widget for dialog
Definition at line 24 of file mdtUiMessageHandler.cpp.
References Information.
Member Function Documentation
bool mdtUiMessageHandler::askUser () virtual
Ask a question to the user.
Returns
True if user accepted the message box (typically if he clicked Ok, Yes, ..), false if he rejected it (typically if Cancel, No, ... was clicked).
Definition at line 130 of file mdtUiMessageHandler.cpp.
References Error, Information, Question, and Warning.
void mdtUiMessageHandler::clear ()
Clear.
Definition at line 30 of file mdtUiMessageHandler.cpp.
References Information.
Referenced by setText().
QString mdtUiMessageHandler::detailedText () const inline
Get detailed text.
Definition at line 86 of file mdtUiMessageHandler.h.
void mdtUiMessageHandler::displayToUser () virtual
Display message to the user.
Definition at line 63 of file mdtUiMessageHandler.cpp.
References Error, Information, Question, and Warning.
Referenced by mdtSqlTableWidget::refresh().
QString mdtUiMessageHandler::informativeText () const inline
Get informative text.
Definition at line 78 of file mdtUiMessageHandler.h.
bool mdtUiMessageHandler::promptUser () virtual
Prompt the user to do a action.
Returns
True if user accepted the message box (typically if he clicked Ok, Yes, ..), false if he rejected it (typically if Cancel, No, ... was clicked).
Definition at line 91 of file mdtUiMessageHandler.cpp.
References Error, Information, Question, and Warning.
void mdtUiMessageHandler::setDetailedText (const QString & txt) inline
Set detailed text.
Definition at line 82 of file mdtUiMessageHandler.h.
void mdtUiMessageHandler::setError (const mdtError & err)
Set error.
Will also set text, informativeText, detailedText and type.
Definition at line 44 of file mdtUiMessageHandler.cpp.
References Error, mdtError::Error, mdtError::Info, Information, mdtError::informativeText(), mdtError::level(), mdtError::NoError, mdtError::systemText(), mdtError::text(), Warning, and mdtError::Warning.
Referenced by mdtSqlTableWidget::refresh().
void mdtUiMessageHandler::setInformativeText (const QString & txt) inline
Set informative text.
Definition at line 74 of file mdtUiMessageHandler.h.
void mdtUiMessageHandler::setText (const QString & txt)
Set text.
Will also clear handler first
Definition at line 38 of file mdtUiMessageHandler.cpp.
References clear().
void mdtUiMessageHandler::setType (Type_t t) inline
Set type.
Definition at line 56 of file mdtUiMessageHandler.h.
QString mdtUiMessageHandler::text () const inline
Get text.
Definition at line 70 of file mdtUiMessageHandler.h.
Type_t mdtUiMessageHandler::type () const inline
Get type.
Definition at line 60 of file mdtUiMessageHandler.h.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtUiMessageHandler.h
src/mdtutilsgui/mdtUiMessageHandler.cpp