Multi diag tools: mdtPortTerm Class Reference
mdtPortTerm Class Reference
Mini port treminal.
#include <mdtPortTerm.h>
Public Slots
void appendReadenData (mdtPortTransaction *transaction)
Append incomming data to terminal.
void sendCmd ()
Send command to current port.
void on_pbSendCmdAbort_clicked ()
Abort command transmission.
void on_pbClearTerm_clicked ()
Clear terminal.
void retranslate ()
Retranslate.
Public Member Functions
mdtPortTerm (QWidget *parent=0)
~mdtPortTerm ()
void setAvailableTranslations (const QMap< QString, QString > &avaliableTranslations, const QString &currentTranslationKey)
Build the translations menu.
Additional Inherited Members
Public Attributes inherited from Ui_mdtPortTerm
QAction * action_Quit
QAction * action_Setup
QAction * action_French
QAction * action_German
QAction * action_SerialPort
QAction * action_UsbTmcPort
QWidget * centralwidget
QGridLayout * gridLayout
QHBoxLayout * horizontalLayout
QLabel * lbTerm
QPushButton * pbClearTerm
QSpacerItem * horizontalSpacer_2
QTextEdit * teTerm
QLabel * lbCmd
QLineEdit * leCmd
QPushButton * pbSendCmdAbort
QPushButton * pbSendCmd
QMenuBar * menubar
QMenu * menu_File
QMenu * menu_Port
QMenu * menu_Language
QStatusBar * statusbar
Detailed Description
Mini port treminal.
Definition at line 44 of file mdtPortTerm.h.
Constructor & Destructor Documentation
mdtPortTerm::mdtPortTerm (QWidget * parent = 0)
Definition at line 36 of file mdtPortTerm.cpp.
References Ui_mdtPortTerm::action_SerialPort, Ui_mdtPortTerm::action_Setup, Ui_mdtPortTerm::action_UsbTmcPort, Ui_mdtPortTerm::leCmd, Ui_mdtPortTerm::pbSendCmd, sendCmd(), and Ui_mdtPortTerm::setupUi().
mdtPortTerm::~mdtPortTerm ()
Definition at line 69 of file mdtPortTerm.cpp.
Member Function Documentation
void mdtPortTerm::appendReadenData (mdtPortTransaction * transaction) slot
Append incomming data to terminal.
Definition at line 97 of file mdtPortTerm.cpp.
References mdtPortTransaction::data(), and Ui_mdtPortTerm::teTerm.
void mdtPortTerm::on_pbClearTerm_clicked () slot
Clear terminal.
Definition at line 141 of file mdtPortTerm.cpp.
References Ui_mdtPortTerm::teTerm.
void mdtPortTerm::on_pbSendCmdAbort_clicked () slot
Abort command transmission.
Definition at line 133 of file mdtPortTerm.cpp.
References mdtPortManager::abort(), and Ui_mdtPortTerm::leCmd.
void mdtPortTerm::retranslate () slot
Retranslate.
This slot is called by mdtApplication when language has changed
Definition at line 146 of file mdtPortTerm.cpp.
References Ui_mdtPortTerm::retranslateUi().
void mdtPortTerm::sendCmd () slot
Send command to current port.
Definition at line 104 of file mdtPortTerm.cpp.
References Ui_mdtPortTerm::leCmd.
Referenced by mdtPortTerm().
void mdtPortTerm::setAvailableTranslations (const QMap< QString, QString > & avaliableTranslations, const QString & currentTranslationKey)
Build the translations menu.
Definition at line 74 of file mdtPortTerm.cpp.
References mdtApp, and Ui_mdtPortTerm::menu_Language.
The documentation for this class was generated from the following files:
src/mdttools/mdtPortTerm.h
src/mdttools/mdtPortTerm.cpp