Multi diag tools: mdtSqlApplicationWidgets< T > Class Template Reference
mdtSqlApplicationWidgets< T > Class Template Reference abstract
Container for SQL editors and views.
#include <mdtSqlApplicationWidgets.h>
Static Public Member Functions
static void setDatabase (QSqlDatabase db)
Set database to use.
static QSqlDatabase database ()
Get used database.
static bool closeOpenWidgets ()
Close all open widgets.
static void clear ()
Clear.
static T * instancePtr ()
Get pointer to instance.
Protected Member Functions
std::shared_ptr< mdtSqlWindow > setupEditorInSqlWindow (const std::shared_ptr< mdtSqlForm > &editor)
Setup given editor in mdtSqlWindow.
void showSqlWindow (const std::shared_ptr< mdtSqlForm > &form, bool enableNavigation, bool enableEdition)
Show open window that contains given sql form.
std::shared_ptr< mdtSqlWindow > getOpenSqlWindow (const std::shared_ptr< mdtSqlForm > &form)
Get open window for given sql form.
bool closeOpenSqlWindows ()
Close all open SQL windows.
virtual bool closeCustomWidgets ()
Close custom widgets.
virtual void clearAllWidgets ()=0
Destroy all created widgets.
void displayError (const mdtError &error)
Display a error to the user.
mdtSqlApplicationWidgets ()
Prevent multiple object instances.
Static Protected Member Functions
static T & instance ()
Get the (unique) instance.
Protected Attributes
QSqlDatabase pvDatabase
Detailed Description
template<typename T>
class mdtSqlApplicationWidgets< T >
Container for SQL editors and views.
Using this class helps to create editors and views. Most of time, only one instance of each editore or view is needed, but must be accessible from multiple places in application.
Definition at line 45 of file mdtSqlApplicationWidgets.h.
Constructor & Destructor Documentation
template<typename T> mdtSqlApplicationWidgets< T >::mdtSqlApplicationWidgets () inline protected
Prevent multiple object instances.
Definition at line 154 of file mdtSqlApplicationWidgets.h.
Member Function Documentation
template<typename T > void mdtSqlApplicationWidgets< T >::clear () static
Clear.
Will destroy all created widgets
Definition at line 178 of file mdtSqlApplicationWidgets.h.
template<typename T> virtual void mdtSqlApplicationWidgets< T >::clearAllWidgets () protected pure virtual
Destroy all created widgets.
Must be impplemented in subclass.
template<typename T> virtual bool mdtSqlApplicationWidgets< T >::closeCustomWidgets () inline protected virtual
Close custom widgets.
For windows created with a mdtSqlForm in a mdtSqlWindow, closeOpenSqlWindows() can be used. For real application, many other widgets can be created.
Subclass can reimplement this function to close such widgets, and use their specific way to check if it is OK to really close it now.
If one widget cannot be closed now, this function returns false.
Default implementation does nothing and allways return true.
Definition at line 136 of file mdtSqlApplicationWidgets.h.
template<typename T > bool mdtSqlApplicationWidgets< T >::closeOpenSqlWindows () protected
Close all open SQL windows.
All SQL windows (mdtSqlWindow objects) that was created with setupEditorInSqlWindow() are stored in a container. When calling this function, it is checked if internal form (a mdtSqlForm object) has all data saved.
If one window contains a form that has pending data, this function retunrs false.
Definition at line 227 of file mdtSqlApplicationWidgets.h.
References mdtSqlForm::allDataAreSaved().
template<typename T > bool mdtSqlApplicationWidgets< T >::closeOpenWidgets () static
Close all open widgets.
If one widget have unsaved data, it will not be closed and this function returns false.
Definition at line 169 of file mdtSqlApplicationWidgets.h.
template<typename T> static QSqlDatabase mdtSqlApplicationWidgets< T >::database () inline static
Get used database.
Definition at line 58 of file mdtSqlApplicationWidgets.h.
template<typename T > void mdtSqlApplicationWidgets< T >::displayError (const mdtError & error) protected
Display a error to the user.
Definition at line 247 of file mdtSqlApplicationWidgets.h.
References mdtError::levelIcon(), mdtError::systemText(), and mdtError::text().
template<typename T > std::shared_ptr< mdtSqlWindow > mdtSqlApplicationWidgets< T >::getOpenSqlWindow (const std::shared_ptr< mdtSqlForm > & form) protected
Get open window for given sql form.
Definition at line 212 of file mdtSqlApplicationWidgets.h.
template<typename T> static T& mdtSqlApplicationWidgets< T >::instance () inline static protected
Get the (unique) instance.
Definition at line 89 of file mdtSqlApplicationWidgets.h.
Referenced by mdtSqlApplicationWidgets< mdtClApplicationWidgets >::database(), mdtSqlApplicationWidgets< mdtClApplicationWidgets >::instancePtr(), and mdtSqlApplicationWidgets< mdtClApplicationWidgets >::setDatabase().
template<typename T> static T* mdtSqlApplicationWidgets< T >::instancePtr () inline static
Get pointer to instance.
Useful for signal/slot connections
Definition at line 80 of file mdtSqlApplicationWidgets.h.
template<typename T> static void mdtSqlApplicationWidgets< T >::setDatabase (QSqlDatabase db) inline static
Set database to use.
Definition at line 51 of file mdtSqlApplicationWidgets.h.
template<typename T > std::shared_ptr< mdtSqlWindow > mdtSqlApplicationWidgets< T >::setupEditorInSqlWindow (const std::shared_ptr< mdtSqlForm > & editor) protected
Setup given editor in mdtSqlWindow.
Returned pointer can be used, for example, to resize the editor.
Freshliy created window will be added to open editors list.
Precondition
editor must be a valid pointer.
Definition at line 185 of file mdtSqlApplicationWidgets.h.
template<typename T > void mdtSqlApplicationWidgets< T >::showSqlWindow (const std::shared_ptr< mdtSqlForm > & form, bool enableNavigation, bool enableEdition) protected
Show open window that contains given sql form.
Definition at line 199 of file mdtSqlApplicationWidgets.h.
Member Data Documentation
template<typename T> QSqlDatabase mdtSqlApplicationWidgets< T >::pvDatabase protected
Definition at line 156 of file mdtSqlApplicationWidgets.h.
Referenced by mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtTtBase::mdtTtBase(), and mdtTtBase::rollbackTransaction().
The documentation for this class was generated from the following file:
src/mdtdatabase/mdtSqlApplicationWidgets.h