Multi diag tools: mdtClArticleConnectionDialog Class Reference
mdtClArticleConnectionDialog Class Reference
Dialog for article connection edition.
#include <mdtClArticleConnectionDialog.h>
Public Member Functions
mdtClArticleConnectionDialog (QWidget *parent, const QSqlDatabase &db)
Constructor.
~mdtClArticleConnectionDialog ()
Destructor.
void setData (const mdtClArticleConnectionData &data)
Set connection data.
mdtClArticleConnectionData data () const
Get connection data.
Additional Inherited Members
Private Member Functions inherited from Ui_mdtClArticleConnectionDialog
void setupUi (QDialog *mdtClArticleConnectionDialog)
void retranslateUi (QDialog *mdtClArticleConnectionDialog)
Private Attributes inherited from Ui_mdtClArticleConnectionDialog
QFormLayout * formLayout
QLabel * lbArticleConnectorNameLabel
QHBoxLayout * horizontalLayout
QPushButton * pbSelectArticleConnector
QLabel * lbArticleConnectorName
QLabel * lbConnectionType
QHBoxLayout * horizontalLayout_2
QComboBox * cbConnectionType
QLabel * lbConnectionTypeText
QLabel * lbArticleContactName
QLineEdit * fld_ArticleContactName
QLabel * lbIoType
QLineEdit * fld_IoType
QLabel * lbFunctionEN
QLineEdit * fld_FunctionEN
QLabel * lbFunctionFR
QLineEdit * fld_FunctionFR
QLabel * lbFunctionDE
QLineEdit * fld_FunctionDE
QLabel * lbFunctionIT
QLineEdit * fld_FunctionIT
QDialogButtonBox * buttonBox
Detailed Description
Dialog for article connection edition.
Definition at line 36 of file mdtClArticleConnectionDialog.h.
Constructor & Destructor Documentation
mdtClArticleConnectionDialog::mdtClArticleConnectionDialog (QWidget * parent, const QSqlDatabase & db)
Constructor.
Definition at line 33 of file mdtClArticleConnectionDialog.cpp.
References Ui_mdtClArticleConnectionDialog::cbConnectionType, Ui_mdtClArticleConnectionDialog::pbSelectArticleConnector, and Ui_mdtClArticleConnectionDialog::setupUi().
mdtClArticleConnectionDialog::~mdtClArticleConnectionDialog ()
Destructor.
Definition at line 44 of file mdtClArticleConnectionDialog.cpp.
Member Function Documentation
mdtClArticleConnectionData mdtClArticleConnectionDialog::data () const
Get connection data.
Definition at line 64 of file mdtClArticleConnectionDialog.cpp.
Referenced by setData().
void mdtClArticleConnectionDialog::setData (const mdtClArticleConnectionData & data)
Set connection data.
Precondition
All fields from ArticleConnection_tbl must exists in data.
Definition at line 48 of file mdtClArticleConnectionDialog.cpp.
References mdtSqlRecord::contains(), and data().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClArticleConnectionDialog.h
src/mdttools/mdttesttool/mdtcablelist/mdtClArticleConnectionDialog.cpp