Multi diag tools: mdtFieldMapItem Class Reference
mdtFieldMapItem Class Reference
Provide informations for mdtFieldMap.
#include <mdtFieldMapItem.h>
Public Member Functions
mdtFieldMapItem ()
Create a item with default parameters.
~mdtFieldMapItem ()
Destructor.
void setDestinationFieldIndex (int value)
Set destination field index.
int destinationFieldIndex () const
Get destination field index.
void setDestinationField (const mdtFieldMapField &field)
Set destination field.
mdtFieldMapField destinationField () const
Get destination field.
void setDestinationFieldName (const QString &value)
Set destination field name.
QString destinationFieldName () const
Get destination field name.
void setDestinationFieldDisplayText (const QString &value)
Set destination field display text.
QString destinationFieldDisplayText () const
Get destination field display text.
void setSourceFieldIndex (int value)
Set source field index.
int sourceFieldIndex () const
Get source field index.
void setSourceField (const mdtFieldMapField &field)
Set source field.
mdtFieldMapField sourceField () const
Get source field.
void setSourceFieldName (const QString &value)
Set source field name.
QString sourceFieldName () const
Get source field name.
void setSourceFieldDisplayText (const QString &text)
Set source field display text.
QString sourceFieldDisplayText () const
Get source field display text.
void setSourceFieldDataStartOffset (int offset)
Set source data start offset.
int sourceFieldDataStartOffset () const
Get source data start offset.
void setSourceFieldDataEndOffset (int offset)
Set source data end offset.
int sourceFieldDataEndOffset () const
Get source data end offset.
void setDataType (QVariant::Type type)
Set data type.
QVariant::Type dataType () const
Get data type.
QVariant destinationData (const QStringList &sourceRow) const
Get destination data from source row.
QVariant destinationData (const QString &sourceData) const
Get destination data from source data.
Detailed Description
Provide informations for mdtFieldMap.
See Also
mdtFieldMap
Definition at line 33 of file mdtFieldMapItem.h.
Constructor & Destructor Documentation
mdtFieldMapItem::mdtFieldMapItem ()
Create a item with default parameters.
Default parameters are:
fieldIndex set to -1
sourceFieldIndex set to -1
Empty values/strings
sourceFieldDataStartOffset set to -1
sourceFieldDataEndOffset set to -1
dataType set to QVariant::Invalid
Definition at line 26 of file mdtFieldMapItem.cpp.
mdtFieldMapItem::~mdtFieldMapItem ()
Destructor.
Definition at line 32 of file mdtFieldMapItem.cpp.
Member Function Documentation
QVariant::Type mdtFieldMapItem::dataType () const
Get data type.
Definition at line 141 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::sqlField().
QVariant mdtFieldMapItem::destinationData (const QStringList & sourceRow) const
Get destination data from source row.
This method will extract data in sourceRow at sourceFieldIndex (if valid).
If a source field start and end offsets are set, only the part from start to end is returned.
Definition at line 146 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::index().
Referenced by mdtFieldMap::dataForDestinationFieldIndex(), and mdtFieldMap::destinationDataRow().
QVariant mdtFieldMapItem::destinationData (const QString & sourceData) const
Get destination data from source data.
If a source field start and end offsets are set, only the part from start to end is returned.
Definition at line 158 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::sqlField().
mdtFieldMapField mdtFieldMapItem::destinationField () const
Get destination field.
Definition at line 51 of file mdtFieldMapItem.cpp.
Referenced by mdtFieldMap::mappedDestinationFields(), and mdtFieldMap::updateDestinationFields().
QString mdtFieldMapItem::destinationFieldDisplayText () const
Get destination field display text.
Definition at line 71 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::displayText().
Referenced by mdtFieldMap::displayTextsByFieldNames().
int mdtFieldMapItem::destinationFieldIndex () const
Get destination field index.
Definition at line 41 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::index().
Referenced by mdtFieldMap::dataForDestinationFieldName(), mdtFieldMap::destinationDataRow(), mdtFieldMap::itemAtDestinationFieldIndex(), and mdtFieldMap::mappedDestinationFields().
QString mdtFieldMapItem::destinationFieldName () const
Get destination field name.
Definition at line 61 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::name().
Referenced by mdtFieldMap::displayTextsByFieldNames(), and mdtFieldMap::itemAtDestinationFieldName().
void mdtFieldMapItem::setDataType (QVariant::Type type)
Set data type.
Definition at line 136 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::sqlField().
Referenced by mdtDataTableManager::addFieldMapping(), mdtDataTableManager::importFromCsvFile(), and mdtFieldMapItemDialog::mdtFieldMapItemDialog().
void mdtFieldMapItem::setDestinationField (const mdtFieldMapField & field)
Set destination field.
Definition at line 46 of file mdtFieldMapItem.cpp.
Referenced by mdtDataTableManager::copyTable(), mdtFieldMap::generateMapping(), and mdtFieldMap::updateDestinationFields().
void mdtFieldMapItem::setDestinationFieldDisplayText (const QString & value)
Set destination field display text.
Definition at line 66 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::setDisplayText().
Referenced by mdtDataTableManager::addFieldMapping(), and mdtDataTableManager::importFromCsvFile().
void mdtFieldMapItem::setDestinationFieldIndex (int value)
Set destination field index.
Definition at line 36 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::setIndex().
Referenced by mdtDataTableManager::copyTable(), and mdtDataTableManager::importFromCsvFile().
void mdtFieldMapItem::setDestinationFieldName (const QString & value)
Set destination field name.
Definition at line 56 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::setName().
Referenced by mdtDataTableManager::addFieldMapping(), and mdtDataTableManager::importFromCsvFile().
void mdtFieldMapItem::setSourceField (const mdtFieldMapField & field)
Set source field.
Definition at line 86 of file mdtFieldMapItem.cpp.
Referenced by mdtDataTableManager::copyTable(), and mdtFieldMap::generateMapping().
void mdtFieldMapItem::setSourceFieldDataEndOffset (int offset)
Set source data end offset.
If offset is < 0, the entiere right part of start offset is considered.
Definition at line 126 of file mdtFieldMapItem.cpp.
Referenced by mdtDataTableManager::addFieldMapping().
void mdtFieldMapItem::setSourceFieldDataStartOffset (int offset)
Set source data start offset.
If offset is < 0, the entiere left part os end offset is considered.
Definition at line 116 of file mdtFieldMapItem.cpp.
Referenced by mdtDataTableManager::addFieldMapping().
void mdtFieldMapItem::setSourceFieldDisplayText (const QString & text)
Set source field display text.
Definition at line 106 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::setDisplayText().
void mdtFieldMapItem::setSourceFieldIndex (int value)
Set source field index.
Definition at line 76 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::setIndex().
Referenced by mdtDataTableManager::copyTable(), and mdtDataTableManager::importFromCsvFile().
void mdtFieldMapItem::setSourceFieldName (const QString & value)
Set source field name.
Definition at line 96 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::setName().
Referenced by mdtDataTableManager::addFieldMapping(), and mdtDataTableManager::importFromCsvFile().
mdtFieldMapField mdtFieldMapItem::sourceField () const
Get source field.
Definition at line 91 of file mdtFieldMapItem.cpp.
Referenced by mdtFieldMap::mappedSourceFields().
int mdtFieldMapItem::sourceFieldDataEndOffset () const
Get source data end offset.
Definition at line 131 of file mdtFieldMapItem.cpp.
Referenced by mdtFieldMap::dataForDestinationFieldIndex(), and mdtFieldMap::destinationDataRow().
int mdtFieldMapItem::sourceFieldDataStartOffset () const
Get source data start offset.
Definition at line 121 of file mdtFieldMapItem.cpp.
Referenced by mdtFieldMap::dataForDestinationFieldIndex(), and mdtFieldMap::destinationDataRow().
QString mdtFieldMapItem::sourceFieldDisplayText () const
Get source field display text.
Definition at line 111 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::displayText().
int mdtFieldMapItem::sourceFieldIndex () const
Get source field index.
Definition at line 81 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::index().
Referenced by mdtFieldMap::dataForDestinationFieldIndex(), mdtFieldMap::destinationDataRow(), mdtFieldMap::itemsAtSourceFieldIndex(), and mdtFieldMap::mappedSourceFields().
QString mdtFieldMapItem::sourceFieldName () const
Get source field name.
Definition at line 101 of file mdtFieldMapItem.cpp.
References mdtFieldMapField::name().
Referenced by mdtFieldMap::itemsAtSourceFieldName(), and mdtFieldMap::sourceFieldNameAtDestinationFieldIndex().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtFieldMapItem.h
src/mdtutilsgui/mdtFieldMapItem.cpp