Multi diag tools: mdtUicNumberWidget Class Reference
mdtUicNumberWidget Class Reference
UIC Number Widget.
#include <mdtUicNumberWidget.h>
Public Member Functions
mdtUicNumberWidget (QWidget *parent=0)
~mdtUicNumberWidget ()
void setUicNumber (mdtUicNumber *uicNumber)
Set the uicNumber object.
mdtUicNumber * uicNumber ()
Get uicNumber object.
void setUicDbsDir (const QString &dir)
Set the directory containing UIC databases CSV files.
Additional Inherited Members
Private Member Functions inherited from Ui_mdtUicNumberWidget
void setupUi (QWidget *mdtUicNumberWidget)
void retranslateUi (QWidget *mdtUicNumberWidget)
Private Attributes inherited from Ui_mdtUicNumberWidget
QGridLayout * gridLayout_2
QLabel * lbUicNumber
QLineEdit * leUicNumber
QPushButton * pbCheckUicNumber
QPushButton * pbDetails
QWidget * wDetails
QVBoxLayout * verticalLayout
QHBoxLayout * horizontalLayout_3
QLabel * lbUsageLabel
QLabel * lbUsage
QSpacerItem * horizontalSpacer_3
QHBoxLayout * horizontalLayout_2
QLabel * lbCountryLabel
QLabel * lbCountry
QSpacerItem * horizontalSpacer_2
QHBoxLayout * horizontalLayout
QLabel * lbTypeLabel
QLabel * lbType
QSpacerItem * horizontalSpacer
QHBoxLayout * horizontalLayout_4
QLabel * lbSpeedAndHeatLabel
QLabel * lbSpeedAndHeat
QSpacerItem * horizontalSpacer_4
Detailed Description
UIC Number Widget.
Definition at line 31 of file mdtUicNumberWidget.h.
Constructor & Destructor Documentation
mdtUicNumberWidget::mdtUicNumberWidget (QWidget * parent = 0)
Definition at line 27 of file mdtUicNumberWidget.cpp.
References Ui_mdtUicNumberWidget::leUicNumber, Ui_mdtUicNumberWidget::pbCheckUicNumber, Ui_mdtUicNumberWidget::pbDetails, Ui_mdtUicNumberWidget::setupUi(), and Ui_mdtUicNumberWidget::wDetails.
mdtUicNumberWidget::~mdtUicNumberWidget ()
Definition at line 46 of file mdtUicNumberWidget.cpp.
Member Function Documentation
void mdtUicNumberWidget::setUicDbsDir (const QString & dir)
Set the directory containing UIC databases CSV files.
Definition at line 64 of file mdtUicNumberWidget.cpp.
void mdtUicNumberWidget::setUicNumber (mdtUicNumber * uicNumber)
Set the uicNumber object.
Precondition
uicNumber must be a valid pointer
Definition at line 50 of file mdtUicNumberWidget.cpp.
References uicNumber().
mdtUicNumber * mdtUicNumberWidget::uicNumber ()
Get uicNumber object.
Precondition
Valid object muts be set before with setUicNumber()
Definition at line 57 of file mdtUicNumberWidget.cpp.
Referenced by setUicNumber().
The documentation for this class was generated from the following files:
src/mdtutils/mdtUicNumberWidget.h
src/mdtutils/mdtUicNumberWidget.cpp