Multi diag tools: mdtUsbEndpointDescriptor Class Reference
mdtUsbEndpointDescriptor Class Reference
USB endpoint descriptor.
#include <mdtUsbEndpointDescriptor.h>
Public Member Functions
mdtUsbEndpointDescriptor ()
Construct a empty endpoint descriptor.
mdtUsbEndpointDescriptor (libusb_endpoint_descriptor descriptor)
Constructor.
bool isEmpty () const
Check if descriptor is empty.
uint8_t address () const
~mdtUsbEndpointDescriptor();
uint8_t number () const
Get endpoint number.
bool isDirectionIN () const
Endpoint direction.
bool isDirectionOUT () const
Endpoint direction.
bool isTransfertTypeControl ()
Endpoint transfert type.
bool isTransfertTypeIsochronus ()
Endpoint transfert type.
bool isTransferTypeBulk () const
Endpoint transfert type.
bool isTransferTypeInterrupt () const
Endpoint transfert type.
bool isAsynchronous ()
Endpoint synchronization type.
bool isAdaptative ()
Endpoint synchronization type.
bool isSynchronous ()
Endpoint synchronization type.
bool isDataEndpoint ()
Endpoint usage type.
bool isFeedbackEndpoint ()
Endpoint usage type.
bool isImplicitFeedbackEndpoint ()
Endpoint usage type.
int maxPacketSize ()
Maximum packet size.
int transactionsCountPerMicroFrame ()
Transactions per microframe.
uint8_t bInterval ()
Interval for polling endpoint for data transfers.
std::vector< unsigned char > extra () const
Extra (unknown) descriptors.
Detailed Description
USB endpoint descriptor.
Definition at line 32 of file mdtUsbEndpointDescriptor.h.
Constructor & Destructor Documentation
mdtUsbEndpointDescriptor::mdtUsbEndpointDescriptor ()
Construct a empty endpoint descriptor.
mdtUsbEndpointDescriptor::mdtUsbEndpointDescriptor() { pvbEndpointAddress = 0; pvbmAttributes = 0; pvwMaxPacketSize = 0; pvbInterval = 0; }
Definition at line 36 of file mdtUsbEndpointDescriptor.cpp.
mdtUsbEndpointDescriptor::mdtUsbEndpointDescriptor (libusb_endpoint_descriptor descriptor)
Constructor.
Will copy all members of passed descriptor. This descriptor can be freed after construction was done.
Definition at line 45 of file mdtUsbEndpointDescriptor.cpp.
Member Function Documentation
uint8_t mdtUsbEndpointDescriptor::address () const inline
~mdtUsbEndpointDescriptor();
Ftech the endpoint descriptor's attributes
Precondition
descriptor must be a valid pointervoid fetchAttributes(libusb_endpoint_descriptor *descriptor);
Endpoint address (bEndpointAddress)
Definition at line 63 of file mdtUsbEndpointDescriptor.h.
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbtmcInterruptTransfer::setup(), mdtUsbtmcBulkTransfer::setupBulkInRequest(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
uint8_t mdtUsbEndpointDescriptor::bInterval ()
Interval for polling endpoint for data transfers.
Value is returned as read in bInterval field (in libusb strcture)
Definition at line 165 of file mdtUsbEndpointDescriptor.cpp.
std::vector<unsigned char> mdtUsbEndpointDescriptor::extra () const inline
Extra (unknown) descriptors.
Definition at line 156 of file mdtUsbEndpointDescriptor.h.
bool mdtUsbEndpointDescriptor::isAdaptative ()
Endpoint synchronization type.
Definition at line 123 of file mdtUsbEndpointDescriptor.cpp.
bool mdtUsbEndpointDescriptor::isAsynchronous ()
Endpoint synchronization type.
Definition at line 117 of file mdtUsbEndpointDescriptor.cpp.
bool mdtUsbEndpointDescriptor::isDataEndpoint ()
Endpoint usage type.
Definition at line 135 of file mdtUsbEndpointDescriptor.cpp.
Referenced by mdtUsbDeviceDescriptor::firstBulkInEndpoint(), mdtUsbDeviceDescriptor::firstBulkOutEndpoint(), mdtUsbDeviceDescriptor::firstInterruptInEndpoint(), and mdtUsbDeviceDescriptor::firstInterruptOutEndpoint().
bool mdtUsbEndpointDescriptor::isDirectionIN () const inline
Endpoint direction.
Definition at line 77 of file mdtUsbEndpointDescriptor.h.
Referenced by mdtUsbDeviceDescriptor::firstBulkInEndpoint(), mdtUsbDeviceDescriptor::firstInterruptInEndpoint(), and isDirectionOUT().
bool mdtUsbEndpointDescriptor::isDirectionOUT () const inline
Endpoint direction.
Definition at line 83 of file mdtUsbEndpointDescriptor.h.
References isDirectionIN().
Referenced by mdtUsbDeviceDescriptor::firstBulkOutEndpoint(), and mdtUsbDeviceDescriptor::firstInterruptOutEndpoint().
bool mdtUsbEndpointDescriptor::isEmpty () const inline
Check if descriptor is empty.
Definition at line 49 of file mdtUsbEndpointDescriptor.h.
Referenced by mdtUsbtmcTransferHandler::hasInterruptInEndpoint(), mdtUsbtmcBulkTransfer::mdtUsbtmcBulkTransfer(), and mdtUsbtmcInterruptTransfer::mdtUsbtmcInterruptTransfer().
bool mdtUsbEndpointDescriptor::isFeedbackEndpoint ()
Endpoint usage type.
Definition at line 141 of file mdtUsbEndpointDescriptor.cpp.
bool mdtUsbEndpointDescriptor::isImplicitFeedbackEndpoint ()
Endpoint usage type.
Definition at line 147 of file mdtUsbEndpointDescriptor.cpp.
bool mdtUsbEndpointDescriptor::isSynchronous ()
Endpoint synchronization type.
Definition at line 129 of file mdtUsbEndpointDescriptor.cpp.
bool mdtUsbEndpointDescriptor::isTransfertTypeControl ()
Endpoint transfert type.
mdtUsbEndpointDescriptor::~mdtUsbEndpointDescriptor() { } void mdtUsbEndpointDescriptor::fetchAttributes(libusb_endpoint_descriptor *descriptor) { Q_ASSERT(descriptor != 0);
Get attributes pvbEndpointAddress = descriptor->bEndpointAddress; pvbmAttributes = descriptor->bmAttributes; pvwMaxPacketSize = descriptor->wMaxPacketSize; pvbInterval = descriptor->bInterval; }
Definition at line 93 of file mdtUsbEndpointDescriptor.cpp.
bool mdtUsbEndpointDescriptor::isTransfertTypeIsochronus ()
Endpoint transfert type.
Definition at line 99 of file mdtUsbEndpointDescriptor.cpp.
bool mdtUsbEndpointDescriptor::isTransferTypeBulk () const inline
Endpoint transfert type.
Definition at line 97 of file mdtUsbEndpointDescriptor.h.
Referenced by mdtUsbDeviceDescriptor::firstBulkInEndpoint(), and mdtUsbDeviceDescriptor::firstBulkOutEndpoint().
bool mdtUsbEndpointDescriptor::isTransferTypeInterrupt () const inline
Endpoint transfert type.
Definition at line 103 of file mdtUsbEndpointDescriptor.h.
Referenced by mdtUsbDeviceDescriptor::firstInterruptInEndpoint(), and mdtUsbDeviceDescriptor::firstInterruptOutEndpoint().
int mdtUsbEndpointDescriptor::maxPacketSize ()
Maximum packet size.
Note: this is the decoded size, i.e. bits 10..0 extracted from wMaxPacketSize
Definition at line 153 of file mdtUsbEndpointDescriptor.cpp.
uint8_t mdtUsbEndpointDescriptor::number () const inline
Get endpoint number.
Returns bits 3..0 extracted from bEndpointAddress.
Definition at line 71 of file mdtUsbEndpointDescriptor.h.
Referenced by mdtUsbtmcTransferHandler::submitClearBulkInEndpointHalt(), and mdtUsbtmcTransferHandler::submitClearBulkOutEndpointHalt().
int mdtUsbEndpointDescriptor::transactionsCountPerMicroFrame ()
Transactions per microframe.
Note: this is the decoded value + 1, i.e. bits 12..11 extracted from wMaxPacketSize Bit 12..11 give additionnal value, and this method returns the extracted value + 1 (f.ex. if bit 12..11 give 00 as result, this method returns 1)
Definition at line 159 of file mdtUsbEndpointDescriptor.cpp.
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbEndpointDescriptor.h
src/mdtport/mdtUsbEndpointDescriptor.cpp