Multi diag tools: mdtParentChildTableItem Class Reference
mdtParentChildTableItem Class Reference
#include <mdtParentChildTableItem.h>
Public Member Functions
mdtParentChildTableItem (QAbstractItemModel *model, int modelRow, mdtParentChildTableItem *parent)
Table item constructor.
mdtParentChildTableItem ()
Table item constructor Use this constructor to create the root item of the model.
~mdtParentChildTableItem ()
void appendChild (mdtParentChildTableItem *child)
mdtParentChildTableItem * child (int row)
int childCount () const
mdtParentChildTableItem * parent ()
int columnCount () const
Columns count of the stored model.
QVariant data (int column, int role) const
Returns the data of the stored model at stored row The row is set by constructor.
int row () const
QAbstractItemModel * model ()
Detailed Description
Definition at line 10 of file mdtParentChildTableItem.h.
Constructor & Destructor Documentation
mdtParentChildTableItem::mdtParentChildTableItem (QAbstractItemModel * model, int modelRow, mdtParentChildTableItem * parent)
Table item constructor.
Parameters
parent Set the parent reference of this object
model The table model to reference (let it null when creating the root object)
modelRow Set the row from the model that must be referenced
Definition at line 8 of file mdtParentChildTableItem.cpp.
mdtParentChildTableItem::mdtParentChildTableItem ()
Table item constructor Use this constructor to create the root item of the model.
Definition at line 15 of file mdtParentChildTableItem.cpp.
mdtParentChildTableItem::~mdtParentChildTableItem ()
Definition at line 22 of file mdtParentChildTableItem.cpp.
Member Function Documentation
void mdtParentChildTableItem::appendChild (mdtParentChildTableItem * child)
Definition at line 28 of file mdtParentChildTableItem.cpp.
mdtParentChildTableItem * mdtParentChildTableItem::child (int row)
Definition at line 33 of file mdtParentChildTableItem.cpp.
Referenced by mdtParentChildTableModel::columnCount(), and mdtParentChildTableModel::index().
int mdtParentChildTableItem::childCount () const
Definition at line 38 of file mdtParentChildTableItem.cpp.
Referenced by mdtParentChildTableModel::rowCount().
int mdtParentChildTableItem::columnCount () const
Columns count of the stored model.
Returns
Columns count of the stored model
Definition at line 56 of file mdtParentChildTableItem.cpp.
Referenced by mdtParentChildTableModel::columnCount().
QVariant mdtParentChildTableItem::data (int column, int role) const
Returns the data of the stored model at stored row The row is set by constructor.
See Also
mdtParentChildTableItem()
Parameters
column Column in witch to get the data
role Role of the data (Display, Edit, ...)
Definition at line 62 of file mdtParentChildTableItem.cpp.
Referenced by mdtParentChildTableModel::data().
QAbstractItemModel * mdtParentChildTableItem::model ()
Definition at line 51 of file mdtParentChildTableItem.cpp.
mdtParentChildTableItem * mdtParentChildTableItem::parent ()
Definition at line 70 of file mdtParentChildTableItem.cpp.
Referenced by mdtParentChildTableModel::parent().
int mdtParentChildTableItem::row () const
Definition at line 43 of file mdtParentChildTableItem.cpp.
Referenced by mdtParentChildTableModel::columnCount(), and mdtParentChildTableModel::parent().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtParentChildTableItem.h
src/mdtutilsgui/mdtParentChildTableItem.cpp