Multi diag tools: mdtAbstractIo Class Reference
mdtAbstractIo Class Reference
Base class for I/O handling on (G)UI.
#include <mdtAbstractIo.h>
Public Slots
virtual void setValue (const mdtValue &value, bool emitValueChanged=false)
Set the value to update display.
Signals
void addressChangedForUi (int addressRead, int addressWrite)
void labelShortChangedForUi (const QString &text)
void labelChangedForUi (const QString &text)
void detailsChangedForUi (const QString &text)
void enabledStateChangedForUi (bool enabled)
void valueChanged (const mdtValue &value)
This signal is emitted whenever the value is changed.
void valueChanged (mdtAnalogIo *io)
This signal is emitted whenever the value is changed.
void valueChanged (mdtDigitalIo *io)
void valueChangedForUi (const mdtValue &value)
This signal is emitted whenever the value is changed.
Public Member Functions
mdtAbstractIo (QObject *parent=0)
Construct a empty I/O.
virtual ~mdtAbstractIo ()
void setAddress (int address)
Set the I/O address.
int address () const
Get the I/O address.
void setAddressRead (int address)
Set the I/O address for read.
int addressRead () const
Get the I/O address for read.
void setAddressWrite (int address)
Set the I/O address for write.
int addressWrite () const
Get the I/O address for write.
void setLabelShort (const QString &text)
Set the short I/O label.
QString labelShort () const
Get the short I/O label.
void setLabel (const QString &text)
Set the complete I/O label.
QString label () const
Get the complete I/O label.
void setDetails (const QString &text)
Set details about the I/O.
QString details () const
Get details about the I/O.
bool hasValidData () const
Returns true if a valid value or state was set.
void setEnabled (bool enabled)
Set enabled state.
const mdtValue & value () const
Get current value.
Protected Attributes
mdtValue pvValue
bool pvNotifyUi
Detailed Description
Base class for I/O handling on (G)UI.
Can be used with mdtAbstractIoWidget and subclasses. This class offers the functionnal part of I/O representation on a UI, or GUI when used with mdtAbstractIoWidget.
Definition at line 37 of file mdtAbstractIo.h.
Constructor & Destructor Documentation
mdtAbstractIo::mdtAbstractIo (QObject * parent = 0)
Construct a empty I/O.
A empty I/O has address 0 and no valid data.
Definition at line 23 of file mdtAbstractIo.cpp.
References pvNotifyUi.
mdtAbstractIo::~mdtAbstractIo () virtual
Definition at line 31 of file mdtAbstractIo.cpp.
Member Function Documentation
int mdtAbstractIo::address () const
Get the I/O address.
Note: if addressRead and addressWrite are not the same, addressRead is returned.
Definition at line 42 of file mdtAbstractIo.cpp.
Referenced by mdtDeviceIos::addDigitalInput(), setAddress(), setAddressRead(), and setAddressWrite().
void mdtAbstractIo::addressChangedForUi (int addressRead, int addressWrite) signal
Referenced by setAddress(), setAddressRead(), and setAddressWrite().
int mdtAbstractIo::addressRead () const
Get the I/O address for read.
See setAddressRead() for details.
Definition at line 53 of file mdtAbstractIo.cpp.
Referenced by mdtDeviceIos::addAnalogInput(), mdtDeviceIos::addAnalogOutput(), mdtDeviceIos::addDigitalInput(), mdtDeviceIos::addDigitalOutput(), mdtMultiIoDevice::getAnalogInputValue(), mdtMultiIoDevice::getAnalogOutputValue(), mdtMultiIoDevice::getDigitalInputValue(), mdtMultiIoDevice::getDigitalOutputValue(), and mdtAbstractIoWidget::setIo().
int mdtAbstractIo::addressWrite () const
Get the I/O address for write.
See setAddressWrite() for details.
Definition at line 64 of file mdtAbstractIo.cpp.
Referenced by mdtDeviceIos::addAnalogOutput(), mdtDeviceIos::addDigitalOutput(), mdtMultiIoDevice::setAnalogOutputValue(), mdtMultiIoDevice::setDigitalOutputValue(), and mdtAbstractIoWidget::setIo().
QString mdtAbstractIo::details () const
Get details about the I/O.
Definition at line 97 of file mdtAbstractIo.cpp.
Referenced by mdtAbstractIoWidget::setIo().
void mdtAbstractIo::detailsChangedForUi (const QString & text) signal
Referenced by setDetails().
void mdtAbstractIo::enabledStateChangedForUi (bool enabled) signal
Referenced by setEnabled().
bool mdtAbstractIo::hasValidData () const
Returns true if a valid value or state was set.
Definition at line 102 of file mdtAbstractIo.cpp.
References mdtValue::isValid(), and pvValue.
QString mdtAbstractIo::label () const
Get the complete I/O label.
Definition at line 86 of file mdtAbstractIo.cpp.
Referenced by mdtAbstractIoWidget::setIo().
void mdtAbstractIo::labelChangedForUi (const QString & text) signal
Referenced by setLabel().
QString mdtAbstractIo::labelShort () const
Get the short I/O label.
Definition at line 75 of file mdtAbstractIo.cpp.
Referenced by mdtAbstractIoWidget::setIo().
void mdtAbstractIo::labelShortChangedForUi (const QString & text) signal
Referenced by setLabelShort().
void mdtAbstractIo::setAddress (int address)
Set the I/O address.
Note: will set both addressRead and addressWrite to given address.
Definition at line 35 of file mdtAbstractIo.cpp.
References address(), and addressChangedForUi().
void mdtAbstractIo::setAddressRead (int address)
Set the I/O address for read.
For some devices, accessing a I/O to set (write) or get (read) its value can be done by another address. Typical examples are some MODBUS fieldbuses (like Wago 750 or Beckhoff BK 90xx). For such case, you can use this method to set the read access address.
Definition at line 47 of file mdtAbstractIo.cpp.
References address(), and addressChangedForUi().
void mdtAbstractIo::setAddressWrite (int address)
Set the I/O address for write.
For some devices, accessing a I/O to set (write) or get (read) its value can be done by another address. Typical examples are some MODBUS fieldbuses (like Wago 750 or Beckhoff BK 90xx). For such case, you can use this method to set the read access address.
Definition at line 58 of file mdtAbstractIo.cpp.
References address(), and addressChangedForUi().
void mdtAbstractIo::setDetails (const QString & text)
Set details about the I/O.
Definition at line 91 of file mdtAbstractIo.cpp.
References detailsChangedForUi().
void mdtAbstractIo::setEnabled (bool enabled)
Set enabled state.
Definition at line 107 of file mdtAbstractIo.cpp.
References enabledStateChangedForUi().
Referenced by mdtMultiIoDevice::setAnalogOutputValue(), and mdtMultiIoDevice::setDigitalOutputValue().
void mdtAbstractIo::setLabel (const QString & text)
Set the complete I/O label.
When used with mdtAbstractIoWidget, this label is displayed as tool tip
Definition at line 80 of file mdtAbstractIo.cpp.
References labelChangedForUi().
void mdtAbstractIo::setLabelShort (const QString & text)
Set the short I/O label.
When used with mdtAbstractIoWidget, the short I/O label is allways displayed
Definition at line 69 of file mdtAbstractIo.cpp.
References labelShortChangedForUi().
void mdtAbstractIo::setValue (const mdtValue & value, bool emitValueChanged = false) virtual slot
Set the value to update display.
Store the value and emit valueChanged() if new value is different from current.
Parameters
value The value to store
emitValueChanged If true, valueChanged(const mdtValue&) will be emitted.
Note: this default implementation does nothing.
Note for UI developpers:
The signal valueChangedForUi() is emited
Definition at line 117 of file mdtAbstractIo.cpp.
const mdtValue & mdtAbstractIo::value () const
Get current value.
Definition at line 112 of file mdtAbstractIo.cpp.
References pvValue.
Referenced by mdtMultiIoDevice::getAnalogInputValue(), mdtMultiIoDevice::getAnalogOutputValue(), mdtMultiIoDevice::getDigitalInputValue(), mdtMultiIoDevice::getDigitalOutputValue(), mdtMultiIoDevice::setAnalogOutputValue(), mdtMultiIoDevice::setDigitalOutputValue(), mdtDigitalOutWidget::setIo(), mdtDigitalInWidget::setIo(), mdtAnalogInWidget::setIo(), and mdtAnalogOutWidget::setIo().
void mdtAbstractIo::valueChanged (const mdtValue & value) signal
This signal is emitted whenever the value is changed.
Referenced by mdtDigitalIo::setValue().
void mdtAbstractIo::valueChanged (mdtAnalogIo * io) signal
This signal is emitted whenever the value is changed.
void mdtAbstractIo::valueChanged (mdtDigitalIo * io) signal
void mdtAbstractIo::valueChangedForUi (const mdtValue & value) signal
This signal is emitted whenever the value is changed.
Use it only for (G-)UI update
Referenced by mdtDigitalIo::setValue().
Member Data Documentation
bool mdtAbstractIo::pvNotifyUi protected
Definition at line 187 of file mdtAbstractIo.h.
Referenced by mdtAbstractIo(), mdtAnalogIo::setRange(), mdtAnalogIo::setValue(), and mdtAnalogIo::setValueInt().
mdtValue mdtAbstractIo::pvValue protected
Definition at line 186 of file mdtAbstractIo.h.
Referenced by hasValidData(), mdtAnalogIo::setRange(), mdtDigitalIo::setValue(), and value().
The documentation for this class was generated from the following files:
src/mdtutils/mdtAbstractIo.h
src/mdtutils/mdtAbstractIo.cpp