Multi diag tools: mdtUsbTransfer Class Reference
mdtUsbTransfer Class Reference
USB transfer.
#include <mdtUsbTransfer.h>
Public Member Functions
mdtUsbTransfer (libusb_device_handle *dev_handle, int isoPacketsCount=0)
Constructor.
~mdtUsbTransfer ()
Destructor.
mdtUsbTransfer (const mdtUsbTransfer &rhs)=delete
mdtUsbTransfer & operator= (const mdtUsbTransfer &rhs)=delete
bool allocOk () const
Check that allocation not failed.
uint8_t flags () const
Get transfer flags.
bool submit (bool sync=false)
Submit transfer.
bool cancel (bool sync=false)
Cancel transfer.
libusb_transfer_status status () const
Get transfer status.
int actualLength () const
Get actual length.
unsigned int timeout () const
Get timeout that was given to transfer.
mdtError lastError () const
Get last error.
bool isSync () const
Check if transfer is a synchronous transfer.
int * completedPointer ()
Access completed flag.
void setCompleted ()
Set completed flag.
bool isCompleted () const
Check completed flag.
Protected Member Functions
libusb_device_handle * deviceHandle ()
Get device handle.
libusb_transfer * transfer ()
Access libusb transfer.
Detailed Description
USB transfer.
libusb_transfer wrapper class.
Definition at line 32 of file mdtUsbTransfer.h.
Constructor & Destructor Documentation
mdtUsbTransfer::mdtUsbTransfer (libusb_device_handle * dev_handle, int isoPacketsCount = 0)
Constructor.
Definition at line 24 of file mdtUsbTransfer.cpp.
mdtUsbTransfer::~mdtUsbTransfer ()
Destructor.
Definition at line 38 of file mdtUsbTransfer.cpp.
mdtUsbTransfer::mdtUsbTransfer (const mdtUsbTransfer & rhs) delete
Member Function Documentation
int mdtUsbTransfer::actualLength () const inline
Get actual length.
Actual length of data that was transferred. Read-only, and only for use within transfer callback function. Not valid for isochronous endpoint transfers. See libusb documentation for details.
Precondition
Internall transfer must be valid (see allocOk()).
Definition at line 102 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcTransferHandler::handleBulkInTransferComplete(), and mdtUsbtmcTransferHandler::handleControlTransferComplete().
bool mdtUsbTransfer::allocOk () const inline
Check that allocation not failed.
Definition at line 50 of file mdtUsbTransfer.h.
bool mdtUsbTransfer::cancel (bool sync = false)
Cancel transfer.
Will use libusb_cancel_transfer(). Note: this function returns directly after cancel was submitted (exactly as libusb_cancel_transfer() does). On error, this function returns false, and lastError's systemError will contain libusb_error error.
Precondition
Internall transfer must be valid (see allocOk()).
Definition at line 65 of file mdtUsbTransfer.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtUsbtmcTransferHandler::submitControlTransfersCancel().
int* mdtUsbTransfer::completedPointer () inline
Access completed flag.
Can be used with libusb_handle_events_completed().
Definition at line 138 of file mdtUsbTransfer.h.
libusb_device_handle* mdtUsbTransfer::deviceHandle () inline protected
Get device handle.
Definition at line 162 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbControlTransfer::fillTransfer(), mdtUsbtmcInterruptTransfer::setup(), mdtUsbtmcBulkTransfer::setupBulkInRequest(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
uint8_t mdtUsbTransfer::flags () const inline
Get transfer flags.
Definition at line 57 of file mdtUsbTransfer.h.
bool mdtUsbTransfer::isCompleted () const inline
Check completed flag.
Definition at line 153 of file mdtUsbTransfer.h.
bool mdtUsbTransfer::isSync () const inline
Check if transfer is a synchronous transfer.
This can help transfer callback. If this flag is set, all it should have to do is call setCompleted(), else. process regarding application.
Definition at line 129 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcTransferHandler::controlTransferCallback().
mdtError mdtUsbTransfer::lastError () const inline
Get last error.
Definition at line 118 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcTransferHandler::dbgSubmitCustomBulkOutTransfer(), mdtUsbtmcTransferHandler::submitClearEndpointHalt(), mdtUsbtmcTransferHandler::submitCommand(), mdtUsbtmcTransferHandler::submitControlTransfersCancel(), and mdtUsbtmcTransferHandler::submitInterruptInTransfer().
mdtUsbTransfer& mdtUsbTransfer::operator= (const mdtUsbTransfer & rhs) delete
void mdtUsbTransfer::setCompleted () inline
Set completed flag.
Definition at line 145 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcTransferHandler::controlTransferCallback().
libusb_transfer_status mdtUsbTransfer::status () const inline
Get transfer status.
Precondition
Internall transfer must be valid (see allocOk()).
Definition at line 88 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcTransferHandler::handleBulkInTransferComplete(), mdtUsbtmcTransferHandler::handleBulkOutTransferComplete(), mdtUsbtmcTransferHandler::handleControlTransferComplete(), mdtUsbtmcTransferHandler::handleInterruptInTransferComplete(), mdtUsbtmcTransferHandler::restoreBulkInTransferSA(), mdtUsbtmcTransferHandler::restoreBulkOutTransferSA(), and mdtUsbtmcTransferHandlerStateMachine::Running_::restoreCancelledBulkOutTransfer().
bool mdtUsbTransfer::submit (bool sync = false)
Submit transfer.
Will use libusb_submit_transfer(). On error, this function returns false, and lastError's systemError will contain libusb_error error.
Precondition
Internall transfer must be valid (see allocOk()).
Definition at line 45 of file mdtUsbTransfer.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtUsbtmcTransferHandler::dbgSubmitCustomBulkOutTransfer(), mdtUsbtmcTransferHandler::submitClearEndpointHalt(), mdtUsbtmcTransferHandler::submitCommand(), and mdtUsbtmcTransferHandler::submitInterruptInTransfer().
unsigned int mdtUsbTransfer::timeout () const inline
Get timeout that was given to transfer.
Definition at line 110 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcTransferHandler::handleBulkOutTransferComplete(), and mdtUsbtmcTransferHandler::handleInterruptInTransferComplete().
libusb_transfer* mdtUsbTransfer::transfer () inline protected
Access libusb transfer.
Definition at line 169 of file mdtUsbTransfer.h.
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbControlTransfer::fillTransfer(), mdtUsbtmcInterruptTransfer::setup(), mdtUsbtmcBulkTransfer::setupBulkInRequest(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbTransfer.h
src/mdtport/mdtUsbTransfer.cpp