Multi diag tools: mdtDeviceDSO1000A Class Reference
mdtDeviceDSO1000A Class Reference
#include <mdtDeviceDSO1000A.h>
Public Member Functions
mdtDeviceDSO1000A (QObject *parent=0)
~mdtDeviceDSO1000A ()
mdtAbstractPort::error_t connectToDevice (const mdtDeviceInfo &devInfo)
Search and connect to physical device.
Public Member Functions inherited from mdtDeviceScpi
mdtDeviceScpi (QObject *parent=0)
Construct a SCPI device.
virtual ~mdtDeviceScpi ()
mdtPortManager * portManager ()
Get internal port manager instance.
mdtAbstractPort::error_t connectToDevice (const mdtDeviceInfo &devInfo)
Search and connect to physical device.
int sendCommand (const QByteArray &command)
Send a command to device.
QByteArray sendQuery (const QByteArray &query)
Send a query to device.
bool waitOperationComplete (int timeout, int interval)
Wait until operation is complete (Using *OPC? query)
int checkDeviceError ()
Query device about error.
Public Member Functions inherited from mdtDevice
mdtDevice (QObject *parent=0)
Construct a device object.
virtual ~mdtDevice ()
Destructor.
void setName (const QString &name)
Set the device name.
QString name () const
Get device name.
void setIdentification (const QVariant &id)
Set device identification.
QVariant identification () const
Get device identification.
virtual void disconnectFromDevice ()
Disconnect from device.
void addInput (mdtAnalogIo *analogInput)
Add a analog input.
void addInputs (const QList< mdtAnalogIo * > &analogInputs)
Add a list of analog inputs.
void addOutput (mdtAnalogIo *analogOutput)
Add a analog output.
void addOutputs (const QList< mdtAnalogIo * > &analogOutputs)
Add a list of analog outputs.
void addInput (mdtDigitalIo *digitalInput)
Add a digital input.
void addInputs (const QList< mdtDigitalIo * > &digitalInputs)
Add a list of digital inputs.
void addOutput (mdtDigitalIo *digitalOutput)
Add a digital output.
void addOutputs (const QList< mdtDigitalIo * > &digitalOutputs)
Add a list of digital outputs.
void deleteIos ()
Delete all I/O in container.
mdtDeviceIos * ios ()
Get the I/Os container.
void setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
virtual bool isReady ()
Check if device is ready.
void start (int queryInterval)
Start periodic device querying.
void stop ()
Stop periodic device querying.
void wait (int ms)
Wait some time.
mdtError lastError () const
Get last error.
mdtValue getAnalogInputValue (mdtAnalogIo *analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (int address, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogInputs (bool waitOnReply)
Read all analog inputs on physical device and update (G)UI representation.
mdtValue getAnalogOutputValue (mdtAnalogIo *analogOutput, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogOutputs (bool waitOnReply)
Read all analog outputs on physical device and update (G)UI representation.
int setAnalogOutputValue (mdtAnalogIo *analogOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
int setAnalogOutputs (bool waitOnReply)
Write all analog outputs on physical device and update (G)UI representation.
mdtValue getDigitalInputValue (mdtDigitalIo *digitalInput, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (int address, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalInputs (bool waitOnReply)
Read all digital inputs on physical device and update (G)UI representation.
mdtValue getDigitalOutputValue (mdtDigitalIo *digitalOutput, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalOutputs (bool waitOnReply)
Read all digital outputs on physical device and update (G)UI representation.
int setDigitalOutputValue (mdtDigitalIo *digitalOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a digital output value.
int setDigitalOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputsValue (const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a value and validity for all digital outputs.
int setDigitalOutputs (bool waitOnReply)
Write all digital outputs to physical device and update (G)UI representation.
mdtPortManager::state_t currentState ()
Get device state.
Additional Inherited Members
Public Slots inherited from mdtDevice
void setAnalogOutputValue (mdtAnalogIo *analogOutput)
Set value on a analog output on physical device.
void setDigitalOutputValue (mdtDigitalIo *digitalOutput)
Set value on a digital output on physical device.
void runQueries ()
Queries to send periodically.
Signals inherited from mdtDevice
void stateChanged (int state)
mdtDeviceIos *pvIos; // I/O's container
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
Protected Slots inherited from mdtDevice
virtual void decodeReadenFrame (mdtPortTransaction *transaction)
Decode incoming frames.
Protected Member Functions inherited from mdtDeviceScpi
void handleDeviceError (const QList< QVariant > &decodedValues)
Handle device error.
virtual void handleDeviceSpecificError (int errNum, const QString &errText, const QList< QString > &deviceSpecificTexts)
Handle device's specific error.
void logDeviceError (int errNum, const QString &errText, const QList< QString > &deviceSpecificTexts, mdtError::level_t level)
Log a device error with mdtError system.
Protected Attributes inherited from mdtDeviceScpi
mdtUsbtmcPortManager * pvUsbtmcPortManager
Detailed Description
Definition at line 28 of file mdtDeviceDSO1000A.h.
Constructor & Destructor Documentation
mdtDeviceDSO1000A::mdtDeviceDSO1000A (QObject * parent = 0)
Definition at line 25 of file mdtDeviceDSO1000A.cpp.
References mdtPortManager::config(), mdtDeviceScpi::portManager(), mdtDeviceScpi::pvUsbtmcPortManager, mdtPortConfig::setReadFrameSize(), mdtPortConfig::setReadQueueSize(), mdtPortConfig::setReadTimeout(), mdtPortConfig::setWriteFrameSize(), mdtPortConfig::setWriteQueueSize(), and mdtDevice::stateChanged().
mdtDeviceDSO1000A::~mdtDeviceDSO1000A ()
Definition at line 40 of file mdtDeviceDSO1000A.cpp.
Member Function Documentation
mdtAbstractPort::error_t mdtDeviceDSO1000A::connectToDevice (const mdtDeviceInfo & devInfo) virtual
Search and connect to physical device.
Will scan available ports and open the first port that has device attached maching request.
Parameters
devInfo Requested device's informations. Note: Vendor ID and/or product ID are automatically set. (in other words, a empty mdtDeviceInfo can be passed). Optionnaly, a serial ID can be set (usefull if many U3606A devices are connected)
Returns
A error listed in mdtAbstractPort::error_t (NoError on success)
Reimplemented from mdtDevice.
Definition at line 45 of file mdtDeviceDSO1000A.cpp.
References mdtDeviceScpi::connectToDevice(), mdtDeviceInfo::setProductId(), and mdtDeviceInfo::setVendorId().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceDSO1000A.h
src/mdtdevice/mdtDeviceDSO1000A.cpp