Multi diag tools: mdtModbusIoTool Class Reference
mdtModbusIoTool Class Reference
Minimal tool for MODBUS I/O.
#include <mdtModbusIoTool.h>
Public Slots
void retranslate ()
Retranslate.
Signals
void errorEvent ()
Public Member Functions
mdtModbusIoTool (QWidget *parent=0, Qt::WindowFlags flags=0)
Construct a mdtModbusIoTool object.
~mdtModbusIoTool ()
destruct a mdtModbusIoTool object
void setAvailableTranslations (const QMap< QString, QString > &avaliableTranslations, const QString &currentTranslationKey)
Build the translations menu.
Additional Inherited Members
Public Attributes inherited from Ui_mdtModbusIoTool
QAction * action_Quit
QAction * action_Setup
QWidget * centralwidget
QGridLayout * gridLayout
QPushButton * pbDisconnect
QPushButton * pbAbortScan
QPushButton * pbConnect
QLabel * lbHwNodeId
QSpinBox * sbHwNodeId
QSpacerItem * horizontalSpacer
QScrollArea * saIos
QWidget * scrollAreaWidgetContents
QMenuBar * menubar
QMenu * menu_File
QMenu * menu_Language
QStatusBar * statusbar
Detailed Description
Minimal tool for MODBUS I/O.
Definition at line 36 of file mdtModbusIoTool.h.
Constructor & Destructor Documentation
mdtModbusIoTool::mdtModbusIoTool (QWidget * parent = 0, Qt::WindowFlags flags = 0)
Construct a mdtModbusIoTool object.
Definition at line 35 of file mdtModbusIoTool.cpp.
References Ui_mdtModbusIoTool::action_Setup, errorEvent(), mdtDeviceModbus::modbusTcpPortManager(), mdtPortManager::notifyCurrentState(), Ui_mdtModbusIoTool::pbAbortScan, Ui_mdtModbusIoTool::pbConnect, Ui_mdtModbusIoTool::pbDisconnect, mdtDeviceModbus::portManager(), Ui_mdtModbusIoTool::saIos, mdtDevice::setName(), Ui_mdtModbusIoTool::setupUi(), and mdtDevice::start().
mdtModbusIoTool::~mdtModbusIoTool ()
destruct a mdtModbusIoTool object
Definition at line 75 of file mdtModbusIoTool.cpp.
Member Function Documentation
void mdtModbusIoTool::errorEvent () signal
Definition at line 124 of file moc_mdtModbusIoTool.cxx.
Referenced by mdtModbusIoTool().
void mdtModbusIoTool::retranslate () slot
Retranslate.
This slot is called by mdtApplication when language has changed
Definition at line 102 of file mdtModbusIoTool.cpp.
References Ui_mdtModbusIoTool::retranslateUi().
void mdtModbusIoTool::setAvailableTranslations (const QMap< QString, QString > & avaliableTranslations, const QString & currentTranslationKey)
Build the translations menu.
Definition at line 79 of file mdtModbusIoTool.cpp.
References mdtApp, and Ui_mdtModbusIoTool::menu_Language.
The documentation for this class was generated from the following files:
src/mdttools/mdtModbusIoTool.h
src/mdttools/mdtModbusIoTool.cpp
src/mdttools/moc_mdtModbusIoTool.cxx