Multi diag tools: mdtUsbtmcFrame Class Reference
mdtUsbtmcFrame Class Reference
#include <QByteArray>
#include <mdtUsbtmcFrame.h>
Public Types
enum msgId_t : uint8_t {
msgId_t::MSG_ZERO = 0, msgId_t::DEV_DEP_MSG_OUT = 1, msgId_t::DEV_DEP_MSG_IN = 2, msgId_t::VENDOR_SPECIFIC_OUT = 126,
msgId_t::VENDOR_SPECIFIC_IN = 127
}
USBTMC MsgID.
Public Member Functions
mdtUsbtmcFrame (int bufferSize)
Constructor.
void clear ()
Clear frame.
int capacity () const
Get internal buffer capacity.
uint8_t * buffer ()
Access internal buffer.
int bufferLength () const
Get buffer length.
bool isComplete (int written) const
Check if tranfer is complete (valid for bulk IN transfer)
void setMsgID (msgId_t id)
Set MsgID.
msgId_t msgID () const
Get MsgID.
void setbTag (uint8_t bTag)
Set bTag.
uint8_t bTag () const
Get bTag.
uint8_t bTagInverse () const
Get bTagInverse.
void setTransferSize (uint32_t size)
Set TransferSize.
void setTransferSizeToMax ()
Set TransferSize to maximum possible size.
uint32_t transferSize () const
Get TransferSize.
void setEOM (bool set)
Set EOM.
bool EOMset () const
Check if EOM is set.
void setTermChar (char c)
Set TermChar.
bool TermCharset () const
Check if TermChar is set.
void resetTermChar ()
Reset TermChar.
void setData (mdtUsbtmcTxMessage &message)
Set data.
void getData (mdtUsbtmcRxMessage &message)
Get data.
void dbgSetCustomValue (int offset, uint8_t value)
Set custom value.
Detailed Description
#include <QByteArray>
Todo:
Check header whenn receiving data.
USBTMC frame (i.e. USBTMC bulk transfer)
Used by USBTMC API to send en receive frames in USBTMC standard over bulk pipes. The name frame was choosen because transfer is close to libusb_transfer, and that part is handled by mdtUsbtmcBulkTransfer.
References:
USBTMC Revision 1.0 (2003)
http://www.usb.org/developers/devclass_docs#approved
http://www.usb.org/developers/devclass_docs/USBTMC_1_006a.zip
To avoid continious alloc/free, the frame has internal fixed capacity. Different capacity and sizes are available. To clarify them, see a USBTMC frame (bulk transfer) format:
| USBTMC | Data bytes | Alignment |
| header | (USBTMC TransferSize) | bytes |
Capacity of the frame is defined as below:
capacity: USBTMC header + Data bytes + alignemnt bytes (is simply the capacity of internal buffer)
Size of the frame is defined as below:
transferSize: data bytes only (without header and without alignment bytes)
bufferLength: USBTMC header + data bytes + alignment bytes (useful for Bulk-OUT transfer)
Note:
For Bulk-OUT transfer, use bufferLength to tell libusb how many bytes must be sent to device.
For Bulk-IN transfer, use capacity to tell libusb how many bytes it can put into buffer.
Definition at line 64 of file mdtUsbtmcFrame.h.
Member Enumeration Documentation
enum mdtUsbtmcFrame::msgId_t : uint8_t strong
USBTMC MsgID.
See Table 2 in USBTMC specifications for details.
Enumerator
MSG_ZERO
Reserved.
DEV_DEP_MSG_OUT
USBTMC device dependent command message
DEV_DEP_MSG_IN
USBTMC response message. Represent the REQUEST_DEV_DEP_MSG_IN if frame is sent from host (OUT)
VENDOR_SPECIFIC_OUT
USBTMC vendor specific command message
VENDOR_SPECIFIC_IN
USBTMC vendor specific response message on the Bulk-IN endpoint. Represent the REQUEST_VENDOR_SPECIFIC_IN if frame is sent from host (OUT)
Definition at line 72 of file mdtUsbtmcFrame.h.
Constructor & Destructor Documentation
mdtUsbtmcFrame::mdtUsbtmcFrame (int bufferSize)
Constructor.
Parameters
bufferSize Internal buffer size.
Precondition
bufferSize must be at least 512 and a multiple of 4
Definition at line 27 of file mdtUsbtmcFrame.cpp.
Member Function Documentation
uint8_t mdtUsbtmcFrame::bTag () const inline
Get bTag.
See Table 1 in USBTMC specifications for details.
Definition at line 165 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::bTag(), mdtUsbtmcBulkTransfer::bTagIsOk(), and setbTag().
uint8_t mdtUsbtmcFrame::bTagInverse () const inline
Get bTagInverse.
See Table 1 in USBTMC specifications for details.
Definition at line 173 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::bTagIsOk().
uint8_t* mdtUsbtmcFrame::buffer () inline
Access internal buffer.
Definition at line 104 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbtmcBulkTransfer::setupBulkInRequest(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
int mdtUsbtmcFrame::bufferLength () const inline
Get buffer length.
Returns length of USBTMC header + data + alignment bytes.
Definition at line 112 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::setupDevDepMsgOut().
int mdtUsbtmcFrame::capacity () const inline
Get internal buffer capacity.
Definition at line 97 of file mdtUsbtmcFrame.h.
Referenced by dbgSetCustomValue(), mdtUsbtmcBulkTransfer::dbgSetupCustom(), setData(), setTransferSizeToMax(), and mdtUsbtmcBulkTransfer::setupBulkInRequest().
void mdtUsbtmcFrame::clear ()
Clear frame.
Will clear header and reset data size
Definition at line 37 of file mdtUsbtmcFrame.cpp.
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbtmcBulkTransfer::setupBulkInRequest(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
void mdtUsbtmcFrame::dbgSetCustomValue (int offset, uint8_t value) inline
Set custom value.
Used for debug and testing
Precondition
offset must be < capacity
Definition at line 286 of file mdtUsbtmcFrame.h.
References capacity().
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom().
bool mdtUsbtmcFrame::EOMset () const inline
Check if EOM is set.
This has sense when response of DEV_DEP_MSG_IN was received from device. See Table 9 in USBTMC specifications for details.
Definition at line 227 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::isEOM().
void mdtUsbtmcFrame::getData (mdtUsbtmcRxMessage & message) inline
Get data.
Will write (by copy) data part to given message.
Definition at line 275 of file mdtUsbtmcFrame.h.
References transferSize(), and mdtUsbtmcRxMessage::write().
Referenced by mdtUsbtmcBulkTransfer::getData().
bool mdtUsbtmcFrame::isComplete (int written) const inline
Check if tranfer is complete (valid for bulk IN transfer)
After a bulk IN transfer completed, tell how many data was written to buffer. This is typically available from libusb_transfer::actual_length.
Note: we assume that libusb handles transfer in one shot, i.e. that, when transfer is completed, all data that device has queued are available.
Assuming this note and that clear() is called before each transfer, we can assume that frame is complete if (written - 12) >= transferSize.
Definition at line 129 of file mdtUsbtmcFrame.h.
References transferSize().
Referenced by mdtUsbtmcBulkTransfer::receivedAllData().
msgId_t mdtUsbtmcFrame::msgID () const inline
Get MsgID.
See Table 2 in USBTMC 1.0 specifications for details.
Definition at line 147 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::msgID().
void mdtUsbtmcFrame::resetTermChar () inline
Reset TermChar.
See Table 4 in USBTMC specifications for details. Note: will also clear TermCharEnabled bit in bmTransferAttributes
Definition at line 255 of file mdtUsbtmcFrame.h.
void mdtUsbtmcFrame::setbTag (uint8_t bTag) inline
Set bTag.
See Table 1 in USBTMC 1.0 specifications for details. Note: will also set bTagInverse
Definition at line 156 of file mdtUsbtmcFrame.h.
References bTag().
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
void mdtUsbtmcFrame::setData (mdtUsbtmcTxMessage & message)
Set data.
Will read data from given message and copy them to internal buffer. If all data of message can be hold in tranfer, EOM bit will be set, else not.
TransferSize will also be adjusted.
Precondition
message must have at least 1 byte of data to read from
Definition at line 54 of file mdtUsbtmcFrame.cpp.
References mdtUsbtmcTxMessage::bytesToRead(), capacity(), mdtUsbtmcTxMessage::read(), and setTransferSize().
Referenced by mdtUsbtmcBulkTransfer::setupDevDepMsgOut().
void mdtUsbtmcFrame::setEOM (bool set) inline
Set EOM.
See Table 3 in USBTMC specifications for details.
Definition at line 214 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::setupDevDepMsgOut().
void mdtUsbtmcFrame::setMsgID (msgId_t id) inline
Set MsgID.
See Table 2 in USBTMC specifications for details.
Definition at line 138 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
void mdtUsbtmcFrame::setTermChar (char c) inline
Set TermChar.
See Table 4 in USBTMC specifications for details. Note: will also set TermCharEnabled bit in bmTransferAttributes
Definition at line 236 of file mdtUsbtmcFrame.h.
Referenced by mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
void mdtUsbtmcFrame::setTransferSize (uint32_t size)
Set TransferSize.
See Table 3 in USBTMC specifications for details. Note that setting TransferSize manually has only sense when setting up a frame for DEV_DEP_MSG_IN or VENDOR_SPECIFIC_IN query. When setting up a frame for DEV_DEP_MSG_OUT or VENDOR_SPECIFIC_OUT, use setData() witch will also ajust TransferSize.
Precondition
size must be > 0 and <= totalCapacity-12
Definition at line 43 of file mdtUsbtmcFrame.cpp.
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), setData(), and setTransferSizeToMax().
void mdtUsbtmcFrame::setTransferSizeToMax () inline
Set TransferSize to maximum possible size.
Useful when setting up frame for DEV_DEP_MSG_IN or VENDOR_SPECIFIC_IN query.
Definition at line 193 of file mdtUsbtmcFrame.h.
References capacity(), and setTransferSize().
Referenced by mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
bool mdtUsbtmcFrame::TermCharset () const inline
Check if TermChar is set.
This has sense when response of DEV_DEP_MSG_IN was received from device. See Table 9 in USBTMC specifications for details.
Definition at line 246 of file mdtUsbtmcFrame.h.
uint32_t mdtUsbtmcFrame::transferSize () const inline
Get TransferSize.
Returns number of message bytes, without USBTMC header and without extra alignment bytes.
See, for example, Table 3 in USBTMC 1.0 specifications for details.
Definition at line 206 of file mdtUsbtmcFrame.h.
Referenced by getData(), and isComplete().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbtmcFrame.h
src/mdtport/mdtUsbtmcFrame.cpp