Multi diag tools: mdtTtTestNodeUnit Class Reference
mdtTtTestNodeUnit Class Reference
Helper class for test node unit data manipulation.
#include <mdtTtTestNodeUnit.h>
Public Member Functions
mdtTtTestNodeUnit (QObject *parent, const QSqlDatabase &db)
Constructor.
QString sqlForTestConnectionSelection (const QList< QVariant > connectionIdList) const
Get SQL statement for test connection selection.
QList< QVariant > getConnectionIdListOfUnitId (const QVariant &unitId, bool excludeAllreadyAffectedToTestNode, bool &ok)
Get a list of unit connection IDs for given unit ID.
QList< QVariant > getConnectionIdListLinkedToConnectionIdList (const QList< QVariant > connectionIdList, bool *ok)
Get unit connection IDs that are linked to given unit connection IDs.
mdtSqlRecord getUnitData (const QVariant &unitId, bool *ok)
Get unit data.
mdtTtTestNodeUnitData getData (const QVariant &nodeUnitId, bool *ok, bool includeTestConnectionData)
Get test node unit data.
bool addNodeUnit (const mdtTtTestNodeUnitData &data)
Add a test node unit.
bool editNodeUnit (const QVariant &nodeUnitId, const mdtTtTestNodeUnitData &data)
Edit a test node unit.
bool removeNodeUnit (const QVariant &nodeUnitId, bool handleTransaction)
Remove a test node unit.
bool removeNodeUnits (const mdtSqlTableSelection &s)
Remove test node units.
bool addConnection (const QVariant &unitConnectionId, const QVariant &testNodeUnitId, const QVariant &testNodeBusId)
Add a connection.
bool addConnections (const QList< QVariant > &unitConnectionIdList, const QVariant &testNodeUnitId, const QVariant &testNodeBusId, bool handleTransaction)
Add a list of connections.
bool addConnections (const QVariant &testNodeUnitId, const QVariant &testNodeBusId, bool handleTransaction)
Add connections that are related to given test node unit.
QStringList getTestLinksDependingOnConnection (const QVariant &testNodeUnitConnectionId, bool &ok)
Get a list of test links on witch depends on given test node unit connection.
bool removeConnection (const QVariant &unitConnectionId)
Remove a test node unit connection from TestNodeUnitConnection_tbl.
bool removeConnections (const QList< QVariant > &unitConnectionIdList, bool handleTransaction)
Remove given test node unit connections from TestNodeUnitConnection_tbl.
bool removeConnections (const QVariant &testNodeUnitId, bool handleTransaction)
Remove connections for given test node unit ID.
bool setBusIdToConnection (const QVariant &unitConnectionId, const QVariant &busId)
Set bus ID to given connection ID.
bool setBusIdToConnections (const QList< QVariant > &unitConnectionIdLits, const QVariant &busId)
Set bus ID to given connection ID list.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
template<typename T >
bool addRecordList (const QList< T > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField1, const QVariant &key1, const QString &matchField2, const QVariant &key2)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for test node unit data manipulation.
Definition at line 38 of file mdtTtTestNodeUnit.h.
Constructor & Destructor Documentation
mdtTtTestNodeUnit::mdtTtTestNodeUnit (QObject * parent, const QSqlDatabase & db)
Constructor.
Definition at line 29 of file mdtTtTestNodeUnit.cpp.
Member Function Documentation
bool mdtTtTestNodeUnit::addConnection (const QVariant & unitConnectionId, const QVariant & testNodeUnitId, const QVariant & testNodeBusId)
Add a connection.
Definition at line 279 of file mdtTtTestNodeUnit.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, and mdtSqlRecord::setValue().
Referenced by addConnections().
bool mdtTtTestNodeUnit::addConnections (const QList< QVariant > & unitConnectionIdList, const QVariant & testNodeUnitId, const QVariant & testNodeBusId, bool handleTransaction)
Add a list of connections.
Definition at line 297 of file mdtTtTestNodeUnit.cpp.
References addConnection(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), and mdtTtBase::rollbackTransaction().
Referenced by addConnections(), mdtTtTestNode::addMissingConnections(), and addNodeUnit().
bool mdtTtTestNodeUnit::addConnections (const QVariant & testNodeUnitId, const QVariant & testNodeBusId, bool handleTransaction)
Add connections that are related to given test node unit.
Definition at line 323 of file mdtTtTestNodeUnit.cpp.
References addConnections(), and getConnectionIdListOfUnitId().
bool mdtTtTestNodeUnit::addNodeUnit (const mdtTtTestNodeUnitData & data)
Add a test node unit.
Definition at line 196 of file mdtTtTestNodeUnit.cpp.
References addConnections(), mdtTtBase::addRecord(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::rollbackTransaction(), and mdtSqlRecord::value().
bool mdtTtTestNodeUnit::editNodeUnit (const QVariant & nodeUnitId, const mdtTtTestNodeUnitData & data)
Edit a test node unit.
Definition at line 216 of file mdtTtTestNodeUnit.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), mdtTtBase::updateRecord(), and mdtSqlRecord::value().
QList< QVariant > mdtTtTestNodeUnit::getConnectionIdListLinkedToConnectionIdList (const QList< QVariant > connectionIdList, bool * ok)
Get unit connection IDs that are linked to given unit connection IDs.
Will return IDs that not currently exists in TestNodeUnitConnection_tbl.
Definition at line 83 of file mdtTtTestNodeUnit.cpp.
References mdtError::clear(), mdtTtBase::database(), mdtClPathGraph::getLinkedConnectionIdList(), mdtClPathGraph::lastError(), mdtClPathGraph::loadLinkList(), and mdtTtBase::pvLastError.
QList< QVariant > mdtTtTestNodeUnit::getConnectionIdListOfUnitId (const QVariant & unitId, bool excludeAllreadyAffectedToTestNode, bool & ok)
Get a list of unit connection IDs for given unit ID.
QList<QVariant> mdtTtTestNodeUnit::getConnectionIdListOfUnitId(const QVariant & unitId, bool *ok)
Definition at line 53 of file mdtTtTestNodeUnit.cpp.
Referenced by addConnections(), and removeConnections().
mdtTtTestNodeUnitData mdtTtTestNodeUnit::getData (const QVariant & nodeUnitId, bool * ok, bool includeTestConnectionData)
Get test node unit data.
Definition at line 144 of file mdtTtTestNodeUnit.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtTtBase::getData(), getUnitData(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::Warning.
QStringList mdtTtTestNodeUnit::getTestLinksDependingOnConnection (const QVariant & testNodeUnitConnectionId, bool & ok)
Get a list of test links on witch depends on given test node unit connection.
Todo:
Create a QSqlError mapping somwhere (note that error code depends on used database engine). When a foreign key constraint was detected, check on witch table it depends, then build a user friendly error
Definition at line 375 of file mdtTtTestNodeUnit.cpp.
mdtSqlRecord mdtTtTestNodeUnit::getUnitData (const QVariant & unitId, bool * ok)
Get unit data.
Definition at line 114 of file mdtTtTestNodeUnit.cpp.
References mdtError::commit(), mdtTtBase::getData(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::Warning.
Referenced by getData().
bool mdtTtTestNodeUnit::removeConnection (const QVariant & unitConnectionId)
Remove a test node unit connection from TestNodeUnitConnection_tbl.
Definition at line 338 of file mdtTtTestNodeUnit.cpp.
References mdtTtBase::removeData().
Referenced by removeConnections().
bool mdtTtTestNodeUnit::removeConnections (const QList< QVariant > & unitConnectionIdList, bool handleTransaction)
Remove given test node unit connections from TestNodeUnitConnection_tbl.
Definition at line 343 of file mdtTtTestNodeUnit.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), removeConnection(), and mdtTtBase::rollbackTransaction().
Referenced by removeConnections(), and removeNodeUnit().
bool mdtTtTestNodeUnit::removeConnections (const QVariant & testNodeUnitId, bool handleTransaction)
Remove connections for given test node unit ID.
Definition at line 383 of file mdtTtTestNodeUnit.cpp.
References getConnectionIdListOfUnitId(), and removeConnections().
bool mdtTtTestNodeUnit::removeNodeUnit (const QVariant & nodeUnitId, bool handleTransaction)
Remove a test node unit.
Will also remove related connections from TestNodeUnitConnection_tbl
Definition at line 227 of file mdtTtTestNodeUnit.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), removeConnections(), mdtTtBase::removeData(), and mdtTtBase::rollbackTransaction().
Referenced by removeNodeUnits().
bool mdtTtTestNodeUnit::removeNodeUnits (const mdtSqlTableSelection & s)
Remove test node units.
Will also remove related connections from TestNodeUnitConnection_tbl
Definition at line 257 of file mdtTtTestNodeUnit.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtSqlTableSelection::dataList(), removeNodeUnit(), and mdtTtBase::rollbackTransaction().
bool mdtTtTestNodeUnit::setBusIdToConnection (const QVariant & unitConnectionId, const QVariant & busId)
Set bus ID to given connection ID.
Definition at line 399 of file mdtTtTestNodeUnit.cpp.
References mdtTtBase::getData(), mdtSqlRecord::setValue(), and mdtTtBase::updateRecord().
Referenced by setBusIdToConnections().
bool mdtTtTestNodeUnit::setBusIdToConnections (const QList< QVariant > & unitConnectionIdLits, const QVariant & busId)
Set bus ID to given connection ID list.
Definition at line 424 of file mdtTtTestNodeUnit.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::rollbackTransaction(), and setBusIdToConnection().
QString mdtTtTestNodeUnit::sqlForTestConnectionSelection (const QList< QVariant > connectionIdList) const
Get SQL statement for test connection selection.
Definition at line 34 of file mdtTtTestNodeUnit.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestNodeUnit.h
src/mdttools/mdttesttool/mdtTtTestNodeUnit.cpp