Multi diag tools: mdtPortThreadHelperSocket Class Reference
mdtPortThreadHelperSocket Class Reference
Help the usage of QTcpSocket's asynchrone API.
#include <mdtPortThreadHelperSocket.h>
Signals
void connected ()
Emitted when internal socket notified that it is connected, and when we are ready.
Signals inherited from mdtPortThreadHelper
void readProcessBegin ()
Emitted when a read process begins.
void writeProcessBegin ()
Emitted when a write process begins.
void newFrameReaden ()
Emited when a new frame is available.
Public Member Functions
mdtPortThreadHelperSocket (QObject *parent=0)
Constructor.
~mdtPortThreadHelperSocket ()
Destructor.
void setSocket (QTcpSocket *socket)
Set socket.
void connectToHost ()
Connect to host set during setSocket()
Public Member Functions inherited from mdtPortThreadHelper
mdtPortThreadHelper (QObject *parent=0)
Constructor.
virtual ~mdtPortThreadHelper ()
Destructor.
void setPort (mdtAbstractPort *port)
Set the port instance.
void setThread (mdtPortThread *thread)
Set the thread instance.
mdtAbstractPort::error_t handleCommonReadErrors (mdtAbstractPort::error_t portError)
Handle common read errors.
mdtAbstractPort::error_t handleCommonWriteErrors (mdtAbstractPort::error_t portError)
Handle common write errors.
mdtAbstractPort::error_t handleCommonReadWriteErrors (mdtAbstractPort::error_t portError)
Handle common read and write errors.
bool getNewFrameRead ()
Get a new frame for reading data from port.
void submitCurrentReadFrame (bool notify)
Submit current read frame.
void restoreCurrentReadFrameToPool ()
Restore current read frame to pool.
int submitReadenData (const char *data, int size, bool emitNewFrameReaden)
Store readen data into frame.
bool getNewFrameWrite ()
Get a new frame for writing data to port.
void restoreCurrentWriteFrameToPool ()
Restore current write frame to pool.
void setCurrentReadFrame (mdtFrame *frame)
Set current read frame.
mdtFrame * currentReadFrame ()
Get current read frame.
void setCurrentWriteFrame (mdtFrame *frame)
Set current write frame.
mdtFrame * currentWriteFrame ()
Get current write frame.
Additional Inherited Members
Protected Slots inherited from mdtPortThreadHelper
virtual void requestWrite ()
Protected Member Functions inherited from mdtPortThreadHelper
void notifyError (mdtAbstractPort::error_t error, bool renotifySameError=false)
Calls mdtPortThread::notifyError()
virtual mdtAbstractPort::error_t reconnect (bool notify)
Call subclass reconnect() method.
Protected Attributes inherited from mdtPortThreadHelper
mdtAbstractPort * pvPort
mdtPortThread * pvThread
Detailed Description
Help the usage of QTcpSocket's asynchrone API.
Definition at line 32 of file mdtPortThreadHelperSocket.h.
Constructor & Destructor Documentation
mdtPortThreadHelperSocket::mdtPortThreadHelperSocket (QObject * parent = 0)
Constructor.
Todo:
Implement socket options (think also about mdtPortConfig)
Definition at line 33 of file mdtPortThreadHelperSocket.cpp.
mdtPortThreadHelperSocket::~mdtPortThreadHelperSocket ()
Destructor.
Definition at line 53 of file mdtPortThreadHelperSocket.cpp.
Member Function Documentation
void mdtPortThreadHelperSocket::connected () signal
Emitted when internal socket notified that it is connected, and when we are ready.
Referenced by setSocket().
void mdtPortThreadHelperSocket::connectToHost ()
Connect to host set during setSocket()
Precondition
port must be set with mdtPortThreadHelper::setPort()
socket must be set with setSocket()
Definition at line 104 of file mdtPortThreadHelperSocket.cpp.
References mdtPortThreadHelper::pvPort.
void mdtPortThreadHelperSocket::setSocket (QTcpSocket * socket)
Set socket.
Take some parameters in port and port's config and make all needed signal/slot connections.
Parameters that are used by port's config are:
connectTimeout
connectMaxTry
readTimeout
writeTimeout
See mdtPortConfig for details.
Port's mutex is not handled by this method, it should be locked before call.
Precondition
socket must be a valid pointer.
port must be set with mdtPortThreadHelper::setPort().
Definition at line 58 of file mdtPortThreadHelperSocket.cpp.
References mdtAbstractPort::config(), connected(), mdtPortConfig::connectMaxTry(), mdtPortConfig::connectTimeout(), mdtTcpSocket::peerName(), mdtTcpSocket::peerPort(), mdtPortThreadHelper::pvPort, mdtPortConfig::readTimeout(), and mdtPortConfig::writeTimeout().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortThreadHelperSocket.h
src/mdtport/mdtPortThreadHelperSocket.cpp