Multi diag tools: mdtState Class Reference
mdtState Class Reference
Representation of a state in mdtStateMachine.
#include <mdtState.h>
Signals
void entered (mdtState *state)
Emited each time state was enterd.
Public Member Functions
mdtState (int id, QState *parent=0)
Constructor.
~mdtState ()
Destructor.
void setId (int id)
Set state ID.
int id () const
Get ID.
void setText (const QString &text)
Set text of the state.
QString text () const
Get text of the state.
void setLedColorId (int colorId)
Set LED color ID.
int ledColorId () const
Get LED color ID.
void setLedOn (bool on)
Set LED ON state.
bool ledIsOn () const
Get LED ON state.
void setNotifyEnteredToUi (bool notify)
Set notifyEnteredToUi flag.
bool notifyEnteredToUi () const
Get notifyEnteredToUi flag.
Detailed Description
Representation of a state in mdtStateMachine.
This class is based on QState, and add some properties.
See Also
mdtStateMachine
Definition at line 33 of file mdtState.h.
Constructor & Destructor Documentation
mdtState::mdtState (int id, QState * parent = 0)
Constructor.
Will set given id, let a empty text and set notifyEnteredToUi flag false.
Definition at line 26 of file mdtState.cpp.
References entered(), and id().
mdtState::~mdtState ()
Destructor.
Definition at line 37 of file mdtState.cpp.
Member Function Documentation
void mdtState::entered (mdtState * state) signal
Emited each time state was enterd.
Note: this signal is used by mdtStateMachine and should not be used directly.
Definition at line 100 of file moc_mdtState.cxx.
Referenced by mdtState().
int mdtState::id () const
Get ID.
The id can typically be used with enums (STATE_READY, ...)
Definition at line 46 of file mdtState.cpp.
Referenced by mdtStateMachine::currentState(), mdtState(), mdtStateMachine::notifyCurrentState(), and setId().
int mdtState::ledColorId () const
Get LED color ID.
The color ID can, for example, be used with mdtLed color enum. It was choosen store this id in int format, because mdtLed is in mdtUtilsGui package (we not want to depend on it).
Definition at line 66 of file mdtState.cpp.
Referenced by mdtStateMachine::notifyCurrentState().
bool mdtState::ledIsOn () const
Get LED ON state.
Definition at line 76 of file mdtState.cpp.
Referenced by mdtStateMachine::notifyCurrentState().
bool mdtState::notifyEnteredToUi () const
Get notifyEnteredToUi flag.
If notifyEnteredToUi is true, mdtStateMachine will emit stateChangedForUi() signal each time this state was entered.
Definition at line 86 of file mdtState.cpp.
Referenced by mdtStateMachine::notifyCurrentState().
void mdtState::setId (int id)
Set state ID.
See Also
id()
Definition at line 41 of file mdtState.cpp.
References id().
void mdtState::setLedColorId (int colorId)
Set LED color ID.
See Also
ledColorId()
Definition at line 61 of file mdtState.cpp.
Referenced by mdtPortManagerStateMachine::buildConnectedSubMachine(), mdtPortManagerStateMachine::buildMainStateMachine(), and mdtPortManagerStateMachine::buildRunningSubMachine().
void mdtState::setLedOn (bool on)
Set LED ON state.
Definition at line 71 of file mdtState.cpp.
Referenced by mdtPortManagerStateMachine::buildConnectedSubMachine(), mdtPortManagerStateMachine::buildMainStateMachine(), and mdtPortManagerStateMachine::buildRunningSubMachine().
void mdtState::setNotifyEnteredToUi (bool notify)
Set notifyEnteredToUi flag.
See Also
notifyEnteredToUi()
Definition at line 81 of file mdtState.cpp.
Referenced by mdtPortManagerStateMachine::buildConnectedSubMachine(), mdtPortManagerStateMachine::buildMainStateMachine(), and mdtPortManagerStateMachine::buildRunningSubMachine().
void mdtState::setText (const QString & text)
Set text of the state.
Definition at line 51 of file mdtState.cpp.
References text().
Referenced by mdtPortManagerStateMachine::buildConnectedSubMachine(), mdtPortManagerStateMachine::buildMainStateMachine(), and mdtPortManagerStateMachine::buildRunningSubMachine().
QString mdtState::text () const
Get text of the state.
Definition at line 56 of file mdtState.cpp.
Referenced by mdtStateMachine::notifyCurrentState(), and setText().
The documentation for this class was generated from the following files:
src/mdtutils/mdtState.h
src/mdtutils/mdtState.cpp
src/mdtutils/moc_mdtState.cxx