Multi diag tools: mdtTtTestModel Class Reference
mdtTtTestModel Class Reference
Helper class for test model edition.
#include <mdtTtTestModel.h>
Public Member Functions
mdtTtTestModel (QObject *parent, QSqlDatabase db)
Constructor.
QString sqlForTestNodeSelection (const QVariant &testModelId) const
Get SQL statement for test node selection.
mdtTtTestModelData getTestModelData (const QVariant &testModelId, bool &ok)
Get test model data for given test model ID.
QList< QVariant > getListOfTestItemIdListByTestId (const QVariant &testId)
Get a list of test item IDs for given test ID.
QList< QVariant > getListOfUsedNodeIdListByTestId (const QVariant &testId)
Get a list of node IDs (database keys) for given test ID.
QList< QVariant > getListOfUnusedNodeUnitIdListByTestId (const QVariant &testId, const QVariant &type)
Get a list of unused node unit IDs for given test ID.
QVariant getNextSequenceNumber (const QVariant &testModelId)
Get next sequence number for a given test.
QList< QVariant > getTestNodeUnitSetupIdList (const QVariant &testId)
Get list of test node unit setup for given test ID.
bool addTestNode (const QVariant &testNodeId, const QVariant &testModelId)
Add a test node.
QList< QSqlRecord > getTestNodeDataList (const QVariant &testModelId, bool &ok)
Get a list of test node data for given test model ID.
bool removeTestNodes (const mdtSqlTableSelection &s)
Remove a test node.
bool removeTestModelItem (const QVariant &testModelItemId, bool removeSetupAndRoute, bool removeTestLinks, bool handleTransaction)
Remove a test model item.
bool removeTestModelItems (const mdtSqlTableSelection &s, bool removeSetupAndRoute, bool removeTestLinks)
Remove a list of test model items.
QList< QVariant > getTestLinkIdListForDutConnectionId (const QVariant &testCableId, const QVariant &dutConnectionId, bool &ok)
Get link ID list for given cable ID and DUT connection ID.
QVariant getTestConnectionId (const QVariant &testLinkId, const QVariant &dutConnectionId, bool &ok)
Get test connection ID list for given test link ID and DUT connection ID.
mdtTtTestModelItemRouteData buildRouteData (const QList< QVariant > &pathConnectionIdList, mdtClPathGraph &graph, bool &ok)
Build route data for given path ID list.
bool addRoutesToItemData (const QVariant &dutConnectionId1, const QVariant &dutConnectionId2, const mdtTtTestModelGenerationParameter &parameters, mdtTtTestModelItemData &itemData, mdtClPathGraph &graph, mdtClPathGraph &graphForShortDetection)
Search 2 path from given DUT connections and measure connections and add routes to item data.
bool generateTestModel (mdtTtTestModelGenerationParameter &parameters, mdtClPathGraph &graph)
Generate test items.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
template<typename T >
bool addRecordList (const QList< T > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField1, const QVariant &key1, const QString &matchField2, const QVariant &key2)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for test model edition.
Definition at line 76 of file mdtTtTestModel.h.
Constructor & Destructor Documentation
mdtTtTestModel::mdtTtTestModel (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 34 of file mdtTtTestModel.cpp.
Member Function Documentation
bool mdtTtTestModel::addRoutesToItemData (const QVariant & dutConnectionId1, const QVariant & dutConnectionId2, const mdtTtTestModelGenerationParameter & parameters, mdtTtTestModelItemData & itemData, mdtClPathGraph & graph, mdtClPathGraph & graphForShortDetection)
Search 2 path from given DUT connections and measure connections and add routes to item data.
Parameters
dutConnectionId1 First test connection
dutConnectionId2 Second test connection
parameters At least testCableId, measureConnexionIdA and measureConnexionIdB must be set
measureConnexionIdA ID of measure connection to witch to find path
measureConnexionIdB ID of other measure connection
testCableId ID of used test cable
itemData Routes will be added to itemData
graph Graph object.
graphForShortDetection Graph object - Will be altered.
Definition at line 425 of file mdtTtTestModel.cpp.
References mdtTtTestModelItemData::addRouteData(), buildRouteData(), mdtError::commit(), mdtTtBase::database(), mdtError::Error, getTestConnectionId(), getTestLinkIdListForDutConnectionId(), MDT_ERROR_SET_SRC, mdtTtTestModelItemRouteData::measureConnectionId(), mdtTtTestModelGenerationParameter::measureConnexionIdA, mdtTtTestModelGenerationParameter::measureConnexionIdB, mdtTtBase::pvLastError, mdtTtTestModelItemRouteData::setDutConnectionId(), mdtError::setError(), mdtError::setInformativeText(), mdtTtTestModelItemRouteData::setMeasureConnectionId(), mdtTtTestModelItemRouteData::setTestConnectionId(), mdtTtTestModelItemRouteData::setTestLinkId(), mdtTtTestModelItemRouteData::setupDataList(), and mdtTtTestModelGenerationParameter::testCableId.
Referenced by generateTestModel().
bool mdtTtTestModel::addTestNode (const QVariant & testNodeId, const QVariant & testModelId)
Add a test node.
Definition at line 233 of file mdtTtTestModel.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, and mdtSqlRecord::setValue().
mdtTtTestModelItemRouteData mdtTtTestModel::buildRouteData (const QList< QVariant > & pathConnectionIdList, mdtClPathGraph & graph, bool & ok)
Build route data for given path ID list.
Parameters
pathConnectionIdList List of connections (IDs) that represent the path from a test connection to a measure connection
Returns
Route data with setupDataList set. All other members are not touched (route ID, testModelItemId, ...)
Precondition
pathConnectionIdList must contain at least 2 connections
Definition at line 393 of file mdtTtTestModel.cpp.
References mdtSqlRecord::clearValues(), mdtTtBase::database(), mdtClPathGraph::getUserData(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtTtTestNodeUnitSetupData::setup(), and mdtSqlRecord::setValue().
Referenced by addRoutesToItemData().
bool mdtTtTestModel::generateTestModel (mdtTtTestModelGenerationParameter & parameters, mdtClPathGraph & graph)
Generate test items.
Parameters
parameters Setup for test model
graph Graph object. Cable list must allready be loaded (see mdtClPathGraph::loadLinkList())
Definition at line 548 of file mdtTtTestModel.cpp.
References mdtTtTestModelItem::addItem(), addRoutesToItemData(), mdtTtBase::beginTransaction(), mdtTtTestModelItemData::clearValues(), mdtTtBase::commitTransaction(), mdtClPathGraph::connectionsAreLinked(), mdtTtTestModelGenerationParameter::continuityExpectedValue, mdtTtBase::database(), mdtTtTestModelGenerationParameter::generateForNonLinkedConnections, getNextSequenceNumber(), mdtTtTestModelGenerationParameter::isolationExpectedValue, mdtTtBase::lastError(), mdtClPathGraph::lastError(), mdtSqlRecord::lastError(), mdtClPathGraph::loadLinkList(), mdtTtTestModelGenerationParameter::measureConnexionIdA, mdtTtTestModelGenerationParameter::measureConnexionIdB, mdtTtBase::pvLastError, mdtTtBase::rollbackTransaction(), mdtTtTestModelItemData::setup(), mdtTtTestModelGenerationParameter::testCableId, mdtTtTestModelItemRouteData::testLinkId(), mdtTtTestModelGenerationParameter::testModelId, and mdtTtTestModelGenerationParameter::testNodeId.
QList< QVariant > mdtTtTestModel::getListOfTestItemIdListByTestId (const QVariant & testId)
Get a list of test item IDs for given test ID.
Definition at line 81 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QList< QVariant > mdtTtTestModel::getListOfUnusedNodeUnitIdListByTestId (const QVariant & testId, const QVariant & type)
Get a list of unused node unit IDs for given test ID.
If given type is not null, only matching test node unit will be returned
Definition at line 133 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, getListOfUsedNodeIdListByTestId(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QList< QVariant > mdtTtTestModel::getListOfUsedNodeIdListByTestId (const QVariant & testId)
Get a list of node IDs (database keys) for given test ID.
Definition at line 105 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by getListOfUnusedNodeUnitIdListByTestId().
QVariant mdtTtTestModel::getNextSequenceNumber (const QVariant & testModelId)
Get next sequence number for a given test.
This method is used to create test items . It will get the highest sequence number existing for given testModelId, and return the next number .
Definition at line 178 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by generateTestModel().
QVariant mdtTtTestModel::getTestConnectionId (const QVariant & testLinkId, const QVariant & dutConnectionId, bool & ok)
Get test connection ID list for given test link ID and DUT connection ID.
Definition at line 373 of file mdtTtTestModel.cpp.
Referenced by addRoutesToItemData().
QList< QVariant > mdtTtTestModel::getTestLinkIdListForDutConnectionId (const QVariant & testCableId, const QVariant & dutConnectionId, bool & ok)
Get link ID list for given cable ID and DUT connection ID.
Definition at line 339 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setInformativeText().
Referenced by addRoutesToItemData().
mdtTtTestModelData mdtTtTestModel::getTestModelData (const QVariant & testModelId, bool & ok)
Get test model data for given test model ID.
Definition at line 59 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, and mdtError::setError().
QList< QSqlRecord > mdtTtTestModel::getTestNodeDataList (const QVariant & testModelId, bool & ok)
Get a list of test node data for given test model ID.
Data will contain fields from TestNode_tbl and VehicleType_tbl
Definition at line 247 of file mdtTtTestModel.cpp.
QList< QVariant > mdtTtTestModel::getTestNodeUnitSetupIdList (const QVariant & testId)
Get list of test node unit setup for given test ID.
Definition at line 205 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtTtTestModel::removeTestModelItem (const QVariant & testModelItemId, bool removeSetupAndRoute, bool removeTestLinks, bool handleTransaction)
Remove a test model item.
Parameters
testModelItemId ID of test model item to remove
removeSetupAndRoute If true, related items in TestNodeUnitSetup_tbl and TestModelItemRoute_tbl will be removed first.
removeTestLinks If true, related items in TestModelItem_TestLink_tbl will be removed first.
handleTransaction If true, transaction will be handled internally.
Definition at line 275 of file mdtTtTestModel.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::removeData(), and mdtTtBase::rollbackTransaction().
Referenced by removeTestModelItems().
bool mdtTtTestModel::removeTestModelItems (const mdtSqlTableSelection & s, bool removeSetupAndRoute, bool removeTestLinks)
Remove a list of test model items.
Definition at line 319 of file mdtTtTestModel.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtSqlTableSelection::data(), removeTestModelItem(), mdtTtBase::rollbackTransaction(), and mdtSqlTableSelection::rowCount().
bool mdtTtTestModel::removeTestNodes (const mdtSqlTableSelection & s)
Remove a test node.
Definition at line 270 of file mdtTtTestModel.cpp.
References mdtTtBase::removeData().
QString mdtTtTestModel::sqlForTestNodeSelection (const QVariant & testModelId) const
Get SQL statement for test node selection.
Will list all test nodes that are not currently assigned to given test model
Definition at line 39 of file mdtTtTestModel.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestModel.h
src/mdttools/mdttesttool/mdtTtTestModel.cpp