Multi diag tools: mdtErrorOutLogger Class Reference
mdtErrorOutLogger Class Reference
Put errors in the log file.
#include <mdtErrorOut.h>
Public Member Functions
mdtErrorOutLogger (QObject *parent=0)
~mdtErrorOutLogger ()
bool setLogFilePath (const QString &path)
Set the log file path.
QString logFilePath ()
Get log file path.
void putData (QString data)
Add a line to the log file.
void setLogFileMaxSize (qint64 maxSize)
Set the maximum log file size [Byte] before backup.
Detailed Description
Put errors in the log file.
Definition at line 119 of file mdtErrorOut.h.
Constructor & Destructor Documentation
mdtErrorOutLogger::mdtErrorOutLogger (QObject * parent = 0)
Definition at line 267 of file mdtErrorOut.cpp.
mdtErrorOutLogger::~mdtErrorOutLogger ()
Definition at line 276 of file mdtErrorOut.cpp.
Member Function Documentation
QString mdtErrorOutLogger::logFilePath ()
Get log file path.
Definition at line 317 of file mdtErrorOut.cpp.
Referenced by mdtErrorOut::logFile().
void mdtErrorOutLogger::putData (QString data)
Add a line to the log file.
Definition at line 328 of file mdtErrorOut.cpp.
Referenced by mdtErrorOut::addError().
void mdtErrorOutLogger::setLogFileMaxSize (qint64 maxSize)
Set the maximum log file size [Byte] before backup.
Definition at line 339 of file mdtErrorOut.cpp.
Referenced by mdtErrorOut::setLogFileMaxSize().
bool mdtErrorOutLogger::setLogFilePath (const QString & path)
Set the log file path.
Returns
True if file can be open for write, false else
Definition at line 291 of file mdtErrorOut.cpp.
Referenced by mdtErrorOut::init().
The documentation for this class was generated from the following files:
src/mdtutils/mdtErrorOut.h
src/mdtutils/mdtErrorOut.cpp