Multi diag tools: mdtAbstractPortSetupDialog Class Reference
mdtAbstractPortSetupDialog Class Reference abstract
Base class to build a port setup dialog.
#include <mdtAbstractPortSetupDialog.h>
Public Member Functions
mdtAbstractPortSetupDialog (QWidget *parent=0)
Constructor.
~mdtAbstractPortSetupDialog ()
Destructor.
void setPortManager (mdtPortManager *portManager)
Set the port manager.
mdtPortManager * portManager ()
Get port manager.
Protected Slots
void showStatusMessage (const QString &message, int timeout=0)
Used to show a message in status widget.
void showStatusMessage (const QString &message, const QString &details, int timeout=0)
Used to show a message and details in status widget.
Protected Member Functions
virtual void portManagerSet ()
Called by setPortManager()
virtual void setStatePortClosed ()=0
Set the PortClosed state.
virtual void setStateDisconnected ()=0
Set the Disconnected state.
virtual void setStateConnecting ()=0
Set the Connecting state.
virtual void setStatePortReady ()=0
Set the PortReady state.
virtual void setStateReady ()=0
Set the Ready state (called when connected to device)
virtual void setStateBusy ()=0
Set the Busy state.
virtual void setStateError ()=0
Set the Error state.
virtual bool applySetup ()=0
Apply setup.
void setHeaderWidget (QWidget *w)
Set the header widget.
void addOptionsTabWidget (QWidget *w, const QString &label)
Add a widget to the options tab.
void setOkButtonEnabled (bool enabled)
Enable/disable Ok button.
void setApplyButtonEnabled (bool enabled)
Enable/disable Apply button.
void setCancelButtonEnabled (bool enabled)
Enable/disable Cancel button.
Detailed Description
Base class to build a port setup dialog.
The first step before display a setup dialog is to set the port manager with setPortManager()
Definition at line 38 of file mdtAbstractPortSetupDialog.h.
Constructor & Destructor Documentation
mdtAbstractPortSetupDialog::mdtAbstractPortSetupDialog (QWidget * parent = 0)
Constructor.
Definition at line 29 of file mdtAbstractPortSetupDialog.cpp.
mdtAbstractPortSetupDialog::~mdtAbstractPortSetupDialog ()
Destructor.
Definition at line 44 of file mdtAbstractPortSetupDialog.cpp.
Member Function Documentation
void mdtAbstractPortSetupDialog::addOptionsTabWidget (QWidget * w, const QString & label) protected
Add a widget to the options tab.
Options tab is a QTabWidget
Definition at line 85 of file mdtAbstractPortSetupDialog.cpp.
Referenced by mdtModbusTcpPortSetupDialog::mdtModbusTcpPortSetupDialog(), and mdtSerialPortSetupDialog::mdtSerialPortSetupDialog().
virtual bool mdtAbstractPortSetupDialog::applySetup () protected pure virtual
Apply setup.
This method must be implemented in subclass.
When Ok or Apply button was clicked, this method will be called. Case of Ok button, if this method returns false, the setup dialog will not be closed.
mdtPortManager * mdtAbstractPortSetupDialog::portManager ()
Get port manager.
Precondition
A valid port manager must be set with setPortManager() befor calling this method.
Definition at line 59 of file mdtAbstractPortSetupDialog.cpp.
Referenced by setPortManager().
void mdtAbstractPortSetupDialog::portManagerSet () protected virtual
Called by setPortManager()
Defaul implementation does nothing
Definition at line 66 of file mdtAbstractPortSetupDialog.cpp.
Referenced by setPortManager().
void mdtAbstractPortSetupDialog::setApplyButtonEnabled (bool enabled) protected
Enable/disable Apply button.
Definition at line 102 of file mdtAbstractPortSetupDialog.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, MDT_GUI_ERROR, and mdtError::Warning.
void mdtAbstractPortSetupDialog::setCancelButtonEnabled (bool enabled) protected
Enable/disable Cancel button.
Definition at line 114 of file mdtAbstractPortSetupDialog.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, MDT_GUI_ERROR, and mdtError::Warning.
void mdtAbstractPortSetupDialog::setHeaderWidget (QWidget * w) protected
Set the header widget.
The header widget is on top of setup dialog.
Precondition
w must be a valid pointer.
Definition at line 70 of file mdtAbstractPortSetupDialog.cpp.
Referenced by mdtModbusTcpPortSetupDialog::mdtModbusTcpPortSetupDialog(), and mdtSerialPortSetupDialog::mdtSerialPortSetupDialog().
void mdtAbstractPortSetupDialog::setOkButtonEnabled (bool enabled) protected
Enable/disable Ok button.
Definition at line 90 of file mdtAbstractPortSetupDialog.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, MDT_GUI_ERROR, and mdtError::Warning.
void mdtAbstractPortSetupDialog::setPortManager (mdtPortManager * portManager)
Set the port manager.
Port manager's stateChanged() signal will be connected to setStateFromPortManager() slot.
Precondition
portManager must be a valid pointer.
Definition at line 48 of file mdtAbstractPortSetupDialog.cpp.
References mdtPortManager::notifyCurrentState(), portManager(), and portManagerSet().
Referenced by mdtSerialPortSetupDialog::setPortManager().
virtual void mdtAbstractPortSetupDialog::setStateBusy () protected pure virtual
Set the Busy state.
This method must be implemented in subclass. Goal is to keep GUI coherent to current state (f.ex. disable/enable some buttons).
virtual void mdtAbstractPortSetupDialog::setStateConnecting () protected pure virtual
Set the Connecting state.
This method must be implemented in subclass. Goal is to keep GUI coherent to current state (f.ex. disable/enable some buttons).
virtual void mdtAbstractPortSetupDialog::setStateDisconnected () protected pure virtual
Set the Disconnected state.
This method must be implemented in subclass. Goal is to keep GUI coherent to current state (f.ex. disable/enable some buttons).
virtual void mdtAbstractPortSetupDialog::setStateError () protected pure virtual
Set the Error state.
This method must be implemented in subclass. Goal is to keep GUI coherent to current state (f.ex. disable/enable some buttons).
virtual void mdtAbstractPortSetupDialog::setStatePortClosed () protected pure virtual
Set the PortClosed state.
This method must be implemented in subclass. Goal is to keep GUI coherent to current state (f.ex. disable/enable some buttons).
virtual void mdtAbstractPortSetupDialog::setStatePortReady () protected pure virtual
Set the PortReady state.
This method must be implemented in subclass. Goal is to keep GUI coherent to current state (f.ex. disable/enable some buttons).
virtual void mdtAbstractPortSetupDialog::setStateReady () protected pure virtual
Set the Ready state (called when connected to device)
This method must be implemented in subclass. Goal is to keep GUI coherent to current state (f.ex. disable/enable some buttons).
void mdtAbstractPortSetupDialog::showStatusMessage (const QString & message, int timeout = 0) protected slot
Used to show a message in status widget.
Parameters
message Message to show
timeout If > 0, message will be cleared after timeout [ms]
Definition at line 126 of file mdtAbstractPortSetupDialog.cpp.
References mdtPortStatusWidget::showMessage().
void mdtAbstractPortSetupDialog::showStatusMessage (const QString & message, const QString & details, int timeout = 0) protected slot
Used to show a message and details in status widget.
Parameters
message Message to show
details Details to show
timeout If > 0, message will be cleared after timeout [ms]
Definition at line 131 of file mdtAbstractPortSetupDialog.cpp.
References mdtPortStatusWidget::showMessage().
The documentation for this class was generated from the following files:
src/mdtport/mdtAbstractPortSetupDialog.h
src/mdtport/mdtAbstractPortSetupDialog.cpp