Multi diag tools: mdtSqlDatabaseManager Class Reference
mdtSqlDatabaseManager Class Reference
Helper class to create and open (connect to) database.
#include <mdtSqlDatabaseManager.h>
Public Types
enum createMode_t { OverwriteExisting, KeepExisting, FailIfExists, AskUserIfExists }
Creation mode.
Public Member Functions
mdtSqlDatabaseManager (QObject *parent=0)
Constructor.
~mdtSqlDatabaseManager ()
Destructor.
void setDatabase (QSqlDatabase db)
Set a allready existing database.
QSqlDatabase database ()
Get current database object.
bool setForeignKeysEnabled (bool enable)
Enable/disable foreing keys constraint.
void setForDialogParentWidget (QWidget *widget)
Set the parent widget for dialogs.
mdtError lastError () const
Get last error.
QFileInfo chooseDatabaseSqlite (const QDir &startDirectory=QDir())
Let the user choose a Sqlite database file.
bool openDatabaseSqlite (const QFileInfo &fileInfo, const QString &connectionName=QString())
Open a sqlite database.
bool openDatabaseSqlite (const QDir &startDirectory=QDir(), const QString &connectionName=QString())
Open a sqlite database.
bool createDatabaseSqlite (const QDir &startDirectory=QDir(), const QString &connectionName=QString())
Ask the user to give a path and create a Sqlite database.
bool createDatabaseSqlite (const QFileInfo &fileInfo, createMode_t createMode, const QString &connectionName=QString())
Create a Sqlite database.
bool createTable (mdtSqlSchemaTable &table, createMode_t createMode)
Create a table.
Detailed Description
Helper class to create and open (connect to) database.
QSqlDatabase allready offers needed methods to open a database. This helper class use it, but gives some methods witch will deal with common problems. For example, with Sqlite, checking if a file exists, what to do if it exists and we are creating a new database, ...
Definition at line 41 of file mdtSqlDatabaseManager.h.
Member Enumeration Documentation
enum mdtSqlDatabaseManager::createMode_t
Creation mode.
Enumerator
OverwriteExisting
If file/database/table allready exists, it will be overwritten
KeepExisting
If file/database/table allready exists, it will simply be open
FailIfExists
If file/database/table allready exists, create method will fail
AskUserIfExists
If file/database/table allready exists, a dialog box will ask the user if it must be overwritten or not
Definition at line 49 of file mdtSqlDatabaseManager.h.
Constructor & Destructor Documentation
mdtSqlDatabaseManager::mdtSqlDatabaseManager (QObject * parent = 0)
Constructor.
Definition at line 32 of file mdtSqlDatabaseManager.cpp.
mdtSqlDatabaseManager::~mdtSqlDatabaseManager ()
Destructor.
Definition at line 38 of file mdtSqlDatabaseManager.cpp.
Member Function Documentation
QFileInfo mdtSqlDatabaseManager::chooseDatabaseSqlite (const QDir & startDirectory = QDir())
Let the user choose a Sqlite database file.
The startDirectory is used as directory to go when displaying the file dialog
Definition at line 108 of file mdtSqlDatabaseManager.cpp.
Referenced by mdtTtDatabaseSchema::importDatabase(), and openDatabaseSqlite().
bool mdtSqlDatabaseManager::createDatabaseSqlite (const QDir & startDirectory = QDir(), const QString & connectionName = QString())
Ask the user to give a path and create a Sqlite database.
The startDirectory is used as directory to go when displaying the file dialog
Definition at line 219 of file mdtSqlDatabaseManager.cpp.
References mdtError::informativeText(), mdtError::levelIcon(), OverwriteExisting, mdtError::systemErrorString(), and mdtError::text().
Referenced by mdtDataTableManager::createDataSet(), and mdtTtDatabaseSchema::createSchemaSqlite().
bool mdtSqlDatabaseManager::createDatabaseSqlite (const QFileInfo & fileInfo, createMode_t createMode, const QString & connectionName = QString())
Create a Sqlite database.
Note: a open connection to database will not be closed by this method. The caller must close existing connection to target database explicitly before overwrite the same.
Definition at line 253 of file mdtSqlDatabaseManager.cpp.
References AskUserIfExists, mdtError::commit(), mdtError::Error, FailIfExists, KeepExisting, MDT_ERROR_SET_SRC, OverwriteExisting, mdtError::setError(), setForeignKeysEnabled(), mdtError::setInformativeText(), and mdtError::setSystemError().
bool mdtSqlDatabaseManager::createTable (mdtSqlSchemaTable & table, createMode_t createMode)
Create a table.
Will also setup database specific thing (like driver name) on table.
Definition at line 391 of file mdtSqlDatabaseManager.cpp.
References AskUserIfExists, mdtError::commit(), mdtError::Error, FailIfExists, KeepExisting, MDT_ERROR_SET_SRC, OverwriteExisting, mdtSqlSchemaTable::setDriverName(), mdtError::setError(), mdtError::setSystemError(), mdtSqlSchemaTable::sqlForCreateTable(), mdtSqlSchemaTable::sqlForDropTable(), mdtSqlSchemaTable::tableName(), and mdtError::Warning.
Referenced by mdtDataTableManager::copyTable(), and mdtDataTableManager::createDataSet().
QSqlDatabase mdtSqlDatabaseManager::database ()
Get current database object.
Definition at line 48 of file mdtSqlDatabaseManager.cpp.
Referenced by mdtTtDatabaseSchema::checkSchema(), mdtDataTableManager::close(), mdtTtDatabaseSchema::createSchemaSqlite(), mdtDataTableManager::database(), and mdtTtDatabaseSchema::importDatabase().
mdtError mdtSqlDatabaseManager::lastError () const
Get last error.
Definition at line 103 of file mdtSqlDatabaseManager.cpp.
Referenced by mdtDataTableManager::copyTable(), mdtDataTableManager::createDataSet(), and mdtTtDatabaseSchema::importDatabase().
bool mdtSqlDatabaseManager::openDatabaseSqlite (const QFileInfo & fileInfo, const QString & connectionName = QString())
Open a sqlite database.
Definition at line 127 of file mdtSqlDatabaseManager.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), setForeignKeysEnabled(), mdtError::setInformativeText(), and mdtError::setSystemError().
Referenced by openDatabaseSqlite().
bool mdtSqlDatabaseManager::openDatabaseSqlite (const QDir & startDirectory = QDir(), const QString & connectionName = QString())
Open a sqlite database.
Will ask the user to choose a file and try to open it . The startDirectory is used as directory to go when displaying the file dialog .
Definition at line 201 of file mdtSqlDatabaseManager.cpp.
References chooseDatabaseSqlite(), mdtError::clear(), and openDatabaseSqlite().
void mdtSqlDatabaseManager::setDatabase (QSqlDatabase db)
Set a allready existing database.
Definition at line 42 of file mdtSqlDatabaseManager.cpp.
Referenced by mdtDataTableManager::copyTable(), and mdtDataTableManager::mdtDataTableManager().
void mdtSqlDatabaseManager::setForDialogParentWidget (QWidget * widget)
Set the parent widget for dialogs.
In interactive mode, some dialogs will be displayed. If widget is set, dialogs will be created as parent of it.
Definition at line 98 of file mdtSqlDatabaseManager.cpp.
bool mdtSqlDatabaseManager::setForeignKeysEnabled (bool enable)
Enable/disable foreing keys constraint.
Definition at line 53 of file mdtSqlDatabaseManager.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), and mdtError::setSystemError().
Referenced by createDatabaseSqlite(), mdtTtDatabaseSchema::importDatabase(), and openDatabaseSqlite().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlDatabaseManager.h
src/mdtdatabase/mdtSqlDatabaseManager.cpp