Multi diag tools: mdtSqlDialog Class Reference
mdtSqlDialog Class Reference
Dialog for a database table view/editor.
#include <mdtSqlDialog.h>
Public Slots
void accept ()
Overloads QDialog::accept()
void reject ()
Overloads QDialog::reject()
Public Member Functions
mdtSqlDialog (QWidget *parent=0)
Constructor.
~mdtSqlDialog ()
Destructor.
void setSqlForm (mdtSqlForm *form)
Set the SQL form.
void enableEdition ()
Enable edition.
void disableEdition ()
Disable edition.
Detailed Description
Dialog for a database table view/editor.
This class offers some functionnality for the GUI part.
It was designed to work with a subclass of mdtSqlForm .
Definition at line 44 of file mdtSqlDialog.h.
Constructor & Destructor Documentation
mdtSqlDialog::mdtSqlDialog (QWidget * parent = 0)
Constructor.
Definition at line 32 of file mdtSqlDialog.cpp.
References accept(), and reject().
mdtSqlDialog::~mdtSqlDialog ()
Destructor.
Definition at line 51 of file mdtSqlDialog.cpp.
Member Function Documentation
void mdtSqlDialog::accept () slot
Overloads QDialog::accept()
Definition at line 88 of file mdtSqlDialog.cpp.
References mdtAbstractSqlWidget::allDataAreSaved(), and mdtSqlForm::mainSqlWidget().
Referenced by mdtSqlDialog().
void mdtSqlDialog::disableEdition ()
Disable edition.
See Also
enableEdition()
Definition at line 82 of file mdtSqlDialog.cpp.
void mdtSqlDialog::enableEdition ()
Enable edition.
Will add save/revert buttons
Precondition
Form must be set with setSqlForm() before call this method.
Definition at line 68 of file mdtSqlDialog.cpp.
References mdtSqlForm::mainSqlWidget().
void mdtSqlDialog::reject () slot
Overloads QDialog::reject()
Definition at line 96 of file mdtSqlDialog.cpp.
References mdtAbstractSqlWidget::allDataAreSaved(), and mdtSqlForm::mainSqlWidget().
Referenced by mdtSqlDialog().
void mdtSqlDialog::setSqlForm (mdtSqlForm * form)
Set the SQL form.
Note: because form will be reparented, it will be deleted when this dialog is destroyed !
Precondition
form must be a valid pointer .
Definition at line 55 of file mdtSqlDialog.cpp.
References mdtSqlForm::start().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlDialog.h
src/mdtdatabase/mdtSqlDialog.cpp