Multi diag tools: mdtTtTestModelContinuityTestGeneratorHelper Class Reference
mdtTtTestModelContinuityTestGeneratorHelper Class Reference
Helper class for continuity test generation.
#include <mdtTtTestModel.h>
Public Member Functions
mdtTtTestModelContinuityTestGeneratorHelper (mdtTtTestModel *tm)
Constructor.
~mdtTtTestModelContinuityTestGeneratorHelper ()
Destructor.
QList< QVariant > getRelatedTestConnectionIdList (const QVariant &testCableId, const QVariant &fromTestConnectionId, mdtClPathGraph &graph, bool &ok)
Get related connections.
bool queueRelatedConnectionToSolved ()
Tell if a related test connection must be queued to solved connections once processed.
action_t actionOnShortInTestNode ()
Return Fail.
QVariant expectedValue ()
Get expected value.
QVariant valueUnit ()
Get value unit.
Public Member Functions inherited from mdtTtTestModelAbstractGeneratorHelper
mdtTtTestModelAbstractGeneratorHelper (mdtTtTestModel *tm)
Constructor.
virtual ~mdtTtTestModelAbstractGeneratorHelper ()
Destructor.
virtual QList< QVariant > relaysToIgnoreIdList ()
Get a list of test node unit ID of relays to not use.
virtual QVariant getDesignationEN (const QVariant &fromTestLinkId, const QVariant &toTestLinkId)
Get a string for the test model item's designation.
QVariant getDutConnectionId (const QVariant &testCableId, const QVariant &testConnectionId, bool &ok)
Get DUT connection ID for given test connection ID.
QVariant getTestConnectionId (const QVariant &testCableId, const QVariant &dutConnectionId, bool &ok, const QVariant &testConnectionToExclude=QVariant())
Get test connection ID for given DUT connection ID.
mdtError lastError () const
Get last error.
Additional Inherited Members
Public Types inherited from mdtTtTestModelAbstractGeneratorHelper
enum action_t { Fail, IgnoreCurrentItem }
Action.
Protected Attributes inherited from mdtTtTestModelAbstractGeneratorHelper
mdtTtTestModel * pvTestModel
mdtError pvLastError
Detailed Description
Helper class for continuity test generation.
Definition at line 117 of file mdtTtTestModel.h.
Constructor & Destructor Documentation
mdtTtTestModelContinuityTestGeneratorHelper::mdtTtTestModelContinuityTestGeneratorHelper (mdtTtTestModel * tm)
Constructor.
Definition at line 186 of file mdtTtTestModel.cpp.
mdtTtTestModelContinuityTestGeneratorHelper::~mdtTtTestModelContinuityTestGeneratorHelper ()
Destructor.
Definition at line 191 of file mdtTtTestModel.cpp.
Member Function Documentation
mdtTtTestModelAbstractGeneratorHelper::action_t mdtTtTestModelContinuityTestGeneratorHelper::actionOnShortInTestNode () virtual
Return Fail.
Implements mdtTtTestModelAbstractGeneratorHelper.
Definition at line 236 of file mdtTtTestModel.cpp.
References mdtTtTestModelAbstractGeneratorHelper::Fail.
QVariant mdtTtTestModelContinuityTestGeneratorHelper::expectedValue () virtual
Get expected value.
Return 0.0
Implements mdtTtTestModelAbstractGeneratorHelper.
Definition at line 241 of file mdtTtTestModel.cpp.
QList< QVariant > mdtTtTestModelContinuityTestGeneratorHelper::getRelatedTestConnectionIdList (const QVariant & testCableId, const QVariant & fromTestConnectionId, mdtClPathGraph & graph, bool & ok) virtual
Get related connections.
Will get the DUT connection that is linked to given fromTestConnectionId, then search about linked DUT connections. Finally, a list of test connection is built for each DUT connection found.
Parameters
testCableId ID of test cable (TestCable_tbl) to use.
fromTestConnectionId Test connection from witch to start.
graph Graph object. Cable list must allready be loaded (see mdtClPathGraph::loadLinkList())
ok Will be set to true on success, false else.
Implements mdtTtTestModelAbstractGeneratorHelper.
Definition at line 195 of file mdtTtTestModel.cpp.
References mdtError::commit(), mdtError::Error, mdtTtTestModelAbstractGeneratorHelper::getDutConnectionId(), mdtClPathGraph::getLinkedConnectionIdList(), mdtTtTestModelAbstractGeneratorHelper::getTestConnectionId(), MDT_ERROR_SET_SRC, mdtTtTestModelAbstractGeneratorHelper::pvLastError, mdtTtTestModelAbstractGeneratorHelper::pvTestModel, and mdtError::setError().
bool mdtTtTestModelContinuityTestGeneratorHelper::queueRelatedConnectionToSolved () virtual
Tell if a related test connection must be queued to solved connections once processed.
Implements mdtTtTestModelAbstractGeneratorHelper.
Definition at line 231 of file mdtTtTestModel.cpp.
QVariant mdtTtTestModelContinuityTestGeneratorHelper::valueUnit () virtual
Get value unit.
Return "Ohm"
Implements mdtTtTestModelAbstractGeneratorHelper.
Definition at line 246 of file mdtTtTestModel.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestModel.h
src/mdttools/mdttesttool/mdtTtTestModel.cpp