Multi diag tools: mdtFieldMapField Class Reference
mdtFieldMapField Class Reference
Container for information about field in field map.
#include <mdtFieldMapField.h>
Public Member Functions
mdtFieldMapField ()
Constructor.
void setIndex (int value)
Set column index.
int index () const
Get column index.
void setDisplayText (const QString &text)
Set text that will be displayed in header.
QString displayText () const
Get text that will be displayed in header.
void setName (const QString &name)
Set field name.
QString name () const
Get field name.
void setSqlField (const QSqlField &field)
Set SQL field.
QSqlField sqlField () const
Get SQL field.
QSqlField & sqlField ()
Get SQL field object for update.
Static Public Member Functions
static bool strContainsIllegalString (const QString &str)
Check if str contains a illegal string.
static QString getFieldName (const QString &name, const QString &replaceBy="_")
Get a field name with no illegal strings.
Detailed Description
Container for information about field in field map.
Internally, in QSqlField object contains most of field attributes. Those not aviable in QSqlField are also stored separatly.
Definition at line 33 of file mdtFieldMapField.h.
Constructor & Destructor Documentation
mdtFieldMapField::mdtFieldMapField ()
Constructor.
Definition at line 26 of file mdtFieldMapField.cpp.
Member Function Documentation
QString mdtFieldMapField::displayText () const
Get text that will be displayed in header.
Definition at line 78 of file mdtFieldMapField.cpp.
Referenced by mdtFieldMapItem::destinationFieldDisplayText(), mdtFieldMap::destinationHeader(), mdtFieldListEditionDialog::setAvailableFields(), mdtFieldMapItemDialog::setDestinationFields(), mdtFieldMapItemDialog::setSourceFields(), mdtFieldMapItem::sourceFieldDisplayText(), and mdtFieldMap::sourceHeader().
QString mdtFieldMapField::getFieldName (const QString & name, const QString & replaceBy = "_") static
Get a field name with no illegal strings.
Definition at line 121 of file mdtFieldMapField.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, name(), strContainsIllegalString(), and mdtError::Warning.
Referenced by mdtDataTableManager::importFromCsvFile(), mdtFieldMap::setDestinationFieldsByDisplayTexts(), and mdtFieldMap::setSourceFieldsByDisplayTexts().
int mdtFieldMapField::index () const
Get column index.
Definition at line 68 of file mdtFieldMapField.cpp.
Referenced by mdtFieldMapItem::destinationData(), mdtFieldMapItem::destinationFieldIndex(), mdtFieldMap::notMappedDestinationFields(), mdtFieldMap::notMappedSourceFields(), mdtFieldListEditionDialog::setAvailableFields(), and mdtFieldMapItem::sourceFieldIndex().
QString mdtFieldMapField::name () const
Get field name.
Comes from sqlField
Definition at line 88 of file mdtFieldMapField.cpp.
Referenced by mdtFieldMapItem::destinationFieldName(), mdtFieldMap::destinationHeader(), getFieldName(), mdtFieldMap::notMappedDestinationFields(), mdtFieldMap::notMappedSourceFields(), mdtFieldListEditionDialog::setAvailableFields(), mdtFieldMapItemDialog::setDestinationFields(), mdtFieldMapItemDialog::setSourceFields(), mdtFieldMapItem::sourceFieldName(), and mdtFieldMap::sourceHeader().
void mdtFieldMapField::setDisplayText (const QString & text)
Set text that will be displayed in header.
Definition at line 73 of file mdtFieldMapField.cpp.
Referenced by mdtFieldMapItem::setDestinationFieldDisplayText(), mdtFieldMap::setDestinationFieldsByDisplayTexts(), mdtFieldMapItem::setSourceFieldDisplayText(), and mdtFieldMap::setSourceFieldsByDisplayTexts().
void mdtFieldMapField::setIndex (int value)
Set column index.
Definition at line 63 of file mdtFieldMapField.cpp.
Referenced by mdtFieldMapItem::setDestinationFieldIndex(), mdtFieldMap::setDestinationFieldsByDisplayTexts(), mdtFieldMapItem::setSourceFieldIndex(), and mdtFieldMap::setSourceFieldsByDisplayTexts().
void mdtFieldMapField::setName (const QString & name)
Set field name.
Is stored in sqlField
Definition at line 83 of file mdtFieldMapField.cpp.
Referenced by mdtFieldMapItem::setDestinationFieldName(), mdtFieldMap::setDestinationFieldsByDisplayTexts(), mdtFieldMapItem::setSourceFieldName(), and mdtFieldMap::setSourceFieldsByDisplayTexts().
void mdtFieldMapField::setSqlField (const QSqlField & field)
Set SQL field.
Definition at line 93 of file mdtFieldMapField.cpp.
Referenced by mdtDataTableManager::copyTable().
QSqlField mdtFieldMapField::sqlField () const
Get SQL field.
Definition at line 98 of file mdtFieldMapField.cpp.
Referenced by mdtFieldMapItem::dataType(), mdtFieldMapItem::destinationData(), mdtFieldMapItem::setDataType(), mdtFieldMap::setDestinationFieldsByDisplayTexts(), and mdtFieldMap::setSourceFieldsByDisplayTexts().
QSqlField & mdtFieldMapField::sqlField ()
Get SQL field object for update.
Definition at line 103 of file mdtFieldMapField.cpp.
bool mdtFieldMapField::strContainsIllegalString (const QString & str) static
Check if str contains a illegal string.
Definition at line 108 of file mdtFieldMapField.cpp.
Referenced by getFieldName().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtFieldMapField.h
src/mdtutilsgui/mdtFieldMapField.cpp