Multi diag tools: mdtPortManagerStateMachine Class Reference
mdtPortManagerStateMachine Class Reference
State machine for port manager.
#include <mdtPortManagerStateMachine.h>
Public Member Functions
mdtPortManagerStateMachine (QObject *parent=0)
Constructor.
~mdtPortManagerStateMachine ()
Destructor.
void buildMainStateMachine (mdtPortManager *portManager)
Build main state machine.
Public Member Functions inherited from mdtStateMachine
mdtStateMachine (QObject *parent=0)
Constructor.
virtual ~mdtStateMachine ()
Destructor.
int currentState () const
Get current state.
bool waitOnState (int state, int timeout=-1)
Wait until a state is reached.
bool waitOnOneState (const QVector< int > &states, int timeout=-1)
Wait until a state is reached.
void notifyCurrentState ()
Notify current state.
Protected Member Functions
void buildRunningSubMachine (mdtPortManager *portManager, mdtState *parentState)
Build the Running sub machine.
void buildConnectedSubMachine (mdtPortManager *portManager, mdtState *parentState)
Build the Connected sub machine.
Additional Inherited Members
Signals inherited from mdtStateMachine
void stateChanged (int id)
Emitted each time the state changed.
void stateChangedForUi (int id, const QString &text, int ledColorId, bool ledIsOn)
Emitted only if a state that must be notified is entered.
Detailed Description
State machine for port manager.
A port manager can receive events form different objects, like threads and main application.
This class helps port manager to keep a coherent state and react only on allowed events regarding current state.
Definition at line 39 of file mdtPortManagerStateMachine.h.
Constructor & Destructor Documentation
mdtPortManagerStateMachine::mdtPortManagerStateMachine (QObject * parent = 0)
Constructor.
Will build the state machine by calling buildMainStateMachine()
Definition at line 26 of file mdtPortManagerStateMachine.cpp.
mdtPortManagerStateMachine::~mdtPortManagerStateMachine ()
Destructor.
Definition at line 46 of file mdtPortManagerStateMachine.cpp.
Member Function Documentation
void mdtPortManagerStateMachine::buildConnectedSubMachine (mdtPortManager * portManager, mdtState * parentState) protected
Build the Connected sub machine.
Precondition
portManager must be a valid pointer
parentState must be a valid pointer
Definition at line 145 of file mdtPortManagerStateMachine.cpp.
References mdtPortManager::Busy, mdtLed::Green, mdtLed::Orange, mdtPortManager::Ready, mdtState::setLedColorId(), mdtState::setLedOn(), mdtState::setNotifyEnteredToUi(), and mdtState::setText().
Referenced by buildRunningSubMachine().
void mdtPortManagerStateMachine::buildMainStateMachine (mdtPortManager * portManager)
Build main state machine.
Precondition
portManager must be a valid pointer
Definition at line 50 of file mdtPortManagerStateMachine.cpp.
References buildRunningSubMachine(), mdtLed::Green, mdtPortManager::PortClosed, mdtPortManager::PortError, mdtLed::Red, mdtPortManager::Running, mdtState::setLedColorId(), mdtState::setLedOn(), mdtState::setNotifyEnteredToUi(), mdtState::setText(), mdtPortManager::Starting, mdtStateMachine::stateChanged(), mdtStateMachine::stateChangedForUi(), mdtPortManager::Stopped, mdtPortManager::Stopping, and mdtStateMachine::waitOnState().
Referenced by mdtPortManager::mdtPortManager().
void mdtPortManagerStateMachine::buildRunningSubMachine (mdtPortManager * portManager, mdtState * parentState) protected
Build the Running sub machine.
Precondition
portManager must be a valid pointer
parentState must be a valid pointer
Definition at line 106 of file mdtPortManagerStateMachine.cpp.
References buildConnectedSubMachine(), mdtPortManager::Connected, mdtPortManager::Connecting, mdtPortManager::Disconnected, mdtLed::Green, mdtLed::Orange, mdtPortManager::PortReady, mdtState::setLedColorId(), mdtState::setLedOn(), mdtState::setNotifyEnteredToUi(), and mdtState::setText().
Referenced by buildMainStateMachine().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortManagerStateMachine.h
src/mdtport/mdtPortManagerStateMachine.cpp