Multi diag tools: mdtFileCopier Class Reference
mdtFileCopier Class Reference
Helper class for file copy.
#include <mdtFileCopier.h>
Public Slots
void cancelCopy ()
Cancel running copy (used internally for progress dialog)
Signals
void finished (bool success)
Emitted when copy process is done.
void newProgressRange (int min, int max)
Emitted when new progress range is set (used internally for proegress dialog)
void newProgressValue (int value)
Emitted when new progress value is set (used internally for proegress dialog)
void newProgressLabelText (const QString &text)
Emitted when new progress label text is set (used internally for proegress dialog)
void copyEnded (const QString &failedCopies, const QString &informativeText=QString())
Emitted when copy is ended or aborted (used internally to display copy result)
Public Member Functions
mdtFileCopier (QObject *parent=0)
~mdtFileCopier ()
void setDirectDestOverwrite (bool directOverwrite)
Permit direct destination overwrite.
void setDefaultSetup ()
Set the default setup.
void addCopy (const QString &srcFilePath, const QString &destFilePath, bool syncAfterCopy=false, bool checkAfterCopy=false)
Add a source and destination file path to copy.
bool startCopy ()
Start the copy.
bool waitFinished ()
Wait until copies are done.
void setTestMode (bool enable)
If set true, message boxes will not be displayed, and some default decisions will be taken.
Detailed Description
Helper class for file copy.
When files must be copied in a GUI application, some common situation must be handled:
Display a message box when source file not exists, or cannot be read
Ask the user if allready existing destination file must be overwritten
Display a progress bar during a long copy
...
This class was made to simplify this process.
The copy is done in a separated thread. Notes:
For a simple and efficient copy, it's better to use system provided functions, QFile or others.
If a file exists at destination, user will be asked about what to do. But, the ask operation, and the effective copy are not a atomic operation. So it can happen that another process creates the destination, and that file is then overwritten during copy !
Definition at line 53 of file mdtFileCopier.h.
Constructor & Destructor Documentation
mdtFileCopier::mdtFileCopier (QObject * parent = 0)
Definition at line 40 of file mdtFileCopier.cpp.
References cancelCopy(), copyEnded(), newProgressLabelText(), newProgressRange(), newProgressValue(), and setDefaultSetup().
mdtFileCopier::~mdtFileCopier ()
Definition at line 67 of file mdtFileCopier.cpp.
Member Function Documentation
void mdtFileCopier::addCopy (const QString & srcFilePath, const QString & destFilePath, bool syncAfterCopy = false, bool checkAfterCopy = false)
Add a source and destination file path to copy.
At this point, the copy is enqueued. To process copy, call startCopy().
See Also
startCopy()
Definition at line 88 of file mdtFileCopier.cpp.
References mdtFileCopierItem::setCheckAfterCopy(), and mdtFileCopierItem::setSyncAfterCopy().
void mdtFileCopier::cancelCopy () slot
Cancel running copy (used internally for progress dialog)
Definition at line 328 of file mdtFileCopier.cpp.
References finished().
Referenced by mdtFileCopier().
void mdtFileCopier::copyEnded (const QString & failedCopies, const QString & informativeText = QString()) signal
Emitted when copy is ended or aborted (used internally to display copy result)
Referenced by mdtFileCopier().
void mdtFileCopier::finished (bool success) signal
Emitted when copy process is done.
Parameters
success True on success, false on failure (errors are displayed to the user, and logged with mdtError system)
Referenced by cancelCopy(), startCopy(), and waitFinished().
void mdtFileCopier::newProgressLabelText (const QString & text) signal
Emitted when new progress label text is set (used internally for proegress dialog)
Referenced by mdtFileCopier().
void mdtFileCopier::newProgressRange (int min, int max) signal
Emitted when new progress range is set (used internally for proegress dialog)
Referenced by mdtFileCopier().
void mdtFileCopier::newProgressValue (int value) signal
Emitted when new progress value is set (used internally for proegress dialog)
Referenced by mdtFileCopier().
void mdtFileCopier::setDefaultSetup ()
Set the default setup.
Default setup is:
Test mode is diseabled
Direct overwrite diseabled, user will be asked if destination allready exists This method is called by constructor.
See Also
setTestMode()
setDirectDestOverwrite()
Definition at line 82 of file mdtFileCopier.cpp.
Referenced by mdtFileCopier().
void mdtFileCopier::setDirectDestOverwrite (bool directOverwrite)
Permit direct destination overwrite.
If set false, the user will be asked about what to do if destination allready exists.
Definition at line 77 of file mdtFileCopier.cpp.
void mdtFileCopier::setTestMode (bool enable)
If set true, message boxes will not be displayed, and some default decisions will be taken.
Used by unit tests. Please never use this flag without you know that it can happen !
Definition at line 322 of file mdtFileCopier.cpp.
bool mdtFileCopier::startCopy ()
Start the copy.
For all enqueued copies, some checks will be done, when ok, copies will then processed.
To know when copy is finished, use waitFinished(), or connect to the finished() signal.
Returns
true if copy will be processed, or false if no copy can be done, or user cancelled copy because of some problems.
Definition at line 97 of file mdtFileCopier.cpp.
References mdtFileCopierItem::destFilePath(), mdtError::Error, finished(), MDT_ERROR_SET_SRC, MDT_FILE_IO_ERROR, mdtFileCopierItem::setDestDirectoryPath(), mdtFileCopierItem::setDestFileName(), mdtFileCopierItem::setDestFilePath(), mdtFileCopierItem::setFileSize(), mdtFileCopierItem::setSrcDirectoryPath(), mdtFileCopierItem::setSrcFileName(), mdtFileCopierItem::setSrcFilePath(), mdtError::setSystemError(), and mdtFileCopierItem::srcFilePath().
bool mdtFileCopier::waitFinished ()
Wait until copies are done.
This function will only return when copy process is done. Internally, a couple of msleep()/process event will be called, so Qt's GUI event loop is not broken, and application will not freeze.
Returns
True on success, false on failure or abort (errors are displayed to the user, and logged with mdtError system)
Definition at line 304 of file mdtFileCopier.cpp.
References finished(), and msleep.
The documentation for this class was generated from the following files:
src/mdtutils/mdtFileCopier.h
src/mdtutils/mdtFileCopier.cpp