Multi diag tools: mdtFieldMap Class Reference
mdtFieldMap Class Reference
Map fields between a source and a destination data set.
#include <mdtFieldMap.h>
Public Types
enum FieldReference_t { ReferenceByIndex, ReferenceByName }
Field reference.
Public Member Functions
mdtFieldMap ()
Create a empty field map.
mdtFieldMap (const mdtFieldMap &other)
Copy constructor.
~mdtFieldMap ()
Destroy field map.
void setSourceFields (const QList< mdtFieldMapField > &fields)
Set the list of source fields.
void setSourceFieldsByDisplayTexts (const QStringList &displayTexts, int startFieldIndex)
Set source fields by display text.
const QList< mdtFieldMapField > & sourceFields () const
Get the list of source fields.
const QList< mdtFieldMapField > mappedSourceFields () const
Get a list of source fields that are mapped.
const QList< mdtFieldMapField > notMappedSourceFields (FieldReference_t reference) const
Get a list of source fields that are not allready mapped.
const QStringList sourceHeader () const
Get the header of source fields that are mapped.
void setDestinationFields (const QList< mdtFieldMapField > &fields)
Set the list of destination fields.
void setDestinationFieldsByDisplayTexts (const QStringList &displayTexts, int startFieldIndex)
Set destination fields by display text.
void updateDestinationFields (const QList< mdtFieldMapField > &fields, FieldReference_t reference)
Update the list of destination fields.
const QList< mdtFieldMapField > & destinationFields () const
Get the list of destination fields.
const QList< mdtFieldMapField > mappedDestinationFields () const
Get a list of destination fields that are mapped.
const QList< mdtFieldMapField > notMappedDestinationFields (FieldReference_t reference) const
Get a list of destination fields that are not allready mapped.
const QStringList destinationHeader () const
Get the header of destination fields.
void addItem (mdtFieldMapItem *item)
Add a item.
void generateMapping ()
Generate mapping.
void removeItem (mdtFieldMapItem *item)
Remove a item.
void removeItemAtSourceFieldIndex (int index)
Remove item with given source field index.
void removeItemAtDestinationFieldIndex (int index)
Remove item with given destination field index.
const QList< mdtFieldMapItem * > & items () const
Get a list of all items.
void clear ()
Delete all items.
mdtFieldMapItem * itemAtDestinationFieldIndex (int index) const
Get the mapping item for a given destination field index.
mdtFieldMapItem * itemAtDestinationFieldName (const QString &name) const
Get the item for a given filed name.
QString sourceFieldNameAtDestinationFieldIndex (int index) const
Get the source field name for a given destination field index.
QList< mdtFieldMapItem * > itemsAtSourceFieldIndex (int index) const
Get the items for given source index.
QList< mdtFieldMapItem * > itemsAtSourceFieldName (const QString &name) const
Get the items for given source field name.
QVariant dataForDestinationFieldIndex (const QStringList &sourceDataRow, int destinationFieldIndex) const
Extract data for given destination field index in source data row.
QVariant dataForDestinationFieldIndex (const QList< QVariant > &sourceDataRow, int destinationFieldIndex) const
QVariant dataForDestinationFieldName (const QStringList &sourceDataRow, const QString &destinationFieldName) const
Extract data for given destination field name in source data row.
const QList< QVariant > destinationDataRow (const QList< QVariant > &sourceDataRow) const
Get destination data row for given source data row.
const QList< QVariant > destinationDataRow (const QStringList &sourceDataRow) const
Get destination data row for given source data row with (source row as QStringList version)
QHash< QString, QString > displayTextsByFieldNames () const
Get display texts referenced by field names.
Detailed Description
Map fields between a source and a destination data set.
To explain this class, we take a example. We have to import data from a CSV file into a table model. The problem is that some data are grouped in one field, we call it "Group1". To display the data to a conveniant way, we have to split Group1's data and header. We know that Group1 contains 3 fileds:
SubID: index 0 to 1
SubName: index 2 to 5
SubValue: index 6 to 9
During import, we have to create 3 fields in model, called SubID, SubName and SubValue, and store correct part of Group1 into each created field.
This class was made to help solving such problem.
Definition at line 69 of file mdtFieldMap.h.
Member Enumeration Documentation
enum mdtFieldMap::FieldReference_t
Field reference.
Used by some methods that need to know what the reference is to find a field .
Enumerator
ReferenceByIndex
Field index is used as reference
ReferenceByName
Field name is used as reference
Definition at line 78 of file mdtFieldMap.h.
Constructor & Destructor Documentation
mdtFieldMap::mdtFieldMap ()
Create a empty field map.
Definition at line 66 of file mdtFieldMap.cpp.
mdtFieldMap::mdtFieldMap (const mdtFieldMap & other)
Copy constructor.
Definition at line 71 of file mdtFieldMap.cpp.
mdtFieldMap::~mdtFieldMap ()
Destroy field map.
All items are deleted. Take care that items pointers will become invalid after destroying this object.
Definition at line 76 of file mdtFieldMap.cpp.
References clear().
Member Function Documentation
void mdtFieldMap::addItem (mdtFieldMapItem * item)
Add a item.
A item contains map informations
Precondition
Item must be a valid pointer
See Also
mdtFieldMapItem
Definition at line 304 of file mdtFieldMap.cpp.
Referenced by mdtDataTableManager::addFieldMapping(), mdtDataTableManager::copyTable(), and mdtDataTableManager::importFromCsvFile().
void mdtFieldMap::clear ()
Delete all items.
Take care that items pointers will become invalid after calling this method.
Definition at line 385 of file mdtFieldMap.cpp.
Referenced by mdtDataTableManager::clearFieldMap(), and ~mdtFieldMap().
QVariant mdtFieldMap::dataForDestinationFieldIndex (const QStringList & sourceDataRow, int destinationFieldIndex) const
Extract data for given destination field index in source data row.
Parameters
sourceDataRow In above example, it's a line in CSV file.
destinationFieldIndex In above example, it's the model column index.
Returns
Converted data, or invalid QVariant if index was not found, or on failed conversion.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 472 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationData(), and itemAtDestinationFieldIndex().
Referenced by mdtDataTableModel::addRows(), and dataForDestinationFieldName().
QVariant mdtFieldMap::dataForDestinationFieldIndex (const QList< QVariant > & sourceDataRow, int destinationFieldIndex) const
Definition at line 482 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationData(), itemAtDestinationFieldIndex(), mdtFieldMapItem::sourceFieldDataEndOffset(), mdtFieldMapItem::sourceFieldDataStartOffset(), and mdtFieldMapItem::sourceFieldIndex().
QVariant mdtFieldMap::dataForDestinationFieldName (const QStringList & sourceDataRow, const QString & destinationFieldName) const
Extract data for given destination field name in source data row.
Parameters
sourceDataRow In above example, it's a line in CSV file.
destinationFieldName Destination technical field name.
Returns
Converted data, or invalid QVariant if name was not found, or on failed conversion.
Definition at line 502 of file mdtFieldMap.cpp.
References dataForDestinationFieldIndex(), mdtFieldMapItem::destinationFieldIndex(), and itemAtDestinationFieldName().
const QList< QVariant > mdtFieldMap::destinationDataRow (const QList< QVariant > & sourceDataRow) const
Get destination data row for given source data row.
Definition at line 511 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationData(), mdtFieldMapItem::destinationFieldIndex(), mdtFieldMapItem::sourceFieldDataEndOffset(), mdtFieldMapItem::sourceFieldDataStartOffset(), and mdtFieldMapItem::sourceFieldIndex().
Referenced by mdtDataTableManager::copyTable(), and mdtDataTableManager::importFromCsvFile().
const QList< QVariant > mdtFieldMap::destinationDataRow (const QStringList & sourceDataRow) const
Get destination data row for given source data row with (source row as QStringList version)
Definition at line 539 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationData(), mdtFieldMapItem::destinationFieldIndex(), mdtFieldMapItem::sourceFieldDataEndOffset(), mdtFieldMapItem::sourceFieldDataStartOffset(), and mdtFieldMapItem::sourceFieldIndex().
const QList< mdtFieldMapField > & mdtFieldMap::destinationFields () const
Get the list of destination fields.
Definition at line 225 of file mdtFieldMap.cpp.
const QStringList mdtFieldMap::destinationHeader () const
Get the header of destination fields.
The returned list is sorted by column indexes . For fields that not have a display text set, the field name is put into header .
Definition at line 284 of file mdtFieldMap.cpp.
References mdtFieldMapField::displayText(), mappedDestinationFields(), and mdtFieldMapField::name().
Referenced by mdtDataTableManager::importFromCsvFile().
QHash< QString, QString > mdtFieldMap::displayTextsByFieldNames () const
Get display texts referenced by field names.
Returns
QHash with fieldName as key and displayText as value.
Definition at line 567 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationFieldDisplayText(), and mdtFieldMapItem::destinationFieldName().
Referenced by mdtDataTableManager::displayTextsByFieldNames().
void mdtFieldMap::generateMapping ()
Generate mapping.
Mapping we be done in 2 distinct ways, regarding allready existing destination fields:
Not destination fields are set: a 1:1 mapping is done .
Destination fields are set: mapping is done by field names, only for names that exists in both source and destination fields .
Use notMappedSourceFields() and notMappedDestinationFields() to know wich fields are ignored .
Definition at line 313 of file mdtFieldMap.cpp.
References ReferenceByName, mdtFieldMapItem::setDestinationField(), and mdtFieldMapItem::setSourceField().
mdtFieldMapItem * mdtFieldMap::itemAtDestinationFieldIndex (int index) const
Get the mapping item for a given destination field index.
Parameters
index In above example, it's the model column index.
Returns
Pointer to item if found, else 0 (null pointer).
Definition at line 393 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationFieldIndex().
Referenced by dataForDestinationFieldIndex(), notMappedDestinationFields(), and sourceFieldNameAtDestinationFieldIndex().
mdtFieldMapItem * mdtFieldMap::itemAtDestinationFieldName (const QString & name) const
Get the item for a given filed name.
Parameters
name Technical field name.
Returns
Pointer to item if found, else 0 (null pointer).
Definition at line 409 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationFieldName().
Referenced by dataForDestinationFieldName(), and notMappedDestinationFields().
const QList< mdtFieldMapItem * > & mdtFieldMap::items () const
Get a list of all items.
Definition at line 380 of file mdtFieldMap.cpp.
Referenced by itemsAtSourceFieldIndex(), itemsAtSourceFieldName(), mappedDestinationFields(), and mappedSourceFields().
QList< mdtFieldMapItem * > mdtFieldMap::itemsAtSourceFieldIndex (int index) const
Get the items for given source index.
Parameters
index In above example, it's the index of field in CSV header.
Returns
Pointer to item if found, else 0 (null pointer).
Definition at line 438 of file mdtFieldMap.cpp.
References items(), and mdtFieldMapItem::sourceFieldIndex().
Referenced by notMappedSourceFields().
QList< mdtFieldMapItem * > mdtFieldMap::itemsAtSourceFieldName (const QString & name) const
Get the items for given source field name.
Parameters
name In above example, it's the technical field name in CSV header.
Returns
Pointer to item if found, else 0 (null pointer).
Definition at line 455 of file mdtFieldMap.cpp.
References items(), and mdtFieldMapItem::sourceFieldName().
Referenced by mdtDataTableManager::copyTable(), mdtDataTableManager::importFromCsvFile(), and notMappedSourceFields().
const QList< mdtFieldMapField > mdtFieldMap::mappedDestinationFields () const
Get a list of destination fields that are mapped.
The returned list is sorted by column indexes .
Definition at line 230 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationField(), mdtFieldMapItem::destinationFieldIndex(), and items().
Referenced by mdtDataTableManager::copyTable(), destinationHeader(), and mdtDataTableManager::importFromCsvFile().
const QList< mdtFieldMapField > mdtFieldMap::mappedSourceFields () const
Get a list of source fields that are mapped.
The returned list is sorted by column indexes .
Definition at line 108 of file mdtFieldMap.cpp.
References items(), mdtFieldMapItem::sourceField(), and mdtFieldMapItem::sourceFieldIndex().
Referenced by mdtDataTableManager::copyTable(), and sourceHeader().
const QList< mdtFieldMapField > mdtFieldMap::notMappedDestinationFields (mdtFieldMap::FieldReference_t reference) const
Get a list of destination fields that are not allready mapped.
Definition at line 256 of file mdtFieldMap.cpp.
References mdtFieldMapField::index(), itemAtDestinationFieldIndex(), itemAtDestinationFieldName(), mdtFieldMapField::name(), ReferenceByIndex, and ReferenceByName.
const QList< mdtFieldMapField > mdtFieldMap::notMappedSourceFields (mdtFieldMap::FieldReference_t reference) const
Get a list of source fields that are not allready mapped.
Definition at line 134 of file mdtFieldMap.cpp.
References mdtFieldMapField::index(), itemsAtSourceFieldIndex(), itemsAtSourceFieldName(), mdtFieldMapField::name(), ReferenceByIndex, and ReferenceByName.
void mdtFieldMap::removeItem (mdtFieldMapItem * item)
Remove a item.
Will also delete item if it was removed from items .
Definition at line 346 of file mdtFieldMap.cpp.
Referenced by removeItemAtDestinationFieldIndex(), and removeItemAtSourceFieldIndex().
void mdtFieldMap::removeItemAtDestinationFieldIndex (int index)
Remove item with given destination field index.
If item was not found, nothing happens .
Definition at line 367 of file mdtFieldMap.cpp.
References removeItem().
void mdtFieldMap::removeItemAtSourceFieldIndex (int index)
Remove item with given source field index.
If item was not found, nothing happens .
Definition at line 354 of file mdtFieldMap.cpp.
References removeItem().
void mdtFieldMap::setDestinationFields (const QList< mdtFieldMapField > & fields)
Set the list of destination fields.
This can be used if destination fields is allready known . If mdtFieldMapDialog is used, this fields are also displayed to the user . For auto map generation, these fields are also needed .
Definition at line 181 of file mdtFieldMap.cpp.
void mdtFieldMap::setDestinationFieldsByDisplayTexts (const QStringList & displayTexts, int startFieldIndex)
Set destination fields by display text.
Will create the destination fields list . Given display text list will be used for display text in fields . Field names are get from display texts, but not allowed chars are replaced . Indexing is also done , starting at given start field index .
Note: it is not checked if a field name appears more than one time, you should care if data must be stored in a database table .
Field data type will be set to QVariant::String .
Definition at line 186 of file mdtFieldMap.cpp.
References mdtFieldMapField::getFieldName(), mdtFieldMapField::setDisplayText(), mdtFieldMapField::setIndex(), mdtFieldMapField::setName(), and mdtFieldMapField::sqlField().
void mdtFieldMap::setSourceFields (const QList< mdtFieldMapField > & fields)
Set the list of source fields.
Definition at line 81 of file mdtFieldMap.cpp.
Referenced by mdtDataTableManager::copyTable().
void mdtFieldMap::setSourceFieldsByDisplayTexts (const QStringList & displayTexts, int startFieldIndex)
Set source fields by display text.
Will create the source fields list . Given display text list will be used for display text in fields . Field names are get from display texts, but not allowed chars are replaced . Indexing is also done , starting at given start field index .
Note: it is not checked if a field name appears more than one time, you should care if data must be stored in a database table .
Field data type will be set to QVariant::String .
Definition at line 86 of file mdtFieldMap.cpp.
References mdtFieldMapField::getFieldName(), mdtFieldMapField::setDisplayText(), mdtFieldMapField::setIndex(), mdtFieldMapField::setName(), and mdtFieldMapField::sqlField().
QString mdtFieldMap::sourceFieldNameAtDestinationFieldIndex (int index) const
Get the source field name for a given destination field index.
Parameters
index In above example, it's the model column index.
Returns
Source field name, or a empty string if field index was not found.
Definition at line 425 of file mdtFieldMap.cpp.
References itemAtDestinationFieldIndex(), and mdtFieldMapItem::sourceFieldName().
const QList< mdtFieldMapField > & mdtFieldMap::sourceFields () const
Get the list of source fields.
Definition at line 103 of file mdtFieldMap.cpp.
Referenced by mdtFieldMapDialog::setFieldMap().
const QStringList mdtFieldMap::sourceHeader () const
Get the header of source fields that are mapped.
The returned list is sorted by column indexes . For fields that not have a display text set, the field name is put into header .
Definition at line 161 of file mdtFieldMap.cpp.
References mdtFieldMapField::displayText(), mappedSourceFields(), and mdtFieldMapField::name().
Referenced by mdtDataTableManager::sourceHeader().
void mdtFieldMap::updateDestinationFields (const QList< mdtFieldMapField > & fields, mdtFieldMap::FieldReference_t reference)
Update the list of destination fields.
Will also update existing mapping . Note: if a mapping item contains a destination filed that not exists anymore in destination field list, the item will be removed .
Definition at line 203 of file mdtFieldMap.cpp.
References mdtFieldMapItem::destinationField(), and mdtFieldMapItem::setDestinationField().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtFieldMap.h
src/mdtutilsgui/mdtFieldMap.cpp