Multi diag tools: mdtTtBasicTester Class Reference
mdtTtBasicTester Class Reference
Provide ability to run tests.
#include <mdtTtBasicTester.h>
Public Member Functions
mdtTtBasicTester (QSqlDatabase db, QObject *parent=0)
Constructor.
bool setup ()
Setup.
mdtError lastError () const
Get last error.
Public Member Functions inherited from mdtTtAbstractTester
mdtTtAbstractTester (QSqlDatabase db, QObject *parent=0)
Constructor.
bool setTestUiWidget (QWidget *widget)
All childs contained in widget that have a name prefixed fld_ will be mapped to corresponding fields in Test_view. They cann be written, but internally used mdtAbstractSqlTableController's submit() slot will not work. Data will be really stored in Test_tbl by saveTest().
bool start ()
Start state machines.
QSqlDatabase database ()
Get database instance.
std::shared_ptr
< mdtSqlDataWidgetController > testViewController ()
Access controller that acts on Test_view.
std::shared_ptr
< mdtSqlTableViewController > testItemViewController ()
Access controller that acts on TestItem_view.
std::shared_ptr
< mdtTtTestNodeManager > testNodeManager ()
Get test node manager object.
std::shared_ptr< mdtTtTest > test ()
Get test object.
bool testIsEmpty () const
Check if a test is empty.
bool testIsSaved () const
Check if test is saved.
Additional Inherited Members
Public Slots inherited from mdtTtAbstractTester
virtual void createTest ()
Create a new test.
virtual void openTest ()
Open a existing test.
virtual void saveTest ()
Save current test.
Signals inherited from mdtTtAbstractTester
void testDataChanged (const QSqlRecord &data)
Emited when test data has changed.
Protected Member Functions inherited from mdtTtAbstractTester
bool removeTestIfEmpty ()
Remove current test if it is empty.
bool removeCurrentTestPv ()
Remove current test.
void displayLastError ()
Display last error to the user.
Protected Attributes inherited from mdtTtAbstractTester
mdtError pvLastError
Contains last error that occured.
Detailed Description
Provide ability to run tests.
: public QMainWindow, Ui::mdtTtBasicTester
Definition at line 36 of file mdtTtBasicTester.h.
Constructor & Destructor Documentation
mdtTtBasicTester::mdtTtBasicTester (QSqlDatabase db, QObject * parent = 0)
Constructor.
Definition at line 47 of file mdtTtBasicTester.cpp.
Member Function Documentation
mdtError mdtTtBasicTester::lastError () const inline
Get last error.
Definition at line 52 of file mdtTtBasicTester.h.
References mdtTtAbstractTester::pvLastError.
Referenced by mdtTtBasicTesterWindow::lastError().
bool mdtTtBasicTester::setup () virtual
Setup.
Reimplemented from mdtTtAbstractTester.
Definition at line 52 of file mdtTtBasicTester.cpp.
References mdtTtAbstractTester::setup().
Referenced by mdtTtBasicTesterWindow::init().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtBasicTester.h
src/mdttools/mdttesttool/mdtTtBasicTester.cpp