Multi diag tools: mdtTtLogicalTestCable Class Reference
mdtTtLogicalTestCable Class Reference
Helper class for test connection cable edition.
#include <mdtTtLogicalTestCable.h>
Public Member Functions
mdtTtLogicalTestCable (QObject *parent, QSqlDatabase db)
Constructor.
~mdtTtLogicalTestCable ()
Destructor.
QString sqlForTestNodeUnitSelection (const QVariant &testCableId)
Get SQL statement for test node unit selection.
QString sqlForDutUnitSelection (const QVariant &testCableId)
Get SQL statement for DUT unit selection.
bool addTestNodeUnit (const QVariant &testNodeUnitId, const QVariant &testCableId)
Add a test node unit.
bool removeTestNodeUnits (const mdtSqlTableSelection &s)
Remove test node units.
bool addDutUnit (const QVariant &unitId, const QVariant &testCableId)
Add a DUT unit.
bool removeDutUnits (const mdtSqlTableSelection &s)
Remove DUT units.
QString sqlForTestNodeSelection () const
Get SQL statement for test node selection.
QString sqlForStartConnectorSelection (const QVariant &dutUnitId) const
Get SQL statement for start unit connector selection.
QString sqlForUnitConnectorSelectionFromUnitConnectorIdList (const QList< QVariant > &connectorIdList) const
Get SQL statement for unit connector selection for given unit connector ID list.
QString sqlForTestCableSelection ()
Get SQL statement for test cable selection.
bool loadLinkList ()
Load link list.
QList< QVariant > getToUnitConnectorRelatedUnitConnectionIdList (const QVariant &unitConnectorId)
Get a list of unit connections IDs related to given unit connector ID.
QList< QVariant > getToUnitConnectionLinkedUnitConnectorIdList (const QVariant &fromUnitConnectionId)
Get a list of unit connections that are part of a connector.
QList< QVariant > getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector (const QVariant &fromUnitConnectionId, const QVariant &unitConnectorId)
Get a list of unit connections that are linked to given start unit connection, and that are part of given unit connector.
QList< QVariant > getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnectorList (const QVariant &fromUnitConnectionId, const QList< QVariant > &unitConnectorIdList)
Get a list of unit connections that are linked to given start unit connection, and that are part of given unit connector list.
QList< QVariant > getToUnitConnectionIdListLinkedUnitConnectionIdListPartOfUnitConnectorList (QList< QVariant > &fromUnitConnectionIdList, const QList< QVariant > &unitConnectorIdList)
Get a list of unit connections that are linked to given start unit connection list, and that are part of given unit connector list.
bool cableExistsByKey (const QString &key, bool &ok)
Create a test cable.
bool createCable (const mdtSqlRecord &cableData, QList< mdtTtTestLinkData > &linkDataList)
Create a logical test cable.
mdtTtTestLinkData getLinkData (const QVariant &testConnectionId, const QVariant &dutConnectionId, bool *ok)
Get test link data.
bool addLink (const mdtTtTestLinkData &data)
Add a link into test link table.
bool addLinks (const QVariant &nodeId, const QVariant &testCableId, const QList< QVariant > &testConnectionIdList, const QList< QVariant > &dutConnectionIdList)
Add links in link table.
bool editLink (const QVariant &testConnectionId, const QVariant &dutConnectionId, const mdtTtTestLinkData &linkData)
Edit a test link.
bool removeLink (const QVariant &testConnectionId, const QVariant &dutConnectionId)
Remove a test link.
bool addCable (const QVariant &identification)
Add a cable into test cable table.
bool addLink (const QVariant &testConnectionId, const QVariant &dutConnectionId, const QVariant &testCableId, const QVariant &identification, const QVariant &value)
Add a link into test link table.
bool connectTestCable (const QVariant &testCableId, const QVariant &testNodeId, const QVariant &dutVehicleTypeId)
Connect a test cable.
bool disconnectTestCable (const QVariant &testCableId)
Get test link data.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
template<typename T >
bool addRecordList (const QList< T > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField1, const QVariant &key1, const QString &matchField2, const QVariant &key2)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for test connection cable edition.
Definition at line 35 of file mdtTtLogicalTestCable.h.
Constructor & Destructor Documentation
mdtTtLogicalTestCable::mdtTtLogicalTestCable (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 31 of file mdtTtLogicalTestCable.cpp.
mdtTtLogicalTestCable::~mdtTtLogicalTestCable ()
Destructor.
Definition at line 37 of file mdtTtLogicalTestCable.cpp.
Member Function Documentation
bool mdtTtLogicalTestCable::addCable (const QVariant & identification)
Add a cable into test cable table.
Definition at line 524 of file mdtTtLogicalTestCable.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtTtLogicalTestCable::addDutUnit (const QVariant & unitId, const QVariant & testCableId)
Add a DUT unit.
Definition at line 110 of file mdtTtLogicalTestCable.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, and mdtSqlRecord::setValue().
bool mdtTtLogicalTestCable::addLink (const mdtTtTestLinkData & data)
Add a link into test link table.
Definition at line 475 of file mdtTtLogicalTestCable.cpp.
References mdtTtBase::addRecord().
Referenced by addLinks(), and editLink().
bool mdtTtLogicalTestCable::addLink (const QVariant & testConnectionId, const QVariant & dutConnectionId, const QVariant & testCableId, const QVariant & identification, const QVariant & value)
Add a link into test link table.
Todo:
Obselete this version
Definition at line 555 of file mdtTtLogicalTestCable.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtTtLogicalTestCable::addLinks (const QVariant & nodeId, const QVariant & testCableId, const QList< QVariant > & testConnectionIdList, const QList< QVariant > & dutConnectionIdList)
Add links in link table.
Precondition
dutConnectionIdList size must be <= testConnectionIdList
Definition at line 480 of file mdtTtLogicalTestCable.cpp.
References addLink().
bool mdtTtLogicalTestCable::addTestNodeUnit (const QVariant & testNodeUnitId, const QVariant & testCableId)
Add a test node unit.
Definition at line 91 of file mdtTtLogicalTestCable.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, and mdtSqlRecord::setValue().
bool mdtTtLogicalTestCable::cableExistsByKey (const QString & key, bool & ok)
Create a test cable.
bool createTestCable(const QVariant & nodeId, const QList<QVariant> & busAtestConnectionIdList, const QList<QVariant> & busAdutConnectionIdList, const QList<QVariant> & busBtestConnectionIdList, const QList<QVariant> & busBdutConnectionIdList);
Check if a logical test cable with key allready exists
Definition at line 359 of file mdtTtLogicalTestCable.cpp.
bool mdtTtLogicalTestCable::connectTestCable (const QVariant & testCableId, const QVariant & testNodeId, const QVariant & dutVehicleTypeId)
Connect a test cable.
mdtClLinkData mdtTtLogicalTestCable::getTestLinkData(const QVariant & testLinkId) { QString sql; QSqlError sqlError; QSqlQuery query(database()); mdtClLinkData data;
Setup and run query to get data in test link table sql = "SELECT "\ "TestConnection_Id_FK , DutConnection_Id_FK, TestCable_Id_FK, Identification, Value "; sql += " FROM TestLink_tbl "; sql += " WHERE Id_PK = " + testLinkId.toString(); if(!query.exec(sql)){ sqlError = query.lastError(); pvLastError.setError("Cannot get test link data", mdtError::Error); pvLastError.setSystemError(sqlError.number(), sqlError.text()); MDT_ERROR_SET_SRC(pvLastError, "mdtTtLogicalTestCable"); pvLastError.commit(); return data; } if(!query.next()){ return data; } data.setUnitConnectionStartId(query.value(0)); data.setUnitConnectionEndId(query.value(1)); data.setIdentification(query.value(3)); data.setValue(query.value(4)); data.setLinkTypeCode("TESTLINK"); data.setLinkDirectionCode("BID");
return data; } bool mdtTtLogicalTestCable::addLinks(const QVariant & nodeId, const QList<QVariant> & testConnectionIdList, const QVariant & dutVehicleId, const QList<QVariant> & dutConnectionIdList) { Q_ASSERT(dutConnectionIdList.size() <= testConnectionIdList.size());
mdtClUnit unit(this, database()); int i;
for(i = 0; i < dutConnectionIdList.size(); ++i){ mdtClLinkData data; qDebug() << "Adding link from test connection " << testConnectionIdList.at(i) << " -> dut connection " << dutConnectionIdList.at(i); data.setUnitConnectionStartId(testConnectionIdList.at(i)); data.setUnitConnectionEndId(dutConnectionIdList.at(i)); data.setIdentification("..."); data.setLinkDirectionCode("BID"); data.setLinkTypeCode("TESTLINK"); data.setValue(0.1); data.addVehicleTypeStartId(nodeId); data.addVehicleTypeEndId(dutVehicleId); if(!data.buildVehicleTypeStartEndIdList()){ qDebug() << "Cannot build vehicle list"; return false; } qDebug() << "VHC lst: " << data.vehicleTypeStartEndIdList(); if(!unit.addLink(data)){ pvLastError = unit.lastError(); return false; } qDebug() << "->Link added"; }
return true; } QList<mdtClLinkData> mdtTtLogicalTestCable::getTestLinkDataByTestCableId(const QVariant & testCableId) { QString sql; QSqlError sqlError; QSqlQuery query(database()); QList<mdtClLinkData> dataList;
Setup and run query to get data in test link table sql = "SELECT "\ "TestConnection_Id_FK , DutConnection_Id_FK, TestCable_Id_FK, Identification, Value "; sql += " FROM TestLink_tbl "; sql += " WHERE TestCable_Id_FK = " + testCableId.toString(); if(!query.exec(sql)){ sqlError = query.lastError(); pvLastError.setError("Cannot get test link data", mdtError::Error); pvLastError.setSystemError(sqlError.number(), sqlError.text()); MDT_ERROR_SET_SRC(pvLastError, "mdtTtLogicalTestCable"); pvLastError.commit(); return dataList; } while(query.next()){ mdtClLinkData data; data.setUnitConnectionStartId(query.value(0)); data.setUnitConnectionEndId(query.value(1)); data.setIdentification(query.value(3)); data.setValue(query.value(4)); data.setLinkTypeCode("TESTLINK"); data.setLinkDirectionCode("BID"); dataList.append(data); }
return dataList; }
Definition at line 697 of file mdtTtLogicalTestCable.cpp.
bool mdtTtLogicalTestCable::createCable (const mdtSqlRecord & cableData, QList< mdtTtTestLinkData > & linkDataList)
Create a logical test cable.
For each item in linkDataList, field LogicalTestCable_Id_FK will be updated with freashly created logical test cable.
Definition at line 377 of file mdtTtLogicalTestCable.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::beginTransaction(), mdtSqlRecord::clearValues(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtTtBase::rollbackTransaction(), and mdtSqlRecord::setValue().
bool mdtTtLogicalTestCable::disconnectTestCable (const QVariant & testCableId)
Get test link data.
mdtClLinkData getTestLinkData(const QVariant & testLinkId);
Get test link data for given test cable IDQList<mdtClLinkData> getTestLinkDataByTestCableId(const QVariant & testCableId);
Disconnect a test cable
Definition at line 733 of file mdtTtLogicalTestCable.cpp.
bool mdtTtLogicalTestCable::editLink (const QVariant & testConnectionId, const QVariant & dutConnectionId, const mdtTtTestLinkData & linkData)
Edit a test link.
Definition at line 499 of file mdtTtLogicalTestCable.cpp.
References addLink(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), removeLink(), and mdtTtBase::rollbackTransaction().
mdtTtTestLinkData mdtTtLogicalTestCable::getLinkData (const QVariant & testConnectionId, const QVariant & dutConnectionId, bool * ok)
Get test link data.
Definition at line 441 of file mdtTtLogicalTestCable.cpp.
References mdtError::commit(), mdtError::Error, mdtTtBase::getData(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, and mdtError::setError().
QList< QVariant > mdtTtLogicalTestCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector (const QVariant & fromUnitConnectionId, const QVariant & unitConnectorId)
Get a list of unit connections that are linked to given start unit connection, and that are part of given unit connector.
Will get unit connections that are linked to given fromUnitConnectionId , but will only return those that are part of given unitConnectorId .
Note: link list must be loaded with loadLinkList() , else this method will fail.
Definition at line 267 of file mdtTtLogicalTestCable.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, mdtClPathGraph::getLinkedConnectionIdList(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnectorList().
QList< QVariant > mdtTtLogicalTestCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnectorList (const QVariant & fromUnitConnectionId, const QList< QVariant > & unitConnectorIdList)
Get a list of unit connections that are linked to given start unit connection, and that are part of given unit connector list.
See Also
getToUnitConnectionLinkedUnitConnectionIdListPartOfUnitConnector()
Definition at line 310 of file mdtTtLogicalTestCable.cpp.
References getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector().
Referenced by getToUnitConnectionIdListLinkedUnitConnectionIdListPartOfUnitConnectorList().
QList< QVariant > mdtTtLogicalTestCable::getToUnitConnectionIdListLinkedUnitConnectionIdListPartOfUnitConnectorList (QList< QVariant > & fromUnitConnectionIdList, const QList< QVariant > & unitConnectorIdList)
Get a list of unit connections that are linked to given start unit connection list, and that are part of given unit connector list.
See Also
getToUnitConnectionLinkedUnitConnectionIdListPartOfUnitConnector()
Note: will alter the given fromUnitConnectionIdList
Definition at line 332 of file mdtTtLogicalTestCable.cpp.
References getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnectorList().
QList< QVariant > mdtTtLogicalTestCable::getToUnitConnectionLinkedUnitConnectorIdList (const QVariant & fromUnitConnectionId)
Get a list of unit connections that are part of a connector.
This method will return unit connections that are part of given unit connector, starting with given unit connections id list (filter) .QList<QVariant> getToUnitConnectorRelatedUnitConnectionIdList(const QVariant & unitConnectorId, const QList<QVariant> & unitConnectionIdList);
Get a list of unit connectors that are linked to given unit connection
Note: link list must be loaded with loadLinkList() , else this method will fail.
QList<QVariant> mdtTtLogicalTestCable::getToUnitConnectorRelatedUnitConnectionIdList(const QVariant & unitConnectorId, const QList<QVariant> & unitConnectionIdList) { QList<QVariant> allConnectionIdList; QList<QVariant> connectionIdList; int i;
allConnectionIdList = getToUnitConnectorRelatedUnitConnectionIdList(unitConnectorId); for(i = 0; i < unitConnectionIdList.size(); ++i){ if(allConnectionIdList.contains(unitConnectionIdList.at(i))){ connectionIdList.append(unitConnectionIdList.at(i)); } }
return connectionIdList; }
Definition at line 228 of file mdtTtLogicalTestCable.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, mdtClPathGraph::getLinkedConnectionIdList(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QList< QVariant > mdtTtLogicalTestCable::getToUnitConnectorRelatedUnitConnectionIdList (const QVariant & unitConnectorId)
Get a list of unit connections IDs related to given unit connector ID.
Definition at line 187 of file mdtTtLogicalTestCable.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtTtLogicalTestCable::loadLinkList ()
Load link list.
Will load link list into internal graph. Some methods will use this graph to find a path starting at a unit connection, connections that are part of a given path, ...
Definition at line 178 of file mdtTtLogicalTestCable.cpp.
References mdtClPathGraph::lastError(), mdtClPathGraph::loadLinkList(), and mdtTtBase::pvLastError.
bool mdtTtLogicalTestCable::removeDutUnits (const mdtSqlTableSelection & s)
Remove DUT units.
Definition at line 124 of file mdtTtLogicalTestCable.cpp.
References mdtTtBase::removeData().
bool mdtTtLogicalTestCable::removeLink (const QVariant & testConnectionId, const QVariant & dutConnectionId)
Remove a test link.
Definition at line 519 of file mdtTtLogicalTestCable.cpp.
References mdtTtBase::removeData().
Referenced by editLink().
bool mdtTtLogicalTestCable::removeTestNodeUnits (const mdtSqlTableSelection & s)
Remove test node units.
Definition at line 105 of file mdtTtLogicalTestCable.cpp.
References mdtTtBase::removeData().
QString mdtTtLogicalTestCable::sqlForDutUnitSelection (const QVariant & testCableId)
Get SQL statement for DUT unit selection.
List all DUT units that are not currently affected to given test cable.
Definition at line 79 of file mdtTtLogicalTestCable.cpp.
QString mdtTtLogicalTestCable::sqlForStartConnectorSelection (const QVariant & dutUnitId) const
Get SQL statement for start unit connector selection.
Parameters
dutUnitId ID of unit that will become the DUT (Device Under Test)
Definition at line 143 of file mdtTtLogicalTestCable.cpp.
QString mdtTtLogicalTestCable::sqlForTestCableSelection ()
Get SQL statement for test cable selection.
Definition at line 169 of file mdtTtLogicalTestCable.cpp.
QString mdtTtLogicalTestCable::sqlForTestNodeSelection () const
Get SQL statement for test node selection.
Definition at line 131 of file mdtTtLogicalTestCable.cpp.
QString mdtTtLogicalTestCable::sqlForTestNodeUnitSelection (const QVariant & testCableId)
Get SQL statement for test node unit selection.
List all test node units that are not currently affected to given test cable.
Definition at line 42 of file mdtTtLogicalTestCable.cpp.
QString mdtTtLogicalTestCable::sqlForUnitConnectorSelectionFromUnitConnectorIdList (const QList< QVariant > & connectorIdList) const
Get SQL statement for unit connector selection for given unit connector ID list.
Definition at line 153 of file mdtTtLogicalTestCable.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtLogicalTestCable.h
src/mdttools/mdttesttool/mdtTtLogicalTestCable.cpp