Multi diag tools: mdtClUnitConnectionDialog Class Reference
mdtClUnitConnectionDialog Class Reference
Dialog for edition of a unit connection.
#include <mdtClUnitConnectionDialog.h>
Public Types
enum mode_t { Add, Edit }
Mode.
Public Member Functions
mdtClUnitConnectionDialog (QWidget *parent, QSqlDatabase db, mode_t mode)
Constructor.
~mdtClUnitConnectionDialog ()
Destructor.
void setData (const mdtClUnitConnectionData &data, const QVariant &baseArticleId)
Set data.
const mdtClUnitConnectionData & data () const
Get data.
Additional Inherited Members
Private Member Functions inherited from Ui_mdtClUnitConnectionDialog
void setupUi (QDialog *mdtClUnitConnectionDialog)
void retranslateUi (QDialog *mdtClUnitConnectionDialog)
Private Attributes inherited from Ui_mdtClUnitConnectionDialog
QVBoxLayout * verticalLayout_2
QFormLayout * formLayout
QLabel * lbArticleIoTypeLabel
QLabel * lbArticleIoType
QLabel * lbSchemaPage
QHBoxLayout * horizontalLayout_7
QLineEdit * leSchemaPage
QSpacerItem * horizontalSpacer_3
QLabel * lbUnitConnectorNameLabel
QHBoxLayout * horizontalLayout
QLabel * lbUnitConnectorName
QPushButton * pbSelectUnitConnector
QPushButton * pbSetNoConnector
QLabel * lbArticleConnectorNameLabel
QLabel * lbArticleConnectorName
QLabel * lbConnectionType
QHBoxLayout * horizontalLayout_11
QComboBox * cbConnectionType
QLabel * lbConnectionTypeText
QLabel * lbUnitContactName
QHBoxLayout * horizontalLayout_2
QLineEdit * leUnitContactName
QPushButton * pbCopyContactName
QLabel * lbContactName
QPushButton * pbSelectContact
QLabel * lbFunctionEN
QHBoxLayout * horizontalLayout_3
QLineEdit * leFunctionEN
QPushButton * pbCopyFunctionEN
QLabel * lbArticleFunctionEN
QLabel * lbFunctionFR
QHBoxLayout * horizontalLayout_4
QLineEdit * leFunctionFR
QPushButton * pbCopyFunctionFR
QLabel * lbArticleFunctionFR
QLabel * lbFunctionDE
QHBoxLayout * horizontalLayout_5
QLineEdit * leFunctionDE
QPushButton * pbCopyFunctionDE
QLabel * lbArticleFunctionDE
QLabel * lbFunctionIT
QHBoxLayout * horizontalLayout_6
QLineEdit * leFunctionIT
QPushButton * pbCopyFunctionIT
QLabel * lbArticleFunctionIT
QLabel * lbSignalName
QHBoxLayout * horizontalLayout_8
QLineEdit * leSignalName
QSpacerItem * horizontalSpacer
QLabel * lbSwAddress
QHBoxLayout * horizontalLayout_9
QSpinBox * sbSwAddress
QSpacerItem * horizontalSpacer_2
QGroupBox * gbRanges
QVBoxLayout * verticalLayout
QTableView * tableView
QHBoxLayout * horizontalLayout_10
QPushButton * pbAddRange
QPushButton * pbEditRange
QPushButton * pbRemoveRange
QSpacerItem * horizontalSpacer_4
QDialogButtonBox * buttonBox
Detailed Description
Dialog for edition of a unit connection.
Definition at line 33 of file mdtClUnitConnectionDialog.h.
Member Enumeration Documentation
enum mdtClUnitConnectionDialog::mode_t
Mode.
Enumerator
Add
In this mode, user can select connection from connector
Edit
In this mode, user cannot change connection, only edit other data
Definition at line 41 of file mdtClUnitConnectionDialog.h.
Constructor & Destructor Documentation
mdtClUnitConnectionDialog::mdtClUnitConnectionDialog (QWidget * parent, QSqlDatabase db, mode_t mode)
Constructor.
Definition at line 34 of file mdtClUnitConnectionDialog.cpp.
References Add, Ui_mdtClUnitConnectionDialog::cbConnectionType, Ui_mdtClUnitConnectionDialog::gbRanges, Ui_mdtClUnitConnectionDialog::pbCopyContactName, Ui_mdtClUnitConnectionDialog::pbCopyFunctionDE, Ui_mdtClUnitConnectionDialog::pbCopyFunctionEN, Ui_mdtClUnitConnectionDialog::pbCopyFunctionFR, Ui_mdtClUnitConnectionDialog::pbCopyFunctionIT, Ui_mdtClUnitConnectionDialog::pbSelectContact, Ui_mdtClUnitConnectionDialog::pbSelectUnitConnector, Ui_mdtClUnitConnectionDialog::pbSetNoConnector, and Ui_mdtClUnitConnectionDialog::setupUi().
mdtClUnitConnectionDialog::~mdtClUnitConnectionDialog ()
Destructor.
Definition at line 61 of file mdtClUnitConnectionDialog.cpp.
Member Function Documentation
const mdtClUnitConnectionData & mdtClUnitConnectionDialog::data () const
Get data.
Definition at line 74 of file mdtClUnitConnectionDialog.cpp.
Referenced by setData().
void mdtClUnitConnectionDialog::setData (const mdtClUnitConnectionData & data, const QVariant & baseArticleId)
Set data.
Fields that are realated to article connection, and thoses that are not null in data, will be enabled.
Precondition
Field Unit_Id_FK must contain a valid ID (not Null)
Definition at line 65 of file mdtClUnitConnectionDialog.cpp.
References data(), and mdtSqlRecord::value().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitConnectionDialog.h
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitConnectionDialog.cpp