Multi diag tools: mdtTtTestLinkData Class Reference
mdtTtTestLinkData Class Reference
Data container for test link.
#include <mdtTtTestLinkData.h>
Public Member Functions
mdtTtTestLinkData ()
Construct a empty test link data.
mdtTtTestLinkData (const QSqlRecord &record)
Construct a test link data based on given record.
bool setup (const QSqlDatabase &db)
Setup test link data fields.
Public Member Functions inherited from mdtSqlRecord
mdtSqlRecord ()
Constructor.
mdtSqlRecord (const QSqlRecord &sqlRecord)
Build a mdtSqlRecord on the base of a QSqlRecord.
virtual ~mdtSqlRecord ()
Destructor.
operator QSqlRecord () const
Get QSqlRecord version.
bool addField (const QString &fieldName, const QString &tableName, const QSqlDatabase &db)
Add a field to record.
bool addAllFields (const QString &tableName, const QSqlDatabase &db)
Add all fields of given table to record.
int count () const
Returns the number of fields in the record.
bool isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
QSqlField field (int index) const
Returns the field at position index.
QSqlField field (const QString &name) const
Returns the field called name.
int indexOf (const QString &name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
bool contains (const QString &name) const
Returns true if there is a field in the record called name; otherwise returns false.
QStringList fieldNames () const
Get a list with all field names.
bool hasValue (int fieldIndex) const
Check if a value was set.
bool hasValue (const QString &fieldName) const
Check if a value was set.
void setValue (int fieldIndex, const QVariant &val)
Set value.
void setValue (const QString &fieldName, const QVariant &val)
Set value.
QVariant value (int index) const
Returns the value of the field located at position index in the record.
QVariant value (const QString &name) const
Returns the value of the field called name in the record.
virtual void clear ()
Removes all the record's fields.
virtual void clearValues ()
Clear values.
mdtError lastError () const
Get last error.
QVector< int > fieldIndexesWithValue () const
Get a list with field indexes that have a value.
QString sqlForInsert (const QString &tableName) const
Get SQL statement for insertion with QSqlQuery.
QString sqlForUpdate (const QString &tableName, const QSqlRecord &matchData) const
Get SQL statement for update with QSqlQuery.
QString dataToUpdateInfo () const
Get information about data that has a value to update (for debug)
Additional Inherited Members
Static Public Member Functions inherited from mdtSqlRecord
static QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtSqlRecord
mdtError pvLastError
Detailed Description
Data container for test link.
Definition at line 28 of file mdtTtTestLinkData.h.
Constructor & Destructor Documentation
mdtTtTestLinkData::mdtTtTestLinkData ()
Construct a empty test link data.
Definition at line 23 of file mdtTtTestLinkData.cpp.
mdtTtTestLinkData::mdtTtTestLinkData (const QSqlRecord & record)
Construct a test link data based on given record.
Precondition
record must contain all fields from TestLink_tbl
Definition at line 28 of file mdtTtTestLinkData.cpp.
References mdtSqlRecord::contains().
Member Function Documentation
bool mdtTtTestLinkData::setup (const QSqlDatabase & db)
Setup test link data fields.
Definition at line 39 of file mdtTtTestLinkData.cpp.
References mdtSqlRecord::addAllFields(), and mdtSqlRecord::clear().
Referenced by mdtTtTestLinkDialog::mdtTtTestLinkDialog().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestLinkData.h
src/mdttools/mdttesttool/mdtTtTestLinkData.cpp