Multi diag tools: mdtStateMachine Class Reference
mdtStateMachine Class Reference
Extend Qt's QStateMachine.
#include <mdtStateMachine.h>
Signals
void stateChanged (int id)
Emitted each time the state changed.
void stateChangedForUi (int id, const QString &text, int ledColorId, bool ledIsOn)
Emitted only if a state that must be notified is entered.
Public Member Functions
mdtStateMachine (QObject *parent=0)
Constructor.
virtual ~mdtStateMachine ()
Destructor.
void start (bool waitStarted)
Start state machine.
void stop (bool waitStopped)
Stop state machine.
int currentState () const
Get current state.
bool waitOnState (int state, int timeout=-1)
Wait until a state is reached.
bool waitOnOneState (const QVector< int > &states, int timeout=-1)
Wait until a state is reached.
void notifyCurrentState ()
Notify current state.
Detailed Description
Extend Qt's QStateMachine.
QStateMachine provides all that is needed to build a state machine. But, for some application, some other things can be usefull:
Get current state
Wait until a state was reached
Notify only some states to the (G)UI
Usually, a system based on a state machine is only event driven, and QStateMachine was build this way. But, for some application, we need to be able to wait until a state is reached, without breaking application's event loop, before we can continue.
Definition at line 44 of file mdtStateMachine.h.
Constructor & Destructor Documentation
mdtStateMachine::mdtStateMachine (QObject * parent = 0)
Constructor.
Current state will be set to -1 (invalid).
Definition at line 27 of file mdtStateMachine.cpp.
mdtStateMachine::~mdtStateMachine () virtual
Destructor.
Definition at line 39 of file mdtStateMachine.cpp.
Member Function Documentation
int mdtStateMachine::currentState () const
Get current state.
Definition at line 65 of file mdtStateMachine.cpp.
References mdtState::id().
Referenced by mdtAbstractSqlTableController::currentState(), mdtPortManager::currentState(), waitOnOneState(), and waitOnState().
void mdtStateMachine::notifyCurrentState ()
Notify current state.
Will emit stateChanged() and stateChangedForUi() (if required by state).
In normal way, signals are emitted when state changes. In some situation, it can be usefull to call this method explicitly (see mdtPortManager::notifyCurrentState() for a example).
Definition at line 113 of file mdtStateMachine.cpp.
References mdtState::id(), mdtState::ledColorId(), mdtState::ledIsOn(), mdtState::notifyEnteredToUi(), stateChanged(), stateChangedForUi(), and mdtState::text().
Referenced by mdtPortManager::notifyCurrentState().
void mdtStateMachine::start (bool waitStarted)
Start state machine.
Parameters
waitStarted If true, call will return only when state machine has started (will not break event loop)
Definition at line 43 of file mdtStateMachine.cpp.
Referenced by mdtPortManagerStateMachine::buildMainStateMachine(), and mdtAbstractSqlTableController::start().
void mdtStateMachine::stateChanged (int id) signal
Emitted each time the state changed.
Referenced by mdtPortManagerStateMachine::buildMainStateMachine(), and notifyCurrentState().
void mdtStateMachine::stateChangedForUi (int id, const QString & text, int ledColorId, bool ledIsOn) signal
Emitted only if a state that must be notified is entered.
See Also
mdtState::notifyEnteredToUi()
Referenced by mdtPortManagerStateMachine::buildMainStateMachine(), and notifyCurrentState().
void mdtStateMachine::stop (bool waitStopped)
Stop state machine.
Parameters
waitStopped If true, call will return only when state machine is stopped (will not break event loop)
Definition at line 54 of file mdtStateMachine.cpp.
Referenced by mdtAbstractSqlTableController::stop().
bool mdtStateMachine::waitOnOneState (const QVector< int > & states, int timeout = -1)
Wait until a state is reached.
This wait method will let the application's event loop continue working, so it will not freeze GUI.
Parameters
states Wait of one of state in the list. If one is reached before timeout, this method returns true
timeout Maximum time to wait [ms]. Value < 0 means a infinite timeout.
Returns
True on success, false on timeout.
Definition at line 93 of file mdtStateMachine.cpp.
References currentState().
bool mdtStateMachine::waitOnState (int state, int timeout = -1)
Wait until a state is reached.
This wait method will let the application's event loop continue working, so it will not freeze GUI.
Parameters
state ID if state on witch to wait.
timeout Maximum time to wait [ms]. Value < 0 means a infinite timeout.
Returns
True on success, false on timeout.
Definition at line 73 of file mdtStateMachine.cpp.
References currentState().
Referenced by mdtPortManagerStateMachine::buildMainStateMachine(), mdtAbstractSqlTableController::select(), mdtAbstractSqlTableController::setFilter(), and mdtPortManager::stop().
The documentation for this class was generated from the following files:
src/mdtutils/mdtStateMachine.h
src/mdtutils/mdtStateMachine.cpp