Multi diag tools: mdtClArticle Class Reference
mdtClArticle Class Reference
Helper class for Article and related tables edition.
#include <mdtClArticle.h>
Public Member Functions
mdtClArticle (QObject *parent, QSqlDatabase db)
Constructor.
~mdtClArticle ()
Destructor.
QString sqlForArticleComponentSelection (const QVariant &articleId) const
Get SQL statement for article component selection.
bool addComponent (const QVariant &articleId, const QVariant &componentId, const QVariant &qty, const QVariant &qtyUnit)
Add a article as component.
bool editComponent (const QVariant &articleId, const QVariant &currentComponentId, const QVariant &newComponentId, const QVariant &qty, const QVariant &qtyUnit)
Edit a component.
bool removeComponent (const QVariant &articleId, const QVariant &componentId)
Remove a single component.
bool removeComponents (const QVariant &articleId, const QList< QVariant > &componentIdList)
Remove a list of components.
bool removeComponents (const QVariant &articleId, const QModelIndexList &indexListOfSelectedRows)
Remove each component that is contained in selection.
QList< QSqlRecord > getConnectorContactDataList (const QList< QVariant > &connectorContactIdList, bool *ok)
Get a list of connector contact data for given connector contact ID list.
mdtClArticleConnectionData getConnectionData (const QVariant &articleConnectionId, bool *ok)
Get article connection data for given article connection ID.
QList< mdtClArticleConnectionData > getConnectionDataListFromConnectionIdList (const QList< QVariant > &connectionIdList, bool *ok)
Get a list af article connection data from given article connection ID list.
mdtClArticleConnectorData getConnectorData (const QVariant &articleConnectorId, bool *ok, bool includeConnectionData, bool includeBaseConnectorData)
Get article connector data for given article connector ID.
bool addConnectionDataListFromConnectorContactIdList (mdtClArticleConnectorData &data, const QList< QVariant > &connectorContactIdList)
Add article connections into article connector data based on a list of given connector contact ID list.
bool addConnection (const mdtClArticleConnectionData &data)
Add a connection.
bool editConnection (const QVariant &connectionId, const mdtClArticleConnectionData &data)
Edit a article connection.
bool removeConnection (const QVariant &articleConnectionId)
Remove a single connection.
bool removeConnections (const QList< QVariant > &articleConnectionIdList)
Remove connections.
bool removeConnections (const QModelIndexList &indexListOfSelectedRows)
Remove each connection that is contained in selection.
bool removeConnectorConnections (const QVariant &articleConnectorId)
Remove connections for a given article connector.
bool removeConnectorsConnections (const QList< QVariant > &articleConnectorIdList)
Remove connections for a given list article connectors.
bool addConnector (const mdtClArticleConnectorData &data)
Add a connector.
bool editConnectorName (const QVariant &articleConnectorId, const QVariant &name)
Edit connector name.
bool removeConnector (const QVariant &articleConnectorId)
Remove a connector and all its contacts.
bool removeConnectors (const QModelIndexList &indexListOfSelectedRows)
Remove each connector that is contained in selection.
bool addLink (const mdtSqlRecord &linkData)
Add a record in Link table.
bool addCableLink (const QVariant &articleConnectionStartId, const QVariant &articleConnectionEndId, const QVariant &identification, const QVariant &R)
Add a cable link.
bool editLink (const QVariant &articleConnectionStartId, const QVariant &articleConnectionEndId, const mdtSqlRecord &data)
Add a link of type resistor.
bool removeLink (const QVariant &articleConnectionStartId, const QVariant &articleConnectionEndId)
Remove a signle link.
bool removeLinks (const QList< QModelIndexList > &indexListOfSelectedRowsByRows)
Remove each unit link that is contained in selection.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
bool addRecordList (const QList< mdtSqlRecord > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for Article and related tables edition.
Definition at line 39 of file mdtClArticle.h.
Constructor & Destructor Documentation
mdtClArticle::mdtClArticle (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 30 of file mdtClArticle.cpp.
mdtClArticle::~mdtClArticle ()
Destructor.
Definition at line 35 of file mdtClArticle.cpp.
Member Function Documentation
bool mdtClArticle::addCableLink (const QVariant & articleConnectionStartId, const QVariant & articleConnectionEndId, const QVariant & identification, const QVariant & R)
Add a cable link.
Definition at line 532 of file mdtClArticle.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, and mdtSqlRecord::setValue().
bool mdtClArticle::addComponent (const QVariant & articleId, const QVariant & componentId, const QVariant & qty, const QVariant & qtyUnit)
Add a article as component.
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 55 of file mdtClArticle.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtClArticle::addConnection (const mdtClArticleConnectionData & data)
Add a connection.
Definition at line 306 of file mdtClArticle.cpp.
References mdtTtBase::addRecord().
bool mdtClArticle::addConnectionDataListFromConnectorContactIdList (mdtClArticleConnectorData & data, const QList< QVariant > & connectorContactIdList)
Add article connections into article connector data based on a list of given connector contact ID list.
Will also get some values from data (ArticleConnector_tbl) and set it to created connections (ArticleConnection_tbl):
ArticleConnector_tbl.Id_PK -> ArticleConnection_tbl.ArticleConnector_Id_FK
ArticleConnector_tbl.Article_Id_FK -> ArticleConnection_tbl.Article_Id_FK
Note: will only update given data, nothing is written to database.
Definition at line 277 of file mdtClArticle.cpp.
References mdtClArticleConnectorData::addConnectionData(), mdtSqlRecord::clearValues(), mdtTtBase::database(), getConnectorContactDataList(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtClArticleConnectionData::setup(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
bool mdtClArticle::addConnector (const mdtClArticleConnectorData & data)
Add a connector.
If given article connector contains connections, they will be added.
Note: in connection data (contained in data), Article_Id_FK and ArticleConnector_Id_FK are not relevant, because they are token from data directly.
Definition at line 412 of file mdtClArticle.cpp.
References mdtTtBase::addRecord(), mdtTtBase::addRecordList(), mdtTtBase::beginTransaction(), mdtError::commit(), mdtTtBase::commitTransaction(), mdtClArticleConnectorData::connectionDataList(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtTtBase::rollbackTransaction(), mdtError::setError(), mdtError::setSystemError(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
bool mdtClArticle::addLink (const mdtSqlRecord & linkData)
Add a record in Link table.
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 527 of file mdtClArticle.cpp.
References mdtTtBase::addRecord().
bool mdtClArticle::editComponent (const QVariant & articleId, const QVariant & currentComponentId, const QVariant & newComponentId, const QVariant & qty, const QVariant & qtyUnit)
Edit a component.
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 88 of file mdtClArticle.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtClArticle::editConnection (const QVariant & connectionId, const mdtClArticleConnectionData & data)
Edit a article connection.
Definition at line 311 of file mdtClArticle.cpp.
References mdtTtBase::updateRecord().
bool mdtClArticle::editConnectorName (const QVariant & articleConnectorId, const QVariant & name)
Edit connector name.
Definition at line 469 of file mdtClArticle.cpp.
References getConnectorData(), mdtSqlRecord::setValue(), and mdtTtBase::updateRecord().
bool mdtClArticle::editLink (const QVariant & articleConnectionStartId, const QVariant & articleConnectionEndId, const mdtSqlRecord & data)
Add a link of type resistor.
Returns
True on success, false else. To get reason of failure, use lastError() .
Add a link of type diode
Add a link of type bridge
Returns
True on success, false else. To get reason of failure, use lastError() .
Edit a record in Link table
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 567 of file mdtClArticle.cpp.
References mdtSqlRecord::addField(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtSqlRecord::setValue(), and mdtTtBase::updateRecord().
mdtClArticleConnectionData mdtClArticle::getConnectionData (const QVariant & articleConnectionId, bool * ok)
Get article connection data for given article connection ID.
Precondition
ok must be a valid pointer.
Definition at line 201 of file mdtClArticle.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::Warning.
QList< mdtClArticleConnectionData > mdtClArticle::getConnectionDataListFromConnectionIdList (const QList< QVariant > & connectionIdList, bool * ok)
Get a list af article connection data from given article connection ID list.
Definition at line 219 of file mdtClArticle.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList().
QList< QSqlRecord > mdtClArticle::getConnectorContactDataList (const QList< QVariant > & connectorContactIdList, bool * ok)
Get a list of connector contact data for given connector contact ID list.
Note: result will contain data from ConnectorContact_tbl
Definition at line 176 of file mdtClArticle.cpp.
References mdtTtBase::getData().
Referenced by addConnectionDataListFromConnectorContactIdList(), and mdtClUnit::addConnectionDataListFromConnectorContactIdList().
mdtClArticleConnectorData mdtClArticle::getConnectorData (const QVariant & articleConnectorId, bool * ok, bool includeConnectionData, bool includeBaseConnectorData)
Get article connector data for given article connector ID.
Parameters
includeConnectionData If true, and SQL statement points to a article connector that contains article connections, result will be populated with these article connection data.
includeBaseConnectorData If true, and SQL statement points to a article connector that is based on a connector (from Connector_tbl), result will be populated with these connector data.
Precondition
ok must be valid
Definition at line 259 of file mdtClArticle.cpp.
References mdtError::commit(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::Warning.
Referenced by mdtClUnit::addArticleConnectorData(), and editConnectorName().
bool mdtClArticle::removeComponent (const QVariant & articleId, const QVariant & componentId)
Remove a single component.
Definition at line 125 of file mdtClArticle.cpp.
References mdtTtBase::removeData().
bool mdtClArticle::removeComponents (const QVariant & articleId, const QList< QVariant > & componentIdList)
Remove a list of components.
Definition at line 130 of file mdtClArticle.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by removeComponents().
bool mdtClArticle::removeComponents (const QVariant & articleId, const QModelIndexList & indexListOfSelectedRows)
Remove each component that is contained in selection.
This is usefull used together with mdtSqlTableWidget .
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 164 of file mdtClArticle.cpp.
References removeComponents().
bool mdtClArticle::removeConnection (const QVariant & articleConnectionId)
Remove a single connection.
Definition at line 316 of file mdtClArticle.cpp.
References removeConnections().
bool mdtClArticle::removeConnections (const QList< QVariant > & articleConnectionIdList)
Remove connections.
Definition at line 325 of file mdtClArticle.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by removeConnection(), and removeConnections().
bool mdtClArticle::removeConnections (const QModelIndexList & indexListOfSelectedRows)
Remove each connection that is contained in selection.
This is usefull used together with mdtSqlTableWidget .
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 358 of file mdtClArticle.cpp.
References removeConnections().
bool mdtClArticle::removeConnector (const QVariant & articleConnectorId)
Remove a connector and all its contacts.
Definition at line 483 of file mdtClArticle.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::removeData(), and mdtTtBase::rollbackTransaction().
bool mdtClArticle::removeConnectorConnections (const QVariant & articleConnectorId)
Remove connections for a given article connector.
If single transaction is set, a transaction is used .
Definition at line 370 of file mdtClArticle.cpp.
References removeConnectorsConnections().
bool mdtClArticle::removeConnectors (const QModelIndexList & indexListOfSelectedRows)
Remove each connector that is contained in selection.
Will also remove related connections.
This is usefull used together with mdtSqlTableWidget .
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 505 of file mdtClArticle.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::removeData(), and mdtTtBase::rollbackTransaction().
bool mdtClArticle::removeConnectorsConnections (const QList< QVariant > & articleConnectorIdList)
Remove connections for a given list article connectors.
Definition at line 379 of file mdtClArticle.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by removeConnectorConnections().
bool mdtClArticle::removeLink (const QVariant & articleConnectionStartId, const QVariant & articleConnectionEndId)
Remove a signle link.
Returns
True on success, false else. To get reason of failure, use lastError() .
Definition at line 586 of file mdtClArticle.cpp.
References mdtTtBase::removeData().
Referenced by removeLinks().
bool mdtClArticle::removeLinks (const QList< QModelIndexList > & indexListOfSelectedRowsByRows)
Remove each unit link that is contained in selection.
Definition at line 591 of file mdtClArticle.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), removeLink(), and mdtTtBase::rollbackTransaction().
QString mdtClArticle::sqlForArticleComponentSelection (const QVariant & articleId) const
Get SQL statement for article component selection.
Definition at line 39 of file mdtClArticle.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClArticle.h
src/mdttools/mdttesttool/mdtcablelist/mdtClArticle.cpp