Multi diag tools: mdtSqlForm Class Reference
mdtSqlForm Class Reference
Base class for high level SQL widgets API.
#include <mdtSqlForm.h>
Public Member Functions
mdtSqlForm (QWidget *parent, QSqlDatabase db)
Constructor.
virtual ~mdtSqlForm ()
Destructor.
void setMainTableWidget (QWidget *widget)
Set main table widget.
template<typename T >
void setMainTableUi ()
Set main table UI.
template<typename T >
void setMainTableUi (T &ui)
Set main table UI.
virtual void addMenus (QMenuBar *menuBar)
Add menus to menu bar.
bool setMainTable (const QString &tableName, const QString &userFriendlyTableName, const QString &firstWidgetInTabOrder=QString())
Set the main (or parent) table of the form.
bool setMainTable (const QString &tableName, const QString &userFriendlyTableName, QSqlDatabase db, const QString &firstWidgetInTabOrder=QString())
Set the main (or parent) table of the form.
bool addChildTable (const mdtSqlRelationInfo &relationInfo, const QString &userFriendlyTableName)
Add a child table to the form.
bool addChildTable (const mdtSqlRelationInfo &relationInfo, const QString &userFriendlyTableName, QSqlDatabase db)
Add a child table to the form.
void addChildWidget (QWidget *widget, const QString &label, const QIcon &icon=QIcon())
Add a widget to the internal QTabWidget.
void start ()
Start internal state machines.
template<typename T >
std::shared_ptr< T > mainTableController ()
Get main table controller.
template<typename T >
std::shared_ptr< T > tableController (const QString &tableName)
Get a table controller.
mdtSqlTableWidget * sqlTableWidget (const QString &tableName)
QSqlDatabase database ()
Get database that was given by constructor.
bool select ()
Call select on model that acts on main table name.
bool select (const QString &tableName)
Call select on model that acts on given table name.
bool setMainTableFilter (const QString &filter)
Set a filter on main table.
bool setMainTableFilter (const QString &fieldName, const QVariant &matchData)
Set a filter on main table.
bool setMainTableFilter (const QString &fieldName, const QList< QVariant > &matchDataList)
Set a filter on main table.
void clearMainTableFilter ()
Clear filter of main table.
mdtError lastError () const
Get last error.
void displayLastError ()
Display last error in a message box.
int rowCount (const QString &tableName, bool fetchAll=false)
Get row count for given tableName.
bool setCurrentRow (const QString &fieldName, const QVariant &matchData)
Set the first row that matches given criteria as current row.
bool setCurrentRow (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Set the first row that matches given criteria as current row.
bool setCurrentData (const QString &tableName, const QString &fieldName, const QVariant &data, bool submit=true)
Set (update) data of current row (record) for given table and field name.
QVariant currentData (const QString &tableName, const QString &fieldName)
Get current data for given table and field name.
QVariant currentData (const QString &tableName, const QString &fieldName, bool &ok)
Get current data for given table and field name.
QVariant data (const QString &tableName, int row, const QString &fieldName)
Get data for given table , row and field name.
QVariant data (const QString &tableName, int row, const QString &fieldName, bool &ok)
Get data for given table , row and field name.
QList< QVariant > dataList (const QString &tableName, const QString &fieldName, bool fetchAll=true)
Get a list of data for given table and field name.
QList< QVariant > dataList (const QString &tableName, const QString &fieldName, bool &ok, bool fetchAll=true)
Get a list of data for given table and field name.
void insert ()
Call insert method on main table controller.
virtual bool setupTables ()
Setup tables.
bool allDataAreSaved ()
Check if all data are saved.
Protected Attributes
mdtError pvLastError
Detailed Description
Base class for high level SQL widgets API.
To create SQL GUI's, some clases are available:
mdtAbstractSqlTableController
mdtSqlDataWidgetController
mdtSqlTableViewController
mdtSqlTableWidget
They help to deal with several common problems, but they need several code (creating objects, configure them, handle memory, ...).
This class was made to have less code for common database GUI .
When adding child table with addChildTable() , a instance of mdtSqlTableWidget is created, and placed to a QTabWidget . It is also possible to add a non database related widget, using addChildWidget() . In this case, the given widget is simply added to the internal QTabWidget .
Definition at line 62 of file mdtSqlForm.h.
Constructor & Destructor Documentation
mdtSqlForm::mdtSqlForm (QWidget * parent, QSqlDatabase db)
Constructor.
Given database will be used whenn adding new tables with setMainTable(const QString&, const QString&) and addChildTable(const QString&, const QString&) .
database() will also return this version .
Definition at line 36 of file mdtSqlForm.cpp.
mdtSqlForm::~mdtSqlForm () virtual
Destructor.
Definition at line 47 of file mdtSqlForm.cpp.
Member Function Documentation
bool mdtSqlForm::addChildTable (const mdtSqlRelationInfo & relationInfo, const QString & userFriendlyTableName)
Add a child table to the form.
Parameters
relationInfo Informations about relation between main table and child table to create (note: parent table name is not used).
userFriendlyTableName If set, will be used at places that are visible from user.
Returns
True on success, false if given table name does not exist or on some other errors (database not open, access privileges, ...). False can also be returned if main table was not set (see setMainTable()).
Definition at line 93 of file mdtSqlForm.cpp.
bool mdtSqlForm::addChildTable (const mdtSqlRelationInfo & relationInfo, const QString & userFriendlyTableName, QSqlDatabase db)
Add a child table to the form.
This method is only useful if different tables have to act on different databases .
Parameters
relationInfo Informations about relation between main table and child table to create (note: parent table name is not used).
userFriendlyTableName If set, will be used at places that are visible from user.
db Database to use.
Returns
True on success, false if given table name does not exist or on some other errors (database not open, access privileges, ...). False can also be returned if main table was not set (see setMainTable()).
Definition at line 98 of file mdtSqlForm.cpp.
References addChildWidget(), mdtSqlRelationInfo::childTableName(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtSqlTableWidget::setTableController(), and mdtSqlTableWidget::userFriendlyTableName().
void mdtSqlForm::addChildWidget (QWidget * widget, const QString & label, const QIcon & icon = QIcon())
Add a widget to the internal QTabWidget.
Can be used if a widget that is not related to a database table must be placed in the QTabWidget .
Note: the given widget will be reparented, and also deleted when the form is destroyed .
Definition at line 134 of file mdtSqlForm.cpp.
Referenced by addChildTable().
virtual void mdtSqlForm::addMenus (QMenuBar * menuBar) inline virtual
Add menus to menu bar.
This method is called by mdtSqlWindow, and let subclass (of mdtSqlForm) add menus. Add all needed stuff using given menuBar pointer.
This default implementation dows nothing.
Reimplemented in mdtTtTestCableEditor.
Definition at line 120 of file mdtSqlForm.h.
Referenced by mdtSqlWindow::setSqlForm().
bool mdtSqlForm::allDataAreSaved () inline
Check if all data are saved.
Will call allDataAreSaved() on main table controller.
Returns
true if all data are saved, false if a SQL table controller has pending data.
Definition at line 454 of file mdtSqlForm.h.
Referenced by mdtSqlDialog::accept(), mdtSqlApplicationWidgets< T >::closeOpenSqlWindows(), and mdtSqlDialog::reject().
void mdtSqlForm::clearMainTableFilter () inline
Clear filter of main table.
Precondition
Main table must be set with setMainTable()
Internal state machine must run (see start()).
Definition at line 306 of file mdtSqlForm.h.
QVariant mdtSqlForm::currentData (const QString & tableName, const QString & fieldName) inline
Get current data for given table and field name.
Note that SQL table controller related to given tableName is searched at each request. If several access to setCurrentData is needed, it can be better to get a pointer to related controller with tableController() , and call his currentData() method.
Returns
Current value, or a invalid QVariant on error (f.ex. table or field not found).
Definition at line 375 of file mdtSqlForm.h.
QVariant mdtSqlForm::currentData (const QString & tableName, const QString & fieldName, bool & ok)
Get current data for given table and field name.
Note that SQL table controller related to given tableName is searched at each request. If several access to setCurrentData is needed, it can be better to get a pointer to related controller with tableController() , and call his currentData() method.
Returns
Current value, or a invalid QVariant on error (f.ex. table or field not found).
Definition at line 256 of file mdtSqlForm.cpp.
QVariant mdtSqlForm::data (const QString & tableName, int row, const QString & fieldName) inline
Get data for given table , row and field name.
Note that SQL table controller related to given tableName is searched at each request. If several access to setCurrentData is needed, it can be better to get a pointer to related controller with tableController() , and call his data() method.
Returns
Current value, or a invalid QVariant on error (f.ex. table, row or field not found).
Definition at line 401 of file mdtSqlForm.h.
QVariant mdtSqlForm::data (const QString & tableName, int row, const QString & fieldName, bool & ok)
Get data for given table , row and field name.
Note that SQL table controller related to given tableName is searched at each request. If several access to setCurrentData is needed, it can be better to get a pointer to related controller with tableController() , and call his data() method.
Returns
Current value, or a invalid QVariant on error (f.ex. table, row or field not found).
Definition at line 266 of file mdtSqlForm.cpp.
QSqlDatabase mdtSqlForm::database () inline
Get database that was given by constructor.
Definition at line 228 of file mdtSqlForm.h.
QList<QVariant> mdtSqlForm::dataList (const QString & tableName, const QString & fieldName, bool fetchAll = true) inline
Get a list of data for given table and field name.
If fetchAll is true, all available data will be fetched from database (regarding applied filter), else only cached data are returned (see QSqlQueryModel::fetchMore() for details).
Definition at line 424 of file mdtSqlForm.h.
QList< QVariant > mdtSqlForm::dataList (const QString & tableName, const QString & fieldName, bool & ok, bool fetchAll = true)
Get a list of data for given table and field name.
If fetchAll is true, all available data will be fetched from database (regarding applied filter), else only cached data are returned (see QSqlQueryModel::fetchMore() for details).
Definition at line 276 of file mdtSqlForm.cpp.
void mdtSqlForm::displayLastError ()
Display last error in a message box.
Definition at line 207 of file mdtSqlForm.cpp.
References mdtError::informativeText(), mdtError::levelIcon(), pvLastError, mdtError::systemText(), and mdtError::text().
Referenced by mdtTtTestModelItemEditor::setSequenceNumber(), and mdtTtTestModelItemEditor::setTestModelId().
void mdtSqlForm::insert () inline
Call insert method on main table controller.
Definition at line 440 of file mdtSqlForm.h.
mdtError mdtSqlForm::lastError () const
Get last error.
Definition at line 202 of file mdtSqlForm.cpp.
References pvLastError.
template<typename T > std::shared_ptr<T> mdtSqlForm::mainTableController () inline
Get main table controller.
Can return a Null pointer if no controller is assigned to rquested table, or it exists, but is not of requested type T.
Definition at line 201 of file mdtSqlForm.h.
int mdtSqlForm::rowCount (const QString & tableName, bool fetchAll = false)
Get row count for given tableName.
Note: this will search internall controller at each request. If repeated calls of this method is required, get a instance of needed controller with tableController(), and call its rowCount() method.
Definition at line 218 of file mdtSqlForm.cpp.
bool mdtSqlForm::select ()
Call select on model that acts on main table name.
Returns
True on success, false on error. On failure, the last error is avaliable with lastError()
Definition at line 169 of file mdtSqlForm.cpp.
References pvLastError.
bool mdtSqlForm::select (const QString & tableName)
Call select on model that acts on given table name.
Returns
True on success, false if tableName was not found or other error. On failure, the last error is avaliable with lastError()
Definition at line 178 of file mdtSqlForm.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
bool mdtSqlForm::setCurrentData (const QString & tableName, const QString & fieldName, const QVariant & data, bool submit = true)
Set (update) data of current row (record) for given table and field name.
Note that SQL table controller related to given tableName is searched at each request. If several access to setCurrentData is needed, it can be better to get a pointer to related controller with tableController() , and call his setCurrentData() method.
Definition at line 242 of file mdtSqlForm.cpp.
References pvLastError.
Referenced by mdtTtTestModelItemEditor::setSequenceNumber(), and mdtTtTestModelItemEditor::setTestModelId().
bool mdtSqlForm::setCurrentRow (const QString & fieldName, const QVariant & matchData) inline
Set the first row that matches given criteria as current row.
This variant will act on main table controller.
Parameters
fieldName Field that must contain searched value
value Value that must matche
Returns
True if matching record was found (in this case, setCurrentIndex() is called on sql widget witch acts on main table to update currentRow), false else.
Definition at line 337 of file mdtSqlForm.h.
References pvLastError.
bool mdtSqlForm::setCurrentRow (const QString & tableName, const QString & fieldName, const QVariant & matchData)
Set the first row that matches given criteria as current row.
Parameters
tableName The controller acting on this table name is used.
fieldName Field that must contain searched value
value Value that must matche
Returns
True if matching record was found (in this case, setCurrentIndex() is called on sql widget witch acts on main table to update currentRow), false else.
Definition at line 228 of file mdtSqlForm.cpp.
References pvLastError.
bool mdtSqlForm::setMainTable (const QString & tableName, const QString & userFriendlyTableName, const QString & firstWidgetInTabOrder = QString())
Set the main (or parent) table of the form.
Note: call setMainTableUi() or setMainTableWidget() before, else no data widget will be mapped. See mdtSqlDataWidgetController for details.
Parameters
tableName Table on witch the form must act.
userFriendlyTableName If set, will be used at places that are visible from user.
firstWidgetInTabOrder It's possible to specify the object name of the first widget in tab order. This is then used by insertion to give this widget the focus.
Returns
True on success, false if given table name does not exist or on some other errors (database not open, access privileges, ...)
Definition at line 60 of file mdtSqlForm.cpp.
bool mdtSqlForm::setMainTable (const QString & tableName, const QString & userFriendlyTableName, QSqlDatabase db, const QString & firstWidgetInTabOrder = QString())
Set the main (or parent) table of the form.
Note: call setMainTableUi() or setMainTableWidget() before, else no data widget will be mapped. See mdtSqlDataWidgetController for details.
This method is only useful if different tables have to act on different databases .
Parameters
tableName Table on witch the form must act.
userFriendlyTableName If set, will be used at places that are visible from user.
db Database to use (pass a QSqlDatabase() if only one database is used).
firstWidgetInTabOrder It's possible to specify the object name of the first widget in tab order. This is then used by insertion to give this widget the focus.
Returns
True on success, false if given table name does not exist or on some other errors (database not open, access privileges, ...)
Definition at line 65 of file mdtSqlForm.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
bool mdtSqlForm::setMainTableFilter (const QString & filter) inline
Set a filter on main table.
Set filter based on SQL query WHERE part, without the WHERE keyword (f.ex. Id_PK = 15)
Note: if internal controller's model is allready populated with data, i.e. select() was called before, filter is applied directly, else, select must be called explicitly after setMainTableFilter() (this is the same behaviour as QSqlTableModel).
Precondition
Main table must be set with setMainTable()
Internal state machine must run (see start()).
Definition at line 256 of file mdtSqlForm.h.
bool mdtSqlForm::setMainTableFilter (const QString & fieldName, const QVariant & matchData) inline
Set a filter on main table.
Parameters
fieldName Field that must match data
matchData Match data
Internally, a SQL statement is generated linke: fieldName = matchData
Note: if internal controller's model is allready populated with data, i.e. select() was called before, filter is applied directly, else, select must be called explicitly after setMainTableFilter() (this is the same behaviour as QSqlTableModel).
Precondition
Main table must be set with setMainTable()
Internal state machine must run (see start()).
Definition at line 276 of file mdtSqlForm.h.
bool mdtSqlForm::setMainTableFilter (const QString & fieldName, const QList< QVariant > & matchDataList) inline
Set a filter on main table.
Parameters
fieldName Field that must match data
matchDataList A list of match data
Internally, a SQL statement is generated linke: fieldName IN (matchData[0], matchData[1], ...)
Note: if internal controller's model is allready populated with data, i.e. select() was called before, filter is applied directly, else, select must be called explicitly after setMainTableFilter() (this is the same behaviour as QSqlTableModel).
Precondition
Main table must be set with setMainTable()
Internal state machine must run (see start()).
Definition at line 296 of file mdtSqlForm.h.
template<typename T > void mdtSqlForm::setMainTableUi () inline
Set main table UI.
Usefull for UI created with QtDesigner
Definition at line 94 of file mdtSqlForm.h.
template<typename T > void mdtSqlForm::setMainTableUi (T & ui) inline
Set main table UI.
Usefull for UI created with QtDesigner
Definition at line 105 of file mdtSqlForm.h.
References setMainTableWidget().
void mdtSqlForm::setMainTableWidget (QWidget * widget)
Set main table widget.
If you have a UI file generated from QtDesigner, witch has a setupUi() method, simply use setMainTableUi()
Definition at line 51 of file mdtSqlForm.cpp.
Referenced by setMainTableUi().
bool mdtSqlForm::setupTables () virtual
Setup tables.
Must be re-implemented in subclass, default implementation does nothing .
Reimplemented in mdtClUnitEditor, mdtClArticleEditor, mdtClVehicleTypeEditor, mdtClWireEditor, mdtTtLogicalTestCableEditor, mdtTtTestCableEditor, mdtClConnectorEditor, mdtTtTestNodeEditor, mdtClLinkBeamEditor, mdtTtTestModelItemEditor, and mdtTtTestModelEditor.
Definition at line 286 of file mdtSqlForm.cpp.
mdtSqlTableWidget * mdtSqlForm::sqlTableWidget (const QString & tableName)
Get instance of the stored SQL table widget related to a table name
Definition at line 155 of file mdtSqlForm.cpp.
void mdtSqlForm::start ()
Start internal state machines.
Will start state machine of each contained SQL widget. This method is called by mdtSqlWindow and mdtSqlDialog.
Definition at line 150 of file mdtSqlForm.cpp.
Referenced by mdtSqlWindow::setSqlForm(), and mdtSqlDialog::setSqlForm().
template<typename T > std::shared_ptr<T> mdtSqlForm::tableController (const QString & tableName) inline
Get a table controller.
Can return a Null pointer if no controller is assigned to rquested table, or it exists, but is not of requested type T.
Definition at line 213 of file mdtSqlForm.h.
Member Data Documentation
mdtError mdtSqlForm::pvLastError protected
Definition at line 458 of file mdtSqlForm.h.
Referenced by addChildTable(), displayLastError(), lastError(), select(), setCurrentData(), setCurrentRow(), and setMainTable().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlForm.h
src/mdtdatabase/mdtSqlForm.cpp