Multi diag tools: mdtTtTestModelItemRouteData Class Reference
mdtTtTestModelItemRouteData Class Reference
Container for test model item route data.
#include <mdtTtTestModelItemRouteData.h>
Public Member Functions
mdtTtTestModelItemRouteData ()
Construct a empty route data.
mdtTtTestModelItemRouteData (const QSqlRecord &record)
Construct data from a sql record.
void clearData ()
Clear.
void setId (const QVariant &id)
Set ID.
QVariant id () const
Get ID.
void setTestModelItemId (const QVariant &id)
Set test model item ID.
QVariant testModelItemId () const
Get test model item ID.
void setTestLinkId (const QVariant &id)
Set test link ID.
QVariant testLinkId () const
Get test link ID.
void setDutConnectionId (const QVariant &id)
Set DUT connection ID.
QVariant dutConnectionId () const
Get DUT connection ID.
void setTestConnectionId (const QVariant &id)
Set test connection ID.
QVariant testConnectionId () const
Get test connection ID.
void setMeasureConnectionId (const QVariant &id)
Set measure connection ID.
QVariant measureConnectionId () const
Get measure connection ID.
void addSetupData (mdtTtTestNodeUnitSetupData data)
Add a test node unit setup data.
const QList
< mdtTtTestNodeUnitSetupData > & setupDataList () const
Get test node unit setup data list.
mdtValue routeResistance () const
Get route resistance.
mdtValue busCouplingRelaysResistance () const
Get route resistance for bus coupling relays part.
mdtValue channelRelaysResistance () const
Get route resistance for channel relays part.
QList< QVariant > busCouplingRelaysIdList () const
Get ID list of bus coupling relays that are part of route.
QList< QVariant > channelRelaysIdList () const
Get ID list of channel relays that are part of route.
Detailed Description
Container for test model item route data.
Contains data from TestModelItemRoute_tbl.
A route is way that links a measure connection to a test connection in a coupler (a test node).
Definition at line 37 of file mdtTtTestModelItemRouteData.h.
Constructor & Destructor Documentation
mdtTtTestModelItemRouteData::mdtTtTestModelItemRouteData ()
Construct a empty route data.
Definition at line 23 of file mdtTtTestModelItemRouteData.cpp.
mdtTtTestModelItemRouteData::mdtTtTestModelItemRouteData (const QSqlRecord & record)
Construct data from a sql record.
Given record must contain all fields from TestModelItemRoute_tbl. If record includes TestConnection_Id_FK, testConnectionId will also be set. If record includes DutConnection_Id_FK, dutConnectionId will also be set.
Precondition
record must contain following fields: Id_PK, TestModelItem_Id_FK, TestLink_Id_FK and MeasureTestNodeUnitConnection_Id_FK.
Definition at line 27 of file mdtTtTestModelItemRouteData.cpp.
References setDutConnectionId(), setId(), setMeasureConnectionId(), setTestConnectionId(), setTestLinkId(), and setTestModelItemId().
Member Function Documentation
void mdtTtTestModelItemRouteData::addSetupData (mdtTtTestNodeUnitSetupData data)
Add a test node unit setup data.
Will update TestModelItem_Id_FK in data with internal testModelItemId and TestModelItemRoute_Id_FK with internal id.
Precondition
Fields TestModelItem_Id_FK and TestModelItemRoute_Id_FK must exist in data.
Definition at line 99 of file mdtTtTestModelItemRouteData.cpp.
References mdtSqlRecord::contains(), and mdtSqlRecord::setValue().
Referenced by mdtTtTestModelItem::addRoute().
QList< QVariant > mdtTtTestModelItemRouteData::busCouplingRelaysIdList () const
Get ID list of bus coupling relays that are part of route.
Definition at line 149 of file mdtTtTestModelItemRouteData.cpp.
mdtValue mdtTtTestModelItemRouteData::busCouplingRelaysResistance () const
Get route resistance for bus coupling relays part.
This function is similar to routeResistance(), but returns only sum for bus coupling relays.
Definition at line 121 of file mdtTtTestModelItemRouteData.cpp.
QList< QVariant > mdtTtTestModelItemRouteData::channelRelaysIdList () const
Get ID list of channel relays that are part of route.
Definition at line 164 of file mdtTtTestModelItemRouteData.cpp.
mdtValue mdtTtTestModelItemRouteData::channelRelaysResistance () const
Get route resistance for channel relays part.
This function is similar to routeResistance(), but returns only sum for channel relays.
Definition at line 135 of file mdtTtTestModelItemRouteData.cpp.
void mdtTtTestModelItemRouteData::clearData ()
Clear.
Definition at line 48 of file mdtTtTestModelItemRouteData.cpp.
QVariant mdtTtTestModelItemRouteData::dutConnectionId () const inline
Get DUT connection ID.
Definition at line 93 of file mdtTtTestModelItemRouteData.h.
QVariant mdtTtTestModelItemRouteData::id () const inline
Get ID.
Definition at line 67 of file mdtTtTestModelItemRouteData.h.
Referenced by setDutConnectionId(), setId(), setMeasureConnectionId(), setTestConnectionId(), setTestLinkId(), and setTestModelItemId().
QVariant mdtTtTestModelItemRouteData::measureConnectionId () const inline
Get measure connection ID.
Definition at line 109 of file mdtTtTestModelItemRouteData.h.
Referenced by mdtTtTestModelItem::addRoute(), mdtTtTestModel::addRoutesToItemData(), and mdtTtTest::getLinkDataListForRoute().
mdtValue mdtTtTestModelItemRouteData::routeResistance () const
Get route resistance.
Route resistance is due to coupler (test node) relays. This values are set during a test node calibration.
Note: this value is only available if added setup data were constructed from TestNodeUnitSetup_view.
Definition at line 109 of file mdtTtTestModelItemRouteData.cpp.
void mdtTtTestModelItemRouteData::setDutConnectionId (const QVariant & id)
Set DUT connection ID.
Definition at line 84 of file mdtTtTestModelItemRouteData.cpp.
References id().
Referenced by mdtTtTestModel::addRoutesToItemData(), and mdtTtTestModelItemRouteData().
void mdtTtTestModelItemRouteData::setId (const QVariant & id)
Set ID.
Will also update field TestModelItemRoute_Id_FK in each test node unit setup
Definition at line 59 of file mdtTtTestModelItemRouteData.cpp.
References id().
Referenced by mdtTtTestModelItem::addRoute(), and mdtTtTestModelItemRouteData().
void mdtTtTestModelItemRouteData::setMeasureConnectionId (const QVariant & id)
Set measure connection ID.
Definition at line 94 of file mdtTtTestModelItemRouteData.cpp.
References id().
Referenced by mdtTtTestModelItem::addRoute(), mdtTtTestModel::addRoutesToItemData(), and mdtTtTestModelItemRouteData().
void mdtTtTestModelItemRouteData::setTestConnectionId (const QVariant & id)
Set test connection ID.
Definition at line 89 of file mdtTtTestModelItemRouteData.cpp.
References id().
Referenced by mdtTtTestModel::addRoutesToItemData(), and mdtTtTestModelItemRouteData().
void mdtTtTestModelItemRouteData::setTestLinkId (const QVariant & id)
Set test link ID.
Definition at line 79 of file mdtTtTestModelItemRouteData.cpp.
References id().
Referenced by mdtTtTestModelItem::addRoute(), mdtTtTestModel::addRoutesToItemData(), and mdtTtTestModelItemRouteData().
void mdtTtTestModelItemRouteData::setTestModelItemId (const QVariant & id)
Set test model item ID.
Will also update field TestModelItem_Id_FK in each test node unit setup
Definition at line 69 of file mdtTtTestModelItemRouteData.cpp.
References id().
Referenced by mdtTtTestModelItem::addRoute(), mdtTtTestModelItemData::addRouteData(), and mdtTtTestModelItemRouteData().
const QList<mdtTtTestNodeUnitSetupData>& mdtTtTestModelItemRouteData::setupDataList () const inline
Get test node unit setup data list.
Definition at line 123 of file mdtTtTestModelItemRouteData.h.
Referenced by mdtTtTestModelItem::addRoute(), mdtTtTestNodeSetupData::addRouteData(), mdtTtTestModel::addRoutesToItemData(), and mdtTtTest::getLinkDataListForRoute().
QVariant mdtTtTestModelItemRouteData::testConnectionId () const inline
Get test connection ID.
Definition at line 101 of file mdtTtTestModelItemRouteData.h.
Referenced by mdtTtTest::getLinkDataListForRoute().
QVariant mdtTtTestModelItemRouteData::testLinkId () const inline
Get test link ID.
Definition at line 85 of file mdtTtTestModelItemRouteData.h.
Referenced by mdtTtTestModelItem::addRoute(), and mdtTtTestModel::generateTestModel().
QVariant mdtTtTestModelItemRouteData::testModelItemId () const inline
Get test model item ID.
Definition at line 77 of file mdtTtTestModelItemRouteData.h.
Referenced by mdtTtTestModelItem::addRoute().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestModelItemRouteData.h
src/mdttools/mdttesttool/mdtTtTestModelItemRouteData.cpp