Multi diag tools: mdtDeviceU3606AWidget Class Reference
mdtDeviceU3606AWidget Class Reference
#include <mdtDeviceU3606AWidget.h>
Public Slots
void essais ()
void scan ()
void selectPort (const QString &port)
void displayIdn (const QStringList &data)
Public Member Functions
mdtDeviceU3606AWidget (QWidget *parent=0)
Additional Inherited Members
Private Member Functions inherited from Ui_mdtDeviceU3606AWidget
void setupUi (QWidget *mdtDeviceU3606AWidget)
void retranslateUi (QWidget *mdtDeviceU3606AWidget)
Private Attributes inherited from Ui_mdtDeviceU3606AWidget
QGridLayout * gridLayout
QComboBox * cbPort
QPushButton * pbScan
QPushButton * pbEssais
QLabel * lbEssais
QLabel * lbManufacturerLabel
QLabel * lbManufacturer
QLabel * lbModelLabel
QLabel * lbModel
QLabel * lbSerialLabel
QLabel * lbSerial
QLabel * lbIfBoardFwLabel
QLabel * lbIfBoardFw
QLabel * lbMeasureBoardFwLabel
QLabel * lbMeasureBoardFw
QLabel * lbSrcBoardFwLabel
QLabel * lbSrcBoardFw
Detailed Description
Todo:
A supprimer !(?)!
Definition at line 32 of file mdtDeviceU3606AWidget.h.
Constructor & Destructor Documentation
mdtDeviceU3606AWidget::mdtDeviceU3606AWidget (QWidget * parent = 0)
Todo:
A supprimer !(?)!
Definition at line 27 of file mdtDeviceU3606AWidget.cpp.
References Ui_mdtDeviceU3606AWidget::cbPort, displayIdn(), essais(), Ui_mdtDeviceU3606AWidget::pbEssais, Ui_mdtDeviceU3606AWidget::pbScan, scan(), selectPort(), and Ui_mdtDeviceU3606AWidget::setupUi().
Member Function Documentation
void mdtDeviceU3606AWidget::displayIdn (const QStringList & data) slot
Definition at line 73 of file mdtDeviceU3606AWidget.cpp.
References Ui_mdtDeviceU3606AWidget::lbIfBoardFw, Ui_mdtDeviceU3606AWidget::lbManufacturer, Ui_mdtDeviceU3606AWidget::lbMeasureBoardFw, Ui_mdtDeviceU3606AWidget::lbModel, Ui_mdtDeviceU3606AWidget::lbSerial, and Ui_mdtDeviceU3606AWidget::lbSrcBoardFw.
Referenced by mdtDeviceU3606AWidget().
void mdtDeviceU3606AWidget::essais () slot
Definition at line 42 of file mdtDeviceU3606AWidget.cpp.
References Ui_mdtDeviceU3606AWidget::pbEssais.
Referenced by mdtDeviceU3606AWidget().
void mdtDeviceU3606AWidget::scan () slot
Definition at line 50 of file mdtDeviceU3606AWidget.cpp.
References Ui_mdtDeviceU3606AWidget::cbPort, and Ui_mdtDeviceU3606AWidget::pbScan.
Referenced by mdtDeviceU3606AWidget().
void mdtDeviceU3606AWidget::selectPort (const QString & port) slot
Definition at line 58 of file mdtDeviceU3606AWidget.cpp.
References Ui_mdtDeviceU3606AWidget::pbEssais.
Referenced by mdtDeviceU3606AWidget().
The documentation for this class was generated from the following files:
src/mdtdevice/linux/mdtDeviceU3606AWidget.h
src/mdtdevice/linux/mdtDeviceU3606AWidget.cpp