Multi diag tools: mdtSqlRelationItem Class Reference
mdtSqlRelationItem Class Reference
Keep informations about a parent/child SQL relation.
#include <mdtSqlRelationItem.h>
Public Member Functions
mdtSqlRelationItem ()
Build a empty relation item.
~mdtSqlRelationItem ()
Destructor.
void setParentField (const QSqlField &field)
Set parent field.
void setParentFieldIndex (int index)
Set parent field index.
void setChildField (const QSqlField &field)
Set child field.
void setChildFieldIndex (int index)
Set child field index.
QString parentFieldName () const
Get parent field name.
int parentFieldIndex () const
Get parent field index.
QString childFieldName () const
Get child field name.
int childFieldIndex () const
Get child field index.
QString nameProtection () const
Get table/field protection.
QString dataProtection () const
Get data protection.
QVariant::Type dataType () const
Get data type.
QVariant valueForNoDataFilter () const
Get value for a filter that gives no data.
void setCopyParentToChildOnInsertion (bool enable)
Set copyParentToChildOnInsertion flag.
bool copyParentToChildOnInsertion () const
Set copyParentToChildOnInsertion flag.
void setRelationOperatorWithPreviousItem (const QString &operatorWithPreviousItem)
Set relation operator with previous item.
QString relationOperatorWithPreviousItem () const
Get relation operator with previous item.
Detailed Description
Keep informations about a parent/child SQL relation.
Definition at line 30 of file mdtSqlRelationItem.h.
Constructor & Destructor Documentation
mdtSqlRelationItem::mdtSqlRelationItem ()
Build a empty relation item.
Definition at line 24 of file mdtSqlRelationItem.cpp.
mdtSqlRelationItem::~mdtSqlRelationItem ()
Destructor.
Definition at line 32 of file mdtSqlRelationItem.cpp.
Member Function Documentation
int mdtSqlRelationItem::childFieldIndex () const inline
Get child field index.
Definition at line 72 of file mdtSqlRelationItem.h.
QString mdtSqlRelationItem::childFieldName () const inline
Get child field name.
Definition at line 68 of file mdtSqlRelationItem.h.
bool mdtSqlRelationItem::copyParentToChildOnInsertion () const inline
Set copyParentToChildOnInsertion flag.
See Also
setCopyParentToChildOnInsertion()
Definition at line 117 of file mdtSqlRelationItem.h.
QString mdtSqlRelationItem::dataProtection () const inline
Get data protection.
Typical data protections are:
' for string type
nothing for numeric type
Definition at line 86 of file mdtSqlRelationItem.h.
QVariant::Type mdtSqlRelationItem::dataType () const inline
Get data type.
Definition at line 90 of file mdtSqlRelationItem.h.
QString mdtSqlRelationItem::nameProtection () const inline
Get table/field protection.
Typical name protection is `
Definition at line 78 of file mdtSqlRelationItem.h.
int mdtSqlRelationItem::parentFieldIndex () const inline
Get parent field index.
Definition at line 64 of file mdtSqlRelationItem.h.
QString mdtSqlRelationItem::parentFieldName () const inline
Get parent field name.
Definition at line 60 of file mdtSqlRelationItem.h.
QString mdtSqlRelationItem::relationOperatorWithPreviousItem () const inline
Get relation operator with previous item.
See Also
setRelationOperatorWithPreviousItem()
Definition at line 132 of file mdtSqlRelationItem.h.
void mdtSqlRelationItem::setChildField (const QSqlField & field)
Set child field.
Definition at line 62 of file mdtSqlRelationItem.cpp.
Referenced by mdtSqlRelation::addRelation().
void mdtSqlRelationItem::setChildFieldIndex (int index)
Set child field index.
Definition at line 67 of file mdtSqlRelationItem.cpp.
Referenced by mdtSqlRelation::addRelation().
void mdtSqlRelationItem::setCopyParentToChildOnInsertion (bool enable)
Set copyParentToChildOnInsertion flag.
Usually, a parent/child relation is based on a primary key in parent table and foreing key (that refers to parent PK) in child model. When inserting a new record in child table, parent table's primary key must be copied into foreing key fields in child table. Set this flag to true to enable this behaviour (see mdtSqlRelation for more details).
By default, this flag is false.
Definition at line 72 of file mdtSqlRelationItem.cpp.
Referenced by mdtSqlRelation::addRelation().
void mdtSqlRelationItem::setParentField (const QSqlField & field)
Set parent field.
Definition at line 36 of file mdtSqlRelationItem.cpp.
Referenced by mdtSqlRelation::addRelation().
void mdtSqlRelationItem::setParentFieldIndex (int index)
Set parent field index.
Definition at line 57 of file mdtSqlRelationItem.cpp.
Referenced by mdtSqlRelation::addRelation().
void mdtSqlRelationItem::setRelationOperatorWithPreviousItem (const QString & operatorWithPreviousItem)
Set relation operator with previous item.
For most of cases, the relation operator between items is AND, that is the default. For some cases, it can be usefull to have a OR operator between 2 relation items. On this case, specify this here.
Definition at line 77 of file mdtSqlRelationItem.cpp.
Referenced by mdtSqlRelation::addRelation().
QVariant mdtSqlRelationItem::valueForNoDataFilter () const inline
Get value for a filter that gives no data.
Typical values are:
empty string
-1 for numeric field
Definition at line 98 of file mdtSqlRelationItem.h.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSqlRelationItem.h
src/mdtutilsgui/mdtSqlRelationItem.cpp