Multi diag tools: mdtFrameModbusTcp Class Reference
mdtFrameModbusTcp Class Reference
MODBUS/TCP Frame.
#include <mdtFrameModbusTcp.h>
Public Member Functions
mdtFrameModbusTcp ()
~mdtFrameModbusTcp ()
void clearSub ()
mdtFrame subclass specific clear
int putData (const char *data, int maxLen)
Overload of mdtFrame::putData()
void setTransactionId (quint16 id)
Set the transaction ID.
quint16 transactionId ()
Get the transaction ID.
quint16 modbusLength ()
Get the length of Unit ID + PDU.
void setUnitId (quint8 id)
Set the Unit ID.
quint8 unitId ()
Get the Unit ID.
void setPdu (const QByteArray &pdu)
Set the MODBUS PDU.
QByteArray getPdu ()
Get the MODBUS PDU.
void encode ()
Encode the MODBUS/TCP frame.
Public Member Functions inherited from mdtFrame
mdtFrame ()
virtual ~mdtFrame ()
void setIgnoreNullValues (bool ignoreNullValues)
Set the ignore null values flag.
int putUntil (const char *data, char token, int maxLen)
Put data until EOF token was reached.
int putUntil (const char *data, QByteArray &token, int maxLen)
Put data until EOF token was reached.
bool isFull ()
Returns true if frame is full.
int remainCapacity ()
Returns the remain capacity.
int bytesToStore ()
Returns the bytes to store into the frame.
void setDirectlyComplete (bool dc)
Set the complete flag directly.
void setComplete ()
Set the frame as complete.
bool isComplete ()
Returns true if EOF condition was reached.
void clear ()
Overloaded function.
virtual int eofSeqLen ()
Get the length of the end of frame sequence.
int take (char *data, int len)
Take some data.
int take (int len)
Take some data.
void setWaitAnAnswer (bool wait)
Tell a write/read thread that an answer is needed after a write frame.
bool waitAnAnswer () const
Know if an answer is needed after a write frame.
Additional Inherited Members
Public Types inherited from mdtFrame
enum type_t {
FT_RAW, FT_RAW_TOP, FT_ASCII, FT_MODBUS_TCP,
FT_USBTMC
}
Frame type.
Protected Attributes inherited from mdtFrame
bool pvIgnoreNullValues
bool pvEOFcondition
bool pvWaitAnAnswer
Detailed Description
MODBUS/TCP Frame.
This encode/decode a MODBUS/TCP frame. Note that function codes, ... , are not handled here. This application layer functions must be done with a frame codec.
Ref:
MODBUS Messaging on TCP/IP Implementation Guide V1.0b
MODBUS Application Protocol Specification V1.1b
http://www.Modbus-IDA.org
Definition at line 39 of file mdtFrameModbusTcp.h.
Constructor & Destructor Documentation
mdtFrameModbusTcp::mdtFrameModbusTcp ()
Definition at line 25 of file mdtFrameModbusTcp.cpp.
mdtFrameModbusTcp::~mdtFrameModbusTcp ()
Definition at line 33 of file mdtFrameModbusTcp.cpp.
Member Function Documentation
void mdtFrameModbusTcp::clearSub () virtual
mdtFrame subclass specific clear
Reimplemented from mdtFrame.
Definition at line 37 of file mdtFrameModbusTcp.cpp.
Referenced by mdtModbusTcpPortManager::sendData().
void mdtFrameModbusTcp::encode ()
Encode the MODBUS/TCP frame.
This will build the frame with MBAP Header.
Precondition
Capacity must be >= 7
Definition at line 142 of file mdtFrameModbusTcp.cpp.
Referenced by mdtModbusTcpPortManager::sendData().
QByteArray mdtFrameModbusTcp::getPdu ()
Get the MODBUS PDU.
Definition at line 137 of file mdtFrameModbusTcp.cpp.
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden().
quint16 mdtFrameModbusTcp::modbusLength ()
Get the length of Unit ID + PDU.
Definition at line 114 of file mdtFrameModbusTcp.cpp.
int mdtFrameModbusTcp::putData (const char * data, int maxLen) virtual
Overload of mdtFrame::putData()
Precondition
Capacity must be >= 7
See Also
mdtFrame
Reimplemented from mdtFrame.
Definition at line 45 of file mdtFrameModbusTcp.cpp.
References mdtFrame::bytesToStore(), mdtFrame::pvEOFcondition, and mdtFrame::remainCapacity().
void mdtFrameModbusTcp::setPdu (const QByteArray & pdu)
Set the MODBUS PDU.
Definition at line 132 of file mdtFrameModbusTcp.cpp.
Referenced by mdtModbusTcpPortManager::sendData().
void mdtFrameModbusTcp::setTransactionId (quint16 id)
Set the transaction ID.
Definition at line 104 of file mdtFrameModbusTcp.cpp.
Referenced by mdtModbusTcpPortManager::sendData().
void mdtFrameModbusTcp::setUnitId (quint8 id)
Set the Unit ID.
Definition at line 122 of file mdtFrameModbusTcp.cpp.
Referenced by mdtModbusTcpPortManager::sendData().
quint16 mdtFrameModbusTcp::transactionId ()
Get the transaction ID.
Definition at line 109 of file mdtFrameModbusTcp.cpp.
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden().
quint8 mdtFrameModbusTcp::unitId ()
Get the Unit ID.
Definition at line 127 of file mdtFrameModbusTcp.cpp.
The documentation for this class was generated from the following files:
src/mdtutils/mdtFrameModbusTcp.h
src/mdtutils/mdtFrameModbusTcp.cpp