Multi diag tools: mdtUsbInterfaceDescriptor Class Reference
mdtUsbInterfaceDescriptor Class Reference
USB interface descriptor.
#include <mdtUsbInterfaceDescriptor.h>
Public Member Functions
mdtUsbInterfaceDescriptor ()
Construct a empty interface descriptor.
mdtUsbInterfaceDescriptor (libusb_interface_descriptor descriptor)
Constructor.
bool isEmpty () const
~mdtUsbInterfaceDescriptor();
void clear ()
Clear descriptor.
uint8_t bInterfaceNumber () const
Ftech the interface descriptor's attributes.
uint8_t bDescriptorType () const
INTERFACE Descriptor Type.
uint8_t bInterfaceClass () const
Class code (assigned by the USB-IF)
uint8_t bInterfaceSubClass () const
Subclass code (assigned by the USB-IF)
uint8_t bInterfaceProtocol () const
Protocol code (assigned by the USB)
uint8_t iInterface () const
Index of string descriptor describing this interface.
QList< mdtUsbEndpointDescriptor > endpoints () const
List of avaliable enpoints.
QList< mdtUsbEndpointDescriptor > bulkInEndpoints () const
Get a list of bulk IN endpoints.
QList< mdtUsbEndpointDescriptor > bulkOutEndpoints () const
Get a list of bulk OUT endpoints.
QList< mdtUsbEndpointDescriptor > interruptInEndpoints () const
Get a list of interrupt IN endpoints.
QList< mdtUsbEndpointDescriptor > interruptOutEndpoints () const
Get a list of interrupt OUT endpoints.
Detailed Description
USB interface descriptor.
Definition at line 32 of file mdtUsbInterfaceDescriptor.h.
Constructor & Destructor Documentation
mdtUsbInterfaceDescriptor::mdtUsbInterfaceDescriptor ()
Construct a empty interface descriptor.
Definition at line 24 of file mdtUsbInterfaceDescriptor.cpp.
mdtUsbInterfaceDescriptor::mdtUsbInterfaceDescriptor (libusb_interface_descriptor descriptor)
Constructor.
Will copy all members of passed descriptor. This given descriptor can be freed after construction was done.
Definition at line 37 of file mdtUsbInterfaceDescriptor.cpp.
Member Function Documentation
uint8_t mdtUsbInterfaceDescriptor::bDescriptorType () const inline
INTERFACE Descriptor Type.
Definition at line 74 of file mdtUsbInterfaceDescriptor.h.
uint8_t mdtUsbInterfaceDescriptor::bInterfaceClass () const inline
Class code (assigned by the USB-IF)
Definition at line 81 of file mdtUsbInterfaceDescriptor.h.
Referenced by mdtUsbPortManager::scan().
uint8_t mdtUsbInterfaceDescriptor::bInterfaceNumber () const inline
Ftech the interface descriptor's attributes.
Precondition
descriptor must be a valid pointer
Get bInterfaceNumber
Definition at line 67 of file mdtUsbInterfaceDescriptor.h.
Referenced by mdtUsbtmcTransferHandler::setup().
uint8_t mdtUsbInterfaceDescriptor::bInterfaceProtocol () const inline
Protocol code (assigned by the USB)
Definition at line 95 of file mdtUsbInterfaceDescriptor.h.
Referenced by mdtUsbPortManager::scan().
uint8_t mdtUsbInterfaceDescriptor::bInterfaceSubClass () const inline
Subclass code (assigned by the USB-IF)
Definition at line 88 of file mdtUsbInterfaceDescriptor.h.
Referenced by mdtUsbPortManager::scan().
QList< mdtUsbEndpointDescriptor > mdtUsbInterfaceDescriptor::bulkInEndpoints () const
Get a list of bulk IN endpoints.
mdtUsbInterfaceDescriptor::~mdtUsbInterfaceDescriptor() { qDeleteAll(pvEndpoints); } quint8 mdtUsbInterfaceDescriptor::bDescriptorType() const { return pvbDescriptorType; }
quint8 mdtUsbInterfaceDescriptor::bInterfaceClass() const { return pvbInterfaceClass; }
quint8 mdtUsbInterfaceDescriptor::bInterfaceSubClass() const { return pvbInterfaceSubClass; }
quint8 mdtUsbInterfaceDescriptor::bInterfaceProtocol() const { return pvbInterfaceProtocol; }
quint8 mdtUsbInterfaceDescriptor::iInterface() const { return pviInterface; } QList<mdtUsbEndpointDescriptor*> &mdtUsbInterfaceDescriptor::endpoints() { return pvEndpoints; }
Definition at line 123 of file mdtUsbInterfaceDescriptor.cpp.
Referenced by mdtUsbtmcTransferHandler::setup().
QList< mdtUsbEndpointDescriptor > mdtUsbInterfaceDescriptor::bulkOutEndpoints () const
Get a list of bulk OUT endpoints.
Definition at line 136 of file mdtUsbInterfaceDescriptor.cpp.
Referenced by mdtUsbtmcTransferHandler::setup().
void mdtUsbInterfaceDescriptor::clear ()
Clear descriptor.
Definition at line 48 of file mdtUsbInterfaceDescriptor.cpp.
QList<mdtUsbEndpointDescriptor> mdtUsbInterfaceDescriptor::endpoints () const inline
List of avaliable enpoints.
QList<mdtUsbEndpointDescriptor*> &endpoints();
Definition at line 110 of file mdtUsbInterfaceDescriptor.h.
Referenced by mdtUsbDeviceDescriptor::endpoint(), mdtUsbDeviceDescriptor::firstBulkInEndpoint(), mdtUsbDeviceDescriptor::firstBulkOutEndpoint(), mdtUsbDeviceDescriptor::firstInterruptInEndpoint(), and mdtUsbDeviceDescriptor::firstInterruptOutEndpoint().
uint8_t mdtUsbInterfaceDescriptor::iInterface () const inline
Index of string descriptor describing this interface.
Definition at line 102 of file mdtUsbInterfaceDescriptor.h.
QList< mdtUsbEndpointDescriptor > mdtUsbInterfaceDescriptor::interruptInEndpoints () const
Get a list of interrupt IN endpoints.
Definition at line 149 of file mdtUsbInterfaceDescriptor.cpp.
Referenced by mdtUsbtmcTransferHandler::setup().
QList< mdtUsbEndpointDescriptor > mdtUsbInterfaceDescriptor::interruptOutEndpoints () const
Get a list of interrupt OUT endpoints.
Definition at line 162 of file mdtUsbInterfaceDescriptor.cpp.
bool mdtUsbInterfaceDescriptor::isEmpty () const inline
~mdtUsbInterfaceDescriptor();
Check if descriptor is empty
Definition at line 51 of file mdtUsbInterfaceDescriptor.h.
Referenced by mdtUsbDeviceDescriptor::endpoint(), mdtUsbDeviceDescriptor::firstBulkInEndpoint(), mdtUsbDeviceDescriptor::firstBulkOutEndpoint(), mdtUsbDeviceDescriptor::firstInterruptInEndpoint(), mdtUsbDeviceDescriptor::firstInterruptOutEndpoint(), and mdtUsbtmcTransferHandler::setup().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbInterfaceDescriptor.h
src/mdtport/mdtUsbInterfaceDescriptor.cpp