Multi diag tools: mdtFieldListEditionDialog Class Reference
mdtFieldListEditionDialog Class Reference
Dialog that provides field list edition.
#include <mdtFieldListEditionDialog.h>
Public Member Functions
mdtFieldListEditionDialog (QWidget *parent=0)
Constructor.
~mdtFieldListEditionDialog ()
Destructor.
void setAvailableFields (const QList< mdtFieldMapField > &fields, int startFieldIndex)
Set the list of available fields.
const QList< mdtFieldMapField > & fields () const
Get the list of fields.
Additional Inherited Members
Private Member Functions inherited from Ui_mdtFieldListEditionDialog
void setupUi (QDialog *mdtFieldListEditionDialog)
void retranslateUi (QDialog *mdtFieldListEditionDialog)
Private Attributes inherited from Ui_mdtFieldListEditionDialog
QVBoxLayout * verticalLayout_2
QLabel * lbFields
QHBoxLayout * horizontalLayout
QTableWidget * twFields
QVBoxLayout * verticalLayout
QPushButton * pbAdd
QPushButton * pbRemove
QSpacerItem * verticalSpacer
QPushButton * pbUp
QPushButton * pbDown
QSpacerItem * verticalSpacer_2
QDialogButtonBox * buttonBox
Detailed Description
Dialog that provides field list edition.
Definition at line 32 of file mdtFieldListEditionDialog.h.
Constructor & Destructor Documentation
mdtFieldListEditionDialog::mdtFieldListEditionDialog (QWidget * parent = 0)
Constructor.
Definition at line 31 of file mdtFieldListEditionDialog.cpp.
References Ui_mdtFieldListEditionDialog::pbAdd, Ui_mdtFieldListEditionDialog::pbDown, Ui_mdtFieldListEditionDialog::pbRemove, Ui_mdtFieldListEditionDialog::pbUp, Ui_mdtFieldListEditionDialog::setupUi(), and Ui_mdtFieldListEditionDialog::twFields.
mdtFieldListEditionDialog::~mdtFieldListEditionDialog ()
Destructor.
Definition at line 50 of file mdtFieldListEditionDialog.cpp.
Member Function Documentation
const QList< mdtFieldMapField > & mdtFieldListEditionDialog::fields () const
Get the list of fields.
Definition at line 93 of file mdtFieldListEditionDialog.cpp.
void mdtFieldListEditionDialog::setAvailableFields (const QList< mdtFieldMapField > & fields, int startFieldIndex)
Set the list of available fields.
Note: here, given fields must have contigous column indexes, "holes" are not handled .
Definition at line 54 of file mdtFieldListEditionDialog.cpp.
References mdtFieldMapField::displayText(), mdtFieldMapField::index(), mdtFieldMapField::name(), and Ui_mdtFieldListEditionDialog::twFields.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtFieldListEditionDialog.h
src/mdtutilsgui/mdtFieldListEditionDialog.cpp