Multi diag tools: mdtAbstractPort Class Reference
mdtAbstractPort Class Reference abstract
Base class for port I/O.
#include <mdtAbstractPort.h>
Public Types
enum error_t {
NoError = 0, PortLocked = -1000, PortNotFound, PortAccess,
SetupError, WriteCanceled, ReadCanceled, ControlCanceled,
ReadTimeout, WriteTimeout, MessageInTimeout, MessageInCanceled,
ControlTimeout, Disconnected, Connecting, ConnectionFailed,
UnhandledError, ReadPoolEmpty, WritePoolEmpty, ErrorHandled,
ReadWriteBusy, UsbWriteStall, UsbReadStall
}
Error.
Public Member Functions
mdtAbstractPort (QObject *parent=0)
virtual ~mdtAbstractPort ()
Destructor.
void setPortName (const QString &portName)
Set the port name.
QString & portName ()
Get port name.
error_t open ()
Open the port given by setPortName()
bool isOpen () const
Get port's open state.
virtual void close ()
Close the port.
void setConfig (mdtPortConfig *cfg)
Set configuration.
mdtPortConfig & config ()
Get the stored configuration.
error_t setup ()
Setup port with given configurations.
virtual error_t reconnect (int timeout)
Reconnect device/peer.
virtual void setReadTimeout (int timeout)=0
Set the read data timeout.
virtual void setWriteTimeout (int timeout)=0
Set the write data timeout.
virtual error_t waitForReadyRead ()=0
Wait until data is available on port.
error_t waitForReadyRead (int msecs)
Wait until data is available on port.
virtual qint64 read (char *data, qint64 maxSize)=0
Read data from port.
virtual bool suspendTransmission ()
Request to suspend transmission.
virtual bool resumeTransmission ()
Request to resume transmission.
void flushIn ()
Flush read buffers.
bool flushInRequestPending ()
Check if a flush in request is pending.
virtual error_t waitEventWriteReady ()=0
Wait until data can be written to port.
virtual qint64 write (const char *data, qint64 maxSize)=0
Write data to port.
void flushOut ()
Flush write buffers.
bool flushOutRequestPending ()
Check if a flush out request is pending.
void flush ()
Flush read/write buffers.
void initQueues ()
Init the read ans write queues.
QQueue< mdtFrame * > & readenFrames ()
Get the readen frames Queue.
QQueue< mdtFrame * > & readFramesPool ()
Get the read frames Queue pool.
virtual void addFrameToWrite (mdtFrame *frame)
Add a frame to write.
mdtFrame * getFrameToWrite ()
Wait until a frame to write is available and get it.
void abortFrameToWriteWait ()
Abort the frame tp write waiting.
QQueue< mdtFrame * > & writeFrames ()
Get the write frames Queue.
QQueue< mdtFrame * > & writeFramesPool ()
Get the write frames Queue pool.
void lockMutex ()
Lock the mutex.
void unlockMutex ()
Unlock the mutex.
Protected Member Functions
virtual error_t pvOpen ()=0
Open the port given by setPortName()
virtual void pvClose ()=0
Close port.
virtual error_t pvSetup ()=0
Setup port with given configurations.
virtual void pvFlushIn ()=0
Flush read port.
virtual void pvFlushOut ()=0
Flush write port.
Protected Attributes
QQueue< mdtFrame * > pvReadenFrames
QQueue< mdtFrame * > pvReadFramesPool
QQueue< mdtFrame * > pvWriteFrames
QQueue< mdtFrame * > pvWriteFramesPool
mdtPortConfig * pvConfig
QString pvPortName
QMutex pvMutex
QWaitCondition pvWriteFrameAvailable
Detailed Description
Base class for port I/O.
Todo:
WaitingCanceled, WriteCanceled, ReadCanceled are not clean defined. The only object that knows when it must stop is the thread itself ! To be a little more clean, thread should check it's running flag each time a function returns a error, and stop if requierd !
Definition at line 42 of file mdtAbstractPort.h.
Member Enumeration Documentation
enum mdtAbstractPort::error_t
Error.
Each system's I/O API can return several error. Goal is here to map them to common error codes.
Note for thread implementation:
Some errors must be handled in specific ways depending on port (serial, USB, TCP, ...). Each time a error occurs, thread should check the pvRunning flag, and stop if it is false (typical: after a stop request from main thread, mdtAbstractPort subclass will return ReadCanceled, WriteCanceled or ControlCanceled. But it can happen that I/O process was canceled for another reason, this is port specific).
Enumerator
NoError
No error
PortLocked
Port is allready locked
PortNotFound
Port was not found
PortAccess
Port cannot be open with requierd access (read, write)
SetupError
Setup failed on a configuration option
WriteCanceled
Write process was cancelled. The thread should stop the write process, restore the current frame into pool, notify the error and continue working.
ReadCanceled
Read process was cancelled. The thread should stop the read process, clear the current , notify the error and continue working.
ControlCanceled
Control process canceled (serial port's modem line, USB control transfer)
ReadTimeout
Read process has timed out. Thread should clear current frame, notify this and continue working. If thread uses the read timeout protocol, no notification should be sent
WriteTimeout
Write process has timed out. Thread should notify this and continue working. If thread uses the write timeout protocol, no notification should be sent
MessageInTimeout
Used by USB/USBTMC for additionnal interrupt IN
MessageInCanceled
Used by USB/USBTMC for additionnal interrupt IN
ControlTimeout
Control process timed out (serial port's modem line, USB control transfer)
Disconnected
For USB port: the device is disconnected. For TCP socket: peer has closed the connection. If this error happens, the thread will try to reconnect. If connection fails after maximum trys, a notification is sent with ConnectionFailed error.
Connecting
Used to notify portmanager that connection is in progress (see mdtPortThread::reconnect())
ConnectionFailed
Can happen during first connection, or afetr max retry of reconnection. Port manager will stop on this error
UnhandledError
Unhandled error happen. In this case, thread will stop working and error is reported with mdtError system. Logfile could give more information, see mdtError and mdtApplication
ReadPoolEmpty
Read frames pool is empty. Says that no data can be received for the moment
WritePoolEmpty
Write queue is empty. Says that no data can be sent for the moment
ErrorHandled
Used by mdtPortThread's helper methods (handle[Read|Write]Error) to tell the thread that error could be handled
ReadWriteBusy
It's currently not possible to read from or write to port/device. This is typically used by USBTMC when some control (f.ex. abort bilk IN/OUT) is in progress
UsbWriteStall
USB specific: occurs for bulk or interrupt endpoint when a halt condition was detected
UsbReadStall
USB specific: occurs for bulk or interrupt endpoint when a halt condition was detected
Definition at line 60 of file mdtAbstractPort.h.
Constructor & Destructor Documentation
mdtAbstractPort::mdtAbstractPort (QObject * parent = 0)
Definition at line 24 of file mdtAbstractPort.cpp.
References pvConfig.
mdtAbstractPort::~mdtAbstractPort () virtual
Destructor.
Subclass notes:
This destructor cannot call the close() method, because this will call the pvClose() from destructed inherited object. So, the subclass must call close() in its own destructor.
Definition at line 33 of file mdtAbstractPort.cpp.
Member Function Documentation
void mdtAbstractPort::abortFrameToWriteWait ()
Abort the frame tp write waiting.
Will wake thread(s) waiting on a frame to write with getFrameToWrite() . This method is called from mdtPortThread::stop() , and should not be called directly.
Mutex is not handled by this method.
Definition at line 329 of file mdtAbstractPort.cpp.
References pvWriteFrameAvailable.
Referenced by mdtPortWriteThread::stop(), and mdtPortThread::stop().
void mdtAbstractPort::addFrameToWrite (mdtFrame * frame) virtual
Add a frame to write.
Once the frame is added to the write queue, waiting thread will be woken up (if waiting) and will send the frame.
The mutex must be locked before calling this method, and still locked inside.
Precondition
frame must be a valid pointer.
Reimplemented in mdtUsbPort, and mdtTcpSocket.
Definition at line 298 of file mdtAbstractPort.cpp.
References pvWriteFrameAvailable, and pvWriteFrames.
Referenced by mdtUsbtmcPortManager::sendData(), mdtModbusTcpPortManager::sendData(), mdtPortManager::sendData(), and mdtUsbtmcPortManager::sendReadRequest().
void mdtAbstractPort::close () virtual
Close the port.
Flush and close port if it is open.
Internal queues are freed here. (If subclass handles additionnaly queues, it should delete is in his pvClose() method).
The mutex is not handled by this method.
Subclass notes:
Internally, this method calls pvClose(). Once done, the flags are updated. Note that this method must be called from subclass destructor. See ~mdtAbstractPort() for details.
Reimplemented in mdtAbstractSerialPort.
Definition at line 70 of file mdtAbstractPort.cpp.
References isOpen(), pvClose(), pvFlushIn(), pvFlushOut(), pvReadenFrames, pvReadFramesPool, pvWriteFrames, and pvWriteFramesPool.
Referenced by mdtAbstractSerialPort::close(), mdtPortManager::closePort(), open(), mdtUsbPort::reconnect(), setup(), mdtPort::~mdtPort(), mdtTcpSocket::~mdtTcpSocket(), and mdtUsbPort::~mdtUsbPort().
mdtPortConfig & mdtAbstractPort::config ()
Get the stored configuration.
Precondition
Configuration must be set with setConfig() before using this method.
Definition at line 103 of file mdtAbstractPort.cpp.
References pvConfig.
Referenced by mdtPortManager::config(), initQueues(), mdtUsbtmcPortManager::mdtUsbtmcPortManager(), mdtPortThreadHelperSocket::setSocket(), mdtPortThread::start(), mdtModbusTcpPortManager::~mdtModbusTcpPortManager(), mdtSerialPortManager::~mdtSerialPortManager(), and mdtUsbPortManager::~mdtUsbPortManager().
void mdtAbstractPort::flush ()
Flush read/write buffers.
Will do the same as calling flushIn() and flushOut(), but lock the mutex only once.
Mutex is locked in this method.
Definition at line 201 of file mdtAbstractPort.cpp.
References lockMutex(), pvFlushIn(), pvFlushOut(), pvReadenFrames, pvReadFramesPool, pvWriteFrames, pvWriteFramesPool, and unlockMutex().
Referenced by mdtPortManager::abort(), and mdtPortManager::flush().
void mdtAbstractPort::flushIn ()
Flush read buffers.
Will move all readen frames to pool, and call pvFlushIn() to flush system's buffers.
After this call, flushInRequestPending() will return true.
Mutex is locked in this method.
Definition at line 161 of file mdtAbstractPort.cpp.
References lockMutex(), pvFlushIn(), pvReadenFrames, pvReadFramesPool, and unlockMutex().
Referenced by mdtPortManager::flushIn().
bool mdtAbstractPort::flushInRequestPending ()
Check if a flush in request is pending.
Returns true after flushIn() was called.
This method is used by thread, and should not be used directly. If a request is pending, thread will put his current read frame back to pool.
A call of this method will clear the internall flag. (a second call will then return false).
Mutex is not handled by this method.
Todo:
Thread are to adapt.
Definition at line 172 of file mdtAbstractPort.cpp.
void mdtAbstractPort::flushOut ()
Flush write buffers.
Will cancel current write operation, and all queued frames are removed.
Internally, all write frames are moved to pool. pvFlushOut() will be called to flush system's buffers and the next call of waitEventWriteReady() will return the WriteCanceled error.
Mutex is locked in this method.
Definition at line 181 of file mdtAbstractPort.cpp.
References lockMutex(), pvFlushOut(), pvWriteFrames, pvWriteFramesPool, and unlockMutex().
Referenced by mdtPortManager::flushOut().
bool mdtAbstractPort::flushOutRequestPending ()
Check if a flush out request is pending.
Returns true after flushOut() was called.
This method is used by thread, and should not be used directly. If a request is pending, thread will put his current write frame back to pool.
A call of this method will clear the internall flag. (a second call will then return false).
Mutex is not handled by this method.
Todo:
Thread are to adapt.
Definition at line 192 of file mdtAbstractPort.cpp.
Referenced by mdtPortThreadHelperPort::writeToPort().
mdtFrame * mdtAbstractPort::getFrameToWrite ()
Wait until a frame to write is available and get it.
If a frame is available in write frames queue, it will be returned. Else, thit method will block calling thread until a frame is available in write frames queue, and return one.
This method is called from mdtPortThread and should not be used directly.
The mutex must be locked before calling this method. Internally, it will be unlocked during wait, and locked again before returning.
Returns
A pointer to a frame, or Null (Null happens after stop request)
Definition at line 306 of file mdtAbstractPort.cpp.
References pvMutex, pvWriteFrameAvailable, and pvWriteFrames.
Referenced by mdtPortThreadHelper::getNewFrameWrite().
void mdtAbstractPort::initQueues ()
Init the read ans write queues.
Precondition
A valid configuration must be set before using this method.
Definition at line 217 of file mdtAbstractPort.cpp.
References config(), mdtPortConfig::endOfFrameSeq(), mdtPortConfig::frameType(), mdtFrame::FT_ASCII, mdtFrame::FT_MODBUS_TCP, mdtFrame::FT_RAW, mdtFrame::FT_RAW_TOP, mdtFrame::FT_USBTMC, pvReadFramesPool, pvWriteFramesPool, mdtPortConfig::readQueueSize(), mdtFrame::setDirectlyComplete(), and mdtPortConfig::writeQueueSize().
Referenced by setup().
bool mdtAbstractPort::isOpen () const
Get port's open state.
Definition at line 48 of file mdtAbstractPort.cpp.
Referenced by mdtAbstractSerialPort::availableBaudRates(), close(), open(), mdtSerialPort::setDtr(), mdtSerialPort::setRts(), setup(), mdtPortManager::start(), mdtPortManager::stop(), and mdtAbstractSerialPort::uartType().
void mdtAbstractPort::lockMutex ()
Lock the mutex.
Definition at line 344 of file mdtAbstractPort.cpp.
References pvMutex.
Referenced by mdtUsbPort::controlTransferCallback(), flush(), flushIn(), flushOut(), mdtPortThreadHelper::getNewFrameRead(), mdtUsbPort::handleUsbEvents(), mdtPortThread::isFinished(), mdtPortThread::isRunning(), mdtPortManager::lockPortMutex(), mdtUsbPort::reconnect(), mdtPortThread::stop(), mdtUsbPortThread::waitOnControlTransferPossible(), and mdtPortThreadHelperPort::writeToPort().
mdtAbstractPort::error_t mdtAbstractPort::open ()
Open the port given by setPortName()
If port can be open successfull, NoError code is returned. If port is open, it will be closed first (by calling close()).
The mutex is not handled by this method.
Subclass notes:
Internally, this method calls pvOpen(). Once done, the flags are updated.
See Also
error_t
Definition at line 53 of file mdtAbstractPort.cpp.
References close(), isOpen(), NoError, and pvOpen().
Referenced by mdtUsbPort::reconnect(), mdtSerialPortManager::scan(), and setup().
QString & mdtAbstractPort::portName ()
Get port name.
Definition at line 43 of file mdtAbstractPort.cpp.
References pvPortName.
Referenced by setPortName().
virtual void mdtAbstractPort::pvClose () protected pure virtual
Close port.
The mutex is not handled by this method.
Precondition
The port must be open whenn calling this method.
Subclass notes:
This method must be re-implemented in subclass.
To handle the port correctly, the subclass method must:
Do the specific work. Note that port was open in exclusive mode. On Linux, don't forget to unlock the port with mdtPortLock.
The mdtError system should be used (on error) to keep trace in logfile.
If additionnal queues are handled, they should be freed here.
Referenced by close().
virtual void mdtAbstractPort::pvFlushIn () protected pure virtual
Flush read port.
This method is called from flushIn(), and is usefull if subsystem needs to be flushed. (For ex. serial port).
This method must be implemented in subclass.
The mutex is handled by flushIn() and should not be handled here.
Referenced by close(), flush(), and flushIn().
virtual void mdtAbstractPort::pvFlushOut () protected pure virtual
Flush write port.
This method is called from flushOut(), and is usefull if subsystem needs to be flushed. (For ex. serial port).
The mutex is handled by flushOut() and should not be handled here.
Referenced by close(), flush(), and flushOut().
virtual error_t mdtAbstractPort::pvOpen () protected pure virtual
Open the port given by setPortName()
If port can be open successfull, NoError code is returned.
The mutex is not handled by this method.
Precondition
The port must not be open whenn calling this method.
Subclass notes:
This method must be re-implemented in subclass.
To handle the port correctly, the subclass method must:
Do the specific work. Note that port must be open in exclusive mode. On Linux, the mdtPortLock should be used for this.
The mdtError system should be used (on error) to keep trace in logfile.
If port must be closed (f.ex. on error), use the close() method to keep flags coherent. Note that pvClose() will not be called if this method returns something else than NoError. If some cleanup (witch are normally done in pvClose()) must be done, do it before return.
Return the correct error code on failure (see the error_t enum)
See Also
close()
error_t
Referenced by open().
virtual error_t mdtAbstractPort::pvSetup () protected pure virtual
Setup port with given configurations.
The mutex is not handled by this method.
Precondition
The port must be open whenn calling this method.
A valid configuration must be set before calling this method.
Subclass notes:
This method must be re-implemented in subclass.
To handle the port correctly, the subclass method must:
Do the specific work
Set read/write timeouts using setReadTimeout() and setWriteTimeout(). See mdtPortConfig to know how to get these timeouts.
Return the correct error code on failure (see the error_t enum)
Configuration is available using config().
See Also
error_t
Referenced by setup().
virtual qint64 mdtAbstractPort::read (char * data, qint64 maxSize) pure virtual
Read data from port.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex is not handled by this method.
Subclass notes:
This method must be implemented in subclass.
Returns
Number of bytes readen, or a error < 0 (see error_t)
Implemented in mdtUsbPort, mdtSerialPort, mdtTcpSocket, and mdtPort.
Referenced by mdtPortThreadHelperPort::readFromPort().
QQueue< mdtFrame * > & mdtAbstractPort::readenFrames ()
Get the readen frames Queue.
Readen frames queue contains frames that where received from device
Mutex is not handled by this method.
Definition at line 288 of file mdtAbstractPort.cpp.
References pvReadenFrames.
Referenced by mdtUsbtmcPortManager::fromThreadNewFrameReaden(), mdtModbusTcpPortManager::fromThreadNewFrameReaden(), mdtPortManager::fromThreadNewFrameReaden(), and mdtPortThreadHelper::submitCurrentReadFrame().
QQueue< mdtFrame * > & mdtAbstractPort::readFramesPool ()
Get the read frames Queue pool.
Read frames queue pool contains frames that are ready to use for reception
Mutex is not handled by this method.
Definition at line 293 of file mdtAbstractPort.cpp.
References pvReadFramesPool.
Referenced by mdtUsbtmcPortManager::fromThreadNewFrameReaden(), mdtModbusTcpPortManager::fromThreadNewFrameReaden(), mdtPortManager::fromThreadNewFrameReaden(), mdtPortThreadHelper::getNewFrameRead(), and mdtPortThreadHelper::restoreCurrentReadFrameToPool().
mdtAbstractPort::error_t mdtAbstractPort::reconnect (int timeout) virtual
Reconnect device/peer.
If one of the method returns a Disconnected error, the thread will call this method to try to reconnect.
Parameters
timeout Timeout [ms]
Returns
NoError if connection could be done. Disconnected if connection could not be done, in wich case the thread will retry (until max retry). A UnhandledError can be returned.
If subclass supports device (de|re)-connection, this method must be implemented.
Default implementation returns a UnhandledError.
Notes about mutex handling:
The mutex is locked when method is called, and must be locked when returns
Reimplemented in mdtUsbPort.
Definition at line 133 of file mdtAbstractPort.cpp.
References UnhandledError.
Referenced by mdtPortThreadHelperPort::reconnect(), and mdtPortThread::reconnect().
bool mdtAbstractPort::resumeTransmission () virtual
Request to resume transmission.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex is not handled by this method.
Subclass notes:
This method must be implemented in subclass if requierd.
Note about serial port subclass:
the right flow control must be used regarding enabled flow control.
Default implementation does nothing.
Returns
False on error, in this case, the reader thread will be stopped.
Reimplemented in mdtSerialPort.
Definition at line 156 of file mdtAbstractPort.cpp.
void mdtAbstractPort::setConfig (mdtPortConfig * cfg)
Set configuration.
Definition at line 98 of file mdtAbstractPort.cpp.
References pvConfig.
Referenced by mdtModbusTcpPortManager::mdtModbusTcpPortManager(), mdtSerialPortManager::mdtSerialPortManager(), and mdtUsbPortManager::mdtUsbPortManager().
void mdtAbstractPort::setPortName (const QString & portName)
Set the port name.
Port name can be, f.ex. /dev/ttyS0 on Linux, or COM1 on Windows. This method just store given port name and does nothing else.
Definition at line 38 of file mdtAbstractPort.cpp.
References portName(), and pvPortName.
Referenced by mdtSerialPortManager::scan(), mdtPortManager::setPortInfo(), and mdtPortManager::setPortName().
virtual void mdtAbstractPort::setReadTimeout (int timeout) pure virtual
Set the read data timeout.
The mutex is not handled by this method.
Subclass notes:
This method must be re-implemented in subclass. The subclass can convert and store the value in system specific type (f.ex: timeval struct on Posix)
Parameters
timeout Timeout [ms]. A value of -1 means a infinite timeout.
Implemented in mdtSerialPort, mdtUsbPort, mdtTcpSocket, and mdtPort.
Referenced by waitForReadyRead().
mdtAbstractPort::error_t mdtAbstractPort::setup ()
Setup port with given configurations.
If port is not open, open() will be called first. Then, pvSetup() is called, and finally queues initialized with initQueues(). If somethig fails, the port is closed again, and error code returned.
The mutex is not handled by this method.
Precondition
A valid configuration must be set before calling this method.
See Also
error_t
Definition at line 110 of file mdtAbstractPort.cpp.
References close(), initQueues(), isOpen(), NoError, open(), and pvSetup().
Referenced by mdtPortManager::openPort(), and mdtUsbPort::reconnect().
virtual void mdtAbstractPort::setWriteTimeout (int timeout) pure virtual
Set the write data timeout.
The mutex is not handled by this method.
Subclass notes:
This method must be re-implemented in subclass. The subclass can convert and store the value in system specific type (f.ex: timeval struct on Posix)
Parameters
timeout Timeout [ms]. A value of -1 means a infinite timeout.
Implemented in mdtSerialPort, mdtUsbPort, mdtTcpSocket, and mdtPort.
bool mdtAbstractPort::suspendTransmission () virtual
Request to suspend transmission.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex is not handled by this method.
Subclass notes:
This method must be implemented in subclass if requierd.
Note about serial port subclass:
the right flow control must be used regarding enabled flow control.
Default implementation does nothing.
Returns
False on error, in this case, the reader thread will be stopped.
Reimplemented in mdtSerialPort.
Definition at line 151 of file mdtAbstractPort.cpp.
void mdtAbstractPort::unlockMutex ()
Unlock the mutex.
Definition at line 349 of file mdtAbstractPort.cpp.
References pvMutex.
Referenced by mdtUsbPort::controlTransferCallback(), flush(), flushIn(), flushOut(), mdtPortThreadHelper::getNewFrameRead(), mdtUsbPort::handleUsbEvents(), mdtPortThread::isFinished(), mdtPortThread::isRunning(), mdtUsbPort::reconnect(), mdtPortThread::stop(), mdtPortManager::unlockPortMutex(), mdtUsbPortThread::waitOnControlTransferPossible(), and mdtPortThreadHelperPort::writeToPort().
virtual error_t mdtAbstractPort::waitEventWriteReady () pure virtual
Wait until data can be written to port.
This method is called from mdtPortWriteThread , and should not be used directly.
Mutex must be locked before calling this method with lockMutex(). The mutex is locked when method returns.
Subclass notes:
This method must be re-implemented in subclass. The write timeout state must be updated with updateWriteTimeoutState() Notes about mutex handling:
Mutex must be released during wait, and relocked befor return.
Returns
On success, NoError is returned. If waiting is canceled, WaitingCanceled is returned and the thread knows that it must end (case of stopping thread). If flushOut() was called, WriteCanceled is returned. If a port lost connection (f.ex. USB port or TCP socket), Disconnected is returned. On unhandled error, UnhandledError is returned. The thread also stop working, and emit a error signal (that can be handled in mdtPortManager, or in another place in application).
Implemented in mdtUsbPort, mdtSerialPort, mdtTcpSocket, and mdtPort.
Referenced by mdtPortThreadHelperPort::writeToPort().
virtual error_t mdtAbstractPort::waitForReadyRead () pure virtual
Wait until data is available on port.
This method is called from reader thread , and should not be used directly.
Mutex must be locked before calling this method with lockMutex(). The mutex is locked when method returns.
Subclass notes:
This method must be re-implemented in subclass. The read timeout state must be updated with updateReadTimeoutState()
Notes about mutex handling:
Mutex must be released during wait, and relocked befor return.
Returns
On success, NoError is returned. If waiting is canceled, ReadCanceled is returned. If a port lost connection (f.ex. USB port or TCP socket), Disconnected is returned. On unhandled error, UnhandledError is returned. The thread also stop working, and emit a error signal (that can be handled in mdtPortManager, or in another place in application).
See Also
mdtPortThread
mdtPortConfig
mdtTcpSocketThread
mdtUsbPortThread
Implemented in mdtUsbPort, mdtSerialPort, mdtTcpSocket, and mdtPort.
Referenced by waitForReadyRead().
mdtAbstractPort::error_t mdtAbstractPort::waitForReadyRead (int msecs)
Wait until data is available on port.
This method calls setReadTimeout() , waitForReadyRead() and setReadTimeout() again to restore original setting. (it is a little bit slower than setting timeout one time, and call waitForReadyRead()).
Note that the reader thread will call waitForReadyRead() without argument.
Note: this method is called from thread , and should not be used directly
Mutex: see waitForReadyRead()
Parameters
timeout Timeout [ms]. A value of -1 means a infinite timeout.
See Also
waitForReadyRead()
Definition at line 138 of file mdtAbstractPort.cpp.
References pvConfig, mdtPortConfig::readTimeout(), setReadTimeout(), and waitForReadyRead().
virtual qint64 mdtAbstractPort::write (const char * data, qint64 maxSize) pure virtual
Write data to port.
This method is called from mdtPortWriteThread , and should not be used directly.
Mutex is not handled by this method.
Subclass notes:
This method must be implemented in subclass.
Returns
Number of bytes written, or error < 0 (see error_t)
Implemented in mdtUsbPort, mdtSerialPort, mdtTcpSocket, and mdtPort.
Referenced by mdtPortThreadHelperPort::writeDataToPort().
QQueue< mdtFrame * > & mdtAbstractPort::writeFrames ()
Get the write frames Queue.
Write frames queue contains frames that must be sent
Mutex is not handled by this method.
Definition at line 334 of file mdtAbstractPort.cpp.
References pvWriteFrames.
QQueue< mdtFrame * > & mdtAbstractPort::writeFramesPool ()
Get the write frames Queue pool.
Write frames queue pool contains frames that are ready to use for transmission
Mutex is not handled by this method.
Definition at line 339 of file mdtAbstractPort.cpp.
References pvWriteFramesPool.
Referenced by mdtPortThreadHelper::restoreCurrentWriteFrameToPool(), mdtUsbtmcPortManager::sendData(), mdtModbusTcpPortManager::sendData(), mdtPortManager::sendData(), and mdtUsbtmcPortManager::sendReadRequest().
Member Data Documentation
mdtPortConfig* mdtAbstractPort::pvConfig protected
Definition at line 589 of file mdtAbstractPort.h.
Referenced by mdtAbstractSerialPort::config(), config(), mdtAbstractPort(), setConfig(), and waitForReadyRead().
QMutex mdtAbstractPort::pvMutex protected
Definition at line 593 of file mdtAbstractPort.h.
Referenced by mdtAbstractSerialPort::carIsOn(), mdtAbstractSerialPort::ctsIsOn(), mdtAbstractSerialPort::dsrIsOn(), getFrameToWrite(), lockMutex(), mdtAbstractSerialPort::rngIsOn(), mdtSerialPort::setDtr(), mdtSerialPort::setRts(), unlockMutex(), mdtSerialPort::waitEventCtl(), mdtPort::waitEventWriteReady(), mdtSerialPort::waitEventWriteReady(), mdtPort::waitForReadyRead(), and mdtSerialPort::waitForReadyRead().
QString mdtAbstractPort::pvPortName protected
Definition at line 591 of file mdtAbstractPort.h.
Referenced by portName(), and setPortName().
QQueue<mdtFrame*> mdtAbstractPort::pvReadenFrames protected
Definition at line 584 of file mdtAbstractPort.h.
Referenced by close(), flush(), flushIn(), and readenFrames().
QQueue<mdtFrame*> mdtAbstractPort::pvReadFramesPool protected
Definition at line 585 of file mdtAbstractPort.h.
Referenced by close(), flush(), flushIn(), initQueues(), and readFramesPool().
QWaitCondition mdtAbstractPort::pvWriteFrameAvailable protected
Definition at line 595 of file mdtAbstractPort.h.
Referenced by abortFrameToWriteWait(), addFrameToWrite(), and getFrameToWrite().
QQueue<mdtFrame*> mdtAbstractPort::pvWriteFrames protected
Definition at line 586 of file mdtAbstractPort.h.
Referenced by mdtTcpSocket::addFrameToWrite(), mdtUsbPort::addFrameToWrite(), addFrameToWrite(), close(), flush(), flushOut(), getFrameToWrite(), and writeFrames().
QQueue<mdtFrame*> mdtAbstractPort::pvWriteFramesPool protected
Definition at line 587 of file mdtAbstractPort.h.
Referenced by close(), flush(), flushOut(), initQueues(), and writeFramesPool().
The documentation for this class was generated from the following files:
src/mdtport/mdtAbstractPort.h
src/mdtport/mdtAbstractPort.cpp