Multi diag tools: Ui_mdtClPathGraphDialog Class Reference
Ui_mdtClPathGraphDialog Class Reference
#include <ui_mdtClPathGraphDialog.h>
Public Member Functions
void setupUi (QDialog *mdtClPathGraphDialog)
void retranslateUi (QDialog *mdtClPathGraphDialog)
Public Attributes
QVBoxLayout * verticalLayout
QGraphicsView * gvPath
QDialogButtonBox * buttonBox
Detailed Description
Definition at line 25 of file ui_mdtClPathGraphDialog.h.
Member Function Documentation
void Ui_mdtClPathGraphDialog::retranslateUi (QDialog * mdtClPathGraphDialog) inline
Definition at line 59 of file ui_mdtClPathGraphDialog.h.
Referenced by setupUi().
void Ui_mdtClPathGraphDialog::setupUi (QDialog * mdtClPathGraphDialog) inline
Definition at line 32 of file ui_mdtClPathGraphDialog.h.
References buttonBox, gvPath, retranslateUi(), and verticalLayout.
Referenced by mdtClPathGraphDialog::mdtClPathGraphDialog().
Member Data Documentation
QDialogButtonBox* Ui_mdtClPathGraphDialog::buttonBox
Definition at line 30 of file ui_mdtClPathGraphDialog.h.
Referenced by setupUi().
QGraphicsView* Ui_mdtClPathGraphDialog::gvPath
Definition at line 29 of file ui_mdtClPathGraphDialog.h.
Referenced by mdtClPathGraphDialog::mdtClPathGraphDialog(), and setupUi().
QVBoxLayout* Ui_mdtClPathGraphDialog::verticalLayout
Definition at line 28 of file ui_mdtClPathGraphDialog.h.
Referenced by setupUi().
The documentation for this class was generated from the following file:
src/mdttools/mdttesttool/ui_mdtClPathGraphDialog.h