Multi diag tools: mdtSqlFieldHandlerLineEdit Class Reference
mdtSqlFieldHandlerLineEdit Class Reference
Public Member Functions
mdtSqlFieldHandlerLineEdit ()
void setLineEdit (QLineEdit *le)
void setData (const QVariant &data)
QVariant data () const
bool isNull () const
void clear ()
QWidget * widget ()
void setReadOnly (bool readOnly)
void setMaxLength (int maxLength)
Public Member Functions inherited from mdtSqlFieldHandlerAbstractDataWidget
virtual ~mdtSqlFieldHandlerAbstractDataWidget ()
virtual void setRange (qreal min, qreal max)
virtual bool validate ()
Detailed Description
Definition at line 132 of file mdtSqlFieldHandler.cpp.
Constructor & Destructor Documentation
mdtSqlFieldHandlerLineEdit::mdtSqlFieldHandlerLineEdit ()
Definition at line 148 of file mdtSqlFieldHandler.cpp.
Member Function Documentation
void mdtSqlFieldHandlerLineEdit::clear () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 182 of file mdtSqlFieldHandler.cpp.
QVariant mdtSqlFieldHandlerLineEdit::data () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 167 of file mdtSqlFieldHandler.cpp.
Referenced by isNull().
bool mdtSqlFieldHandlerLineEdit::isNull () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 177 of file mdtSqlFieldHandler.cpp.
References data().
void mdtSqlFieldHandlerLineEdit::setData (const QVariant & data) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 160 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandlerLineEdit::setLineEdit (QLineEdit * le)
Definition at line 153 of file mdtSqlFieldHandler.cpp.
Referenced by mdtSqlFieldHandler::setDataWidget().
void mdtSqlFieldHandlerLineEdit::setMaxLength (int maxLength) virtual
Reimplemented from mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 201 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandlerLineEdit::setReadOnly (bool readOnly) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 194 of file mdtSqlFieldHandler.cpp.
QWidget * mdtSqlFieldHandlerLineEdit::widget () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 189 of file mdtSqlFieldHandler.cpp.
The documentation for this class was generated from the following file:
src/mdtdatabase/mdtSqlFieldHandler.cpp