Multi diag tools: mdtClUnitConnectorData Class Reference
mdtClUnitConnectorData Class Reference
Data container class for article connector data.
#include <mdtClUnitConnectorData.h>
Public Member Functions
mdtClUnitConnectorData ()
Construct a empty mdtClUnitConnectorData.
mdtClUnitConnectorData (const QSqlRecord &record)
Contruct a mdtClUnitConnectorData from a QSqlRecord.
bool setup (const QSqlDatabase &db, bool setupCd, bool setupAcd)
Setup fields from UnitConnector_tbl.
void clearValues ()
Clear values.
void clear ()
Clear values and fields.
void setConnectionDataList (const QList< mdtClUnitConnectionData > &dataList)
Add a list of connection data.
const QList
< mdtClUnitConnectionData > & connectionDataList () const
Get list of connection data.
QList< mdtClUnitConnectionData > & connectionDataList ()
Get list of connection data.
void addConnectionData (const mdtClUnitConnectionData &data)
Add connection data.
bool setConnectionData (const QVariant &connectionId, const mdtClUnitConnectionData &data)
Update existing connection data.
mdtClUnitConnectionData connectionData (const QVariant &connectionId, bool *ok) const
Get connection data for given connection ID.
void setConnectorData (const mdtClConnectorData &data)
Set connector data.
mdtClConnectorData connectorData () const
Get connector data (from Connector_tbl)
void setArticleConnectorData (const mdtClArticleConnectorData &data)
Set article connector data.
mdtClArticleConnectorData articleConnectorData () const
Get article connector data.
bool isBasedOnArticleConnector () const
Check if unit connector is based on a article connector.
bool isBasedOnConnector () const
Check if unit connector is based on a connector (from Connector_tbl)
Public Member Functions inherited from mdtSqlRecord
mdtSqlRecord ()
Constructor.
mdtSqlRecord (const QSqlRecord &sqlRecord)
Build a mdtSqlRecord on the base of a QSqlRecord.
virtual ~mdtSqlRecord ()
Destructor.
operator QSqlRecord ()
Get QSqlRecord version.
bool addField (const QString &fieldName, const QString &tableName, const QSqlDatabase &db)
Add a field to record.
bool addAllFields (const QString &tableName, const QSqlDatabase &db)
Add all fields of given table to record.
int count () const
Returns the number of fields in the record.
bool isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
QSqlField field (int index) const
Returns the field at position index.
QSqlField field (const QString &name) const
Returns the field called name.
int indexOf (const QString &name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
bool contains (const QString &name) const
Returns true if there is a field in the record called name; otherwise returns false.
QStringList fieldNames () const
Get a list with all field names.
bool hasValue (int fieldIndex) const
Check if a value was set.
bool hasValue (const QString &fieldName) const
Check if a value was set.
void setValue (int fieldIndex, const QVariant &val)
Set value.
void setValue (const QString &fieldName, const QVariant &val)
Set value.
QVariant value (int index) const
Returns the value of the field located at position index in the record.
QVariant value (const QString &name) const
Returns the value of the field called name in the record.
mdtError lastError () const
Get last error.
QVector< int > fieldIndexesWithValue () const
Get a list with field indexes that have a value.
QString sqlForInsert (const QString &tableName) const
Get SQL statement for insertion with QSqlQuery.
QString sqlForUpdate (const QString &tableName, const QSqlRecord &matchData) const
Get SQL statement for update with QSqlQuery.
QString dataToUpdateInfo () const
Get information about data that has a value to update (for debug)
Additional Inherited Members
Static Public Member Functions inherited from mdtSqlRecord
static QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtSqlRecord
mdtError pvLastError
Detailed Description
Data container class for article connector data.
Permit to echange data with UnitConnector_tbl and UnitConnection_tbl.
Definition at line 36 of file mdtClUnitConnectorData.h.
Constructor & Destructor Documentation
mdtClUnitConnectorData::mdtClUnitConnectorData ()
Construct a empty mdtClUnitConnectorData.
Definition at line 24 of file mdtClUnitConnectorData.cpp.
mdtClUnitConnectorData::mdtClUnitConnectorData (const QSqlRecord & record)
Contruct a mdtClUnitConnectorData from a QSqlRecord.
Note: if this method is used, setup is not relevant.
Precondition
All fields from UnitConnector_tbl must exist in record
Definition at line 28 of file mdtClUnitConnectorData.cpp.
References mdtSqlRecord::contains().
Member Function Documentation
void mdtClUnitConnectorData::addConnectionData (const mdtClUnitConnectionData & data)
Add connection data.
Precondition
data must contains following fields:
Id_PK
Unit_Id_FK
UnitConnector_Id_FK
ArticleConnection_Id_FK
UnitContactName
SchemaPage
SignalName
SwAddress
FunctionEN
FunctionFR
FunctionDE
FunctionIT
Definition at line 87 of file mdtClUnitConnectorData.cpp.
References mdtSqlRecord::contains().
Referenced by mdtClUnit::addConnectionDataListFromArticleConnectionIdList(), and mdtClUnit::addConnectionDataListFromConnectorContactIdList().
mdtClArticleConnectorData mdtClUnitConnectorData::articleConnectorData () const
Get article connector data.
Definition at line 163 of file mdtClUnitConnectorData.cpp.
void mdtClUnitConnectorData::clear () virtual
Clear values and fields.
Will clear values, including connection data. Fields are also removed.
Reimplemented from mdtSqlRecord.
Definition at line 63 of file mdtClUnitConnectorData.cpp.
References mdtClArticleConnectorData::clear(), and mdtSqlRecord::clear().
void mdtClUnitConnectorData::clearValues () virtual
Clear values.
Will clear values, including connection data. Fields are keeped.
Reimplemented from mdtSqlRecord.
Definition at line 55 of file mdtClUnitConnectorData.cpp.
References mdtClArticleConnectorData::clearValues(), and mdtSqlRecord::clearValues().
mdtClUnitConnectionData mdtClUnitConnectorData::connectionData (const QVariant & connectionId, bool * ok) const
Get connection data for given connection ID.
Return the connection data for witch Id_PK matches given connectionId. ok will be set to false if connectionId was not found.
Definition at line 123 of file mdtClUnitConnectorData.cpp.
const QList< mdtClUnitConnectionData > & mdtClUnitConnectorData::connectionDataList () const
Get list of connection data.
Definition at line 77 of file mdtClUnitConnectorData.cpp.
Referenced by mdtClUnit::addConnector(), mdtClLink::canConnectConnectors(), and mdtClLink::connectByContactName().
QList< mdtClUnitConnectionData > & mdtClUnitConnectorData::connectionDataList ()
Get list of connection data.
Definition at line 82 of file mdtClUnitConnectorData.cpp.
mdtClConnectorData mdtClUnitConnectorData::connectorData () const
Get connector data (from Connector_tbl)
Definition at line 150 of file mdtClUnitConnectorData.cpp.
bool mdtClUnitConnectorData::isBasedOnArticleConnector () const
Check if unit connector is based on a article connector.
Definition at line 168 of file mdtClUnitConnectorData.cpp.
References mdtSqlRecord::value().
bool mdtClUnitConnectorData::isBasedOnConnector () const
Check if unit connector is based on a connector (from Connector_tbl)
Definition at line 173 of file mdtClUnitConnectorData.cpp.
References mdtSqlRecord::value().
void mdtClUnitConnectorData::setArticleConnectorData (const mdtClArticleConnectorData & data)
Set article connector data.
Will also update Connector_Id_FK and ArticleConnector_Id_FK
Definition at line 155 of file mdtClUnitConnectorData.cpp.
References mdtClArticleConnectorData::connectorData(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
Referenced by mdtClUnit::addArticleConnectorData().
bool mdtClUnitConnectorData::setConnectionData (const QVariant & connectionId, const mdtClUnitConnectionData & data)
Update existing connection data.
Will update connection data for witch Id_PK matches given connectionId.
Returns
False if connectionId was not found.
Definition at line 105 of file mdtClUnitConnectorData.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtSqlRecord::pvLastError, and mdtError::setError().
void mdtClUnitConnectorData::setConnectionDataList (const QList< mdtClUnitConnectionData > & dataList)
Add a list of connection data.
By using this method, the caller is responsible to give valid records, that contains needed fields.
See Also
addConnectionData().
Definition at line 72 of file mdtClUnitConnectorData.cpp.
void mdtClUnitConnectorData::setConnectorData (const mdtClConnectorData & data)
Set connector data.
Will also update Connector_Id_FK and set ArticleConnector_Id_FK to Null.
Definition at line 142 of file mdtClUnitConnectorData.cpp.
References mdtClArticleConnectorData::clearValues(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
bool mdtClUnitConnectorData::setup (const QSqlDatabase & db, bool setupCd, bool setupAcd)
Setup fields from UnitConnector_tbl.
Parameters
setupCd If true, fields from connector part are also added.
setupAcd If true, fields from article connector part are also added.
Definition at line 39 of file mdtClUnitConnectorData.cpp.
References mdtSqlRecord::addAllFields(), mdtClConnectorData::setup(), and mdtClArticleConnectorData::setup().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitConnectorData.h
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitConnectorData.cpp