Multi diag tools: mdtClUnitLinkDialog Class Reference
mdtClUnitLinkDialog Class Reference
Dialog that let the user edit a unit link.
#include <mdtClUnitLinkDialog.h>
Public Member Functions
mdtClUnitLinkDialog (QWidget *parent, QSqlDatabase db)
Constructor.
~mdtClUnitLinkDialog ()
Destructor.
void setStartUnit (const QVariant &unitId)
Set start unit.
void setStartUnitSelectionList (const QList< QVariant > &idList)
Limit start unit selection to given list.
void clearStartUnitSelectionList ()
Clear start unit selection list.
void setEndUnit (const QVariant &unitId)
Set end unit.
void setEndUnitSelectionList (const QList< QVariant > &idList)
Limit end unit selection to given list.
void clearEndUnitSelectionList ()
Clear end unit selection list.
void setShowOnlyUnusedStartConnection (bool onlyUnused)
Set show only unused start connections.
void setShowOnlyUnusedEndConnection (bool onlyUnused)
Set show only unused end connections.
void setWorkingOnVehicleTypeIdList (const QList< QVariant > &vtIdList)
Set the vehicle type ID list on witch we are working on.
void clearWorkingOnVehicleTypeList ()
Clear the working on vehicle type list.
const QList< QVariant > startVehicleTypeIdList () const
Get selected start vehicle types.
const QList< QVariant > endVehicleTypeIdList () const
Get selected end vehicle types.
void setLinkTypeCode (const QVariant &code)
Display link type in combobox.
QVariant linkTypeCode () const
Get selected link type code.
void setLinkDirectionCode (const QVariant &code)
Display link direction in combobox.
QVariant linkDirectionCode () const
Get selected link direction code.
void setLinkData (mdtClLinkData &data)
Set link data.
mdtClLinkData linkData ()
Get link data.
Detailed Description
Dialog that let the user edit a unit link.
Definition at line 38 of file mdtClUnitLinkDialog.h.
Constructor & Destructor Documentation
mdtClUnitLinkDialog::mdtClUnitLinkDialog (QWidget * parent, QSqlDatabase db)
Constructor.
Definition at line 40 of file mdtClUnitLinkDialog.cpp.
References setLinkTypeCode(), and mdtClLinkData::setup().
mdtClUnitLinkDialog::~mdtClUnitLinkDialog ()
Destructor.
Definition at line 96 of file mdtClUnitLinkDialog.cpp.
Member Function Documentation
void mdtClUnitLinkDialog::clearEndUnitSelectionList ()
Clear end unit selection list.
Definition at line 133 of file mdtClUnitLinkDialog.cpp.
void mdtClUnitLinkDialog::clearStartUnitSelectionList ()
Clear start unit selection list.
Definition at line 114 of file mdtClUnitLinkDialog.cpp.
void mdtClUnitLinkDialog::clearWorkingOnVehicleTypeList ()
Clear the working on vehicle type list.
See Also
setWorkingOnVehicleTypeIdList()
Definition at line 153 of file mdtClUnitLinkDialog.cpp.
const QList< QVariant > mdtClUnitLinkDialog::endVehicleTypeIdList () const
Get selected end vehicle types.
Definition at line 172 of file mdtClUnitLinkDialog.cpp.
mdtClLinkData mdtClUnitLinkDialog::linkData ()
Get link data.
Definition at line 283 of file mdtClUnitLinkDialog.cpp.
QVariant mdtClUnitLinkDialog::linkDirectionCode () const
Get selected link direction code.
Definition at line 234 of file mdtClUnitLinkDialog.cpp.
QVariant mdtClUnitLinkDialog::linkTypeCode () const
Get selected link type code.
Definition at line 202 of file mdtClUnitLinkDialog.cpp.
void mdtClUnitLinkDialog::setEndUnit (const QVariant & unitId)
Set end unit.
This will also clear end connection and set end vehicle types.
Definition at line 119 of file mdtClUnitLinkDialog.cpp.
References mdtClLinkData::setEndConnectionData().
void mdtClUnitLinkDialog::setEndUnitSelectionList (const QList< QVariant > & idList)
Limit end unit selection to given list.
Definition at line 128 of file mdtClUnitLinkDialog.cpp.
void mdtClUnitLinkDialog::setLinkData (mdtClLinkData & data)
Set link data.
Definition at line 250 of file mdtClUnitLinkDialog.cpp.
References mdtClLinkData::endConnectionData(), setLinkDirectionCode(), setLinkTypeCode(), mdtClLinkData::startConnectionData(), mdtSqlRecord::value(), and mdtClLinkData::vehicleTypeLinkDataList().
void mdtClUnitLinkDialog::setLinkDirectionCode (const QVariant & code)
Display link direction in combobox.
Definition at line 218 of file mdtClUnitLinkDialog.cpp.
Referenced by setLinkData().
void mdtClUnitLinkDialog::setLinkTypeCode (const QVariant & code)
Display link type in combobox.
Definition at line 186 of file mdtClUnitLinkDialog.cpp.
Referenced by mdtClUnitLinkDialog(), and setLinkData().
void mdtClUnitLinkDialog::setShowOnlyUnusedEndConnection (bool onlyUnused)
Set show only unused end connections.
Definition at line 143 of file mdtClUnitLinkDialog.cpp.
void mdtClUnitLinkDialog::setShowOnlyUnusedStartConnection (bool onlyUnused)
Set show only unused start connections.
Definition at line 138 of file mdtClUnitLinkDialog.cpp.
void mdtClUnitLinkDialog::setStartUnit (const QVariant & unitId)
Set start unit.
This will also clear start connection and set start vehicle types.
Definition at line 100 of file mdtClUnitLinkDialog.cpp.
References mdtClLinkData::setStartConnectionData().
void mdtClUnitLinkDialog::setStartUnitSelectionList (const QList< QVariant > & idList)
Limit start unit selection to given list.
Definition at line 109 of file mdtClUnitLinkDialog.cpp.
void mdtClUnitLinkDialog::setWorkingOnVehicleTypeIdList (const QList< QVariant > & vtIdList)
Set the vehicle type ID list on witch we are working on.
This will limit the unit selections to those that exists for given vehicle types.
Definition at line 148 of file mdtClUnitLinkDialog.cpp.
const QList< QVariant > mdtClUnitLinkDialog::startVehicleTypeIdList () const
Get selected start vehicle types.
Definition at line 158 of file mdtClUnitLinkDialog.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitLinkDialog.h
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitLinkDialog.cpp