Multi diag tools: mdtClLinkBeam Class Reference
mdtClLinkBeam Class Reference
Helper class for link beam edition.
#include <mdtClLinkBeam.h>
Public Member Functions
mdtClLinkBeam (QObject *parent, QSqlDatabase db)
Constructor.
QString sqlForStartUnitSelection (const QVariant &linkBeamId)
Get SQL statement for start unit selection.
QString sqlForEndUnitSelection (const QVariant &linkBeamId)
Get SQL statement for end unit selection.
QString sqlForLinkSelection (const QList< QVariant > &unitStartIdList, const QList< QVariant > &unitEndIdList) const
Get SQL statement for link add selection.
bool addStartUnit (const QVariant &unitId, const QVariant &linkBeamId)
Add a start unit.
bool removeStartUnit (const QVariant &unitId, const QVariant &linkBeamId)
Remove a start unit.
bool removeStartUnits (const mdtSqlTableSelection &s)
Remove start units from selection.
bool addEndUnit (const QVariant &unitId, const QVariant &linkBeamId)
Add a end unit.
bool removeEndUnit (const QVariant &unitId, const QVariant &linkBeamId)
Remove a end unit.
bool removeEndUnits (const mdtSqlTableSelection &s)
Remove end units from selection.
bool addLink (const QVariant &unitConnectionStartId, const QVariant &unitConnectionEndId, const QVariant &linkBeamId)
Add a existing link to given link beam.
bool removeLinks (const mdtSqlTableSelection &s)
Remove links from beam (will not delete links)
bool removeLink (const QVariant &unitConnectionStartId, const QVariant &unitConnectionEndId)
Remove a link from beam (will not delete links)
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
template<typename T >
bool addRecordList (const QList< T > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField1, const QVariant &key1, const QString &matchField2, const QVariant &key2)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for link beam edition.
Definition at line 35 of file mdtClLinkBeam.h.
Constructor & Destructor Documentation
mdtClLinkBeam::mdtClLinkBeam (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 27 of file mdtClLinkBeam.cpp.
Member Function Documentation
bool mdtClLinkBeam::addEndUnit (const QVariant & unitId, const QVariant & linkBeamId)
Add a end unit.
Definition at line 113 of file mdtClLinkBeam.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, and mdtSqlRecord::setValue().
bool mdtClLinkBeam::addLink (const QVariant & unitConnectionStartId, const QVariant & unitConnectionEndId, const QVariant & linkBeamId)
Add a existing link to given link beam.
Definition at line 137 of file mdtClLinkBeam.cpp.
References mdtSqlRecord::addField(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtSqlRecord::setValue(), and mdtTtBase::updateRecord().
bool mdtClLinkBeam::addStartUnit (const QVariant & unitId, const QVariant & linkBeamId)
Add a start unit.
Definition at line 89 of file mdtClLinkBeam.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, and mdtSqlRecord::setValue().
bool mdtClLinkBeam::removeEndUnit (const QVariant & unitId, const QVariant & linkBeamId)
Remove a end unit.
Definition at line 127 of file mdtClLinkBeam.cpp.
References mdtTtBase::removeData().
bool mdtClLinkBeam::removeEndUnits (const mdtSqlTableSelection & s)
Remove end units from selection.
Definition at line 132 of file mdtClLinkBeam.cpp.
References mdtTtBase::removeData().
bool mdtClLinkBeam::removeLink (const QVariant & unitConnectionStartId, const QVariant & unitConnectionEndId)
Remove a link from beam (will not delete links)
Definition at line 183 of file mdtClLinkBeam.cpp.
References mdtSqlRecord::addField(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtSqlRecord::setValue(), and mdtTtBase::updateRecord().
Referenced by removeLinks().
bool mdtClLinkBeam::removeLinks (const mdtSqlTableSelection & s)
Remove links from beam (will not delete links)
Definition at line 163 of file mdtClLinkBeam.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtSqlTableSelection::data(), removeLink(), mdtTtBase::rollbackTransaction(), and mdtSqlTableSelection::rowCount().
bool mdtClLinkBeam::removeStartUnit (const QVariant & unitId, const QVariant & linkBeamId)
Remove a start unit.
Definition at line 103 of file mdtClLinkBeam.cpp.
References mdtTtBase::removeData().
bool mdtClLinkBeam::removeStartUnits (const mdtSqlTableSelection & s)
Remove start units from selection.
Definition at line 108 of file mdtClLinkBeam.cpp.
References mdtTtBase::removeData().
QString mdtClLinkBeam::sqlForEndUnitSelection (const QVariant & linkBeamId)
Get SQL statement for end unit selection.
List all units that are not currently affected to given link beam.
Definition at line 44 of file mdtClLinkBeam.cpp.
QString mdtClLinkBeam::sqlForLinkSelection (const QList< QVariant > & unitStartIdList, const QList< QVariant > & unitEndIdList) const
Get SQL statement for link add selection.
List all links that starts from one of given start units, and ends from one of given end units, and that are not currently affected to a link beam.
Definition at line 56 of file mdtClLinkBeam.cpp.
QString mdtClLinkBeam::sqlForStartUnitSelection (const QVariant & linkBeamId)
Get SQL statement for start unit selection.
List all units that are not currently affected to given link beam.
Definition at line 32 of file mdtClLinkBeam.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClLinkBeam.h
src/mdttools/mdttesttool/mdtcablelist/mdtClLinkBeam.cpp