Multi diag tools: mdtDeviceModbusWago Class Reference
mdtDeviceModbusWago Class Reference
#include <mdtDeviceModbusWago.h>
Public Member Functions
mdtDeviceModbusWago (QObject *parent=0)
Constructor.
~mdtDeviceModbusWago ()
Destructor.
mdtAbstractPort::error_t connectToDevice (const mdtPortInfo &portInfo)
Connect to physical device.
mdtAbstractPort::error_t connectToDevice (const mdtDeviceInfo &devInfo)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice (const QList< mdtPortInfo * > &scanResult, int hardwareNodeId, int bitsCount, int startFrom=0)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice (const QList< int > &existingHwNodeIdList)
Search and connect to physical device.
bool isWago750 ()
Check if device is a Wago 750 series.
int analogOutputsCount ()
Get number of analog outputs.
int analogInputsCount ()
Get number of analog inputs.
int digitalOutputsCount ()
Get number of digital outputs.
int digitalInputsCount ()
Get number of digital inputs.
bool detectIos (const QMap< int, mdtDeviceModbusWagoModule * > specialModules=QMap< int, mdtDeviceModbusWagoModule * >())
Query device about filed bus + I/Os setup.
Public Member Functions inherited from mdtDeviceModbus
mdtDeviceModbus (QObject *parent=0)
virtual ~mdtDeviceModbus ()
mdtPortManager * portManager ()
Get internal port manager instance.
mdtModbusTcpPortManager * modbusTcpPortManager ()
Get internal port manager instance.
mdtAbstractPort::error_t connectToDevice (const mdtDeviceInfo &devInfo)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice (const QList< mdtPortInfo * > &scanResult, int hardwareNodeId, int bitsCount, int startFrom=0)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice (const QList< int > &existingHwNodeIdList)
Search and connect to physical device.
mdtAbstractPort::error_t connectToDevice ()
Search and connect to physical device.
bool getRegisterValues (int address, int n)
Helper method for register service.
const QList< int > & registerValues () const
Helper method for register service.
bool setRegisterValues (int startAddress, QList< int > &values)
Helper method for register service.
Public Member Functions inherited from mdtMultiIoDevice
mdtMultiIoDevice (QObject *parent=0)
Construct a multi I/O device object.
virtual ~mdtMultiIoDevice ()
Destructor.
void addInput (mdtAnalogIo *analogInput)
Add a analog input.
void addInputs (const QList< mdtAnalogIo * > &analogInputs)
Add a list of analog inputs.
void addOutput (mdtAnalogIo *analogOutput)
Add a analog output.
void addOutputs (const QList< mdtAnalogIo * > &analogOutputs)
Add a list of analog outputs.
void addInput (mdtDigitalIo *digitalInput)
Add a digital input.
void addInputs (const QList< mdtDigitalIo * > &digitalInputs)
Add a list of digital inputs.
void addOutput (mdtDigitalIo *digitalOutput)
Add a digital output.
void addOutputs (const QList< mdtDigitalIo * > &digitalOutputs)
Add a list of digital outputs.
void deleteIos ()
Delete all I/O in container.
std::shared_ptr< mdtDeviceIos > ios ()
Access internal I/Os container.
mdtValue getAnalogInputValue (mdtAnalogIo *analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (int address, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogInputs (bool waitOnReply)
Read all analog inputs on physical device and update (G)UI representation.
mdtValue getAnalogOutputValue (mdtAnalogIo *analogOutput, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogOutputs (bool waitOnReply)
Read all analog outputs on physical device and update (G)UI representation.
int setAnalogOutputValue (mdtAnalogIo *analogOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
int setAnalogOutputs (bool waitOnReply)
Write all analog outputs on physical device and update (G)UI representation.
mdtValue getDigitalInputValue (mdtDigitalIo *digitalInput, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (int address, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalInputs (bool waitOnReply)
Read all digital inputs on physical device and update (G)UI representation.
mdtValue getDigitalOutputValue (mdtDigitalIo *digitalOutput, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalOutputs (bool waitOnReply)
Read all digital outputs on physical device and update (G)UI representation.
int setDigitalOutputValue (mdtDigitalIo *digitalOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a digital output value.
int setDigitalOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputsValue (const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a value and validity for all digital outputs.
int setDigitalOutputs (bool waitOnReply)
Write all digital outputs to physical device and update (G)UI representation.
Public Member Functions inherited from mdtDevice
mdtDevice (QObject *parent=0)
Construct a device object.
virtual ~mdtDevice ()
Destructor.
void setName (const QString &name)
Set the device name.
QString name () const
Get device name.
void setIdentification (const QVariant &id)
Set device identification.
QVariant identification () const
Get device identification.
virtual bool connectToDevice (const mdtDeviceAddress &address)
Search and connect to physical device.
void disconnectFromDevice ()
Disconnect from device.
void setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
virtual bool isReady ()
Check if device is ready.
void start (int queryInterval)
Start periodic device querying.
void stop ()
Stop periodic device querying.
void wait (int t)
Wait some time without breaking main event loop.
mdtError lastError () const
Get last error.
State_t currentState () const
Get current state.
Additional Inherited Members
Public Types inherited from mdtDevice
enum State_t { State_t::Disconnected, State_t::Connecting, State_t::Ready, State_t::Error }
State of device.
Public Slots inherited from mdtMultiIoDevice
void setAnalogOutputValue (mdtAnalogIo *analogOutput)
Set value on a analog output on physical device.
void setDigitalOutputValue (mdtDigitalIo *digitalOutput)
Set value on a digital output on physical device.
Public Slots inherited from mdtDevice
void runQueries ()
Queries to send periodically.
Signals inherited from mdtDevice
void stateChanged (State_t state)
Emitted when state has changed.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
Protected Member Functions inherited from mdtDeviceModbus
int readAnalogInput (mdtPortTransaction *transaction)
Read one analog input on physical device.
int readAnalogInputs (mdtPortTransaction *transaction)
Read all analog inputs on physical device.
int readAnalogOutput (mdtPortTransaction *transaction)
Read one analog output on physical device.
int readAnalogOutputs (mdtPortTransaction *transaction)
Read all analog outputs on physical device.
int writeAnalogOutput (int value, mdtPortTransaction *transaction)
Write value on a analog output to physical device.
int writeAnalogOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all analog outputs to physical device.
int readDigitalInput (mdtPortTransaction *transaction)
Read one digital input on physical device.
int readDigitalInputs (mdtPortTransaction *transaction)
Read all digital inputs on physical device.
int readDigitalOutput (mdtPortTransaction *transaction)
Read one digital output on physical device.
int readDigitalOutputs (mdtPortTransaction *transaction)
Read all digital outputs on physical device.
int writeDigitalOutput (bool state, mdtPortTransaction *transaction)
Write state on a digital output to physical device.
int writeDigitalOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all digital outputs to physical device.
bool queriesSequence ()
Sequence of queries to send periodically.
Protected Member Functions inherited from mdtMultiIoDevice
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
bool waitTransactionDone (int id)
Wait until a transaction is done without break the GUI's event loop.
void stateChangedEvent (State_t newState)
Called when current state has changed.
Protected Member Functions inherited from mdtDevice
QString deviceIdString () const
Get device identification string.
void setCurrentState (State_t state)
Set current state.
virtual void nameChangedEvent (const QString &newName)
Called by setName()
Protected Attributes inherited from mdtDeviceModbus
mdtModbusTcpPortManager * pvTcpPortManager
mdtFrameCodecModbus * pvCodec
Protected Attributes inherited from mdtDevice
mdtError pvLastError
Last error object.
Detailed Description
Definition at line 35 of file mdtDeviceModbusWago.h.
Constructor & Destructor Documentation
mdtDeviceModbusWago::mdtDeviceModbusWago (QObject * parent = 0)
Constructor.
Definition at line 39 of file mdtDeviceModbusWago.cpp.
mdtDeviceModbusWago::~mdtDeviceModbusWago ()
Destructor.
Definition at line 44 of file mdtDeviceModbusWago.cpp.
Member Function Documentation
int mdtDeviceModbusWago::analogInputsCount ()
Get number of analog inputs.
Note: calling this method will query the device
Returns
Number of analog inputs, or < 0 on error
Definition at line 116 of file mdtDeviceModbusWago.cpp.
References mdtDeviceModbus::getRegisterValues(), and mdtDeviceModbus::registerValues().
Referenced by detectIos().
int mdtDeviceModbusWago::analogOutputsCount ()
Get number of analog outputs.
Note: calling this method will query the device
Returns
Number of analog outputs, or < 0 on error
Definition at line 105 of file mdtDeviceModbusWago.cpp.
References mdtDeviceModbus::getRegisterValues(), and mdtDeviceModbus::registerValues().
Referenced by detectIos().
mdtAbstractPort::error_t mdtDeviceModbusWago::connectToDevice (const mdtPortInfo & portInfo) virtual
Connect to physical device.
This method can be reimplemented in subclass if specific tasks must be done during connection .
Parameters
portInfo mdtPortInfo object . The portName attribute of portInfo must contain host:port format (or ip:port) .
Returns
A error listed in mdtAbstractPort::error_t (NoError on success) .
Reimplemented from mdtDeviceModbus.
Definition at line 49 of file mdtDeviceModbusWago.cpp.
References mdtPortManager::isClosed(), isWago750(), mdtAbstractPort::NoError, mdtPortInfo::portName(), mdtAbstractPort::PortNotFound, mdtDeviceModbus::pvTcpPortManager, mdtPortManager::setPortInfo(), mdtPortManager::start(), and mdtPortManager::stop().
mdtAbstractPort::error_t mdtDeviceModbusWago::connectToDevice (const mdtDeviceInfo & devInfo)
Search and connect to physical device.
See Also
mdtDeviceModbus::connectToDevice(const mdtDeviceInfo&) .
Definition at line 69 of file mdtDeviceModbusWago.cpp.
References mdtDeviceModbus::connectToDevice().
mdtAbstractPort::error_t mdtDeviceModbusWago::connectToDevice (const QList< mdtPortInfo * > & scanResult, int hardwareNodeId, int bitsCount, int startFrom = 0)
Search and connect to physical device.
Work as mdtDeviceModbus::connectToDevice() , but checks that device is a Wago 750 fieldbus coupler.
Definition at line 74 of file mdtDeviceModbusWago.cpp.
References mdtDeviceModbus::connectToDevice().
mdtAbstractPort::error_t mdtDeviceModbusWago::connectToDevice (const QList< int > & existingHwNodeIdList)
Search and connect to physical device.
See mdtDeviceModbus::connectToDevice(const QList<int>&) .
Definition at line 79 of file mdtDeviceModbusWago.cpp.
References mdtDeviceModbus::connectToDevice().
bool mdtDeviceModbusWago::detectIos (const QMap< int, mdtDeviceModbusWagoModule * > specialModules = QMap<int, mdtDeviceModbusWagoModule*>())
Query device about filed bus + I/Os setup.
For some special configurable modules, channels count and process image format can vary. Because some of these parameters cannot be readen from module via MODBUS, a instance of a module object with corresponding setup must be given as argument. (It's also possible to specify only the special modules. Internally, setup regarding register word returned from fieldbus coupler will be used for positions that are not present in the map).
Parameters
specialModules Map with module position as key and special module object as value. Note: position 0 is the fieldbus coupler, so module position starts at 1. Module objects contained in the map are not deleted in this method.
Returns
True on success. A failure is mostly due to a communication error, an unsupported fieldbus coupler, a unsupported module or a mistmatch with a special module configuration.
Definition at line 149 of file mdtDeviceModbusWago.cpp.
References mdtMultiIoDevice::addInputs(), mdtMultiIoDevice::addOutputs(), mdtDeviceModbusWagoModule::analogInputs(), analogInputsCount(), mdtDeviceModbusWagoModule::analogOutputs(), analogOutputsCount(), mdtDeviceModbusWagoModule::clear(), mdtError::commit(), mdtMultiIoDevice::deleteIos(), mdtDeviceModbusWagoModule::digitalInputs(), digitalInputsCount(), mdtDeviceModbusWagoModule::digitalOutputs(), digitalOutputsCount(), mdtError::Error, mdtDeviceModbus::getRegisterValues(), mdtMultiIoDevice::ios(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtDevice::name(), mdtDeviceModbusWagoModule::nextModuleFirstAiAddress(), mdtDeviceModbusWagoModule::nextModuleFirstAoAddressRead(), mdtDeviceModbusWagoModule::nextModuleFirstAoAddressWrite(), mdtDeviceModbusWagoModule::nextModuleFirstDiAddress(), mdtDeviceModbusWagoModule::nextModuleFirstDoAddressRead(), mdtDeviceModbusWagoModule::nextModuleFirstDoAddressWrite(), mdtDeviceModbus::registerValues(), mdtDeviceModbusWagoModule::setupFromRegisterWord(), mdtDeviceModbusWagoModule::type(), mdtDeviceModbusWagoModule::Unknown, and mdtDeviceModbusWagoModule::updateAddresses().
int mdtDeviceModbusWago::digitalInputsCount ()
Get number of digital inputs.
Note: calling this method will query the device
Returns
Number of digital inputs, or < 0 on error
Definition at line 138 of file mdtDeviceModbusWago.cpp.
References mdtDeviceModbus::getRegisterValues(), and mdtDeviceModbus::registerValues().
Referenced by detectIos().
int mdtDeviceModbusWago::digitalOutputsCount ()
Get number of digital outputs.
Note: calling this method will query the device
Returns
Number of digital outputs, or < 0 on error
Definition at line 127 of file mdtDeviceModbusWago.cpp.
References mdtDeviceModbus::getRegisterValues(), and mdtDeviceModbus::registerValues().
Referenced by detectIos().
bool mdtDeviceModbusWago::isWago750 ()
Check if device is a Wago 750 series.
Definition at line 84 of file mdtDeviceModbusWago.cpp.
References mdtError::commit(), mdtDeviceModbus::getRegisterValues(), mdtError::Info, MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtDevice::name(), and mdtDeviceModbus::registerValues().
Referenced by connectToDevice().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceModbusWago.h
src/mdtdevice/mdtDeviceModbusWago.cpp