Multi diag tools: mdtBlinkLed Class Reference
mdtBlinkLed Class Reference
Blinking LED.
#include <mdtBlinkLed.h>
Public Slots
void setOn ()
Set the LED ON.
void setOn (bool on)
Set the LED ON or OFF.
void setOn (int holdTime, bool priority=false)
Set the LED ON for a given time.
void setOff ()
Set the LED OFF.
Public Slots inherited from mdtLed
void setOn ()
Set the LED ON.
void setOff ()
Set the LED OFF.
void setOn (bool on)
Set the LED ON or OFF.
void toggleOnOff ()
Toggle On/Off.
Public Member Functions
mdtBlinkLed (QWidget *parent=0)
void setBlinkPeriod (int T)
Set blinking period.
void setBlinking (bool on)
Set LED blinking.
Public Member Functions inherited from mdtLed
mdtLed (QWidget *parent=0)
Contruct a new mdtLED.
void setBorders (int horizontalBorder, int verticalBorder)
Set the borders.
void setGreen ()
Set the LED color to green.
void setOrange ()
Set the LED color to orange.
void setRed ()
Set the LED color to red.
void setColor (color_t color)
Set the LED color.
void setFlat ()
Set a simple flat LED.
void setGlint ()
Set a glint LED.
void setTextMode ()
Set the LED as text.
void setAntialiasing (bool enabled)
Enable the antialiasing.
void setFixedSize (int width, int height)
Force the LED to have a fixed size.
void setAutoSize ()
Use Qt QSizePolicy to resize the LED.
QSize sizeHint () const
QSize minimumSizeHint () const
bool isOn ()
Get the LED ON state.
Additional Inherited Members
Public Types inherited from mdtLed
enum color_t { Green, Orange, Red }
LED predefined colors.
Protected Member Functions inherited from mdtLed
void paintEvent (QPaintEvent *)
Detailed Description
Blinking LED.
This class can be helpfull to get a blinking LED in a simple way.
If a lot of blinking LED's are needed, it is recommanded to use mdtLed objects and one QTimer, and to connect the QTimer::timeout() signal to each mdtLed::toggleOnOff() slot.
Definition at line 34 of file mdtBlinkLed.h.
Constructor & Destructor Documentation
mdtBlinkLed::mdtBlinkLed (QWidget * parent = 0)
Definition at line 23 of file mdtBlinkLed.cpp.
References setBlinkPeriod(), and mdtLed::toggleOnOff().
Member Function Documentation
void mdtBlinkLed::setBlinking (bool on)
Set LED blinking.
Set the LED blinking. The blink period can be changed with setBlinkPeriod() When setOn() or setOff() is called, the blinking is cancelled.
Parameters
on If true, the LED goes blinking.
Definition at line 38 of file mdtBlinkLed.cpp.
Referenced by setOff(), and setOn().
void mdtBlinkLed::setBlinkPeriod (int T)
Set blinking period.
In 1 period, the LED toogles 1x ON ant 1x OFF (The time whenn the LED is ON is 1/2 period)
Parameters
T The period ms
Definition at line 30 of file mdtBlinkLed.cpp.
Referenced by mdtBlinkLed().
void mdtBlinkLed::setOff () slot
Set the LED OFF.
Definition at line 74 of file mdtBlinkLed.cpp.
References setBlinking(), and mdtLed::setOff().
void mdtBlinkLed::setOn () slot
Set the LED ON.
Definition at line 48 of file mdtBlinkLed.cpp.
References setBlinking(), and mdtLed::setOn().
Referenced by mdtPortStatusWidget::setState().
void mdtBlinkLed::setOn (bool on) slot
Set the LED ON or OFF.
Parameters
on If true, the LED is set ON , else OFF
Definition at line 54 of file mdtBlinkLed.cpp.
References setBlinking(), and mdtLed::setOn().
void mdtBlinkLed::setOn (int holdTime, bool priority = false) slot
Set the LED ON for a given time.
The LED will set ON and hold this state for specified time. After this time, the LED goes back OFF.
Parameters
holdTime ON state hold time [ms]
priority If true, cancel allready running shot.
Definition at line 60 of file mdtBlinkLed.cpp.
References mdtLed::setOn().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtBlinkLed.h
src/mdtutilsgui/mdtBlinkLed.cpp