Multi diag tools: mdtPartitionAttributes Class Reference
mdtPartitionAttributes Class Reference
Get some attributes of a file system partition.
#include <mdtPartitionAttributes.h>
Public Member Functions
mdtPartitionAttributes ()
~mdtPartitionAttributes ()
bool setPath (const QString &path)
Set the path of partition on wich the infos must be retreived.
QString rootPath (bool nativeFormat=false)
Get the root path.
QString & name ()
Get the partition name.
bool isReadOnly ()
Returns true if partition is read only.
bool isWriteable ()
Returns true if partition is writeable.
QString & fileSystem ()
Returns the name of partition filesystem.
Static Public Member Functions
static QStringList availablePartitions (const QStringList &ignoreList=QStringList())
Get the list of system's available partitions.
Detailed Description
Get some attributes of a file system partition.
Note: this class is not thread safe
Definition at line 31 of file mdtPartitionAttributes.h.
Constructor & Destructor Documentation
mdtPartitionAttributes::mdtPartitionAttributes ()
Definition at line 24 of file mdtPartitionAttributes.cpp.
mdtPartitionAttributes::~mdtPartitionAttributes ()
Definition at line 29 of file mdtPartitionAttributes.cpp.
Member Function Documentation
QStringList mdtPartitionAttributes::availablePartitions (const QStringList & ignoreList = QStringList()) static
Get the list of system's available partitions.
On Linux, this return mounted partitions (reading /etc/mtab)
Note: could be fixed in future, when I understand something in DBus :)
On Windows, returns the paths geven by QDir::drives()
Parameters
ignoreList All paths listed here will not be returned (ignore list can contain / , C:/ ,... , but NOT C:)
Definition at line 90 of file mdtPartitionAttributesPosix.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_FILE_IO_ERROR, and mdtError::setSystemError().
QString & mdtPartitionAttributes::fileSystem ()
Returns the name of partition filesystem.
Filesystem name could be ext3 , NTFS, ...
Definition at line 60 of file mdtPartitionAttributes.cpp.
bool mdtPartitionAttributes::isReadOnly ()
Returns true if partition is read only.
Definition at line 50 of file mdtPartitionAttributes.cpp.
bool mdtPartitionAttributes::isWriteable ()
Returns true if partition is writeable.
Definition at line 55 of file mdtPartitionAttributes.cpp.
QString & mdtPartitionAttributes::name ()
Get the partition name.
On Windows, name can be a CD-ROM name, USB Key partition name, ... On Linux, name is the device path like /dev/sda1
Definition at line 45 of file mdtPartitionAttributes.cpp.
QString mdtPartitionAttributes::rootPath (bool nativeFormat = false)
Get the root path.
For example, if /usr is on partition / , and /usr was passed to setPath() , this method will return /
Similar on Wondows, if C: was passed to setPath() , C:/ is returned.
On Windows, if nativeFormat is true, the \ separator is used, else, POSIX / separator is used in returned path.
Definition at line 35 of file mdtPartitionAttributes.cpp.
bool mdtPartitionAttributes::setPath (const QString & path)
Set the path of partition on wich the infos must be retreived.
On POSIX, path could be / , /home, ...
On Windows, it can be C:\ , D:.
Returns
False if partition attributes could not be fetsched.
Definition at line 32 of file mdtPartitionAttributesPosix.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_FILE_IO_ERROR, and mdtError::setSystemError().
The documentation for this class was generated from the following files:
src/mdtutils/mdtPartitionAttributes.h
src/mdtutils/linux/mdtPartitionAttributesPosix.cpp
src/mdtutils/mdtPartitionAttributes.cpp
src/mdtutils/windows/mdtPartitionAttributesWindows.cpp