Multi diag tools: mdtSqlFormWidget Class Reference
mdtSqlFormWidget Class Reference
Widget that accept a user designed form and helps dealing with table model.
#include <mdtSqlFormWidget.h>
Public Slots
void toFirst ()
Set first record as current record.
void toLast ()
Set last record as current record.
void toPrevious ()
Set previous record as current record.
void toNext ()
Set next record as current record.
void setCurrentIndex (int row)
Set row as current record.
Public Slots inherited from mdtAbstractSqlWidget
void submit ()
Submit current record to model.
void revert ()
Revert current record from model.
void insert ()
Insert a new row to model.
void remove ()
Remove a row from model.
virtual void toFirst ()=0
Set first record as current record.
virtual void toLast ()=0
Set last record as current record.
virtual void toPrevious ()=0
Set previous record as current record.
virtual void toNext ()=0
Set next record as current record.
virtual void setCurrentIndex (int row)=0
Set row as current record.
bool setCurrentRecord (const QString &fieldName, const QVariant &value)
Set the first record that matches given criteria as current record (index).
Public Member Functions
mdtSqlFormWidget (QWidget *parent=0)
Constructor.
~mdtSqlFormWidget ()
Destructor.
void mapFormWidgets (QWidget *widget, const QString &firstWidgetInTabOrder=QString())
Map widgets to matching database fields.
void mapFormWidgets (const QString &firstWidgetInTabOrder=QString())
Map widgets to matching database fields.
QWidgetList mappedWidgets () const
Get a list of mapped widgets.
int currentRow () const
Get the current row.
Public Member Functions inherited from mdtAbstractSqlWidget
mdtAbstractSqlWidget (QWidget *parent=0)
Constructor.
virtual ~mdtAbstractSqlWidget ()
Destructor.
void setAskUserBeforRevert (bool ask)
Ask user before revert occurs.
void setModel (QSqlTableModel *model)
Set the table model.
QSqlTableModel * model ()
Get current model.
void start ()
Start internal state machine.
void addDataValidator (mdtSqlDataValidator *validator, bool putAtTopPriority=false)
Add a data validator.
void setUserFriendlyTableName (const QString &name)
Set the user friendly table name.
QString userFriendlyTableName () const
Get the user friendly table name.
void addChildWidget (mdtAbstractSqlWidget *widget, mdtSqlRelation *relation)
Add a child (details) widget and relation.
QList< mdtAbstractSqlWidget * > sqlWidgets ()
Get a list of all SQL widgets.
bool setCurrentData (const QString &fieldName, const QVariant &data, bool submit=true)
Set (update) data of current row (record) for given field name.
QVariant currentData (const QString &fieldName) const
Get current data for given field name.
QVariant data (int row, const QString &fieldName) const
Get data for given row and field name.
int rowCount () const
Get row count.
state_t currentState () const
Get current state.
virtual void enableLocalNavigation ()
Enable local navigation.
virtual void enableLocalEdition ()
Enable local edition.
bool allDataAreSaved (bool showMessageBoxIfNotSaved=true)
Check if all data are saved.
void clearColumnsSortOrder ()
Clear columns sort order.
void addColumnToSortOrder (const QString &fieldName, Qt::SortOrder order=Qt::AscendingOrder)
Add a column to columns sort order.
virtual void sort ()
Sort data.
bool submitAndWait (int timeout=-1)
Submit and wait until success or failure.
mdtError lastError () const
Get last error.
Additional Inherited Members
Public Types inherited from mdtAbstractSqlWidget
enum state_t {
Visualizing = 0, Reverting, Editing, Submitting,
Inserting, EditingNewRow, RevertingNewRow, SubmittingNewRow,
Removing
}
State of edit/view widget.
Signals inherited from mdtAbstractSqlWidget
void toFirstEnabledStateChanged (bool enabled)
Emitted when toFirst() function goes enabled/disabled.
void toLastEnabledStateChanged (bool enabled)
Emitted when toLast() function goes enabled/disabled.
void toNextEnabledStateChanged (bool enabled)
Emitted when toNext() function goes enabled/disabled.
void toPreviousEnabledStateChanged (bool enabled)
Emitted when toPrevious() function goes enabled/disabled.
void submitEnabledStateChanged (bool enabled)
Emitted when submit() function goes enabled/disabled.
void revertEnabledStateChanged (bool enabled)
Emitted when revert() function goes enabled/disabled.
void insertEnabledStateChanged (bool enabled)
Emitted when insert() function goes enabled/disabled.
void removeEnabledStateChanged (bool enabled)
Emitted when remove() function goes enabled/disabled.
void submitTriggered ()
Emitted when submit() was called.
void revertTriggered ()
Emitted when revert() was called.
void insertTriggered ()
Emitted when insert() was called.
void removeTriggered ()
Emitted when remove() was called.
void errorOccured ()
Emitted when a error occured.
void operationSucceed ()
Emitted when a operation succeed.
void dataEdited ()
Emitted when data was edited.
void stateVisualizingEntered ()
Emitted when Visualizing state was entered.
void stateVisualizingExited ()
Emitted when Visualizing state was exited.
void stateEditingExited ()
Emitted when Editing state was exited.
void stateEditingNewRowExited ()
Emitted when Editing state was exited.
void currentRowChanged (int row)
Emitted when current row has changed.
void modelSelected ()
Emitted when select() or setQuery() was called on (parent) model.
Protected Member Functions inherited from mdtAbstractSqlWidget
void displayDatabaseError (QSqlError error)
Display a message to the user regarding error.
QString getUserReadableTextFromSqliteError (const QSqlError &error)
Get message for the user regarding SQLite error number.
QString getUserReadableTextFromMysqlError (const QSqlError &error)
Get message for the user regarding MySql error number.
bool childWidgetsAreInVisaluzingState (bool showMessageBoxIfNotSaved)
Check that child widgtes have no pending data.
void warnUserAboutUnsavedRow (const QString &tableName)
Show a message box to the user to warn him that it should save/revert data.
bool restorePrimaryKeyDataToModel (const QSqlRecord &previousRecord)
Restore primary key data to (parent) model.
mdtSortFilterProxyModel * proxyModel ()
Get internal proxy model.
const mdtSortFilterProxyModel * proxyModel () const
Get internal proxy model.
Protected Attributes inherited from mdtAbstractSqlWidget
mdtError pvLastError
Store last error.
Detailed Description
Widget that accept a user designed form and helps dealing with table model.
To create a database table form, Qt offers several classes. But, if we have to create many forms, we have to deal with common problems (insertion, field mapping, etc..).
It's possible to create a form, for example with Qt Designer, and add needed Widgets (QLineEdit, QSpinBox, ...). It's important to respect a convention here: For each Widget that must display/edit data from database (i.e. model), set the name of the field with fld_ prefix. For example, if we have a field called name, create a QLineEdit with fld_name as object name.
Once your form was created, call his setupUi() method passing mdtSqlFormWidget object as parameter. setupUi() will also create layouts and widgets with mdtSqlFormWidget object as parent. As result, mdtSqlFormWidget object will have a layout with all widgets. Finally, use mapFormWidgets() to do the mapping between widgets and fields in database.
To use the resulting form, set it, f.ex. as central widget of a QMainWindow. See the list of slots to know how to use integrated actions (navigation, insertion, ...).
Internally, mdtSqlDataWidgetMapper is used together with mdtSqlFieldHandler. Errors and user interactions are handled by this class.
See Also
mdtSqlWindow
Definition at line 67 of file mdtSqlFormWidget.h.
Constructor & Destructor Documentation
mdtSqlFormWidget::mdtSqlFormWidget (QWidget * parent = 0)
Constructor.
Definition at line 40 of file mdtSqlFormWidget.cpp.
mdtSqlFormWidget::~mdtSqlFormWidget ()
Destructor.
Definition at line 48 of file mdtSqlFormWidget.cpp.
Member Function Documentation
int mdtSqlFormWidget::currentRow () const virtual
Get the current row.
Current row is the row that is displayed in the form view.
Implements mdtAbstractSqlWidget.
Definition at line 160 of file mdtSqlFormWidget.cpp.
Referenced by mdtSqlForm::addRelation(), and toNext().
void mdtSqlFormWidget::mapFormWidgets (QWidget * widget, const QString & firstWidgetInTabOrder = QString())
Map widgets to matching database fields.
Will parse all child widgets found in layout (and contained widgets layouts), extract widgets that have a fld_ prefix as object name. For each of them, corresponding field will be searched in model (database).
Parameters
widget Widget on witch child widgets must be searched.
firstWidgetInTabOrder It's possible to specify the object name of the first widget in tab order. This is then used by insertion to give this widget the focus.
Precondition
The custom form's setupUi() must be called on this object before using this method. Once setupUi() is done, mdtSqlFormWidget object (this) will contain a layout with all widgets (QLineEdit, QSpinBox, ...).
Model must be set with setModel() before using this method.
Definition at line 53 of file mdtSqlFormWidget.cpp.
References mdtAbstractSqlWidget::addDataValidator(), mdtAbstractSqlWidget::dataEdited(), mdtSqlSchemaTable::field(), MDT_ERROR_SET_SRC, mdtAbstractSqlWidget::model(), mdtAbstractSqlWidget::modelSelected(), mdtAbstractSqlWidget::rowCount(), mdtSqlFieldHandler::setDataWidget(), mdtSqlFieldHandler::setField(), mdtSqlSchemaTable::setupFromTable(), and mdtError::Warning.
Referenced by mapFormWidgets(), and mdtSqlForm::setMainTable().
void mdtSqlFormWidget::mapFormWidgets (const QString & firstWidgetInTabOrder = QString())
Map widgets to matching database fields.
Same than mapFormWidgets(QWidget *widget, const QString &firstWidgetInTabOrder) , but acts on this
Definition at line 138 of file mdtSqlFormWidget.cpp.
References mapFormWidgets().
QWidgetList mdtSqlFormWidget::mappedWidgets () const
Get a list of mapped widgets.
Note: the list is built at each call of this method.
Definition at line 143 of file mdtSqlFormWidget.cpp.
References mdtSqlFieldHandler::dataWidget().
void mdtSqlFormWidget::setCurrentIndex (int row) slot
Set row as current record.
Definition at line 251 of file mdtSqlFormWidget.cpp.
References mdtAbstractSqlWidget::allDataAreSaved(), mdtAbstractSqlWidget::model(), and mdtAbstractSqlWidget::rowCount().
void mdtSqlFormWidget::toFirst () slot
Set first record as current record.
Definition at line 165 of file mdtSqlFormWidget.cpp.
References mdtAbstractSqlWidget::allDataAreSaved().
void mdtSqlFormWidget::toLast () slot
Set last record as current record.
Definition at line 182 of file mdtSqlFormWidget.cpp.
References mdtAbstractSqlWidget::allDataAreSaved(), mdtAbstractSqlWidget::model(), and mdtAbstractSqlWidget::rowCount().
void mdtSqlFormWidget::toNext () slot
Set next record as current record.
Definition at line 224 of file mdtSqlFormWidget.cpp.
References mdtAbstractSqlWidget::allDataAreSaved(), currentRow(), and mdtAbstractSqlWidget::model().
void mdtSqlFormWidget::toPrevious () slot
Set previous record as current record.
Definition at line 207 of file mdtSqlFormWidget.cpp.
References mdtAbstractSqlWidget::allDataAreSaved().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlFormWidget.h
src/mdtdatabase/mdtSqlFormWidget.cpp