Multi diag tools: mdtTtTestModelAbstractGeneratorHelper Class Reference
mdtTtTestModelAbstractGeneratorHelper Class Reference abstract
Helper class for test model generation.
#include <mdtTtTestModel.h>
Public Types
enum action_t { Fail, IgnoreCurrentItem }
Action.
Public Member Functions
mdtTtTestModelAbstractGeneratorHelper (mdtTtTestModel *tm)
Constructor.
virtual ~mdtTtTestModelAbstractGeneratorHelper ()
Destructor.
virtual QList< QVariant > relaysToIgnoreIdList ()
Get a list of test node unit ID of relays to not use.
virtual QList< QVariant > getRelatedTestConnectionIdList (const QVariant &testCableId, const QVariant &fromTestConnectionId, mdtClPathGraph &graph, bool &ok)=0
Get related connections.
virtual bool queueRelatedConnectionToSolved ()=0
Tell if a related test connection must be queued to solved connections once processed.
virtual action_t actionOnShortInTestNode ()=0
Tell what to do if a setup is about to produce a short circuit in test node.
virtual QVariant expectedValue ()=0
Get expected value (type double or Null)
virtual QVariant valueUnit ()=0
Get value unit.
virtual QVariant getDesignationEN (const QVariant &fromTestLinkId, const QVariant &toTestLinkId)
Get a string for the test model item's designation.
QVariant getDutConnectionId (const QVariant &testCableId, const QVariant &testConnectionId, bool &ok)
Get DUT connection ID for given test connection ID.
QVariant getTestConnectionId (const QVariant &testCableId, const QVariant &dutConnectionId, bool &ok, const QVariant &testConnectionToExclude=QVariant())
Get test connection ID for given DUT connection ID.
mdtError lastError () const
Get last error.
Protected Attributes
mdtTtTestModel * pvTestModel
mdtError pvLastError
Detailed Description
Helper class for test model generation.
Definition at line 36 of file mdtTtTestModel.h.
Member Enumeration Documentation
enum mdtTtTestModelAbstractGeneratorHelper::action_t
Action.
Enumerator
Fail
Fail test model generation
IgnoreCurrentItem
Do not add a item, continue processing
Definition at line 42 of file mdtTtTestModel.h.
Constructor & Destructor Documentation
mdtTtTestModelAbstractGeneratorHelper::mdtTtTestModelAbstractGeneratorHelper (mdtTtTestModel * tm) inline
Constructor.
Definition at line 49 of file mdtTtTestModel.h.
References pvTestModel.
virtual mdtTtTestModelAbstractGeneratorHelper::~mdtTtTestModelAbstractGeneratorHelper () inline virtual
Destructor.
Definition at line 57 of file mdtTtTestModel.h.
Member Function Documentation
virtual action_t mdtTtTestModelAbstractGeneratorHelper::actionOnShortInTestNode () pure virtual
Tell what to do if a setup is about to produce a short circuit in test node.
Implemented in mdtTtTestModelIsolationTestGeneratorHelper, and mdtTtTestModelContinuityTestGeneratorHelper.
Referenced by mdtTtTestModel::generateTestModel().
virtual QVariant mdtTtTestModelAbstractGeneratorHelper::expectedValue () pure virtual
Get expected value (type double or Null)
Implemented in mdtTtTestModelIsolationTestGeneratorHelper, and mdtTtTestModelContinuityTestGeneratorHelper.
Referenced by mdtTtTestModel::generateTestModel().
QVariant mdtTtTestModelAbstractGeneratorHelper::getDesignationEN (const QVariant & fromTestLinkId, const QVariant & toTestLinkId) virtual
Get a string for the test model item's designation.
Definition at line 69 of file mdtTtTestModel.cpp.
References mdtTtBase::getDataList(), and pvTestModel.
Referenced by mdtTtTestModel::generateTestModel().
QVariant mdtTtTestModelAbstractGeneratorHelper::getDutConnectionId (const QVariant & testCableId, const QVariant & testConnectionId, bool & ok)
Get DUT connection ID for given test connection ID.
Definition at line 138 of file mdtTtTestModel.cpp.
References mdtTtBase::getDataList(), and pvTestModel.
Referenced by mdtTtTestModelContinuityTestGeneratorHelper::getRelatedTestConnectionIdList(), and mdtTtTestModelIsolationTestGeneratorHelper::getRelatedTestConnectionIdList().
virtual QList<QVariant> mdtTtTestModelAbstractGeneratorHelper::getRelatedTestConnectionIdList (const QVariant & testCableId, const QVariant & fromTestConnectionId, mdtClPathGraph & graph, bool & ok) pure virtual
Get related connections.
What rRelated connections are depends on implementation. For example, for a continuity check generator, they will be linked connections.
Implemented in mdtTtTestModelIsolationTestGeneratorHelper, and mdtTtTestModelContinuityTestGeneratorHelper.
Referenced by mdtTtTestModel::generateTestModel().
QVariant mdtTtTestModelAbstractGeneratorHelper::getTestConnectionId (const QVariant & testCableId, const QVariant & dutConnectionId, bool & ok, const QVariant & testConnectionToExclude = QVariant())
Get test connection ID for given DUT connection ID.
Definition at line 158 of file mdtTtTestModel.cpp.
References mdtTtBase::getDataList(), and pvTestModel.
Referenced by mdtTtTestModelContinuityTestGeneratorHelper::getRelatedTestConnectionIdList().
mdtError mdtTtTestModelAbstractGeneratorHelper::lastError () const inline
Get last error.
Definition at line 101 of file mdtTtTestModel.h.
References pvLastError.
Referenced by mdtTtTestModel::generateTestModel().
virtual bool mdtTtTestModelAbstractGeneratorHelper::queueRelatedConnectionToSolved () pure virtual
Tell if a related test connection must be queued to solved connections once processed.
Implemented in mdtTtTestModelIsolationTestGeneratorHelper, and mdtTtTestModelContinuityTestGeneratorHelper.
Referenced by mdtTtTestModel::generateTestModel().
QList< QVariant > mdtTtTestModelAbstractGeneratorHelper::relaysToIgnoreIdList () virtual
Get a list of test node unit ID of relays to not use.
Reimplemented in mdtTtTestModelIsolationTestGeneratorHelper.
Definition at line 63 of file mdtTtTestModel.cpp.
Referenced by mdtTtTestModel::generateTestModel().
virtual QVariant mdtTtTestModelAbstractGeneratorHelper::valueUnit () pure virtual
Get value unit.
Implemented in mdtTtTestModelIsolationTestGeneratorHelper, and mdtTtTestModelContinuityTestGeneratorHelper.
Referenced by mdtTtTestModel::generateTestModel().
Member Data Documentation
mdtError mdtTtTestModelAbstractGeneratorHelper::pvLastError protected
Definition at line 108 of file mdtTtTestModel.h.
Referenced by mdtTtTestModelContinuityTestGeneratorHelper::getRelatedTestConnectionIdList(), mdtTtTestModelIsolationTestGeneratorHelper::getRelatedTestConnectionIdList(), and lastError().
mdtTtTestModel* mdtTtTestModelAbstractGeneratorHelper::pvTestModel protected
Definition at line 107 of file mdtTtTestModel.h.
Referenced by getDesignationEN(), getDutConnectionId(), mdtTtTestModelContinuityTestGeneratorHelper::getRelatedTestConnectionIdList(), mdtTtTestModelIsolationTestGeneratorHelper::getRelatedTestConnectionIdList(), getTestConnectionId(), and mdtTtTestModelAbstractGeneratorHelper().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestModel.h
src/mdttools/mdttesttool/mdtTtTestModel.cpp