Multi diag tools: mdtDevice Class Reference
mdtDevice Class Reference
Base class for a device connected to a port.
#include <mdtDevice.h>
Public Slots
void setAnalogOutputValue (mdtAnalogIo *analogOutput)
Set value on a analog output on physical device.
void setDigitalOutputValue (mdtDigitalIo *digitalOutput)
Set value on a digital output on physical device.
void runQueries ()
Queries to send periodically.
Signals
void stateChanged (int state)
mdtDeviceIos *pvIos; // I/O's container
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
Public Member Functions
mdtDevice (QObject *parent=0)
Construct a device object.
virtual ~mdtDevice ()
Destructor.
void setName (const QString &name)
Set the device name.
QString name () const
Get device name.
void setIdentification (const QVariant &id)
Set device identification.
QVariant identification () const
Get device identification.
virtual mdtAbstractPort::error_t connectToDevice (const mdtDeviceInfo &devInfo)
Search and connect to physical device.
virtual void disconnectFromDevice ()
Disconnect from device.
void addInput (mdtAnalogIo *analogInput)
Add a analog input.
void addInputs (const QList< mdtAnalogIo * > &analogInputs)
Add a list of analog inputs.
void addOutput (mdtAnalogIo *analogOutput)
Add a analog output.
void addOutputs (const QList< mdtAnalogIo * > &analogOutputs)
Add a list of analog outputs.
void addInput (mdtDigitalIo *digitalInput)
Add a digital input.
void addInputs (const QList< mdtDigitalIo * > &digitalInputs)
Add a list of digital inputs.
void addOutput (mdtDigitalIo *digitalOutput)
Add a digital output.
void addOutputs (const QList< mdtDigitalIo * > &digitalOutputs)
Add a list of digital outputs.
void deleteIos ()
Delete all I/O in container.
mdtDeviceIos * ios ()
Get the I/Os container.
void setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
virtual mdtPortManager * portManager ()
Get internal port manager instance.
virtual bool isReady ()
Check if device is ready.
void start (int queryInterval)
Start periodic device querying.
void stop ()
Stop periodic device querying.
void wait (int ms)
Wait some time.
mdtError lastError () const
Get last error.
mdtValue getAnalogInputValue (mdtAnalogIo *analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (int address, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogInputs (bool waitOnReply)
Read all analog inputs on physical device and update (G)UI representation.
mdtValue getAnalogOutputValue (mdtAnalogIo *analogOutput, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogOutputs (bool waitOnReply)
Read all analog outputs on physical device and update (G)UI representation.
int setAnalogOutputValue (mdtAnalogIo *analogOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
int setAnalogOutputs (bool waitOnReply)
Write all analog outputs on physical device and update (G)UI representation.
mdtValue getDigitalInputValue (mdtDigitalIo *digitalInput, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (int address, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalInputs (bool waitOnReply)
Read all digital inputs on physical device and update (G)UI representation.
mdtValue getDigitalOutputValue (mdtDigitalIo *digitalOutput, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalOutputs (bool waitOnReply)
Read all digital outputs on physical device and update (G)UI representation.
int setDigitalOutputValue (mdtDigitalIo *digitalOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a digital output value.
int setDigitalOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputsValue (const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a value and validity for all digital outputs.
int setDigitalOutputs (bool waitOnReply)
Write all digital outputs to physical device and update (G)UI representation.
mdtPortManager::state_t currentState ()
Get device state.
Protected Slots
virtual void decodeReadenFrame (mdtPortTransaction *transaction)
Decode incoming frames.
Protected Member Functions
mdtError & lastErrorW ()
Get last error for write access.
virtual int readAnalogInput (mdtPortTransaction *transaction)
Read one analog input on physical device.
virtual int readAnalogInputs (mdtPortTransaction *transaction)
Read all analog inputs on physical device.
virtual int readAnalogOutput (mdtPortTransaction *transaction)
Read one analog output on physical device.
virtual int readAnalogOutputs (mdtPortTransaction *transaction)
Read all analog outputs on physical device.
virtual int writeAnalogOutput (int value, mdtPortTransaction *transaction)
Write value on a analog output to physical device.
virtual int writeAnalogOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all analog outputs to physical device.
virtual int readDigitalInput (mdtPortTransaction *transaction)
Read one digital input on physical device.
virtual int readDigitalInputs (mdtPortTransaction *transaction)
Read all digital inputs on physical device.
virtual int readDigitalOutput (mdtPortTransaction *transaction)
Read one digital output on physical device.
virtual int readDigitalOutputs (mdtPortTransaction *transaction)
Read all digital outputs on physical device.
virtual int writeDigitalOutput (bool state, mdtPortTransaction *transaction)
Write state on a digital output to physical device.
virtual int writeDigitalOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all digital outputs to physical device.
virtual bool queriesSequence ()
Sequence of queries to send periodically.
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
bool waitTransactionDone (int id)
Wait until a transaction is done without break the GUI's event loop.
Protected Attributes
mdtError pvLastError
Last error object.
Detailed Description
Base class for a device connected to a port.
Querying a device can be done several ways. Some devices sends a confirmation after each query.
Some queries (f.ex. read a input value or state) give a result after query. In some applications, we need to display the reult priodically. In other application, we need to send the query and wait on result before we can continue. This base class gives a interface for these two cases.
At basis, all query methods are not blocking by default. The normal way is to connect mdtPortManager::newTransactionDone() to decodeReadenFrame() slot (must be done in subclass). This way, a query will be sent to device and method returns. When device returns a result, mdtPortManager will send the newTransactionDone() signal, and decoding will be processed in decodeReadenFrame() and I/O's are updated.
Because the blocking behaviour is sometimes needed, the concept of transaction was implemented in mdtPortManager. At first, we tell the query method (for example getAnalogInputValue()) that we will wait on a reply by setting the waitOnReply flag. Then, the query is sent to device and a transaction ID is added to a list (see mdtPortManager for details). At next, waitTransactionDone() is called, and finally result is returned. Note that waitTransactionDone() will not breack the Qt's event loop because it uses the mdtPortManager::wait() method (see documentation of mdtPortManager for details).
If it is needed to continiusly update the representation of device's inputs (digital/analog I/O, voltage, temperature, ...), two things can happen:
1) Used port can receive data continiusly (f.ex. RS232) and device send data automatically
2) Used port need that a request is sent for each read (TCP, USB, ...) or device need such request Continous update is typical usefull for a GUI representing a real device.
A other usage is automated sequence. In this case, the sequence will tell when it need to set a output and when a input value is reuqierd.
A device can accept one or many request before results must be read. This depends most case on used port and protocol.
It can be useful to find on witch port a device is attached (f.ex. setup of a automated test application). For this, connectToDevice() was introduced.
A device can have several states (ready, busy, disconnected, ...). To help the application programmer to keep consistency, this states are updated in this class using mdtPortManager 's state machine. This state machine is based on QStateMachine.
Notes about I/O container: In first version of mdtDevice, I/O container (mdtDeviceIos object) was handled by caller. Experience showed that this was a bad solution. Now, the container is created, and destroyed, bay mdtDevice itself. To deal with I/O container, some methods are available:
addInput(mdtAnalogIo *) : add a analog input.
addInputs(QList<mdtAnalogIo*> &) : add a list of analog inputs.
addOutput(mdtAnalogIo *) : add a analog output.
addOutputs(QList<mdtAnalogIo*> &) : add a list of analog outputs.
addInput(mdtDigitalIo *) : add a digital input.
addInputs(QList<mdtDigitalIo*> &) : add a list of digital inputs.
addOutput(mdtDigitalIo *) : add a digital output.
addOutputs(QList<mdtDigitalIo*> &) : add a list of digital outputs.
ios() : access I/O container.
deleteIos() : delete all I/O in container.
Definition at line 108 of file mdtDevice.h.
Constructor & Destructor Documentation
mdtDevice::mdtDevice (QObject * parent = 0)
Construct a device object.
Definition at line 29 of file mdtDevice.cpp.
References runQueries(), and setName().
mdtDevice::~mdtDevice () virtual
Destructor.
Will disconnect from device and delete I/O container.
Definition at line 48 of file mdtDevice.cpp.
References disconnectFromDevice().
Member Function Documentation
void mdtDevice::addInput (mdtAnalogIo * analogInput)
Add a analog input.
Definition at line 85 of file mdtDevice.cpp.
References mdtDeviceIos::addAnalogInput().
Referenced by mdtDeviceU3606A::mdtDeviceU3606A().
void mdtDevice::addInput (mdtDigitalIo * digitalInput)
Add a digital input.
Definition at line 122 of file mdtDevice.cpp.
References mdtDeviceIos::addDigitalInput().
void mdtDevice::addInputs (const QList< mdtAnalogIo * > & analogInputs)
Add a list of analog inputs.
Definition at line 93 of file mdtDevice.cpp.
References mdtDeviceIos::addAnalogInputs().
Referenced by mdtDeviceModbusWago::detectIos().
void mdtDevice::addInputs (const QList< mdtDigitalIo * > & digitalInputs)
Add a list of digital inputs.
Definition at line 130 of file mdtDevice.cpp.
References mdtDeviceIos::addDigitalInputs().
void mdtDevice::addOutput (mdtAnalogIo * analogOutput)
Add a analog output.
Definition at line 100 of file mdtDevice.cpp.
References mdtDeviceIos::addAnalogOutput(), and setAnalogOutputValue().
Referenced by mdtDeviceU3606A::mdtDeviceU3606A().
void mdtDevice::addOutput (mdtDigitalIo * digitalOutput)
Add a digital output.
Definition at line 137 of file mdtDevice.cpp.
References mdtDeviceIos::addDigitalOutput(), and setDigitalOutputValue().
void mdtDevice::addOutputs (const QList< mdtAnalogIo * > & analogOutputs)
Add a list of analog outputs.
Definition at line 109 of file mdtDevice.cpp.
References mdtDeviceIos::addAnalogOutputs(), and setAnalogOutputValue().
Referenced by mdtDeviceModbusWago::detectIos().
void mdtDevice::addOutputs (const QList< mdtDigitalIo * > & digitalOutputs)
Add a list of digital outputs.
Definition at line 146 of file mdtDevice.cpp.
References mdtDeviceIos::addDigitalOutputs(), and setDigitalOutputValue().
mdtAbstractPort::error_t mdtDevice::connectToDevice (const mdtDeviceInfo & devInfo) virtual
Search and connect to physical device.
Will scan available ports and open the first port that has device attached matching request.
Parameters
devInfo Requested device's informations.
Returns
A error listed in mdtAbstractPort::error_t (NoError on success)
Note: default implementation does nothing and returns allways a UnhandledError. See subclass documentation for more details.
Reimplemented in mdtDeviceModbus, mdtDeviceU3606A, mdtDeviceScpi, mdtDeviceModbusWago, and mdtDeviceDSO1000A.
Definition at line 70 of file mdtDevice.cpp.
References mdtAbstractPort::UnhandledError.
mdtPortManager::state_t mdtDevice::currentState ()
Get device state.
Definition at line 1170 of file mdtDevice.cpp.
References mdtPortManager::currentState(), mdtPortManager::PortClosed, and portManager().
Referenced by runQueries(), setAnalogOutputValue(), and setDigitalOutputValue().
void mdtDevice::decodeReadenFrame (mdtPortTransaction * transaction) protected virtual slot
Decode incoming frames.
Subclass notes:
This default implementation does nothing.
This slot should be connected with mdtPortManager::newTransactionDone(mdtPortTransaction*) signal.
In this class, this connection is not made, it is the sublcass responsability to do this.
Once decoding was done, the concerned I/O(s) sould be updated with new value, or set to invalid value on error (see mdtValue class). Doing so will keep (G)UI consistency.
Definition at line 1213 of file mdtDevice.cpp.
void mdtDevice::deleteIos ()
Delete all I/O in container.
All I/O's will be deleted, but I/O container itself will remain valid.
Definition at line 159 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputs(), mdtDeviceIos::deleteIos(), mdtDeviceIos::digitalOutputs(), setAnalogOutputValue(), and setDigitalOutputValue().
Referenced by mdtDeviceModbusWago::detectIos().
void mdtDevice::disconnectFromDevice () virtual
Disconnect from device.
Will stop periodic querying (see stop()), and stop internal port manager (if set).
If specific work must be done, subclass can re-implement this method.
Note: in the implementation, ios are keeped as they are.
Definition at line 75 of file mdtDevice.cpp.
References portManager(), stop(), and mdtPortManager::stop().
Referenced by ~mdtDevice().
int mdtDevice::getAnalogInputs (bool waitOnReply)
Read all analog inputs on physical device and update (G)UI representation.
Will call readAnalogInputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogInputs() for details).
Once results are available or error occured, the internal analog inputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout or other error, a value < 0 is returned.
Definition at line 339 of file mdtDevice.cpp.
References mdtDeviceIos::analogInputsCount(), mdtDeviceIos::analogInputsSegments(), getNewTransaction(), mdtDeviceIosSegment::ioCount(), readAnalogInputs(), mdtPortTransaction::setAddress(), mdtDeviceIos::setAnalogInputsValue(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
Referenced by mdtDeviceModbus::queriesSequence().
mdtDevice::getAnalogInputValue (mdtAnalogIo * analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
Get device or internal analog value. Internal value is updated if queryDevice is set.
Parameters
analogInput Pointer to a analog input object.
queryDevice If true, value is readen from device by calling readAnalogInput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogInput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
A mdtValue with valueDouble as real value and valueInt as device specific encoded fromat (if available). See mdtValue documentation for details about validity and other flags.
Precondition
analogInput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtAnalogIo for details).
Definition at line 232 of file mdtDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readAnalogInput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtAnalogIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getAnalogInputValue(), getAnalogInputValueAt(), and mdtDeviceU3606A::getMeasureValue().
mdtValue mdtDevice::getAnalogInputValue (int address, bool queryDevice, bool waitOnReply)
Get analog input value.
Parameters
address Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a input number, etc...
See Also
getAnalogInputValue(mdtAnalogIo*, bool, bool)
Definition at line 274 of file mdtDevice.cpp.
References mdtDeviceIos::analogInputAtAddress(), mdtError::commit(), mdtError::Error, getAnalogInputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getAnalogInputValue (const QString & labelShort, bool queryDevice, bool waitOnReply)
Definition at line 319 of file mdtDevice.cpp.
References mdtDeviceIos::analogInputWithLabelShort(), mdtError::commit(), mdtError::Error, getAnalogInputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog input value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getAnalogInputValue(mdtAnalogIo*, bool, bool)
Definition at line 293 of file mdtDevice.cpp.
References mdtDeviceIos::analogInputs(), mdtError::commit(), mdtError::Error, getAnalogInputValue(), MDT_ERROR_SET_SRC, name(), pvLastError, and mdtError::setError().
int mdtDevice::getAnalogOutputs (bool waitOnReply)
Read all analog outputs on physical device and update (G)UI representation.
Will call readAnalogOutputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogOutputs() for details).
Once results are available or error occured, the internal analog outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout or other error, a value < 0 is returned.
Definition at line 491 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputsCount(), mdtDeviceIos::analogOutputsSegments(), getNewTransaction(), mdtDeviceIosSegment::ioCount(), readAnalogOutputs(), mdtPortTransaction::setAddress(), mdtDeviceIos::setAnalogOutputsValue(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
mdtDevice::getAnalogOutputValue (mdtAnalogIo * analogOutput, bool queryDevice, bool waitOnReply)
Get analog output value.
Get device or internal analog value. Internal value is updated if queryDevice is set.
Parameters
analogOutput Pointer to a analog output object.
queryDevice If true, value is readen from device by calling readAnalogOutput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readAnalogOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
A mdtValue with valueDouble as real value and valueInt as device specific encoded fromat (if available). See mdtValue documentation for details about validity and other flags.
Precondition
analogOutput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtAnalogIo for details).
Definition at line 385 of file mdtDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readAnalogOutput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtAnalogIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getAnalogOutputValue(), and getAnalogOutputValueAt().
mdtValue mdtDevice::getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get analog output value.
Parameters
addressRead Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
getAnalogOutputValue(mdtAnalogIo*, bool, bool)
Definition at line 427 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputAtAddressRead(), mdtError::commit(), mdtError::Error, getAnalogOutputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getAnalogOutputValue (const QString & labelShort, bool queryDevice, bool waitOnReply)
Definition at line 472 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputWithLabelShort(), mdtError::commit(), mdtError::Error, getAnalogOutputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getAnalogOutputValue(mdtAnalogIo*, bool, bool)
Definition at line 446 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputs(), mdtError::commit(), mdtError::Error, getAnalogOutputValue(), MDT_ERROR_SET_SRC, name(), pvLastError, and mdtError::setError().
int mdtDevice::getDigitalInputs (bool waitOnReply)
Read all digital inputs on physical device and update (G)UI representation.
Will call readDigitalInputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalInputs() for details).
Once results are available, the internal digital inputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout ar other error, a value < 0 is returned.
Definition at line 798 of file mdtDevice.cpp.
References mdtDeviceIos::digitalInputsCount(), mdtDeviceIos::digitalInputsSegments(), getNewTransaction(), mdtDeviceIosSegment::ioCount(), readDigitalInputs(), mdtPortTransaction::setAddress(), mdtDeviceIos::setDigitalInputsValue(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
Referenced by mdtDeviceModbus::queriesSequence().
mdtDevice::getDigitalInputValue (mdtDigitalIo * digitalInput, bool queryDevice, bool waitOnReply)
Get digital input value.
Get device or internal digital value. Internal value is updated if queryDevice is set.
Parameters
digitalInput Pointer to a digital input.
queryDevice If true, value is readen from device by calling readDigitalInput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalInput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
A mdtValue with valueBool. See mdtValue documentation for details about validity and other flags.
Precondition
digitalInput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtDigitalIo for details).
Definition at line 692 of file mdtDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readDigitalInput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtDigitalIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getDigitalInputValue(), and getDigitalInputValueAt().
mdtValue mdtDevice::getDigitalInputValue (int address, bool queryDevice, bool waitOnReply)
Get digital input value.
Parameters
address Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a input number, etc...
See Also
getDigitalInputValue(mdtDigitalIo*, bool, bool)
Definition at line 734 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalInputAtAddress(), mdtError::Error, getDigitalInputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getDigitalInputValue (const QString & labelShort, bool queryDevice, bool waitOnReply)
Definition at line 779 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalInputWithLabelShort(), mdtError::Error, getDigitalInputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital input value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getDigitalInputValue(mdtDigitalIo*, bool, bool)
Definition at line 753 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalInputs(), mdtError::Error, getDigitalInputValue(), MDT_ERROR_SET_SRC, name(), pvLastError, and mdtError::setError().
int mdtDevice::getDigitalOutputs (bool waitOnReply)
Read all digital outputs on physical device and update (G)UI representation.
Will call readDigitalOutputs(), witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalOutputs() for details).
Once results are available, the internal digital outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout ar other error, a value < 0 is returned.
Definition at line 951 of file mdtDevice.cpp.
References mdtDeviceIos::digitalOutputsCount(), mdtDeviceIos::digitalOutputsSegments(), getNewTransaction(), mdtDeviceIosSegment::ioCount(), readDigitalOutputs(), mdtPortTransaction::setAddress(), mdtDeviceIos::setDigitalOutputsValue(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressRead(), and waitTransactionDone().
mdtDevice::getDigitalOutputValue (mdtDigitalIo * digitalOutput, bool queryDevice, bool waitOnReply)
Get digital output value.
Parameters
digitalOutput Pointer to a digital output.
queryDevice If true, value is readen from device by calling readDigitalOutput(), else cached value is returned. Behaviour of this method can vary, depending on device specific subclass. (See sublcass readDigitalOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
A mdtValue with valueBool. See mdtValue documentation for details about validity and other flags.
Precondition
digitalOutput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtDigitalIo for details).
Definition at line 845 of file mdtDevice.cpp.
References mdtAbstractIo::addressRead(), getNewTransaction(), readDigitalOutput(), mdtPortTransaction::setAddress(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtDigitalIo::setValue(), mdtAbstractIo::value(), and waitTransactionDone().
Referenced by getDigitalOutputValue(), and getDigitalOutputValueAt().
mdtValue mdtDevice::getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get digital output value.
Parameters
addressRead Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
getDigitalOutputValue(mdtDigitalIo*, bool, bool)
Definition at line 887 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalOutputAtAddressRead(), mdtError::Error, getDigitalOutputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getDigitalOutputValue (const QString & labelShort, bool queryDevice, bool waitOnReply)
Definition at line 932 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalOutputWithLabelShort(), mdtError::Error, getDigitalOutputValue(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and name().
mdtValue mdtDevice::getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
getDigitalOutputValue(mdtDigitalIo*, bool, bool)
Definition at line 906 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalOutputs(), mdtError::Error, getDigitalOutputValue(), MDT_ERROR_SET_SRC, name(), pvLastError, and mdtError::setError().
mdtPortTransaction * mdtDevice::getNewTransaction () protected
Get a new transaction.
See Also
mdtPortManager::getNewTransaction()
Precondition
portManager must be set before calling this method
Definition at line 1283 of file mdtDevice.cpp.
References mdtPortManager::getNewTransaction(), and portManager().
Referenced by mdtDeviceScpi::checkDeviceError(), getAnalogInputs(), getAnalogInputValue(), getAnalogOutputs(), getAnalogOutputValue(), getDigitalInputs(), getDigitalInputValue(), getDigitalOutputs(), getDigitalOutputValue(), mdtDeviceU3606A::getMeasureConfiguration(), setAnalogOutputs(), setAnalogOutputValue(), setDigitalOutputs(), and setDigitalOutputValue().
QVariant mdtDevice::identification () const inline
Get device identification.
Definition at line 139 of file mdtDevice.h.
mdtDeviceIos * mdtDevice::ios ()
Get the I/Os container.
Note: once this mdtDevice object was destroyed, the I/O container is deleted.
Postcondition
During the lifetime of this mdtDevice object, a valid pointer will be returned.
Definition at line 180 of file mdtDevice.cpp.
Referenced by mdtDeviceModbusWago::detectIos(), mdtDeviceModbus::readAnalogInput(), mdtDeviceModbus::readAnalogInputs(), mdtDeviceModbus::readAnalogOutput(), mdtDeviceModbus::readAnalogOutputs(), mdtDeviceModbus::readDigitalInput(), mdtDeviceModbus::readDigitalInputs(), mdtDeviceModbus::readDigitalOutput(), mdtDeviceModbus::readDigitalOutputs(), mdtDeviceModbus::writeAnalogOutput(), mdtDeviceModbus::writeAnalogOutputs(), mdtDeviceModbus::writeDigitalOutput(), and mdtDeviceModbus::writeDigitalOutputs().
bool mdtDevice::isReady () virtual
Check if device is ready.
This default implementation calls mdtPortManager::isReady() , or returns false if portManager was not set.
Note: isReady() should return true only if device it ready for querying.
Definition at line 197 of file mdtDevice.cpp.
References mdtPortManager::isReady(), and portManager().
Referenced by start(), and mdtDeviceScpi::waitOperationComplete().
mdtError mdtDevice::lastError () const
Get last error.
Todo:
Not completly used currently, must be implemented in this class + subclasses .
Definition at line 227 of file mdtDevice.cpp.
References pvLastError.
mdtError & mdtDevice::lastErrorW () protected
Get last error for write access.
Deprecated:
Use pvLastError directly.
Definition at line 1217 of file mdtDevice.cpp.
References pvLastError.
Referenced by mdtDeviceModbus::connectToDevice().
QString mdtDevice::name () const
Get device name.
Definition at line 60 of file mdtDevice.cpp.
Referenced by mdtDeviceModbusWago::detectIos(), mdtDeviceModbusWagoModule::deviceName(), getAnalogInputValue(), getAnalogInputValueAt(), getAnalogOutputValue(), getAnalogOutputValueAt(), getDigitalInputValue(), getDigitalInputValueAt(), getDigitalOutputValue(), getDigitalOutputValueAt(), mdtDeviceScpi::handleDeviceError(), mdtDeviceModbusWago::isWago750(), mdtDeviceScpi::logDeviceError(), mdtDeviceModbusWagoModule::readRegisters(), mdtDeviceModbusWagoModule::readStatusBytes(), setAnalogOutputValue(), setAnalogOutputValueAt(), setDigitalOutputValue(), setDigitalOutputValueAt(), setName(), mdtDeviceU3606A::setupResistanceMeasure(), mdtDeviceModbusWagoModule::writeControlBytes(), and mdtDeviceModbusWagoModule::writeRegisters().
mdtPortManager * mdtDevice::portManager () virtual
Get internal port manager instance.
Note that port manager is set by subclass, and that a Null pointer can be returned. (See subclass documentation for details)
Reimplemented in mdtDeviceScpi, and mdtDeviceModbus.
Definition at line 192 of file mdtDevice.cpp.
Referenced by currentState(), disconnectFromDevice(), getNewTransaction(), isReady(), restoreTransaction(), mdtDeviceWindow::setDevice(), wait(), and waitTransactionDone().
bool mdtDevice::queriesSequence () protected virtual
Sequence of queries to send periodically.
This method is called from runQueries().
Returns
true if all queries are sent successfully.
Subclass notes:
This default implementation does nothing and allways returns false.
This method can be reimplemented periodic queries must be sent to device.
Reimplemented in mdtDeviceModbus.
Definition at line 1208 of file mdtDevice.cpp.
Referenced by runQueries().
int mdtDevice::readAnalogInput (mdtPortTransaction * transaction) protected virtual
Read one analog input on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogInputValue() .
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details).
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1222 of file mdtDevice.cpp.
Referenced by getAnalogInputValue().
int mdtDevice::readAnalogInputs (mdtPortTransaction * transaction) protected virtual
Read all analog inputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogInputs() .
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1227 of file mdtDevice.cpp.
Referenced by getAnalogInputs().
int mdtDevice::readAnalogOutput (mdtPortTransaction * transaction) protected virtual
Read one analog output on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogOutputValue().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1232 of file mdtDevice.cpp.
Referenced by getAnalogOutputValue().
int mdtDevice::readAnalogOutputs (mdtPortTransaction * transaction) protected virtual
Read all analog outputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog inputs, this method should be implemented.
This method is called from getAnalogOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address (for read access) to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1237 of file mdtDevice.cpp.
Referenced by getAnalogOutputs().
int mdtDevice::readDigitalInput (mdtPortTransaction * transaction) protected virtual
Read one digital input on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital inputs, this method should be implemented.
This method is called from getDigitalInputValue().
Parameters
transaction Contains:
digitalIo object
QueryReplyMode flag
address
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1252 of file mdtDevice.cpp.
Referenced by getDigitalInputValue().
int mdtDevice::readDigitalInputs (mdtPortTransaction * transaction) protected virtual
Read all digital inputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital inputs, this method should be implemented.
This method is called from getDigitalInputs().
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1257 of file mdtDevice.cpp.
Referenced by getDigitalInputs().
int mdtDevice::readDigitalOutput (mdtPortTransaction * transaction) protected virtual
Read one digital output on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from getDigitalOutputValue().
Parameters
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1262 of file mdtDevice.cpp.
Referenced by getDigitalOutputValue().
int mdtDevice::readDigitalOutputs (mdtPortTransaction * transaction) protected virtual
Read all digital outputs on physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from getDigitalOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to get
address : first I/O address (for read access) to considere
QueryReplyMode flag
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1267 of file mdtDevice.cpp.
Referenced by getDigitalOutputs().
void mdtDevice::restoreTransaction (mdtPortTransaction * transaction) protected
Restore a transaction into pool.
See Also
mdtPortManager::restoreTransaction()
Precondition
portManager must be set before calling this method
Definition at line 1290 of file mdtDevice.cpp.
References portManager(), and mdtPortManager::restoreTransaction().
void mdtDevice::runQueries () slot
Queries to send periodically.
This slot is periodically called after a call of start().
Definition at line 1200 of file mdtDevice.cpp.
References currentState(), queriesSequence(), and mdtPortManager::Ready.
Referenced by mdtDevice().
int mdtDevice::setAnalogOutputs (bool waitOnReply)
Write all analog outputs on physical device and update (G)UI representation.
To send the analog outputs values once, it's possible to set them without sending query. See mdtDeviceIos and mdtAnalogIo for details. Then, call this method to sent all analog outputs values to device.
writeAnalogOutputs() will be called, witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeAnalogOutputs() for details).
Once results are available or on error, the internal analog outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout ar other error, a value < 0 is returned.
Definition at line 644 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputsCount(), mdtDeviceIos::analogOutputsSegments(), getNewTransaction(), mdtDeviceIosSegment::ioCount(), mdtPortTransaction::setAddress(), mdtDeviceIos::setAnalogOutputsEnabled(), mdtDeviceIos::setAnalogOutputsValue(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressWrite(), waitTransactionDone(), and writeAnalogOutputs().
mdtDevice::setAnalogOutputValue (mdtAnalogIo * analogOutput, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set analog output value.
Set device or internal analog value. Internal value is updated if queryDevice is set.
Parameters
analogOutput Pointer to a analog output object.
value Value to send/store.
sendToDevice If true, value is sent device by calling writeAnalogOutput(), else value is only cached. Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeAnalogOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout, on invalid value or other error, a value < 0 is returned.
Precondition
analogOutput must be valid.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
labelShort Short label set in I/O (see mdtAnalogIo for details).
Definition at line 537 of file mdtDevice.cpp.
References mdtAbstractIo::addressWrite(), getNewTransaction(), mdtPortTransaction::setAddress(), mdtAbstractIo::setEnabled(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtAnalogIo::setValue(), mdtAbstractIo::value(), mdtValue::valueInt(), waitTransactionDone(), and writeAnalogOutput().
Referenced by addOutput(), addOutputs(), deleteIos(), setAnalogOutputValue(), and setAnalogOutputValueAt().
int mdtDevice::setAnalogOutputValue (int addressWrite, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set analog output value.
Parameters
addressWrite Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
setAnalogOutputValue(mdtAnalogIo*, const mdtValue&, bool, bool)
Definition at line 580 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputAtAddressWrite(), mdtError::commit(), mdtError::Error, MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, name(), and setAnalogOutputValue().
int mdtDevice::setAnalogOutputValue (const QString & labelShort, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Definition at line 625 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputWithLabelShort(), mdtError::commit(), mdtError::Error, MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, name(), and setAnalogOutputValue().
void mdtDevice::setAnalogOutputValue (mdtAnalogIo * analogOutput) slot
Set value on a analog output on physical device.
Checks device's state and send request if Ready.
This slot is used by mdtDeviceIos to notify that a value has changed.
See setAnalogOutputValue(mdtAnalogIo*, const mdtValue&, bool, bool) for details.
Definition at line 1178 of file mdtDevice.cpp.
References currentState(), mdtPortManager::Ready, setAnalogOutputValue(), and mdtAbstractIo::value().
int mdtDevice::setAnalogOutputValueAt (int position, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set analog output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
setAnalogOutputValue(mdtAnalogIo*, const mdtValue&, bool, bool)
Definition at line 599 of file mdtDevice.cpp.
References mdtDeviceIos::analogOutputs(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, name(), pvLastError, setAnalogOutputValue(), and mdtError::setError().
void mdtDevice::setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
After some event (device disconnected, response timeout, ...) the state can be changed from Ready to another.
Note: if state is different than Ready, the slots setAnalogOutputValue(int) and setDigitalOutputState(int) will return immediately, without trying to send a request.
In some application, it can be usefull that state comes back automatically to ready.
Parameters
timeout Time before go back to ready state [ms] If timeout is < 0, device still in current state, and setStateReady() can be used.
Definition at line 187 of file mdtDevice.cpp.
Referenced by mdtDeviceModbus::mdtDeviceModbus(), and mdtDeviceScpi::mdtDeviceScpi().
int mdtDevice::setDigitalOutputs (bool waitOnReply)
Write all digital outputs to physical device and update (G)UI representation.
To send the digital outputs values once. It's possible to use setDigitalOutputValue() without sending the query to device, then using this method to commit all values once.
See mdtDeviceIos and mdtDigitalIo for details.
writeDigitalOutputs() will be called, witch also sends the request to device. Depending on result, device's state can be updated.
Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeDigitalOutputs() for details).
Once results are available, the internal digital outputs are updated. (See mdtDeviceIos for details).
Parameters
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout ar other error, a value < 0 is returned.
Definition at line 1122 of file mdtDevice.cpp.
References mdtDeviceIos::digitalOutputsCount(), mdtDeviceIos::digitalOutputsSegments(), getNewTransaction(), mdtDeviceIosSegment::ioCount(), mdtPortTransaction::setAddress(), mdtDeviceIos::setDigitalOutputsEnabled(), mdtDeviceIos::setDigitalOutputsValue(), mdtPortTransaction::setIoCount(), mdtPortTransaction::setQueryReplyMode(), mdtDeviceIosSegment::startAddressWrite(), waitTransactionDone(), and writeDigitalOutputs().
Referenced by setDigitalOutputsValue().
int mdtDevice::setDigitalOutputsValue (const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set a value and validity for all digital outputs.
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 1104 of file mdtDevice.cpp.
References mdtDeviceIos::digitalOutputsCount(), setDigitalOutputs(), and mdtDeviceIos::setDigitalOutputsValue().
int mdtDevice::setDigitalOutputValue (mdtDigitalIo * digitalOutput, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set a digital output value.
Set device or internal digital value. Depending on subclass implementation, if queryDevice is set, output can be updated regarding device response.
Parameters
digitalOutput Pointer to a digital output object.
value Value to send/store.
sendToDevice If true, value is sent to device by calling writeDigitalOutput(), else value is only cached. Behaviour of this method can vary, depending on device specific subclass. (See sublcass writeDigitalOutput() for details).
waitOnReply If true, this method will wait until reply comes in, or timeout (See waitTransactionDone()), else it will return immediately after the query was sent.
Returns
0 or a ID on success. If no I/O's are set, on timeout, on invalid value or other error, a value < 0 is returned.
Precondition
digitalOutput must be valid.
Definition at line 998 of file mdtDevice.cpp.
References mdtAbstractIo::addressWrite(), getNewTransaction(), mdtPortTransaction::setAddress(), mdtAbstractIo::setEnabled(), mdtPortTransaction::setIo(), mdtPortTransaction::setQueryReplyMode(), mdtDigitalIo::setValue(), mdtValue::valueBool(), waitTransactionDone(), and writeDigitalOutput().
Referenced by addOutput(), addOutputs(), deleteIos(), setDigitalOutputValue(), and setDigitalOutputValueAt().
int mdtDevice::setDigitalOutputValue (int addressWrite, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set digital output value.
Parameters
addressWrite Depending on device organisation and protocol, this can be a relative or absolute address (f.ex. MODBUS queries), a output number, etc...
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 1040 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalOutputAtAddressWrite(), mdtError::Error, MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, name(), and setDigitalOutputValue().
int mdtDevice::setDigitalOutputValue (const QString & labelShort, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set digital output value.
Parameters
labelShort Short label set in I/O (see mdtDigitalIo for details).
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 1085 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalOutputWithLabelShort(), mdtError::Error, MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, name(), and setDigitalOutputValue().
void mdtDevice::setDigitalOutputValue (mdtDigitalIo * digitalOutput) slot
Set value on a digital output on physical device.
Checks device's state and send request if Ready.
This slot is used by mdtDeviceIos to notify that a value has changed.
See setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool) for details.
Definition at line 1189 of file mdtDevice.cpp.
References currentState(), mdtPortManager::Ready, setDigitalOutputValue(), and mdtAbstractIo::value().
int mdtDevice::setDigitalOutputValueAt (int position, const mdtValue & value, bool sendToDevice, bool waitOnReply)
Set digital output value.
Parameters
position See the concept of position in mdtDeviceIos class detailed description .
See Also
setDigitalOutputValue(mdtDigitalIo*, const mdtValue&, bool, bool)
Definition at line 1059 of file mdtDevice.cpp.
References mdtError::commit(), mdtDeviceIos::digitalOutputs(), mdtError::Error, MDT_ERROR_SET_SRC, name(), pvLastError, setDigitalOutputValue(), and mdtError::setError().
void mdtDevice::setIdentification (const QVariant & id)
Set device identification.
Definition at line 65 of file mdtDevice.cpp.
void mdtDevice::setName (const QString & name)
Set the device name.
Definition at line 55 of file mdtDevice.cpp.
References name().
Referenced by mdtDevice(), and mdtModbusIoTool::mdtModbusIoTool().
void mdtDevice::start (int queryInterval)
Start periodic device querying.
Internally, the runQueries() slot will be called each queryInterval of time.
Note: if device is ready, querying starts immediatly, else it will start once device becomes ready.
See Also
isReady()
Parameters
queryInterval Query interval [ms]
Definition at line 205 of file mdtDevice.cpp.
References isReady().
Referenced by mdtDeviceScpi::connectToDevice(), and mdtModbusIoTool::mdtModbusIoTool().
void mdtDevice::stateChanged (int state) signal
mdtDeviceIos *pvIos; // I/O's container
Emitted when state has changed
See setStateFromPortManager() for some details.
This signal should be used by application developpers, and not directly mdtPortManager::stateChanged(). This is because some actions are made when entering new state, and stateChanged() is sent after.
But, to display current state in a easier way (f.ex. using mdtPortStatusWidget), mdtPortManager::stateChangedForUi() can be used.
Referenced by mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceModbus::mdtDeviceModbus(), and mdtDeviceScpi::mdtDeviceScpi().
void mdtDevice::statusMessageChanged (const QString & message, const QString & details, int timeout) signal
Emitted when a new status message is to display.
Typically used with mdtPortStatusWidget
Referenced by mdtDeviceModbus::mdtDeviceModbus().
void mdtDevice::stop ()
Stop periodic device querying.
Definition at line 214 of file mdtDevice.cpp.
Referenced by disconnectFromDevice(), and mdtDeviceScpi::~mdtDeviceScpi().
void mdtDevice::wait (int ms)
Wait some time.
See Also
mdtPortManager::wait()
Precondition
Port manager must be set before using this method
Definition at line 220 of file mdtDevice.cpp.
References portManager(), and mdtPortManager::wait().
Referenced by mdtDeviceModbusWagoModule::wait().
bool mdtDevice::waitTransactionDone (int id) protected
Wait until a transaction is done without break the GUI's event loop.
Todo:
Adapt, comment
This is a helper method that provide a blocking wait. Internally, a couple of sleep and event processing is done, avoiding freezing the GUI.
Internally, mdtPortManager::waitTransactionDone() is called.
Parameters
id Id returned by query method
Returns
True on success, false on timeout. If id was not found in transactions list, a warning will be generated in mdtError system, and false will be returned.
Precondition
granularity must be > 0.
Definition at line 1298 of file mdtDevice.cpp.
References portManager(), mdtPortManager::readenFrame(), and mdtPortManager::waitTransactionDone().
Referenced by getAnalogInputs(), getAnalogInputValue(), getAnalogOutputs(), getAnalogOutputValue(), getDigitalInputs(), getDigitalInputValue(), getDigitalOutputs(), getDigitalOutputValue(), mdtDeviceU3606A::getMeasureConfiguration(), setAnalogOutputs(), setAnalogOutputValue(), setDigitalOutputs(), and setDigitalOutputValue().
int mdtDevice::writeAnalogOutput (int value, mdtPortTransaction * transaction) protected virtual
Write value on a analog output to physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog outputs, this method should be implemented.
This method is called from setAnalogOutputValue().
Parameters
value Value encoded regarding device format.
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1242 of file mdtDevice.cpp.
Referenced by setAnalogOutputValue().
int mdtDevice::writeAnalogOutputs (mdtPortTransaction * transaction, mdtDeviceIosSegment * segment) protected virtual
Write all analog outputs to physical device.
This is the device specific implementation to send the query. If device handled by subclass has analog outputs, this method should be implemented.
This method is called from setAnalogOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to set
address : first I/O address (for write access) to considere
QueryReplyMode flag
segment Contains contiguous outputs to write.
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1247 of file mdtDevice.cpp.
Referenced by setAnalogOutputs().
int mdtDevice::writeDigitalOutput (bool state, mdtPortTransaction * transaction) protected virtual
Write state on a digital output to physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from setDigitalOutputState().
Parameters
state State (ON/OFF).
transaction Contains some flags used during query/reply process (address, id, I/O object, ...).
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1272 of file mdtDevice.cpp.
Referenced by setDigitalOutputValue().
int mdtDevice::writeDigitalOutputs (mdtPortTransaction * transaction, mdtDeviceIosSegment * segment) protected virtual
Write all digital outputs to physical device.
This is the device specific implementation to send the query. If device handled by subclass has digital outputs, this method should be implemented.
This method is called from setDigitalOutputs().
Parameters
transaction Contains:
ioCount : number of I/Os to set
address : first I/O address (for write access) to considere
QueryReplyMode flag
segment Contains contiguous outputs to write.
Returns
0 or a ID on success, value < 0 on error (see mdtPortManager::writeData() for details)
Precondition
I/O's must be set with setIos().
transaction must be a valid pointer.
Reimplemented in mdtDeviceModbus.
Definition at line 1277 of file mdtDevice.cpp.
Referenced by setDigitalOutputs().
Member Data Documentation
mdtError mdtDevice::pvLastError protected
Last error object.
Definition at line 707 of file mdtDevice.h.
Referenced by getAnalogInputValueAt(), getAnalogOutputValueAt(), getDigitalInputValueAt(), getDigitalOutputValueAt(), lastError(), lastErrorW(), setAnalogOutputValueAt(), setDigitalOutputValueAt(), and mdtDeviceU3606A::setupResistanceMeasure().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDevice.h
src/mdtdevice/mdtDevice.cpp