Multi diag tools: mdtDeviceAddressList Class Reference
mdtDeviceAddressList Class Reference
Device address list.
#include <mdtDeviceAddress.h>
Public Member Functions
mdtDeviceAddressList ()
Construct a empty device address list.
bool isEmpty () const
Check if device addresses list is empty.
int size () const
Get device addresses list size.
mdtError lastError () const
Get last error.
void clear ()
Clear.
void append (const mdtDeviceAddress &address)
Append a device address at the end of the list.
void append (const mdtDeviceAddressList &addressList)
Append a list of device addresses at the end of the list.
const std::vector
< mdtDeviceAddress > & internalVector () const
Access internal vector.
mdtDeviceAddress at (int index) const
Get device address at index.
bool saveToFile (const QString &filePath)
Save device address list to a file.
bool readFromFile (const QString &filePath)
Get device address list from a file.
Detailed Description
Device address list.
See Also
mdtDeviceAddress
Definition at line 400 of file mdtDeviceAddress.h.
Constructor & Destructor Documentation
mdtDeviceAddressList::mdtDeviceAddressList () inline
Construct a empty device address list.
Definition at line 406 of file mdtDeviceAddress.h.
Member Function Documentation
void mdtDeviceAddressList::append (const mdtDeviceAddress & address) inline
Append a device address at the end of the list.
Definition at line 440 of file mdtDeviceAddress.h.
Referenced by readFromFile(), and mdtModbusTcpPortManager::scan().
void mdtDeviceAddressList::append (const mdtDeviceAddressList & addressList) inline
Append a list of device addresses at the end of the list.
Definition at line 446 of file mdtDeviceAddress.h.
References internalVector().
mdtDeviceAddress mdtDeviceAddressList::at (int index) const inline
Get device address at index.
Precondition
index must be in valid range ([0,size-1])
Definition at line 473 of file mdtDeviceAddress.h.
References size().
void mdtDeviceAddressList::clear () inline
Clear.
Definition at line 433 of file mdtDeviceAddress.h.
const std::vector<mdtDeviceAddress>& mdtDeviceAddressList::internalVector () const inline
Access internal vector.
Can be used, for example, to iterate all addresses:
for(const auto & address : list.internalVector()){
  if(address.addressString() == "A::B::C"){
    doSomeStuff(address);
  }
}
Please take in accound that returned reference become invalid as soon as this mdtDeviceAddressList object is destroyed.
Definition at line 464 of file mdtDeviceAddress.h.
Referenced by append(), and mdtModbusTcpPortManager::scan().
bool mdtDeviceAddressList::isEmpty () const inline
Check if device addresses list is empty.
Definition at line 412 of file mdtDeviceAddress.h.
Referenced by mdtModbusTcpPortManager::scanFromKnownHostsFile().
mdtError mdtDeviceAddressList::lastError () const inline
Get last error.
Definition at line 426 of file mdtDeviceAddress.h.
Referenced by mdtModbusTcpPortManager::readDeviceAddressList(), and mdtModbusTcpPortManager::saveDeviceAddressList().
bool mdtDeviceAddressList::readFromFile (const QString & filePath)
Get device address list from a file.
Definition at line 276 of file mdtDeviceAddress.cpp.
References append(), mdtError::commit(), mdtError::Error, mdtDeviceAddress::lastError(), MDT_ERROR_SET_SRC, mdtDeviceAddress::setAddressString(), mdtDeviceAddress::setAlias(), and mdtError::setError().
Referenced by mdtModbusTcpPortManager::readDeviceAddressList().
bool mdtDeviceAddressList::saveToFile (const QString & filePath)
Save device address list to a file.
Note: if file given by filePath allready exits, it will be overwritten.
Definition at line 246 of file mdtDeviceAddress.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and mdtError::setError().
Referenced by mdtModbusTcpPortManager::saveDeviceAddressList().
int mdtDeviceAddressList::size () const inline
Get device addresses list size.
Definition at line 419 of file mdtDeviceAddress.h.
Referenced by at().
The documentation for this class was generated from the following files:
src/mdtport/mdtDeviceAddress.h
src/mdtport/mdtDeviceAddress.cpp