Multi diag tools: mdtDeviceModbusWagoModuleRtd Class Reference
mdtDeviceModbusWagoModuleRtd Class Reference
Helper class for RTD modules.
#include <mdtDeviceModbusWagoModuleRtd.h>
Public Types
enum psrrMode_t { Psrr50Hz, Psrr60Hz, Psrr5060Hz, PsrrUnknown }
PSRR mode.
enum sensorType_t {
Unknown, Pt100, Ni100, Pt1000,
Pt500, Pt200, Ni1000, Ni120,
Ni1000TK, Potentiometer, R10R5000, R10R1200
}
Sensor type.
enum processValueRepresentation_t { C2, AmountSign, C2S5, AmountSignS5 }
Process calue representation.
Public Types inherited from mdtDeviceModbusWagoModule
enum type_t {
Unknown, AnalogInputs, AnalogOutputs, DigitalInputs,
DigitalOutputs, DigitalInputsOutputs
}
Module type.
Public Member Functions
mdtDeviceModbusWagoModuleRtd (bool autoDeleteIos, mdtDeviceModbusWago *device)
Constructor.
~mdtDeviceModbusWagoModuleRtd ()
Destructor.
void setIoCount (int count)
Set the I/O count.
void setPsrrMode (psrrMode_t mode)
Set the PSRR mode.
psrrMode_t psrrMode () const
Get the PSRR mode.
void setSensorType (int channel, sensorType_t type)
Set the sensor type for given channel.
sensorType_t sensorType (int channel) const
Get the sensor type of given channel.
void setConnectionTypeWiresCount (int channel, int wiresCount)
int connectionTypeWiresCount (int channel) const
void setWatchdogTimerEnabled (int channel, bool enable)
bool watchdogTimerIsEnabled (int channel) const
void setAverageValueFilterEnabled (int channel, bool enable)
bool averageValueFilterIsEnabled (int channel) const
void setProcessValueRepresentation (int channel, processValueRepresentation_t representation)
Set process value representation for given channel.
processValueRepresentation_t processValueRepresentation (int channel) const
Get process value representation for given channel.
bool siemensFormatIsEnabled (int channel) const
void setWireBreakShortCircuitIndicationEnabled (int channel, bool enable)
bool wireBreakShortCircuitIndicationIsEnabled (int channel) const
void setOutOfRangeIndicationEnabled (int channel, bool enable)
bool outOfRangeIndicationIsEnabled (int channel) const
void setOutOfRangeIndicationLimits (int channel, int underrange, int overrange)
int underrangeIndicationLimit (int channel)
int overrangeIndicationLimit (int channel)
void setManufacturerCalibration (int channel)
void setUserCalibration (int channel, double offset, double gain)
double calibrationOffset () const
double calibrationGain () const
void setScaling (int channel, bool useManufacturerScaling, bool useUserScaling, double userOffset, double userGain, double twoWireOffset)
Set scaling.
bool manufacturerScalingIsEnabled (int channel) const
Check if manufacturer scaling is used.
double manufacturerScalingOffset (int channel) const
Get manufacturer scaling offset.
double manufacturerScalingGain (int channel) const
Get manufacturer scaling gain.
bool userScalingIsEnabled (int channel) const
Check if user scaling is used.
double userScalingOffset (int channel) const
Get user scaling offset.
double userScalingGain (int channel) const
Get user scaling gain.
double twoWireOffset (int channel) const
Public Member Functions inherited from mdtDeviceModbusWagoModule
mdtDeviceModbusWagoModule (bool autoDeleteIos, mdtDeviceModbusWago *device)
Constructor.
virtual ~mdtDeviceModbusWagoModule ()
Destructor.
void clear (bool forceDeleteIos=false)
Clear I/O module.
bool setupFromRegisterWord (quint16 word)
Setup module.
virtual void updateAddresses (int firstAiAddress, int firstAoAddressRead, int firstAoAddressWrite, int firstDiAddress, int firstDoAddressRead, int firstDoAddressWrite)
Update addresses of the module.
int firstAiAddress () const
Get first address of module's analog inputs process image.
virtual int lastAiAddress () const
Get last address of module's analog inputs process image.
virtual int nextModuleFirstAiAddress () const
Get first address for next module in analog inputs process image.
int firstAoAddressRead () const
Get first address of module's analog outputs process image for read access.
virtual int lastAoAddressRead () const
Get last address of module's analog outputs process image for read access.
virtual int nextModuleFirstAoAddressRead () const
Get first address for next module in analog outputs process image for read access.
int firstAoAddressWrite () const
Get first address of module's analog outputs process image for write access.
virtual int lastAoAddressWrite () const
Get last address of module's analog outputs process image for write access.
virtual int nextModuleFirstAoAddressWrite () const
Get first address for next module in digital outputs process image for write access.
int firstDiAddress () const
Get first address of module's digital inputs process image.
virtual int lastDiAddress () const
Get last address of module's digital inputs process image.
virtual int nextModuleFirstDiAddress () const
Get first address for next module in digital inputs process image.
int firstDoAddressRead () const
Get first address of module's digital outputs process image for read access.
virtual int lastDoAddressRead () const
Get last address of module's digital outputs process image for read access.
virtual int nextModuleFirstDoAddressRead () const
Get first address for next module in digital outputs process image for read access.
int firstDoAddressWrite () const
Get first address of module's digital outputs process image for write access.
virtual int lastDoAddressWrite () const
Get last address of module's digital outputs process image for write access.
virtual int nextModuleFirstDoAddressWrite () const
Get first address for next module in digital outputs process image for write access.
const QList< mdtAnalogIo * > & analogInputs ()
Access internal analog inputs.
const QList< mdtAnalogIo * > & analogOutputs ()
Access internal analog outputs.
const QList< mdtDigitalIo * > & digitalInputs ()
Access internal digital inputs.
const QList< mdtDigitalIo * > & digitalOutputs ()
Access internal digital outputs.
type_t type () const
Get module type.
int partNumber () const
QString typeText() const;.
QString partNumberText () const
Get text version of part number.
QString deviceName ()
Get device name.
Additional Inherited Members
Protected Member Functions inherited from mdtDeviceModbusWagoModule
void addAnalogInput (mdtAnalogIo *aio)
Add a analog input.
void addAnalogOutput (mdtAnalogIo *aio)
Add a analog output.
void addDigitalInput (mdtDigitalIo *dio)
Add a digital input.
void addDigitalOutput (mdtDigitalIo *dio)
Add a digital output.
void addRegisters (int channelCount, int firstAddressRead, int firstAddressWrite)
Add registers.
void clearRegisters ()
Clear registers.
int channelCountRegisters () const
Get number of channels regarding registers.
quint8 statusByte (int channel) const
Get the status byte for given channel.
void setControlByte (int channel, quint8 byte)
Set the control byte for given channel.
quint8 controlByte (int channel) const
Get the control byte for given channel.
void setRegisterDataWord (int channel, quint16 word)
Set register data word for given channel.
quint16 registerDataWord (int channel) const
Get register data word for given channel.
void setRegisterDataBytes (int channel, quint8 byteD1, quint8 byteD0)
Set register data bytes for given channel.
quint8 registerDataByteD1 (int channel)
Get register data byte D1 or D3 or ...
quint8 registerDataByteD0 (int channel)
Get register data byte D0 or D2 or ...
bool readRegisters (int firstChannel, int lastChannel, bool needDeviceSetupState)
Read register bytes for given range of channels.
bool writeRegisters (int firstChannel, int lastChannel, bool needDeviceSetupState)
Write register bytes for given range of channels.
bool readStatusBytes (int firstChannel, int lastChannel, bool needDeviceSetupState)
Read status byte for given range of channels.
bool writeControlBytes (int firstChannel, int lastChannel, bool needDeviceSetupState)
Write control byte for given range of channels.
void wait (int ms)
Wait some time.
virtual QVariant analogOutputValueMin (int partNumber, int channel) const
Get the min value of a range of analog outputs.
virtual QVariant analogOutputValueMax (int partNumber, int channel) const
Get the max value of a range of analog outputs.
virtual int analogOutputValueBitsCount (int partNumber, int channel) const
Get the number of bits (including sign bit) used to represent a value of analog outputs.
virtual int analogOutputValueLsbIndex (int partNumber, int channel) const
Get index of the first bit (LSB) that represents the value of analog outputs.
virtual QVariant analogOutputValueSigned (int partNumber, int channel) const
Check if a analog outputs returns a signed value or not.
virtual QVariant analogOutputValueScaledFromMinToMax (int partNumber, int channel) const
Check if analog output's value is scaled from minimum to maximum.
virtual QVariant analogOutputValueConversionFactor (int partNumber, int channel) const
Get analog output's conversion factor.
virtual QString analogOutputUnit (int partNumber, int channel) const
Get unit of a analog outputs (V, A, ...)
int digitalInputsProcessImageSize (quint16 word) const
Get size of digital inputs process image.
virtual int digitalInputsCount (quint16 word) const
Get the number of digital inputs.
int digitalOutputsProcessImageSize (quint16 word) const
Get size of digital outputs process image.
virtual int digitalOutputsCount (quint16 word) const
Get the number of digital outputs.
Detailed Description
Helper class for RTD modules.
Current version implements following modules:
750-464 2/4 AI RTD
Definition at line 34 of file mdtDeviceModbusWagoModuleRtd.h.
Member Enumeration Documentation
enum mdtDeviceModbusWagoModuleRtd::processValueRepresentation_t
Process calue representation.
Enumerator
C2
Two's complement representation
AmountSign
Amount / sign representation
C2S5
S5-FB250 with two's complement representation
AmountSignS5
S5-FB250 with amount / sign representation
Definition at line 66 of file mdtDeviceModbusWagoModuleRtd.h.
enum mdtDeviceModbusWagoModuleRtd::psrrMode_t
PSRR mode.
Enumerator
Psrr50Hz
50Hz
Psrr60Hz
60Hz
Psrr5060Hz
50/60Hz
PsrrUnknown
Unknow/illegal
Definition at line 40 of file mdtDeviceModbusWagoModuleRtd.h.
enum mdtDeviceModbusWagoModuleRtd::sensorType_t
Sensor type.
Enumerator
Unknown
Unknown (for reserved bits)
Pt100
Pt100 (IEC 751)
Ni100
Ni100 (DIN 43760)
Pt1000
Pt1000 (IEC 751)
Pt500
Pt500 (IEC 751)
Pt200
Pt200 (IEC 751)
Ni1000
Ni1000 (DIN 43760)
Ni120
Ni120 (Minco)
Ni1000TK
Ni1000 (TK 5000)
Potentiometer
Potentiometer
R10R5000
10 to 5000 Ohm
R10R1200
10 to 1200 Ohm
Definition at line 49 of file mdtDeviceModbusWagoModuleRtd.h.
Constructor & Destructor Documentation
mdtDeviceModbusWagoModuleRtd::mdtDeviceModbusWagoModuleRtd (bool autoDeleteIos, mdtDeviceModbusWago * device)
Constructor.
Parameters
autoDeleteIos If true, internally created I/O's are deleted when this object is destroyed
device Pointer to device (used for register service access)
Precondition
device must be a valid pointer
Definition at line 27 of file mdtDeviceModbusWagoModuleRtd.cpp.
References C2, Pt100, Pt1000, setIoCount(), setProcessValueRepresentation(), and setSensorType().
mdtDeviceModbusWagoModuleRtd::~mdtDeviceModbusWagoModuleRtd ()
Destructor.
If autoDeleteIos is true, internal I/O's are deleted
Definition at line 50 of file mdtDeviceModbusWagoModuleRtd.cpp.
Member Function Documentation
bool mdtDeviceModbusWagoModuleRtd::averageValueFilterIsEnabled (int channel) const
Definition at line 122 of file mdtDeviceModbusWagoModuleRtd.cpp.
double mdtDeviceModbusWagoModuleRtd::calibrationGain () const
Definition at line 186 of file mdtDeviceModbusWagoModuleRtd.cpp.
double mdtDeviceModbusWagoModuleRtd::calibrationOffset () const
Definition at line 182 of file mdtDeviceModbusWagoModuleRtd.cpp.
int mdtDeviceModbusWagoModuleRtd::connectionTypeWiresCount (int channel) const
Definition at line 106 of file mdtDeviceModbusWagoModuleRtd.cpp.
double mdtDeviceModbusWagoModuleRtd::manufacturerScalingGain (int channel) const
Get manufacturer scaling gain.
Definition at line 202 of file mdtDeviceModbusWagoModuleRtd.cpp.
bool mdtDeviceModbusWagoModuleRtd::manufacturerScalingIsEnabled (int channel) const
Check if manufacturer scaling is used.
Definition at line 194 of file mdtDeviceModbusWagoModuleRtd.cpp.
double mdtDeviceModbusWagoModuleRtd::manufacturerScalingOffset (int channel) const
Get manufacturer scaling offset.
Definition at line 198 of file mdtDeviceModbusWagoModuleRtd.cpp.
bool mdtDeviceModbusWagoModuleRtd::outOfRangeIndicationIsEnabled (int channel) const
Definition at line 158 of file mdtDeviceModbusWagoModuleRtd.cpp.
int mdtDeviceModbusWagoModuleRtd::overrangeIndicationLimit (int channel)
Definition at line 170 of file mdtDeviceModbusWagoModuleRtd.cpp.
mdtDeviceModbusWagoModuleRtd::processValueRepresentation_t mdtDeviceModbusWagoModuleRtd::processValueRepresentation (int channel) const
Get process value representation for given channel.
Precondition
Channel must be in a valid range
Definition at line 134 of file mdtDeviceModbusWagoModuleRtd.cpp.
mdtDeviceModbusWagoModuleRtd::psrrMode_t mdtDeviceModbusWagoModuleRtd::psrrMode () const
Get the PSRR mode.
Definition at line 81 of file mdtDeviceModbusWagoModuleRtd.cpp.
mdtDeviceModbusWagoModuleRtd::sensorType_t mdtDeviceModbusWagoModuleRtd::sensorType (int channel) const
Get the sensor type of given channel.
Precondition
Channel must be in a valid range
Definition at line 94 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setAverageValueFilterEnabled (int channel, bool enable)
Definition at line 118 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setConnectionTypeWiresCount (int channel, int wiresCount)
Definition at line 102 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setIoCount (int count)
Set the I/O count.
Note that analog inputs (mdtAnalogIo objects) are not created here. They will be created by mdtDeviceModbusWagoModule::setupFromRegisterWord() .
Precondition
count must be 2 or 4
Definition at line 54 of file mdtDeviceModbusWagoModuleRtd.cpp.
References mdtDeviceModbusWagoModule::analogInputs(), C2, and Pt100.
Referenced by mdtDeviceModbusWagoModuleRtd().
void mdtDeviceModbusWagoModuleRtd::setManufacturerCalibration (int channel)
Definition at line 174 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setOutOfRangeIndicationEnabled (int channel, bool enable)
Definition at line 154 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setOutOfRangeIndicationLimits (int channel, int underrange, int overrange)
Definition at line 162 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setProcessValueRepresentation (int channel, processValueRepresentation_t representation)
Set process value representation for given channel.
Precondition
Channel must be in a valid range
Definition at line 126 of file mdtDeviceModbusWagoModuleRtd.cpp.
Referenced by mdtDeviceModbusWagoModuleRtd().
void mdtDeviceModbusWagoModuleRtd::setPsrrMode (psrrMode_t mode)
Set the PSRR mode.
Definition at line 76 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setScaling (int channel, bool useManufacturerScaling, bool useUserScaling, double userOffset, double userGain, double twoWireOffset)
Set scaling.
Definition at line 190 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setSensorType (int channel, sensorType_t type)
Set the sensor type for given channel.
Precondition
Channel must be in a valid range
Definition at line 86 of file mdtDeviceModbusWagoModuleRtd.cpp.
References mdtDeviceModbusWagoModule::type().
Referenced by mdtDeviceModbusWagoModuleRtd().
void mdtDeviceModbusWagoModuleRtd::setUserCalibration (int channel, double offset, double gain)
Definition at line 178 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setWatchdogTimerEnabled (int channel, bool enable)
Definition at line 110 of file mdtDeviceModbusWagoModuleRtd.cpp.
void mdtDeviceModbusWagoModuleRtd::setWireBreakShortCircuitIndicationEnabled (int channel, bool enable)
Definition at line 146 of file mdtDeviceModbusWagoModuleRtd.cpp.
bool mdtDeviceModbusWagoModuleRtd::siemensFormatIsEnabled (int channel) const
Definition at line 142 of file mdtDeviceModbusWagoModuleRtd.cpp.
double mdtDeviceModbusWagoModuleRtd::twoWireOffset (int channel) const
Definition at line 218 of file mdtDeviceModbusWagoModuleRtd.cpp.
int mdtDeviceModbusWagoModuleRtd::underrangeIndicationLimit (int channel)
Definition at line 166 of file mdtDeviceModbusWagoModuleRtd.cpp.
double mdtDeviceModbusWagoModuleRtd::userScalingGain (int channel) const
Get user scaling gain.
Definition at line 214 of file mdtDeviceModbusWagoModuleRtd.cpp.
bool mdtDeviceModbusWagoModuleRtd::userScalingIsEnabled (int channel) const
Check if user scaling is used.
Definition at line 206 of file mdtDeviceModbusWagoModuleRtd.cpp.
double mdtDeviceModbusWagoModuleRtd::userScalingOffset (int channel) const
Get user scaling offset.
Definition at line 210 of file mdtDeviceModbusWagoModuleRtd.cpp.
bool mdtDeviceModbusWagoModuleRtd::watchdogTimerIsEnabled (int channel) const
Definition at line 114 of file mdtDeviceModbusWagoModuleRtd.cpp.
bool mdtDeviceModbusWagoModuleRtd::wireBreakShortCircuitIndicationIsEnabled (int channel) const
Definition at line 150 of file mdtDeviceModbusWagoModuleRtd.cpp.
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceModbusWagoModuleRtd.h
src/mdtdevice/mdtDeviceModbusWagoModuleRtd.cpp