Multi diag tools: mdtDeviceIos Class Reference
mdtDeviceIos Class Reference
Container for a set of I/O's.
#include <mdtDeviceIos.h>
Public Types
enum addressAccess_t { Read, Write }
Adress access type.
Public Slots
void updateAnalogInputValues (const QList< QVariant > &values, const int firstAddress, const int n, bool matchAddresses)
Update (G)UI's value for a set of analog inputs.
void updateAnalogOutputValues (const QList< QVariant > &values, int firstAddress, addressAccess_t firstAddressAccess, int n, bool matchAddresses)
Update (G)UI's value for a set of analog outputs.
void setAnalogOutputsEnabled (bool enabled)
Enable/disable (G)UI's analog outputs.
void updateDigitalInputValues (const QList< QVariant > &values, int firstAddress, int n, bool matchAddresses)
Update (G)UI's value for a set of digital inputs.
void updateDigitalOutputValues (const QList< QVariant > &values, int firstAddress, addressAccess_t firstAddressAccess, int n, bool matchAddresses)
Update (G)UI's value for a set of digital outputs.
void setDigitalOutputsEnabled (bool enabled)
Enable/disable (G)UI's digital outputs.
Public Member Functions
mdtDeviceIos (QObject *parent=0)
Constructor.
~mdtDeviceIos ()
Destructor.
void setAutoDeleteIos (bool autoDelete)
Set the auto delete flag.
void deleteIos ()
Delete all I/O objects.
void addAnalogInput (mdtAnalogIo *ai)
Add a analog input.
void addAnalogInputs (const QList< mdtAnalogIo * > &aiList)
Add a list of analog inputs.
mdtAnalogIo * analogInputAtAddress (int address)
Get analog input at given address.
mdtAnalogIo * analogInputWithLabelShort (const QString &labelShort)
Get analog input with a given short label.
const QList< mdtAnalogIo * > analogInputs () const
Get a list containing all analog inputs.
const QList
< mdtDeviceIosSegment * > & analogInputsSegments () const
Get a list of all analog inputs segments.
int analogInputsCount () const
Get the number of analog inputs.
void setAnalogInputsValue (const mdtValue &value)
Set a value and validity for all analog inputs.
void addAnalogOutput (mdtAnalogIo *ao, addressAccess_t sortSegmentsBy=Write)
Add a analog output.
void addAnalogOutputs (const QList< mdtAnalogIo * > &aoList, addressAccess_t sortSegmentsBy=Write)
Add a list of analog outputs.
mdtAnalogIo * analogOutputAtAddressRead (int address)
Get analog output at given address for read access.
mdtAnalogIo * analogOutputAtAddressWrite (int address)
Get analog output at given address for write access.
mdtAnalogIo * analogOutputWithLabelShort (const QString &labelShort)
Get analog output with a given short label.
const QList< mdtAnalogIo * > analogOutputs () const
Get a list containing all analog outputs.
const QList
< mdtDeviceIosSegment * > & analogOutputsSegments () const
Get a list of all analog inputs segments.
int analogOutputsCount () const
Get the number of analog outputs.
QList< int > analogOutputsValuesIntByAddressWrite () const
Get all analog outputs values in device specific format sorted by address for write access.
void setAnalogOutputsValue (const mdtValue &value)
Set a value and validity for all analog outputs.
void addDigitalInput (mdtDigitalIo *di)
Add a digital input.
void addDigitalInputs (const QList< mdtDigitalIo * > &diList)
Add a list of digital inputs.
mdtDigitalIo * digitalInputAtAddress (int address)
Get digital input at given address.
mdtDigitalIo * digitalInputWithLabelShort (const QString &labelShort)
Get digital input with a given short label.
const QList< mdtDigitalIo * > digitalInputs () const
Get a list containing all digital inputs.
const QList
< mdtDeviceIosSegment * > & digitalInputsSegments () const
Get a list of all digital inputs segments.
int digitalInputsCount () const
Get the number of digital inputs.
void setDigitalInputsValue (const mdtValue &value)
Set a value and validity for all digital inputs.
void addDigitalOutput (mdtDigitalIo *dout, addressAccess_t sortSegmentsBy=Write)
Add a digital output.
void addDigitalOutputs (const QList< mdtDigitalIo * > &doList, addressAccess_t sortSegmentsBy=Write)
Add a list of digital outputs.
mdtDigitalIo * digitalOutputAtAddressRead (int address)
Get digital output at given address for read access.
mdtDigitalIo * digitalOutputAtAddressWrite (int address)
Get digital output at given address for write access.
mdtDigitalIo * digitalOutputWithLabelShort (const QString &labelShort)
Get digital output with a given short label.
const QList< mdtDigitalIo * > digitalOutputs () const
Get a list containing all digital outputs.
const QList
< mdtDeviceIosSegment * > & digitalOutputsSegments () const
Get a list of all digital outputs segments.
int digitalOutputsCount () const
Get the number of digital outputs.
void setDigitalOutputsValue (const mdtValue &value)
Set a value and validity for all digital outputs.
QList< bool > digitalOutputsStatesByAddressWrite () const
Get all digital outputs states sorted by address for write access.
void setIosDefaultLabelShort ()
Set a default short label for each I/O.
Detailed Description
Container for a set of I/O's.
This class can contain 4 type of I/O:
Analog input (based on mdtAnalogIo)
Analog output (based on mdtAnalogIo)
Digital input (based on mdtDigitalIo)
Digital output (based on mdtDigitalIo)
The main goal here is the functionnal part. The (G)UI part is done in other place. For example, it's possible to use mdtDeviceIosWidget class to have a generic representation af all type of I/O.
Concept of position
Internally, I/Os are stored in 4 QList:
1 for analog inputs
1 fro analog outputs
1 for digital inputs
1 for digital outputs
The position is simply a index in a list, with a range from 0 to N-1 I/O for a type . The order of position is the order of call to add method .
Concept of address
Internally, each I/O is stored in a QMap with an address as key. In some cases, this can reflect a real situations, for exaple:
Relative address of a MODBUS query
Memory address of physical device
You can choose to use this address as simple index.
Note: if a address is changed by accessing directly by mdtAnalogIo or mdtDigitalIo, this will not be reflected, and stored I/O's will become incoherent. The address must allways be set before adding the I/O to this container. Example:
mdtAnalogIo *analogIn = new mdtAnalogIo;
analogIn->setAddress(25);
ios.addAnalogInput(analogIn);
For some devices it's possible to read/write multiple I/O's in one query (f.ex. I/O systems communicating with MODBUS). To use this functionnality, this I/O container provide a solution to get values for several I/O's. Because addresses of all I/O's that will be stored in this container are not necessarily contiguous, the concept of segment is used. For example: ADDRESS|0|1|2|5|6| . Here, we have 2 segments: |0|1|2| and |5|6| . If we would write all I/O's present in this example, we could do it with 2 queries (1 per segment). To set/get data for segments, the folowing methods can be used:
analogInputsSegments()
analogOutputsSegments()
digitalInputsSegments()
digitalOutputsSegments()
Some helper methods are also available:
updateAnalogInputValues()
updateAnalogOutputValues()
updateDigitalInputValues()
updateDigitalOutputValues()
Definition at line 94 of file mdtDeviceIos.h.
Member Enumeration Documentation
enum mdtDeviceIos::addressAccess_t
Adress access type.
It can happen that a I/O must be accessed by 2 different addresses for write (set) and read (get). A typical example is MODBUS.
Enumerator
Read
Considere the read access address
Write
Considere the write access address
Definition at line 106 of file mdtDeviceIos.h.
Constructor & Destructor Documentation
mdtDeviceIos::mdtDeviceIos (QObject * parent = 0)
Constructor.
Definition at line 29 of file mdtDeviceIos.cpp.
mdtDeviceIos::~mdtDeviceIos ()
Destructor.
Definition at line 35 of file mdtDeviceIos.cpp.
References deleteIos().
Member Function Documentation
void mdtDeviceIos::addAnalogInput (mdtAnalogIo * ai)
Add a analog input.
Precondition
ao must be a valid pointer allready be stored
No I/O with same address must be set as double
Definition at line 98 of file mdtDeviceIos.cpp.
References mdtAbstractIo::addressRead(), and mdtDeviceIosSegment::setIos().
Referenced by addAnalogInputs(), and mdtDevice::addInput().
void mdtDeviceIos::addAnalogInputs (const QList< mdtAnalogIo * > & aiList)
Add a list of analog inputs.
See Also
addAnalogInput()
Definition at line 139 of file mdtDeviceIos.cpp.
References addAnalogInput().
Referenced by mdtDevice::addInputs().
void mdtDeviceIos::addAnalogOutput (mdtAnalogIo * ao, mdtDeviceIos::addressAccess_t sortSegmentsBy = Write)
Add a analog output.
Parameters
sortSegmentsBy Output will be added to a segment. sortSegmentsBy gives the address access to consider. Note: if device maps addresses for read and write access in the same order, but just with a offset, this parameter is not important (The address set in mdtAnalogIo object are not changed).
Precondition
ao must be a valid pointer allready be stored
No I/O with same address must be set as double
Definition at line 193 of file mdtDeviceIos.cpp.
References mdtAbstractIo::addressRead(), mdtAbstractIo::addressWrite(), Read, and mdtDeviceIosSegment::setIos().
Referenced by addAnalogOutputs(), and mdtDevice::addOutput().
void mdtDeviceIos::addAnalogOutputs (const QList< mdtAnalogIo * > & aoList, addressAccess_t sortSegmentsBy = Write)
Add a list of analog outputs.
See Also
addAnalogOutput()
Definition at line 251 of file mdtDeviceIos.cpp.
References addAnalogOutput().
Referenced by mdtDevice::addOutputs().
void mdtDeviceIos::addDigitalInput (mdtDigitalIo * di)
Add a digital input.
Precondition
ao must be a valid pointer allready be stored
No I/O with same address must be set as double
Definition at line 325 of file mdtDeviceIos.cpp.
References mdtAbstractIo::address(), mdtAbstractIo::addressRead(), and mdtDeviceIosSegment::setIos().
Referenced by addDigitalInputs(), and mdtDevice::addInput().
void mdtDeviceIos::addDigitalInputs (const QList< mdtDigitalIo * > & diList)
Add a list of digital inputs.
See Also
addDigitalInput()
Definition at line 368 of file mdtDeviceIos.cpp.
References addDigitalInput().
Referenced by mdtDevice::addInputs().
void mdtDeviceIos::addDigitalOutput (mdtDigitalIo * dout, addressAccess_t sortSegmentsBy = Write)
Add a digital output.
Parameters
sortSegmentsBy Output will be added to a segment. sortSegmentsBy gives the address access to consider. Note: if device maps addresses for read and write access in the same order, but just with a offset, this parameter is not important (The address set in mdtAnalogIo object are not changed).
Precondition
ao must be a valid pointer allready be stored
No I/O with same address must be set as double
Definition at line 422 of file mdtDeviceIos.cpp.
References mdtAbstractIo::addressRead(), mdtAbstractIo::addressWrite(), Read, and mdtDeviceIosSegment::setIos().
Referenced by addDigitalOutputs(), and mdtDevice::addOutput().
void mdtDeviceIos::addDigitalOutputs (const QList< mdtDigitalIo * > & doList, addressAccess_t sortSegmentsBy = Write)
Add a list of digital outputs.
See Also
addDigitalOutput()
Definition at line 479 of file mdtDeviceIos.cpp.
References addDigitalOutput().
Referenced by mdtDevice::addOutputs().
mdtAnalogIo * mdtDeviceIos::analogInputAtAddress (int address)
Get analog input at given address.
If no object exists at given address, a null pointer is returned.
Definition at line 149 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogInputValue().
const QList< mdtAnalogIo * > mdtDeviceIos::analogInputs () const
Get a list containing all analog inputs.
Note: the returned list is not sorted by address . for grouped queries, see analogInputsSegments() and updateAnalogInputValues()
Definition at line 168 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogInputValueAt(), and mdtDeviceIosWidget::setDeviceIos().
int mdtDeviceIos::analogInputsCount () const
Get the number of analog inputs.
Definition at line 178 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogInputs().
const QList< mdtDeviceIosSegment * > & mdtDeviceIos::analogInputsSegments () const
Get a list of all analog inputs segments.
Definition at line 173 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogInputs(), and updateAnalogInputValues().
mdtAnalogIo * mdtDeviceIos::analogInputWithLabelShort (const QString & labelShort)
Get analog input with a given short label.
If no object exists at given short label, a null pointer is returned. If more than one object exists with the same short label, the first found is returned.
Definition at line 154 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogInputValue().
mdtAnalogIo * mdtDeviceIos::analogOutputAtAddressRead (int address)
Get analog output at given address for read access.
If no object exists at given address, a null pointer is returned.
Definition at line 261 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogOutputValue().
mdtAnalogIo * mdtDeviceIos::analogOutputAtAddressWrite (int address)
Get analog output at given address for write access.
If no object exists at given address, a null pointer is returned.
Definition at line 266 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::setAnalogOutputValue().
const QList< mdtAnalogIo * > mdtDeviceIos::analogOutputs () const
Get a list containing all analog outputs.
Note: the returned list is not sorted by address .
Definition at line 285 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::deleteIos(), mdtDevice::getAnalogOutputValueAt(), mdtDevice::setAnalogOutputValueAt(), and mdtDeviceIosWidget::setDeviceIos().
int mdtDeviceIos::analogOutputsCount () const
Get the number of analog outputs.
Definition at line 295 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogOutputs(), and mdtDevice::setAnalogOutputs().
const QList< mdtDeviceIosSegment * > & mdtDeviceIos::analogOutputsSegments () const
Get a list of all analog inputs segments.
Definition at line 290 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogOutputs(), mdtDevice::setAnalogOutputs(), and updateAnalogOutputValues().
QList< int > mdtDeviceIos::analogOutputsValuesIntByAddressWrite () const
Get all analog outputs values in device specific format sorted by address for write access.
Definition at line 300 of file mdtDeviceIos.cpp.
mdtAnalogIo * mdtDeviceIos::analogOutputWithLabelShort (const QString & labelShort)
Get analog output with a given short label.
If no object exists at given short label, a null pointer is returned. If more than one object exists with the same short label, the first found is returned.
Definition at line 271 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogOutputValue(), and mdtDevice::setAnalogOutputValue().
void mdtDeviceIos::deleteIos ()
Delete all I/O objects.
Will free all stored I/O objects.
Definition at line 70 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::deleteIos(), and ~mdtDeviceIos().
mdtDigitalIo * mdtDeviceIos::digitalInputAtAddress (int address)
Get digital input at given address.
If no object exists at given address, a null pointer is returned.
Definition at line 378 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalInputValue().
const QList< mdtDigitalIo * > mdtDeviceIos::digitalInputs () const
Get a list containing all digital inputs.
Note: the returned list is not sorted by address .
Definition at line 397 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalInputValueAt(), and mdtDeviceIosWidget::setDeviceIos().
int mdtDeviceIos::digitalInputsCount () const
Get the number of digital inputs.
Definition at line 402 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalInputs().
const QList< mdtDeviceIosSegment * > & mdtDeviceIos::digitalInputsSegments () const
Get a list of all digital inputs segments.
Definition at line 407 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalInputs(), and updateDigitalInputValues().
mdtDigitalIo * mdtDeviceIos::digitalInputWithLabelShort (const QString & labelShort)
Get digital input with a given short label.
If no object exists at given short label, a null pointer is returned. If more than one object exists with the same short label, the first found is returned.
Definition at line 383 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalInputValue().
mdtDigitalIo * mdtDeviceIos::digitalOutputAtAddressRead (int address)
Get digital output at given address for read access.
If no object exists at given address, a null pointer is returned.
Definition at line 489 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalOutputValue().
mdtDigitalIo * mdtDeviceIos::digitalOutputAtAddressWrite (int address)
Get digital output at given address for write access.
If no object exists at given address, a null pointer is returned.
Definition at line 494 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::setDigitalOutputValue().
const QList< mdtDigitalIo * > mdtDeviceIos::digitalOutputs () const
Get a list containing all digital outputs.
Note: the returned list is not sorted by address .
Definition at line 513 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::deleteIos(), mdtDevice::getDigitalOutputValueAt(), mdtDeviceIosWidget::setDeviceIos(), and mdtDevice::setDigitalOutputValueAt().
int mdtDeviceIos::digitalOutputsCount () const
Get the number of digital outputs.
Definition at line 523 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalOutputs(), and mdtDevice::setDigitalOutputs().
const QList< mdtDeviceIosSegment * > & mdtDeviceIos::digitalOutputsSegments () const
Get a list of all digital outputs segments.
Definition at line 518 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalOutputs(), mdtDevice::setDigitalOutputs(), and updateDigitalOutputValues().
QList< bool > mdtDeviceIos::digitalOutputsStatesByAddressWrite () const
Get all digital outputs states sorted by address for write access.
Definition at line 538 of file mdtDeviceIos.cpp.
mdtDigitalIo * mdtDeviceIos::digitalOutputWithLabelShort (const QString & labelShort)
Get digital output with a given short label.
If no object exists at given short label, a null pointer is returned. If more than one object exists with the same short label, the first found is returned.
Definition at line 499 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalOutputValue(), and mdtDevice::setDigitalOutputValue().
void mdtDeviceIos::setAnalogInputsValue (const mdtValue & value)
Set a value and validity for all analog inputs.
Definition at line 183 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogInputs().
void mdtDeviceIos::setAnalogOutputsEnabled (bool enabled) slot
Enable/disable (G)UI's analog outputs.
Definition at line 776 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::setAnalogOutputs().
void mdtDeviceIos::setAnalogOutputsValue (const mdtValue & value)
Set a value and validity for all analog outputs.
Definition at line 315 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getAnalogOutputs(), and mdtDevice::setAnalogOutputs().
void mdtDeviceIos::setAutoDeleteIos (bool autoDelete)
Set the auto delete flag.
If true, all internal I/O's will be deleted when this object is deleted.
By default, this flag is true.
Definition at line 65 of file mdtDeviceIos.cpp.
void mdtDeviceIos::setDigitalInputsValue (const mdtValue & value)
Set a value and validity for all digital inputs.
Definition at line 412 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalInputs().
void mdtDeviceIos::setDigitalOutputsEnabled (bool enabled) slot
Enable/disable (G)UI's digital outputs.
Definition at line 977 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::setDigitalOutputs().
void mdtDeviceIos::setDigitalOutputsValue (const mdtValue & value)
Set a value and validity for all digital outputs.
Definition at line 528 of file mdtDeviceIos.cpp.
Referenced by mdtDevice::getDigitalOutputs(), and mdtDevice::setDigitalOutputs().
void mdtDeviceIos::setIosDefaultLabelShort ()
Set a default short label for each I/O.
Default short label is the I/O type suffixed with his number (AI1, AI2, AO1, DI1, DO1, ...)
Definition at line 553 of file mdtDeviceIos.cpp.
Referenced by mdtDeviceModbusWago::detectIos().
void mdtDeviceIos::updateAnalogInputValues (const QList< QVariant > & values, const int firstAddress, const int n, bool matchAddresses) slot
Update (G)UI's value for a set of analog inputs.
Parameters
values The values of inputs, must be sorted by address, ascending. If a value is invalid, concerned input will be set invalid.
firstAddress Address of first input to update:
firstAddress < 0 : the I/O in container that has the lowest address will fix the first address.
firstAddress >= 0 : will be token as first address.
n Maximum quantity of inputs to update (can be < values size). If < 0, the maximum possible values to store is determined between list size and the internal quantity of inputs. Note: this limit was introduced for conveniance during MODBUS decoding.
matchAddresses If true, first index of values will be considered as first address , and only I/O's for witch address match will be updated. For example, if we have following I/O's addresses in container: 0,1,2,5,6 and we give 4 values:
If firstAddress = 2 and matchAddresses is set : I/O's with address 2, 5 and 6 will be updated with values at index 0 and 3 (by giving firstAddress = 2, addresses are considered 2,3,4,5, so only 2 values will be updated).
If firstAddress = -1 and matchAddresses is set : I/O's with address 0, 1 and 2 will be updated (4th value must match address 3 that not exit in container, so only 3 values will be updated).
If firstAddress = 2 and matchAddresses not set : I/O's with address 2, 5 and 6 will be updated (only 3 values).
If firstAddress = -1 and matchAddresses not set : I/O's with address 0, 1, 2 and 5 will be updated (all 4 values).
Note:
If one value is invalid, concerned input will be set invalid.
Regarding on internal values type (double, int, ...), conversions will be done by internal mdtAnalogIo.
Precondition
n must be <= values size
Definition at line 585 of file mdtDeviceIos.cpp.
References analogInputsSegments(), mdtDeviceIosSegment::containsAddressRead(), mdtDeviceIosSegment::ioCount(), mdtDeviceIosSegment::startAddressRead(), and mdtDeviceIosSegment::updateValuesFromAddressRead().
void mdtDeviceIos::updateAnalogOutputValues (const QList< QVariant > & values, int firstAddress, addressAccess_t firstAddressAccess, int n, bool matchAddresses) slot
Update (G)UI's value for a set of analog outputs.
Parameters
values The values of outputs, must be sorted by address, ascending. If a value is invalid, concerned outputs will be set invalid.
firstAddress Address of first output to update:
firstAddress < 0 : the I/O in container that has the lowest address will fix the first address.
firstAddress >= 0 : will be token as first address.
firstAddressAccess Tell here if given firstAddress is supposed for read or write access. Note: f.ex: by decoding a MODBUS PDU, we update I/O's of this container once we had read states from device, here the address access will also be Read.
n Maximum quantity of outputs to update (can be < values size). If < 0, the maximum possible values to store is determined between list size and the internal quantity of outputs. Note: this limit was introduced for conveniance during MODBUS decoding.
matchAddresses If true, first index of values will be considered as first address , and only I/O's for witch address match will be updated. For example, if we have following I/O's addresses in container: 0,1,2,5,6 and we give 4 values:
If firstAddress = 2 and matchAddresses is set : I/O's with address 2, 5 and 6 will be updated with values at index 0 and 3 (by giving firstAddress = 2, addresses are considered 2,3,4,5, so only 2 values will be updated).
If firstAddress = -1 and matchAddresses is set : I/O's with address 0, 1 and 2 will be updated (4th value must match address 3 that not exit in container, so only 3 values will be updated).
If firstAddress = 2 and matchAddresses not set : I/O's with address 2, 5 and 6 will be updated (only 3 values).
If firstAddress = -1 and matchAddresses not set : I/O's with address 0, 1, 2 and 5 will be updated (all 4 values).
Note:
If one value is invalid, concerned output will be set invalid.
Regarding on internal values type (double, int, ...), conversions will be done by internal mdtAnalogIo.
Precondition
n must be <= values size
Definition at line 669 of file mdtDeviceIos.cpp.
References analogOutputsSegments(), mdtDeviceIosSegment::containsAddressRead(), mdtDeviceIosSegment::containsAddressWrite(), mdtDeviceIosSegment::ioCount(), Read, mdtDeviceIosSegment::startAddressRead(), mdtDeviceIosSegment::startAddressWrite(), and mdtDeviceIosSegment::updateValuesFromAddressRead().
void mdtDeviceIos::updateDigitalInputValues (const QList< QVariant > & values, int firstAddress, int n, bool matchAddresses) slot
Update (G)UI's value for a set of digital inputs.
Parameters
values The values of inputs, must be sorted by address, ascending. If a value is invalid, concerned input will be set invalid.
firstAddress Address of first input to update:
firstAddress < 0 : the I/O in container that has the lowest address will fix the first address.
firstAddress >= 0 : will be token as first address.
n Maximum quantity of inputs to update (can be < values size). If < 0, the maximum possible values to store is determined between list size and the internal quantity of inputs. Note: this limit was introduced for conveniance during MODBUS decoding.
matchAddresses If true, first index of values will be considered as first address , and only I/O's for witch address match will be updated. For example, if we have following I/O's addresses in container: 0,1,2,5,6 and we give 4 values:
If firstAddress = 2 and matchAddresses is set : I/O's with address 2, 5 and 6 will be updated with values at index 0 and 3 (by giving firstAddress = 2, addresses are considered 2,3,4,5, so only 2 values will be updated).
If firstAddress = -1 and matchAddresses is set : I/O's with address 0, 1 and 2 will be updated (4th value must match address 3 that not exit in container, so only 3 values will be updated).
If firstAddress = 2 and matchAddresses not set : I/O's with address 2, 5 and 6 will be updated (only 3 values).
If firstAddress = -1 and matchAddresses not set : I/O's with address 0, 1, 2 and 5 will be updated (all 4 values).
Note:
If one value is invalid, concerned input will be set invalid.
Regarding on internal values type (double, int, ...), conversions will be done by internal mdtAnalogIo.
Precondition
n must be <= values size
Definition at line 786 of file mdtDeviceIos.cpp.
References mdtDeviceIosSegment::containsAddressRead(), digitalInputsSegments(), mdtDeviceIosSegment::ioCount(), mdtDeviceIosSegment::startAddressRead(), and mdtDeviceIosSegment::updateValuesFromAddressRead().
void mdtDeviceIos::updateDigitalOutputValues (const QList< QVariant > & values, int firstAddress, addressAccess_t firstAddressAccess, int n, bool matchAddresses) slot
Update (G)UI's value for a set of digital outputs.
Parameters
values The values of outputs, must be sorted by address, ascending. If a value is invalid, concerned outputs will be set invalid.
firstAddress Address of first output to update:
firstAddress < 0 : the I/O in container that has the lowest address will fix the first address.
firstAddress >= 0 : will be token as first address.
firstAddressAccess Tell here if given firstAddress is supposed for read or write access. Note: f.ex: by decoding a MODBUS PDU, we update I/O's of this container once we had read states from device, here the address access will also be Read.
n Maximum quantity of outputs to update (can be < values size). If < 0, the maximum possible values to store is determined between list size and the internal quantity of outputs. Note: this limit was introduced for conveniance during MODBUS decoding.
matchAddresses If true, first index of values will be considered as first address , and only I/O's for witch address match will be updated. For example, if we have following I/O's addresses in container: 0,1,2,5,6 and we give 4 values:
If firstAddress = 2 and matchAddresses is set : I/O's with address 2, 5 and 6 will be updated with values at index 0 and 3 (by giving firstAddress = 2, addresses are considered 2,3,4,5, so only 2 values will be updated).
If firstAddress = -1 and matchAddresses is set : I/O's with address 0, 1 and 2 will be updated (4th value must match address 3 that not exit in container, so only 3 values will be updated).
If firstAddress = 2 and matchAddresses not set : I/O's with address 2, 5 and 6 will be updated (only 3 values).
If firstAddress = -1 and matchAddresses not set : I/O's with address 0, 1, 2 and 5 will be updated (all 4 values).
Note:
If one value is invalid, concerned output will be set invalid.
Regarding on internal values type (double, int, ...), conversions will be done by internal mdtAnalogIo.
Precondition
n must be <= values size
Definition at line 870 of file mdtDeviceIos.cpp.
References mdtDeviceIosSegment::containsAddressRead(), mdtDeviceIosSegment::containsAddressWrite(), digitalOutputsSegments(), mdtDeviceIosSegment::ioCount(), Read, mdtDeviceIosSegment::startAddressRead(), mdtDeviceIosSegment::startAddressWrite(), and mdtDeviceIosSegment::updateValuesFromAddressRead().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceIos.h
src/mdtdevice/mdtDeviceIos.cpp