Multi diag tools: mdtBuffer< T > Class Template Reference
mdtBuffer< T > Class Template Reference
Stockage d'éléments basé sur le principe du tampon circulaire.
#include <mdtBuffer.h>
Public Member Functions
mdtBuffer ()
Constructeur.
mdtBuffer (mdtBuffer< T > &src)
Constructeur de copie.
mdtBuffer< T > & operator= (mdtBuffer< T > &src)
Opérateur de copie.
~mdtBuffer ()
Destructeur.
bool init (size_t size)
Initialisation du tampon.
void clear ()
Efface le contenu du tampon.
size_t put (const T *data, size_t len)
Stockage d'un lot de données.
bool putOne (T data)
Stockage d'un élément par copie.
size_t putUntil (const T *data, T token, size_t maxLen, bool IgnoreNullValues)
Stockage d'un lot de données jusqu'à la rencontre d'un élément.
bool tokenReached ()
Retourne true si l'élément de fin de copie à été atteint.
size_t capacity ()
Capacité totale.
size_t remainCapacity ()
Capacité restante.
bool full ()
Déterminer si le tampon est plein.
size_t available ()
Nombre d'éléments disponibles en lecture.
size_t get (T *data, size_t len)
Lecture d'un lot de données.
size_t take (T *data, size_t len)
Retrait d'un lot de données.
T takeOne ()
Retrait d'un élément.
Detailed Description
template<class T>
class mdtBuffer< T >
Stockage d'éléments basé sur le principe du tampon circulaire.
#if USE_ASSERT == 1 #undef NDEBUG #else #define NDEBUG #endif
Stockage d'éléments basé sur le principe du tampon circulaire Idéal pour le stockage temporaire si une taille maximale est connue. Evite de nombreuses allocations/libération mémoire
Definition at line 39 of file mdtBuffer.h.
Constructor & Destructor Documentation
template<class T > template mdtBuffer< T >::mdtBuffer ()
Constructeur.
Constructeur, utiliser init() avant tout autre opération
Definition at line 7 of file mdtBuffer.cpp.
template<class T > mdtBuffer< T >::mdtBuffer (mdtBuffer< T > & src)
Constructeur de copie.
Constructeur de copie. Effectue une copie des données vers l'autre instance
Definition at line 16 of file mdtBuffer.cpp.
References mdtBuffer< T >::available(), mdtBuffer< T >::capacity(), and mdtBuffer< T >::get().
template<class T > template mdtBuffer< T >::~mdtBuffer ()
Destructeur.
Destructeur
Definition at line 59 of file mdtBuffer.cpp.
Member Function Documentation
template<class T > template size_t mdtBuffer< T >::available ()
Nombre d'éléments disponibles en lecture.
Nombre d'éléments disponibles en lecture
Returns
Le nombre d'éléments qu'il est possible de lire
Definition at line 236 of file mdtBuffer.cpp.
Referenced by mdtBuffer< T >::mdtBuffer(), and mdtBuffer< T >::operator=().
template<class T > template size_t mdtBuffer< T >::capacity ()
Capacité totale.
Capacité totale
Returns
La capacité totale du tampon
Definition at line 221 of file mdtBuffer.cpp.
Referenced by mdtBuffer< T >::mdtBuffer(), and mdtBuffer< T >::operator=().
template<class T > template void mdtBuffer< T >::clear ()
Efface le contenu du tampon.
Efface le contenu du tampon. La quantité disponible ainsi que la capacité restante sont aussi ré-initialisés
Definition at line 88 of file mdtBuffer.cpp.
template<class T > template bool mdtBuffer< T >::full ()
Déterminer si le tampon est plein.
Déterminer si le tampon est plein
Returns
True si le tampon est plein
Definition at line 231 of file mdtBuffer.cpp.
template<class T > template size_t mdtBuffer< T >::get (T * data, size_t len)
Lecture d'un lot de données.
La copie, basée sur memcpy, est performante Le cusreur de lecture interne, ainsi que le quantité disponible et la capacité restante ne sont pas altérés (plusieurs appels à cette méthode renverrait chaque fois les même données)
Parameters
data Pointeur vers les données de destination
len Nombre d'éléments à lire
Returns
Le nombre d'éléments effectivement lus
Definition at line 241 of file mdtBuffer.cpp.
Referenced by mdtBuffer< T >::mdtBuffer(), and mdtBuffer< T >::operator=().
template<class T > template bool mdtBuffer< T >::init (size_t size)
Initialisation du tampon.
Initialisation du tampon. Alloue la mémoire, initialise les données à une valeur nulle. Il est possible de ré-appeler cette fonction plusieurs fois, la zone mémoire étant alors ré-alouée
Parameters
size Capacité du tampon [nombre d'éléments]
Returns
false en cas de problème d'allocation mémoire (true si tout s'est bien passé)
Definition at line 66 of file mdtBuffer.cpp.
template<class T > template mdtBuffer< char > & mdtBuffer< T >::operator= (mdtBuffer< T > & src)
Opérateur de copie.
Opérateur de copie. Effectue une copie des données vers l'autre instance
Definition at line 38 of file mdtBuffer.cpp.
References mdtBuffer< T >::available(), mdtBuffer< T >::capacity(), and mdtBuffer< T >::get().
template<class T > template size_t mdtBuffer< T >::put (const T * data, size_t len)
Stockage d'un lot de données.
Stockage d'un lot de données par copie. La copie, basée sur memcpy, est performante
Parameters
data Pointeur vers les données sources
len Nombre d'éléments à stocker
Returns
Le nombre d'éléments effectivement stockés
Definition at line 107 of file mdtBuffer.cpp.
template<class T > template bool mdtBuffer< T >::putOne (T data)
Stockage d'un élément par copie.
Stockage d'un élément par copie.
Parameters
data Elément à stocker
Returns
True si Ok, false en cas d'erreur
Definition at line 155 of file mdtBuffer.cpp.
References incWrCursor.
template<class T > template size_t mdtBuffer< T >::putUntil (const T * data, T token, size_t maxLen, bool IgnoreNullValues)
Stockage d'un lot de données jusqu'à la rencontre d'un élément.
Stockage d'un lot de données par copie jusqu'à la rencontre d'un élément, ou maxLen si l'élément recherché n'est pas trouvé. L'élément de recherche est aussi stocké La copie, basée sur une boucle, est relativement lente (comparé à memcpy) Il est possible de ne pas stocker les caractères null ('\0')
Parameters
data Pointeur vers les données sources
token Elément désignant la fin de la copie
Maxlen Nombre d'éléments maximal à stocker
IgnoreNullValues Si true, les éléments null (0) ne seront pas stockés
Returns
Le nombre d'éléments effectivement stockés
Definition at line 175 of file mdtBuffer.cpp.
References incWrCursor.
template<class T > template size_t mdtBuffer< T >::remainCapacity ()
Capacité restante.
Capacité restante
Returns
Le nombre d'éléments qu'il est encore possible de stocker
Definition at line 226 of file mdtBuffer.cpp.
template<class T > template size_t mdtBuffer< T >::take (T * data, size_t len)
Retrait d'un lot de données.
Retrait d'un lot de données par copie. La copie, basée sur memcpy, et performante Le cusreur de lecture interne, ainsi que le quantité disponible et la capacité restante sont altérés
Parameters
data Pointeur vers les données de destination
len Nombre d'éléments à lire
Returns
Le nombre d'éléments effectivement retirés
Definition at line 280 of file mdtBuffer.cpp.
template<class T > template std::string mdtBuffer< T >::takeOne ()
Retrait d'un élément.
Retrait d'un élément Le cusreur de lecture interne, ainsi que le quantité disponible et la capacité restante sont altérés Test retour: 0 est retourné si aucun élément n'est disponible. Etant donnée que 0 peut très bien être un élément valide stocké dans le tampon, il faut utiliser une méthode de test avant le retrait. Voir available()
Returns
Un élément, ou 0 si aucune disponibilité
Definition at line 326 of file mdtBuffer.cpp.
References incRdCursor.
template<class T > template bool mdtBuffer< T >::tokenReached ()
Retourne true si l'élément de fin de copie à été atteint.
Retourne true si l'élément de fin de copie à été atteint Voir la méthode putUntil() Ce flag est effacé par un appel de la méthode take() , même si l'élément n'est pas "consommé" clear() efface aussi ce flag
Returns
True si l'élément de fin à été atteint
Definition at line 216 of file mdtBuffer.cpp.
The documentation for this class was generated from the following files:
src/mdtutils/mdtBuffer.h
src/mdtutils/mdtBuffer.cpp