Multi diag tools: mdtAbstractSqlTableController Class Reference
mdtAbstractSqlTableController Class Reference abstract
Base class for SQL table controllers.
#include <mdtAbstractSqlTableController.h>
Public Types
enum State_t {
Stopped = 0, Selecting, Visualizing, Reverting,
Editing, Submitting, Inserting, EditingNewRow,
RevertingNewRow, SubmittingNewRow, Removing
}
State of edit/view widget.
Public Slots
void submit ()
Submit data.
void revert ()
Revert current record from model.
void insert ()
Insert a new row to model.
void remove ()
Remove a row from model.
Signals
void mainWidgetEnableStateChanged (bool enabled)
Emitted when the entier widget enable state changes.
void childWidgetEnableStateChanged (bool enabled)
Emitted when the entier widget enable state changes for a child widget.
void submitEnabledStateChanged (bool enabled)
Emitted when submit() function goes enabled/disabled.
void revertEnabledStateChanged (bool enabled)
Emitted when revert() function goes enabled/disabled.
void insertEnabledStateChanged (bool enabled)
Emitted when insert() function goes enabled/disabled.
void removeEnabledStateChanged (bool enabled)
Emitted when remove() function goes enabled/disabled.
void selectTriggered ()
Emitted when select() or setFilter() was called.
void submitTriggered ()
Emitted when submit() was called.
void revertTriggered ()
Emitted when revert() was called.
void insertTriggered ()
Emitted when insert() was called.
void removeTriggered ()
Emitted when remove() was called.
void errorOccured ()
Emitted when a error occured.
void operationSucceed ()
Emitted when a operation succeed.
void dataEdited ()
Emitted when data was edited.
void stateEditingExited ()
Emitted when Editing state was exited.
void stateEditingNewRowExited ()
Emitted when Editing state was exited.
Public Member Functions
mdtAbstractSqlTableController (QObject *parent=0)
Constructor.
virtual ~mdtAbstractSqlTableController ()
Destructor.
void setMessageHandler (std::shared_ptr< mdtUiMessageHandler > handler)
Set message handler.
bool hasMessageHandler () const
Check if a message handler was allready set.
void setTableName (const QString &tableName, QSqlDatabase db, const QString &userFriendlyTableName=QString())
Set table name.
void setModel (std::shared_ptr< QSqlTableModel > m, const QString &userFriendlyTableName=QString())
Set table model.
void setCanWriteToDatabase (bool canWrite)
Set the canWriteToDatabase flag.
bool canWriteToDatabase () const
Set the canWriteToDatabase flag.
int fieldIndex (const QString &fieldName) const
Get index of field with fieldName.
void setHeaderData (const QString &fieldName, const QString &data)
Set a user friendly name for a column.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get header data of given section.
QVariant headerData (int column, int role=Qt::DisplayRole) const
Get header data of given column.
QVariant headerData (const QString &fieldName, int role=Qt::DisplayRole) const
Get header data of given field name.
template<typename T >
bool addChildController (const mdtSqlRelationInfo &relationInfo, QSqlDatabase db, const QString &userFriendlyChildTableName=QString())
Add a child controller.
template<typename T >
bool addChildController (const mdtSqlRelationInfo &relationInfo, const QString &userFriendlyChildTableName=QString())
Add a child controller.
template<typename T >
std::shared_ptr< T > childController (const QString &tableName)
Get a child controller.
bool select ()
Select data in main table.
bool setFilter (const QString &filter)
Set a filter on main table.
bool setFilter (const QString &fieldName, const QVariant &matchData)
Set a filter on main table.
bool setFilter (const QString &fieldName, const QList< QVariant > &matchDataList)
Set a filter on main table.
void clearFilter ()
Clear filter.
const std::shared_ptr
< QSqlTableModel > model () const
Get model (read only access)
std::shared_ptr< QSqlTableModel > model ()
Get model (write access)
QString tableName () const
Get (technical) table name.
void setUserFriendlyTableName (const QString &name)
Set user friendly table name.
QString userFriendlyTableName () const
Get user friendly table name.
void start ()
Start internal state machine.
void stop ()
Stop internal state machine.
State_t currentState () const
Get current state.
void addDataValidator (std::shared_ptr< mdtSqlDataValidator > validator, bool putAtTopPriority=false, bool setInternalMessageHandler=true)
Add a data validator.
void addColumnToSortOrder (const QString &fieldName, Qt::SortOrder order=Qt::AscendingOrder)
Add a column to columns sort order.
void clearColumnsSortOrder ()
Clear columns sort order.
void sort ()
Sort data.
bool setCurrentData (const QString &fieldName, const QVariant &data, bool submit=true)
Set current data for given field name.
bool setData (int row, const QString &fieldName, const QVariant &data, bool submit=true)
Set data for given row and field name.
bool setData (const QString &matchFieldName, const QVariant &matchData, const QString &dataFieldName, const QVariant &data, bool submit=true)
Set data for given match and field name.
bool setData (const QString &matchFieldName1, const QVariant &key1, const QString &matchFieldName2, const QVariant &key2, const QString &dataFieldName, const QVariant &data, bool submit=true)
Set data for given match and field name.
QVariant currentData (const QString &fieldName)
Get current data for given field name.
QVariant currentData (const QString &fieldName, bool &ok)
Get current data for given field name.
QString currentFormatedValue (const QString &fieldName)
Get formated current value for SQL query.
QString currentFormatedValue (const QString &fieldName, bool &ok)
Get formated current value for SQL query.
QVariant data (const QModelIndex &index)
Get data for given index.
QVariant data (const QModelIndex &index, bool &ok)
Get data for given index.
QVariant data (int row, int column)
Get data for given row and column.
QVariant data (int row, int column, bool &ok)
Get data for given row and column.
QVariant data (int row, const QString &fieldName)
Get data for given row and field name.
QVariant data (int row, const QString &fieldName, bool &ok)
Get data for given row and field name.
QVariant data (const QString &matchFieldName, const QVariant &matchData, const QString &dataFieldName, bool &ok)
Get data for given match and field name.
QVariant data (const QString &matchFieldName, const QVariant &matchData, const QString &dataFieldName)
Get data for given match and field name.
QVariant data (const QString &matchFieldName1, const QVariant &key1, const QString &matchFieldName2, const QVariant &key2, const QString &dataFieldName, bool &ok)
Get data for given match and field name.
QVariant data (const QString &matchFieldName1, const QVariant &key1, const QString &matchFieldName2, const QVariant &key2, const QString &dataFieldName)
Get data for given match and field name.
mdtSqlRecord record (int row, const QStringList &fieldNames)
Get a record that contains given field names for given row.
mdtSqlRecord record (int row, const QStringList &fieldNames, bool &ok)
Get a record that contains given field names for given row.
mdtSqlRecord record (const QString &matchFieldName, const QVariant &matchData, const QStringList &fieldNames, bool &ok)
Get a record for given match and that contains given field names.
mdtSqlRecord record (const QString &matchFieldName, const QVariant &matchData, const QStringList &fieldNames)
Get a record for given match and that contains given field names.
mdtSqlRecord currentRecord (const QStringList &fieldNames, bool &ok)
Get a record that contains given field names for current row.
mdtSqlRecord currentRecord (const QStringList &fieldNames)
Get a record that contains given field names for current row.
QList< QVariant > dataList (const QString &fieldName, bool fetchAll=true)
Get a list of data for given field name.
QList< QVariant > dataList (const QString &fieldName, bool &ok, bool fetchAll=true)
Get a list of data for given field name.
QString formatedValue (int row, const QString &fieldName)
Get formated value for SQL query.
QString formatedValue (int row, const QString &fieldName, bool &ok)
Get formated value for SQL query.
QString formatValue (const QString &fieldName, const QVariant &value)
Get formated value for SQL query.
QString formatValue (const QString &fieldName, const QVariant &value, bool &ok)
Get formated value for SQL query.
QString formatValue (const QSqlField &field)
Get formated value for SQL query.
int columnCount () const
Get column count.
int rowCount (bool fetchAll=true) const
Get row count.
bool setCurrentRow (int row)
Set current row.
bool setCurrentRow (const QString &fieldName, const QVariant &matchData)
Set current row.
int currentRow () const
Get current row.
void update ()
Update controllers with data for current row.
bool allDataAreSaved (bool checkAboutDirtyIndex=false)
Check if all data are saved.
mdtError lastError () const
Get last error.
bool submitAndWait ()
Submit and wait until success or failure.
bool removeAndWait ()
Remove and wait until success or failure.
Protected Slots
void onStateSelectingEntered ()
Activity after Selecting state entered.
virtual void onStateVisualizingEntered ()
Activity after Visualizing state entered.
virtual void onStateVisualizingExited ()
Activity after Visualizing state entered.
virtual void onStateEditingEntered ()
Activity after Editing state entered.
void onStateEditingExited ()
Activity after Editing state exited.
void onStateSubmittingEntered ()
Activity after Submitting state entered.
void onStateRevertingEntered ()
Activity after Reverting state entered.
virtual void onStateInsertingEntered ()
Activity after Inserting state entered.
virtual void onStateEditingNewRowEntered ()
Activity after EditingNewRow state entered.
void onStateEditingNewRowExited ()
Activity after Editing state exited.
void onStateSubmittingNewRowEntered ()
Activity after SubmittingNewRow state entered.
void onStateRevertingNewRowEntered ()
Activity after RevertingNewRow state entered.
void onStateRemovingEntered ()
Activity after Removing state entered.
Protected Member Functions
std::shared_ptr
< mdtUiMessageHandler > messageHandler ()
Get message handler.
std::shared_ptr
< mdtSortFilterProxyModel > proxyModel ()
Get internal proxy model.
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
virtual void modelSetEvent ()
Table model set event.
virtual void currentRowChangedEvent (int row)
Current row changed event.
virtual void insertDoneEvent (int row)
Insert done event.
bool setCurrentRowPv (int row)
Set current row - For internal use.
virtual bool submitToModel ()=0
Submit data to model.
bool submitToDatabase ()
Submit data from model to database.
virtual bool doRevert ()=0
Submit current row to model.
virtual bool doRemove ()=0
Submit new row to model.
Protected Attributes
mdtError pvLastError
Last error (for write access)
Detailed Description
Base class for SQL table controllers.
In MVC pattern, this class is the controller part for database GUI.
Todo:
Documnent correctly
When creating a GUI for database table edition, this class can be used as controller between your GUI and QSqlTableModel. To keep coherence of common operation, such as insert, remove, submit and remove, some signals are available:
insertEnabledStateChanged()
removeEnabledStateChanged()
submitEnabledStateChanged()
removeEnabledStateChanged()
This abstract class can not be used directly, but must be subclassed. Use existing one, or create your own if needed.
Typicall usage:
Make needed signal/slot connections with GUI actions
Set table with setTableName()
If needed, add child controllers with addChildController()
Start inetrnal state machine with start()
Load data with select()
Definition at line 80 of file mdtAbstractSqlTableController.h.
Member Enumeration Documentation
enum mdtAbstractSqlTableController::State_t
State of edit/view widget.
This state is set by internal state machine.
Enumerator
Stopped
Stopped state (internall state machine not running, see start())
Selecting
Selecting state
Visualizing
Visualizing state
Reverting
Reverting state
Editing
Editing state
Submitting
Submitting state
Inserting
Inserting state
EditingNewRow
Editing a new row
RevertingNewRow
RevertingNewRow state
SubmittingNewRow
SubmittingNewRow state
Removing
Removing state
Definition at line 90 of file mdtAbstractSqlTableController.h.
Constructor & Destructor Documentation
mdtAbstractSqlTableController::mdtAbstractSqlTableController (QObject * parent = 0)
Constructor.
Definition at line 36 of file mdtAbstractSqlTableController.cpp.
mdtAbstractSqlTableController::~mdtAbstractSqlTableController () virtual
Destructor.
Definition at line 45 of file mdtAbstractSqlTableController.cpp.
Member Function Documentation
template<typename T > bool mdtAbstractSqlTableController::addChildController (const mdtSqlRelationInfo & relationInfo, QSqlDatabase db, const QString & userFriendlyChildTableName = QString()) inline
Add a child controller.
Will create a controller of type T, needed relations (mdtSqlRelation objects) and add controller to childs.
Parameters
relationInfo Informations of relation between current controller's table (parent) and child controller's table (child) Note: parent table name is ignored.
db QSqlDatabase object to use
userFriendlyChildTableName User friendly table name for child controller.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 201 of file mdtAbstractSqlTableController.h.
template<typename T > bool mdtAbstractSqlTableController::addChildController (const mdtSqlRelationInfo & relationInfo, const QString & userFriendlyChildTableName = QString()) inline
Add a child controller.
Will create a controller of type T, needed relations (mdtSqlRelation objects) and add controller to childs.
Parameters
relationInfo Informations of relation between current controller's table (parent) and child controller's table (child) Note: parent table name is ignored.
userFriendlyChildTableName User friendly table name for child controller.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 220 of file mdtAbstractSqlTableController.h.
void mdtAbstractSqlTableController::addColumnToSortOrder (const QString & fieldName, Qt::SortOrder order = Qt::AscendingOrder)
Add a column to columns sort order.
Columns sort order is similar meaning than SQL ORDER BY clause.
Internally, mdtSortFilterProxyModel is used, witch provide a natural sort for strings.
For example, to sort columns in order "Id_PK", "FirstName", "LastName", all ascending, call:
clearColumnsSortOrder();
addColumnToSortOrder("Id_PK", Qt::AscendingOrder);
addColumnToSortOrder("FirstName", Qt::AscendingOrder);
addColumnToSortOrder("LastName", Qt::AscendingOrder);
Note: if given field not exists, it will simply be ignored.
Note: to apply sorting, call sort()
Precondition
Model must be set with setModel() before using this method.
Definition at line 330 of file mdtAbstractSqlTableController.cpp.
void mdtAbstractSqlTableController::addDataValidator (std::shared_ptr< mdtSqlDataValidator > validator, bool putAtTopPriority = false, bool setInternalMessageHandler = true)
Add a data validator.
Parameters
validator A instance of mdtSqlDataValidator or subclass.
putAtTopPriority If true, validator will be called before allready stored ones. (validators are put into a queue).
setInternalMessageHandler If true, message handler set with setMessageHandler() will be set to validator.
Precondition
validator must be a valid pointer.
Definition at line 316 of file mdtAbstractSqlTableController.cpp.
Referenced by mdtSqlDataWidgetController::mapFormWidgets().
bool mdtAbstractSqlTableController::allDataAreSaved (bool checkAboutDirtyIndex = false)
Check if all data are saved.
This will check state of current table controller and state of all assigned child controllers. If one of them is not in Visualizing, Selecting or Stopped state, some data are not saved.
If checkAboutDirtyIndex is true, current state of controllers are also checked, but in addition, each index for each cached row will be checked using QSqlTableModel::isDirty(). This is slower, but works also after data was edited with setData().
Returns
true if all data are saved, false if there are pending data.
Definition at line 812 of file mdtAbstractSqlTableController.cpp.
References currentRow(), currentState(), Selecting, Stopped, userFriendlyTableName(), Visualizing, and mdtUiMessageHandler::Warning.
Referenced by insert(), select(), setCurrentRow(), and setFilter().
bool mdtAbstractSqlTableController::beginTransaction () protected
Beginn manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 920 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtAbstractSqlTableController::canWriteToDatabase () const inline
Set the canWriteToDatabase flag.
See Also
setCanWriteToDatabase().
Definition at line 151 of file mdtAbstractSqlTableController.h.
template<typename T > std::shared_ptr<T> mdtAbstractSqlTableController::childController (const QString & tableName) inline
Get a child controller.
Can return a Null pointer if no controller is assigned to requested table, or it exists, but is not requested type T.
Definition at line 233 of file mdtAbstractSqlTableController.h.
References tableName().
void mdtAbstractSqlTableController::childWidgetEnableStateChanged (bool enabled) signal
Emitted when the entier widget enable state changes for a child widget.
Referenced by onStateVisualizingEntered(), and onStateVisualizingExited().
void mdtAbstractSqlTableController::clearColumnsSortOrder ()
Clear columns sort order.
See Also
addColumnToSortOrder()
Definition at line 335 of file mdtAbstractSqlTableController.cpp.
void mdtAbstractSqlTableController::clearFilter ()
Clear filter.
Definition at line 250 of file mdtAbstractSqlTableController.cpp.
References setFilter().
int mdtAbstractSqlTableController::columnCount () const inline
Get column count.
Definition at line 722 of file mdtAbstractSqlTableController.h.
Referenced by mdtSqlTableViewController::setDefaultColumnToSelect().
bool mdtAbstractSqlTableController::commitTransaction () protected
Commit manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 950 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
QVariant mdtAbstractSqlTableController::currentData (const QString & fieldName) inline
Get current data for given field name.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 445 of file mdtAbstractSqlTableController.h.
References currentRow(), and data().
QVariant mdtAbstractSqlTableController::currentData (const QString & fieldName, bool & ok) inline
Get current data for given field name.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 458 of file mdtAbstractSqlTableController.h.
References currentRow(), and data().
QString mdtAbstractSqlTableController::currentFormatedValue (const QString & fieldName) inline
Get formated current value for SQL query.
Definition at line 469 of file mdtAbstractSqlTableController.h.
QString mdtAbstractSqlTableController::currentFormatedValue (const QString & fieldName, bool & ok) inline
Get formated current value for SQL query.
Definition at line 478 of file mdtAbstractSqlTableController.h.
References currentRow(), and formatedValue().
mdtSqlRecord mdtAbstractSqlTableController::currentRecord (const QStringList & fieldNames, bool & ok) inline
Get a record that contains given field names for current row.
Definition at line 639 of file mdtAbstractSqlTableController.h.
References currentRow(), and record().
mdtSqlRecord mdtAbstractSqlTableController::currentRecord (const QStringList & fieldNames) inline
Get a record that contains given field names for current row.
Definition at line 647 of file mdtAbstractSqlTableController.h.
References currentRow(), and record().
int mdtAbstractSqlTableController::currentRow () const inline
Get current row.
Definition at line 755 of file mdtAbstractSqlTableController.h.
Referenced by allDataAreSaved(), currentData(), currentFormatedValue(), currentRecord(), onStateVisualizingEntered(), setCurrentData(), mdtSqlDataWidgetController::toNext(), and mdtSqlDataWidgetController::toPrevious().
virtual void mdtAbstractSqlTableController::currentRowChangedEvent (int row) inline protected virtual
Current row changed event.
Subclass can re-implement this method if some tasks should be done after current row changed.
Note: don't wory about child controllers or other things, they are handled in this base class.
Definition at line 880 of file mdtAbstractSqlTableController.h.
Referenced by setCurrentRowPv(), and update().
State_t mdtAbstractSqlTableController::currentState () const inline
Get current state.
Definition at line 347 of file mdtAbstractSqlTableController.h.
References mdtStateMachine::currentState(), and Stopped.
Referenced by mdtSqlDataWidgetController::addMapping(), allDataAreSaved(), and mdtSqlDataWidgetController::mapFormWidgets().
QVariant mdtAbstractSqlTableController::data (const QModelIndex & index) inline
Get data for given index.
Note: index is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 491 of file mdtAbstractSqlTableController.h.
Referenced by currentData(), data(), dataList(), and record().
QVariant mdtAbstractSqlTableController::data (const QModelIndex & index, bool & ok)
Get data for given index.
Note: index is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 459 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
QVariant mdtAbstractSqlTableController::data (int row, int column) inline
Get data for given row and column.
Note: row is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 514 of file mdtAbstractSqlTableController.h.
References data().
QVariant mdtAbstractSqlTableController::data (int row, int column, bool & ok) inline
Get data for given row and column.
Note: row is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 528 of file mdtAbstractSqlTableController.h.
References data().
QVariant mdtAbstractSqlTableController::data (int row, const QString & fieldName) inline
Get data for given row and field name.
Note: row is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 541 of file mdtAbstractSqlTableController.h.
References data().
QVariant mdtAbstractSqlTableController::data (int row, const QString & fieldName, bool & ok)
Get data for given row and field name.
Note: row is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 476 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), data(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
QVariant mdtAbstractSqlTableController::data (const QString & matchFieldName, const QVariant & matchData, const QString & dataFieldName, bool & ok)
Get data for given match and field name.
Parameters
matchFieldName Field name in witch matchData must be searched
matchData Data that must match in matchFieldName
dataFieldName Field name in witch data must be returned
Definition at line 494 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), data(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
QVariant mdtAbstractSqlTableController::data (const QString & matchFieldName, const QVariant & matchData, const QString & dataFieldName) inline
Get data for given match and field name.
Parameters
matchFieldName Field name in witch matchData must be searched
matchData Data that must match in matchFieldName
dataFieldName Field name in witch data must be returned
Definition at line 571 of file mdtAbstractSqlTableController.h.
References data().
QVariant mdtAbstractSqlTableController::data (const QString & matchFieldName1, const QVariant & key1, const QString & matchFieldName2, const QVariant & key2, const QString & dataFieldName, bool & ok)
Get data for given match and field name.
Parameters
matchFieldName1 Field name in witch key1 must be searched
key1 Data that must match in matchFieldName1
matchFieldName2 Field name in witch key2 must be searched
key2 Data that must match in matchFieldName2
dataFieldName Field name in witch data must be returned
Definition at line 530 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), data(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
QVariant mdtAbstractSqlTableController::data (const QString & matchFieldName1, const QVariant & key1, const QString & matchFieldName2, const QVariant & key2, const QString & dataFieldName) inline
Get data for given match and field name.
Parameters
matchFieldName1 Field name in witch key1 must be searched
key1 Data that must match in matchFieldName1
matchFieldName2 Field name in witch key2 must be searched
key2 Data that must match in matchFieldName2
dataFieldName Field name in witch data must be returned
Definition at line 596 of file mdtAbstractSqlTableController.h.
References data().
void mdtAbstractSqlTableController::dataEdited () signal
Emitted when data was edited.
Referenced by mdtSqlDataWidgetController::addMapping(), and mdtSqlTableViewController::setTableView().
QList<QVariant> mdtAbstractSqlTableController::dataList (const QString & fieldName, bool fetchAll = true) inline
Get a list of data for given field name.
If fetchAll is true, all available data will be fetched from database (regarding applied filter), else only cached data are returned (see QSqlQueryModel::fetchMore() for details).
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 661 of file mdtAbstractSqlTableController.h.
QList< QVariant > mdtAbstractSqlTableController::dataList (const QString & fieldName, bool & ok, bool fetchAll = true)
Get a list of data for given field name.
If fetchAll is true, all available data will be fetched from database (regarding applied filter), else only cached data are returned (see QSqlQueryModel::fetchMore() for details).
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 623 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), data(), mdtError::Error, MDT_ERROR_SET_SRC, proxyModel(), pvLastError, and mdtError::setError().
virtual bool mdtAbstractSqlTableController::doRemove () protected pure virtual
Submit new row to model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
Note: current row will be updated after successfull call of this method, calling then currentRowChangedEvent().
Remove current row from model
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
Referenced by onStateRemovingEntered().
virtual bool mdtAbstractSqlTableController::doRevert () protected pure virtual
Submit current row to model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
Note: current row will be updated after successfull call of this method, calling then currentRowChangedEvent().
Revert current row from model
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
Depending on subclass choosen EditStrategy, this method has potentially no effect.
Referenced by onStateRevertingEntered().
void mdtAbstractSqlTableController::errorOccured () signal
Emitted when a error occured.
Referenced by onStateInsertingEntered(), onStateRevertingEntered(), onStateRevertingNewRowEntered(), onStateSubmittingEntered(), and onStateSubmittingNewRowEntered().
int mdtAbstractSqlTableController::fieldIndex (const QString & fieldName) const
Get index of field with fieldName.
Returns a value < 0 if fieldName was not found.
Definition at line 97 of file mdtAbstractSqlTableController.cpp.
Referenced by mdtSqlDataWidgetController::addMapping(), headerData(), mdtSqlTableViewController::setDefaultColumnToSelect(), and setHeaderData().
QString mdtAbstractSqlTableController::formatedValue (int row, const QString & fieldName) inline
Get formated value for SQL query.
Definition at line 680 of file mdtAbstractSqlTableController.h.
Referenced by currentFormatedValue().
QString mdtAbstractSqlTableController::formatedValue (int row, const QString & fieldName, bool & ok)
Get formated value for SQL query.
Will add delimiter to value, regarding field type.
Definition at line 660 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, formatValue(), MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
QString mdtAbstractSqlTableController::formatValue (const QString & fieldName, const QVariant & value) inline
Get formated value for SQL query.
Will add delimiter to value, regarding field type.
Definition at line 699 of file mdtAbstractSqlTableController.h.
Referenced by formatedValue(), formatValue(), and setFilter().
QString mdtAbstractSqlTableController::formatValue (const QString & fieldName, const QVariant & value, bool & ok)
Get formated value for SQL query.
Will add delimiter to value, regarding field type.
Definition at line 687 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, formatValue(), MDT_ERROR_SET_SRC, pvLastError, and mdtError::setError().
QString mdtAbstractSqlTableController::formatValue (const QSqlField & field)
Get formated value for SQL query.
Will add delimiter to value, regarding field type.
Definition at line 708 of file mdtAbstractSqlTableController.cpp.
bool mdtAbstractSqlTableController::hasMessageHandler () const
Check if a message handler was allready set.
Definition at line 62 of file mdtAbstractSqlTableController.cpp.
QVariant mdtAbstractSqlTableController::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const inline
Get header data of given section.
Definition at line 170 of file mdtAbstractSqlTableController.h.
Referenced by headerData().
QVariant mdtAbstractSqlTableController::headerData (int column, int role = Qt::DisplayRole) const inline
Get header data of given column.
Definition at line 177 of file mdtAbstractSqlTableController.h.
QVariant mdtAbstractSqlTableController::headerData (const QString & fieldName, int role = Qt::DisplayRole) const
Get header data of given field name.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 118 of file mdtAbstractSqlTableController.cpp.
References fieldIndex(), and headerData().
void mdtAbstractSqlTableController::insert () slot
Insert a new row to model.
Internally, insertTriggered() signal will be emitted.
Definition at line 907 of file mdtAbstractSqlTableController.cpp.
References allDataAreSaved(), and insertTriggered().
virtual void mdtAbstractSqlTableController::insertDoneEvent (int row) inline protected virtual
Insert done event.
Subclass can re-implement this method if some tasks should be done after current row changed.
Note: don't wory about child controllers or other things, they are handled in this base class.
Parameters
row Row (index) that was freshly insert. Note: row refers to proxyModel.
Definition at line 892 of file mdtAbstractSqlTableController.h.
Referenced by onStateInsertingEntered().
void mdtAbstractSqlTableController::insertEnabledStateChanged (bool enabled) signal
Emitted when insert() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by onStateVisualizingEntered(), and onStateVisualizingExited().
void mdtAbstractSqlTableController::insertTriggered () signal
Emitted when insert() was called.
Referenced by insert().
mdtError mdtAbstractSqlTableController::lastError () const inline
Get last error.
Definition at line 780 of file mdtAbstractSqlTableController.h.
References pvLastError.
void mdtAbstractSqlTableController::mainWidgetEnableStateChanged (bool enabled) signal
Emitted when the entier widget enable state changes.
Referenced by start(), and stop().
std::shared_ptr<mdtUiMessageHandler> mdtAbstractSqlTableController::messageHandler () inline protected
Get message handler.
Can return a Null pointer if no message handler was set (witch is acceptable case).
Definition at line 841 of file mdtAbstractSqlTableController.h.
Referenced by start(), and submitToDatabase().
const std::shared_ptr<QSqlTableModel> mdtAbstractSqlTableController::model () const inline
Get model (read only access)
Definition at line 313 of file mdtAbstractSqlTableController.h.
Referenced by mdtSqlDataWidgetController::addMapping(), mdtSqlTableViewController::currentSelection(), mdtSqlTableViewController::firstVisibleColumnIndex(), mdtSqlDataWidgetController::mapFormWidgets(), mdtSqlTableViewController::setDefaultColumnToSelect(), setHeaderData(), sort(), and submitToDatabase().
std::shared_ptr<QSqlTableModel> mdtAbstractSqlTableController::model () inline
Get model (write access)
Todo:
If not needed, make it protected and adapt tests
Definition at line 319 of file mdtAbstractSqlTableController.h.
virtual void mdtAbstractSqlTableController::modelSetEvent () inline protected virtual
Table model set event.
Cann be re-implemented in subclass if some things must be done once a table model was set.
Definition at line 870 of file mdtAbstractSqlTableController.h.
Referenced by setModel().
void mdtAbstractSqlTableController::onStateEditingEntered () protected virtual slot
Activity after Editing state entered.
This slot is called from internal state machine and should not be used directly.
Definition at line 1039 of file mdtAbstractSqlTableController.cpp.
References revertEnabledStateChanged(), and submitEnabledStateChanged().
void mdtAbstractSqlTableController::onStateEditingExited () protected slot
Activity after Editing state exited.
This slot is called from internal state machine and should not be used directly.
Definition at line 1045 of file mdtAbstractSqlTableController.cpp.
References revertEnabledStateChanged(), stateEditingExited(), and submitEnabledStateChanged().
void mdtAbstractSqlTableController::onStateEditingNewRowEntered () protected virtual slot
Activity after EditingNewRow state entered.
This slot is called from internal state machine and should not be used directly.
Definition at line 1138 of file mdtAbstractSqlTableController.cpp.
References revertEnabledStateChanged(), and submitEnabledStateChanged().
void mdtAbstractSqlTableController::onStateEditingNewRowExited () protected slot
Activity after Editing state exited.
This slot is called from internal state machine and should not be used directly.
Definition at line 1144 of file mdtAbstractSqlTableController.cpp.
References revertEnabledStateChanged(), stateEditingNewRowExited(), and submitEnabledStateChanged().
void mdtAbstractSqlTableController::onStateInsertingEntered () protected virtual slot
Activity after Inserting state entered.
This slot is called from internal state machine and should not be used directly.
Definition at line 1116 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, errorOccured(), insertDoneEvent(), MDT_ERROR_SET_SRC, operationSucceed(), pvLastError, rowCount(), mdtError::setError(), and userFriendlyTableName().
void mdtAbstractSqlTableController::onStateRemovingEntered () protected slot
Activity after Removing state entered.
Will call doRemove().
This slot is called from internal state machine and should not be used directly.
Definition at line 1230 of file mdtAbstractSqlTableController.cpp.
References doRemove(), operationSucceed(), rowCount(), setCurrentRowPv(), and mdtUiMessageHandler::Warning.
void mdtAbstractSqlTableController::onStateRevertingEntered () protected slot
Activity after Reverting state entered.
Will call doRevert().
This slot is called from internal state machine and should not be used directly.
Definition at line 1090 of file mdtAbstractSqlTableController.cpp.
References doRevert(), errorOccured(), operationSucceed(), and mdtUiMessageHandler::Warning.
void mdtAbstractSqlTableController::onStateRevertingNewRowEntered () protected slot
Activity after RevertingNewRow state entered.
Will call doRevertNewRow().
This slot is called from internal state machine and should not be used directly.
Definition at line 1192 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, errorOccured(), MDT_ERROR_SET_SRC, operationSucceed(), pvLastError, setCurrentRowPv(), mdtError::setError(), userFriendlyTableName(), and mdtUiMessageHandler::Warning.
void mdtAbstractSqlTableController::onStateSelectingEntered () protected slot
Activity after Selecting state entered.
This slot is called from internal state machine and should not be used directly.
Definition at line 1014 of file mdtAbstractSqlTableController.cpp.
void mdtAbstractSqlTableController::onStateSubmittingEntered () protected slot
Activity after Submitting state entered.
Will call checkBeforeSubmit() and, on success, doSubmit().
This slot is called from internal state machine and should not be used directly.
Definition at line 1052 of file mdtAbstractSqlTableController.cpp.
References errorOccured(), operationSucceed(), setCurrentRowPv(), submitToDatabase(), and submitToModel().
void mdtAbstractSqlTableController::onStateSubmittingNewRowEntered () protected slot
Activity after SubmittingNewRow state entered.
Will call checkBeforeSubmit() and, on success, doSubmitNewRow().
This slot is called from internal state machine and should not be used directly.
Definition at line 1151 of file mdtAbstractSqlTableController.cpp.
References errorOccured(), operationSucceed(), setCurrentRowPv(), submitToDatabase(), and submitToModel().
void mdtAbstractSqlTableController::onStateVisualizingEntered () protected virtual slot
Activity after Visualizing state entered.
This slot is called from internal state machine and should not be used directly.
Definition at line 1018 of file mdtAbstractSqlTableController.cpp.
References childWidgetEnableStateChanged(), currentRow(), insertEnabledStateChanged(), removeEnabledStateChanged(), revertEnabledStateChanged(), and submitEnabledStateChanged().
void mdtAbstractSqlTableController::onStateVisualizingExited () protected virtual slot
Activity after Visualizing state entered.
This slot is called from internal state machine and should not be used directly.
Definition at line 1032 of file mdtAbstractSqlTableController.cpp.
References childWidgetEnableStateChanged(), insertEnabledStateChanged(), and removeEnabledStateChanged().
void mdtAbstractSqlTableController::operationSucceed () signal
Emitted when a operation succeed.
Referenced by onStateInsertingEntered(), onStateRemovingEntered(), onStateRevertingEntered(), onStateRevertingNewRowEntered(), onStateSubmittingEntered(), onStateSubmittingNewRowEntered(), select(), and setFilter().
std::shared_ptr<mdtSortFilterProxyModel> mdtAbstractSqlTableController::proxyModel () inline protected
Get internal proxy model.
Definition at line 845 of file mdtAbstractSqlTableController.h.
Referenced by mdtSqlTableViewController::currentSelection(), dataList(), mdtSqlDataWidgetController::mdtSqlDataWidgetController(), mdtSqlTableViewController::setTableView(), and sort().
mdtSqlRecord mdtAbstractSqlTableController::record (int row, const QStringList & fieldNames) inline
Get a record that contains given field names for given row.
Definition at line 605 of file mdtAbstractSqlTableController.h.
Referenced by currentRecord(), and record().
mdtSqlRecord mdtAbstractSqlTableController::record (int row, const QStringList & fieldNames, bool & ok)
Get a record that contains given field names for given row.
Definition at line 574 of file mdtAbstractSqlTableController.cpp.
References mdtSqlRecord::addField(), data(), mdtSqlRecord::lastError(), pvLastError, and mdtSqlRecord::setValue().
mdtSqlRecord mdtAbstractSqlTableController::record (const QString & matchFieldName, const QVariant & matchData, const QStringList & fieldNames, bool & ok)
Get a record for given match and that contains given field names.
Parameters
matchFieldName Field name in witch matchData must be searched
matchData Data that must match in matchFieldName
fieldNames List of fields that must be contained in returned record
Definition at line 597 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, record(), and mdtError::setError().
mdtSqlRecord mdtAbstractSqlTableController::record (const QString & matchFieldName, const QVariant & matchData, const QStringList & fieldNames) inline
Get a record for given match and that contains given field names.
Parameters
matchFieldName Field name in witch matchData must be searched
matchData Data that must match in matchFieldName
fieldNames List of fields that must be contained in returned record
Definition at line 630 of file mdtAbstractSqlTableController.h.
References record().
void mdtAbstractSqlTableController::remove () slot
Remove a row from model.
Internally, removeTriggered() signal will be emitted.
Definition at line 915 of file mdtAbstractSqlTableController.cpp.
References removeTriggered().
bool mdtAbstractSqlTableController::removeAndWait ()
Remove and wait until success or failure.
Note: will not freeze Qt's event loop.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 882 of file mdtAbstractSqlTableController.cpp.
References mdtError::clear(), mdtError::level(), mdtError::NoError, pvLastError, and removeTriggered().
void mdtAbstractSqlTableController::removeEnabledStateChanged (bool enabled) signal
Emitted when remove() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by onStateVisualizingEntered(), and onStateVisualizingExited().
void mdtAbstractSqlTableController::removeTriggered () signal
Emitted when remove() was called.
Referenced by remove(), and removeAndWait().
void mdtAbstractSqlTableController::revert () slot
Revert current record from model.
Depending on subclass choosen EditStrategy, this method has potentially no effect.
Internally, revertTriggered() signal will be emitted.
Definition at line 902 of file mdtAbstractSqlTableController.cpp.
References revertTriggered().
void mdtAbstractSqlTableController::revertEnabledStateChanged (bool enabled) signal
Emitted when revert() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by onStateEditingEntered(), onStateEditingExited(), onStateEditingNewRowEntered(), onStateEditingNewRowExited(), and onStateVisualizingEntered().
void mdtAbstractSqlTableController::revertTriggered () signal
Emitted when revert() was called.
Referenced by revert().
bool mdtAbstractSqlTableController::rollbackTransaction () protected
Rollback manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 935 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
int mdtAbstractSqlTableController::rowCount (bool fetchAll = true) const
Get row count.
Parameters
fetchAll If true, all rows will be fetched in database (see QSqlTableModel::fetchMore())
Definition at line 739 of file mdtAbstractSqlTableController.cpp.
Referenced by onStateInsertingEntered(), onStateRemovingEntered(), sort(), and mdtSqlDataWidgetController::toLast().
bool mdtAbstractSqlTableController::select ()
Select data in main table.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Internal state machine must run (see start()).
Definition at line 125 of file mdtAbstractSqlTableController.cpp.
References allDataAreSaved(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, operationSucceed(), pvLastError, Selecting, selectTriggered(), setCurrentRowPv(), mdtError::setError(), mdtError::setSystemError(), sort(), Visualizing, and mdtStateMachine::waitOnState().
void mdtAbstractSqlTableController::selectTriggered () signal
Emitted when select() or setFilter() was called.
Referenced by select(), and setFilter().
void mdtAbstractSqlTableController::setCanWriteToDatabase (bool canWrite)
Set the canWriteToDatabase flag.
If this flag is true (the default), calling submit will send data to database (see QSqlTableModel::submitAll() for details). For some cases, typically when working on a view, it's not possible to store data to DB by a default method. A way to deal with this is to only cache data to model, and save data to each corresponding tables in a manual way. For such usage, set this flag false.
Definition at line 92 of file mdtAbstractSqlTableController.cpp.
bool mdtAbstractSqlTableController::setCurrentData (const QString & fieldName, const QVariant & data, bool submit = true)
Set current data for given field name.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 360 of file mdtAbstractSqlTableController.cpp.
References currentRow(), and setData().
bool mdtAbstractSqlTableController::setCurrentRow (int row)
Set current row.
If not all data are saved for current row, this method will return false. If row is > model's cached rowCount-1, data will be fetched in database. If request row could not be found, false is returned.
Parameters
row Row to witch to go. Must be in range [-1;rowCount()-1] Note: row is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 755 of file mdtAbstractSqlTableController.cpp.
References allDataAreSaved(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, setCurrentRowPv(), mdtError::setError(), and userFriendlyTableName().
Referenced by setCurrentRow(), mdtSqlDataWidgetController::toFirst(), mdtSqlDataWidgetController::toLast(), mdtSqlDataWidgetController::toNext(), and mdtSqlDataWidgetController::toPrevious().
bool mdtAbstractSqlTableController::setCurrentRow (const QString & fieldName, const QVariant & matchData)
Set current row.
Will search the first record that contains match data for given field name.
See Also
setCurrentRow(int).
Definition at line 779 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, setCurrentRow(), and mdtError::setError().
bool mdtAbstractSqlTableController::setCurrentRowPv (int row) protected
Set current row - For internal use.
If row is > model's cached rowCount-1, data will be fetched in database. If request row could not be found, false is returned.
Will call currentRowChangedEvent() , but will not update child controllers.
Parameters
row Row to witch to go. Must be in range [-1;rowCount()-1]
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 965 of file mdtAbstractSqlTableController.cpp.
References currentRowChangedEvent().
Referenced by onStateRemovingEntered(), onStateRevertingNewRowEntered(), onStateSubmittingEntered(), onStateSubmittingNewRowEntered(), select(), setCurrentRow(), and setFilter().
bool mdtAbstractSqlTableController::setData (int row, const QString & fieldName, const QVariant & data, bool submit = true)
Set data for given row and field name.
Note: row is relative to sorted data model (proxyModel), not underlaying QSqlTableModel.
Note: if submit is true, but canWriteToDatabase flag is false, submit flag is silently ignored.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 367 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and submitToDatabase().
Referenced by setCurrentData(), and setData().
bool mdtAbstractSqlTableController::setData (const QString & matchFieldName, const QVariant & matchData, const QString & dataFieldName, const QVariant & data, bool submit = true)
Set data for given match and field name.
Parameters
matchFieldName Field name in witch matchData must be searched
matchData Data that must match in matchFieldName
dataFieldName Field name in witch data must be set
data Data to set
submit If true, data will be submitted to database, else it will be cached only in model.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 402 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, setData(), and mdtError::setError().
bool mdtAbstractSqlTableController::setData (const QString & matchFieldName1, const QVariant & key1, const QString & matchFieldName2, const QVariant & key2, const QString & dataFieldName, const QVariant & data, bool submit = true)
Set data for given match and field name.
Parameters
matchFieldName1 Field name in witch key1 must be searched
key1 Data that must match in matchFieldName1
matchFieldName2 Field name in witch key2 must be searched
key2 Data that must match in matchFieldName2
dataFieldName Field name in witch data must be set
data Data to set
submit If true, data will be submitted to database, else it will be cached only in model.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 426 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, setData(), and mdtError::setError().
bool mdtAbstractSqlTableController::setFilter (const QString & filter)
Set a filter on main table.
Set filter based on SQL query WHERE part, without the WHERE keyword (f.ex. Id_PK = 15)
Note: if internal controller's model is allready populated with data, i.e. select() was called before, filter is applied directly, else, select must be called explicitly after setMainTableFilter() (this is the same behaviour as QSqlTableModel).
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Internal state machine must run (see start()).
Definition at line 170 of file mdtAbstractSqlTableController.cpp.
References allDataAreSaved(), operationSucceed(), Selecting, selectTriggered(), setCurrentRowPv(), Visualizing, and mdtStateMachine::waitOnState().
Referenced by clearFilter(), and setFilter().
bool mdtAbstractSqlTableController::setFilter (const QString & fieldName, const QVariant & matchData)
Set a filter on main table.
Parameters
fieldName Field that must match data
matchData Match data
Internally, a SQL statement is generated linke: fieldName = matchData
Note: if internal controller's model is allready populated with data, i.e. select() was called before, filter is applied directly, else, select must be called explicitly after setMainTableFilter() (this is the same behaviour as QSqlTableModel).
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Internal state machine must run (see start()).
Definition at line 203 of file mdtAbstractSqlTableController.cpp.
References formatValue(), and setFilter().
bool mdtAbstractSqlTableController::setFilter (const QString & fieldName, const QList< QVariant > & matchDataList)
Set a filter on main table.
Parameters
fieldName Field that must match data
matchDataList A list of match data
Internally, a SQL statement is generated linke: fieldName IN (matchData[0], matchData[1], ...)
Note: if internal controller's model is allready populated with data, i.e. select() was called before, filter is applied directly, else, select must be called explicitly after setMainTableFilter() (this is the same behaviour as QSqlTableModel).
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Internal state machine must run (see start()).
Definition at line 219 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, formatValue(), MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and setFilter().
void mdtAbstractSqlTableController::setHeaderData (const QString & fieldName, const QString & data)
Set a user friendly name for a column.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 105 of file mdtAbstractSqlTableController.cpp.
References fieldIndex(), and model().
void mdtAbstractSqlTableController::setMessageHandler (std::shared_ptr< mdtUiMessageHandler > handler)
Set message handler.
Will also set this message handler to each contained data validator (see addDataValidator()).
Definition at line 49 of file mdtAbstractSqlTableController.cpp.
void mdtAbstractSqlTableController::setModel (std::shared_ptr< QSqlTableModel > m, const QString & userFriendlyTableName = QString())
Set table model.
Will replace internal model if allready set.
Definition at line 78 of file mdtAbstractSqlTableController.cpp.
References modelSetEvent(), and userFriendlyTableName().
Referenced by setTableName().
void mdtAbstractSqlTableController::setTableName (const QString & tableName, QSqlDatabase db, const QString & userFriendlyTableName = QString())
Set table name.
Will replace internal model if allready set.
Definition at line 71 of file mdtAbstractSqlTableController.cpp.
References setModel().
void mdtAbstractSqlTableController::setUserFriendlyTableName (const QString & name) inline
Set user friendly table name.
Definition at line 327 of file mdtAbstractSqlTableController.h.
void mdtAbstractSqlTableController::sort ()
Sort data.
See Also
addColumnToSortOrder()
Definition at line 340 of file mdtAbstractSqlTableController.cpp.
References model(), proxyModel(), rowCount(), and tableName().
Referenced by select().
void mdtAbstractSqlTableController::start ()
Start internal state machine.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 266 of file mdtAbstractSqlTableController.cpp.
References mainWidgetEnableStateChanged(), messageHandler(), pvLastError, mdtStateMachine::start(), and stop().
void mdtAbstractSqlTableController::stateEditingExited () signal
Emitted when Editing state was exited.
Referenced by onStateEditingExited().
void mdtAbstractSqlTableController::stateEditingNewRowExited () signal
Emitted when Editing state was exited.
Referenced by onStateEditingNewRowExited().
void mdtAbstractSqlTableController::stop ()
Stop internal state machine.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 297 of file mdtAbstractSqlTableController.cpp.
References mainWidgetEnableStateChanged(), and mdtStateMachine::stop().
Referenced by start().
void mdtAbstractSqlTableController::submit () slot
Submit data.
If canWriteToDatabase flag is true, data will be stored to database, else they will only be keeped cached in model.
Internally, submitTriggered() signal will be emitted.
Definition at line 897 of file mdtAbstractSqlTableController.cpp.
References submitTriggered().
bool mdtAbstractSqlTableController::submitAndWait ()
Submit and wait until success or failure.
Note: will not freeze Qt's event loop.
Precondition
Table model must be set with setModel() or setTableName() begore calling this method.
Definition at line 867 of file mdtAbstractSqlTableController.cpp.
References mdtError::clear(), mdtError::level(), mdtError::NoError, pvLastError, and submitTriggered().
void mdtAbstractSqlTableController::submitEnabledStateChanged (bool enabled) signal
Emitted when submit() function goes enabled/disabled.
This is usefull to keep GUI control coherent. For example, this is used in mdtSqlWindow to enable/disable actions.
Referenced by onStateEditingEntered(), onStateEditingExited(), onStateEditingNewRowEntered(), onStateEditingNewRowExited(), and onStateVisualizingEntered().
bool mdtAbstractSqlTableController::submitToDatabase () protected
Submit data from model to database.
Definition at line 992 of file mdtAbstractSqlTableController.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, messageHandler(), model(), pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by onStateSubmittingEntered(), onStateSubmittingNewRowEntered(), and setData().
virtual bool mdtAbstractSqlTableController::submitToModel () protected pure virtual
Submit data to model.
Subclass must implement this method. On problem, subclass should explain what goes wrong to the user and return false.
Note: current row will be updated after successfull call of this method, calling then currentRowChangedEvent(), so subclass does not have to worry about this.
Referenced by onStateSubmittingEntered(), and onStateSubmittingNewRowEntered().
void mdtAbstractSqlTableController::submitTriggered () signal
Emitted when submit() was called.
Referenced by submit(), and submitAndWait().
QString mdtAbstractSqlTableController::tableName () const
Get (technical) table name.
Definition at line 258 of file mdtAbstractSqlTableController.cpp.
Referenced by mdtSqlDataWidgetController::addMapping(), childController(), mdtSqlDataWidgetController::mapFormWidgets(), and sort().
void mdtAbstractSqlTableController::update ()
Update controllers with data for current row.
Precondition
Table model must be set with setModel() or setTableName() before calling this method.
Definition at line 804 of file mdtAbstractSqlTableController.cpp.
References currentRowChangedEvent().
QString mdtAbstractSqlTableController::userFriendlyTableName () const inline
Get user friendly table name.
Definition at line 331 of file mdtAbstractSqlTableController.h.
Referenced by allDataAreSaved(), onStateInsertingEntered(), onStateRevertingNewRowEntered(), setCurrentRow(), and setModel().
Member Data Documentation
mdtError mdtAbstractSqlTableController::pvLastError protected
Last error (for write access)
Definition at line 835 of file mdtAbstractSqlTableController.h.
Referenced by mdtSqlDataWidgetController::addMapping(), beginTransaction(), commitTransaction(), data(), dataList(), formatedValue(), formatValue(), lastError(), mdtSqlDataWidgetController::mapFormWidgets(), onStateInsertingEntered(), onStateRevertingNewRowEntered(), record(), removeAndWait(), rollbackTransaction(), select(), setCurrentRow(), setData(), setFilter(), start(), submitAndWait(), and submitToDatabase().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtAbstractSqlTableController.h
src/mdtdatabase/mdtAbstractSqlTableController.cpp