Multi diag tools: mdtDeviceU3606A Class Reference
mdtDeviceU3606A Class Reference
Representation of a Agilent U3606A.
#include <mdtDeviceU3606A.h>
Public Types
enum MeasureType_t {
MeasureType_t::Unknown, MeasureType_t::VoltageDc, MeasureType_t::VoltageAc, MeasureType_t::CurrentDc,
MeasureType_t::CurrentAc, MeasureType_t::Resistance, MeasureType_t::Continuity, MeasureType_t::Lresistance,
MeasureType_t::Capacitance, MeasureType_t::Diode, MeasureType_t::Frequency, MeasureType_t::Pwidth,
MeasureType_t::Dcycle
}
Measure type.
enum Range_t {
Range_t::Auto = -10, Range_t::Min, Range_t::Max, Range_t::Range20m = 1,
Range_t::Range100m, Range_t::Range1, Range_t::Range10, Range_t::Range100,
Range_t::Range1k, Range_t::Range10k, Range_t::Range100k, Range_t::Range1M,
Range_t::Range10M, Range_t::Range100M
}
Range for measure.
enum Resolution_t { Resolution_t::Min, Resolution_t::Max }
Resolution.
enum SourceRange_t { SourceRange_t::S1_30V1A, SourceRange_t::S2_8V3A }
Range of source subsystem.
Public Types inherited from mdtDevice
enum State_t { State_t::Disconnected, State_t::Connecting, State_t::Ready, State_t::Error }
State of device.
Public Member Functions
mdtDeviceU3606A (QObject *parent=0)
Constructor.
~mdtDeviceU3606A ()
Destructor.
bool connectToDevice (const QString &serialNumber, const QString &alias=QString())
Connect to device.
bool setupVoltageDcMeasure (Range_t range, Resolution_t resolution)
Setup DC voltage measure.
bool setupResistanceMeasure (Range_t range, Resolution_t resolution)
Setup resistance measure.
bool setupLowResistanceMeasure (Range_t range, Resolution_t resolution)
Setup low resistance measure (4 wires)
MeasureType_t getMeasureConfiguration ()
Get the measure configuration.
mdtValueDouble getMeasureValue (int timeout=30000)
Get measure value.
bool setOutputState (bool state)
Set source output state (On/Off)
bool setSourceRange (SourceRange_t range)
Set source range.
bool setSourceVoltageLimit (double v)
Set source voltage limit.
bool setSourceCurrent (double x)
Set source current.
Public Member Functions inherited from mdtDeviceScpi
mdtDeviceScpi (QObject *parent=0)
Construct a SCPI device.
virtual ~mdtDeviceScpi ()
Destructor.
bool connectToDevice ()
Connect to a USBTMC device.
bool connectToDevice (uint16_t idVendor, uint16_t idProduct, const QString &serialNumber, const QString &alias=QString())
Connect to a USBTMC device.
bool sendCommand (const QByteArray &command, int timeout=30000)
Send a command to device.
QByteArray sendQuery (const QByteArray &query, int timeout=30000)
Send a query to device.
mdtError getDeviceError (const QString &errorText=QString())
Get device error.
bool waitOperationComplete (int timeout, int interval)
Send a command to device.
Public Member Functions inherited from mdtDevice
mdtDevice (QObject *parent=0)
Construct a device object.
virtual ~mdtDevice ()
Destructor.
void setDeviceAddress (const mdtDeviceAddress &address, const QString &alias=QString())
Set device address.
mdtDeviceAddress deviceAddress () const
Get device address.
QString alias () const
Get device alias.
void disconnectFromDevice ()
Disconnect from device.
void setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
virtual bool isReady ()
Check if device is ready.
void start (int queryInterval)
Start periodic device querying.
void stop ()
Stop periodic device querying.
void wait (int t)
Wait some time without breaking main event loop.
mdtError lastError () const
Get last error.
State_t currentState () const
Get current state.
Additional Inherited Members
Public Slots inherited from mdtDevice
void runQueries ()
Queries to send periodically.
Signals inherited from mdtDevice
void stateChanged (State_t state)
Emitted when state has changed.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
Protected Member Functions inherited from mdtDeviceScpi
void disconnectFromDeviceEvent ()
Close port.
void deviceAddressChangedEvent (const mdtDeviceAddress &address)
Update name in port.
Protected Member Functions inherited from mdtDevice
QString deviceIdString () const
Get device identification string.
virtual bool queriesSequence ()
Sequence of queries to send periodically.
void setCurrentState (State_t state)
Set current state.
virtual void stateChangedEvent (State_t newState)
Called when current state has changed.
Protected Attributes inherited from mdtDevice
mdtError pvLastError
Last error object.
Detailed Description
Representation of a Agilent U3606A.
Definition at line 29 of file mdtDeviceU3606A.h.
Member Enumeration Documentation
enum mdtDeviceU3606A::MeasureType_t strong
Measure type.
Enumerator
Unknown
Unknown measure type
VoltageDc
Measure type DC voltage
VoltageAc
Measure type AC voltage
CurrentDc
Measure type DC current
CurrentAc
Measure type AC current
Resistance
Measure type resistance
Continuity
Measure type continuity
Lresistance
Measure type low value reistance
Capacitance
Measure type capacitance
Diode
Measure type diode
Frequency
Measure type frequency
Pwidth
Measure type pulse width
Dcycle
Measure type duty cycle
Definition at line 37 of file mdtDeviceU3606A.h.
enum mdtDeviceU3606A::Range_t strong
Range for measure.
Enumerator
Auto
AUTO range
Min
MIN range
Max
MAX range
Range20m
20 milli range
Range100m
100 milli range
Range1
1 range
Range10
10 range
Range100
100 range
Range1k
1k range
Range10k
10k range
Range100k
100k range
Range1M
1M range
Range10M
10M range
Range100M
100M range
Definition at line 56 of file mdtDeviceU3606A.h.
enum mdtDeviceU3606A::Resolution_t strong
Resolution.
Enumerator
Min
5 1/2 digit
Max
4 1/2 digit
Definition at line 76 of file mdtDeviceU3606A.h.
enum mdtDeviceU3606A::SourceRange_t strong
Range of source subsystem.
Enumerator
S1_30V1A
Range S1: 30V / 1A
S2_8V3A
Range S2: 8V / 3A
Definition at line 84 of file mdtDeviceU3606A.h.
Constructor & Destructor Documentation
mdtDeviceU3606A::mdtDeviceU3606A (QObject * parent = 0)
Constructor.
Will create the needed codec, I/Os and configure internal port manager .
Definition at line 28 of file mdtDeviceU3606A.cpp.
mdtDeviceU3606A::~mdtDeviceU3606A ()
Destructor.
Definition at line 33 of file mdtDeviceU3606A.cpp.
Member Function Documentation
bool mdtDeviceU3606A::connectToDevice (const QString & serialNumber, const QString & alias = QString()) inline
Connect to device.
Parameters
serialNumber Device serial number. Will be ignored if empty
alias Alias to give. Will be ignored if empty
Definition at line 105 of file mdtDeviceU3606A.h.
References mdtDevice::alias(), and mdtDeviceScpi::connectToDevice().
mdtDeviceU3606A::MeasureType_t mdtDeviceU3606A::getMeasureConfiguration ()
Get the measure configuration.
Will get the device current measure configuration by sending the CONF? query .
By error, unknown measure type is returned .
Definition at line 193 of file mdtDeviceU3606A.cpp.
References mdtScpiFunctionFarameter::Ac, mdtScpiFunctionFarameter::Current, CurrentAc, CurrentDc, mdtScpiFunctionFarameter::Dc, mdtCodecScpi::decodeFunctionParameters(), mdtScpiFunctionFarameter::Fresistance, mdtScpiFunctionFarameter::fundamentalMeasurementCommand(), Lresistance, Resistance, mdtScpiFunctionFarameter::Resistance, mdtDeviceScpi::sendQuery(), mdtScpiFunctionFarameter::simpleMeasurementCommand(), Unknown, mdtScpiFunctionFarameter::Unknown, mdtScpiFunctionFarameter::Voltage, VoltageAc, and VoltageDc.
mdtValueDouble mdtDeviceU3606A::getMeasureValue (int timeout = 30000)
Get measure value.
Will submit the READ? query to device. Don't forget to setup measure before.
Parameters
timeout Timeout [ms]
Definition at line 236 of file mdtDeviceU3606A.cpp.
References mdtCodecScpi::decodeValueDouble(), mdtValueDouble::isNull(), mdtCodecScpi::lastError(), mdtDevice::pvLastError, and mdtDeviceScpi::sendQuery().
bool mdtDeviceU3606A::setOutputState (bool state)
Set source output state (On/Off)
Definition at line 255 of file mdtDeviceU3606A.cpp.
References mdtDeviceScpi::sendCommand().
bool mdtDeviceU3606A::setSourceCurrent (double x)
Set source current.
Will setup source for constant current mode, with given current.
Refers to [SOURce:]CURRent[:LEVel][:IMMediate][:AMPLitude] in programmers reference guide.
Definition at line 293 of file mdtDeviceU3606A.cpp.
References mdtDeviceScpi::sendCommand().
bool mdtDeviceU3606A::setSourceRange (mdtDeviceU3606A::SourceRange_t range)
Set source range.
Note: source range can ba changed only whenn output is OFF.
See Also
setOutputState()
Definition at line 268 of file mdtDeviceU3606A.cpp.
References S1_30V1A, S2_8V3A, and mdtDeviceScpi::sendCommand().
bool mdtDeviceU3606A::setSourceVoltageLimit (double v)
Set source voltage limit.
This voltage limit is used for constant current source mode. Refers to [SOURce:]VOLTage:LIMit in programmers reference guide.
Definition at line 284 of file mdtDeviceU3606A.cpp.
References mdtDeviceScpi::sendCommand().
bool mdtDeviceU3606A::setupLowResistanceMeasure (mdtDeviceU3606A::Range_t range, mdtDeviceU3606A::Resolution_t resolution)
Setup low resistance measure (4 wires)
Parameters
range If range is supported by instrument, it will be set, else AUTO range is used.
resolution Resolution to use
Definition at line 150 of file mdtDeviceU3606A.cpp.
References Auto, mdtError::commit(), mdtDevice::deviceIdString(), Max, MDT_ERROR_SET_SRC, Min, mdtDevice::pvLastError, Range1, Range100m, mdtDeviceScpi::sendCommand(), mdtError::setError(), and mdtError::Warning.
bool mdtDeviceU3606A::setupResistanceMeasure (mdtDeviceU3606A::Range_t range, mdtDeviceU3606A::Resolution_t resolution)
Setup resistance measure.
Parameters
range If range is supported by instrument, it will be set, else AUTO range is used.
resolution Resolution to use
Definition at line 92 of file mdtDeviceU3606A.cpp.
References Auto, mdtError::commit(), mdtDevice::deviceIdString(), Max, MDT_ERROR_SET_SRC, Min, mdtDevice::pvLastError, Range100, Range100k, Range100M, Range10k, Range10M, Range1k, Range1M, mdtDeviceScpi::sendCommand(), mdtError::setError(), and mdtError::Warning.
bool mdtDeviceU3606A::setupVoltageDcMeasure (mdtDeviceU3606A::Range_t range, mdtDeviceU3606A::Resolution_t resolution)
Setup DC voltage measure.
Parameters
range If range is supported by instrument, it will be set, else AUTO range is used.
resolution Resolution to use
Definition at line 37 of file mdtDeviceU3606A.cpp.
References Auto, mdtError::commit(), mdtDevice::deviceIdString(), Max, MDT_ERROR_SET_SRC, Min, mdtDevice::pvLastError, Range1, Range10, Range100, Range100m, Range1k, Range20m, mdtDeviceScpi::sendCommand(), mdtError::setError(), and mdtError::Warning.
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceU3606A.h
src/mdtdevice/mdtDeviceU3606A.cpp