Multi diag tools: mdtTtBasicTestNodeCalibrationWindow Class Reference
mdtTtBasicTestNodeCalibrationWindow Class Reference
#include <mdtTtBasicTestNodeCalibrationWindow.h>
Public Member Functions
mdtTtBasicTestNodeCalibrationWindow (QSqlDatabase db, QWidget *parent=0)
Constructor.
bool init ()
Init.
Detailed Description
Test node calibration example
Definition at line 32 of file mdtTtBasicTestNodeCalibrationWindow.h.
Constructor & Destructor Documentation
mdtTtBasicTestNodeCalibrationWindow::mdtTtBasicTestNodeCalibrationWindow (QSqlDatabase db, QWidget * parent = 0)
Constructor.
Definition at line 32 of file mdtTtBasicTestNodeCalibrationWindow.cpp.
Member Function Documentation
bool mdtTtBasicTestNodeCalibrationWindow::init ()
Init.
Definition at line 47 of file mdtTtBasicTestNodeCalibrationWindow.cpp.
References mdtSqlTableWidget::setTableController(), mdtTtAbstractTestNodeCalibrationTool::setTestNode(), mdtTtBasicTestNodeCalibrationTool::setup(), and mdtTtAbstractTestNodeCalibrationTool::testNodeUnitViewTableController().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtBasicTestNodeCalibrationWindow.h
src/mdttools/mdttesttool/mdtTtBasicTestNodeCalibrationWindow.cpp