Multi diag tools: mdtFrameUsbTmc Class Reference
mdtFrameUsbTmc Class Reference
USBTMC frame.
#include <mdtFrameUsbTmc.h>
Public Types
enum msg_id_t {
MSG_ZERO = 0, DEV_DEP_MSG_OUT = 1, DEV_DEP_MSG_IN = 2, VENDOR_SPECIFIC_OUT = 126,
VENDOR_SPECIFIC_IN = 127
}
USBTMC MsgID.
Public Types inherited from mdtFrame
enum type_t {
FT_RAW, FT_RAW_TOP, FT_ASCII, FT_MODBUS_TCP,
FT_USBTMC
}
Frame type.
Public Member Functions
mdtFrameUsbTmc ()
~mdtFrameUsbTmc ()
void clearSub ()
mdtFrame subclass specific clear
int putData (const char *data, int maxLen)
Put data into the frame.
void setMsgID (msg_id_t MsgID)
Set the MsgID.
msg_id_t MsgID () const
Get the MsgID.
bool MsgIDsupported () const
Check if received MsgID is supported.
void setbTag (quint8 bTag)
Set the bTag.
quint8 bTag () const
Get the bTag.
bool bTagOk () const
Check bTag/bTagInverse coherence.
void setEOM (bool EOM)
Set the EOM flag.
bool isEOM () const
Get the EOM flag.
void setTransferSize (int size)
Set transfer size.
void setMessageData (const QByteArray &data)
Set the message data.
QByteArray & messageData ()
Get the message data.
void encode ()
Encode the USBTMC frame.
Public Member Functions inherited from mdtFrame
mdtFrame ()
virtual ~mdtFrame ()
void setIgnoreNullValues (bool ignoreNullValues)
Set the ignore null values flag.
int putUntil (const char *data, char token, int maxLen)
Put data until EOF token was reached.
int putUntil (const char *data, QByteArray &token, int maxLen)
Put data until EOF token was reached.
bool isFull ()
Returns true if frame is full.
int remainCapacity ()
Returns the remain capacity.
int bytesToStore ()
Returns the bytes to store into the frame.
void setDirectlyComplete (bool dc)
Set the complete flag directly.
void setComplete ()
Set the frame as complete.
bool isComplete ()
Returns true if EOF condition was reached.
void clear ()
Overloaded function.
virtual int eofSeqLen ()
Get the length of the end of frame sequence.
int take (char *data, int len)
Take some data.
int take (int len)
Take some data.
void setWaitAnAnswer (bool wait)
Tell a write/read thread that an answer is needed after a write frame.
bool waitAnAnswer () const
Know if an answer is needed after a write frame.
Additional Inherited Members
Protected Attributes inherited from mdtFrame
bool pvIgnoreNullValues
bool pvEOFcondition
bool pvWaitAnAnswer
Detailed Description
USBTMC frame.
Used by mdtport API to send en receive frames in USBTMC standard.
References:
USBTMC Revision 1.0 (2003)
http://www.usb.org/developers/devclass_docs#approved
http://www.usb.org/developers/devclass_docs/USBTMC_1_006a.zip
Definition at line 37 of file mdtFrameUsbTmc.h.
Member Enumeration Documentation
enum mdtFrameUsbTmc::msg_id_t
USBTMC MsgID.
Enumerator
MSG_ZERO
Reserved.
DEV_DEP_MSG_OUT
USBTMC device dependent command message
DEV_DEP_MSG_IN
USBTMC response message. Represent the REQUEST_DEV_DEP_MSG_IN if frame is sent from host (OUT)
VENDOR_SPECIFIC_OUT
USBTMC vendor specific command message
VENDOR_SPECIFIC_IN
USBTMC vendor specific response message on the Bulk-IN endpoint. Represent the REQUEST_VENDOR_SPECIFIC_IN if frame is sent from host (OUT)
Definition at line 43 of file mdtFrameUsbTmc.h.
Constructor & Destructor Documentation
mdtFrameUsbTmc::mdtFrameUsbTmc ()
Definition at line 25 of file mdtFrameUsbTmc.cpp.
mdtFrameUsbTmc::~mdtFrameUsbTmc ()
Definition at line 39 of file mdtFrameUsbTmc.cpp.
Member Function Documentation
quint8 mdtFrameUsbTmc::bTag () const
Get the bTag.
Usefull for frames received from device. Is only valid when the frame is complete.
Definition at line 151 of file mdtFrameUsbTmc.cpp.
Referenced by mdtUsbtmcPortManager::fromThreadNewFrameReaden(), and setbTag().
bool mdtFrameUsbTmc::bTagOk () const
Check bTag/bTagInverse coherence.
Usefull for frames received from device.
Returns
true if header was decoded and bTag/bTagInverse are coherent.
Definition at line 156 of file mdtFrameUsbTmc.cpp.
void mdtFrameUsbTmc::clearSub () virtual
mdtFrame subclass specific clear
Reimplemented from mdtFrame.
Definition at line 43 of file mdtFrameUsbTmc.cpp.
Referenced by mdtUsbtmcPortManager::sendData(), and mdtUsbtmcPortManager::sendReadRequest().
void mdtFrameUsbTmc::encode ()
Encode the USBTMC frame.
To use to build a frame that will be sent to device.
Note: clear() is called internally.
Definition at line 187 of file mdtFrameUsbTmc.cpp.
References mdtFrame::clear(), DEV_DEP_MSG_IN, and DEV_DEP_MSG_OUT.
Referenced by mdtUsbtmcPortManager::sendData(), and mdtUsbtmcPortManager::sendReadRequest().
bool mdtFrameUsbTmc::isEOM () const
Get the EOM flag.
If true, this transfer is the last in current message. Is only valid when the frame is complete.
Definition at line 166 of file mdtFrameUsbTmc.cpp.
QByteArray & mdtFrameUsbTmc::messageData ()
Get the message data.
Usefull for frames received from device. Is only valid when the frame is complete.
Definition at line 182 of file mdtFrameUsbTmc.cpp.
Referenced by mdtUsbtmcPortManager::fromThreadNewFrameReaden().
mdtFrameUsbTmc::msg_id_t mdtFrameUsbTmc::MsgID () const
Get the MsgID.
Usefull for frames received from device. Is only valid when the frame is complete.
Definition at line 135 of file mdtFrameUsbTmc.cpp.
Referenced by mdtUsbtmcPortManager::fromThreadNewFrameReaden(), and setMsgID().
bool mdtFrameUsbTmc::MsgIDsupported () const
Check if received MsgID is supported.
Usefull for frames received from device.
Returns
true if header was decoded and MsgID is supported.
Definition at line 140 of file mdtFrameUsbTmc.cpp.
int mdtFrameUsbTmc::putData (const char * data, int maxLen) virtual
Put data into the frame.
This method is called by the read thread, and should not be used directly.
Reimplemented from mdtFrame.
Definition at line 57 of file mdtFrameUsbTmc.cpp.
References mdtFrame::bytesToStore(), DEV_DEP_MSG_IN, mdtFrame::pvEOFcondition, and mdtFrame::remainCapacity().
void mdtFrameUsbTmc::setbTag (quint8 bTag)
Set the bTag.
The bTag should be incremented each time a new USBTMC message is sent, (each time a new USBTMC header is sent).
To use to build a frame that will be sent to device.
Precondition
bTag must be <> 0
Definition at line 145 of file mdtFrameUsbTmc.cpp.
References bTag().
Referenced by mdtUsbtmcPortManager::sendData(), and mdtUsbtmcPortManager::sendReadRequest().
void mdtFrameUsbTmc::setEOM (bool EOM)
Set the EOM flag.
EOM: End Of (USBTMC) Message.
If true, tells the device that this USBTMC transfer is the last in message.
Definition at line 161 of file mdtFrameUsbTmc.cpp.
Referenced by mdtUsbtmcPortManager::sendData().
void mdtFrameUsbTmc::setMessageData (const QByteArray & data)
Set the message data.
To use to build a frame that will be sent to device.
Definition at line 176 of file mdtFrameUsbTmc.cpp.
Referenced by mdtUsbtmcPortManager::sendData().
void mdtFrameUsbTmc::setMsgID (mdtFrameUsbTmc::msg_id_t MsgID)
Set the MsgID.
To use to build a frame that will be sent to device.
Definition at line 130 of file mdtFrameUsbTmc.cpp.
References MsgID().
Referenced by mdtUsbtmcPortManager::sendData(), and mdtUsbtmcPortManager::sendReadRequest().
void mdtFrameUsbTmc::setTransferSize (int size)
Set transfer size.
To use with DEV_DEP_MSG_IN request.
Definition at line 171 of file mdtFrameUsbTmc.cpp.
Referenced by mdtUsbtmcPortManager::sendReadRequest().
The documentation for this class was generated from the following files:
src/mdtutils/mdtFrameUsbTmc.h
src/mdtutils/mdtFrameUsbTmc.cpp