Multi diag tools: mdtClDirectLink Class Reference
mdtClDirectLink Class Reference
Create a temporary table with direct links informations.
#include <mdtClDirectLink.h>
Public Member Functions
mdtClDirectLink (QObject *parent, QSqlDatabase db)
Constructor.
~mdtClDirectLink ()
Destructor.
QList< QVariant > getUnitConnectionIdListPartOfUnit (const QList< QVariant > &unitConnectionIdList, const QVariant &unitId, bool *ok)
Get a list of ID unit connections that are part of given unit.
QList< QVariant > getUnitConnectionIdListPartOfUnitConnector (const QList< QVariant > &unitConnectionIdList, const QVariant &unitConnectorId, bool *ok)
Get a list of ID unit connections that are part of given unit connector.
bool addLink (const QVariant &unitConnectionStartId, const QVariant &unitConnectionEndId)
Will get data from LinkList_view for given start and end connections and put them into DirectLink_tbl.
bool addLinksByUnitConnector (const QVariant unitConnectorIdS, const QVariant unitConnectorIdE, mdtClPathGraph *graph)
Add direct links for connections of connectors S and E that are linked together.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
bool addRecordList (const QList< mdtSqlRecord > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Create a temporary table with direct links informations.
Real links are stored in Link_tbl. LinkList_view is also avalable to get more informations.
Link_tbl references all links that exists in practice, and also all connections. With mdtClPathGraph, it's possible get the path, including several linked links, starting from a defined unit connection. In some cases, it can be more interesting to have a synthetic view of paths starting from a element. Typical usage could be to see witch connection from a starting connector goes to witch connection of a other connector. This result will also contain several, so called, direct links.
Definition at line 49 of file mdtClDirectLink.h.
Constructor & Destructor Documentation
mdtClDirectLink::mdtClDirectLink (QObject * parent, QSqlDatabase db)
Constructor.
Will also create DirectLink_tbl temporary table.
Note: if DirectLink_tbl allready exists, it will be overwritten.
Definition at line 31 of file mdtClDirectLink.cpp.
mdtClDirectLink::~mdtClDirectLink ()
Destructor.
Will also remove DirectLink_tbl.
Definition at line 37 of file mdtClDirectLink.cpp.
Member Function Documentation
bool mdtClDirectLink::addLink (const QVariant & unitConnectionStartId, const QVariant & unitConnectionEndId)
Will get data from LinkList_view for given start and end connections and put them into DirectLink_tbl.
Definition at line 104 of file mdtClDirectLink.cpp.
References mdtTtBase::addRecord(), mdtError::commit(), mdtError::Error, mdtSqlRecord::isEmpty(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, and mdtError::setError().
Referenced by addLinksByUnitConnector().
bool mdtClDirectLink::addLinksByUnitConnector (const QVariant unitConnectorIdS, const QVariant unitConnectorIdE, mdtClPathGraph * graph)
Add direct links for connections of connectors S and E that are linked together.
Todo:
Add transactions
Definition at line 160 of file mdtClDirectLink.cpp.
References addLink(), mdtTtBase::database(), mdtClUnit::getConnectionIdListPartOfConnectorId(), mdtClUnit::getConnectorIdOfConnectionId(), mdtClPathGraph::getLinkedConnectionIdList(), mdtTtBase::lastError(), and mdtTtBase::pvLastError.
QList< QVariant > mdtClDirectLink::getUnitConnectionIdListPartOfUnit (const QList< QVariant > & unitConnectionIdList, const QVariant & unitId, bool * ok)
Get a list of ID unit connections that are part of given unit.
Definition at line 42 of file mdtClDirectLink.cpp.
References mdtTtBase::getData().
QList< QVariant > mdtClDirectLink::getUnitConnectionIdListPartOfUnitConnector (const QList< QVariant > & unitConnectionIdList, const QVariant & unitConnectorId, bool * ok)
Get a list of ID unit connections that are part of given unit connector.
Definition at line 73 of file mdtClDirectLink.cpp.
References mdtTtBase::getData().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClDirectLink.h
src/mdttools/mdttesttool/mdtcablelist/mdtClDirectLink.cpp