Multi diag tools: mdtUsbPort Class Reference
mdtUsbPort Class Reference
USB port I/O port class.
#include <mdtUsbPort.h>
Public Member Functions
mdtUsbPort (QObject *parent=0)
~mdtUsbPort ()
Destructor.
error_t reconnect (int timeout)
Reconnect device.
void setReadTimeout (int timeout)
Set the read data timeout.
void setWriteTimeout (int timeout)
Set the write data timeout.
QQueue< mdtFrameUsbControl * > & controlFramesPool ()
Get the control pool queue.
QQueue< mdtFrameUsbControl * > & controlQueryFrames ()
Get the control query queue.
void addControlRequest (mdtFrameUsbControl *frame, bool setwIndexAsbInterfaceNumber=false)
Add a control request.
void submitControlQuery ()
Submit a control query.
error_t cancelControlTransfer ()
Cancel current control transfer.
QQueue< mdtFrameUsbControl * > & controlResponseFrames ()
Get the control responses queue.
void requestReadUntilShortPacketReceived ()
Request to read until a short packet is received.
bool readUntilShortPacketReceivedRequestPending ()
Check if a request to read until a short packet is received is pending.
int readBufferSize () const
Get read buffer size.
error_t initReadTransfer (qint64 maxSize)
Submit a read transfer.
error_t cancelReadTransfer ()
Cancel current bulk/interrupt input transfer.
error_t clearReadEndpointHalt ()
Clear halt on read endpoint.
error_t waitForReadyRead ()
Wait until data is available on port.
qint64 read (char *data, qint64 maxSize)
Read data from port.
error_t initMessageInTransfer ()
Request a new interrupt input transfer for additional message input.
error_t cancelMessageInTransfer ()
Cancel current interrupt message input transfer.
QQueue< mdtFrame * > & messageInFramesPool ()
Get the message IN frames pool.
QQueue< mdtFrame * > & messageInFrames ()
Get the message IN frames.
void addFrameToWrite (mdtFrame *frame)
Add a frame to write.
error_t initWriteTransfer (const char *data, qint64 maxSize)
Request a new bulk/interrupt out transfer.
error_t cancelWriteTransfer ()
Cancel current bulk/interrupt input transfer.
error_t clearWriteEndpointHalt ()
Clear halt on write endpoint.
error_t waitEventWriteReady ()
Wait until data can be written to port.
qint64 write (const char *, qint64)
Write data to port.
void addError (mdtAbstractPort::error_t error)
Set error.
QList< error_t > lastErrors ()
Get the lis of current errors.
error_t cancelTransfers ()
Cancel pending transfers.
error_t handleUsbEvents ()
Call libusb handle_event() function.
quint8 currentReadEndpointAddress () const
Get current read endpoint address.
quint8 currentWriteEndpointAddress () const
Get current write endpoint address.
QQueue< quint8 > & expectedBulkInbTags ()
Get list of expeced incomming bTags.
Public Member Functions inherited from mdtAbstractPort
mdtAbstractPort (QObject *parent=0)
virtual ~mdtAbstractPort ()
Destructor.
void setPortName (const QString &portName)
Set the port name.
QString & portName ()
Get port name.
error_t open ()
Open the port given by setPortName()
bool isOpen () const
Get port's open state.
virtual void close ()
Close the port.
void setConfig (mdtPortConfig *cfg)
Set configuration.
mdtPortConfig & config ()
Get the stored configuration.
error_t setup ()
Setup port with given configurations.
error_t waitForReadyRead (int msecs)
Wait until data is available on port.
virtual bool suspendTransmission ()
Request to suspend transmission.
virtual bool resumeTransmission ()
Request to resume transmission.
void flushIn ()
Flush read buffers.
bool flushInRequestPending ()
Check if a flush in request is pending.
void flushOut ()
Flush write buffers.
bool flushOutRequestPending ()
Check if a flush out request is pending.
void flush ()
Flush read/write buffers.
void initQueues ()
Init the read ans write queues.
QQueue< mdtFrame * > & readenFrames ()
Get the readen frames Queue.
QQueue< mdtFrame * > & readFramesPool ()
Get the read frames Queue pool.
mdtFrame * getFrameToWrite ()
Wait until a frame to write is available and get it.
void abortFrameToWriteWait ()
Abort the frame tp write waiting.
QQueue< mdtFrame * > & writeFrames ()
Get the write frames Queue.
QQueue< mdtFrame * > & writeFramesPool ()
Get the write frames Queue pool.
void lockMutex ()
Lock the mutex.
void unlockMutex ()
Unlock the mutex.
Static Public Member Functions
static void controlTransferCallback (struct libusb_transfer *transfer)
Transfer callback for control endpoint.
static void readTransferCallback (struct libusb_transfer *transfer)
Transfer callback for read endpoint.
static void messageInTransferCallback (struct libusb_transfer *transfer)
Transfer callback for message in (additional interrupt) endpoint.
static void writeTransferCallback (struct libusb_transfer *transfer)
Transfer callback for write endpoint.
Additional Inherited Members
Public Types inherited from mdtAbstractPort
enum error_t {
NoError = 0, PortLocked = -1000, PortNotFound, PortAccess,
SetupError, WriteCanceled, ReadCanceled, ControlCanceled,
ReadTimeout, WriteTimeout, MessageInTimeout, MessageInCanceled,
ControlTimeout, Disconnected, Connecting, ConnectionFailed,
UnhandledError, ReadPoolEmpty, WritePoolEmpty, ErrorHandled,
ReadWriteBusy, UsbWriteStall, UsbReadStall
}
Error.
Protected Attributes inherited from mdtAbstractPort
QQueue< mdtFrame * > pvReadenFrames
QQueue< mdtFrame * > pvReadFramesPool
QQueue< mdtFrame * > pvWriteFrames
QQueue< mdtFrame * > pvWriteFramesPool
mdtPortConfig * pvConfig
QString pvPortName
QMutex pvMutex
QWaitCondition pvWriteFrameAvailable
Detailed Description
USB port I/O port class.
Built on top of libusb-1.x API
Note about the port name (set with setPortName()):
Because it can happen that multiple devices with same vendor ID and product ID can be attached to system, this class must provide a unique identifier when (re-)open the port. Because of this, the choosen format is: VID=0x1234:PID=0x1234:SID=0x1234:bInterfaceNumber=0. VID is the Vendor ID, PID the Product ID, SID the Serial ID (also called Serial Number) and bInterfaceNumber the interface number (some devices have mor than one interface, f.ex. sound cards, keboard/mouse receiver, ...). SID and bInterfaceNumber are optional. In this case, the first port with given vendor ID and device ID is open. In brief, following names are allowed:
VID=0x1234:PID=0x5678 (Open the first port with given Vendor ID and Product ID. bInterfaceNumber is 0)
VID=0x1234:PID=0x5678:SID=ABC1234 (Open the first port with given Vendor ID, Product ID and Serial ID. bInterfaceNumber is 0)
VID=0x1234:PID=0x5678:bInterfaceNumber=1 (Open the first port with given Vendor ID and Product ID. bInterfaceNumber is 1)
VID=0x1234:PID=0x5678:SID=ABC1234:bInterfaceNumber=1 (Open the first port with given Vendor ID, Product ID and Serial ID. bInterfaceNumber is 1) The last example in the above list is the format returned by mdtUsbPortManager::scan().
For read and write of data, the mdtAbstractPort's API is used, expected that waitForReadyRead() and waitEventWriteReady() are not used.
The control transfer is a little bit different:
If the main thread (f.ex. GUI thread) wants to send a request, it locks the mutex using lockMutex(), then it takes a frame in pool with controlFramesPool(). Finaly, query is submitted using addControlRequest(), witch will submit the frame, and main thread unlocks the mutex with unlockMutex().
The thread periodically checks if a response is available using controlResponseFrames() queue's size, and emit controlResponseReaden() if a control response is available.
If a additional (to read and write) interrupt IN endpoint exists, it is handled as message IN as follow:
The thread periodically checks if a message IN is available using messageInFrames() queue's size, and emit messageInReaden() if a message IN is available.
A new transfer is reinitialized by thread.
Definition at line 64 of file mdtUsbPort.h.
Constructor & Destructor Documentation
mdtUsbPort::mdtUsbPort (QObject * parent = 0)
Definition at line 40 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, and mdtError::setSystemError().
mdtUsbPort::~mdtUsbPort ()
Destructor.
Definition at line 80 of file mdtUsbPort.cpp.
References mdtAbstractPort::close().
Member Function Documentation
void mdtUsbPort::addControlRequest (mdtFrameUsbControl * frame, bool setwIndexAsbInterfaceNumber = false)
Add a control request.
Add a control frame to the queries queue. Frame will be sent as soon as possible.
The mutex must be locked before calling this method, and still locked inside.
Parameters
frame Control frame
setwIndexAsbInterfaceNumber If true, wIndex will be set with current bInterfaceNumber
Precondition
frame must be a valid pointer.
Definition at line 138 of file mdtUsbPort.cpp.
References mdtFrameUsbControl::setwIndex(), and submitControlQuery().
Referenced by mdtUsbPortThread::sendControlQuery(), and mdtUsbPortManager::sendControlRequest().
void mdtUsbPort::addError (mdtAbstractPort::error_t error)
Set error.
Used by transfer callbacks
Mutex is not handled by this method.
Definition at line 955 of file mdtUsbPort.cpp.
Referenced by addFrameToWrite(), controlTransferCallback(), messageInTransferCallback(), readTransferCallback(), requestReadUntilShortPacketReceived(), submitControlQuery(), and writeTransferCallback().
void mdtUsbPort::addFrameToWrite (mdtFrame * frame) virtual
Add a frame to write.
Once the frame is added to the write queue, waiting thread will be woken up (if waiting) and will send the frame.
The mutex must be locked before calling this method, and still locked inside.
Precondition
frame must be a valid pointer.
Reimplemented from mdtAbstractPort.
Definition at line 743 of file mdtUsbPort.cpp.
References addError(), initWriteTransfer(), mdtAbstractPort::NoError, and mdtAbstractPort::pvWriteFrames.
mdtAbstractPort::error_t mdtUsbPort::cancelControlTransfer ()
Cancel current control transfer.
Used by mdtUsbPortThread, should not be used else.
Definition at line 309 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, handleUsbEvents(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
Referenced by cancelTransfers().
mdtAbstractPort::error_t mdtUsbPort::cancelMessageInTransfer ()
Cancel current interrupt message input transfer.
Used by mdtUsbPortThread, should not be used else.
Definition at line 694 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, handleUsbEvents(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
Referenced by cancelTransfers().
mdtAbstractPort::error_t mdtUsbPort::cancelReadTransfer ()
Cancel current bulk/interrupt input transfer.
Used by mdtUsbPortThread, should not be used else.
Definition at line 487 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, handleUsbEvents(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
Referenced by cancelTransfers().
mdtAbstractPort::error_t mdtUsbPort::cancelTransfers ()
Cancel pending transfers.
Will cancel all pending transfers.
Used by mdtUsbPortThread, should not be used else.
Definition at line 970 of file mdtUsbPort.cpp.
References cancelControlTransfer(), cancelMessageInTransfer(), cancelReadTransfer(), cancelWriteTransfer(), mdtAbstractPort::ControlCanceled, mdtAbstractPort::MessageInCanceled, mdtAbstractPort::NoError, mdtAbstractPort::ReadCanceled, and mdtAbstractPort::WriteCanceled.
Referenced by reconnect().
mdtAbstractPort::error_t mdtUsbPort::cancelWriteTransfer ()
Cancel current bulk/interrupt input transfer.
Used by mdtUsbPortThread, should not be used else.
Definition at line 873 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, handleUsbEvents(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
Referenced by cancelTransfers().
mdtAbstractPort::error_t mdtUsbPort::clearReadEndpointHalt ()
Clear halt on read endpoint.
This is a blocking method, and should only be called by port thread. Active read transfers should be canceled before using this method (see cancelReadTransfer()).
Definition at line 527 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, and mdtError::setSystemError().
mdtAbstractPort::error_t mdtUsbPort::clearWriteEndpointHalt ()
Clear halt on write endpoint.
This is a blocking method, and should only be called by port thread. Active write transfers should be canceled before using this method (see cancelWriteTransfer()).
Definition at line 913 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, and mdtError::setSystemError().
QQueue< mdtFrameUsbControl * > & mdtUsbPort::controlFramesPool ()
Get the control pool queue.
This queue contains the pool of control frames.
Mutex is not handled by this method.
Definition at line 299 of file mdtUsbPort.cpp.
Referenced by controlTransferCallback(), mdtUsbPortManager::fromThreadControlResponseReaden(), mdtUsbPortManager::sendControlRequest(), submitControlQuery(), and mdtUsbPortThread::waitOnControlTransferPossible().
QQueue< mdtFrameUsbControl * > & mdtUsbPort::controlQueryFrames ()
Get the control query queue.
This queue contains control query frames (control requests).
Mutex is not handled by this method.
Definition at line 304 of file mdtUsbPort.cpp.
QQueue< mdtFrameUsbControl * > & mdtUsbPort::controlResponseFrames ()
Get the control responses queue.
This queue contains the response frames returned from device.
Mutex is not handled by this method.
Definition at line 348 of file mdtUsbPort.cpp.
Referenced by controlTransferCallback(), and mdtUsbPortManager::fromThreadControlResponseReaden().
void mdtUsbPort::controlTransferCallback (struct libusb_transfer * transfer) static
Transfer callback for control endpoint.
Check completion and error flags and add control frame in responses queue if ok, or in pool else. On error, addError() is called, so thread can notify it.
Once done, submitControlQuery() is called.
This method is called from libusb and should not be used directly.
Mutex is locked during process and unlocked befor return.
Precondition
transfer must be valid
transfer->user_data must be valid
Definition at line 198 of file mdtUsbPort.cpp.
References addError(), mdtFrame::clear(), mdtFrameUsbControl::clearSub(), mdtError::commit(), mdtAbstractPort::ControlCanceled, controlFramesPool(), controlResponseFrames(), mdtAbstractPort::ControlTimeout, mdtAbstractPort::Disconnected, mdtError::Error, mdtAbstractPort::lockMutex(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtFrameUsbControl::setbmRequestType(), mdtFrameUsbControl::setbRequest(), mdtFrameUsbControl::setwIndex(), mdtFrameUsbControl::setwLength(), mdtFrameUsbControl::setwValue(), submitControlQuery(), mdtAbstractPort::UnhandledError, and mdtAbstractPort::unlockMutex().
Referenced by submitControlQuery().
quint8 mdtUsbPort::currentReadEndpointAddress () const
Get current read endpoint address.
Note: mutex is not handled by this method
Definition at line 1028 of file mdtUsbPort.cpp.
quint8 mdtUsbPort::currentWriteEndpointAddress () const
Get current write endpoint address.
Note: mutex is not handled by this method
Definition at line 1033 of file mdtUsbPort.cpp.
QQueue< quint8 > & mdtUsbPort::expectedBulkInbTags ()
Get list of expeced incomming bTags.
This method is used by mdtUsbtmcPortManager and mdtUsbtmcPortThread and should not be used else.
Definition at line 1038 of file mdtUsbPort.cpp.
Referenced by mdtUsbtmcPortManager::fromThreadNewFrameReaden().
mdtAbstractPort::error_t mdtUsbPort::handleUsbEvents ()
Call libusb handle_event() function.
Notes: must be called only by I/O thread (typically mdtUsbPortThread). This method unlocks the mutex during wait (must be locked by call, is locked again before return)
Returns
NoError or mdtAbstractPort::error_t error (Note: timeout is ignored here)
Definition at line 994 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtAbstractPort::Disconnected, mdtError::Error, mdtAbstractPort::lockMutex(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, mdtAbstractPort::PortAccess, mdtError::setSystemError(), mdtAbstractPort::UnhandledError, and mdtAbstractPort::unlockMutex().
Referenced by cancelControlTransfer(), cancelMessageInTransfer(), cancelReadTransfer(), cancelWriteTransfer(), mdtUsbPortThread::readUntilShortPacketReceived(), mdtUsbPortThread::sendControlQuery(), and mdtUsbPortThread::waitOnControlTransferPossible().
mdtAbstractPort::error_t mdtUsbPort::initMessageInTransfer ()
Request a new interrupt input transfer for additional message input.
Will fill and init a new interrupt transfer and submit it to libusb.
If a transfer is pending, this method simply returns.
This method is called by USB port thread and should not be used else.
Mutex is not handled by this method.
Returns
NoError or a error from mdtAbstractPort::error_t
Definition at line 577 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, messageInTransferCallback(), mdtAbstractPort::NoError, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
mdtAbstractPort::error_t mdtUsbPort::initReadTransfer (qint64 maxSize)
Submit a read transfer.
If a transfer is pending, this method simply returns.
This method is called by USB port thread and should not be used else.
Mutex is not handled by this method.
Returns
NoError or a error from mdtAbstractPort::error_t
Definition at line 374 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, readTransferCallback(), mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
Referenced by mdtUsbPortThread::readUntilShortPacketReceived(), and requestReadUntilShortPacketReceived().
mdtAbstractPort::error_t mdtUsbPort::initWriteTransfer (const char * data, qint64 maxSize)
Request a new bulk/interrupt out transfer.
Will fill and init a new bulk/interrupt (depending setup) transfer and submit it to libusb.
If a transfer is pending, this method simply returns.
This method is called by USB port thread and should not be used else.
Mutex is not handled by this method.
Returns
NoError or a error from mdtAbstractPort::error_t
Definition at line 761 of file mdtUsbPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, mdtError::setSystemError(), mdtAbstractPort::UnhandledError, and writeTransferCallback().
Referenced by addFrameToWrite().
QList< mdtAbstractPort::error_t > mdtUsbPort::lastErrors ()
Get the lis of current errors.
Will clear internal list (a second call will return a empty list)
Used by mdtUsbPortThread, should not be used else.
Definition at line 960 of file mdtUsbPort.cpp.
Referenced by mdtUsbPortThread::readUntilShortPacketReceived(), mdtUsbPortThread::sendControlQuery(), and mdtUsbPortThread::waitOnControlTransferPossible().
QQueue< mdtFrame * > & mdtUsbPort::messageInFrames ()
Get the message IN frames.
This queue contains the message IN frames.
Mutex is not handled by this method.
Definition at line 738 of file mdtUsbPort.cpp.
QQueue< mdtFrame * > & mdtUsbPort::messageInFramesPool ()
Get the message IN frames pool.
This queue contains the pool of message IN frames.
Mutex is not handled by this method.
Definition at line 733 of file mdtUsbPort.cpp.
void mdtUsbPort::messageInTransferCallback (struct libusb_transfer * transfer) static
Transfer callback for message in (additional interrupt) endpoint.
Check completion and error flags. On error, addError() is called, so thread can notify it.
This method is called from libusb and should not be used directly.
Mutex is not handled by this method.
Precondition
transfer must be valid
transfer->user_data must be valid
Definition at line 609 of file mdtUsbPort.cpp.
References addError(), mdtFrame::clear(), mdtFrame::clearSub(), mdtError::commit(), mdtAbstractPort::Disconnected, mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::MessageInCanceled, mdtAbstractPort::MessageInTimeout, mdtAbstractPort::ReadPoolEmpty, mdtAbstractPort::UnhandledError, and mdtError::Warning.
Referenced by initMessageInTransfer().
qint64 mdtUsbPort::read (char * data, qint64 maxSize) virtual
Read data from port.
This method is called from mdtUsbPortThread , and should not be used directly.
Mutex is not handled by this method.
Returns
Amount of readen data (can be 0 if transfer is pending or no more data are available), mdtAbstractPort::error_t code on error.
Precondition
data must be valid
Implements mdtAbstractPort.
Definition at line 548 of file mdtUsbPort.cpp.
References mdtAbstractPort::UnhandledError.
Referenced by mdtUsbPortThread::readUntilShortPacketReceived().
int mdtUsbPort::readBufferSize () const
Get read buffer size.
This is the same as wMaxPacketSize of read endpoint.
This method is used by USB thread, and should not be used else.
Mutex is not handled by this method.
Definition at line 572 of file mdtUsbPort.cpp.
Referenced by mdtUsbPortThread::readUntilShortPacketReceived().
void mdtUsbPort::readTransferCallback (struct libusb_transfer * transfer) static
Transfer callback for read endpoint.
Check completion and error flags. On error, addError() is called, so thread can notify it.
This method is called from libusb and should not be used directly.
Mutex is not handled by this method.
Precondition
transfer must be valid
transfer->user_data must be valid
Definition at line 426 of file mdtUsbPort.cpp.
References addError(), mdtError::commit(), mdtAbstractPort::Disconnected, mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::ReadCanceled, mdtAbstractPort::ReadTimeout, mdtAbstractPort::UnhandledError, mdtAbstractPort::UsbReadStall, and mdtError::Warning.
Referenced by initReadTransfer().
bool mdtUsbPort::readUntilShortPacketReceivedRequestPending ()
Check if a request to read until a short packet is received is pending.
Flag will be cleared after a call of this method.
This method is used by USB thread, and should not be used else.
Mutex is not handled by this method.
Definition at line 365 of file mdtUsbPort.cpp.
mdtAbstractPort::error_t mdtUsbPort::reconnect (int timeout) virtual
Reconnect device.
If one of the method returns a Disconnected error, the thread will call this method to try to reconnect.
Parameters
timeout Timeout [ms]
Returns
NoError if connection could be done. Disconnected if connection could not be done, in wich case the thread will retry (until max retry). A UnhandledError can be returned.
Reimplemented from mdtAbstractPort.
Definition at line 87 of file mdtUsbPort.cpp.
References cancelTransfers(), mdtAbstractPort::close(), mdtAbstractPort::Disconnected, mdtAbstractPort::lockMutex(), msleep, mdtAbstractPort::NoError, mdtAbstractPort::open(), mdtAbstractPort::setup(), and mdtAbstractPort::unlockMutex().
void mdtUsbPort::requestReadUntilShortPacketReceived ()
Request to read until a short packet is received.
The mutex must be locked before calling this method, and still locked inside.
Definition at line 353 of file mdtUsbPort.cpp.
References addError(), initReadTransfer(), and mdtAbstractPort::NoError.
Referenced by mdtUsbPortManager::readUntilShortPacketReceived().
void mdtUsbPort::setReadTimeout (int timeout) virtual
Set the read data timeout.
The mutex is not handled by this method.
Implements mdtAbstractPort.
Definition at line 112 of file mdtUsbPort.cpp.
void mdtUsbPort::setWriteTimeout (int timeout) virtual
Set the write data timeout.
The mutex is not handled by this method.
Implements mdtAbstractPort.
Definition at line 125 of file mdtUsbPort.cpp.
void mdtUsbPort::submitControlQuery ()
Submit a control query.
If frames are available in queries queue and no control transfer is pending, a transfer will be submitted.
This method is called by addControlRequest() and controlTransferCallback() and should not be used directly.
The mutex must be locked before calling this method, and still locked inside.
Definition at line 149 of file mdtUsbPort.cpp.
References addError(), mdtError::commit(), controlFramesPool(), controlTransferCallback(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
Referenced by addControlRequest(), and controlTransferCallback().
mdtAbstractPort::error_t mdtUsbPort::waitEventWriteReady () virtual
Wait until data can be written to port.
This method is not implemented here and will allways return a UnhandledError.
Implements mdtAbstractPort.
Definition at line 929 of file mdtUsbPort.cpp.
References mdtAbstractPort::UnhandledError.
mdtAbstractPort::error_t mdtUsbPort::waitForReadyRead () virtual
Wait until data is available on port.
Not implemented, will allways return a UnhandledError
Implements mdtAbstractPort.
Definition at line 543 of file mdtUsbPort.cpp.
References mdtAbstractPort::UnhandledError.
qint64 mdtUsbPort::write (const char * , qint64) virtual
Write data to port.
This method is called from mdtPortWriteThread , and should not be used directly.
Mutex is not handled by this method.
Implements mdtAbstractPort.
Definition at line 934 of file mdtUsbPort.cpp.
References mdtAbstractPort::UnhandledError.
void mdtUsbPort::writeTransferCallback (struct libusb_transfer * transfer) static
Transfer callback for write endpoint.
Check completion and error flags. On error, addError() is called, so thread can notify it.
This method is called from libusb and should not be used directly.
Mutex is not handled by this method.
Precondition
transfer must be valid
transfer->user_data must be valid
Definition at line 815 of file mdtUsbPort.cpp.
References addError(), mdtError::commit(), mdtAbstractPort::Disconnected, mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::UnhandledError, mdtAbstractPort::UsbWriteStall, mdtAbstractPort::WriteCanceled, and mdtAbstractPort::WriteTimeout.
Referenced by initWriteTransfer().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbPort.h
src/mdtport/mdtUsbPort.cpp