Multi diag tools: mdtTtTestNodeSetupData Class Reference
mdtTtTestNodeSetupData Class Reference
Storage class for test node setup data.
#include <mdtTtTestNodeSetupData.h>
Public Member Functions
void setId (const QVariant &id)
Set ID (primary key)
QVariant id () const
Get ID (primary key)
void setNodeIdentification (const QString &id)
Set test node identification.
QString nodeIdentification () const
Get node identification.
void setDeviceIdentification (const QVariant &id)
Set device identification.
QVariant deviceIdentification () const
Get device identification.
void clear ()
Clear data.
void clearUnitSetup ()
Clear test node unit setup data list.
void addUnitSetup (const mdtTtTestNodeUnitSetupData &data)
Add a test node unit setup.
void addUnitSetupList (const QList< mdtTtTestNodeUnitSetupData > &datalist)
Add a list of test node unit setup.
const QList
< mdtTtTestNodeUnitSetupData > & unitSetupList () const
Get all test node unit setup data list.
void addRouteData (const mdtTtTestModelItemRouteData &data)
Add route data.
void addRouteDataList (const QList< mdtTtTestModelItemRouteData > &dataList)
Add a list of route data.
const QList
< mdtTtTestModelItemRouteData > & routeDataList () const
Get route data list.
QList
< mdtTtTestModelItemRouteData > routeDataListForStepNumber (int stepNumber) const
Get route data list for given stepNumber.
Detailed Description
Storage class for test node setup data.
Definition at line 32 of file mdtTtTestNodeSetupData.h.
Member Function Documentation
void mdtTtTestNodeSetupData::addRouteData (const mdtTtTestModelItemRouteData & data)
Add route data.
Will also add test node unit setup data contained in data to list
Definition at line 55 of file mdtTtTestNodeSetupData.cpp.
References mdtTtTestModelItemRouteData::setupDataList().
Referenced by addRouteDataList().
void mdtTtTestNodeSetupData::addRouteDataList (const QList< mdtTtTestModelItemRouteData > & dataList)
Add a list of route data.
Will also add test node unit setup data contained in data to list
Definition at line 61 of file mdtTtTestNodeSetupData.cpp.
References addRouteData().
void mdtTtTestNodeSetupData::addUnitSetup (const mdtTtTestNodeUnitSetupData & data)
Add a test node unit setup.
Definition at line 45 of file mdtTtTestNodeSetupData.cpp.
Referenced by mdtTtTestItemNodeSetupData::addNodeSetupData().
void mdtTtTestNodeSetupData::addUnitSetupList (const QList< mdtTtTestNodeUnitSetupData > & datalist)
Add a list of test node unit setup.
Definition at line 50 of file mdtTtTestNodeSetupData.cpp.
void mdtTtTestNodeSetupData::clear ()
Clear data.
Definition at line 33 of file mdtTtTestNodeSetupData.cpp.
References clearUnitSetup().
Referenced by mdtTtTestItemNodeSetupData::clear().
void mdtTtTestNodeSetupData::clearUnitSetup ()
Clear test node unit setup data list.
Definition at line 40 of file mdtTtTestNodeSetupData.cpp.
Referenced by clear().
QVariant mdtTtTestNodeSetupData::deviceIdentification () const inline
Get device identification.
Definition at line 63 of file mdtTtTestNodeSetupData.h.
Referenced by mdtTtTestItemNodeSetupData::addNodeSetupData(), and mdtTtTestItemNodeSetupData::currentDeviceIdentification().
QVariant mdtTtTestNodeSetupData::id () const inline
Get ID (primary key)
Definition at line 44 of file mdtTtTestNodeSetupData.h.
Referenced by setDeviceIdentification(), setId(), and setNodeIdentification().
QString mdtTtTestNodeSetupData::nodeIdentification () const inline
Get node identification.
Definition at line 55 of file mdtTtTestNodeSetupData.h.
Referenced by mdtTtTestItemNodeSetupData::addNodeSetupData().
const QList<mdtTtTestModelItemRouteData>& mdtTtTestNodeSetupData::routeDataList () const inline
Get route data list.
Definition at line 99 of file mdtTtTestNodeSetupData.h.
QList< mdtTtTestModelItemRouteData > mdtTtTestNodeSetupData::routeDataListForStepNumber (int stepNumber) const
Get route data list for given stepNumber.
Definition at line 70 of file mdtTtTestNodeSetupData.cpp.
void mdtTtTestNodeSetupData::setDeviceIdentification (const QVariant & id)
Set device identification.
Definition at line 28 of file mdtTtTestNodeSetupData.cpp.
References id().
Referenced by mdtTtTestItemNodeSetupData::addNodeSetupData().
void mdtTtTestNodeSetupData::setId (const QVariant & id) inline
Set ID (primary key)
Definition at line 38 of file mdtTtTestNodeSetupData.h.
References id().
void mdtTtTestNodeSetupData::setNodeIdentification (const QString & id)
Set test node identification.
Definition at line 23 of file mdtTtTestNodeSetupData.cpp.
References id().
Referenced by mdtTtTestItemNodeSetupData::addNodeSetupData().
const QList<mdtTtTestNodeUnitSetupData>& mdtTtTestNodeSetupData::unitSetupList () const inline
Get all test node unit setup data list.
Definition at line 83 of file mdtTtTestNodeSetupData.h.
Referenced by mdtTtTestItemNodeSetupData::addNodeSetupData().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestNodeSetupData.h
src/mdttools/mdttesttool/mdtTtTestNodeSetupData.cpp