Multi diag tools: mdtValueBool Class Reference
mdtValueBool Class Reference
Boolean type with Null attribute.
#include <mdtValue.h>
Public Member Functions
mdtValueBool ()
Construct a null boolean.
mdtValueBool (bool value)
Construct boolean.
void clear ()
Clear boolean.
bool isNull () const
Check if boolean is null.
void setValue (bool value)
Set value.
bool value () const
Get boolean's value.
Detailed Description
Boolean type with Null attribute.
Most of cases, using standard C++ types are sufficent. But, in some cases, its needed to test if a function returned a valid value or not. Here, the Null flag is used for that.
Definition at line 417 of file mdtValue.h.
Constructor & Destructor Documentation
mdtValueBool::mdtValueBool () inline
Construct a null boolean.
Definition at line 423 of file mdtValue.h.
mdtValueBool::mdtValueBool (bool value) inline
Construct boolean.
Definition at line 431 of file mdtValue.h.
Member Function Documentation
void mdtValueBool::clear () inline
Clear boolean.
Definition at line 439 of file mdtValue.h.
bool mdtValueBool::isNull () const inline
Check if boolean is null.
Definition at line 447 of file mdtValue.h.
Referenced by operator<<().
void mdtValueBool::setValue (bool value) inline
Set value.
Definition at line 454 of file mdtValue.h.
References value().
bool mdtValueBool::value () const inline
Get boolean's value.
Definition at line 462 of file mdtValue.h.
Referenced by operator<<(), and setValue().
The documentation for this class was generated from the following file:
src/mdtutils/mdtValue.h