Multi diag tools: mdtItemsSelectorDialogItem Class Reference
mdtItemsSelectorDialogItem Class Reference
Data container for mdtItemsSelectorDialog.
#include <mdtItemsSelectorDialogItem.h>
Public Member Functions
mdtItemsSelectorDialogItem ()
Constructor.
void setText (const QString &text)
QString text (bool includeSortOrderText=false) const
Get text.
void setColumnIndex (int index)
Set column index.
int columnIndex () const
Get column index.
void setName (const QString &name)
Set name.
QString name () const
Get name.
void setSortOrder (Qt::SortOrder order)
Set sort order.
Qt::SortOrder sortOrder () const
Get sort order.
QString sortOrderText () const
Get sort order text.
bool operator< (const mdtItemsSelectorDialogItem &other) const
Used by mdtItemsSelectorDialog to sort available items.
Detailed Description
Data container for mdtItemsSelectorDialog.
Definition at line 29 of file mdtItemsSelectorDialogItem.h.
Constructor & Destructor Documentation
mdtItemsSelectorDialogItem::mdtItemsSelectorDialogItem ()
Constructor.
Definition at line 24 of file mdtItemsSelectorDialogItem.cpp.
Member Function Documentation
int mdtItemsSelectorDialogItem::columnIndex () const inline
Get column index.
Definition at line 51 of file mdtItemsSelectorDialogItem.h.
QString mdtItemsSelectorDialogItem::name () const inline
Get name.
Name is a technical name, for example a field name, table name or else.
Definition at line 63 of file mdtItemsSelectorDialogItem.h.
Referenced by setName().
bool mdtItemsSelectorDialogItem::operator< (const mdtItemsSelectorDialogItem & other) const
Used by mdtItemsSelectorDialog to sort available items.
Definition at line 69 of file mdtItemsSelectorDialogItem.cpp.
void mdtItemsSelectorDialogItem::setColumnIndex (int index)
Set column index.
Definition at line 43 of file mdtItemsSelectorDialogItem.cpp.
void mdtItemsSelectorDialogItem::setName (const QString & name)
Set name.
Name is a technical name, for example a field name, table name or else.
Definition at line 48 of file mdtItemsSelectorDialogItem.cpp.
References name().
void mdtItemsSelectorDialogItem::setSortOrder (Qt::SortOrder order)
Set sort order.
Definition at line 53 of file mdtItemsSelectorDialogItem.cpp.
void mdtItemsSelectorDialogItem::setText (const QString & text)
Set text
Definition at line 30 of file mdtItemsSelectorDialogItem.cpp.
References text().
Qt::SortOrder mdtItemsSelectorDialogItem::sortOrder () const inline
Get sort order.
Definition at line 71 of file mdtItemsSelectorDialogItem.h.
QString mdtItemsSelectorDialogItem::sortOrderText () const
Get sort order text.
Definition at line 58 of file mdtItemsSelectorDialogItem.cpp.
Referenced by text().
QString mdtItemsSelectorDialogItem::text (bool includeSortOrderText = false) const
Get text.
Definition at line 35 of file mdtItemsSelectorDialogItem.cpp.
References sortOrderText().
Referenced by setText().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtItemsSelectorDialogItem.h
src/mdtutilsgui/mdtItemsSelectorDialogItem.cpp