Multi diag tools: mdtErrorOut Class Reference
mdtErrorOut Class Reference
Error output system Helper for error output. Outputs are the stderr output (console), a GUI messagebox and a logfile.
#include <mdtErrorOut.h>
Signals
void sigShowDialog (mdtError error)
Static Public Member Functions
static bool init (const QString &logFile)
Initialize the error output system.
static void setLogLevelsMask (int mask)
Set the log levels mask.
static void setDialogLevelsMask (int mask)
Set the dialog display levels mask.
static void addError (mdtError &error)
Add a error to the error output system.
static mdtErrorOut * instance ()
Get the instance of the error output system.
static QString logFile ()
Get the log file path.
static void destroy ()
Destroy the error output system instance.
static void setLogFileMaxSize (qint64 maxSize)
Set the maximum log file size [Byte] before backup.
Detailed Description
Error output system Helper for error output. Outputs are the stderr output (console), a GUI messagebox and a logfile.
Definition at line 38 of file mdtErrorOut.h.
Member Function Documentation
void mdtErrorOut::addError (mdtError & error) static
Add a error to the error output system.
Precondition
The system must be initialized.
See Also
init()
Definition at line 93 of file mdtErrorOut.cpp.
References mdtError::Error, mdtError::fileLine(), mdtError::fileName(), mdtError::functionName(), mdtError::Info, instance(), mdtError::level(), mdtError::number(), mdtErrorOutLogger::putData(), sigShowDialog(), mdtError::systemNumber(), mdtError::systemText(), mdtError::text(), and mdtError::Warning.
Referenced by mdtError::commit().
void mdtErrorOut::destroy () static
Destroy the error output system instance.
This function must be called from main thread (GUI thread)
Definition at line 184 of file mdtErrorOut.cpp.
Referenced by main(), and mdtApplication::~mdtApplication().
bool mdtErrorOut::init (const QString & logFile) static
Initialize the error output system.
After this call, the log and dialog levels are defined to Warning and Error This function must be called from main thread (GUI thread)
Definition at line 56 of file mdtErrorOut.cpp.
References instance(), mdtErrorOutLogger::setLogFilePath(), and sigShowDialog().
Referenced by mdtApplication::init(), and main().
mdtErrorOut * mdtErrorOut::instance () static
Get the instance of the error output system.
This function can return a Null pointer if init() was never called. This function, and returned pointer, should be used with care in multi-thread applicatopn !
Definition at line 170 of file mdtErrorOut.cpp.
Referenced by addError(), init(), logFile(), setDialogLevelsMask(), setLogFileMaxSize(), and setLogLevelsMask().
QString mdtErrorOut::logFile () static
Get the log file path.
Precondition
The system must be initialized.
See Also
init()
Definition at line 175 of file mdtErrorOut.cpp.
References instance(), and mdtErrorOutLogger::logFilePath().
void mdtErrorOut::setDialogLevelsMask (int mask) static
Set the dialog display levels mask.
The mask is a OR combinaison of mdtError::level_t flags
Precondition
The system must be initialized.
See Also
init()
Definition at line 84 of file mdtErrorOut.cpp.
References instance().
Referenced by mdtApplication::init(), and main().
void mdtErrorOut::setLogFileMaxSize (qint64 maxSize) static
Set the maximum log file size [Byte] before backup.
Definition at line 192 of file mdtErrorOut.cpp.
References instance(), and mdtErrorOutLogger::setLogFileMaxSize().
void mdtErrorOut::setLogLevelsMask (int mask) static
Set the log levels mask.
The mask is a OR combinaison of mdtError::level_t flags
Precondition
The system must be initialized.
See Also
init()
Definition at line 75 of file mdtErrorOut.cpp.
References instance().
void mdtErrorOut::sigShowDialog (mdtError error) signal
Referenced by addError(), and init().
The documentation for this class was generated from the following files:
src/mdtutils/mdtErrorOut.h
src/mdtutils/mdtErrorOut.cpp