Multi diag tools: mdtFileCopierItem Class Reference
mdtFileCopierItem Class Reference
This is a container class used by mdtFileCopier.
#include <mdtFileCopierItem.h>
Public Member Functions
mdtFileCopierItem (const QString &srcFilePath, const QString &destFilePath)
~mdtFileCopierItem ()
void setSrcFilePath (const QString &filePath)
Set the source file path.
QString & srcFilePath ()
Get the source file path.
void setSrcFileName (const QString &fileName)
Set the source file name (without directory path)
QString & srcFileName ()
Get the source file name (without directory path)
void setSrcDirectoryPath (const QString &directoryPath)
Set the source file'directory path.
QString & srcDirectoryPath ()
Get the source file path.
void setSrcFileHash (const QByteArray &hash)
Set the source file hash.
QByteArray & srcFileHash ()
Get the source file hash.
void setFileSize (qint64 size)
Set the file size.
qint64 fileSize ()
Get the file size.
void setDestFilePath (const QString &filePath)
Set the destination file path.
QString & destFilePath ()
Get the destination file path.
void setDestFileName (const QString &fileName)
Set the destination file name (without directory path)
QString & destFileName ()
Get the destination file name (without directory path)
void setDestDirectoryPath (const QString &directoryPath)
Set the destination file'directory path.
QString & destDirectoryPath ()
Get the source file path.
void setDestFileHash (const QByteArray &hash)
Set the destination file hash.
QByteArray & destFileHash ()
Get the destination file hash.
QString & copyText ()
Get text to display in progress dialog.
void setSyncAfterCopy (bool sync)
Set sync afetr copy flag.
bool syncAfterCopy ()
Get sync afetr copy flag.
void setCheckAfterCopy (bool check)
Set the check after copy flag.
bool checkAfterCopy ()
Get the check after copy flag.
Detailed Description
This is a container class used by mdtFileCopier.
Definition at line 29 of file mdtFileCopierItem.h.
Constructor & Destructor Documentation
mdtFileCopierItem::mdtFileCopierItem (const QString & srcFilePath, const QString & destFilePath)
Definition at line 24 of file mdtFileCopierItem.cpp.
References destFilePath(), and srcFilePath().
mdtFileCopierItem::~mdtFileCopierItem ()
Definition at line 33 of file mdtFileCopierItem.cpp.
Member Function Documentation
bool mdtFileCopierItem::checkAfterCopy ()
Get the check after copy flag.
See Also
setCheckAfterCopy()
Definition at line 173 of file mdtFileCopierItem.cpp.
QString & mdtFileCopierItem::copyText ()
Get text to display in progress dialog.
Definition at line 127 of file mdtFileCopierItem.cpp.
QString & mdtFileCopierItem::destDirectoryPath ()
Get the source file path.
Definition at line 112 of file mdtFileCopierItem.cpp.
QByteArray & mdtFileCopierItem::destFileHash ()
Get the destination file hash.
Definition at line 122 of file mdtFileCopierItem.cpp.
QString & mdtFileCopierItem::destFileName ()
Get the destination file name (without directory path)
Definition at line 102 of file mdtFileCopierItem.cpp.
QString & mdtFileCopierItem::destFilePath ()
Get the destination file path.
Definition at line 92 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopierItem(), and mdtFileCopier::startCopy().
qint64 mdtFileCopierItem::fileSize ()
Get the file size.
Definition at line 82 of file mdtFileCopierItem.cpp.
void mdtFileCopierItem::setCheckAfterCopy (bool check)
Set the check after copy flag.
If check is true, source and destination hash will be calculated (with SHA-1), and compared. If they don't match, the copy will be considered as failed.
Definition at line 168 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::addCopy().
void mdtFileCopierItem::setDestDirectoryPath (const QString & directoryPath)
Set the destination file'directory path.
Definition at line 107 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::startCopy().
void mdtFileCopierItem::setDestFileHash (const QByteArray & hash)
Set the destination file hash.
Definition at line 117 of file mdtFileCopierItem.cpp.
void mdtFileCopierItem::setDestFileName (const QString & fileName)
Set the destination file name (without directory path)
Definition at line 97 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::startCopy().
void mdtFileCopierItem::setDestFilePath (const QString & filePath)
Set the destination file path.
Definition at line 87 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::startCopy().
void mdtFileCopierItem::setFileSize (qint64 size)
Set the file size.
Definition at line 77 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::startCopy().
void mdtFileCopierItem::setSrcDirectoryPath (const QString & directoryPath)
Set the source file'directory path.
Definition at line 57 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::startCopy().
void mdtFileCopierItem::setSrcFileHash (const QByteArray & hash)
Set the source file hash.
Definition at line 67 of file mdtFileCopierItem.cpp.
void mdtFileCopierItem::setSrcFileName (const QString & fileName)
Set the source file name (without directory path)
Definition at line 47 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::startCopy().
void mdtFileCopierItem::setSrcFilePath (const QString & filePath)
Set the source file path.
Definition at line 37 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::startCopy().
void mdtFileCopierItem::setSyncAfterCopy (bool sync)
Set sync afetr copy flag.
If sync is true, fsync() (or OS equivalent) will be called after file copy.
Definition at line 158 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopier::addCopy().
QString & mdtFileCopierItem::srcDirectoryPath ()
Get the source file path.
Definition at line 62 of file mdtFileCopierItem.cpp.
QByteArray & mdtFileCopierItem::srcFileHash ()
Get the source file hash.
Definition at line 72 of file mdtFileCopierItem.cpp.
QString & mdtFileCopierItem::srcFileName ()
Get the source file name (without directory path)
Definition at line 52 of file mdtFileCopierItem.cpp.
QString & mdtFileCopierItem::srcFilePath ()
Get the source file path.
Definition at line 42 of file mdtFileCopierItem.cpp.
Referenced by mdtFileCopierItem(), and mdtFileCopier::startCopy().
bool mdtFileCopierItem::syncAfterCopy ()
Get sync afetr copy flag.
See Also
setSyncAfterCopy()
Definition at line 163 of file mdtFileCopierItem.cpp.
The documentation for this class was generated from the following files:
src/mdtutils/mdtFileCopierItem.h
src/mdtutils/mdtFileCopierItem.cpp