Multi diag tools: mdtClPathGraphicsLink Class Reference
mdtClPathGraphicsLink Class Reference
Item that represent a link in a graphics scene.
#include <mdtClPathGraphicsLink.h>
Public Types
enum { Type = UserType + 2 }
For QGraphicsView.
enum linkType_t { CableLink, Connection }
Public Member Functions
mdtClPathGraphicsLink (mdtClPathGraphicsConnection *startConnection, mdtClPathGraphicsConnection *endConnection)
Constructor.
void setText (const QString &text)
Set text.
void setLinkType (linkType_t type)
Set the link type.
mdtClPathGraphicsConnection * startConnection ()
Get start connection.
mdtClPathGraphicsConnection * endConnection ()
Get end connection.
void adjust ()
Adjust the start and end points of the link.
int type () const
Get type.
QRectF boundingRect () const
Get bounding rect.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Paint the link.
Detailed Description
Item that represent a link in a graphics scene.
Definition at line 39 of file mdtClPathGraphicsLink.h.
Member Enumeration Documentation
anonymous enum
For QGraphicsView.
Enumerator
Type
Definition at line 45 of file mdtClPathGraphicsLink.h.
enum mdtClPathGraphicsLink::linkType_t
Enumerator
CableLink
Connection
Cable link.
Connection
Definition at line 49 of file mdtClPathGraphicsLink.h.
Constructor & Destructor Documentation
mdtClPathGraphicsLink::mdtClPathGraphicsLink (mdtClPathGraphicsConnection * startConnection, mdtClPathGraphicsConnection * endConnection)
Constructor.
Definition at line 32 of file mdtClPathGraphicsLink.cpp.
References mdtClPathGraphicsConnection::addLink(), adjust(), endConnection(), and startConnection().
Member Function Documentation
void mdtClPathGraphicsLink::adjust ()
Adjust the start and end points of the link.
Definition at line 90 of file mdtClPathGraphicsLink.cpp.
Referenced by mdtClPathGraphicsConnection::addLink(), and mdtClPathGraphicsLink().
QRectF mdtClPathGraphicsLink::boundingRect () const
Get bounding rect.
Definition at line 110 of file mdtClPathGraphicsLink.cpp.
mdtClPathGraphicsConnection * mdtClPathGraphicsLink::endConnection ()
Get end connection.
Definition at line 85 of file mdtClPathGraphicsLink.cpp.
Referenced by mdtClPathGraphicsLink().
void mdtClPathGraphicsLink::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
Paint the link.
Definition at line 118 of file mdtClPathGraphicsLink.cpp.
void mdtClPathGraphicsLink::setLinkType (linkType_t type)
Set the link type.
This will affect the graphical representation of the link.
Note
: current version will only change color of the link ..
Definition at line 68 of file mdtClPathGraphicsLink.cpp.
References CableLink, and Connection.
void mdtClPathGraphicsLink::setText (const QString & text)
Set text.
Definition at line 46 of file mdtClPathGraphicsLink.cpp.
mdtClPathGraphicsConnection * mdtClPathGraphicsLink::startConnection ()
Get start connection.
Definition at line 80 of file mdtClPathGraphicsLink.cpp.
Referenced by mdtClPathGraphicsLink().
int mdtClPathGraphicsLink::type () const
Get type.
Definition at line 105 of file mdtClPathGraphicsLink.cpp.
References Type.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClPathGraphicsLink.h
src/mdttools/mdttesttool/mdtcablelist/mdtClPathGraphicsLink.cpp