Multi diag tools: mdtSqlFieldHandler Class Reference
mdtSqlFieldHandler Class Reference
Handle events between a SQL field and a edition widget.
#include <mdtSqlFieldHandler.h>
Public Slots
void updateFlags ()
Update some internal flags.
Signals
void dataEdited ()
Emitted the first time the user has edited data.
Public Member Functions
mdtSqlFieldHandler (QWidget *parent=0)
Construct a null field handler.
~mdtSqlFieldHandler ()
Destructor.
void setField (const QSqlField &field)
Set SQL field.
void setReadOnly (bool readOnly)
Set the readOnly flag.
bool isReadOnly () const
Get the readOnly flag.
void setDataWidget (QWidget *widget)
Set the edit/view widget.
void setDataWidget (QLineEdit *widget)
Set the edit/view widget.
void setDataWidget (QAbstractButton *widget)
Set the edit/view widget.
void setDataWidget (QDateTimeEdit *widget)
Set the edit/view widget.
void setDataWidget (QDoubleSpinBox *widget)
Set the edit/view widget.
void setDataWidget (QSpinBox *widget)
Set the edit/view widget.
QWidget * dataWidget ()
Get data widget Get current edit/view widget.
void clear ()
Clear.
void clearWidgetData ()
Clear widget's data.
bool isNull () const
Get the null flag.
bool dataWasEdited () const
Get the dataWasEdited flag.
bool checkBeforeSubmit ()
Make some checks before submit data.
void setData (const QVariant &data)
Set data widget's data.
QVariant data () const
Get data widget's data.
Properties
QVariant data
Detailed Description
Handle events between a SQL field and a edition widget.
When writing a GUI for a SQL database, Qt offers several classes. For example, QSqlTableModel, QDataWidgetMapper, QLineEdit, ...
mdtSqlFieldHandler add some functions that will help keeping the GUI more coherent with the underlaying database.
To use this class, first set the field with setField(), then add your edition/view widget with setDataWidget().
If field must be read only (independent of field access set in QSqlField), use setReaOnly().
Definition at line 53 of file mdtSqlFieldHandler.h.
Constructor & Destructor Documentation
mdtSqlFieldHandler::mdtSqlFieldHandler (QWidget * parent = 0)
Construct a null field handler.
See clear() for default flags.
Definition at line 140 of file mdtSqlFieldHandler.cpp.
References clear().
mdtSqlFieldHandler::~mdtSqlFieldHandler ()
Destructor.
Definition at line 148 of file mdtSqlFieldHandler.cpp.
Member Function Documentation
bool mdtSqlFieldHandler::checkBeforeSubmit ()
Make some checks before submit data.
Definition at line 294 of file mdtSqlFieldHandler.cpp.
References isNull().
void mdtSqlFieldHandler::clear ()
Clear.
Will unref (set to null) all internall widget pointers and set default flags.
Default flags are:
isReadOnly: false
isNull: true
dataWasEdited: false
Definition at line 246 of file mdtSqlFieldHandler.cpp.
Referenced by mdtSqlFieldHandler(), and setDataWidget().
void mdtSqlFieldHandler::clearWidgetData ()
Clear widget's data.
Will only clear the widget's content.
Definition at line 260 of file mdtSqlFieldHandler.cpp.
References mdtSqlFieldHandlerAbstractDataWidget::clear().
QVariant mdtSqlFieldHandler::data () const
Get data widget's data.
void mdtSqlFieldHandler::dataEdited () signal
Emitted the first time the user has edited data.
bool mdtSqlFieldHandler::dataWasEdited () const
Get the dataWasEdited flag.
Definition at line 289 of file mdtSqlFieldHandler.cpp.
QWidget * mdtSqlFieldHandler::dataWidget ()
Get data widget Get current edit/view widget.
Returns
A QWidget of current edit/view, or 0 if none was set.
Definition at line 220 of file mdtSqlFieldHandler.cpp.
References mdtSqlFieldHandlerAbstractDataWidget::widget().
Referenced by mdtSqlFormWidget::mappedWidgets().
bool mdtSqlFieldHandler::isNull () const
Get the null flag.
Definition at line 281 of file mdtSqlFieldHandler.cpp.
References mdtSqlFieldHandlerAbstractDataWidget::isNull().
Referenced by checkBeforeSubmit().
bool mdtSqlFieldHandler::isReadOnly () const
Get the readOnly flag.
Definition at line 165 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandler::setData (const QVariant & data)
Set data widget's data.
Definition at line 309 of file mdtSqlFieldHandler.cpp.
References mdtSqlFieldHandlerAbstractDataWidget::setData().
void mdtSqlFieldHandler::setDataWidget (QWidget * widget)
Set the edit/view widget.
Will search what type given widget is, cast it and store if found.
Precondition
widget must be a valid pointer.
Definition at line 170 of file mdtSqlFieldHandler.cpp.
References MDT_DATABASE_ERROR, MDT_ERROR_SET_SRC, and mdtError::Warning.
Referenced by mdtSqlFormWidget::mapFormWidgets().
void mdtSqlFieldHandler::setDataWidget (QLineEdit * widget)
Set the edit/view widget.
Precondition
widget must be a valid pointer.
Definition at line 187 of file mdtSqlFieldHandler.cpp.
References clear(), and mdtSqlFieldHandlerLineEdit::setLineEdit().
void mdtSqlFieldHandler::setDataWidget (QAbstractButton * widget)
Set the edit/view widget.
Precondition
widget must be a valid pointer.
Definition at line 200 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandler::setDataWidget (QDateTimeEdit * widget)
Set the edit/view widget.
Precondition
widget must be a valid pointer.
Definition at line 205 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandler::setDataWidget (QDoubleSpinBox * widget)
Set the edit/view widget.
Precondition
widget must be a valid pointer.
Definition at line 210 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandler::setDataWidget (QSpinBox * widget)
Set the edit/view widget.
Precondition
widget must be a valid pointer.
Definition at line 215 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandler::setField (const QSqlField & field)
Set SQL field.
Store the sql field. Some field's attributes will be used to handle edit/view widget.
Definition at line 153 of file mdtSqlFieldHandler.cpp.
Referenced by mdtSqlFormWidget::mapFormWidgets().
void mdtSqlFieldHandler::setReadOnly (bool readOnly)
Set the readOnly flag.
If set, readOnly flag will force the edit/view widget to be not editable.
Definition at line 159 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandler::updateFlags () slot
Update some internal flags.
Some flags, like Null flag, or data edited flag are updated here.
QDataWidgetMapper::currentIndexChanged() signal should be connected to this slot.
Definition at line 339 of file mdtSqlFieldHandler.cpp.
Property Documentation
QVariant mdtSqlFieldHandler::data read write
Definition at line 56 of file mdtSqlFieldHandler.h.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSqlFieldHandler.h
src/mdtutilsgui/mdtSqlFieldHandler.cpp