Multi diag tools: mdtTtBase Class Reference
mdtTtBase Class Reference
Base class for helper class.
#include <mdtTtBase.h>
Public Member Functions
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
template<typename T >
bool addRecordList (const QList< T > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField1, const QVariant &key1, const QString &matchField2, const QVariant &key2)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Protected Member Functions
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes
mdtError pvLastError
Detailed Description
Base class for helper class.
To edit entities (links, Article, Unit, ...) , dedicated classes helps for interaction with database .
This class is a base that regroups common methods .
Todo:
Should inherit QObject, because:
Use of tr()
Use QObject::destroyed() signal (see mdtTtTest for a typical usecase)
Definition at line 48 of file mdtTtBase.h.
Constructor & Destructor Documentation
mdtTtBase::mdtTtBase (QObject * parent, QSqlDatabase db)
Constructor.
Todo:
Add tr() in errors
Definition at line 30 of file mdtTtBase.cpp.
mdtTtBase::~mdtTtBase () virtual
Destructor.
Definition at line 36 of file mdtTtBase.cpp.
Member Function Documentation
bool mdtTtBase::addRecord (const mdtSqlRecord & record, const QString & tableName)
Add a record to given table.
Will only get values from fields that have a value. For this, mdtSqlRecord::hasValue() is used.
Definition at line 50 of file mdtTtBase.cpp.
References database().
Referenced by mdtClArticle::addCableLink(), mdtTtTestNodeUnit::addConnection(), mdtClArticle::addConnection(), mdtClUnit::addConnection(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtTtLogicalTestCable::addDutUnit(), mdtClLinkBeam::addEndUnit(), mdtTtTestModelItem::addItem(), mdtClDirectLink::addLink(), mdtClLink::addLink(), mdtTtLogicalTestCable::addLink(), mdtClArticle::addLink(), mdtTtTestNodeUnit::addNodeUnit(), mdtTtTestModelItem::addOrUpdateTestNodeUnitSetup(), addRecordList(), mdtTtTestModelItem::addRoute(), mdtClLinkBeam::addStartUnit(), mdtTtTestModelItem::addTestLink(), mdtTtTestModel::addTestNode(), mdtTtLogicalTestCable::addTestNodeUnit(), mdtTtLogicalTestCable::createCable(), and mdtTtTest::createTest().
bool mdtTtBase::addRecord (const mdtSqlRecord & record, const QString & tableName, QSqlQuery & query)
Add a record to given table.
Works the same way as addRecord(const mdtSqlRecord&, const QString&) , but uses given QSqlQuery object.
This can be useful, for example, if QSqlQuery::lastInsertId() must be used by insersion in multiple tables.
Definition at line 56 of file mdtTtBase.cpp.
References mdtError::commit(), mdtSqlRecord::dataToUpdateInfo(), mdtError::Error, mdtSqlRecord::fieldIndexesWithValue(), MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtError::setSystemError(), mdtSqlRecord::sqlForInsert(), and mdtSqlRecord::value().
template<typename T > bool mdtTtBase::addRecordList (const QList< T > & recordList, const QString & tableName, bool singleTransaction = false) inline
Add a list of records to given table.
If singleTransaction is true, a transaction will be used for adding all records. If you need to handle a transaction outside, set this parameter to false.
Definition at line 92 of file mdtTtBase.h.
References addRecord(), beginTransaction(), commitTransaction(), and rollbackTransaction().
Referenced by mdtClArticle::addConnector().
bool mdtTtBase::beginTransaction () protected
Beginn manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 424 of file mdtTtBase.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtClUnit::addConnection(), mdtTtTestNodeUnit::addConnections(), mdtClUnit::addConnections(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtTtTestModelItem::addItem(), mdtClLink::addLink(), mdtClLink::addLinks(), mdtTtTestNode::addMissingConnections(), mdtTtTestNodeUnit::addNodeUnit(), mdtTtTestModelItem::addOrUpdateTestNodeUnitSetupList(), addRecordList(), mdtTtTestModelItem::addRoute(), mdtTtLogicalTestCable::createCable(), mdtTtTest::createTest(), mdtClLink::disconnectConnectors(), mdtClLink::editLink(), mdtTtLogicalTestCable::editLink(), mdtTtTestModel::generateTestModel(), mdtClUnit::removeConnection(), mdtTtTestNodeUnit::removeConnections(), mdtClUnit::removeConnections(), mdtClArticle::removeConnector(), mdtClUnit::removeConnector(), mdtClArticle::removeConnectors(), removeData(), mdtClLink::removeLink(), mdtClLinkBeam::removeLinks(), mdtClLink::removeLinks(), mdtClArticle::removeLinks(), mdtTtTestNodeUnit::removeNodeUnit(), mdtTtTestNodeUnit::removeNodeUnits(), mdtTtTest::removeTest(), mdtTtTestModel::removeTestModelItem(), mdtTtTestModel::removeTestModelItems(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), mdtTtTest::saveTest(), mdtTtTestNodeUnit::setBusIdToConnections(), mdtTtTestNode::setTestNodeUnitIoRange(), and mdtClArticle::updateUnitConnections().
bool mdtTtBase::commitTransaction () protected
Commit manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 450 of file mdtTtBase.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtClUnit::addConnection(), mdtTtTestNodeUnit::addConnections(), mdtClUnit::addConnections(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtTtTestModelItem::addItem(), mdtClLink::addLink(), mdtClLink::addLinks(), mdtTtTestNode::addMissingConnections(), mdtTtTestNodeUnit::addNodeUnit(), mdtTtTestModelItem::addOrUpdateTestNodeUnitSetupList(), addRecordList(), mdtTtTestModelItem::addRoute(), mdtTtLogicalTestCable::createCable(), mdtTtTest::createTest(), mdtClLink::disconnectConnectors(), mdtClLink::editLink(), mdtTtLogicalTestCable::editLink(), mdtTtTestModel::generateTestModel(), mdtClUnit::removeConnection(), mdtTtTestNodeUnit::removeConnections(), mdtClUnit::removeConnections(), mdtClArticle::removeConnector(), mdtClUnit::removeConnector(), mdtClArticle::removeConnectors(), removeData(), mdtClLink::removeLink(), mdtClLinkBeam::removeLinks(), mdtClLink::removeLinks(), mdtClArticle::removeLinks(), mdtTtTestNodeUnit::removeNodeUnit(), mdtTtTestNodeUnit::removeNodeUnits(), mdtTtTest::removeTest(), mdtTtTestModel::removeTestModelItem(), mdtTtTestModel::removeTestModelItems(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), mdtTtTest::saveTest(), mdtTtTestNodeUnit::setBusIdToConnections(), mdtTtTestNode::setTestNodeUnitIoRange(), and mdtClArticle::updateUnitConnections().
QSqlDatabase mdtTtBase::database ()
Get database instance.
Definition at line 40 of file mdtTtBase.cpp.
Referenced by mdtClUnit::addArticleConnectorData(), mdtTtLogicalTestCable::addCable(), mdtClArticle::addCableLink(), mdtClArticle::addComponent(), mdtClUnit::addComponent(), mdtTtTestNodeUnit::addConnection(), mdtClUnit::addConnection(), mdtClArticle::addConnectionDataListFromConnectorContactIdList(), mdtClUnit::addConnectionDataListFromConnectorContactIdList(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtTtLogicalTestCable::addDutUnit(), mdtClLinkBeam::addEndUnit(), mdtTtTestModelItem::addItem(), mdtClLinkBeam::addLink(), mdtTtLogicalTestCable::addLink(), mdtClDirectLink::addLinksByUnitConnector(), mdtTtTestNode::addMissingConnections(), addRecord(), mdtTtTestModelItem::addRoute(), mdtTtTestModel::addRoutesToItemData(), mdtClLinkBeam::addStartUnit(), mdtTtTestModelItem::addTestLink(), mdtTtTestModel::addTestNode(), mdtTtLogicalTestCable::addTestNodeUnit(), mdtTtTestModelItem::addTestNodeUnitSetup(), mdtClUnitVehicleType::addUnitVehicleTypeAssignments(), mdtTtTestModel::buildRouteData(), mdtClLink::canConnectConnections(), mdtClLink::canConnectConnectors(), mdtClLink::connectByContactName(), mdtTtLogicalTestCable::createCable(), mdtTtTest::createTest(), mdtClArticle::editComponent(), mdtClArticle::editLink(), mdtTtTestModel::generateTestModel(), mdtTtTestNode::getChannelTestConnectionIdList(), mdtClArticle::getConnectionDataListFromConnectionIdList(), mdtTtTestNodeUnit::getConnectionIdListLinkedToConnectionIdList(), mdtTtTestNodeUnit::getData(), getData(), getDataList(), mdtTtTestNode::getIdListOfUnitConnectionsLinkedToUnitConnectionId(), mdtTtTestNode::getIdListOfUnitConnectionsPartOfUnit(), mdtTtTestNode::getIdListOfUnitIdForUnitConnectionIdList(), mdtTtTestNode::getLinkDataListForPath(), mdtTtTest::getLinkDataListForRoute(), mdtTtTestModel::getListOfTestItemIdListByTestId(), mdtTtTestModel::getListOfUnusedNodeUnitIdListByTestId(), mdtTtTestModel::getListOfUsedNodeIdListByTestId(), mdtTtTestModel::getNextSequenceNumber(), mdtTtTestNode::getRelayPathSetupDataList(), mdtTtTestModelItem::getTestNodeUnitSetupIdList(), mdtTtTestModel::getTestNodeUnitSetupIdList(), mdtTtLogicalTestCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector(), mdtTtLogicalTestCable::getToUnitConnectionLinkedUnitConnectorIdList(), mdtTtLogicalTestCable::getToUnitConnectorRelatedUnitConnectionIdList(), mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList(), mdtTtTestModelItem::getUsedNodeUnitIdList(), mdtClLink::getVehicleTypeLinkDataByUnitId(), mdtClArticle::removeComponents(), mdtClUnit::removeComponents(), mdtClArticle::removeConnections(), mdtClArticle::removeConnectorsConnections(), removeData(), mdtClLinkBeam::removeLink(), mdtTtTestModelItem::removeTestNodeUnitSetup(), mdtTtTestModelItem::removeTestNodeUnitSetupsForTestItemId(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), mdtTtTestNode::setTestNodeUnitIoRange(), mdtClUnit::toUnitRelatedArticleConnectionCount(), updateRecord(), mdtTtTestModelItem::updateTestNodeUnitData(), and mdtClArticle::updateUnitConnections().
QList< QSqlRecord > mdtTtBase::getData (const QString & sql, bool * ok = 0, const QStringList & expectedFields = QStringList())
Get data for given sql statement.
Note that this method will not check if given SQL statement makes a SELECT, INSERT, etc.. It is simply executed.
Parameters
sql SQL statement
ok If not null, this pointer will contain true on success, false else (in that case, lastError() will contain error).
expectedFields If not empty, it will be checked that query result contains all listed fields, and fail if some fields are missing.
bool mdtTtBase::addRecordList(const QList<mdtSqlRecord> & recordList, const QString & tableName, bool singleTransaction) { int i;
if(singleTransaction){ if(!beginTransaction()){ return false; } } for(i = 0; i < recordList.size(); ++i){ if(!addRecord(recordList.at(i), tableName)){ if(singleTransaction){ rollbackTransaction(); } return false; } } if(singleTransaction){ if(!commitTransaction()){ return false; } }
return true; }
Definition at line 129 of file mdtTtBase.cpp.
References database().
Referenced by mdtTtTestNode::addMissingConnections(), mdtClLink::disconnectConnectors(), mdtClUnit::getConnectionIdListPartOfConnectorId(), mdtClArticle::getConnectorContactDataList(), mdtClUnit::getConnectorIdOfConnectionId(), mdtTtTestNodeUnit::getData(), mdtTtLogicalTestCable::getLinkData(), mdtTtTestNode::getTestNodeData(), mdtTtTestModelItem::getTestNodeUnitSetupData(), mdtClDirectLink::getUnitConnectionIdListPartOfUnit(), mdtClDirectLink::getUnitConnectionIdListPartOfUnitConnector(), mdtClUnit::getUnitConnectorIdBasedOnArticleConnectorId(), mdtTtTestNodeUnit::getUnitData(), mdtClLink::getVehicleTypeLinkDataByUnitId(), mdtClUnit::removeConnector(), mdtTtTestNodeUnit::setBusIdToConnection(), mdtTtTestModelItem::testNodeUnitSetupExists(), and mdtClUnit::toUnitRelatedLinksList().
template<typename T > QList<T> mdtTtBase::getDataList (const QString & sql, bool & ok, const QStringList & expectedFields = QStringList()) inline
Get data of type T for given sql statement.
Note that this method will not check if given SQL statement makes a SELECT, INSERT, etc.. It is simply executed.
T can be QSqlRecord, QVariant or a type that QVariant can handle.
Parameters
sql SQL statement
ok Will contain true on success, false else (in that case, lastError() will contain error).
expectedFields If not empty, it will be checked that query result contains all listed fields, and fail if some fields are missing.
Precondition
If T is another type than QSqlRecord, sql must select exactly on field.
Definition at line 147 of file mdtTtBase.h.
References database().
Referenced by mdtTtLogicalTestCableDutWidget::containsTestCableConnection(), mdtTtLogicalTestCableTsWidget::containsTestCableConnection(), mdtTtLogicalTestCableDutWidget::getAffectedDutConnections(), mdtTtLogicalTestCableTsWidget::getAffectedTsConnections(), mdtTtLogicalTestCableDutWidget::setDutUnit(), mdtTtLogicalTestCableDialog::setTestCable(), and mdtTtLogicalTestCableTsWidget::setTestSystem().
mdtError mdtTtBase::lastError ()
Get last error.
Definition at line 45 of file mdtTtBase.cpp.
References pvLastError.
Referenced by mdtClUnit::addArticleConnectorData(), mdtClDirectLink::addLinksByUnitConnector(), mdtTtTestNode::addMissingConnections(), mdtClLink::canConnectConnections(), mdtClLink::canConnectConnectors(), mdtClLink::connectByContactName(), mdtTtLogicalTestCableDutWidget::containsTestCableConnection(), mdtTtLogicalTestCableTsWidget::containsTestCableConnection(), mdtTtTestModel::generateTestModel(), mdtTtLogicalTestCableDutWidget::getAffectedDutConnections(), mdtTtLogicalTestCableTsWidget::getAffectedTsConnections(), mdtTtTest::getLinkDataListForRoute(), mdtClPathGraph::getLinkedConnectorIdList(), mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList(), and mdtTtLogicalTestCableDialog::setTestCable().
bool mdtTtBase::removeData (const QString & tableName, const QStringList & fields, const QModelIndexList & indexes)
Remove data from given table.
This method can be used with result of mdtSqlTableWidget::indexListOfSelectedRows() (the indexes part) .
Parameters
tableName Name of table in witch data must be removed .
fields List of fields. Be shure that this list matches exactly with given indexes .
indexes In each index, the column will be used to find field name, and data is used for row condition .
Definition at line 218 of file mdtTtBase.cpp.
References mdtError::commit(), database(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtError::setSystemError(), and sqlDataDelimiter().
Referenced by mdtClArticle::removeComponent(), mdtTtTestNodeUnit::removeConnection(), mdtClUnit::removeConnection(), mdtClArticle::removeConnector(), mdtClUnit::removeConnector(), mdtClArticle::removeConnectors(), removeData(), mdtTtLogicalTestCable::removeDutUnits(), mdtClLinkBeam::removeEndUnit(), mdtClLinkBeam::removeEndUnits(), mdtClLink::removeLink(), mdtTtLogicalTestCable::removeLink(), mdtClArticle::removeLink(), mdtTtTestNodeUnit::removeNodeUnit(), mdtTtTestModelItem::removeRoutes(), mdtClLinkBeam::removeStartUnit(), mdtClLinkBeam::removeStartUnits(), mdtTtTest::removeTest(), mdtTtTestModelItem::removeTestLinks(), mdtTtTestModel::removeTestModelItem(), mdtTtTestModel::removeTestNodes(), mdtTtLogicalTestCable::removeTestNodeUnits(), and mdtTtTestModelItem::removeTestNodeUnitSetups().
bool mdtTtBase::removeData (const QString & tableName, const QString & fieldName, const QModelIndexList & indexes)
Remove data from given table.
This method works for a single field .
See Also
removeData(const QString &, const QStringList &, const QModelIndexList &)
Definition at line 279 of file mdtTtBase.cpp.
References removeData().
bool mdtTtBase::removeData (const QString & tableName, const QString & fieldName, const QVariant & matchData)
Remove data from given table.
Parameters
tableName Name of table in witch data must be removed .
fieldName Name of field that contains delete condition .
matchData Data that match delete condition .
Definition at line 284 of file mdtTtBase.cpp.
References mdtError::commit(), database(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtError::setSystemError(), and sqlDataDelimiter().
bool mdtTtBase::removeData (const QString & tableName, const QString & fieldName1, const QVariant & matchData1, const QString & fieldName2, const QVariant & matchData2)
Remove data from given table.
This variant is typically usefull for tables containing 2 primary keys. Will only remove rows that match the 2 fields (condition 1 AND condition 2).
Parameters
tableName Name of table in witch data must be removed .
fieldName1 Name of first field that contains delete condition .
matchData1 Data that match delete condition for first field.
fieldName2 Name of second field that contains delete condition .
matchData2 Data that match delete condition for second field.
Definition at line 310 of file mdtTtBase.cpp.
References mdtError::commit(), database(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtError::setSystemError(), and sqlDataDelimiter().
bool mdtTtBase::removeData (const QString & tableName, const mdtSqlTableSelection & s, bool handleTransaction)
Remove data in given selection from given table.
A SQL statement will be built with a filter (WHERE clause). For a given row, each field will be added with a AND clause. Each row will be separated with a OR clause.
For example, if we want to remove data from AB_tbl, and have following data in the selection:
Row Field name Data
0 A_Id_FK 1
0 B_Id_FK 10
1 A_Id_FK 2
1 B_Id_FK 20
the query will be: DELETE FROM AB_tbl WHERE (A_Id_FK=1 AND B_Id_FK=10) OR (A_Id_FK=2 AND B_Id_FK=20)
Parameters
tableName Name of table in witch data must be removed.
s Selection (see detailed description).
handleTransaction If true, a transaction will be initiated internally.
Definition at line 335 of file mdtTtBase.cpp.
References beginTransaction(), mdtError::commit(), commitTransaction(), mdtSqlTableSelection::data(), database(), mdtError::Error, mdtSqlTableSelection::fields(), mdtSqlTableSelection::isEmpty(), MDT_ERROR_SET_SRC, pvLastError, rollbackTransaction(), mdtSqlTableSelection::rowCount(), mdtError::setError(), mdtError::setSystemError(), and sqlDataDelimiter().
bool mdtTtBase::rollbackTransaction () protected
Rollback manually a new transaction.
On error, false is returned and error is available with lastError() .
Definition at line 437 of file mdtTtBase.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtClUnit::addConnection(), mdtTtTestNodeUnit::addConnections(), mdtClUnit::addConnections(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtTtTestModelItem::addItem(), mdtClLink::addLink(), mdtClLink::addLinks(), mdtTtTestNode::addMissingConnections(), mdtTtTestNodeUnit::addNodeUnit(), mdtTtTestModelItem::addOrUpdateTestNodeUnitSetupList(), addRecordList(), mdtTtTestModelItem::addRoute(), mdtTtLogicalTestCable::createCable(), mdtTtTest::createTest(), mdtClLink::disconnectConnectors(), mdtClLink::editLink(), mdtTtLogicalTestCable::editLink(), mdtTtTestModel::generateTestModel(), mdtClUnit::removeConnection(), mdtTtTestNodeUnit::removeConnections(), mdtClUnit::removeConnections(), mdtClArticle::removeConnector(), mdtClUnit::removeConnector(), mdtClArticle::removeConnectors(), removeData(), mdtClLink::removeLink(), mdtClLinkBeam::removeLinks(), mdtClLink::removeLinks(), mdtClArticle::removeLinks(), mdtTtTestNodeUnit::removeNodeUnit(), mdtTtTestNodeUnit::removeNodeUnits(), mdtTtTest::removeTest(), mdtTtTestModel::removeTestModelItem(), mdtTtTestModel::removeTestModelItems(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), mdtTtTest::saveTest(), mdtTtTestNodeUnit::setBusIdToConnections(), mdtTtTestNode::setTestNodeUnitIoRange(), and mdtClArticle::updateUnitConnections().
QString mdtTtBase::sqlDataDelimiter (QVariant::Type type) protected
Get SQL data delimiter for given data type.
Definition at line 463 of file mdtTtBase.cpp.
References mdtSqlRecord::sqlDataDelimiter().
Referenced by removeData().
bool mdtTtBase::updateRecord (const QString & tableName, const mdtSqlRecord & record, const QSqlRecord & matchData)
Update data for given table.
Parameters
tableName Name of table in witch data must be updated.
record Record containing data to update.
matchData Records that contains conditions. For each field, a condition of type fieldName = fieldValue is added.
Definition at line 151 of file mdtTtBase.cpp.
References mdtError::commit(), database(), mdtError::Error, mdtSqlRecord::fieldIndexesWithValue(), MDT_ERROR_SET_SRC, pvLastError, mdtError::setError(), mdtError::setSystemError(), mdtSqlRecord::sqlForUpdate(), and mdtSqlRecord::value().
Referenced by mdtClLinkBeam::addLink(), mdtClArticle::editConnection(), mdtClUnit::editConnection(), mdtClArticle::editConnectorName(), mdtClUnit::editConnectorName(), mdtClLink::editLink(), mdtClArticle::editLink(), mdtTtTestNodeUnit::editNodeUnit(), mdtClLinkBeam::removeLink(), mdtTtTest::saveTest(), mdtTtTestNodeUnit::setBusIdToConnection(), mdtTtTestNode::setTestNodeUnitIoRange(), updateRecord(), mdtTtTestModelItem::updateTestNodeUnitData(), and mdtClArticle::updateUnitConnections().
bool mdtTtBase::updateRecord (const QString & tableName, const mdtSqlRecord & record, const QString & matchField, const QVariant & matchData)
Update data for given table.
Parameters
tableName Name of table in witch data must be updated.
record Record containing data to update.
matchField Field that contains condition.
matchData Data that contains conditions.
Definition at line 185 of file mdtTtBase.cpp.
References mdtSqlRecord::addField(), database(), mdtSqlRecord::lastError(), pvLastError, mdtSqlRecord::setValue(), and updateRecord().
bool mdtTtBase::updateRecord (const QString & tableName, const mdtSqlRecord & record, const QString & matchField1, const QVariant & key1, const QString & matchField2, const QVariant & key2)
Update data for given table.
Parameters
tableName Name of table in witch data must be updated.
record Record containing data to update.
matchField1 Field for witch key1 must match.
key1 Key that matches matchField1.
matchField2 Field for witch key2 must match.
key2 Key that matches matchField2.
Definition at line 198 of file mdtTtBase.cpp.
References mdtSqlRecord::addField(), database(), mdtSqlRecord::lastError(), pvLastError, mdtSqlRecord::setValue(), and updateRecord().
Member Data Documentation
mdtError mdtTtBase::pvLastError protected
Definition at line 283 of file mdtTtBase.h.
Referenced by mdtClUnit::addArticleConnectorData(), mdtTtLogicalTestCable::addCable(), mdtClArticle::addCableLink(), mdtClArticle::addComponent(), mdtClUnit::addComponent(), mdtTtTestNodeUnit::addConnection(), mdtClArticle::addConnectionDataListFromConnectorContactIdList(), mdtClUnit::addConnectionDataListFromConnectorContactIdList(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtTtLogicalTestCable::addDutUnit(), mdtClLinkBeam::addEndUnit(), mdtClDirectLink::addLink(), mdtClLinkBeam::addLink(), mdtTtLogicalTestCable::addLink(), mdtClDirectLink::addLinksByUnitConnector(), mdtTtTestNode::addMissingConnections(), addRecord(), mdtTtTestModelItem::addRoute(), mdtTtTestModel::addRoutesToItemData(), mdtClLinkBeam::addStartUnit(), mdtTtTestModelItem::addTestLink(), mdtTtTestModel::addTestNode(), mdtTtLogicalTestCable::addTestNodeUnit(), mdtTtTestModelItem::addTestNodeUnitSetup(), mdtClUnitVehicleType::addUnitVehicleTypeAssignments(), beginTransaction(), mdtTtTestModel::buildRouteData(), mdtClLink::canConnectConnections(), mdtClLink::canConnectConnectors(), commitTransaction(), mdtClLink::connectByContactName(), mdtTtLogicalTestCable::createCable(), mdtTtTest::createTest(), mdtClArticle::editComponent(), mdtClArticle::editLink(), mdtTtTestNodeUnit::editNodeUnit(), mdtTtTestNode::ensureAbsenceOfShortCircuit(), mdtTtTestModel::generateTestModel(), mdtTtTestNode::getChannelTestConnectionIdList(), mdtClUnit::getConnectionData(), mdtClArticle::getConnectionData(), mdtClArticle::getConnectionDataListFromConnectionIdList(), mdtTtTest::getConnectionId(), mdtTtTestNodeUnit::getConnectionIdListLinkedToConnectionIdList(), mdtClArticle::getConnectorData(), mdtClUnit::getConnectorData(), mdtTtTestNodeUnit::getData(), mdtTtTestNode::getIdListOfUnitConnectionsLinkedToUnitConnectionId(), mdtTtTestNode::getIdListOfUnitConnectionsPartOfUnit(), mdtTtTestNode::getIdListOfUnitIdForUnitConnectionIdList(), mdtClLink::getLinkData(), mdtTtLogicalTestCable::getLinkData(), mdtTtTestNode::getLinkDataListForPath(), mdtTtTest::getLinkDataListForRoute(), mdtTtTestModel::getListOfTestItemIdListByTestId(), mdtTtTestModel::getListOfUnusedNodeUnitIdListByTestId(), mdtTtTestModel::getListOfUsedNodeIdListByTestId(), mdtTtTestModel::getNextSequenceNumber(), mdtTtTestNode::getRelayPathSetupDataList(), mdtTtTestModel::getTestLinkIdListForDutConnectionId(), mdtTtTestModel::getTestModelData(), mdtTtTest::getTestNodeSetupData(), mdtTtTestModelItem::getTestNodeUnitSetupIdList(), mdtTtTestModel::getTestNodeUnitSetupIdList(), mdtTtLogicalTestCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector(), mdtTtLogicalTestCable::getToUnitConnectionLinkedUnitConnectorIdList(), mdtTtLogicalTestCable::getToUnitConnectorRelatedUnitConnectionIdList(), mdtClUnit::getUnitConnectionDataListFromArticleConnectionIdList(), mdtClUnit::getUnitConnectorIdBasedOnArticleConnectorId(), mdtTtTestNodeUnit::getUnitData(), mdtTtTestModelItem::getUsedNodeUnitIdList(), lastError(), mdtTtLogicalTestCable::loadLinkList(), mdtClArticle::removeComponents(), mdtClUnit::removeComponents(), mdtClArticle::removeConnections(), mdtClArticle::removeConnectorsConnections(), removeData(), mdtClLinkBeam::removeLink(), mdtTtTestModelItem::removeTestNodeUnitSetup(), mdtTtTestModelItem::removeTestNodeUnitSetupsForTestItemId(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), rollbackTransaction(), mdtTtTestNode::setTestNodeUnitIoRange(), mdtClLink::sqlForConnectableUnitConnectionsSelection(), mdtClLink::sqlForConnectableUnitConnectorsSelection(), mdtClUnit::toUnitRelatedArticleConnectionCount(), updateRecord(), mdtTtTestModelItem::updateTestNodeUnitData(), and mdtClArticle::updateUnitConnections().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtBase.h
src/mdttools/mdttesttool/mdtTtBase.cpp