Multi diag tools: mdtLed Class Reference
mdtLed Class Reference
mdtLED is a widget witch displays a LED
#include <mdtLed.h>
Public Types
enum color_t { Green, Orange, Red }
LED predefined colors.
Public Slots
void setOn ()
Set the LED ON.
void setOff ()
Set the LED OFF.
void setOn (bool on)
Set the LED ON or OFF.
void toggleOnOff ()
Toggle On/Off.
Public Member Functions
mdtLed (QWidget *parent=0)
Contruct a new mdtLED.
void setBorders (int horizontalBorder, int verticalBorder)
Set the borders.
void setGreen ()
Set the LED color to green.
void setOrange ()
Set the LED color to orange.
void setRed ()
Set the LED color to red.
void setColor (color_t color)
Set the LED color.
void setFlat ()
Set a simple flat LED.
void setGlint ()
Set a glint LED.
void setTextMode ()
Set the LED as text.
void setAntialiasing (bool enabled)
Enable the antialiasing.
void setFixedSize (int width, int height)
Force the LED to have a fixed size.
void setAutoSize ()
Use Qt QSizePolicy to resize the LED.
QSize sizeHint () const
QSize minimumSizeHint () const
bool isOn ()
Get the LED ON state.
Protected Member Functions
void paintEvent (QPaintEvent *)
Detailed Description
mdtLED is a widget witch displays a LED
Definition at line 35 of file mdtLed.h.
Member Enumeration Documentation
enum mdtLed::color_t
LED predefined colors.
Enumerator
Green
Green LED
Orange
Orange LED
Red
Red LED
Definition at line 43 of file mdtLed.h.
Constructor & Destructor Documentation
mdtLed::mdtLed (QWidget * parent = 0)
Contruct a new mdtLED.
Definition at line 27 of file mdtLed.cpp.
References setBorders(), setGlint(), setGreen(), and setOff().
Member Function Documentation
bool mdtLed::isOn ()
Get the LED ON state.
Definition at line 155 of file mdtLed.cpp.
QSize mdtLed::minimumSizeHint () const
Definition at line 150 of file mdtLed.cpp.
void mdtLed::paintEvent (QPaintEvent *) protected
Definition at line 196 of file mdtLed.cpp.
void mdtLed::setAntialiasing (bool enabled)
Enable the antialiasing.
Parameters
enabled If true, antialiasing will be enabled (else, diseabled)
Definition at line 114 of file mdtLed.cpp.
void mdtLed::setAutoSize ()
Use Qt QSizePolicy to resize the LED.
Use the Qt default QSizePolicy (see the QLayout and QWidget references for details) This is the default behaviour if setFixedSize() was never called.
Definition at line 136 of file mdtLed.cpp.
void mdtLed::setBorders (int horizontalBorder, int verticalBorder)
Set the borders.
The LED will be drawn in the center, with horizontal and vertical specified spaces.
Parameters
horizontalBorder Set the horizontal borders (will be the same at left and right of the LED)
verticalBorder Set the vertical borders (will be the same at top and bottom of the LED)
Definition at line 48 of file mdtLed.cpp.
Referenced by mdtLed().
void mdtLed::setColor (mdtLed::color_t color)
Set the LED color.
Definition at line 83 of file mdtLed.cpp.
References Green, Orange, Red, setGreen(), setOrange(), and setRed().
Referenced by mdtPortStatusWidget::setState().
void mdtLed::setFixedSize (int width, int height)
Force the LED to have a fixed size.
By default, ldtLED uses the Qt default QSizePolicy Wenn calling this method, the LED will keep a fixed size
Parameters
width The width (min. 10)
height The height (min. 10)
Definition at line 119 of file mdtLed.cpp.
Referenced by mdtPortStatusWidget::enableTxRxLeds(), mdtDigitalInWidget::mdtDigitalInWidget(), mdtPortStatusWidget::mdtPortStatusWidget(), and mdtSerialPortCtlWidget::mdtSerialPortCtlWidget().
void mdtLed::setFlat ()
Set a simple flat LED.
The color will be uniform on the LED surface
Definition at line 98 of file mdtLed.cpp.
void mdtLed::setGlint ()
Set a glint LED.
This will use the Qt::RadialGradientPattern brush style This can slow down the application with many LED's. For better performance, use setFlat() .
Definition at line 104 of file mdtLed.cpp.
Referenced by mdtLed().
void mdtLed::setGreen ()
Set the LED color to green.
Definition at line 56 of file mdtLed.cpp.
Referenced by mdtPortStatusWidget::enableTxRxLeds(), mdtLed(), and setColor().
void mdtLed::setOff () slot
Set the LED OFF.
Definition at line 169 of file mdtLed.cpp.
Referenced by mdtLed(), mdtBlinkLed::setOff(), setOn(), and toggleOnOff().
void mdtLed::setOn () slot
Set the LED ON.
Definition at line 160 of file mdtLed.cpp.
Referenced by mdtBlinkLed::setOn(), setOn(), and toggleOnOff().
void mdtLed::setOn (bool on) slot
Set the LED ON or OFF.
Parameters
on If true, the LED is set ON , else OFF
Definition at line 178 of file mdtLed.cpp.
References setOff(), and setOn().
void mdtLed::setOrange ()
Set the LED color to orange.
Definition at line 65 of file mdtLed.cpp.
Referenced by setColor().
void mdtLed::setRed ()
Set the LED color to red.
Definition at line 74 of file mdtLed.cpp.
Referenced by setColor().
void mdtLed::setTextMode ()
Set the LED as text.
The LED will display a ON/OFF text instead a color
Definition at line 109 of file mdtLed.cpp.
QSize mdtLed::sizeHint () const
Definition at line 145 of file mdtLed.cpp.
void mdtLed::toggleOnOff () slot
Toggle On/Off.
Definition at line 187 of file mdtLed.cpp.
References setOff(), and setOn().
Referenced by mdtBlinkLed::mdtBlinkLed().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtLed.h
src/mdtutilsgui/mdtLed.cpp