Multi diag tools: mdtTtBasicTestNodeCalibrationTool Class Reference
mdtTtBasicTestNodeCalibrationTool Class Reference
#include <mdtTtBasicTestNodeCalibrationTool.h>
Public Slots
void runCalibration ()
Run calibration.
void saveCalibration ()
Save calibration.
Public Member Functions
mdtTtBasicTestNodeCalibrationTool (QSqlDatabase db, QObject *parent=0)
Constructor.
bool setup (QWidget *testNodeFormWidget)
Do setup.
Public Member Functions inherited from mdtTtAbstractTestNodeCalibrationTool
mdtTtAbstractTestNodeCalibrationTool (QSqlDatabase db, QObject *parent=0)
Constructor.
bool setTestNode (const QVariant &testNodeId)
Set test node to calibrate.
QSqlDatabase database ()
Get database instance.
std::shared_ptr
< mdtSqlTableViewController > testNodeUnitViewTableController ()
Get table controller to access data in TestNodeUnit_view.
std::shared_ptr
< mdtTtTestNodeManager > testNodeManager ()
Get test node manager object.
std::shared_ptr< mdtTtTest > test ()
Get test object.
QVariant currentTestNodeData (const QString &fieldName)
Get current test node data for given field.
QVariant testNodeUnitData (int testNodeUnitId, const QString &fieldName)
Get test node unit data for given test node unit ID and field name.
QVariant testNodeUnitData (const QString &schemaPosition, const QString &fieldName)
Get test node unit data for given test node unit schema position and field name.
bool setTestNodeUnitData (int testNodeUnitId, const QString &fieldName, const QVariant &data)
Set test node unit data for given test node unit ID and field name.
bool setTestNodeUnitData (const QString &schemaPosition, const QString &fieldName, const QVariant &data)
Set test node unit data for given test node unit schemaPosition and field name.
bool setTestNodeUnitCalibrationOffset (int testNodeUnitId, double offset)
Set calibration offset for given testNodeUnitId.
bool setTestNodeUnitCalibrationOffset (const QString &schemaPosition, double offset)
Set calibration offset for given test node unit schemaPosition.
bool saveTestNodeUnitCalibrationOffsets ()
Save calibration results to TestNodeUnit_tbl.
Additional Inherited Members
Protected Member Functions inherited from mdtTtAbstractTestNodeCalibrationTool
void displayLastError ()
Display last error to the user.
void displayMessage (const QString &text, const QString &informativeText=QString(), QMessageBox::Icon icon=QMessageBox::Information)
Display a message to the user.
bool promptUser (const QString &text, const QString &informativeText=QString(), QMessageBox::Icon icon=QMessageBox::Information, QMessageBox::StandardButtons buttons=(QMessageBox::Ok|QMessageBox::Cancel))
Prompt the user to do a action.
bool askUser (const QString &text, const QString &informativeText=QString(), QMessageBox::Icon icon=QMessageBox::Question, QMessageBox::StandardButtons buttons=(QMessageBox::Ok|QMessageBox::No|QMessageBox::Cancel))
Ask a question to the user.
bool isInRange (const mdtValueDouble &value, double min, double max=std::numeric_limits< double >::max())
Check if x is in range.
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
Protected Attributes inherited from mdtTtAbstractTestNodeCalibrationTool
mdtError pvLastError
Contains last error that occured.
Detailed Description
Test node calibration tool example
Definition at line 37 of file mdtTtBasicTestNodeCalibrationTool.h.
Constructor & Destructor Documentation
mdtTtBasicTestNodeCalibrationTool::mdtTtBasicTestNodeCalibrationTool (QSqlDatabase db, QObject * parent = 0)
Constructor.
Definition at line 41 of file mdtTtBasicTestNodeCalibrationTool.cpp.
Member Function Documentation
void mdtTtBasicTestNodeCalibrationTool::runCalibration () slot
Run calibration.
Definition at line 58 of file mdtTtBasicTestNodeCalibrationTool.cpp.
References mdtTtAbstractTestNodeCalibrationTool::displayLastError(), mdtClPathGraph::lastError(), mdtClPathGraph::loadLinkList(), mdtTtAbstractTestNodeCalibrationTool::promptUser(), and mdtTtAbstractTestNodeCalibrationTool::pvLastError.
void mdtTtBasicTestNodeCalibrationTool::saveCalibration () slot
Save calibration.
Definition at line 163 of file mdtTtBasicTestNodeCalibrationTool.cpp.
References mdtTtAbstractTestNodeCalibrationTool::displayLastError(), and mdtTtAbstractTestNodeCalibrationTool::saveTestNodeUnitCalibrationOffsets().
bool mdtTtBasicTestNodeCalibrationTool::setup (QWidget * testNodeFormWidget) virtual
Do setup.
Will setup database controllers and map widgets contained in testNodeFormWidget.
Note: connect signals and slots before calling this method, else UI will be incoherent at initial state.
Reimplemented from mdtTtAbstractTestNodeCalibrationTool.
Definition at line 48 of file mdtTtBasicTestNodeCalibrationTool.cpp.
References mdtTtAbstractTestNodeCalibrationTool::setup().
Referenced by mdtTtBasicTestNodeCalibrationWindow::init().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtBasicTestNodeCalibrationTool.h
src/mdttools/mdttesttool/mdtTtBasicTestNodeCalibrationTool.cpp