Multi diag tools: mdtClConnectorData Class Reference
mdtClConnectorData Class Reference
Data container class for connector data.
#include <mdtClConnectorData.h>
Public Member Functions
mdtClConnectorData ()
Construct a empty mdtClConnectorData.
mdtClConnectorData (const QSqlRecord &record)
Contruct a mdtClConnectorData from a QSqlRecord.
bool setup (const QSqlDatabase &db)
Setup fields from Connector_tbl.
void setContactDataList (const QList< mdtSqlRecord > &dataList)
Add a list of contact data.
QList< mdtSqlRecord > contactDataList () const
Get list of contact data.
void addContactData (const mdtSqlRecord &data)
Add contact data.
bool setContactData (const QVariant &contactId, const mdtSqlRecord &data)
Update existing contact data.
mdtSqlRecord contactData (const QVariant &contactId, bool *ok) const
Get contact data for given contact ID.
Public Member Functions inherited from mdtSqlRecord
mdtSqlRecord ()
Constructor.
mdtSqlRecord (const QSqlRecord &sqlRecord)
Build a mdtSqlRecord on the base of a QSqlRecord.
virtual ~mdtSqlRecord ()
Destructor.
operator QSqlRecord ()
Get QSqlRecord version.
bool addField (const QString &fieldName, const QString &tableName, const QSqlDatabase &db)
Add a field to record.
bool addAllFields (const QString &tableName, const QSqlDatabase &db)
Add all fields of given table to record.
int count () const
Returns the number of fields in the record.
bool isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
QSqlField field (int index) const
Returns the field at position index.
QSqlField field (const QString &name) const
Returns the field called name.
int indexOf (const QString &name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
bool contains (const QString &name) const
Returns true if there is a field in the record called name; otherwise returns false.
QStringList fieldNames () const
Get a list with all field names.
bool hasValue (int fieldIndex) const
Check if a value was set.
bool hasValue (const QString &fieldName) const
Check if a value was set.
void setValue (int fieldIndex, const QVariant &val)
Set value.
void setValue (const QString &fieldName, const QVariant &val)
Set value.
QVariant value (int index) const
Returns the value of the field located at position index in the record.
QVariant value (const QString &name) const
Returns the value of the field called name in the record.
virtual void clear ()
Removes all the record's fields.
virtual void clearValues ()
Clear values.
mdtError lastError () const
Get last error.
QVector< int > fieldIndexesWithValue () const
Get a list with field indexes that have a value.
QString sqlForInsert (const QString &tableName) const
Get SQL statement for insertion with QSqlQuery.
QString sqlForUpdate (const QString &tableName, const QSqlRecord &matchData) const
Get SQL statement for update with QSqlQuery.
QString dataToUpdateInfo () const
Get information about data that has a value to update (for debug)
Additional Inherited Members
Static Public Member Functions inherited from mdtSqlRecord
static QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtSqlRecord
mdtError pvLastError
Detailed Description
Data container class for connector data.
Permit to echange data with Connector_tbl and ConnectorContact_tbl.
Definition at line 34 of file mdtClConnectorData.h.
Constructor & Destructor Documentation
mdtClConnectorData::mdtClConnectorData ()
Construct a empty mdtClConnectorData.
Definition at line 26 of file mdtClConnectorData.cpp.
mdtClConnectorData::mdtClConnectorData (const QSqlRecord & record)
Contruct a mdtClConnectorData from a QSqlRecord.
Note: if this method is used, setup is not relevant.
Precondition
All fields from Connector_tbl must exist in record
Definition at line 30 of file mdtClConnectorData.cpp.
References mdtSqlRecord::contains().
Member Function Documentation
void mdtClConnectorData::addContactData (const mdtSqlRecord & data)
Add contact data.
Will also update Connector_Id_FK in data.
Precondition
data must contains following fields:
Id_PK
Connector_Id_FK
Definition at line 56 of file mdtClConnectorData.cpp.
References mdtSqlRecord::contains(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
mdtSqlRecord mdtClConnectorData::contactData (const QVariant & contactId, bool * ok) const
Get contact data for given contact ID.
Return the contact data for witch Id_PK matches given contactId. ok will be set to false if contactId was not found.
Definition at line 84 of file mdtClConnectorData.cpp.
References mdtSqlRecord::mdtSqlRecord().
QList< mdtSqlRecord > mdtClConnectorData::contactDataList () const
Get list of contact data.
Definition at line 51 of file mdtClConnectorData.cpp.
bool mdtClConnectorData::setContactData (const QVariant & contactId, const mdtSqlRecord & data)
Update existing contact data.
Will update contact data for witch Id_PK matches given contactId.
Returns
False if contactId was not found.
Definition at line 66 of file mdtClConnectorData.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtSqlRecord::pvLastError, and mdtError::setError().
void mdtClConnectorData::setContactDataList (const QList< mdtSqlRecord > & dataList)
Add a list of contact data.
By using this method, the caller is responsible to give valid records, that contains needed fields.
See Also
addContactData().
Definition at line 46 of file mdtClConnectorData.cpp.
bool mdtClConnectorData::setup (const QSqlDatabase & db)
Setup fields from Connector_tbl.
Definition at line 38 of file mdtClConnectorData.cpp.
References mdtSqlRecord::addAllFields().
Referenced by mdtClArticleConnectorData::setup(), and mdtClUnitConnectorData::setup().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClConnectorData.h
src/mdttools/mdttesttool/mdtcablelist/mdtClConnectorData.cpp