Multi diag tools: mdtSqlFieldHandlerDateTimeEdit Class Reference
mdtSqlFieldHandlerDateTimeEdit Class Reference
Public Member Functions
mdtSqlFieldHandlerDateTimeEdit ()
void setDateTimeEdit (QDateTimeEdit *e)
void setData (const QVariant &data)
QVariant data () const
bool isNull () const
void clear ()
QWidget * widget ()
void setReadOnly (bool readOnly)
Public Member Functions inherited from mdtSqlFieldHandlerAbstractDataWidget
virtual ~mdtSqlFieldHandlerAbstractDataWidget ()
virtual void setMaxLength (int maxLength)
virtual void setRange (qreal min, qreal max)
Detailed Description
Definition at line 440 of file mdtSqlFieldHandler.cpp.
Constructor & Destructor Documentation
mdtSqlFieldHandlerDateTimeEdit::mdtSqlFieldHandlerDateTimeEdit ()
Definition at line 455 of file mdtSqlFieldHandler.cpp.
Member Function Documentation
void mdtSqlFieldHandlerDateTimeEdit::clear () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 484 of file mdtSqlFieldHandler.cpp.
QVariant mdtSqlFieldHandlerDateTimeEdit::data () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 472 of file mdtSqlFieldHandler.cpp.
Referenced by isNull().
bool mdtSqlFieldHandlerDateTimeEdit::isNull () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 478 of file mdtSqlFieldHandler.cpp.
References data().
void mdtSqlFieldHandlerDateTimeEdit::setData (const QVariant & data) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 466 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandlerDateTimeEdit::setDateTimeEdit (QDateTimeEdit * e)
Definition at line 460 of file mdtSqlFieldHandler.cpp.
Referenced by mdtSqlFieldHandler::setDataWidget().
void mdtSqlFieldHandlerDateTimeEdit::setReadOnly (bool readOnly) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 496 of file mdtSqlFieldHandler.cpp.
QWidget * mdtSqlFieldHandlerDateTimeEdit::widget () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 490 of file mdtSqlFieldHandler.cpp.
The documentation for this class was generated from the following file:
src/mdtdatabase/mdtSqlFieldHandler.cpp