Multi diag tools: mdtDoubleEdit Class Reference
mdtDoubleEdit Class Reference
Input box for double values.
#include <mdtDoubleEdit.h>
Public Types
enum UnitSymbol_t { UnitSymbol_t::omega, UnitSymbol_t::OmegaCapital }
Special symbols for units.
enum EditionMode_t { DefaultEditionMode, WireSectionEditionMode, EngineeringNotationMode }
Edition mode.
Public Slots
void setUnit (const QString &u)
Set unit.
void setEditionMode (EditionMode_t mode)
Set edition mode.
Signals
void valueChanged (double value, bool isValid)
Emitted when a new value was set.
void valueEdited ()
Emitted when user has edited value.
Public Member Functions
mdtDoubleEdit (QWidget *parent=0)
Unit prefix ranges.
void setReadOnly (bool ro)
Set read only.
QString unit () const
Get unit.
void setMinimum (double min)
Set minimum.
void setMinimumToMinusInfinity ()
Set minimum to -infinity.
double minimum () const
Get minimum.
void setMaximum (double max)
Set maximum.
void setMaximumToInfinity ()
Set maximum to infinity.
double maximum () const
Get maximum.
void setRange (double min, double max)
Set range.
void setValueString (const QString &s, bool emitValueChanged=true)
Set value from a string.
void setValueDouble (double v, bool emitValueChanged=true)
Set value.
void setValue (const QVariant &v, bool emitValueChanged=true)
Set value.
double valueDouble () const
Get value.
QVariant value () const
Get value.
bool isNull () const
Check if value is null.
bool valueIsValid () const
Check if value is valid.
bool validate ()
Validate edited data.
QString text () const
Get text in line edit.
QLineEdit * lineEdit ()
EditionMode_t editionMode () const
Get edition mode.
Static Public Member Functions
static int p10exponent (const QChar &c)
Get power of 10 exponent for given char.
static QString infinityString ()
Get infinity string.
Properties
QString unit
EditionMode_t editionMode
double minimum
double maximum
Detailed Description
Input box for double values.
A value can be displayed with the value itself, a power of 10 factor and a unit. For example, 1 V represents a value 1 and is displayed with [V] unit. 1 mV also represents value 1e-3 and is displayed with [V] unit.
Unit exponent, for example m2, is also supported.
Definition at line 73 of file mdtDoubleEdit.h.
Member Enumeration Documentation
enum mdtDoubleEdit::EditionMode_t
Edition mode.
Enumerator
DefaultEditionMode
Default edition mode
WireSectionEditionMode
Wire section edition mode
EngineeringNotationMode
Wire edition mode
Definition at line 95 of file mdtDoubleEdit.h.
enum mdtDoubleEdit::UnitSymbol_t strong
Special symbols for units.
Enumerator
omega
Omega (small letter) , ω
OmegaCapital
Capital omega , Ω
Definition at line 87 of file mdtDoubleEdit.h.
Constructor & Destructor Documentation
mdtDoubleEdit::mdtDoubleEdit (QWidget * parent = 0)
Unit prefix ranges.
Constructor
Definition at line 34 of file mdtDoubleEdit.cpp.
References DefaultEditionMode, infinityString(), and valueEdited().
Member Function Documentation
EditionMode_t mdtDoubleEdit::editionMode () const inline
Get edition mode.
Definition at line 249 of file mdtDoubleEdit.h.
QString mdtDoubleEdit::infinityString () static
Get infinity string.
Definition at line 261 of file mdtDoubleEdit.cpp.
Referenced by mdtDoubleEdit(), and mdtDoubleValidator::validate().
bool mdtDoubleEdit::isNull () const inline
Check if value is null.
See Also
isValid()
Definition at line 205 of file mdtDoubleEdit.h.
QLineEdit* mdtDoubleEdit::lineEdit () inline
Definition at line 242 of file mdtDoubleEdit.h.
double mdtDoubleEdit::maximum () const
Get maximum.
Referenced by setMinimum(), and setValueDouble().
double mdtDoubleEdit::minimum () const
Get minimum.
Referenced by setMaximum(), and setValueDouble().
int mdtDoubleEdit::p10exponent (const QChar & c) static
Get power of 10 exponent for given char.
Will return y in 10^y expression, or 0 if char is unknown.
Supported chars are:
Char Designation Factor
a atto -18
f femto -15
p pico -12
n nano -9
u micro -6
m milli -3
c centi -2
d deci -1
h hecto 2
k kilo 3
M mega 6
G giga 9
T tera 12
P peta 15
E exa 18
Definition at line 143 of file mdtDoubleEdit.cpp.
void mdtDoubleEdit::setEditionMode (mdtDoubleEdit::EditionMode_t mode) slot
Set edition mode.
Definition at line 302 of file mdtDoubleEdit.cpp.
References DefaultEditionMode, EngineeringNotationMode, and WireSectionEditionMode.
void mdtDoubleEdit::setMaximum (double max)
Set maximum.
Definition at line 111 of file mdtDoubleEdit.cpp.
References minimum(), and mdtDoubleValidator::setTop().
Referenced by setMaximumToInfinity(), and setRange().
void mdtDoubleEdit::setMaximumToInfinity ()
Set maximum to infinity.
Definition at line 127 of file mdtDoubleEdit.cpp.
References setMaximum().
void mdtDoubleEdit::setMinimum (double min)
Set minimum.
Definition at line 85 of file mdtDoubleEdit.cpp.
References maximum(), and mdtDoubleValidator::setBottom().
Referenced by setMinimumToMinusInfinity(), and setRange().
void mdtDoubleEdit::setMinimumToMinusInfinity ()
Set minimum to -infinity.
Definition at line 101 of file mdtDoubleEdit.cpp.
References setMinimum().
void mdtDoubleEdit::setRange (double min, double max)
Set range.
Definition at line 137 of file mdtDoubleEdit.cpp.
References setMaximum(), and setMinimum().
void mdtDoubleEdit::setReadOnly (bool ro)
Set read only.
Definition at line 78 of file mdtDoubleEdit.cpp.
Referenced by mdtSqlFieldHandlerMdtDoubleEdit::setReadOnly().
void mdtDoubleEdit::setUnit (const QString & u) slot
Set unit.
If u ends with 2 or 3, unit will be considered having a exponent. For example, passing m2 will be unit m (meter) with a unit exponent of 2.
Definition at line 273 of file mdtDoubleEdit.cpp.
References DefaultEditionMode, EngineeringNotationMode, and mdtDoubleValidator::setSuffix().
void mdtDoubleEdit::setValue (const QVariant & v, bool emitValueChanged = true)
Set value.
Definition at line 214 of file mdtDoubleEdit.cpp.
References setValueDouble(), setValueString(), and valueChanged().
Referenced by mdtSqlFieldHandlerMdtDoubleEdit::clear(), and mdtSqlFieldHandlerMdtDoubleEdit::setData().
void mdtDoubleEdit::setValueDouble (double v, bool emitValueChanged = true)
Set value.
Definition at line 197 of file mdtDoubleEdit.cpp.
References maximum(), minimum(), and valueChanged().
Referenced by setValue().
void mdtDoubleEdit::setValueString (const QString & s, bool emitValueChanged = true)
Set value from a string.
s can also contain power of 10 char and unit. Unit must be the same than set with setUnit().
Definition at line 181 of file mdtDoubleEdit.cpp.
References mdtDoubleValidator::validate(), and valueChanged().
Referenced by setValue().
QString mdtDoubleEdit::text () const
Get text in line edit.
Definition at line 256 of file mdtDoubleEdit.cpp.
QString mdtDoubleEdit::unit () const inline
Get unit.
Definition at line 120 of file mdtDoubleEdit.h.
bool mdtDoubleEdit::validate ()
Validate edited data.
After user has finished editing value, it is converted, checked and displayed in recognised way. The valueChanged() signal will also be emitted. Editing is finished when user hits <Enter> key, or internal line edit losses focus. To proceed to conversion and validation sooner than that, call this function.
Returns
If currently edited data represents a valid value, true is returned, false else.
Definition at line 249 of file mdtDoubleEdit.cpp.
Referenced by mdtSqlFieldHandlerMdtDoubleEdit::validate().
QVariant mdtDoubleEdit::value () const
Get value.
Definition at line 238 of file mdtDoubleEdit.cpp.
Referenced by mdtSqlFieldHandlerMdtDoubleEdit::data().
void mdtDoubleEdit::valueChanged (double value, bool isValid) signal
Emitted when a new value was set.
Happens when user has finished editting, or when a set function was called with emitValueChanged flag set.
Referenced by setValue(), setValueDouble(), and setValueString().
double mdtDoubleEdit::valueDouble () const inline
Get value.
Definition at line 195 of file mdtDoubleEdit.h.
void mdtDoubleEdit::valueEdited () signal
Emitted when user has edited value.
Is a simple relay of internal line edit's textEdited() signal.
Referenced by mdtDoubleEdit().
bool mdtDoubleEdit::valueIsValid () const inline
Check if value is valid.
Value is valid only if it represents a number or is null. For example, if setValue() was called with a pure string, like 'abcd', the function will return false.
Note that a value can also be null and valid.
Definition at line 215 of file mdtDoubleEdit.h.
Property Documentation
EditionMode_t mdtDoubleEdit::editionMode read write
Definition at line 78 of file mdtDoubleEdit.h.
double mdtDoubleEdit::maximum read write
Definition at line 81 of file mdtDoubleEdit.h.
double mdtDoubleEdit::minimum read write
Definition at line 80 of file mdtDoubleEdit.h.
QString mdtDoubleEdit::unit read write
Definition at line 77 of file mdtDoubleEdit.h.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtDoubleEdit.h
src/mdtutilsgui/mdtDoubleEdit.cpp