Multi diag tools: mdtUsbConfigDescriptor Class Reference
mdtUsbConfigDescriptor Class Reference
USB configuration descriptor.
#include <mdtUsbConfigDescriptor.h>
Public Member Functions
mdtUsbConfigDescriptor ()
~mdtUsbConfigDescriptor ()
void fetchAttributes (struct libusb_config_descriptor *descriptor)
Ftech the configuration descriptor's attributes.
quint8 bDescriptorType () const
CONFIGURATION Descriptor Type.
quint8 bConfigurationValue () const
Value to use as an argument to the SetConfiguration() request to select this configuration.
quint8 iConfiguration () const
Index of string descriptor describing this configuration.
quint8 bmAttributes () const
Configuration characteristics.
bool isSelfPowered () const
Return true if device is self powered with this configuration.
bool supportsRemoteWakeup () const
Return true if device supports remote wakeup with this configuration.
quint8 bMaxPower () const
Max power in 2 [mA] units.
int maxPower () const
Max power [mA].
QList
< mdtUsbInterfaceDescriptor * > & interfaces ()
Detailed Description
USB configuration descriptor.
Definition at line 32 of file mdtUsbConfigDescriptor.h.
Constructor & Destructor Documentation
mdtUsbConfigDescriptor::mdtUsbConfigDescriptor ()
Definition at line 24 of file mdtUsbConfigDescriptor.cpp.
mdtUsbConfigDescriptor::~mdtUsbConfigDescriptor ()
Definition at line 33 of file mdtUsbConfigDescriptor.cpp.
Member Function Documentation
quint8 mdtUsbConfigDescriptor::bConfigurationValue () const
Value to use as an argument to the SetConfiguration() request to select this configuration.
Definition at line 73 of file mdtUsbConfigDescriptor.cpp.
quint8 mdtUsbConfigDescriptor::bDescriptorType () const
CONFIGURATION Descriptor Type.
Definition at line 68 of file mdtUsbConfigDescriptor.cpp.
quint8 mdtUsbConfigDescriptor::bmAttributes () const
Configuration characteristics.
See Also
isSelfPowered()
supportsRemoteWakeup()
Definition at line 83 of file mdtUsbConfigDescriptor.cpp.
quint8 mdtUsbConfigDescriptor::bMaxPower () const
Max power in 2 [mA] units.
See Also
maxPower()
Definition at line 98 of file mdtUsbConfigDescriptor.cpp.
void mdtUsbConfigDescriptor::fetchAttributes (struct libusb_config_descriptor * descriptor)
Ftech the configuration descriptor's attributes.
Precondition
descriptor must be a valid pointer
Definition at line 38 of file mdtUsbConfigDescriptor.cpp.
References mdtUsbInterfaceDescriptor::fetchAttributes().
Referenced by mdtUsbDeviceDescriptor::fetchAttributes().
quint8 mdtUsbConfigDescriptor::iConfiguration () const
Index of string descriptor describing this configuration.
Definition at line 78 of file mdtUsbConfigDescriptor.cpp.
QList< mdtUsbInterfaceDescriptor * > & mdtUsbConfigDescriptor::interfaces ()
Definition at line 108 of file mdtUsbConfigDescriptor.cpp.
Referenced by mdtUsbDeviceDescriptor::interface(), and mdtUsbPortManager::scan().
bool mdtUsbConfigDescriptor::isSelfPowered () const
Return true if device is self powered with this configuration.
This is bit D6 from bmAttributes()
See Also
bmAttributes()
Definition at line 88 of file mdtUsbConfigDescriptor.cpp.
int mdtUsbConfigDescriptor::maxPower () const
Max power [mA].
Definition at line 103 of file mdtUsbConfigDescriptor.cpp.
bool mdtUsbConfigDescriptor::supportsRemoteWakeup () const
Return true if device supports remote wakeup with this configuration.
This is bit D5 from bmAttributes()
See Also
bmAttributes()
Definition at line 93 of file mdtUsbConfigDescriptor.cpp.
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbConfigDescriptor.h
src/mdtport/mdtUsbConfigDescriptor.cpp