Multi diag tools: mdtModbusTcpPortManager Class Reference
mdtModbusTcpPortManager Class Reference
MODBUS/TCP port manager.
#include <mdtModbusTcpPortManager.h>
Public Slots
void abortScan ()
Abort the scan process.
void abortTryToConnect ()
Called by connect timeout timer.
void fromThreadNewFrameReaden ()
Called by the thread whenn a complete frame was readen.
Public Slots inherited from mdtPortManager
virtual void abort ()
Cancel read and write operations.
Public Member Functions
mdtModbusTcpPortManager (QObject *parent=0)
Construct a MODBUS/TCP port manager.
~mdtModbusTcpPortManager ()
Destructor.
mdtDeviceAddressList scan (const QList< mdtNetworkHost > &hosts, const mdtModbusHwNodeIdList &expectedHwNodeAddresses, int timeout=500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
mdtDeviceAddressList scan (const QNetworkInterface &iface, const mdtModbusHwNodeIdList &expectedHwNodeAddresses, quint16 port=502, int timeout=500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
mdtDeviceAddressList scan (const QNetworkInterface &iface, quint16 port=502, int timeout=500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
mdtDeviceAddressList scan (const QList< QNetworkInterface > &ifaces, const mdtModbusHwNodeIdList &expectedHwNodeAddresses, quint16 port=502, bool ignoreLoopback=true, int timeout=500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
mdtDeviceAddressList scan (const QList< QNetworkInterface > &ifaces, quint16 port=502, bool ignoreLoopback=true, int timeout=500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
mdtDeviceAddressList scan (const mdtDeviceAddressList &addressList, int timeout=500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
mdtDeviceAddressList scanFromKnownHostsFile (int timeout=500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
bool tryToConnect (const QString &hostName, quint16 port, int timeout)
Try to connect to a host.
bool saveDeviceAddressList (mdtDeviceAddressList &addressList)
Save device address list into the known hosts file.
mdtDeviceAddressList readDeviceAddressList ()
Read device address list from known hosts file.
bool saveScanResult (const QList< mdtPortInfo * > scanResult)
Save a scan result into the known hosts file.
QStringList readScanResult ()
Read scan result stored in cache file.
bool isReady () const
Check if port manager is ready.
mdtModbusHwNodeId getHardwareNodeAddress (int bitsCount, int startFrom=0)
Get the hardware node ID.
mdtModbusHwNodeId findMatchingToHostModebusHwNodeId (const mdtModbusHwNodeIdList &hwNodeIdList)
Get MODBUS hardware node ID that matches in given list.
bool getRegisterValues (int address, int n)
Helper method for register service.
const QList< int > & registerValues () const
Helper method for register service.
bool setRegisterValues (int startAddress, QList< int > &values)
Helper method for register service.
int sendData (mdtPortTransaction *transaction)
Send PDU on TCP port.
int sendData (const QByteArray &pdu, bool queryReplyMode=false)
Send PDU by copy.
Public Member Functions inherited from mdtPortManager
mdtPortManager (QObject *parent=0)
Contruct a port manager.
virtual ~mdtPortManager ()
Destructor.
virtual void setPort (mdtAbstractPort *port)
Scan for available ports.
void lockPortMutex ()
Lock the port's mutex.
void unlockPortMutex ()
Unlock port's mutex.
void detachPort (bool deletePort, bool deleteThreads)
Detach port.
void addThread (mdtPortThread *thread)
Add a thread and assign it to port.
mdtPortThread * readThread ()
Returns instance of reader thread.
mdtPortThread * writeThread ()
Returns instance of writer thread.
void removeThreads (bool releaseMemory)
Detach threads from port and remove threads.
virtual bool start ()
Start port manager.
void stop ()
Stop port manager.
void setPortName (const QString &portName)
Set port name.
void setPortInfo (mdtPortInfo info)
Set port info.
mdtPortInfo portInfo ()
Get current port info.
QString portName () const
Get current port name.
virtual mdtPortConfig & config ()
Get the port's config object.
mdtPortConfig & config () const
Get the port's config object.
void setKeepTransactionsDone (bool keep)
Force transactions done to be keeped.
bool keepTransactionsDone () const
Get the keepTransactionsDone flag.
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
bool waitTransactionDone (int id)
Wait until a transaction is done.
bool waitOneTransactionDone ()
Wait until current transaction is done.
void wait (int ms)
Wait for some time.
QByteArray readenFrame (int id)
Get data by frame ID.
QList< QByteArray > readenFrames ()
Get all readen data.
virtual void flushIn (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush input buffers.
void flushIn ()
Flush input buffers.
virtual void flushOut (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush output buffers.
void flushOut ()
Flush output buffers.
void flush (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush I/O buffers.
void flush ()
Flush I/O buffers.
state_t currentState () const
Get current state.
void notifyCurrentState ()
Notify the current state.
bool isClosed () const
Check if port is closed.
mdtError lastError () const
Get last error.
Additional Inherited Members
Public Types inherited from mdtPortManager
enum state_t {
PortClosed = 0, Stopped, Starting, Stopping,
Running, PortError, PortReady, Disconnected,
Connecting, Connected, Ready, Busy
}
State of device.
Signals inherited from mdtPortManager
void newTransactionDone (mdtPortTransaction *transaction)
Emitted each time a transaction is done.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
void stateChanged (int stateId)
Emitted each time the state changed.
void stateChangedForUi (int stateId, const QString &stateText, int ledColorId, bool ledIsOn)
Emitted only if a state that must be notified is entered.
void pmPortClosedEvent ()
Sent when port was closed.
void pmStartThreadsEvent ()
Sent when threads must be started.
void pmStopThreadsEvent ()
Sent when threads must be stopped.
void pmAllThreadsReadyEvent ()
Sent when all threads are ready.
void pmAllThreadsStoppedEvent ()
Sent when all threads are stopped.
void pmUnhandledErrorEvent ()
Sent when a unhandled error occured.
void pmConnectingEvent ()
Sent when connection with device beginns.
void pmConnectedEvent ()
Sent when connection with device is established.
void pmDisconnectedEvent ()
Sent when connection with device was lost/closed.
void pmConnectionFailedEvent ()
Sent when connection failed on startup or after max try.
void pmBusyEvent ()
Sent when device is busy (or other slow down reason..)
void pmReadyEvent ()
Sent when device and communication becomes ready again.
void pmTransactionTimeoutEvent ()
Sent when a transaction timeout occured.
Protected Slots inherited from mdtPortManager
virtual void fromThreadNewFrameReaden ()
Called by the read thread whenn a complete frame was readen.
virtual void onThreadsErrorOccured (int error)
Manage errors comming from port threads.
Protected Member Functions inherited from mdtPortManager
virtual bool openPort ()
Open the port.
void closePort ()
Close the port.
void setCurrentTransactionId (int id)
Set the current transaction ID.
int currentTransactionId () const
Get the current transaction ID.
void incrementCurrentTransactionId (int min=0, int max=INT_MAX)
Increment current transaction ID.
bool waitTransactionPossible ()
Wait until transaction pending queue has less than maximum possible items.
void addTransactionPending (mdtPortTransaction *transaction)
Add a transaction to pending queue.
mdtPortTransaction * transactionPending (int id)
Take pending transaction matching id.
void flushTransactionsPending ()
Restore all transactions pending to pool.
void addTransactionDone (mdtPortTransaction *transaction)
Add a transaction to the DONE queue.
bool transactionsDoneContains (int id) const
Check if a transaction with given ID exists in done queue.
mdtPortTransaction * transactionDone (int id)
Take transaction from DONE queue matching id.
void flushTransactionsDone ()
Restore all transactions done to pool.
void startTransactionTimer (int timeout)
Start transaction timer.
void stopTransactionTimer ()
Stop transaction timer.
bool transactionTimeoutOccured () const
Check if a transaction timeout occured.
void commitFrames ()
Emit signals for each done transactions.
Protected Attributes inherited from mdtPortManager
mdtError pvLastError
Last error object.
mdtAbstractPort * pvPort
QList< mdtPortThread * > pvThreads
Detailed Description
MODBUS/TCP port manager.
This is the simplest way to use the MODBUS/TCP API.
All needed object are created by constructor. To alter configuration, use config(). To access the tcp port object, use port().
Use start() to begin read/write and stop to end.
References:
MODBUS Application Protocol Specification V1.1b
http://www.Modbus-IDA.org
Definition at line 68 of file mdtModbusTcpPortManager.h.
Constructor & Destructor Documentation
mdtModbusTcpPortManager::mdtModbusTcpPortManager (QObject * parent = 0)
Construct a MODBUS/TCP port manager.
Creates a mdtPortConfig, a mdtTcpSocket, and thread object.
Definition at line 41 of file mdtModbusTcpPortManager.cpp.
References mdtPortManager::addThread(), mdtPortManager::config(), mdtFrame::FT_MODBUS_TCP, mdtAbstractPort::setConfig(), mdtPortConfig::setFrameType(), mdtPortManager::setKeepTransactionsDone(), mdtPortManager::setPort(), mdtPortConfig::setReadFrameSize(), mdtPortConfig::setReadTimeout(), mdtPortConfig::setWriteFrameSize(), and mdtPortConfig::setWriteQueueSize().
mdtModbusTcpPortManager::~mdtModbusTcpPortManager ()
Destructor.
Stop the manager (if running), and close the port (if open). All internal objects (port, config and threads) are deleted here.
Definition at line 66 of file mdtModbusTcpPortManager.cpp.
References mdtAbstractPort::config(), mdtPortManager::detachPort(), and mdtPortManager::pvPort.
Member Function Documentation
void mdtModbusTcpPortManager::abortScan () slot
Abort the scan process.
Definition at line 631 of file mdtModbusTcpPortManager.cpp.
void mdtModbusTcpPortManager::abortTryToConnect () slot
Called by connect timeout timer.
Definition at line 636 of file mdtModbusTcpPortManager.cpp.
Referenced by tryToConnect().
mdtModbusHwNodeId mdtModbusTcpPortManager::findMatchingToHostModebusHwNodeId (const mdtModbusHwNodeIdList & hwNodeIdList)
Get MODBUS hardware node ID that matches in given list.
Will get MODBUS harware node ID, regarding bitsCount and firstBit for each item in given list, and return the first item that matches. If no matching item was found, a null ID is returned.
Precondition
Port manager must be connected and thread running before calling this method.
Todo:
Should be protected.
Definition at line 448 of file mdtModbusTcpPortManager.cpp.
References getHardwareNodeAddress(), mdtModbusHwNodeId::id(), mdtModbusHwNodeIdList::internalVector(), mdtModbusHwNodeId::isNull(), and isReady().
Referenced by scan().
void mdtModbusTcpPortManager::fromThreadNewFrameReaden () slot
Called by the thread whenn a complete frame was readen.
Definition at line 641 of file mdtModbusTcpPortManager.cpp.
References mdtPortManager::addTransactionDone(), mdtError::commit(), mdtPortManager::commitFrames(), mdtFrameModbusTcp::getPdu(), mdtFrame::isComplete(), mdtPortManager::lockPortMutex(), MDT_ERROR_SET_SRC, MDT_TCP_IO_ERROR, mdtPortManager::pvPort, mdtAbstractPort::readenFrames(), mdtAbstractPort::readFramesPool(), mdtPortTransaction::setData(), mdtPortTransaction::setId(), mdtFrameModbusTcp::transactionId(), mdtPortManager::transactionPending(), mdtPortManager::unlockPortMutex(), and mdtError::Warning.
mdtModbusHwNodeId mdtModbusTcpPortManager::getHardwareNodeAddress (int bitsCount, int startFrom = 0)
Get the hardware node ID.
The concept of node ID is specific to MultiDiagTools. It was introduced to solve the problem of network IP configurations.
Take a example: We have a application that needs several MODBUS/TCP nodes. Each node has several I/O's. Say that digital output 1 of node 1 is used to activate a lamp and output 1 of node 2 must activate heating register. We could choose to have static IP addresses in the network and configure the application to activate the correct output of correct node. But, this can be a problem when a node must be replaced. More cumbersome case is a modular application that could manage several nodes, and change his I/Os layout in a dynamic way regarding a context.
A easy way to solve such problems is to have a DHCP server in the network and all nodes configured as DHCP clients (static addressing can still be a solution, but we not depend on it). Then, for a given application, we can fix a number of digital inputs to play the role of node address. Then, instead of using IP address as identification (as in the example), we use node address.
Parameters
bitsCount Number of digital inputs that represents the hardware node address.
startFrom First digital input that represents the hardware node address (is the LSB).
Returns
Node address. On error, a null hardware node ID is returned.
Precondition
Port manager must be connected and thread running before calling this method.
bitsCount must be > 0
startFrom must be >= 0
Definition at line 371 of file mdtModbusTcpPortManager.cpp.
References mdtError::commit(), mdtFrameCodecModbus::decode(), mdtFrameCodecModbus::encodeReadDiscreteInputs(), mdtError::Error, mdtPortManager::getNewTransaction(), isReady(), MDT_ERROR_SET_SRC, mdtPortManager::pvLastError, mdtPortManager::readenFrame(), sendData(), mdtPortTransaction::setData(), mdtError::setError(), mdtModbusHwNodeId::setId(), mdtPortTransaction::setQueryReplyMode(), mdtFrameCodec::values(), and mdtPortManager::waitTransactionDone().
Referenced by mdtDeviceModbus::connectToDevice(), findMatchingToHostModebusHwNodeId(), and scan().
bool mdtModbusTcpPortManager::getRegisterValues (int address, int n)
Helper method for register service.
Usefull to get resgister values (f.ex. configurations regsisters, ...).
Note: to get analog I/O values, the mdtDevice API should be used.
Returns
True on success. Values are the available with registerValues()
Precondition
address must be >= 0
n must be > 0
Definition at line 469 of file mdtModbusTcpPortManager.cpp.
References mdtError::commit(), mdtFrameCodecModbus::decode(), mdtFrameCodecModbus::encodeReadInputRegisters(), mdtError::Error, mdtPortManager::getNewTransaction(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtPortManager::readenFrame(), sendData(), mdtPortTransaction::setData(), mdtPortTransaction::setQueryReplyMode(), mdtFrameCodec::values(), and mdtPortManager::waitTransactionDone().
Referenced by mdtDeviceModbus::getRegisterValues().
bool mdtModbusTcpPortManager::isReady () const virtual
Check if port manager is ready.
Internally, the currentState is used to check if port manager is ready. This implementation returns true if currentState is Ready (= connected to device).
Reimplemented from mdtPortManager.
Definition at line 366 of file mdtModbusTcpPortManager.cpp.
References mdtPortManager::currentState(), and mdtPortManager::Ready.
Referenced by findMatchingToHostModebusHwNodeId(), getHardwareNodeAddress(), and sendData().
mdtDeviceAddressList mdtModbusTcpPortManager::readDeviceAddressList ()
Read device address list from known hosts file.
Will read file written by saveDeviceAddressList().
Definition at line 304 of file mdtModbusTcpPortManager.cpp.
References mdtApplication::cacheDir(), mdtDeviceAddressList::lastError(), mdtPortManager::pvLastError, and mdtDeviceAddressList::readFromFile().
Referenced by scanFromKnownHostsFile().
QStringList mdtModbusTcpPortManager::readScanResult ()
Read scan result stored in cache file.
The file stored by saveScanResult() is readen (if exists) and content returned.
Returns
List of lines or empty list if file not exists or on error.
Deprecated:
Use readDeviceAddressList()
Definition at line 347 of file mdtModbusTcpPortManager.cpp.
References mdtApplication::cacheDir().
const QList< int > & mdtModbusTcpPortManager::registerValues () const
Helper method for register service.
Return result set by getRegisterValues(). Note that values are keeped until next call of getRegisterValues().
Definition at line 521 of file mdtModbusTcpPortManager.cpp.
Referenced by mdtDeviceModbus::registerValues().
bool mdtModbusTcpPortManager::saveDeviceAddressList (mdtDeviceAddressList & addressList)
Save device address list into the known hosts file.
The file will be written to the $HOME/.mdt/cache directory.
Precondition
Manager must no running
Definition at line 296 of file mdtModbusTcpPortManager.cpp.
References mdtApplication::cacheDir(), mdtDeviceAddressList::lastError(), mdtPortManager::pvLastError, and mdtDeviceAddressList::saveToFile().
Referenced by mdtDeviceModbus::connectToDevice().
bool mdtModbusTcpPortManager::saveScanResult (const QList< mdtPortInfo * > scanResult)
Save a scan result into the known hosts file.
The file will be written to the $HOME/.mdt/cache directory, and contains lines with format host:port.
Parameters
scanResult List of port informations returned by a scan() method.
Returns
True on successfull write.
Precondition
Manager must no running
Deprecated:
Use saveDeviceAddressList()
Definition at line 315 of file mdtModbusTcpPortManager.cpp.
References mdtApplication::cacheDir(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FILE_IO_ERROR.
mdtDeviceAddressList mdtModbusTcpPortManager::scan (const QList< mdtNetworkHost > & hosts, const mdtModbusHwNodeIdList & expectedHwNodeAddresses, int timeout = 500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
Parameters
hosts A list of hosts to scan.
expectedHwNodeAddresses If this list contains HW node addresses, scan will break when each one was found.
timeout Maximum wait time [ms].
Returns
A list of device addresses that contains found hosts. A empty list means that no device was found, or other error happened, lastError() will also provide some informations in the case.
Precondition
Port manager must be stopped before scanning.
Definition at line 74 of file mdtModbusTcpPortManager.cpp.
References mdtDeviceAddressList::append(), findMatchingToHostModebusHwNodeId(), mdtPortManager::isClosed(), mdtModbusHwNodeIdList::isEmpty(), mdtDeviceAddress::setModbusTcpIdentification(), mdtPortManager::setPortName(), mdtModbusHwNodeIdList::size(), mdtDeviceAddressList::size(), mdtPortManager::start(), mdtPortManager::stop(), and tryToConnect().
Referenced by mdtDeviceModbus::connectToDevice(), scan(), and scanFromKnownHostsFile().
mdtDeviceAddressList mdtModbusTcpPortManager::scan (const QNetworkInterface & iface, const mdtModbusHwNodeIdList & expectedHwNodeAddresses, quint16 port = 502, int timeout = 500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
Parameters
iface Scan will be done for all IP addresses available for given intarface. Note that only IPv4 is implemented.
port Port. MODBUS/TCP default port is 502.
expectedHwNodeAddresses If this list contains HW node addresses, scan will break when each one was found.
timeout Maximum wait time [ms].
Returns
A list of device addresses that contains found hosts. A empty list means that no device was found, or other error happened, lastError() will also provide some informations in the case.
Precondition
Port manager must be stopped before scanning.
Definition at line 113 of file mdtModbusTcpPortManager.cpp.
References mdtError::commit(), mdtError::Error, mdtNetworkHost::hostName, mdtPortManager::isClosed(), MDT_ERROR_SET_SRC, mdtNetworkHost::port, mdtPortManager::pvLastError, scan(), mdtError::setError(), and mdtError::Warning.
mdtDeviceAddressList mdtModbusTcpPortManager::scan (const QNetworkInterface & iface, quint16 port = 502, int timeout = 500) inline
Scan for available hosts with a MODBUS/TCP compatible device attached.
Parameters
iface Scan will be done for all IP addresses available for given intarface. Note that only IPv4 is implemented.
port Port. MODBUS/TCP default port is 502.
timeout Maximum wait time [ms].
Returns
A list of device addresses that contains found hosts. A empty list means that no device was found, or other error happened, lastError() will also provide some informations in the case.
Precondition
Port manager must be stopped before scanning.
Definition at line 126 of file mdtModbusTcpPortManager.h.
References scan().
mdtDeviceAddressList mdtModbusTcpPortManager::scan (const QList< QNetworkInterface > & ifaces, const mdtModbusHwNodeIdList & expectedHwNodeAddresses, quint16 port = 502, bool ignoreLoopback = true, int timeout = 500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
Parameters
ifaces Scan will be done for all IP addresses available for all given intarfaces. Note that only IPv4 is implemented.
port Port. MODBUS/TCP default port is 502.
ignoreLoopback If true, loopback interface will be ignored.
expectedHwNodeAddresses If this list contains HW node addresses, scan will break when each one was found.
timeout Maximum wait time [ms].
Returns
A list of device addresses that contains found hosts. A empty list means that no device was found, or other error happened, lastError() will also provide some informations in the case.
Precondition
Port manager must be stopped before scanning.
Definition at line 177 of file mdtModbusTcpPortManager.cpp.
References mdtDeviceAddressList::append(), mdtPortManager::isClosed(), and scan().
mdtDeviceAddressList mdtModbusTcpPortManager::scan (const QList< QNetworkInterface > & ifaces, quint16 port = 502, bool ignoreLoopback = true, int timeout = 500) inline
Scan for available hosts with a MODBUS/TCP compatible device attached.
Parameters
ifaces Scan will be done for all IP addresses available for all given intarfaces. Note that only IPv4 is implemented.
port Port. MODBUS/TCP default port is 502.
ignoreLoopback If true, loopback interface will be ignored.
timeout Maximum wait time [ms].
Returns
A list of device addresses that contains found hosts. A empty list means that no device was found, or other error happened, lastError() will also provide some informations in the case.
Precondition
Port manager must be stopped before scanning.
Definition at line 160 of file mdtModbusTcpPortManager.h.
References scan().
mdtDeviceAddressList mdtModbusTcpPortManager::scan (const mdtDeviceAddressList & addressList, int timeout = 500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
Return a list of each device in address list that is a MODBUS/TCP device, that can be reached and that has matching hardware node ID.
Parameters
addressList Address list that contains hosts to try to connect to.
timeout Maximum wait time [ms].
Returns
A list of device addresses that contains found hosts. A empty list means that no device was found, or other error happened, lastError() will also provide some informations in the case.
Precondition
Port manager must be stopped before scanning.
Definition at line 198 of file mdtModbusTcpPortManager.cpp.
References mdtDeviceAddressList::append(), mdtModbusHwNodeId::bitsCount(), mdtModbusHwNodeId::firstBit(), getHardwareNodeAddress(), mdtModbusHwNodeId::id(), mdtDeviceAddressList::internalVector(), mdtModbusHwNodeId::isNull(), mdtDeviceAddress::MODBUS, mdtPortManager::setPortName(), mdtDeviceAddressList::size(), mdtPortManager::start(), mdtPortManager::stop(), mdtDeviceAddress::TCPIP, and tryToConnect().
mdtDeviceAddressList mdtModbusTcpPortManager::scanFromKnownHostsFile (int timeout = 500)
Scan for available hosts with a MODBUS/TCP compatible device attached.
Will read known hosts file and return list of devices that are attached at given host name, port and that have hardware node ID matching.
Parameters
timeout Maximum wait time [ms].
Returns
A list of device addresses that contains found hosts. A empty list means that no device was found, or other error happened, lastError() will also provide some informations in the case.
Precondition
Port manager must be stopped before scanning.
Definition at line 242 of file mdtModbusTcpPortManager.cpp.
References mdtDeviceAddressList::isEmpty(), readDeviceAddressList(), and scan().
Referenced by mdtDeviceModbus::connectToDevice().
int mdtModbusTcpPortManager::sendData (mdtPortTransaction * transaction) virtual
Send PDU on TCP port.
At first, this method waits until the ready state is set calling isReady() , a frame is available in port's write frames pool, and until a transaction is possible (see waitTransactionPossible()). This wait will not break event loop, so no GUI freeze occurs. If port manager is stopped during this wait (unhandled error, stop request), this method returns.
Then, data will be encoded regarding MODBUS/TCP standard and passed to the mdtTcpSocket write queue. This method returns immediatly after enqueue, and don't wait until data was written.
Parameters
transaction Transaction used to send data. Following members are used by this method:
id : MODBUS/TCP transaction ID (will be set internally).
data : PDU to send.
isQueryReplyMode : if true, the transaction will be keeped in transactions done queue until readenFrame(int) is called. For all cases, signal newReadenFrame(mdtPortTransaction*) is emitted when data comes in.
Returns
Transaction ID on success or value < 0 on error. Possible error is mdtAbstractPort::WriteCanceled, witch typically occurs when port manager stops. Note: on failure, the transaction is restored to pool.
Precondition
Port must be set with setPort() before use of this method.
transaction must be a valid pointer, and not allready exists in transactions pending or transactions done queue.
Reimplemented from mdtPortManager.
Definition at line 565 of file mdtModbusTcpPortManager.cpp.
References mdtAbstractPort::addFrameToWrite(), mdtPortManager::addTransactionPending(), mdtFrame::clear(), mdtFrameModbusTcp::clearSub(), mdtPortManager::currentTransactionId(), mdtPortTransaction::data(), mdtFrameModbusTcp::encode(), mdtPortTransaction::id(), mdtPortManager::incrementCurrentTransactionId(), mdtPortManager::isClosed(), isReady(), mdtPortManager::lockPortMutex(), mdtPortManager::pvPort, mdtPortManager::restoreTransaction(), mdtPortTransaction::setId(), mdtFrameModbusTcp::setPdu(), mdtFrameModbusTcp::setTransactionId(), mdtFrameModbusTcp::setUnitId(), mdtFrame::setWaitAnAnswer(), mdtPortManager::transactionsDoneContains(), mdtPortManager::unlockPortMutex(), mdtPortManager::waitTransactionPossible(), mdtAbstractPort::WriteCanceled, and mdtAbstractPort::writeFramesPool().
Referenced by getHardwareNodeAddress(), getRegisterValues(), mdtDeviceModbus::readAnalogInput(), mdtDeviceModbus::readAnalogInputs(), mdtDeviceModbus::readAnalogOutput(), mdtDeviceModbus::readAnalogOutputs(), mdtDeviceModbus::readDigitalInput(), mdtDeviceModbus::readDigitalInputs(), mdtDeviceModbus::readDigitalOutput(), mdtDeviceModbus::readDigitalOutputs(), sendData(), setRegisterValues(), mdtDeviceModbus::writeAnalogOutput(), mdtDeviceModbus::writeAnalogOutputs(), mdtDeviceModbus::writeDigitalOutput(), and mdtDeviceModbus::writeDigitalOutputs().
int mdtModbusTcpPortManager::sendData (const QByteArray & pdu, bool queryReplyMode = false) virtual
Send PDU by copy.
Will get a new transaction, setup it with pdu as data and queryReplyMode flag, then send it with sendData(mdtPortTransaction*).
Parameters
pdu MODBUS PDU (see the MODBUS Application Protocol Specification for details)
Reimplemented from mdtPortManager.
Definition at line 617 of file mdtModbusTcpPortManager.cpp.
References mdtPortManager::getNewTransaction(), mdtPortManager::pvPort, sendData(), mdtPortTransaction::setData(), and mdtPortTransaction::setQueryReplyMode().
bool mdtModbusTcpPortManager::setRegisterValues (int startAddress, QList< int > & values)
Helper method for register service.
Usefull to set register values (f.ex. configurations regsisters, ...).
Note: to set analog I/O values, the mdtDevice API should be used.
Returns
True on success.
Precondition
startAddress must be >= 0
Definition at line 526 of file mdtModbusTcpPortManager.cpp.
References mdtError::commit(), mdtFrameCodecModbus::decode(), mdtFrameCodecModbus::encodeWriteMultipleRegisters(), mdtError::Error, mdtPortManager::getNewTransaction(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, mdtPortManager::readenFrame(), sendData(), mdtPortTransaction::setData(), mdtPortTransaction::setQueryReplyMode(), and mdtPortManager::waitTransactionDone().
Referenced by mdtDeviceModbus::setRegisterValues().
bool mdtModbusTcpPortManager::tryToConnect (const QString & hostName, quint16 port, int timeout)
Try to connect to a host.
Parameters
hostName Host name or a IP address
port Port. Note that MODBUS/TCP default port is 502.
timeout Maximum wait time [ms]. Must be a multiple of 50 [ms]
Returns
True on successfull connection.
Precondition
Port manager must be stopped
Definition at line 254 of file mdtModbusTcpPortManager.cpp.
References abortTryToConnect(), mdtPortManager::isClosed(), and mdtPortManager::statusMessageChanged().
Referenced by scan().
The documentation for this class was generated from the following files:
src/mdtport/mdtModbusTcpPortManager.h
src/mdtport/mdtModbusTcpPortManager.cpp