Multi diag tools: mdtTtTestModelItem Class Reference
mdtTtTestModelItem Class Reference
Helper class for test item edition.
#include <mdtTtTestModelItem.h>
Public Member Functions
mdtTtTestModelItem (QObject *parent, QSqlDatabase db)
Constructor.
QString sqlForTestLinkSelection (const QVariant &testModelItemId, const QVariant &testModelId) const
Get SQL statement for test link selection.
QString sqlForTestNodeUnitSelection (const QVariant &testModelItemId, const QVariant &testModelId) const
Get SQL statement for test node unit selection.
QString sqlForTestNodeSelection (const QVariant &testModelId) const
Get SQL statement for test node selection.
QList< QVariant > getUsedNodeUnitIdList (const QVariant &testItemId, const QVariant &type)
Get a list of used node unit IDs for given test item ID.
QList< QVariant > getTestNodeUnitSetupIdList (const QVariant &testItemId)
Get list of test node unit setup for given test item ID.
bool addTestLink (const QVariant &testModelItemId, const QVariant &testLinkId)
Add a test link to TestModelItem_TestLink_tbl.
bool testLinkExists (const QVariant &testModelItemId, const QVariant &testLinkId, bool &ok)
Check if a test link exists in TestModelItem_TestLink_tbl.
bool removeTestLinks (const mdtSqlTableSelection &s)
Remove test links.
bool addOrUpdateTestNodeUnitSetup (const mdtTtTestNodeUnitSetupData &data)
Add a test node unit to TestNodeUnitSetup_tbl.
bool addOrUpdateTestNodeUnitSetupList (const QList< mdtTtTestNodeUnitSetupData > &dataList)
Add a list of test node unit to TestNodeUnitSetup_tbl.
bool testNodeUnitSetupExists (const QVariant &testModelItemId, const QVariant &testNodeUnitId, bool *ok)
Check if a node unit setup exists.
mdtTtTestNodeUnitSetupData getTestNodeUnitSetupData (const QVariant &testModelItemId, const QVariant &testNodeUnitId, bool *ok)
Get test node unit setup data.
bool updateTestNodeUnitData (const QVariant &testModelItemId, const QVariant &testNodeUnitId, const mdtTtTestNodeUnitSetupData &data)
Update test node unit setup data.
bool removeTestNodeUnitSetups (const mdtSqlTableSelection &s)
Remove test node units from TestNodeUnitSetup_tbl.
bool addItem (mdtTtTestModelItemData data, bool handleTransaction)
Add a test model item to TestModelItem_tbl.
bool addRoute (mdtTtTestModelItemRouteData routeData, bool handleTransaction)
Add a route to TestModelItemRoute_tbl.
bool addRoute (const QVariant &testModelItemId, const QVariant &testLinkId, const QVariant &measureTestNodeUnitConnectionId, const QList< mdtTtTestNodeUnitSetupData > &dataList, bool handleTransaction)
Add a route to TestModelItemRoute_tbl.
bool removeRoutes (const mdtSqlTableSelection &s)
Remove a route from TestModelItemRoute_tbl.
bool addTestNodeUnitSetup (const QVariant &testItemId, const QVariant &testNodeUnitId, const QVariant &state)
Add a test node unit setup.
bool removeTestNodeUnitSetup (const QVariant &tnusId)
Remove test node unit setup.
bool removeTestNodeUnitSetupsForTestItemId (const QVariant &testItemId)
Remove test node unit setup.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
template<typename T >
bool addRecordList (const QList< T > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField1, const QVariant &key1, const QString &matchField2, const QVariant &key2)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for test item edition.
Definition at line 36 of file mdtTtTestModelItem.h.
Constructor & Destructor Documentation
mdtTtTestModelItem::mdtTtTestModelItem (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 31 of file mdtTtTestModelItem.cpp.
Member Function Documentation
bool mdtTtTestModelItem::addItem (mdtTtTestModelItemData data, bool handleTransaction)
Add a test model item to TestModelItem_tbl.
Will also routes contained in data using addRoute(mdtTtTestModelItemRouteData, bool)
Definition at line 383 of file mdtTtTestModelItem.cpp.
References mdtTtBase::addRecord(), addRoute(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtTtBase::rollbackTransaction(), mdtTtTestModelItemData::routeDataList(), and mdtTtTestModelItemData::setId().
Referenced by mdtTtTestModel::generateTestModel().
bool mdtTtTestModelItem::addOrUpdateTestNodeUnitSetup (const mdtTtTestNodeUnitSetupData & data)
Add a test node unit to TestNodeUnitSetup_tbl.
If given setup allready exists (a couple of PK: TestModelItem_Id_FK, TestNodeUnit_Id_FK) it will be updated with given data.
Definition at line 281 of file mdtTtTestModelItem.cpp.
References mdtTtBase::addRecord(), testNodeUnitSetupExists(), updateTestNodeUnitData(), and mdtSqlRecord::value().
Referenced by addOrUpdateTestNodeUnitSetupList(), and addRoute().
bool mdtTtTestModelItem::addOrUpdateTestNodeUnitSetupList (const QList< mdtTtTestNodeUnitSetupData > & dataList)
Add a list of test node unit to TestNodeUnitSetup_tbl.
Definition at line 297 of file mdtTtTestModelItem.cpp.
References addOrUpdateTestNodeUnitSetup(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), and mdtTtBase::rollbackTransaction().
bool mdtTtTestModelItem::addRoute (mdtTtTestModelItemRouteData routeData, bool handleTransaction)
Add a route to TestModelItemRoute_tbl.
Will also add test link <-> test model item association and add or update needed test node unit setup (for path relays)
Definition at line 424 of file mdtTtTestModelItem.cpp.
References addOrUpdateTestNodeUnitSetup(), mdtTtBase::addRecord(), addTestLink(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtTtTestModelItemRouteData::measureConnectionId(), mdtTtBase::pvLastError, mdtTtBase::rollbackTransaction(), mdtTtTestModelItemRouteData::setId(), mdtTtTestModelItemRouteData::setupDataList(), mdtTtTestModelItemRouteData::testLinkId(), and mdtTtTestModelItemRouteData::testModelItemId().
Referenced by addItem(), and addRoute().
bool mdtTtTestModelItem::addRoute (const QVariant & testModelItemId, const QVariant & testLinkId, const QVariant & measureTestNodeUnitConnectionId, const QList< mdtTtTestNodeUnitSetupData > & dataList, bool handleTransaction)
Add a route to TestModelItemRoute_tbl.
See Also
addRoute(mdtTtTestModelItemRouteData, bool)
Definition at line 485 of file mdtTtTestModelItem.cpp.
References addRoute(), mdtTtTestModelItemRouteData::addSetupData(), mdtTtTestModelItemRouteData::setMeasureConnectionId(), mdtTtTestModelItemRouteData::setTestLinkId(), and mdtTtTestModelItemRouteData::setTestModelItemId().
bool mdtTtTestModelItem::addTestLink (const QVariant & testModelItemId, const QVariant & testLinkId)
Add a test link to TestModelItem_TestLink_tbl.
Definition at line 234 of file mdtTtTestModelItem.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtSqlRecord::setValue(), and testLinkExists().
Referenced by addRoute().
bool mdtTtTestModelItem::addTestNodeUnitSetup (const QVariant & testItemId, const QVariant & testNodeUnitId, const QVariant & state)
Add a test node unit setup.
Definition at line 506 of file mdtTtTestModelItem.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
mdtTtTestNodeUnitSetupData mdtTtTestModelItem::getTestNodeUnitSetupData (const QVariant & testModelItemId, const QVariant & testNodeUnitId, bool * ok)
Get test node unit setup data.
Definition at line 335 of file mdtTtTestModelItem.cpp.
References mdtTtBase::getData().
QList< QVariant > mdtTtTestModelItem::getTestNodeUnitSetupIdList (const QVariant & testItemId)
Get list of test node unit setup for given test item ID.
Definition at line 206 of file mdtTtTestModelItem.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QList< QVariant > mdtTtTestModelItem::getUsedNodeUnitIdList (const QVariant & testItemId, const QVariant & type)
Get a list of used node unit IDs for given test item ID.
If given type is not null, only matching test node unit will be returned
Definition at line 175 of file mdtTtTestModelItem.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtTtTestModelItem::removeRoutes (const mdtSqlTableSelection & s)
Remove a route from TestModelItemRoute_tbl.
Definition at line 501 of file mdtTtTestModelItem.cpp.
References mdtTtBase::removeData().
bool mdtTtTestModelItem::removeTestLinks (const mdtSqlTableSelection & s)
Remove test links.
Definition at line 276 of file mdtTtTestModelItem.cpp.
References mdtTtBase::removeData().
bool mdtTtTestModelItem::removeTestNodeUnitSetup (const QVariant & tnusId)
Remove test node unit setup.
Definition at line 539 of file mdtTtTestModelItem.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
bool mdtTtTestModelItem::removeTestNodeUnitSetups (const mdtSqlTableSelection & s)
Remove test node units from TestNodeUnitSetup_tbl.
Definition at line 378 of file mdtTtTestModelItem.cpp.
References mdtTtBase::removeData().
bool mdtTtTestModelItem::removeTestNodeUnitSetupsForTestItemId (const QVariant & testItemId)
Remove test node unit setup.
bool removeTestNodeUnitSetups(const QModelIndexList & indexListOfSelectedRows);
Remove all test node unit setup for given test item ID
bool mdtTtTestModelItem::removeTestNodeUnitSetups(const QModelIndexList & indexListOfSelectedRows) { int row;
for(row = 0; row < indexListOfSelectedRows.size(); ++row){ if(!removeTestNodeUnitSetup(indexListOfSelectedRows.at(row).data())){ return false; } }
return true; }
Definition at line 574 of file mdtTtTestModelItem.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QString mdtTtTestModelItem::sqlForTestLinkSelection (const QVariant & testModelItemId, const QVariant & testModelId) const
Get SQL statement for test link selection.
List all test links that not exists in TestModelItem_TestLink_tbl for given test model item ID, and that exist in TestModel_TestNode_tbl for given TestModel ID.
Definition at line 36 of file mdtTtTestModelItem.cpp.
QString mdtTtTestModelItem::sqlForTestNodeSelection (const QVariant & testModelId) const
Get SQL statement for test node selection.
Definition at line 154 of file mdtTtTestModelItem.cpp.
QString mdtTtTestModelItem::sqlForTestNodeUnitSelection (const QVariant & testModelItemId, const QVariant & testModelId) const
Get SQL statement for test node unit selection.
List all test node units that not exists in TestNodeUnitSetup_tbl for given testModelItemId, and that exists in TestModel_TestNode_tbl for given testModelId.
Definition at line 102 of file mdtTtTestModelItem.cpp.
bool mdtTtTestModelItem::testLinkExists (const QVariant & testModelItemId, const QVariant & testLinkId, bool & ok)
Check if a test link exists in TestModelItem_TestLink_tbl.
Definition at line 259 of file mdtTtTestModelItem.cpp.
Referenced by addTestLink().
bool mdtTtTestModelItem::testNodeUnitSetupExists (const QVariant & testModelItemId, const QVariant & testNodeUnitId, bool * ok)
Check if a node unit setup exists.
Definition at line 317 of file mdtTtTestModelItem.cpp.
References mdtTtBase::getData().
Referenced by addOrUpdateTestNodeUnitSetup().
bool mdtTtTestModelItem::updateTestNodeUnitData (const QVariant & testModelItemId, const QVariant & testNodeUnitId, const mdtTtTestNodeUnitSetupData & data)
Update test node unit setup data.
Definition at line 359 of file mdtTtTestModelItem.cpp.
References mdtSqlRecord::addField(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtSqlRecord::setValue(), and mdtTtBase::updateRecord().
Referenced by addOrUpdateTestNodeUnitSetup().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestModelItem.h
src/mdttools/mdttesttool/mdtTtTestModelItem.cpp