Multi diag tools: mdtUsbTransferPool< T > Class Template Reference
mdtUsbTransferPool< T > Class Template Reference
Storage of USB transfers.
#include <mdtUsbTransferPool.h>
Public Member Functions
mdtUsbTransferPool (unsigned int maxTransfers=50)
Constructor.
~mdtUsbTransferPool ()
Destructor.
void clear ()
Clear pool.
template<typename TransferHandlerType >
bool allocTransfers (unsigned int n, TransferHandlerType &th, libusb_device_handle *devHandle)
Alloc transfers.
template<typename TransferHandlerType >
bool allocTransfers (unsigned int n, TransferHandlerType &th, mdtUsbEndpointDescriptor endpointDescriptor, libusb_device_handle *devHandle)
Alloc transfers.
template<typename TransferHandlerType >
T * getTransfer (TransferHandlerType &th)
Get a transfer from pool.
template<typename TransferHandlerType >
T * getTransfer (TransferHandlerType &th, mdtUsbEndpointDescriptor endpointDescriptor)
Get a transfer from pool.
void restoreTransfer (T *transfer)
Restore a transfer.
int pendingTransferCount () const
Get number of pending transfers.
T * getPendingTransfer ()
Get a pending transfer.
std::vector< T * > getAllPendingTransfers ()
Get all pending transfers.
void restorePendingTransfers ()
Restore pending transfers to pool.
Detailed Description
template<typename T>
class mdtUsbTransferPool< T >
Storage of USB transfers.
This class handles 2 transfer queues:
Pool: available transfers to initiate I/O requests
Pending: transfers that where submitted but not yet completed
To get a transfer, use getTransfer(). This will directly put returned transfer to pending (but not yet completed) queue.
Because submitting a transfer, and cancelling the same transfer, can be done in concurrent way, a lock should be used to prevent this.
For example, submitting could be something like: 1) Lock mutex 2) transfer = getTransfer(); // Transfer will immediatly be available in pending queue. 3) Fill transfer 4) Submit transfer 5) Unlock mutex
Cancel function could be like: 1) Lock mutex 2) transfer = getPendingTransfer(); 3) Cancel transfer (submition only, libusb_cancel_transfer() will return before completion) 4) Unlock mutex
Finally, the transfer callback could be like: 1) Lock mutex 2) restoreTransfer() 3) Unlock mutex 4) If required, submit a new transfer (whenn the mutex is unlocked!)
Because several tasks must be done in a atomic way, it was chosen to not put any lock in this class.
Definition at line 64 of file mdtUsbTransferPool.h.
Constructor & Destructor Documentation
template<typename T> mdtUsbTransferPool< T >::mdtUsbTransferPool (unsigned int maxTransfers = 50) inline
Constructor.
Parameters
maxTransfers Maximum allowed number of transfers. This limit can be usefull for bug detection. If exceeded, getTransfer() will return a null pointer. In debug build, a assertion will also fail in this case.
Definition at line 75 of file mdtUsbTransferPool.h.
template<typename T> mdtUsbTransferPool< T >::~mdtUsbTransferPool () inline
Destructor.
Definition at line 84 of file mdtUsbTransferPool.h.
Member Function Documentation
template<typename T> template<typename TransferHandlerType > bool mdtUsbTransferPool< T >::allocTransfers (unsigned int n, TransferHandlerType & th, libusb_device_handle * devHandle) inline
Alloc transfers.
Parameters
n Number of transfers
th Application specific transfer handler
devHandle Must be a valid pointer to currently open device.
Precondition
n must be <= maxTransfers (given in constructor)
Definition at line 113 of file mdtUsbTransferPool.h.
Referenced by mdtUsbtmcTransferHandler::setup().
template<typename T> template<typename TransferHandlerType > bool mdtUsbTransferPool< T >::allocTransfers (unsigned int n, TransferHandlerType & th, mdtUsbEndpointDescriptor endpointDescriptor, libusb_device_handle * devHandle) inline
Alloc transfers.
Parameters
n Number of transfers
th Application specific transfer handler
devHandle Must be a valid pointer to currently open device.
endpointDescriptor USB endpoint descriptor.
Precondition
n must be <= maxTransfers (given in constructor)
Definition at line 132 of file mdtUsbTransferPool.h.
template<typename T> void mdtUsbTransferPool< T >::clear () inline
Clear pool.
Will also destroy each transfer.
Definition at line 93 of file mdtUsbTransferPool.h.
Referenced by mdtUsbTransferPool< mdtUsbtmcBulkTransfer >::~mdtUsbTransferPool().
template<typename T> std::vector<T*> mdtUsbTransferPool< T >::getAllPendingTransfers () inline
Get all pending transfers.
Note that returned transfers are not removed from pending queue. Be aware that another thread, or a callback, could restore a transfer at the same time, and that will invalidate returned queue.
Definition at line 220 of file mdtUsbTransferPool.h.
Referenced by mdtUsbtmcTransferHandler::beginAbortBulkIn(), mdtUsbtmcTransferHandler::getReceivedData(), mdtUsbtmcTransferHandler::submitCancelAllBulkInTransfers(), and mdtUsbtmcTransferHandler::submitCancelAllBulkOutTransfers().
template<typename T> T* mdtUsbTransferPool< T >::getPendingTransfer () inline
Get a pending transfer.
Will return 0 if no transfer is pending. This function will simply return the last transfer in pending queue, and not remove it. Removal from pending queue is done by restoreTransfer() or restorePendingTransfers().
Definition at line 206 of file mdtUsbTransferPool.h.
Referenced by mdtUsbtmcTransferHandler::dbgSubmitAbortOnePendingBulkInTransfer(), mdtUsbtmcTransferHandler::dbgSubmitAbortOnePendingBulkOutTransfer(), and mdtUsbtmcTransferHandler::submitControlTransfersCancel().
template<typename T> template<typename TransferHandlerType > T* mdtUsbTransferPool< T >::getTransfer (TransferHandlerType & th) inline
Get a transfer from pool.
Will create a new transfer if pool is empty.
The transfer is also filed into pending queue.
Returns
A valid pointer to transfer (or 0 on memory allocation failure)
Definition at line 151 of file mdtUsbTransferPool.h.
Referenced by mdtUsbtmcTransferHandler::dbgSubmitCustomBulkOutTransfer(), mdtUsbtmcTransferHandler::submitClearEndpointHalt(), mdtUsbtmcTransferHandler::submitCommand(), and mdtUsbtmcTransferHandler::submitInterruptInTransfer().
template<typename T> template<typename TransferHandlerType > T* mdtUsbTransferPool< T >::getTransfer (TransferHandlerType & th, mdtUsbEndpointDescriptor endpointDescriptor) inline
Get a transfer from pool.
Will create a new transfer if pool is empty.
The transfer is also filed into pending queue.
Returns
A valid pointer to transfer (or 0 on memory allocation failure)
Definition at line 169 of file mdtUsbTransferPool.h.
template<typename T> int mdtUsbTransferPool< T >::pendingTransferCount () const inline
Get number of pending transfers.
Definition at line 194 of file mdtUsbTransferPool.h.
Referenced by mdtUsbtmcTransferHandler::beginBulkIoClear(), mdtUsbtmcTransferHandler::handleBulkInTransferComplete(), mdtUsbtmcTransferHandler::handleControlTransferComplete(), mdtUsbtmcTransferHandler::hasPendingBulkInTransfers(), mdtUsbtmcTransferHandler::hasPendingBulkOutTransfers(), mdtUsbtmcTransferHandler::hasPendingTransfers(), mdtUsbtmcTransferHandler::restoreAllTransfers(), mdtUsbtmcTransferHandler::restoreBulkInTransferSA(), mdtUsbtmcTransferHandler::restoreBulkOutTransferSA(), mdtUsbtmcTransferHandler::submitCommand(), and mdtUsbtmcTransferHandler::submitStopRequest().
template<typename T> void mdtUsbTransferPool< T >::restorePendingTransfers () inline
Restore pending transfers to pool.
Definition at line 227 of file mdtUsbTransferPool.h.
Referenced by mdtUsbTransferPool< mdtUsbtmcBulkTransfer >::clear(), mdtUsbtmcTransferHandler::getReceivedData(), mdtUsbtmcTransferHandler::handleBulkInTransferComplete(), and mdtUsbtmcTransferHandler::restoreAllTransfers().
template<typename T> void mdtUsbTransferPool< T >::restoreTransfer (T * transfer) inline
Restore a transfer.
Definition at line 180 of file mdtUsbTransferPool.h.
Referenced by mdtUsbtmcTransferHandler::restoreBulkInTransferSA(), mdtUsbtmcTransferHandler::restoreBulkInTransferToPool(), mdtUsbtmcTransferHandler::restoreBulkOutTransferSA(), mdtUsbtmcTransferHandler::restoreBulkOutTransferToPool(), mdtUsbtmcTransferHandler::restoreControlTransferToPool(), and mdtUsbtmcTransferHandler::restoreInterruptInTransferToPool().
The documentation for this class was generated from the following file:
src/mdtport/mdtUsbTransferPool.h