Multi diag tools: mdtSqlSelectionDialog Class Reference
mdtSqlSelectionDialog Class Reference
Provide a way for the user to select row in a set of data.
#include <mdtSqlSelectionDialog.h>
Public Slots
void accept ()
Overloads QDialog to to build selection results.
void reject ()
Overloads QDialog to tell selectionResult() that it must return a empty result.
Public Member Functions
mdtSqlSelectionDialog (QWidget *parent=0)
Constructor.
~mdtSqlSelectionDialog ()
Destructor.
void setMessage (const QString &message)
Set a message that will be displayed to the user.
void setAllowEmptyResult (bool allow)
Set allow empty result.
void setQuery (const QString &sql, QSqlDatabase db, bool allowMultiSelection=false)
Set SQL query to display data.
void setHeaderData (const QString &fieldName, const QString &data)
Set a user friendly name for a column.
void setColumnHidden (int column, bool hide)
Set a coulumn as hidden.
void setColumnHidden (const QString &fieldName, bool hide)
Set a coulumn as hidden.
void clearColumnsSortOrder ()
Clear columns sort order.
void addColumnToSortOrder (int column, Qt::SortOrder order=Qt::AscendingOrder)
Add a column to columns sort order.
void addColumnToSortOrder (const QString &fieldName, Qt::SortOrder order=Qt::AscendingOrder)
Add a field to columns sort order.
void sort ()
Sort data.
void selectRows (const QString &fieldName, const QVariant &matchData)
Select rows.
void setSelectionResultColumns (const QList< int > &columns)
Set a list of column that will contain the selected data.
void setSelectionResultColumns (const QStringList &fields)
Set a list of column that will contain the selected data.
void addSelectionResultColumn (const QString &field)
Add a column to the list of column that will contain the selected data.
QSqlRecord selectedDataRecord ()
Return a record containing data that user has selected.
QList< QVariant > selectionResult ()
Return data that user has selected.
QModelIndexList selectionResults ()
Return data that user has selected.
QVariant selectedData (int row, const QString &fieldName)
Return data that user has selected.
Additional Inherited Members
Private Member Functions inherited from Ui_mdtSqlSelectionDialog
void setupUi (QDialog *mdtSqlSelectionDialog)
void retranslateUi (QDialog *mdtSqlSelectionDialog)
Private Attributes inherited from Ui_mdtSqlSelectionDialog
QVBoxLayout * verticalLayout
QLabel * pvMessageLabel
QTableView * pvTableView
QDialogButtonBox * buttonBox
Detailed Description
Provide a way for the user to select row in a set of data.
Definition at line 42 of file mdtSqlSelectionDialog.h.
Constructor & Destructor Documentation
mdtSqlSelectionDialog::mdtSqlSelectionDialog (QWidget * parent = 0)
Constructor.
Definition at line 35 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView, and Ui_mdtSqlSelectionDialog::setupUi().
mdtSqlSelectionDialog::~mdtSqlSelectionDialog ()
Destructor.
Definition at line 50 of file mdtSqlSelectionDialog.cpp.
Member Function Documentation
void mdtSqlSelectionDialog::accept () slot
Overloads QDialog to to build selection results.
Definition at line 305 of file mdtSqlSelectionDialog.cpp.
void mdtSqlSelectionDialog::addColumnToSortOrder (int column, Qt::SortOrder order = Qt::AscendingOrder)
Add a column to columns sort order.
Columns sort order is similar meaning than SQL ORDER BY clause.
For example, to sort columns in order 0, 2, 1 all ascending, call:
clearColumnsSortOrder();
addColumnToSortOrder(0, Qt::AscendingOrder);
addColumnToSortOrder(2, Qt::AscendingOrder);
addColumnToSortOrder(1, Qt::AscendingOrder);
Note: if given column is out of bound, it will simply be ignored.
Note: to apply sorting, call sort()
Definition at line 124 of file mdtSqlSelectionDialog.cpp.
References mdtSortFilterProxyModel::addColumnToSortOrder().
void mdtSqlSelectionDialog::addColumnToSortOrder (const QString & fieldName, Qt::SortOrder order = Qt::AscendingOrder)
Add a field to columns sort order.
Here it's possible to define a field name. Note that this method does nothing if sourceModel is not based on QSqlQueryModel.
Note: to apply sorting, call sort()
Definition at line 131 of file mdtSqlSelectionDialog.cpp.
References mdtSortFilterProxyModel::addColumnToSortOrder().
void mdtSqlSelectionDialog::addSelectionResultColumn (const QString & field)
Add a column to the list of column that will contain the selected data.
Note: if a given field not exists, it will be simply ignored.
Precondition
Model must be set with setModel() before using this method.
Definition at line 186 of file mdtSqlSelectionDialog.cpp.
References mdtError::commit(), mdtError::Error, and MDT_ERROR_SET_SRC.
Referenced by setSelectionResultColumns().
void mdtSqlSelectionDialog::clearColumnsSortOrder ()
Clear columns sort order.
See Also
addColumnToSortOrder()
Definition at line 117 of file mdtSqlSelectionDialog.cpp.
References mdtSortFilterProxyModel::clearColumnsSortOrder().
void mdtSqlSelectionDialog::reject () slot
Overloads QDialog to tell selectionResult() that it must return a empty result.
Definition at line 300 of file mdtSqlSelectionDialog.cpp.
QVariant mdtSqlSelectionDialog::selectedData (int row, const QString & fieldName)
Return data that user has selected.
Will return data from selection results that match given row, for given fieldName .
Note that row to give does not match given model's row, but is the row in selection.
This method alos works for multiple rows selection, but is slower than selectionResults() .
If row is out of bound or fieldName not exists, a invalid QVariant is returned.
Definition at line 262 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
QSqlRecord mdtSqlSelectionDialog::selectedDataRecord ()
Return a record containing data that user has selected.
The data are these that was specified with setSelectionResultColumns() , in the same order.
If the user reject the dialog, a empty record is returned.
This method works only for single row selection.
Definition at line 201 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
QList< QVariant > mdtSqlSelectionDialog::selectionResult ()
Return data that user has selected.
The data are these that was specified with setSelectionResultColumns() , in the same order.
If the user reject the dialog, a empty list is returned.
This method works only for single row selection.
Definition at line 231 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
QModelIndexList mdtSqlSelectionDialog::selectionResults ()
Return data that user has selected.
The index list only contains columns that where set with setSelectionResultColumns() or addSelectionResultColumn() .
This method alos works for multiple rows selection.
Definition at line 257 of file mdtSqlSelectionDialog.cpp.
void mdtSqlSelectionDialog::selectRows (const QString & fieldName, const QVariant & matchData)
Select rows.
Will select rows for witch data in field (designated by fieldName) matches given matchData .
Precondition
Model must be set with setModel() before using this method.
Definition at line 150 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
void mdtSqlSelectionDialog::setAllowEmptyResult (bool allow)
Set allow empty result.
If this flag is true, the dialog cannot be accepted if nothing was selected.
Default is false.
Definition at line 59 of file mdtSqlSelectionDialog.cpp.
void mdtSqlSelectionDialog::setColumnHidden (int column, bool hide)
Set a coulumn as hidden.
Definition at line 99 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
Referenced by setColumnHidden().
void mdtSqlSelectionDialog::setColumnHidden (const QString & fieldName, bool hide)
Set a coulumn as hidden.
Precondition
Model must be set with setModel() before using this method.
Definition at line 104 of file mdtSqlSelectionDialog.cpp.
References setColumnHidden().
void mdtSqlSelectionDialog::setHeaderData (const QString & fieldName, const QString & data)
Set a user friendly name for a column.
Precondition
Model must be set with setModel() before using this method.
Definition at line 85 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
void mdtSqlSelectionDialog::setMessage (const QString & message)
Set a message that will be displayed to the user.
Definition at line 54 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvMessageLabel.
void mdtSqlSelectionDialog::setQuery (const QString & sql, QSqlDatabase db, bool allowMultiSelection = false)
Set SQL query to display data.
Definition at line 64 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
void mdtSqlSelectionDialog::setSelectionResultColumns (const QList< int > & columns)
Set a list of column that will contain the selected data.
Note: if a given column is out of range, it will be simply ignored.
Precondition
Model must be set with setModel() before using this method.
Definition at line 170 of file mdtSqlSelectionDialog.cpp.
void mdtSqlSelectionDialog::setSelectionResultColumns (const QStringList & fields)
Set a list of column that will contain the selected data.
Note: if a given field not exists, it will be simply ignored.
Precondition
Model must be set with setModel() before using this method.
Definition at line 175 of file mdtSqlSelectionDialog.cpp.
References addSelectionResultColumn().
void mdtSqlSelectionDialog::sort ()
Sort data.
See Also
addColumnToSortOrder()
Definition at line 138 of file mdtSqlSelectionDialog.cpp.
References Ui_mdtSqlSelectionDialog::pvTableView.
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlSelectionDialog.h
src/mdtdatabase/mdtSqlSelectionDialog.cpp