Multi diag tools: mdtSqlFieldHandlerMdtDoubleEdit Class Reference
mdtSqlFieldHandlerMdtDoubleEdit Class Reference
Public Member Functions
mdtSqlFieldHandlerMdtDoubleEdit ()
void setDoubleEdit (mdtDoubleEdit *e)
void setData (const QVariant &data)
QVariant data () const
bool isNull () const
void clear ()
QWidget * widget ()
void setReadOnly (bool readOnly)
void setMaxLength (int maxLength)
Public Member Functions inherited from mdtSqlFieldHandlerAbstractDataWidget
virtual ~mdtSqlFieldHandlerAbstractDataWidget ()
virtual void setRange (qreal min, qreal max)
Detailed Description
Definition at line 371 of file mdtSqlFieldHandler.cpp.
Constructor & Destructor Documentation
mdtSqlFieldHandlerMdtDoubleEdit::mdtSqlFieldHandlerMdtDoubleEdit ()
Definition at line 387 of file mdtSqlFieldHandler.cpp.
Member Function Documentation
void mdtSqlFieldHandlerMdtDoubleEdit::clear () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 415 of file mdtSqlFieldHandler.cpp.
References mdtDoubleEdit::setValue().
QVariant mdtSqlFieldHandlerMdtDoubleEdit::data () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 404 of file mdtSqlFieldHandler.cpp.
References mdtDoubleEdit::value().
Referenced by isNull().
bool mdtSqlFieldHandlerMdtDoubleEdit::isNull () const virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 410 of file mdtSqlFieldHandler.cpp.
References data().
void mdtSqlFieldHandlerMdtDoubleEdit::setData (const QVariant & data) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 398 of file mdtSqlFieldHandler.cpp.
References mdtDoubleEdit::setValue().
void mdtSqlFieldHandlerMdtDoubleEdit::setDoubleEdit (mdtDoubleEdit * e)
Definition at line 392 of file mdtSqlFieldHandler.cpp.
Referenced by mdtSqlFieldHandler::setDataWidget().
void mdtSqlFieldHandlerMdtDoubleEdit::setMaxLength (int maxLength) virtual
Reimplemented from mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 432 of file mdtSqlFieldHandler.cpp.
void mdtSqlFieldHandlerMdtDoubleEdit::setReadOnly (bool readOnly) virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 426 of file mdtSqlFieldHandler.cpp.
References mdtDoubleEdit::setReadOnly().
QWidget * mdtSqlFieldHandlerMdtDoubleEdit::widget () virtual
Implements mdtSqlFieldHandlerAbstractDataWidget.
Definition at line 421 of file mdtSqlFieldHandler.cpp.
The documentation for this class was generated from the following file:
src/mdtdatabase/mdtSqlFieldHandler.cpp