Multi diag tools: mdtUsbtmcPort Class Reference
mdtUsbtmcPort Class Reference
Port to communicate with a USBTMC device.
#include <mdtUsbtmcPort.h>
Public Types
enum TransactionState_t {
TransactionState_t::Pending = 0, TransactionState_t::Done, TransactionState_t::Aborted, TransactionState_t::Error,
TransactionState_t::DeviceDisconnected
}
USBTMC transaction state.
Public Slots
void setError (const mdtError &error)
Set error.
Signals
void transactionFinished (TransactionState_t s)
Signal error.
Public Member Functions
mdtUsbtmcPort (QObject *parent=0)
Constructor.
~mdtUsbtmcPort ()
Destructor.
QList< mdtUsbDeviceDescriptor > scan ()
Enumerate attached USBTMC devices.
void setDeviceName (const QString &name)
Set device name.
QString deviceName () const
Get device name.
bool openDevice (uint16_t idVendor, uint16_t idProduct, const QString &serialNumber=QString())
Open device represented by given idVendor, idProduct and serial number.
bool openDevice (const mdtUsbDeviceDescriptor &deviceDescriptor, uint8_t bInterfaceNumber=0, bool clearDeviceList=true)
Open device represented by given descriptor.
void close ()
Close.
bool sendCommand (const QByteArray &command, int timeout=30000)
Send a command to device.
QByteArray sendQuery (const QByteArray &query, int timeout=30000)
Send a query to device.
bool clearBulkIo ()
Clear bulk I/O.
mdtError lastError ()
Get last error.
void thSetTransactionDone ()
Signal bulk transaction done.
void thSetTransactionAborted ()
Signal bulk transaction aborted.
void thSetDeviceDisconnected ()
Signal device disconnected.
Detailed Description
Port to communicate with a USBTMC device.
Definition at line 40 of file mdtUsbtmcPort.h.
Member Enumeration Documentation
enum mdtUsbtmcPort::TransactionState_t strong
USBTMC transaction state.
Enumerator
Pending
Transaction is in progress
Done
Transaction done without error
Aborted
Transaction aborted
Error
Transaction finished because a error occured
DeviceDisconnected
Device has been disconnected (note: currently not properly reported)
Definition at line 48 of file mdtUsbtmcPort.h.
Constructor & Destructor Documentation
mdtUsbtmcPort::mdtUsbtmcPort (QObject * parent = 0)
Constructor.
Definition at line 33 of file mdtUsbtmcPort.cpp.
References transactionFinished().
mdtUsbtmcPort::~mdtUsbtmcPort ()
Destructor.
Definition at line 44 of file mdtUsbtmcPort.cpp.
References close().
Member Function Documentation
bool mdtUsbtmcPort::clearBulkIo ()
Clear bulk I/O.
Note: is allready called by openDevice().
Definition at line 214 of file mdtUsbtmcPort.cpp.
References Aborted, Pending, and mdtUsbtmcTransferHandler::submitBulkIoClear().
Referenced by openDevice().
void mdtUsbtmcPort::close ()
Close.
Definition at line 154 of file mdtUsbtmcPort.cpp.
References mdtUsbPortThreadNew::stop().
Referenced by mdtDeviceScpi::disconnectFromDeviceEvent(), and ~mdtUsbtmcPort().
QString mdtUsbtmcPort::deviceName () const inline
Get device name.
See Also
setDeviceName()
Definition at line 80 of file mdtUsbtmcPort.h.
mdtError mdtUsbtmcPort::lastError () inline
Get last error.
Definition at line 127 of file mdtUsbtmcPort.h.
Referenced by mdtDeviceScpi::connectToDevice(), mdtDeviceScpi::sendCommand(), mdtPortTerm::sendCommandToUsbtmcPort(), and mdtDeviceScpi::sendQuery().
bool mdtUsbtmcPort::openDevice (uint16_t idVendor, uint16_t idProduct, const QString & serialNumber = QString())
Open device represented by given idVendor, idProduct and serial number.
Parameters
idVendor Vendor ID
idProduct Product ID
serialNumber Device serial number. Will be ignored if empty
Definition at line 92 of file mdtUsbtmcPort.cpp.
References mdtUsbDeviceList::clear(), mdtUsbDeviceList::findDevice(), mdtUsbDeviceDescriptor::isEmpty(), mdtUsbDeviceList::lastError(), and mdtUsbDeviceList::scan().
Referenced by mdtDeviceScpi::connectToDevice().
bool mdtUsbtmcPort::openDevice (const mdtUsbDeviceDescriptor & deviceDescriptor, uint8_t bInterfaceNumber = 0, bool clearDeviceList = true)
Open device represented by given descriptor.
Parameters
deviceDescriptor USB device descriptor to open. Must be a item returned by scan().
bInterfaceNumber Interface number to use.
clearDeviceList If true, internal device descriptors list will be cleared once device was open.
Definition at line 116 of file mdtUsbtmcPort.cpp.
References mdtUsbDeviceList::clear(), clearBulkIo(), mdtError::commit(), mdtError::Error, mdtUsbDeviceDescriptor::idString(), mdtUsbDeviceDescriptor::isEmpty(), mdtUsbtmcTransferHandler::lastError(), MDT_ERROR_SET_SRC, mdtUsbtmcTransferHandler::setDeviceName(), mdtError::setError(), and mdtUsbPortThreadNew::start().
QList< mdtUsbDeviceDescriptor > mdtUsbtmcPort::scan ()
Enumerate attached USBTMC devices.
Definition at line 59 of file mdtUsbtmcPort.cpp.
References mdtUsbDeviceList::clear(), mdtUsbDeviceList::lastError(), mdtUsbDeviceList::scan(), mdtError::setError(), mdtUsbDeviceList::usbtmcDeviceList(), and mdtError::Warning.
bool mdtUsbtmcPort::sendCommand (const QByteArray & command, int timeout = 30000)
Send a command to device.
Parameters
command Command to send
timeout Timeout [ms]
Definition at line 161 of file mdtUsbtmcPort.cpp.
References Done, mdtUsbtmcTxMessage::hasBytesToRead(), mdtUsbtmcTransferHandler::lastError(), Pending, setError(), and mdtUsbtmcTransferHandler::submitCommand().
Referenced by mdtDeviceScpi::sendCommand(), and mdtPortTerm::sendCommandToUsbtmcPort().
QByteArray mdtUsbtmcPort::sendQuery (const QByteArray & query, int timeout = 30000)
Send a query to device.
Parameters
query Query to send
timeout Timeout [ms]
Definition at line 182 of file mdtUsbtmcPort.cpp.
References Done, mdtUsbtmcTransferHandler::getReceivedData(), mdtUsbtmcTransferHandler::lastError(), Pending, setError(), and mdtUsbtmcTransferHandler::submitCommand().
Referenced by mdtPortTerm::sendCommandToUsbtmcPort(), and mdtDeviceScpi::sendQuery().
void mdtUsbtmcPort::setDeviceName (const QString & name)
Set device name.
Set a user friendly name for this device. Will also be used to build error messages.
Definition at line 84 of file mdtUsbtmcPort.cpp.
References mdtUsbtmcTransferHandler::setDeviceName().
Referenced by mdtDeviceScpi::nameChangedEvent().
void mdtUsbtmcPort::setError (const mdtError & error) slot
Set error.
Will also generate a event in main thread and wake up QCoreApplication::processEvents()
Note: used by mdtUsbtmcTransferHandler and mdtUsbtmcPortThread
Definition at line 228 of file mdtUsbtmcPort.cpp.
References Error, and transactionFinished().
Referenced by mdtUsbtmcTransferHandler::handleBulkInTransferComplete(), mdtUsbtmcTransferHandler::notifyError(), sendCommand(), and sendQuery().
void mdtUsbtmcPort::thSetDeviceDisconnected () inline
Signal device disconnected.
Note: used by mdtUsbtmcTransferHandler
Definition at line 155 of file mdtUsbtmcPort.h.
References DeviceDisconnected, and transactionFinished().
Referenced by mdtUsbtmcTransferHandler::notifyDeviceDisconnected().
void mdtUsbtmcPort::thSetTransactionAborted () inline
Signal bulk transaction aborted.
Note: used by mdtUsbtmcTransferHandler
Definition at line 146 of file mdtUsbtmcPort.h.
References Aborted, and transactionFinished().
Referenced by mdtUsbtmcTransferHandler::notifyBulkIoAborted().
void mdtUsbtmcPort::thSetTransactionDone () inline
Signal bulk transaction done.
Note: used by mdtUsbtmcTransferHandler
Definition at line 137 of file mdtUsbtmcPort.h.
References Done, and transactionFinished().
Referenced by mdtUsbtmcTransferHandler::handleBulkInTransferComplete(), mdtUsbtmcTransferHandler::handleBulkOutTransferComplete(), and mdtUsbtmcTransferHandler::notifyBulkIoDone().
void mdtUsbtmcPort::transactionFinished (TransactionState_t s) signal
Signal error.
Note: used by mdtUsbtmcTransferHandler
Signal that transaction is finished
See Also
setTransactionState().
Referenced by mdtUsbtmcPort(), setError(), thSetDeviceDisconnected(), thSetTransactionAborted(), and thSetTransactionDone().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbtmcPort.h
src/mdtport/mdtUsbtmcPort.cpp