Multi diag tools: mdtFrameUsbControl Class Reference
mdtFrameUsbControl Class Reference
USB Control frame.
#include <mdtFrameUsbControl.h>
Public Types
enum request_type_t { RT_STANDARD = 0, RT_CLASS = 1, RT_VENDOR = 2, RT_RESERVED = 3 }
Bits D6, D5 (Type) as defined for bmRequestType.
enum request_recipient_t { RR_DEVICE = 0, RR_INTERFACE = 1, RR_ENDPOINT = 2, RR_OTHER = 3 }
Bits D4-D0 (Recipient) as defined for bmRequestType.
Public Types inherited from mdtFrame
enum type_t {
FT_RAW, FT_RAW_TOP, FT_ASCII, FT_MODBUS_TCP,
FT_USBTMC
}
Frame type.
Public Member Functions
mdtFrameUsbControl ()
~mdtFrameUsbControl ()
void clearSub ()
mdtFrame subclass specific clear
void setDirectionDeviceToHost (bool deviceToHost)
Set direction.
bool directionIsDeviceToHost () const
Get direction.
void setRequestType (request_type_t type)
Set the request type.
request_type_t requestType () const
Get the request type.
void setRequestRecipient (request_recipient_t recipient)
Set request recipient.
request_recipient_t requestRecipient () const
Get request recipient.
void setbmRequestType (quint8 requestType)
Set bmRequestType.
quint8 bmRequestType () const
Get bmRequestType.
void setbRequest (quint8 request)
Set the bRequest.
quint8 bRequest () const
Get the bRequest.
void setwValue (quint16 value)
Set the wValue.
quint16 wValue () const
Get the wValue.
void setwIndex (quint16 index)
Set the wIndex.
quint16 wIndex () const
Get the wIndex.
void setwLength (quint16 length)
Set wLength.
quint16 wLength () const
Get wLength.
void encode ()
Encode the control frame.
Public Member Functions inherited from mdtFrame
mdtFrame ()
virtual ~mdtFrame ()
void setIgnoreNullValues (bool ignoreNullValues)
Set the ignore null values flag.
int putUntil (const char *data, char token, int maxLen)
Put data until EOF token was reached.
int putUntil (const char *data, QByteArray &token, int maxLen)
Put data until EOF token was reached.
bool isFull ()
Returns true if frame is full.
int remainCapacity ()
Returns the remain capacity.
int bytesToStore ()
Returns the bytes to store into the frame.
void setDirectlyComplete (bool dc)
Set the complete flag directly.
void setComplete ()
Set the frame as complete.
bool isComplete ()
Returns true if EOF condition was reached.
void clear ()
Overloaded function.
virtual int putData (const char *data, int len)
Put data into the frame.
virtual int eofSeqLen ()
Get the length of the end of frame sequence.
int take (char *data, int len)
Take some data.
int take (int len)
Take some data.
void setWaitAnAnswer (bool wait)
Tell a write/read thread that an answer is needed after a write frame.
bool waitAnAnswer () const
Know if an answer is needed after a write frame.
Additional Inherited Members
Protected Attributes inherited from mdtFrame
bool pvIgnoreNullValues
bool pvEOFcondition
bool pvWaitAnAnswer
Detailed Description
USB Control frame.
This is only a partial implementation of a USB control frame. The USB port API (see mdtUsbPort) uses libusb. libusb handles the most needed part of control transfers. The goal of this class is to send application specific requests, for ex. USBTMC and USBTMC 488.
See the USB 2.0 specifications, section 9.3 for details. See the USB488 specifications for USBTMC details.
Definition at line 39 of file mdtFrameUsbControl.h.
Member Enumeration Documentation
enum mdtFrameUsbControl::request_recipient_t
Bits D4-D0 (Recipient) as defined for bmRequestType.
See USB 2.0 specifications, section 9.3 for details.
Enumerator
RR_DEVICE
Device
RR_INTERFACE
Interface
RR_ENDPOINT
Endpoint
RR_OTHER
Other
Definition at line 58 of file mdtFrameUsbControl.h.
enum mdtFrameUsbControl::request_type_t
Bits D6, D5 (Type) as defined for bmRequestType.
See USB 2.0 specifications, section 9.3 for details.
Enumerator
RT_STANDARD
Standard
RT_CLASS
Class
RT_VENDOR
Vendor
RT_RESERVED
Reserved
Definition at line 47 of file mdtFrameUsbControl.h.
Constructor & Destructor Documentation
mdtFrameUsbControl::mdtFrameUsbControl ()
Definition at line 25 of file mdtFrameUsbControl.cpp.
References clearSub().
mdtFrameUsbControl::~mdtFrameUsbControl ()
Definition at line 31 of file mdtFrameUsbControl.cpp.
Member Function Documentation
quint8 mdtFrameUsbControl::bmRequestType () const
Get bmRequestType.
Definition at line 83 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPortManager::sendControlRequest().
quint8 mdtFrameUsbControl::bRequest () const
Get the bRequest.
Definition at line 93 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPortManager::sendControlRequest().
void mdtFrameUsbControl::clearSub () virtual
mdtFrame subclass specific clear
Reimplemented from mdtFrame.
Definition at line 35 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPort::controlTransferCallback(), mdtFrameUsbControl(), and mdtUsbPortManager::sendControlRequest().
bool mdtFrameUsbControl::directionIsDeviceToHost () const
Get direction.
Will read bit D7 in bmRequestType
Returns
true if direction is Device-to-host, else Host-to-device
Definition at line 53 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPortManager::sendControlRequest().
void mdtFrameUsbControl::encode ()
Encode the control frame.
To use to build a frame that will be sent to device.
Note: clear() is called internally.
Definition at line 128 of file mdtFrameUsbControl.cpp.
References mdtFrame::clear().
Referenced by mdtUsbPortManager::sendControlRequest(), and mdtUsbtmcPortManager::sendReadStatusByteRequest().
mdtFrameUsbControl::request_recipient_t mdtFrameUsbControl::requestRecipient () const
Get request recipient.
Will read bits D4 to D0 in bmRequestType
Definition at line 73 of file mdtFrameUsbControl.cpp.
mdtFrameUsbControl::request_type_t mdtFrameUsbControl::requestType () const
Get the request type.
Will read bits D6 and D5 in bmRequestType
Definition at line 63 of file mdtFrameUsbControl.cpp.
Referenced by setbmRequestType().
void mdtFrameUsbControl::setbmRequestType (quint8 requestType)
Set bmRequestType.
Definition at line 78 of file mdtFrameUsbControl.cpp.
References requestType().
Referenced by mdtUsbPort::controlTransferCallback(), and mdtUsbPortManager::sendControlRequest().
void mdtFrameUsbControl::setbRequest (quint8 request)
Set the bRequest.
Definition at line 88 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPort::controlTransferCallback(), mdtUsbPortManager::sendControlRequest(), and mdtUsbtmcPortManager::sendReadStatusByteRequest().
void mdtFrameUsbControl::setDirectionDeviceToHost (bool deviceToHost)
Set direction.
Will write bit D7 in bmRequestType
Parameters
deviceToHost If true, direction is Device-to-host, else Host-to-device
Definition at line 44 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPortManager::sendControlRequest(), and mdtUsbtmcPortManager::sendReadStatusByteRequest().
void mdtFrameUsbControl::setRequestRecipient (request_recipient_t recipient)
Set request recipient.
Will write bits D4 to D0 in bmRequestType
Definition at line 68 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbtmcPortManager::sendReadStatusByteRequest().
void mdtFrameUsbControl::setRequestType (request_type_t type)
Set the request type.
Will write bits D6 and D5 in bmRequestType
Definition at line 58 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbtmcPortManager::sendReadStatusByteRequest().
void mdtFrameUsbControl::setwIndex (quint16 index)
Set the wIndex.
Definition at line 108 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPort::addControlRequest(), mdtUsbPort::controlTransferCallback(), and mdtUsbPortManager::sendControlRequest().
void mdtFrameUsbControl::setwLength (quint16 length)
Set wLength.
Definition at line 118 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPort::controlTransferCallback(), mdtUsbPortManager::sendControlRequest(), and mdtUsbtmcPortManager::sendReadStatusByteRequest().
void mdtFrameUsbControl::setwValue (quint16 value)
Set the wValue.
Definition at line 98 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPort::controlTransferCallback(), mdtUsbPortManager::sendControlRequest(), and mdtUsbtmcPortManager::sendReadStatusByteRequest().
quint16 mdtFrameUsbControl::wIndex () const
Get the wIndex.
Definition at line 113 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPortManager::sendControlRequest().
quint16 mdtFrameUsbControl::wLength () const
Get wLength.
Definition at line 123 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPortManager::sendControlRequest().
quint16 mdtFrameUsbControl::wValue () const
Get the wValue.
Definition at line 103 of file mdtFrameUsbControl.cpp.
Referenced by mdtUsbPortManager::sendControlRequest().
The documentation for this class was generated from the following files:
src/mdtutils/mdtFrameUsbControl.h
src/mdtutils/mdtFrameUsbControl.cpp