Multi diag tools: mdtDoubleValidator Class Reference
mdtDoubleValidator Class Reference
Double validator.
#include <mdtDoubleValidator.h>
Public Member Functions
mdtDoubleValidator (QObject *parent=0)
Constructor.
void setSuffix (const QString &s)
Set a custom suffix.
void setBottom (double min)
Set bottom value.
double bottom () const
Get bottom value.
void setTop (double max)
Set top value.
double top () const
Get top value.
void setRange (double min, double max, int decimals=0)
Set range.
QValidator::State validate (QString &input, int &pos) const
Validate input.
Detailed Description
Double validator.
mdtDoubleValidator uses QDoubleValidator internally, but also accepts a power of 10 suffix.
Definition at line 33 of file mdtDoubleValidator.h.
Constructor & Destructor Documentation
mdtDoubleValidator::mdtDoubleValidator (QObject * parent = 0)
Constructor.
Definition at line 28 of file mdtDoubleValidator.cpp.
Member Function Documentation
double mdtDoubleValidator::bottom () const inline
Get bottom value.
Definition at line 55 of file mdtDoubleValidator.h.
void mdtDoubleValidator::setBottom (double min)
Set bottom value.
Definition at line 38 of file mdtDoubleValidator.cpp.
Referenced by mdtDoubleEdit::setMinimum().
void mdtDoubleValidator::setRange (double min, double max, int decimals = 0)
Set range.
Definition at line 48 of file mdtDoubleValidator.cpp.
void mdtDoubleValidator::setSuffix (const QString & s)
Set a custom suffix.
Can be typically a unit (A, V, ...)
Definition at line 33 of file mdtDoubleValidator.cpp.
Referenced by mdtDoubleEdit::setUnit().
void mdtDoubleValidator::setTop (double max)
Set top value.
Definition at line 43 of file mdtDoubleValidator.cpp.
Referenced by mdtDoubleEdit::setMaximum().
double mdtDoubleValidator::top () const inline
Get top value.
Definition at line 63 of file mdtDoubleValidator.h.
QValidator::State mdtDoubleValidator::validate (QString & input, int & pos) const
Validate input.
Definition at line 53 of file mdtDoubleValidator.cpp.
References mdtDoubleEdit::infinityString().
Referenced by mdtDoubleEdit::setValueString().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtDoubleValidator.h
src/mdtutilsgui/mdtDoubleValidator.cpp