Multi diag tools: mdtPortThreadHelper Class Reference
mdtPortThreadHelper Class Reference
Helper class for mdtPortThread and subclasses.
#include <mdtPortThreadHelper.h>
Signals
void readProcessBegin ()
Emitted when a read process begins.
void writeProcessBegin ()
Emitted when a write process begins.
void newFrameReaden ()
Emited when a new frame is available.
Public Member Functions
mdtPortThreadHelper (QObject *parent=0)
Constructor.
virtual ~mdtPortThreadHelper ()
Destructor.
void setPort (mdtAbstractPort *port)
Set the port instance.
void setThread (mdtPortThread *thread)
Set the thread instance.
mdtAbstractPort::error_t handleCommonReadErrors (mdtAbstractPort::error_t portError)
Handle common read errors.
mdtAbstractPort::error_t handleCommonWriteErrors (mdtAbstractPort::error_t portError)
Handle common write errors.
mdtAbstractPort::error_t handleCommonReadWriteErrors (mdtAbstractPort::error_t portError)
Handle common read and write errors.
bool getNewFrameRead ()
Get a new frame for reading data from port.
void submitCurrentReadFrame (bool notify)
Submit current read frame.
void restoreCurrentReadFrameToPool ()
Restore current read frame to pool.
int submitReadenData (const char *data, int size, bool emitNewFrameReaden)
Store readen data into frame.
bool getNewFrameWrite ()
Get a new frame for writing data to port.
void restoreCurrentWriteFrameToPool ()
Restore current write frame to pool.
void setCurrentReadFrame (mdtFrame *frame)
Set current read frame.
mdtFrame * currentReadFrame ()
Get current read frame.
void setCurrentWriteFrame (mdtFrame *frame)
Set current write frame.
mdtFrame * currentWriteFrame ()
Get current write frame.
Protected Slots
virtual void requestWrite ()
Protected Member Functions
void notifyError (mdtAbstractPort::error_t error, bool renotifySameError=false)
Calls mdtPortThread::notifyError()
virtual mdtAbstractPort::error_t reconnect (bool notify)
Call subclass reconnect() method.
Protected Attributes
mdtAbstractPort * pvPort
mdtPortThread * pvThread
Detailed Description
Helper class for mdtPortThread and subclasses.
This class was introduced during TCP socket part redesing.
Goal is to put common methods in a dedicated class, avoiding the to big complexity of mdtPortThread.
Definition at line 37 of file mdtPortThreadHelper.h.
Constructor & Destructor Documentation
mdtPortThreadHelper::mdtPortThreadHelper (QObject * parent = 0)
Constructor.
Definition at line 38 of file mdtPortThreadHelper.cpp.
References pvPort, and pvThread.
mdtPortThreadHelper::~mdtPortThreadHelper () virtual
Destructor.
Will call:
restoreCurrentReadFrameToPool()
restoreCurrentWriteFrameToPool();
Definition at line 47 of file mdtPortThreadHelper.cpp.
References restoreCurrentReadFrameToPool(), and restoreCurrentWriteFrameToPool().
Member Function Documentation
mdtFrame * mdtPortThreadHelper::currentReadFrame ()
Get current read frame.
Can return a null pointer.
Definition at line 328 of file mdtPortThreadHelper.cpp.
Referenced by mdtPortThreadHelperPort::readFromPort().
mdtFrame * mdtPortThreadHelper::currentWriteFrame ()
Get current write frame.
Can return a null pointer.
Definition at line 338 of file mdtPortThreadHelper.cpp.
Referenced by mdtPortThreadHelperPort::writeDataToPort(), and mdtPortThreadHelperPort::writeToPort().
bool mdtPortThreadHelper::getNewFrameRead ()
Get a new frame for reading data from port.
This is a helper method to get a new frame in port's read frames pool.
It can hapen that the read frames pool is empty. In this case, a error will be generated in the mdtError log system, and notified with ReadPoolEmpty error. This method will also block (sleep) until a frame is available in read pool.
Todo:
Currently implemented in polling, should be done with a wait condition.
Note about port mutex handling:
The port mutext must be locked before calling this method. Internally, it will be unlocked during wait, and will be locked again. So, the port mutex is allways locked when this method returns.
Note: internally, currentReadFrame is updated.
Returns
True on success, false if thread is stopping.
Precondition
Port must be set with setPort().
Thread must be set with setThread().
Postcondition
If this method returns true, currentReadFrame() will return a valid pointer.
Definition at line 180 of file mdtPortThreadHelper.cpp.
References mdtError::commit(), mdtError::Info, mdtAbstractPort::lockMutex(), MDT_ERROR_SET_SRC, MDT_NO_ERROR, MDT_PORT_QUEUE_EMPTY_ERROR, msleep, mdtAbstractPort::NoError, notifyError(), pvPort, pvThread, mdtAbstractPort::readFramesPool(), mdtAbstractPort::ReadPoolEmpty, mdtPortThread::runningFlagSet(), mdtAbstractPort::unlockMutex(), and mdtError::Warning.
Referenced by handleCommonReadErrors(), mdtPortThreadHelperPort::readFromPort(), and submitReadenData().
bool mdtPortThreadHelper::getNewFrameWrite ()
Get a new frame for writing data to port.
This is a helper method to get a new frame in port's write frames pool.
If no frame is available for write, this method will block the caller thread until one is avaliable.
Note about port mutex handling:
The port mutext must be locked before calling this method. Internally, it will be unlocked during wait, and will be locked again. So, the port mutex is allways locked when this method returns.
Note: internally, currentWriteFrame is updated.
Returns
True on success, false if thread is stopping.
Precondition
Port must be set with setPort().
Thread must be set with setThread().
Postcondition
If this method returns true, currentWriteFrame() will return a valid pointer.
See Also
mdtAbstractPort
Definition at line 292 of file mdtPortThreadHelper.cpp.
References mdtAbstractPort::getFrameToWrite(), pvPort, pvThread, and mdtPortThread::runningFlagSet().
mdtAbstractPort::error_t mdtPortThreadHelper::handleCommonReadErrors (mdtAbstractPort::error_t portError)
Handle common read errors.
This is a helper method for common errors.
If no read frame is currently set (i.e. currentReadFrame() returns 0), a UnhandledError is returned and error is logged.
Handled errors are:
mdtAbstractPort::Disconnected: will try to reconnect
mdtAbstractPort::ReadCanceled.
mdtAbstractPort::ReadTimeout.
For all cases, except Disconnected, the current frame is cleared and the notification is sent. For Disconnected, the frame is restored to port's readFramesPool pool.
If this method is called by a non running thread, a warning will be logged.
Returns
ErrorHandled if error could be handled or other error (most of cases a UnhandledError).
Precondition
port must be set with setPort().
Thread must be set with setThread().
Postcondition
If frame is null, a UnhandledError is returned.
Definition at line 70 of file mdtPortThreadHelper.cpp.
References mdtFrame::clear(), mdtFrame::clearSub(), mdtError::commit(), mdtAbstractPort::Disconnected, mdtError::Error, mdtAbstractPort::ErrorHandled, getNewFrameRead(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, mdtAbstractPort::NoError, notifyError(), pvPort, pvThread, mdtAbstractPort::ReadCanceled, mdtAbstractPort::ReadTimeout, reconnect(), restoreCurrentReadFrameToPool(), mdtPortThread::runningFlagSet(), mdtAbstractPort::UnhandledError, and mdtError::Warning.
Referenced by handleCommonReadWriteErrors().
mdtAbstractPort::error_t mdtPortThreadHelper::handleCommonReadWriteErrors (mdtAbstractPort::error_t portError)
Handle common read and write errors.
This is a helper class for common errors.
If currentReadFrame is not null, handleCommonReadErrors() is called first. If no error was handled, and currentWriteFrame is not null, handleCommonWriteErrors() is called.
Returns
ErrorHandled if error could be handled or other error (most of cases a UnhandledError).
Precondition
port must be set with setPort().
Thread must be set with setThread().
Definition at line 162 of file mdtPortThreadHelper.cpp.
References mdtAbstractPort::ErrorHandled, handleCommonReadErrors(), handleCommonWriteErrors(), pvPort, and pvThread.
mdtAbstractPort::error_t mdtPortThreadHelper::handleCommonWriteErrors (mdtAbstractPort::error_t portError)
Handle common write errors.
This is a helper class for port common errors.
If no write frame is currently set (i.e. currentWriteFrame() returns 0), a UnhandledError is returned and error is logged.
Handled errors are:
mdtAbstractPort::Disconnected: will try to reconnect
mdtAbstractPort::WriteCanceled.
mdtAbstractPort::WriteTimeout.
For all cases, the current frame is put back to write pool and the notification is sent.
If this method is called by a non running thread, a warning will be logged.
Returns
ErrorHandled if error could be handled or other error (most of cases a UnhandledError).
Precondition
port must be set with setPort().
Thread must be set with setThread().
Definition at line 120 of file mdtPortThreadHelper.cpp.
References mdtError::commit(), mdtAbstractPort::Disconnected, mdtError::Error, mdtAbstractPort::ErrorHandled, MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, mdtAbstractPort::NoError, notifyError(), pvPort, pvThread, mdtAbstractPort::ReadCanceled, mdtAbstractPort::ReadTimeout, reconnect(), restoreCurrentWriteFrameToPool(), mdtPortThread::runningFlagSet(), mdtAbstractPort::UnhandledError, and mdtError::Warning.
Referenced by handleCommonReadWriteErrors(), and mdtPortThreadHelperPort::writeToPort().
void mdtPortThreadHelper::newFrameReaden () signal
Emited when a new frame is available.
This signal is connected to mdtPortThread::void newFrameReaden() in setThread().
Referenced by setThread(), and submitCurrentReadFrame().
void mdtPortThreadHelper::notifyError (mdtAbstractPort::error_t error, bool renotifySameError = false) protected
Calls mdtPortThread::notifyError()
Precondition
Thread must be set with setThread().
Definition at line 343 of file mdtPortThreadHelper.cpp.
References mdtPortThread::notifyError(), and pvThread.
Referenced by getNewFrameRead(), handleCommonReadErrors(), handleCommonWriteErrors(), and mdtPortThreadHelperPort::writeToPort().
void mdtPortThreadHelper::readProcessBegin () signal
Emitted when a read process begins.
This signal is connected to mdtPortThread::void readProcessBegin() in setThread().
Referenced by setThread(), and submitReadenData().
mdtAbstractPort::error_t mdtPortThreadHelper::reconnect (bool notify) protected virtual
Call subclass reconnect() method.
This implementation does nothing and allways returns a UnhandledError.
Reimplemented in mdtPortThreadHelperPort.
Definition at line 350 of file mdtPortThreadHelper.cpp.
References mdtAbstractPort::UnhandledError.
Referenced by handleCommonReadErrors(), and handleCommonWriteErrors().
void mdtPortThreadHelper::requestWrite () protected virtual slot
Definition at line 355 of file mdtPortThreadHelper.cpp.
void mdtPortThreadHelper::restoreCurrentReadFrameToPool ()
Restore current read frame to pool.
currentReadFrame will be enqueued in port's readFramesPool queue.
If currentReadFrame is null, nothing happens.
After this call, currentReadFrame() will return a null pointer.
Precondition
Port must be set with setPort().
Thread must be set with setThread().
Port's readFramesPool queue must not allready contain currentReadFrame.
Definition at line 231 of file mdtPortThreadHelper.cpp.
References pvPort, pvThread, and mdtAbstractPort::readFramesPool().
Referenced by handleCommonReadErrors(), and ~mdtPortThreadHelper().
void mdtPortThreadHelper::restoreCurrentWriteFrameToPool ()
Restore current write frame to pool.
currentWriteFrame will be enqueued in port's writeFramesPool queue.
If currentWriteFrame is null, nothing happens.
After this call, currentWriteFrame() will return a null pointer.
Precondition
Port must be set with setPort().
Thread must be set with setThread().
Port's writeFramesPool queue must not allready contain currentWriteFrame.
Definition at line 310 of file mdtPortThreadHelper.cpp.
References pvPort, pvThread, and mdtAbstractPort::writeFramesPool().
Referenced by handleCommonWriteErrors(), mdtPortThreadHelperPort::writeToPort(), and ~mdtPortThreadHelper().
void mdtPortThreadHelper::setCurrentReadFrame (mdtFrame * frame)
Set current read frame.
Definition at line 323 of file mdtPortThreadHelper.cpp.
void mdtPortThreadHelper::setCurrentWriteFrame (mdtFrame * frame)
Set current write frame.
Definition at line 333 of file mdtPortThreadHelper.cpp.
void mdtPortThreadHelper::setPort (mdtAbstractPort * port)
Set the port instance.
Precondition
port must be a valid pointer.
Definition at line 53 of file mdtPortThreadHelper.cpp.
References pvPort.
void mdtPortThreadHelper::setThread (mdtPortThread * thread)
Set the thread instance.
Precondition
thread must be a valid pointer.
Definition at line 60 of file mdtPortThreadHelper.cpp.
References newFrameReaden(), pvThread, readProcessBegin(), and writeProcessBegin().
void mdtPortThreadHelper::submitCurrentReadFrame (bool notify)
Submit current read frame.
currentReadFrame will be enqueued in port's readenFrames queue.
If currentReadFrame is null, nothing happens.
After this call, currentReadFrame() will return a null pointer.
Parameters
notify If true, newFrameReaden() signal is emitted.
Precondition
Port must be set with setPort().
Thread must be set with setThread().
Port's readenFrames queue must not allready contain currentReadFrame.
Definition at line 215 of file mdtPortThreadHelper.cpp.
References newFrameReaden(), pvPort, pvThread, and mdtAbstractPort::readenFrames().
Referenced by submitReadenData().
int mdtPortThreadHelper::submitReadenData (const char * data, int size, bool emitNewFrameReaden)
Store readen data into frame.
This method helps to store data that was readen. If frame becomes full, it will be enqueued in port's readen frames, an newFrameReaden() signal is emitted.
Note about port mutex handling:
The port mutex must be locked before calling this method. Internally, it will be unlocked during wait, and will be locked again. So, the port mutex is allways locked when this method returns.
Parameters
data Pointer to buffer that contains readen data.
size Size of readen data.
emitNewFrameReaden If true, newFrameReaden() will be emitted each time a complete frame was generated.
Returns
The number of frames completed during the process. This can be helpful for query/reply protocols in witch the standard reply should be one frame. On error, one of the mdtAbstractPort::error_t is returned and thread must handle error itself.
Precondition
Port must be set with setPort().
Thread must be set with setThread().
data must be valid.
Definition at line 244 of file mdtPortThreadHelper.cpp.
References mdtFrame::bytesToStore(), mdtFrame::eofSeqLen(), getNewFrameRead(), mdtFrame::putData(), pvPort, pvThread, readProcessBegin(), submitCurrentReadFrame(), and mdtAbstractPort::UnhandledError.
Referenced by mdtPortThreadHelperPort::readFromPort().
void mdtPortThreadHelper::writeProcessBegin () signal
Emitted when a write process begins.
This signal is connected to mdtPortThread::void writeProcessBegin() in setThread().
Referenced by setThread(), and mdtPortThreadHelperPort::writeDataToPort().
Member Data Documentation
mdtAbstractPort* mdtPortThreadHelper::pvPort protected
Definition at line 310 of file mdtPortThreadHelper.h.
Referenced by mdtPortThreadHelperSocket::connectToHost(), getNewFrameRead(), getNewFrameWrite(), handleCommonReadErrors(), handleCommonReadWriteErrors(), handleCommonWriteErrors(), mdtPortThreadHelper(), mdtPortThreadHelperPort::readFromPort(), mdtPortThreadHelperPort::reconnect(), restoreCurrentReadFrameToPool(), restoreCurrentWriteFrameToPool(), setPort(), mdtPortThreadHelperSocket::setSocket(), submitCurrentReadFrame(), submitReadenData(), mdtPortThreadHelperPort::writeDataToPort(), and mdtPortThreadHelperPort::writeToPort().
mdtPortThread* mdtPortThreadHelper::pvThread protected
Definition at line 311 of file mdtPortThreadHelper.h.
Referenced by getNewFrameRead(), getNewFrameWrite(), handleCommonReadErrors(), handleCommonReadWriteErrors(), handleCommonWriteErrors(), mdtPortThreadHelper(), notifyError(), mdtPortThreadHelperPort::readFromPort(), mdtPortThreadHelperPort::reconnect(), restoreCurrentReadFrameToPool(), restoreCurrentWriteFrameToPool(), setThread(), submitCurrentReadFrame(), submitReadenData(), mdtPortThreadHelperPort::writeDataToPort(), and mdtPortThreadHelperPort::writeToPort().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortThreadHelper.h
src/mdtport/mdtPortThreadHelper.cpp