Multi diag tools: mdtClUnitVehicleType Class Reference
mdtClUnitVehicleType Class Reference
Helper class for Unit <-> VehicleType assignments.
#include <mdtClUnitVehicleType.h>
Public Member Functions
mdtClUnitVehicleType (QObject *parent, QSqlDatabase db)
Constructor.
~mdtClUnitVehicleType ()
Destructor.
QString sqlForVehicleTypeNotAssignedToUnit (const QVariant &unitId) const
Get SQL statement for vehicle type assignment selection.
bool addUnitVehicleTypeAssignment (const QVariant &unitId, const QVariant &vehicleTypeId)
Add unit <-> vehicle type assignment.
bool addUnitVehicleTypeAssignments (const QVariant &unitId, const QList< QVariant > &vehicleTypeIdList)
Add unit <-> vehicle type assignments.
bool addUnitVehicleTypeAssignments (const QVariant &unitId, const QModelIndexList &vehicleTypeIdList)
Add unit <-> vehicle type assignments.
bool removeUnitVehicleAssignment (const QVariant &unitId, const QVariant &vehicleTypeId)
Remove unit <-> vehicle type assignment.
bool removeUnitVehicleAssignments (const QVariant &unitId, const QList< QVariant > &vehicleTypeIdList)
Remove unit <-> vehicle type assignments.
bool removeUnitVehicleAssignments (const QVariant &unitId, const QModelIndexList &vehicleTypeIdList)
Remove unit <-> vehicle type assignments.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
bool addRecordList (const QList< mdtSqlRecord > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for Unit <-> VehicleType assignments.
Definition at line 33 of file mdtClUnitVehicleType.h.
Constructor & Destructor Documentation
mdtClUnitVehicleType::mdtClUnitVehicleType (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 29 of file mdtClUnitVehicleType.cpp.
mdtClUnitVehicleType::~mdtClUnitVehicleType ()
Destructor.
Definition at line 34 of file mdtClUnitVehicleType.cpp.
Member Function Documentation
bool mdtClUnitVehicleType::addUnitVehicleTypeAssignment (const QVariant & unitId, const QVariant & vehicleTypeId)
Add unit <-> vehicle type assignment.
Definition at line 54 of file mdtClUnitVehicleType.cpp.
References addUnitVehicleTypeAssignments().
bool mdtClUnitVehicleType::addUnitVehicleTypeAssignments (const QVariant & unitId, const QList< QVariant > & vehicleTypeIdList)
Add unit <-> vehicle type assignments.
Definition at line 63 of file mdtClUnitVehicleType.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by addUnitVehicleTypeAssignment(), and addUnitVehicleTypeAssignments().
bool mdtClUnitVehicleType::addUnitVehicleTypeAssignments (const QVariant & unitId, const QModelIndexList & vehicleTypeIdList)
Add unit <-> vehicle type assignments.
Precondition
vehicleTypeIdList must contain only 1 column.
Definition at line 99 of file mdtClUnitVehicleType.cpp.
References addUnitVehicleTypeAssignments().
bool mdtClUnitVehicleType::removeUnitVehicleAssignment (const QVariant & unitId, const QVariant & vehicleTypeId)
Remove unit <-> vehicle type assignment.
Definition at line 113 of file mdtClUnitVehicleType.cpp.
References removeUnitVehicleAssignments().
bool mdtClUnitVehicleType::removeUnitVehicleAssignments (const QVariant & unitId, const QList< QVariant > & vehicleTypeIdList)
Remove unit <-> vehicle type assignments.
Will also remove vehicle type links (from VehicleType_Link_tbl) using given unit ID.
Definition at line 122 of file mdtClUnitVehicleType.cpp.
References mdtTtBase::beginTransaction(), mdtError::commit(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtClLink::removeVehicleTypeLinkByUnitId(), mdtTtBase::rollbackTransaction(), mdtError::setError(), and mdtError::setSystemError().
Referenced by removeUnitVehicleAssignment(), and removeUnitVehicleAssignments().
bool mdtClUnitVehicleType::removeUnitVehicleAssignments (const QVariant & unitId, const QModelIndexList & vehicleTypeIdList)
Remove unit <-> vehicle type assignments.
Definition at line 169 of file mdtClUnitVehicleType.cpp.
References removeUnitVehicleAssignments().
QString mdtClUnitVehicleType::sqlForVehicleTypeNotAssignedToUnit (const QVariant & unitId) const
Get SQL statement for vehicle type assignment selection.
List all vehicle types that are not assigned to given unit
Definition at line 38 of file mdtClUnitVehicleType.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitVehicleType.h
src/mdttools/mdttesttool/mdtcablelist/mdtClUnitVehicleType.cpp