Multi diag tools: mdtError Class Reference
mdtError Class Reference
mdtError contains informations about a error that occured
#include <mdtError.h>
Public Types
enum level_t { NoError = 0x00, Info = 0x01, Warning = 0x02, Error = 0x04 }
Error level.
Public Member Functions
mdtError ()
Constructor.
mdtError (int number, const QString &text, level_t level)
Construct new error.
mdtError (const QString &text, level_t level)
Construct new error.
void setError (const QString &text, level_t level)
Set error.
void updateText (const QString &text)
Update error text.
void clear ()
Clear.
void setSystemError (int number, const QString &text)
Add system returned error (for example, errno)
void setSource (const QString &filePath, int fileLine, const QString &className, const QString &functionName)
Add system error (for Windows API)
void commit ()
Send error to output.
int number () const
Error number.
QString text () const
Error text.
level_t level () const
Error level level_t.
QMessageBox::Icon levelIcon () const
Map the level to a QMessageBox Icon.
int systemNumber () const
Error number returned from system if available.
QString systemText () const
Error text returned from system, if available.
QString systemErrorString (QObject *obj=0) const
Error number and text from system, if available.
void setInformativeText (const QString &text)
Set informative text.
QString informativeText () const
Get informative text.
QString functionName () const
Error source function.
QString fileName () const
Error source file (name only)
int fileLine () const
Error source line.
Detailed Description
mdtError contains informations about a error that occured
Currently, a mdtError contains several informations:
text (mandatory) : a description of the error that occured . Access: mdtError(const QString&, level_t) , text() .
level (mandatory) : the severity of the error . Access: mdtError(const QString&, level_t) , level() , levelIcon() .
systemNumber (optional) : error number returned by a system (or other library) call . Access: setSystemError() , systemNumber() , systemErrorString() .
systemText (optional) : error text number returned by a system (or other library) call . Access: setSystemError() , systemText() , systemErrorString() .
informativeText (optional) : can be used the same way than QMessageBox . Access : setInformativeText() , informativeText() .
number : currently used with mdt_error_t enum, but it seems that this is not a good idea, and this will change once a better one is found ...
This class contains the information of a error. To just put it to standard defined outputs, use commit() .
Note: no copy constrctor/operator are defined, because only primitve and copiable objects are used, but a mdtError can be copied .
Definition at line 84 of file mdtError.h.
Member Enumeration Documentation
enum mdtError::level_t
Error level.
Enumerator
NoError
No error .
Info
Just a information, application continues to work in normal way .
Warning
Error that could be handled
Error
Error that was not handled
Definition at line 90 of file mdtError.h.
Constructor & Destructor Documentation
mdtError::mdtError ()
Constructor.
Definition at line 29 of file mdtError.cpp.
References NoError.
mdtError::mdtError (int number, const QString & text, mdtError::level_t level)
Construct new error.
Deprecated:
If no good idea falls in for the usage of number , this constrctor should become obselete .
Definition at line 34 of file mdtError.cpp.
References level(), number(), and text().
mdtError::mdtError (const QString & text, level_t level)
Construct new error.
Definition at line 46 of file mdtError.cpp.
References level(), and text().
Member Function Documentation
void mdtError::clear ()
Clear.
Definition at line 70 of file mdtError.cpp.
References NoError.
Referenced by mdtSqlRecord::clear(), mdtSqlDatabaseManager::openDatabaseSqlite(), and setError().
void mdtError::commit ()
Send error to output.
Definition at line 113 of file mdtError.cpp.
References mdtErrorOut::addError().
Referenced by mdtSqlRecord::addAllFields(), mdtTtTestConnectionCable::addCable(), mdtSqlForm::addChildTable(), mdtClArticle::addComponent(), mdtClUnit::addComponent(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtSqlRecord::addField(), mdtDataTableManager::addFieldMapping(), mdtSqlSchemaTable::addFieldToForeignKey(), mdtSqlSchemaTable::addFieldToIndex(), mdtClDirectLink::addLink(), mdtTtTestConnectionCable::addLink(), mdtTtBase::addRecord(), mdtSqlRelation::addRelation(), mdtSqlForm::addRelation(), mdtSqlSelectionDialog::addSelectionResultColumn(), mdtTtTestModel::addTestItem(), mdtTtTestModelItem::addTestNodeUnitSetup(), mdtPortManager::addTransactionPending(), mdtApplication::addTranslationsDirectory(), mdtClUnitVehicleType::addUnitVehicleTypeAssignments(), mdtPartitionAttributes::availablePartitions(), mdtSerialPort::baudRate(), mdtTtBase::beginTransaction(), mdtUsbPort::cancelControlTransfer(), mdtUsbPort::cancelMessageInTransfer(), mdtUsbPort::cancelReadTransfer(), mdtUsbPort::cancelWriteTransfer(), mdtApplication::changeLanguage(), mdtTtDatabaseSchema::checkSchema(), mdtFrameCodecAscii::clean(), mdtUsbPort::clearReadEndpointHalt(), mdtUsbPort::clearWriteEndpointHalt(), mdtTtBase::commitTransaction(), mdtClLink::connectByContactName(), mdtDeviceModbus::connectToDevice(), mdtUsbPort::controlTransferCallback(), mdtDataTableManager::copyTable(), mdtSqlDatabaseManager::createDatabaseSqlite(), mdtSqlDatabaseManager::createTable(), mdtTtTestConnectionCable::createTestCable(), mdtSqlForm::currentData(), mdtSqlForm::currentRow(), mdtSqlForm::data(), mdtSerialPort::dataBits(), mdtFrameCodecK8055::decode(), mdtFrameCodecModbus::decode(), mdtFrameCodecScpiU3606A::decodeConfigure(), mdtFrameCodecScpi::decodeError(), mdtFrameCodecScpi::decodeFunctionParameters(), mdtFrameCodecScpi::decodeIEEEblock(), mdtFrameCodecScpi::decodeScpiVersion(), mdtFrameCodecScpi::decodeSingleValueDouble(), mdtDeviceModbusWago::detectIos(), mdtSqlDataValidator::displayError(), mdtSqlDataValidator::displayWarning(), mdtClArticle::editComponent(), mdtTtTestNodeUnit::editNodeUnit(), mdtFrameCodecModbus::encodeReadCoils(), mdtFrameCodecModbus::encodeReadDiscreteInputs(), mdtFrameCodecModbus::encodeReadHoldingRegisters(), mdtFrameCodecModbus::encodeReadInputRegisters(), mdtFrameCodecModbus::encodeWriteMultipleCoils(), mdtFrameCodecModbus::encodeWriteMultipleRegisters(), mdtUsbDeviceDescriptor::fetchAttributes(), mdtSerialPort::flowCtlRtsCtsOn(), mdtSerialPort::flowCtlXonXoffOn(), mdtUsbPortManager::fromThreadControlResponseReaden(), mdtUsbtmcPortManager::fromThreadNewFrameReaden(), mdtModbusTcpPortManager::fromThreadNewFrameReaden(), mdtPortManager::fromThreadNewFrameReaden(), mdtTtTestModel::generateTestNodeUnitSetup(), mdtTtTestModelItem::generateTestNodeUnitSetup(), mdtDevice::getAnalogInputValue(), mdtDevice::getAnalogInputValueAt(), mdtDevice::getAnalogOutputValue(), mdtDevice::getAnalogOutputValueAt(), mdtTtTestNode::getChannelTestConnectionIdList(), mdtClArticle::getConnectionData(), mdtClUnit::getConnectionData(), mdtClArticle::getConnectionDataListFromConnectionIdList(), mdtClArticle::getConnectorData(), mdtClUnit::getConnectorData(), mdtSerialPort::getCtlStates(), mdtTtTestNodeUnit::getData(), mdtTtBase::getData(), mdtDevice::getDigitalInputValue(), mdtDevice::getDigitalInputValueAt(), mdtDevice::getDigitalOutputValue(), mdtDevice::getDigitalOutputValueAt(), mdtFieldMapField::getFieldName(), mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtTtTestNode::getIdListOfUnitConnectionsPartOfUnit(), mdtTtTestNode::getIdListOfUnitIdForUnitConnectionIdList(), mdtClLink::getLinkData(), mdtTtTestConnectionCable::getLinkData(), mdtTtTestModel::getListOfTestItemIdListByTestId(), mdtTtTestModel::getListOfUnusedNodeUnitIdListByTestId(), mdtTtTestModel::getListOfUsedNodeIdListByTestId(), mdtPortThreadHelper::getNewFrameRead(), mdtPortManager::getNewTransaction(), mdtTtTestModel::getNextSequenceNumber(), mdtModbusTcpPortManager::getRegisterValues(), mdtTtTestModelItem::getTestNodeUnitSetupIdList(), mdtTtTestModel::getTestNodeUnitSetupIdList(), mdtTtTestConnectionCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector(), mdtTtTestConnectionCable::getToUnitConnectionLinkedUnitConnectorIdList(), mdtTtTestConnectionCable::getToUnitConnectorRelatedUnitConnectionIdList(), mdtClUnit::getUnitConnectorIdBasedOnArticleConnectorId(), mdtTtTestNodeUnit::getUnitData(), mdtTtTestModelItem::getUsedNodeUnitIdList(), mdtPortThreadHelper::handleCommonReadErrors(), mdtPortThreadHelper::handleCommonWriteErrors(), mdtDeviceScpi::handleDeviceError(), mdtUsbPort::handleUsbEvents(), mdtTtDatabaseSchema::importDatabase(), mdtDataTableManager::importFromCsvFile(), mdtUsbPort::initMessageInTransfer(), mdtUsbPort::initReadTransfer(), mdtUsbPort::initWriteTransfer(), mdtUicNumber::isValid(), mdtDeviceModbusWago::isWago750(), mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), mdtUicNumber::loadUsagesDb(), mdtPortManager::lockPortMutex(), mdtDeviceScpi::logDeviceError(), mdtClArticleComponentDialog::mdtClArticleComponentDialog(), mdtUsbPort::mdtUsbPort(), mdtUsbPort::messageInTransferCallback(), mdtSqlDatabaseManager::openDatabaseSqlite(), mdtPortLock::openLocked(), mdtSerialPort::parity(), mdtPort::read(), mdtSerialPort::read(), mdtPortThreadHelperPort::readFromPort(), mdtCsvFile::readLine(), mdtCsvFile::readLines(), mdtUsbPort::readTransferCallback(), mdtUsbPortThread::readUntilShortPacketReceived(), mdtPortThread::reconnect(), mdtClArticle::removeComponents(), mdtClUnit::removeComponents(), mdtClArticle::removeConnections(), mdtClArticle::removeConnectorsConnections(), mdtTtBase::removeData(), mdtFrameCodecAscii::removeEofSeq(), mdtTtTestModel::removeTestItem(), mdtTtTestModelItem::removeTestNodeUnitSetup(), mdtTtTestModelItem::removeTestNodeUnitSetupsForTestItemId(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), mdtSerialPort::resumeTransmission(), mdtTtBase::rollbackTransaction(), mdtSqlForm::rowCount(), mdtUsbPortManager::scan(), mdtSqlForm::select(), mdtDevice::setAnalogOutputValue(), mdtDevice::setAnalogOutputValueAt(), mdtAbstractPortSetupDialog::setApplyButtonEnabled(), mdtSerialPort::setBaudRate(), mdtAbstractPortSetupDialog::setCancelButtonEnabled(), mdtClArticleConnectorData::setConnectionData(), mdtClUnitConnectorData::setConnectionData(), mdtClConnectorData::setContactData(), mdtDataTableManager::setCsvFormat(), mdtSqlForm::setCurrentData(), mdtSqlForm::setCurrentRecord(), mdtSerialPort::setDataBits(), mdtDataTableManager::setDataSetDirectory(), mdtDevice::setDigitalOutputValue(), mdtDevice::setDigitalOutputValueAt(), mdtSerialPort::setDtr(), mdtSerialPort::setFlowCtlRtsCts(), mdtSerialPort::setFlowCtlXonXoff(), mdtSqlDatabaseManager::setForeignKeysEnabled(), mdtSqlForm::setMainTable(), mdtSqlForm::setMainTableFilter(), mdtUicNumber::setNumber(), mdtAbstractPortSetupDialog::setOkButtonEnabled(), mdtSerialPort::setParity(), mdtPartitionAttributes::setPath(), mdtAnalogIo::setRange(), mdtModbusTcpPortManager::setRegisterValues(), mdtSerialPort::setStopBits(), mdtSqlSchemaTable::setupFromTable(), mdtClUnitEditor::setWorkingOnVehicleTypeIdList(), mdtClLink::sqlForConnectableUnitConnectorsSelection(), mdtSqlSchemaTable::sqlForCreateTable(), mdtPortThread::stop(), mdtSerialPort::stopBits(), mdtUsbPort::submitControlQuery(), mdtSerialPort::suspendTransmission(), mdtClUnit::toUnitRelatedArticleConnectionCount(), mdtSqlSchemaTable::updateForeignKeyReferingTable(), mdtTtBase::updateRecord(), mdtSerialPort::waitEventCtl(), mdtPort::waitEventWriteReady(), mdtSerialPort::waitEventWriteReady(), mdtPort::waitForReadyRead(), mdtSerialPort::waitForReadyRead(), mdtUsbPortThread::waitOnControlTransferPossible(), mdtPortManager::waitTransactionDone(), mdtPort::write(), mdtSerialPort::write(), mdtCsvFile::writeLine(), mdtPortThreadHelperPort::writeToPort(), and mdtUsbPort::writeTransferCallback().
int mdtError::fileLine () const
Error source line.
Definition at line 197 of file mdtError.cpp.
Referenced by mdtErrorOut::addError(), and setSource().
QString mdtError::fileName () const
Error source file (name only)
Definition at line 192 of file mdtError.cpp.
Referenced by mdtErrorOut::addError().
QString mdtError::functionName () const
Error source function.
Definition at line 187 of file mdtError.cpp.
Referenced by mdtErrorOut::addError(), and setSource().
QString mdtError::informativeText () const
Get informative text.
Definition at line 182 of file mdtError.cpp.
Referenced by mdtSqlDatabaseManager::createDatabaseSqlite().
mdtError::level_t mdtError::level () const
Error level level_t.
Definition at line 128 of file mdtError.cpp.
Referenced by mdtErrorOut::addError(), mdtError(), and setError().
QMessageBox::Icon mdtError::levelIcon () const
Map the level to a QMessageBox Icon.
Definition at line 133 of file mdtError.cpp.
References Error, Info, NoError, and Warning.
Referenced by mdtSqlDatabaseManager::createDatabaseSqlite(), and mdtSqlForm::displayLastError().
int mdtError::number () const
Error number.
Deprecated:
If no good idea falls in for the usage of number , this method should become obselete .
Definition at line 118 of file mdtError.cpp.
Referenced by mdtErrorOut::addError(), mdtError(), and setSystemError().
void mdtError::setError (const QString & text, level_t level)
Set error.
Will also clear current error .
Definition at line 58 of file mdtError.cpp.
References clear(), level(), and text().
Referenced by mdtSqlRecord::addAllFields(), mdtTtTestConnectionCable::addCable(), mdtSqlForm::addChildTable(), mdtClArticle::addComponent(), mdtClUnit::addComponent(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtSqlRecord::addField(), mdtDataTableManager::addFieldMapping(), mdtSqlSchemaTable::addFieldToForeignKey(), mdtSqlSchemaTable::addFieldToIndex(), mdtClDirectLink::addLink(), mdtTtTestConnectionCable::addLink(), mdtTtBase::addRecord(), mdtSqlForm::addRelation(), mdtTtTestModel::addTestItem(), mdtTtTestModelItem::addTestNodeUnitSetup(), mdtClUnitVehicleType::addUnitVehicleTypeAssignments(), mdtTtBase::beginTransaction(), mdtTtDatabaseSchema::checkSchema(), mdtTtBase::commitTransaction(), mdtClLink::connectByContactName(), mdtDeviceModbus::connectToDevice(), mdtDataTableManager::copyTable(), mdtSqlDatabaseManager::createDatabaseSqlite(), mdtSqlDatabaseManager::createTable(), mdtTtTestConnectionCable::createTestCable(), mdtSqlForm::currentData(), mdtSqlForm::currentRow(), mdtSqlForm::data(), mdtClArticle::editComponent(), mdtTtTestNodeUnit::editNodeUnit(), mdtTtTestModel::generateTestNodeUnitSetup(), mdtTtTestModelItem::generateTestNodeUnitSetup(), mdtDevice::getAnalogInputValueAt(), mdtDevice::getAnalogOutputValueAt(), mdtTtTestNode::getChannelTestConnectionIdList(), mdtClArticle::getConnectionData(), mdtClUnit::getConnectionData(), mdtClArticle::getConnectionDataListFromConnectionIdList(), mdtClArticle::getConnectorData(), mdtClUnit::getConnectorData(), mdtTtTestNodeUnit::getData(), mdtTtBase::getData(), mdtDevice::getDigitalInputValueAt(), mdtDevice::getDigitalOutputValueAt(), mdtTtTestNode::getIdListOfUnitConnectionsPartOfUnit(), mdtTtTestNode::getIdListOfUnitIdForUnitConnectionIdList(), mdtClLink::getLinkData(), mdtTtTestConnectionCable::getLinkData(), mdtTtTestModel::getListOfTestItemIdListByTestId(), mdtTtTestModel::getListOfUnusedNodeUnitIdListByTestId(), mdtTtTestModel::getListOfUsedNodeIdListByTestId(), mdtTtTestModel::getNextSequenceNumber(), mdtTtTestModelItem::getTestNodeUnitSetupIdList(), mdtTtTestModel::getTestNodeUnitSetupIdList(), mdtTtTestConnectionCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector(), mdtTtTestConnectionCable::getToUnitConnectionLinkedUnitConnectorIdList(), mdtTtTestConnectionCable::getToUnitConnectorRelatedUnitConnectionIdList(), mdtClUnit::getUnitConnectorIdBasedOnArticleConnectorId(), mdtTtTestNodeUnit::getUnitData(), mdtTtTestModelItem::getUsedNodeUnitIdList(), mdtTtDatabaseSchema::importDatabase(), mdtDataTableManager::importFromCsvFile(), mdtSqlDatabaseManager::openDatabaseSqlite(), mdtClArticle::removeComponents(), mdtClUnit::removeComponents(), mdtClArticle::removeConnections(), mdtClArticle::removeConnectorsConnections(), mdtTtBase::removeData(), mdtTtTestModel::removeTestItem(), mdtTtTestModelItem::removeTestNodeUnitSetup(), mdtTtTestModelItem::removeTestNodeUnitSetupsForTestItemId(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), mdtTtBase::rollbackTransaction(), mdtSqlForm::rowCount(), mdtSqlForm::select(), mdtDevice::setAnalogOutputValueAt(), mdtClArticleConnectorData::setConnectionData(), mdtClUnitConnectorData::setConnectionData(), mdtClConnectorData::setContactData(), mdtDataTableManager::setCsvFormat(), mdtSqlForm::setCurrentData(), mdtSqlForm::setCurrentRecord(), mdtDataTableManager::setDataSetDirectory(), mdtDevice::setDigitalOutputValueAt(), mdtSqlDatabaseManager::setForeignKeysEnabled(), mdtSqlForm::setMainTable(), mdtSqlForm::setMainTableFilter(), mdtSqlSchemaTable::setupFromTable(), mdtClUnitEditor::setWorkingOnVehicleTypeIdList(), mdtClLink::sqlForConnectableUnitConnectorsSelection(), mdtSqlSchemaTable::sqlForCreateTable(), mdtClUnit::toUnitRelatedArticleConnectionCount(), mdtSqlSchemaTable::updateForeignKeyReferingTable(), and mdtTtBase::updateRecord().
void mdtError::setInformativeText (const QString & text)
Set informative text.
Definition at line 177 of file mdtError.cpp.
References text().
Referenced by mdtSqlDatabaseManager::createDatabaseSqlite(), and mdtSqlDatabaseManager::openDatabaseSqlite().
void mdtError::setSource (const QString & filePath, int fileLine, const QString & className, const QString & functionName)
Add system error (for Windows API)
When using Windows API, the standard mechanism is GetLastError() and FormatMessage(). Calling this method will do this internally.
Add the source of error
It's possible to use the helper macro MDT_ERROR_SET_SRC()
Definition at line 101 of file mdtError.cpp.
References fileLine(), and functionName().
void mdtError::setSystemError (int number, const QString & text)
Add system returned error (for example, errno)
Definition at line 82 of file mdtError.cpp.
References number(), and text().
Referenced by mdtSqlRecord::addAllFields(), mdtTtTestConnectionCable::addCable(), mdtSqlForm::addChildTable(), mdtClArticle::addComponent(), mdtClUnit::addComponent(), mdtClArticle::addConnector(), mdtClUnit::addConnector(), mdtSqlRecord::addField(), mdtTtTestConnectionCable::addLink(), mdtTtBase::addRecord(), mdtTtTestModel::addTestItem(), mdtTtTestModelItem::addTestNodeUnitSetup(), mdtClUnitVehicleType::addUnitVehicleTypeAssignments(), mdtPartitionAttributes::availablePartitions(), mdtSerialPort::baudRate(), mdtTtBase::beginTransaction(), mdtUsbPort::cancelControlTransfer(), mdtUsbPort::cancelMessageInTransfer(), mdtUsbPort::cancelReadTransfer(), mdtUsbPort::cancelWriteTransfer(), mdtUsbPort::clearReadEndpointHalt(), mdtUsbPort::clearWriteEndpointHalt(), mdtTtBase::commitTransaction(), mdtDataTableManager::copyTable(), mdtSqlDatabaseManager::createDatabaseSqlite(), mdtSqlDatabaseManager::createTable(), mdtTtTestConnectionCable::createTestCable(), mdtSerialPort::dataBits(), mdtAbstractSqlWidget::displayDatabaseError(), mdtSqlDataValidator::displayError(), mdtSqlDataValidator::displayWarning(), mdtClArticle::editComponent(), mdtSerialPort::flowCtlRtsCtsOn(), mdtSerialPort::flowCtlXonXoffOn(), mdtTtTestModel::generateTestNodeUnitSetup(), mdtTtTestNode::getChannelTestConnectionIdList(), mdtClArticle::getConnectionDataListFromConnectionIdList(), mdtSerialPort::getCtlStates(), mdtTtBase::getData(), mdtTtTestNode::getIdListOfUnitConnectionsPartOfUnit(), mdtTtTestNode::getIdListOfUnitIdForUnitConnectionIdList(), mdtTtTestModel::getListOfTestItemIdListByTestId(), mdtTtTestModel::getListOfUnusedNodeUnitIdListByTestId(), mdtTtTestModel::getListOfUsedNodeIdListByTestId(), mdtTtTestModel::getNextSequenceNumber(), mdtTtTestModelItem::getTestNodeUnitSetupIdList(), mdtTtTestModel::getTestNodeUnitSetupIdList(), mdtTtTestConnectionCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector(), mdtTtTestConnectionCable::getToUnitConnectionLinkedUnitConnectorIdList(), mdtTtTestConnectionCable::getToUnitConnectorRelatedUnitConnectionIdList(), mdtTtTestModelItem::getUsedNodeUnitIdList(), mdtUsbPort::handleUsbEvents(), mdtUsbPort::initMessageInTransfer(), mdtUsbPort::initReadTransfer(), mdtUsbPort::initWriteTransfer(), mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), mdtUicNumber::loadUsagesDb(), mdtClArticleComponentDialog::mdtClArticleComponentDialog(), mdtUsbPort::mdtUsbPort(), mdtSqlDatabaseManager::openDatabaseSqlite(), mdtPortLock::openLocked(), mdtSerialPort::parity(), mdtPort::read(), mdtSerialPort::read(), mdtClArticle::removeComponents(), mdtClUnit::removeComponents(), mdtClArticle::removeConnections(), mdtClArticle::removeConnectorsConnections(), mdtTtBase::removeData(), mdtTtTestModel::removeTestItem(), mdtTtTestModelItem::removeTestNodeUnitSetup(), mdtTtTestModelItem::removeTestNodeUnitSetupsForTestItemId(), mdtClUnitVehicleType::removeUnitVehicleAssignments(), mdtClLink::removeVehicleTypeLinks(), mdtSerialPort::resumeTransmission(), mdtTtBase::rollbackTransaction(), mdtSqlForm::select(), mdtSerialPort::setBaudRate(), mdtSerialPort::setDataBits(), mdtSerialPort::setDtr(), mdtSerialPort::setFlowCtlRtsCts(), mdtSerialPort::setFlowCtlXonXoff(), mdtSqlDatabaseManager::setForeignKeysEnabled(), mdtSqlForm::setMainTable(), mdtSerialPort::setParity(), mdtPartitionAttributes::setPath(), mdtSerialPort::setStopBits(), mdtFileCopier::startCopy(), mdtPortThread::stop(), mdtSerialPort::stopBits(), mdtUsbPort::submitControlQuery(), mdtSerialPort::suspendTransmission(), mdtClUnit::toUnitRelatedArticleConnectionCount(), mdtTtBase::updateRecord(), mdtSerialPort::waitEventCtl(), mdtPort::waitEventWriteReady(), mdtSerialPort::waitEventWriteReady(), mdtPort::waitForReadyRead(), mdtSerialPort::waitForReadyRead(), mdtPort::write(), and mdtSerialPort::write().
QString mdtError::systemErrorString (QObject * obj = 0) const
Error number and text from system, if available.
If obj is set, translation is used. (We not want to use the static QObject::tr()).
Definition at line 158 of file mdtError.cpp.
Referenced by mdtSqlDatabaseManager::createDatabaseSqlite().
int mdtError::systemNumber () const
Error number returned from system if available.
Definition at line 148 of file mdtError.cpp.
Referenced by mdtErrorOut::addError().
QString mdtError::systemText () const
Error text returned from system, if available.
Definition at line 153 of file mdtError.cpp.
Referenced by mdtErrorOut::addError(), mdtSqlForm::displayLastError(), mdtClArticleLinkDialog::mdtClArticleLinkDialog(), and mdtTtTestLinkDialog::mdtTtTestLinkDialog().
QString mdtError::text () const
Error text.
Definition at line 123 of file mdtError.cpp.
Referenced by mdtErrorOut::addError(), mdtDataTableManager::copyTable(), mdtSqlDatabaseManager::createDatabaseSqlite(), mdtSqlForm::displayLastError(), mdtClArticleLinkDialog::mdtClArticleLinkDialog(), mdtError(), mdtTtTestLinkDialog::mdtTtTestLinkDialog(), setError(), setInformativeText(), setSystemError(), and updateText().
void mdtError::updateText (const QString & text)
Update error text.
Will set error text, but does not clear error .
Definition at line 65 of file mdtError.cpp.
References text().
Referenced by mdtDataTableManager::copyTable().
The documentation for this class was generated from the following files:
src/mdtutils/mdtError.h
src/mdtutils/mdtError.cpp