Multi diag tools: mdtUsbtmcControlTransfer Class Reference
mdtUsbtmcControlTransfer Class Reference
USBTMC control transfer.
#include <mdtUsbtmcControlTransfer.h>
Public Types
enum USBTMCbRequest : uint8_t {
USBTMCbRequest::None = 0, USBTMCbRequest::INITIATE_ABORT_BULK_OUT = 1, USBTMCbRequest::CHECK_ABORT_BULK_OUT_STATUS = 2, USBTMCbRequest::INITIATE_ABORT_BULK_IN = 3,
USBTMCbRequest::CHECK_ABORT_BULK_IN_STATUS = 4, USBTMCbRequest::INITIATE_CLEAR = 5, USBTMCbRequest::CHECK_CLEAR_STATUS = 6, USBTMCbRequest::GET_CAPABILITIES = 7,
USBTMCbRequest::INDICATOR_PULSE = 64
}
USBTMC bRequest.
enum USBTMCstatus : uint8_t {
USBTMCstatus::STATUS_SUCCESS = 0x01, USBTMCstatus::STATUS_PENDING = 0x02, USBTMCstatus::STATUS_FAILED = 0x80, USBTMCstatus::STATUS_TRANSFER_NOT_IN_PROGRESS = 0x81,
USBTMCstatus::STATUS_SPLIT_NOT_IN_PROGRESS = 0x82, USBTMCstatus::STATUS_SPLIT_IN_PROGRESS = 0x83, USBTMCstatus::STATUS_INTERRUPT_IN_BUSY = 0x20
}
USBTMC_status values.
Public Types inherited from mdtUsbControlTransfer
enum RequestRecipient_t : uint8_t { RequestRecipient_t::Device = 0, RequestRecipient_t::Interface = 1, RequestRecipient_t::Endpoint = 2, RequestRecipient_t::Other = 3 }
Request recipient.
enum StandardRequestCode_t : uint8_t { StandardRequestCode_t::GET_STATUS = 0, StandardRequestCode_t::CLEAR_FEATURE = 1 }
Standard Request Codes.
enum DescriptorType_t : uint8_t {
DescriptorType_t::DEVICE = 1, DescriptorType_t::CONFIGURATION = 2, DescriptorType_t::STRING = 3, DescriptorType_t::INTERFACE = 4,
DescriptorType_t::ENDPOINT = 5
}
Descriptor Types.
enum StandardFeatureSelector_t : uint16_t { StandardFeatureSelector_t::DEVICE_REMOTE_WAKEUP = 1, StandardFeatureSelector_t::ENDPOINT_HALT = 0, StandardFeatureSelector_t::TEST_MODE = 2 }
Standard Feature Selectors.
Public Member Functions
mdtUsbtmcControlTransfer (mdtUsbtmcTransferHandler &th, libusb_device_handle *dev_handle, int bufferSize=1024)
Constructor.
mdtUsbtmcControlTransfer (const mdtUsbtmcControlTransfer &rhs)=delete
mdtUsbtmcControlTransfer & operator= (const mdtUsbtmcControlTransfer &rhs)=delete
void setupClearEndpointHalt (uint8_t endpointNumber, unsigned int timeout)
Setup a clear endpoint halt transfer.
bool isClearEndpointHaltRequest (uint8_t endpointNumber) const
Check if this is a CLEAR_FEATURE request with wValue = ENDPOINT_HALT for given endpoint.
void setupInitiateAbortBulkOut (uint8_t bTag, uint8_t endpointNumber, unsigned int timeout)
Setup a INITIATE_ABORT_BULK_OUT transfer.
void setupCheckAbortBulkOutStatus (uint8_t endpointNumber, unsigned int timeout)
Setup a CHECK_ABORT_BULK_OUT_STATUS transfer.
void setupInitiateAbortBulkIn (uint8_t bTag, uint8_t endpointNumber, unsigned int timeout)
Setup a INITIATE_ABORT_BULK_IN transfer.
void setupCheckAbortBulkInStatus (uint8_t endpointNumber, unsigned int timeout)
Setup a CHECK_ABORT_BULK_IN_STATUS transfer.
void setupInitiateClear (uint8_t interfaceNumber, unsigned int timeout)
Setup a INITIATE_CLEAR transfer.
void setupCheckClearStatus (uint8_t interfaceNumber, unsigned int timeout)
Setup a CHECK_CLEAR_STATUS transfer.
void setupGetCapabilities (uint8_t interfaceNumber, unsigned int timeout)
Setup a GET_CAPABILITIES transfer.
uint16_t bcdUSBTMC () const
Get bcdUSBTMC.
bool interfaceAcceptsIndicatorPulse () const
Check if interface accepts INDICATOR_PULSE.
bool interfaceIsTalkOnly () const
Check if interface is talk-only.
bool interfaceIsListenOnly () const
Check if interface is listen-only.
bool deviceSupportsTermChar () const
Check if device supports TermChar.
uint16_t bcdUSB488 () const
Get bcdUSB488.
bool interfaceIsUSB488 () const
Check if interface is a 488.2 USB488 one.
bool interfaceAcceptsRenControl () const
Check if interface accepts REN_CONTROL.
bool interfaceAcceptsTrigger () const
Check if interface accepts MsgID = TRIGGER.
bool deviceSupportsAllMandatoryScpiCommands () const
Check if device supports all mandatory SCPI commands.
bool deviceIsSR1Capable () const
Check if device is SR1 capable.
bool deviceIsRL1Capable () const
Check if device is RL1 capable.
bool deviceIsDT1Capable () const
Check if device is DT1 capable.
void setupIndicatorPulse (uint8_t interfaceNumber, unsigned int timeout)
Setup a INDICATOR_PULSE transfer.
USBTMCbRequest usbtmcRequest () const
Get USBTMC bRequest.
QString usbtmcRequestText () const
Get USBTMC bRequest text.
USBTMCstatus usbtmcStatus () const
Get USBTMC_status.
QString usbtmcStatusText () const
Get USBTMC_status text.
mdtUsbtmcTransferHandler & transferHandler ()
Get transfer handler.
Public Member Functions inherited from mdtUsbControlTransfer
mdtUsbControlTransfer (libusb_device_handle *dev_handle, int bufferSize=1024)
Constructor.
mdtUsbControlTransfer (const mdtUsbControlTransfer &rhs)=delete
mdtUsbControlTransfer & operator= (const mdtUsbControlTransfer &rhs)=delete
void setByteValue (unsigned int offset, uint8_t value)
Set value at offset.
uint8_t byteValue (unsigned int offset) const
Get value at offset.
void setWordValue (unsigned int offset, uint16_t value)
Set value at offset.
uint16_t wordValue (unsigned int offset) const
Get value at offset.
uint8_t bmRequestType () const
Get bmRequestType part.
uint8_t bRequest () const
Get bRequest part.
uint16_t wValue () const
Get wValue.
uint16_t wIndex () const
Get wIndex.
uint16_t wLength () const
Get wLength.
void setupClearFeature (libusb_transfer_cb_fn callback, RequestRecipient_t recipient, StandardFeatureSelector_t feature, uint16_t recipientNumber, unsigned int timeout)
Setup a Clear feature transfer.
Public Member Functions inherited from mdtUsbTransfer
mdtUsbTransfer (libusb_device_handle *dev_handle, int isoPacketsCount=0)
Constructor.
~mdtUsbTransfer ()
Destructor.
mdtUsbTransfer (const mdtUsbTransfer &rhs)=delete
mdtUsbTransfer & operator= (const mdtUsbTransfer &rhs)=delete
bool allocOk () const
Check that allocation not failed.
uint8_t flags () const
Get transfer flags.
bool submit (bool sync=false)
Submit transfer.
bool cancel (bool sync=false)
Cancel transfer.
libusb_transfer_status status () const
Get transfer status.
int actualLength () const
Get actual length.
unsigned int timeout () const
Get timeout that was given to transfer.
mdtError lastError () const
Get last error.
bool isSync () const
Check if transfer is a synchronous transfer.
int * completedPointer ()
Access completed flag.
void setCompleted ()
Set completed flag.
bool isCompleted () const
Check completed flag.
Additional Inherited Members
Protected Member Functions inherited from mdtUsbControlTransfer
void fillTransfer (libusb_transfer_cb_fn callback, uint8_t bmRequestType, uint8_t bRequest, uint16_t wValue, uint16_t wIndex, uint16_t wLength, unsigned int timeout)
Fill transfer.
void fillTransfer (libusb_transfer_cb_fn callback, uint8_t bmRequestType, uint8_t bRequest, uint16_t wValue, uint16_t wIndex, const std::vector< unsigned char > &data, unsigned int timeout)
Fill transfer.
Protected Member Functions inherited from mdtUsbTransfer
libusb_device_handle * deviceHandle ()
Get device handle.
libusb_transfer * transfer ()
Access libusb transfer.
Detailed Description
USBTMC control transfer.
Definition at line 33 of file mdtUsbtmcControlTransfer.h.
Member Enumeration Documentation
enum mdtUsbtmcControlTransfer::USBTMCbRequest : uint8_t strong
USBTMC bRequest.
See Table 15 in USBTMC 1.0 specifications, section 4.2.1.
Enumerator
None
Marked as reserved in specification, but...
INITIATE_ABORT_BULK_OUT
Abort a Bulk-OUT transfer.
CHECK_ABORT_BULK_OUT_STATUS
Returns the status of the previously sent INITIATE_ABORT_BULK_OUT request.
INITIATE_ABORT_BULK_IN
Abort a Bulk-IN transfer.
CHECK_ABORT_BULK_IN_STATUS
Returns the status of the previously sent INITIATE_ABORT_BULK_IN request.
INITIATE_CLEAR
Clear bulk-OUT and bulk-IN transfers.
CHECK_CLEAR_STATUS
Returns the status of previously sent INITIATE_CLEAR request.
GET_CAPABILITIES
Returns attributes and capabilities of the USBTMC interface.
INDICATOR_PULSE
A mechanism to turn on an activity indicator for identification purposes.
Definition at line 41 of file mdtUsbtmcControlTransfer.h.
enum mdtUsbtmcControlTransfer::USBTMCstatus : uint8_t strong
USBTMC_status values.
See Table 16 in USBTMC 1.0 specifications, section 4.2.1. For USB488 specific status, see USBTMC-USB488 1.0 specification, section 4.3
Enumerator
STATUS_SUCCESS
Success
STATUS_PENDING
Valid after a USBTMC CHECK_STATUS. See USBTMC 1.0, section 4.2.1.1
STATUS_FAILED
Failure, unspecified reason
STATUS_TRANSFER_NOT_IN_PROGRESS
Valid after a INITIATE_ABORT_BULK_OUT or INITIATE_ABORT_BULK_IN request and specified transfer abort is not in progress
STATUS_SPLIT_NOT_IN_PROGRESS
Valid if device received a CHECK_STATUS request and device is not processing INITIATE request
STATUS_SPLIT_IN_PROGRESS
Valid if device received a new Class specific request and device is still processing INITIATE
STATUS_INTERRUPT_IN_BUSY
USB488: Valid if device received READ_STATUS_BYTE request.
Definition at line 59 of file mdtUsbtmcControlTransfer.h.
Constructor & Destructor Documentation
mdtUsbtmcControlTransfer::mdtUsbtmcControlTransfer (mdtUsbtmcTransferHandler & th, libusb_device_handle * dev_handle, int bufferSize = 1024)
Constructor.
Todo:
Fix a realistic bufferSize
Precondition
bufferSize must be >= 8.
Definition at line 26 of file mdtUsbtmcControlTransfer.cpp.
mdtUsbtmcControlTransfer::mdtUsbtmcControlTransfer (const mdtUsbtmcControlTransfer & rhs) delete
Member Function Documentation
uint16_t mdtUsbtmcControlTransfer::bcdUSB488 () const inline
Get bcdUSB488.
Valid only for GET_CAPABILITIES response.
BCD version number of the relevant USB488 specification for this USB488 interface. Format is Binary-Coded-Decimal. For example, 0x0210 represents version 2.10.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 236 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::wordValue().
uint16_t mdtUsbtmcControlTransfer::bcdUSBTMC () const inline
Get bcdUSBTMC.
Valid only for GET_CAPABILITIES response.
BCD version number of the relevant USBTMC specification for this USBTMC interface. Format is Binary-Coded-Decimal. For example, 0x0210 represents version 2.10.
See USBTMC specifications, section 4.2.1.8
Definition at line 177 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::wordValue().
bool mdtUsbtmcControlTransfer::deviceIsDT1Capable () const inline
Check if device is DT1 capable.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 320 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::deviceIsRL1Capable () const inline
Check if device is RL1 capable.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 308 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::deviceIsSR1Capable () const inline
Check if device is SR1 capable.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 296 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::deviceSupportsAllMandatoryScpiCommands () const inline
Check if device supports all mandatory SCPI commands.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 284 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::deviceSupportsTermChar () const inline
Check if device supports TermChar.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8
Definition at line 221 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::interfaceAcceptsIndicatorPulse () const inline
Check if interface accepts INDICATOR_PULSE.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8
Definition at line 188 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::interfaceAcceptsRenControl () const inline
Check if interface accepts REN_CONTROL.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 260 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::interfaceAcceptsTrigger () const inline
Check if interface accepts MsgID = TRIGGER.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 272 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::interfaceIsListenOnly () const inline
Check if interface is listen-only.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8
Definition at line 210 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::interfaceIsTalkOnly () const inline
Check if interface is talk-only.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8
Definition at line 199 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::interfaceIsUSB488 () const inline
Check if interface is a 488.2 USB488 one.
Valid only for GET_CAPABILITIES response.
See USBTMC specifications, section 4.2.1.8 and USBTMC-USB488 specification, section 4.2.2
Definition at line 248 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
bool mdtUsbtmcControlTransfer::isClearEndpointHaltRequest (uint8_t endpointNumber) const inline
Check if this is a CLEAR_FEATURE request with wValue = ENDPOINT_HALT for given endpoint.
Definition at line 94 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::bmRequestType(), mdtUsbControlTransfer::bRequest(), mdtUsbControlTransfer::CLEAR_FEATURE, mdtUsbControlTransfer::Endpoint, mdtUsbControlTransfer::ENDPOINT_HALT, mdtUsbControlTransfer::wIndex(), and mdtUsbControlTransfer::wValue().
mdtUsbtmcControlTransfer& mdtUsbtmcControlTransfer::operator= (const mdtUsbtmcControlTransfer & rhs) delete
void mdtUsbtmcControlTransfer::setupCheckAbortBulkInStatus (uint8_t endpointNumber, unsigned int timeout)
Setup a CHECK_ABORT_BULK_IN_STATUS transfer.
See USBTMC specifications, section 4.2.1.5
Parameters
endpointNumber Endpoint number.
timeout timeout for the transfer in milliseconds.
Definition at line 61 of file mdtUsbtmcControlTransfer.cpp.
References CHECK_ABORT_BULK_IN_STATUS, mdtUsbtmcTransferHandler::controlTransferCallback(), and mdtUsbControlTransfer::fillTransfer().
void mdtUsbtmcControlTransfer::setupCheckAbortBulkOutStatus (uint8_t endpointNumber, unsigned int timeout)
Setup a CHECK_ABORT_BULK_OUT_STATUS transfer.
See USBTMC specifications, section 4.2.1.3
Parameters
endpointNumber Endpoint number.
timeout timeout for the transfer in milliseconds.
Definition at line 46 of file mdtUsbtmcControlTransfer.cpp.
References CHECK_ABORT_BULK_OUT_STATUS, mdtUsbtmcTransferHandler::controlTransferCallback(), and mdtUsbControlTransfer::fillTransfer().
void mdtUsbtmcControlTransfer::setupCheckClearStatus (uint8_t interfaceNumber, unsigned int timeout)
Setup a CHECK_CLEAR_STATUS transfer.
See USBTMC specifications, section 4.2.1.7
Parameters
interfaceNumber Interface number.
timeout timeout for the transfer in milliseconds.
Definition at line 75 of file mdtUsbtmcControlTransfer.cpp.
References CHECK_CLEAR_STATUS, mdtUsbtmcTransferHandler::controlTransferCallback(), and mdtUsbControlTransfer::fillTransfer().
void mdtUsbtmcControlTransfer::setupClearEndpointHalt (uint8_t endpointNumber, unsigned int timeout)
Setup a clear endpoint halt transfer.
See USBTMC specifications, section 4.1.1 (CLEAR_FEATURE request wValue = ENDPOINT_HALT)
Parameters
transferHandler This transferHandler will be passed to user_data in libusb_transfer.
endpointNumber Endpoint number.
timeout timeout for the transfer in milliseconds.
Definition at line 32 of file mdtUsbtmcControlTransfer.cpp.
References mdtUsbtmcTransferHandler::controlTransferCallback(), mdtUsbControlTransfer::Endpoint, mdtUsbControlTransfer::ENDPOINT_HALT, and mdtUsbControlTransfer::setupClearFeature().
Referenced by mdtUsbtmcTransferHandler::submitClearEndpointHalt().
void mdtUsbtmcControlTransfer::setupGetCapabilities (uint8_t interfaceNumber, unsigned int timeout)
Setup a GET_CAPABILITIES transfer.
See USBTMC specifications, section 4.2.1.8
Parameters
interfaceNumber Interface number.
timeout timeout for the transfer in milliseconds.
Definition at line 82 of file mdtUsbtmcControlTransfer.cpp.
References mdtUsbtmcTransferHandler::controlTransferCallback(), mdtUsbControlTransfer::fillTransfer(), and GET_CAPABILITIES.
void mdtUsbtmcControlTransfer::setupIndicatorPulse (uint8_t interfaceNumber, unsigned int timeout)
Setup a INDICATOR_PULSE transfer.
See USBTMC specifications, section 4.2.1.9
Parameters
interfaceNumber Interface number.
timeout timeout for the transfer in milliseconds.
Definition at line 89 of file mdtUsbtmcControlTransfer.cpp.
References mdtUsbtmcTransferHandler::controlTransferCallback(), mdtUsbControlTransfer::fillTransfer(), and INDICATOR_PULSE.
void mdtUsbtmcControlTransfer::setupInitiateAbortBulkIn (uint8_t bTag, uint8_t endpointNumber, unsigned int timeout)
Setup a INITIATE_ABORT_BULK_IN transfer.
See USBTMC specifications, section 4.2.1.4
Parameters
bTag bTag of the bulk out transfer to abort.
endpointNumber Endpoint number.
timeout timeout for the transfer in milliseconds.
Definition at line 53 of file mdtUsbtmcControlTransfer.cpp.
References mdtUsbtmcTransferHandler::controlTransferCallback(), mdtUsbControlTransfer::fillTransfer(), and INITIATE_ABORT_BULK_IN.
void mdtUsbtmcControlTransfer::setupInitiateAbortBulkOut (uint8_t bTag, uint8_t endpointNumber, unsigned int timeout)
Setup a INITIATE_ABORT_BULK_OUT transfer.
See USBTMC specifications, section 4.2.1.2
Parameters
bTag bTag of the bulk out transfer to abort.
endpointNumber Endpoint number.
timeout timeout for the transfer in milliseconds.
Definition at line 39 of file mdtUsbtmcControlTransfer.cpp.
References mdtUsbtmcTransferHandler::controlTransferCallback(), mdtUsbControlTransfer::fillTransfer(), and INITIATE_ABORT_BULK_OUT.
void mdtUsbtmcControlTransfer::setupInitiateClear (uint8_t interfaceNumber, unsigned int timeout)
Setup a INITIATE_CLEAR transfer.
See USBTMC specifications, section 4.2.1.6
Parameters
interfaceNumber Interface number.
timeout timeout for the transfer in milliseconds.
Definition at line 68 of file mdtUsbtmcControlTransfer.cpp.
References mdtUsbtmcTransferHandler::controlTransferCallback(), mdtUsbControlTransfer::fillTransfer(), and INITIATE_CLEAR.
mdtUsbtmcTransferHandler& mdtUsbtmcControlTransfer::transferHandler () inline
Get transfer handler.
Definition at line 365 of file mdtUsbtmcControlTransfer.h.
Referenced by mdtUsbtmcTransferHandler::controlTransferCallback().
USBTMCbRequest mdtUsbtmcControlTransfer::usbtmcRequest () const inline
Get USBTMC bRequest.
Is valid just after setupXY() was called, and after transfer is done, thanks to libusb wich does not overwrite it.
Definition at line 339 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
Referenced by mdtUsbtmcTransferHandler::handleControlTransferComplete(), and usbtmcRequestText().
QString mdtUsbtmcControlTransfer::usbtmcRequestText () const
Get USBTMC bRequest text.
Definition at line 96 of file mdtUsbtmcControlTransfer.cpp.
References CHECK_ABORT_BULK_IN_STATUS, CHECK_ABORT_BULK_OUT_STATUS, CHECK_CLEAR_STATUS, GET_CAPABILITIES, INDICATOR_PULSE, INITIATE_ABORT_BULK_IN, INITIATE_ABORT_BULK_OUT, INITIATE_CLEAR, None, and usbtmcRequest().
Referenced by mdtUsbtmcTransferHandler::handleControlTransferComplete().
USBTMCstatus mdtUsbtmcControlTransfer::usbtmcStatus () const inline
Get USBTMC_status.
Notes:
No check is made about actualLength(). It is the caller responsability to be shure that response contains expected data length.
Returned status is simply a cast from value that device returned. Don't forget a default section in your switch()
Definition at line 354 of file mdtUsbtmcControlTransfer.h.
References mdtUsbControlTransfer::byteValue().
Referenced by usbtmcStatusText().
QString mdtUsbtmcControlTransfer::usbtmcStatusText () const
Get USBTMC_status text.
Definition at line 139 of file mdtUsbtmcControlTransfer.cpp.
References STATUS_FAILED, STATUS_INTERRUPT_IN_BUSY, STATUS_PENDING, STATUS_SPLIT_IN_PROGRESS, STATUS_SPLIT_NOT_IN_PROGRESS, STATUS_SUCCESS, STATUS_TRANSFER_NOT_IN_PROGRESS, and usbtmcStatus().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbtmcControlTransfer.h
src/mdtport/mdtUsbtmcControlTransfer.cpp