Multi diag tools: mdtFieldMapItemDialog Class Reference
mdtFieldMapItemDialog Class Reference
A dialog to setup a field map item.
#include <mdtFieldMapItemDialog.h>
Public Slots
void accept ()
Public Member Functions
mdtFieldMapItemDialog (QWidget *parent=0)
Constructor.
~mdtFieldMapItemDialog ()
Destructor.
void setSourceFields (const QList< mdtFieldMapField > &fields)
Set source fields.
void setDestinationFields (const QList< mdtFieldMapField > &fields)
Set destination fields.
void setSourceData (const QString &data)
Set source data (used for preview)
void setMapItem (const mdtFieldMapItem &item)
Set map item.
mdtFieldMapItem mapItem () const
Get map item.
Additional Inherited Members
Public Attributes inherited from Ui_mdtFieldMapItemDialog
QVBoxLayout * verticalLayout_3
QHBoxLayout * horizontalLayout
QFormLayout * formLayout_3
QLabel * lbSourceField
QComboBox * cbSourceField
QLabel * lbSourceFieldNameLabel
QLabel * lbSourceFieldName
QLabel * lbSourceFieldIndexLabel
QLabel * lbSourceFieldIndex
QFormLayout * formLayout_4
QLabel * lbDestinationField
QComboBox * cbDestinationField
QLabel * lbDestinationFieldNameLabel
QLabel * lbDestinationFieldName
QLabel * lbDestinationFieldIndexLabel
QLabel * lbDestinationFieldIndex
QHBoxLayout * horizontalLayout_2
QGroupBox * gbSourceSplitting
QVBoxLayout * verticalLayout
QRadioButton * rbNoSourceSplit
QRadioButton * rbUseSplitting
QFormLayout * formLayout
QLabel * lbSourceStartOffset
QLabel * lbSourceSize
QSpinBox * sbSourceSize
QSpinBox * sbSourceStartOffset
QVBoxLayout * verticalLayout_2
QGroupBox * gbPreview
QFormLayout * formLayout_2
QLabel * lbSourceDataLabel
QLabel * lbSourceData
QLabel * lbDestinationDataLabel
QLabel * lbDestinationData
QSpacerItem * verticalSpacer
QDialogButtonBox * buttonBox
Detailed Description
A dialog to setup a field map item.
Definition at line 35 of file mdtFieldMapItemDialog.h.
Constructor & Destructor Documentation
mdtFieldMapItemDialog::mdtFieldMapItemDialog (QWidget * parent = 0)
Constructor.
Definition at line 29 of file mdtFieldMapItemDialog.cpp.
References Ui_mdtFieldMapItemDialog::cbDestinationField, Ui_mdtFieldMapItemDialog::cbSourceField, Ui_mdtFieldMapItemDialog::rbUseSplitting, Ui_mdtFieldMapItemDialog::sbSourceSize, Ui_mdtFieldMapItemDialog::sbSourceStartOffset, mdtFieldMapItem::setDataType(), setSourceData(), and Ui_mdtFieldMapItemDialog::setupUi().
mdtFieldMapItemDialog::~mdtFieldMapItemDialog ()
Destructor.
Definition at line 49 of file mdtFieldMapItemDialog.cpp.
Member Function Documentation
void mdtFieldMapItemDialog::accept () slot
Definition at line 109 of file mdtFieldMapItemDialog.cpp.
mdtFieldMapItem mdtFieldMapItemDialog::mapItem () const
Get map item.
Definition at line 104 of file mdtFieldMapItemDialog.cpp.
void mdtFieldMapItemDialog::setDestinationFields (const QList< mdtFieldMapField > & fields)
Set destination fields.
Parameters
fields List of available (possibly allready not used) fields. These fields will populate the destination fields combobox .
Precondition
fields must contain at least 1 item
Definition at line 73 of file mdtFieldMapItemDialog.cpp.
References Ui_mdtFieldMapItemDialog::cbDestinationField, mdtFieldMapField::displayText(), and mdtFieldMapField::name().
void mdtFieldMapItemDialog::setMapItem (const mdtFieldMapItem & item)
Set map item.
Definition at line 99 of file mdtFieldMapItemDialog.cpp.
void mdtFieldMapItemDialog::setSourceData (const QString & data)
Set source data (used for preview)
Definition at line 93 of file mdtFieldMapItemDialog.cpp.
References Ui_mdtFieldMapItemDialog::lbSourceData.
Referenced by mdtFieldMapItemDialog().
void mdtFieldMapItemDialog::setSourceFields (const QList< mdtFieldMapField > & fields)
Set source fields.
Precondition
fields must contain at least 1 item
Definition at line 53 of file mdtFieldMapItemDialog.cpp.
References Ui_mdtFieldMapItemDialog::cbSourceField, mdtFieldMapField::displayText(), and mdtFieldMapField::name().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtFieldMapItemDialog.h
src/mdtutilsgui/mdtFieldMapItemDialog.cpp