Multi diag tools: mdtSqlFormOld Class Reference
mdtSqlFormOld Class Reference abstract
Base class for high level SQL widgets API.
#include <mdtSqlFormOld.h>
Public Member Functions
mdtSqlFormOld (QObject *parent=0)
Constructor.
virtual ~mdtSqlFormOld ()
Destructor.
mdtSqlFormWidget * mainSqlWidget ()
Get the main SQL widget.
bool setTable (const QString &tableName, const QString &userFriendlyTableName="", QSqlDatabase db=QSqlDatabase())
Set the main (or parent) table of the form.
virtual bool addChildTable (const QString &tableName, const QString &userFriendlyTableName="", QSqlDatabase db=QSqlDatabase())
Add a child table to the form.
bool addRelation (const QString &parentFieldName, const QString &childTableName, const QString &childFieldName, const QString &operatorWithPreviousItem="AND")
Add a relation between main table and a child table.
mdtAbstractSqlWidget * sqlWidget (const QString &tableName)
Get instance of the stored SQL widget related to a table name.
mdtSqlFormWidget * sqlFormWidget (const QString &tableName)
mdtSqlTableWidget * sqlTableWidget (const QString &tableName)
QSqlTableModel * model (const QString &tableName)
Get model that acts on given table name.
bool select (const QString &tableName)
Call select on model that acts on given table name.
QSqlError lastSqlError (const QString &tableName)
Get last error of model that acts on tableName.
mdtError lastError () const
Get last error.
int rowCount (const QString &tableName)
Get the row count for given table name.
int currentRow (const QString &tableName)
Get the current row of given table name.
bool setCurrentData (const QString &tableName, const QString &fieldName, const QVariant &data, bool submit=true)
Set (update) data of current row (record) for given table and field name.
QVariant currentData (const QString &tableName, const QString &fieldName)
Get current data for given table and field name.
QVariant data (const QString &tableName, int row, const QString &fieldName)
Get data for given table , row and field name.
Protected Member Functions
virtual void addChildWidget (mdtAbstractSqlWidget *widget)=0
Add given child widget.
Detailed Description
Base class for high level SQL widgets API.
To create SQL GUI's, some clases are available:
mdtSqlFormWidget
mdtSqlTableWidget
mdtSqlRelation
They help to deal with several common problems, but they need several code (creating objects, configure them, handle memory, ...).
This class was made to have less code for common database GUI.
You should not use this class directly, but better one of its derivate.
See Also
mdtSqlFormWindow
mdtSqlFormDialog
Definition at line 57 of file mdtSqlFormOld.h.
Constructor & Destructor Documentation
mdtSqlFormOld::mdtSqlFormOld (QObject * parent = 0)
Constructor.
Definition at line 31 of file mdtSqlFormOld.cpp.
mdtSqlFormOld::~mdtSqlFormOld () virtual
Destructor.
Definition at line 37 of file mdtSqlFormOld.cpp.
Member Function Documentation
bool mdtSqlFormOld::addChildTable (const QString & tableName, const QString & userFriendlyTableName = "", QSqlDatabase db = QSqlDatabase()) virtual
Add a child table to the form.
Parameters
tableName Table on witch the new (internally created) widget must act.
userFriendlyTableName If set, will be used at places that are visible from user.
db Database to use (pass a QSqlDatabase() if only one database is used).
Returns
True on success, false if given table name does not exist or on some other errors (database not open, access privileges, ...). False can also be returned if main table was not set (see setTable()).
Definition at line 77 of file mdtSqlFormOld.cpp.
References mdtAbstractSqlWidget::addChildWidget(), addChildWidget(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtAbstractSqlWidget::model(), model(), mdtSqlRelation::setChildModel(), mdtError::setError(), mdtAbstractSqlWidget::setModel(), mdtSqlRelation::setParentModel(), mdtError::setSystemError(), and mdtAbstractSqlWidget::setUserFriendlyTableName().
virtual void mdtSqlFormOld::addChildWidget (mdtAbstractSqlWidget * widget) protected pure virtual
Add given child widget.
Referenced by addChildTable().
bool mdtSqlFormOld::addRelation (const QString & parentFieldName, const QString & childTableName, const QString & childFieldName, const QString & operatorWithPreviousItem = "AND")
Add a relation between main table and a child table.
Returns
True on succes, false if childTableName or a field does not exit.
Definition at line 123 of file mdtSqlFormOld.cpp.
References mdtSqlRelation::addRelation(), mdtError::commit(), mdtSqlFormWidget::currentRow(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), and mdtSqlRelation::setParentCurrentIndex().
QVariant mdtSqlFormOld::currentData (const QString & tableName, const QString & fieldName)
Get current data for given table and field name.
Note that SQL widget related to given tableName is searched at each request. If several access to currentData is needed, it can be better to get a pointer to related widget with sqlWidget() , and call his currentData() method.
Returns
Current value, or a invalid QVariant on error (f.ex. table or field not found).
Definition at line 286 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtAbstractSqlWidget::currentData(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), and sqlWidget().
int mdtSqlFormOld::currentRow (const QString & tableName)
Get the current row of given table name.
Current row can be the currently selected row (case of a table view), or simply the current row that is displayed in a form view.
Note that SQL widget related to given tableName is searched at each request. If several access to currentRow is needed, it can be better to get a pointer to related widget with sqlWidget() , and call his currentRow() method.
Returns
Current row, or value < 0 on error (f.ex. table not found).
Definition at line 252 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtAbstractSqlWidget::currentRow(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), and sqlWidget().
QVariant mdtSqlFormOld::data (const QString & tableName, int row, const QString & fieldName)
Get data for given table , row and field name.
Note that SQL widget related to given tableName is searched at each request. If several access to data is needed, it can be better to get a pointer to related widget with sqlWidget() , and call his data() method.
Returns
Current value, or a invalid QVariant on error (f.ex. table, row or field not found).
Definition at line 303 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtAbstractSqlWidget::data(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setError(), and sqlWidget().
mdtError mdtSqlFormOld::lastError () const
Get last error.
Definition at line 231 of file mdtSqlFormOld.cpp.
QSqlError mdtSqlFormOld::lastSqlError (const QString & tableName)
Get last error of model that acts on tableName.
Returns
A valid QSqlError if table was found and a error occured.
Definition at line 215 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, model(), and mdtError::setError().
mdtSqlFormWidget * mdtSqlFormOld::mainSqlWidget ()
Get the main SQL widget.
Use this method to get the widget to give as argument to setupUi() method of your Ui widget.
Postcondition
Returns a valid object.
Definition at line 41 of file mdtSqlFormOld.cpp.
Referenced by mdtSqlFormDialog::mdtSqlFormDialog(), and mdtSqlFormWindow::mdtSqlFormWindow().
QSqlTableModel * mdtSqlFormOld::model (const QString & tableName)
Get model that acts on given table name.
Returns
QSqlTableModel object or a null pointer if table was not found.
Definition at line 187 of file mdtSqlFormOld.cpp.
References mdtAbstractSqlWidget::model(), and sqlWidget().
Referenced by addChildTable(), lastSqlError(), rowCount(), select(), and setTable().
int mdtSqlFormOld::rowCount (const QString & tableName)
Get the row count for given table name.
Note that SQL widget related to given tableName is searched at each request. If several access to rowCount is needed, it can be better to get a pointer to related model with model() , and call his rowCount() method.
Returns
Row count, or value < 0 on error (f.ex. table not found).
Definition at line 236 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, model(), and mdtError::setError().
bool mdtSqlFormOld::select (const QString & tableName)
Call select on model that acts on given table name.
Returns
True on success, false if tableName was not found or other error. On failure, the last error is avaliable with lastError()
Definition at line 199 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, model(), and mdtError::setError().
bool mdtSqlFormOld::setCurrentData (const QString & tableName, const QString & fieldName, const QVariant & data, bool submit = true)
Set (update) data of current row (record) for given table and field name.
Note that SQL widget related to given tableName is searched at each request. If several access to setCurrentData is needed, it can be better to get a pointer to related widget with sqlWidget() , and call his setCurrentData() method.
Definition at line 269 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtAbstractSqlWidget::setCurrentData(), mdtError::setError(), and sqlWidget().
bool mdtSqlFormOld::setTable (const QString & tableName, const QString & userFriendlyTableName = "", QSqlDatabase db = QSqlDatabase())
Set the main (or parent) table of the form.
Note: be shure that your Ui::setupUi() was called on widget returned by mainSqlWidget() before.
Parameters
tableName Table on witch the form must act.
userFriendlyTableName If set, will be used at places that are visible from user.
db Database to use (pass a QSqlDatabase() if only one database is used).
Returns
True on success, false if given table name does not exist or on some other errors (database not open, access privileges, ...)
Definition at line 48 of file mdtSqlFormOld.cpp.
References mdtError::commit(), mdtError::Error, mdtSqlFormWidget::mapFormWidgets(), MDT_ERROR_SET_SRC, mdtAbstractSqlWidget::model(), model(), mdtError::setError(), mdtAbstractSqlWidget::setModel(), mdtError::setSystemError(), and mdtAbstractSqlWidget::setUserFriendlyTableName().
mdtSqlFormWidget * mdtSqlFormOld::sqlFormWidget (const QString & tableName)
Definition at line 163 of file mdtSqlFormOld.cpp.
References sqlWidget().
mdtSqlTableWidget * mdtSqlFormOld::sqlTableWidget (const QString & tableName)
Definition at line 175 of file mdtSqlFormOld.cpp.
References sqlWidget().
mdtSqlFormOld::sqlWidget (const QString & tableName)
Get instance of the stored SQL widget related to a table name.
Returns a null pointer if widget related to tableName was not found.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 146 of file mdtSqlFormOld.cpp.
References mdtAbstractSqlWidget::sqlWidgets().
Referenced by currentData(), currentRow(), data(), model(), setCurrentData(), sqlFormWidget(), and sqlTableWidget().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSqlFormOld.h
src/mdtutilsgui/mdtSqlFormOld.cpp