Multi diag tools: mdtFrame Class Reference
mdtFrame Class Reference
Provide an array of bytes.
#include <mdtFrame.h>
Public Types
enum type_t {
FT_RAW, FT_RAW_TOP, FT_ASCII, FT_MODBUS_TCP,
FT_USBTMC
}
Frame type.
Public Member Functions
mdtFrame ()
virtual ~mdtFrame ()
void setIgnoreNullValues (bool ignoreNullValues)
Set the ignore null values flag.
int putUntil (const char *data, char token, int maxLen)
Put data until EOF token was reached.
int putUntil (const char *data, QByteArray &token, int maxLen)
Put data until EOF token was reached.
bool isFull ()
Returns true if frame is full.
int remainCapacity ()
Returns the remain capacity.
int bytesToStore ()
Returns the bytes to store into the frame.
void setDirectlyComplete (bool dc)
Set the complete flag directly.
void setComplete ()
Set the frame as complete.
bool isComplete ()
Returns true if EOF condition was reached.
void clear ()
Overloaded function.
virtual void clearSub ()
mdtFrame subclass specific clear
virtual int putData (const char *data, int len)
Put data into the frame.
virtual int eofSeqLen ()
Get the length of the end of frame sequence.
int take (char *data, int len)
Take some data.
int take (int len)
Take some data.
void setWaitAnAnswer (bool wait)
Tell a write/read thread that an answer is needed after a write frame.
bool waitAnAnswer () const
Know if an answer is needed after a write frame.
Protected Attributes
bool pvIgnoreNullValues
bool pvEOFcondition
bool pvWaitAnAnswer
Detailed Description
Provide an array of bytes.
mdtFrame is based on Qt's QByteArray, that provide a array of bytes. To store data, the QByteArray's methods append() can be used.
For ASCII frames reception, the end is a special char/string on most case. mdtFrame provide the functions putUntil() for that purpose.
During data reception, for exemple from serial port, the best way to check if more data can be stored is to use bytesToStore(). It returns the remain capacity of the frame, and 0 if the end of frame (EOF) condition was reached. To know if the frame is complete (i.e. end of frame condition ok), use isComplete()
Here are the states of a frame with return values of both functions:
State bytesToStore() isComplete()
Frame is not full, and EOF condition not reached remainCapacity() false
Frame is full, and EOF condition not reached 0 false
Frame is not full, and EOF condition reached 0 true
Frame is full, and EOF condition reached 0 true
At this state, whenn bytesToStore() returns 0 and isComplete() is true, the received frame is ok. The next step is to decode it, according to the used protocol (modbus, ...).
Note that these states are only set when using putUntil() and putData() functions.
Definition at line 48 of file mdtFrame.h.
Member Enumeration Documentation
enum mdtFrame::type_t
Frame type.
Enumerator
FT_RAW
Raw binary data
FT_RAW_TOP
Raw binary data for usage with timeout protocol
FT_ASCII
ASCII frame type
FT_MODBUS_TCP
MODBUS/TCP frame type
FT_USBTMC
USBTMC frame type
Definition at line 57 of file mdtFrame.h.
Constructor & Destructor Documentation
mdtFrame::mdtFrame ()
Definition at line 24 of file mdtFrame.cpp.
References pvEOFcondition, pvIgnoreNullValues, and pvWaitAnAnswer.
mdtFrame::~mdtFrame () virtual
Definition at line 32 of file mdtFrame.cpp.
Member Function Documentation
int mdtFrame::bytesToStore ()
Returns the bytes to store into the frame.
Bytes to store can be the remainCapacity() value if frame is not full and EOF condition was not reached. Else, it returns 0.
Definition at line 156 of file mdtFrame.cpp.
References pvEOFcondition, and remainCapacity().
Referenced by mdtFrameModbusTcp::putData(), and mdtPortThreadHelper::submitReadenData().
void mdtFrame::clear ()
Overloaded function.
Internally, it calls QByteArray's clear() and reserve() methods. The goal is to keep the same capacity and reset some mdtFrame and subclass specific flags
Definition at line 179 of file mdtFrame.cpp.
References pvEOFcondition.
Referenced by mdtPortThreadHelper::handleCommonReadErrors(), mdtModbusTcpPortManager::sendData(), and mdtPortManager::sendData().
void mdtFrame::clearSub () virtual
mdtFrame subclass specific clear
This method is usefull to clear some specific flags and data in subclasses (such as mdtFrameUsbTmc).
Note that QByteArray's flags and data are not altered.
This method is called from mdtPortThread::getNewFrameRead() . Default implementation does nothing.
This class must be implemented is subclass if needed.
Reimplemented in mdtFrameModbusTcp.
Definition at line 188 of file mdtFrame.cpp.
Referenced by mdtPortThreadHelper::handleCommonReadErrors(), and mdtPortManager::sendData().
int mdtFrame::eofSeqLen () virtual
Get the length of the end of frame sequence.
Used for ASCII frames. Default implementation returns 0
Reimplemented in mdtFrameAscii.
Definition at line 209 of file mdtFrame.cpp.
Referenced by mdtPortThreadHelper::submitReadenData().
bool mdtFrame::isComplete ()
Returns true if EOF condition was reached.
Definition at line 174 of file mdtFrame.cpp.
References pvEOFcondition.
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), mdtPortManager::fromThreadNewFrameReaden(), and putUntil().
bool mdtFrame::isFull ()
Returns true if frame is full.
Definition at line 140 of file mdtFrame.cpp.
References remainCapacity().
Referenced by putUntil().
int mdtFrame::putData (const char * data, int len) virtual
Put data into the frame.
Must be implemented by specific frame subclass.
This method is called by the read thread.
Default implementation simply stores data, and set the EOF condition to true. This way, it's possible to use mdtFrame for raw binary transfers.
Parameters
data Valid pointer to the data
len Maximum number of byte to store, must not be more than data size
Returns
Number of bytes that could really be stored
Precondition
The data pointer must be valid, and not be the internal pointer returned by data().
Reimplemented in mdtFrameModbusTcp, and mdtFrameAscii.
Definition at line 192 of file mdtFrame.cpp.
References pvEOFcondition, and remainCapacity().
Referenced by mdtPortThreadHelper::submitReadenData().
int mdtFrame::putUntil (const char * data, char token, int maxLen)
Put data until EOF token was reached.
This function is usefull for ASCII frames reception. Whenn token is reached, the EOF condition will become true (the EOF char is not stored).
When the EOF condition was reached, this function does not store any more data.
Note that this function is slower than QByteArray's append() method, because it compares each byte with the token.
Parameters
data Pointer to source data
token Token that represents the EOF (End Of Frame)
maxLen Length of the array pointed by data
Returns
The number of bytes really stored
Precondition
The data pointer must be valid, and not be the internal pointer returned by data().
Definition at line 41 of file mdtFrame.cpp.
References isComplete(), isFull(), pvEOFcondition, pvIgnoreNullValues, and remainCapacity().
Referenced by mdtFrameAscii::putData().
int mdtFrame::putUntil (const char * data, QByteArray & token, int maxLen)
Put data until EOF token was reached.
This is an overloaded function. The token can be a sequence of bytes.
See Also
putUntil()
Definition at line 88 of file mdtFrame.cpp.
References isComplete(), isFull(), pvEOFcondition, pvIgnoreNullValues, and remainCapacity().
int mdtFrame::remainCapacity ()
Returns the remain capacity.
Definition at line 145 of file mdtFrame.cpp.
Referenced by bytesToStore(), isFull(), mdtFrameModbusTcp::putData(), putData(), and putUntil().
void mdtFrame::setComplete ()
Set the frame as complete.
This is used by mdtPortReadThread with timeout protocols.
Definition at line 169 of file mdtFrame.cpp.
References pvEOFcondition.
void mdtFrame::setDirectlyComplete (bool dc)
Set the complete flag directly.
This is usefull for raw mode transfert. If true, the frame is set complete after each call of putData()
Parameters
dc The Directly complete flag
Definition at line 164 of file mdtFrame.cpp.
Referenced by mdtAbstractPort::initQueues().
void mdtFrame::setIgnoreNullValues (bool ignoreNullValues)
Set the ignore null values flag.
If set true, all null values ('\0' or 0) are not stored by putUntil() methods
Definition at line 36 of file mdtFrame.cpp.
References pvIgnoreNullValues.
void mdtFrame::setWaitAnAnswer (bool wait)
Tell a write/read thread that an answer is needed after a write frame.
In some case, typically USB, the host must allways init a transaction, for read and for write. For such case, only one thread manages the write/read process:
Wait until a frame must be sent (can be bypassed with a flag)
Init a write transaction, wait until transaction is finish
Init a read transaction, wait until something was readen. The last step can be a problem if we have to write a frame (f.ex. a query), but not need an answer. After that, we have to send a second query, but need wait until data was received.
To solve this problem, we must tell the thread if it must init a read transaction after a frame was written (request) or not, and this is the goal of this method.
See Also
mdtUsbPortThread
Definition at line 246 of file mdtFrame.cpp.
References pvWaitAnAnswer.
Referenced by mdtModbusTcpPortManager::sendData().
int mdtFrame::take (char * data, int len)
Take some data.
Parameters
data Pointer to data destination
len Number of bytes to take
Precondition
The data pointer must be valid, and not be the internal pointer returned by data().
Definition at line 214 of file mdtFrame.cpp.
Referenced by mdtPortThreadHelperPort::writeDataToPort().
int mdtFrame::take (int len)
Take some data.
This method does not copy any data, but is usefull after a copy using QByteArray::data() . The consumed bytes are removed from frame
Parameters
data Pointer to data destination
len Number of bytes to take
Precondition
The data pointer must be valid, and not be the internal pointer returned by data().
Definition at line 232 of file mdtFrame.cpp.
bool mdtFrame::waitAnAnswer () const
Know if an answer is needed after a write frame.
See Also
setWaitAnAnswer()
Definition at line 251 of file mdtFrame.cpp.
References pvWaitAnAnswer.
Member Data Documentation
bool mdtFrame::pvEOFcondition protected
Definition at line 214 of file mdtFrame.h.
Referenced by bytesToStore(), clear(), isComplete(), mdtFrame(), mdtFrameModbusTcp::putData(), putData(), putUntil(), and setComplete().
bool mdtFrame::pvIgnoreNullValues protected
Definition at line 213 of file mdtFrame.h.
Referenced by mdtFrame(), putUntil(), and setIgnoreNullValues().
bool mdtFrame::pvWaitAnAnswer protected
Definition at line 215 of file mdtFrame.h.
Referenced by mdtFrame(), setWaitAnAnswer(), and waitAnAnswer().
The documentation for this class was generated from the following files:
src/mdtutils/mdtFrame.h
src/mdtutils/mdtFrame.cpp