Multi diag tools: mdtClLink Class Reference
mdtClLink Class Reference
Helper class for link management.
#include <mdtClLink.h>
Public Member Functions
mdtClLink (QObject *parent, QSqlDatabase db)
Constructor.
~mdtClLink ()
Destructor.
bool buildVehicleTypeLinkDataList (mdtClLinkData &linkData, const QList< QVariant > &vtStartIdList, const QList< QVariant > &vtEndIdList)
Build vehicle type link data based on given start and end vehicle ID lists.
bool addLink (const mdtClLinkData &linkData, bool handleTransaction=true)
Add a link.
bool addLinks (const QList< mdtClLinkData > &linkDataList, bool handleTransaction=true)
Add a list of links.
bool linkExists (const QVariant &unitConnectionStartId, const QVariant &unitConnectionEndId, bool *ok)
Check if a link exists.
mdtClLinkData getLinkData (const QVariant &unitConnectionStartId, const QVariant &unitConnectionEndId, bool includeConnectionData, bool includeVehicleTypeLinkData, bool *ok)
Get link data.
bool editLink (const QVariant &unitConnectionStartId, const QVariant &unitConnectionEndId, const mdtClLinkData &linkData)
Edit a unit link.
bool removeLink (const QVariant &unitConnectionStartId, const QVariant &unitConnectionEndId, bool handleTransaction=true)
Remove a unit link.
bool removeLinks (const mdtSqlTableSelection &s)
Remove each unit link that is contained in selection.
QList< mdtClVehicleTypeLinkData > getVehicleTypeLinkDataByUnitId (const QVariant &unitId, bool *ok)
Get vehicle type link data for given unit ID.
bool removeVehicleTypeLinkByUnitId (const QVariant &unitId, bool handleTransaction)
Remove vehicle type links for given unit ID.
bool removeVehicleTypeLinks (const QList< mdtClVehicleTypeLinkData > &vtLinkList, bool handleTransaction)
Remove vehicle type links.
QList< mdtClLinkData > getConnectionLinkListByName (const QList< mdtClUnitConnectionData > &A, const QList< mdtClUnitConnectionData > &B)
Get a list of connection links between A and B connections, by name.
bool canConnectConnectors (const mdtClUnitConnectorData &S, const mdtClUnitConnectorData &E)
Check if unit connector S can be connected with unit connector E.
bool canConnectConnectors (const QVariant &startUnitConnectorId, const QVariant &endUnitConnectorId, bool *ok)
Check if unit connector start can be connected with unit connector end.
QString sqlForConnectableUnitConnectorsSelection (const QVariant &unitConnectorId, const QVariant &unitId, bool *ok)
Get SQL statement for connectable unit connector selection.
bool connectByContactName (const mdtClUnitConnectorData &S, const mdtClUnitConnectorData &E, const QVariant &startVehicleTypeId, const QVariant &endVehicleTypeId)
Connect start and end connector by contact name.
bool connectByContactName (const QVariant &startUnitConnectorId, const QVariant &endUnitConnectorId, const QVariant &startVehicleTypeId, const QVariant &endVehicleTypeId)
Connect start and end connector by contact name.
bool disconnectConnectors (const QVariant &startUnitConnectorId, const QVariant &endUnitConnectorId, const QList< QVariant > &startVehicleTypeIdList, const QList< QVariant > &endVehicleTypeIdList)
Disconnect connector S from E.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
bool addRecordList (const QList< mdtSqlRecord > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class for link management.
Definition at line 37 of file mdtClLink.h.
Constructor & Destructor Documentation
mdtClLink::mdtClLink (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 32 of file mdtClLink.cpp.
mdtClLink::~mdtClLink ()
Destructor.
Definition at line 37 of file mdtClLink.cpp.
Member Function Documentation
bool mdtClLink::addLink (const mdtClLinkData & linkData, bool handleTransaction = true)
Add a link.
Will also add required vehicle type links stored in linkData. To generate vehicle type links, use buildVehicleTypeLinkDataList().
Definition at line 84 of file mdtClLink.cpp.
References mdtTtBase::addRecord(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::rollbackTransaction(), and mdtClLinkData::vehicleTypeLinkDataList().
Referenced by addLinks(), and editLink().
bool mdtClLink::addLinks (const QList< mdtClLinkData > & linkDataList, bool handleTransaction = true)
Add a list of links.
See Also
addLink().
Definition at line 115 of file mdtClLink.cpp.
References addLink(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), and mdtTtBase::rollbackTransaction().
Referenced by connectByContactName().
bool mdtClLink::buildVehicleTypeLinkDataList (mdtClLinkData & linkData, const QList< QVariant > & vtStartIdList, const QList< QVariant > & vtEndIdList)
Build vehicle type link data based on given start and end vehicle ID lists.
The list is built regarding distinct cases:
If both start and end vehicle types lists contains exactly the same count of items, each start ID is put together with each end ID , in the order of both lists.
If one vehicle types list has only 1 item, and the other has many items, the ID of the 1 item list is copied to the other list (case of 1 vehicle type linked to many vehicle types) .
All other cases are wrong.
Definition at line 41 of file mdtClLink.cpp.
References mdtClLinkData::addVehicleTypeLinkData(), mdtClLinkData::clearVehicleTypeLinkDataList(), mdtClVehicleTypeLinkData::setVehicleTypeEndId(), and mdtClVehicleTypeLinkData::setVehicleTypeStartId().
Referenced by connectByContactName().
bool mdtClLink::canConnectConnectors (const mdtClUnitConnectorData & S, const mdtClUnitConnectorData & E)
Check if unit connector S can be connected with unit connector E.
Currently, this method will only check if at least S and E have a socket/pin (or pin/socket) that have the same contact name.
Definition at line 433 of file mdtClLink.cpp.
References mdtClUnitConnectorData::connectionDataList(), and getConnectionLinkListByName().
Referenced by canConnectConnectors(), and sqlForConnectableUnitConnectorsSelection().
bool mdtClLink::canConnectConnectors (const QVariant & startUnitConnectorId, const QVariant & endUnitConnectorId, bool * ok)
Check if unit connector start can be connected with unit connector end.
Currently, this method will only check if at least S and E have a socket/pin (or pin/socket) that have the same contact name.
Definition at line 438 of file mdtClLink.cpp.
References canConnectConnectors(), mdtTtBase::database(), mdtClUnit::getConnectorData(), mdtTtBase::lastError(), and mdtTtBase::pvLastError.
bool mdtClLink::connectByContactName (const mdtClUnitConnectorData & S, const mdtClUnitConnectorData & E, const QVariant & startVehicleTypeId, const QVariant & endVehicleTypeId)
Connect start and end connector by contact name.
Will create a link of type CONNECTION for each connection from start connector to a connection of end connector that can be connected. See getConnectionLinkListByName() for details.
Definition at line 522 of file mdtClLink.cpp.
References addLinks(), buildVehicleTypeLinkDataList(), mdtError::commit(), mdtClUnitConnectorData::connectionDataList(), getConnectionLinkListByName(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), mdtSqlRecord::value(), and mdtError::Warning.
Referenced by connectByContactName().
bool mdtClLink::connectByContactName (const QVariant & startUnitConnectorId, const QVariant & endUnitConnectorId, const QVariant & startVehicleTypeId, const QVariant & endVehicleTypeId)
Connect start and end connector by contact name.
Will create a link of type CONNECTION for each connection from start connector to a connection of end connector that can be connected. See getConnectionLinkListByName() for details.
Definition at line 553 of file mdtClLink.cpp.
References connectByContactName(), mdtTtBase::database(), mdtClUnit::getConnectorData(), mdtTtBase::lastError(), and mdtTtBase::pvLastError.
bool mdtClLink::disconnectConnectors (const QVariant & startUnitConnectorId, const QVariant & endUnitConnectorId, const QList< QVariant > & startVehicleTypeIdList, const QList< QVariant > & endVehicleTypeIdList)
Disconnect connector S from E.
Todo:
In current version, vehicle type list are not token in acount. This will be the case once removeLink() is fixed.
Definition at line 574 of file mdtClLink.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::getData(), removeLink(), and mdtTtBase::rollbackTransaction().
bool mdtClLink::editLink (const QVariant & unitConnectionStartId, const QVariant & unitConnectionEndId, const mdtClLinkData & linkData)
Edit a unit link.
Definition at line 204 of file mdtClLink.cpp.
References addLink(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), removeLink(), and mdtTtBase::rollbackTransaction().
QList< mdtClLinkData > mdtClLink::getConnectionLinkListByName (const QList< mdtClUnitConnectionData > & A, const QList< mdtClUnitConnectionData > & B)
Get a list of connection links between A and B connections, by name.
Will search connections that have the same name, and that can be connected together, in A and B list. Currently, connections can be connected if item of A is a pin and item of B is a socket, or in reverse case.
This method is typically used to create connections links between 2 connectors (i.e. connect them).
For each link that was found, following fields are also set:
UnitConnectionStart_Id_FK : ID of item in A
UnitConnectionEnd_Id_FK : ID of item in B
LinkType_Code_FK : CONNECTION
LinkDirection_Code_FK : BID
Definition at line 378 of file mdtClLink.cpp.
References mdtClLinkData::clearValues(), mdtTtBase::database(), mdtClLinkData::setEndConnectionData(), mdtClLinkData::setStartConnectionData(), mdtClLinkData::setup(), mdtSqlRecord::setValue(), and mdtSqlRecord::value().
Referenced by canConnectConnectors(), and connectByContactName().
mdtClLinkData mdtClLink::getLinkData (const QVariant & unitConnectionStartId, const QVariant & unitConnectionEndId, bool includeConnectionData, bool includeVehicleTypeLinkData, bool * ok)
Get link data.
Definition at line 156 of file mdtClLink.cpp.
References mdtError::commit(), mdtError::Error, mdtTtBase::getData(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, and mdtError::setError().
QList< mdtClVehicleTypeLinkData > mdtClLink::getVehicleTypeLinkDataByUnitId (const QVariant & unitId, bool * ok)
Get vehicle type link data for given unit ID.
Definition at line 280 of file mdtClLink.cpp.
References mdtTtBase::database(), mdtTtBase::getData(), mdtClVehicleTypeLinkData::setUnitConnectionEndId(), mdtClVehicleTypeLinkData::setUnitConnectionStartId(), mdtClVehicleTypeLinkData::setVehicleTypeEndId(), and mdtClVehicleTypeLinkData::setVehicleTypeStartId().
Referenced by removeVehicleTypeLinkByUnitId().
bool mdtClLink::linkExists (const QVariant & unitConnectionStartId, const QVariant & unitConnectionEndId, bool * ok)
Check if a link exists.
Definition at line 141 of file mdtClLink.cpp.
References mdtTtBase::getData().
bool mdtClLink::removeLink (const QVariant & unitConnectionStartId, const QVariant & unitConnectionEndId, bool handleTransaction = true)
Remove a unit link.
Will also remove all vehicle type related links
Todo:
Wrong way for delete: will delete links for all vehicle type assoc. Check about a overloaded method that limits vehicle type assoc. , that only remove the link in Link_tbl when no entry exists in VehicleType_Link_tbl
Definition at line 229 of file mdtClLink.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::removeData(), and mdtTtBase::rollbackTransaction().
Referenced by disconnectConnectors(), editLink(), and removeLinks().
bool mdtClLink::removeLinks (const mdtSqlTableSelection & s)
Remove each unit link that is contained in selection.
Definition at line 260 of file mdtClLink.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtSqlTableSelection::data(), removeLink(), mdtTtBase::rollbackTransaction(), and mdtSqlTableSelection::rowCount().
bool mdtClLink::removeVehicleTypeLinkByUnitId (const QVariant & unitId, bool handleTransaction)
Remove vehicle type links for given unit ID.
Definition at line 314 of file mdtClLink.cpp.
References getVehicleTypeLinkDataByUnitId(), and removeVehicleTypeLinks().
Referenced by mdtClUnitVehicleType::removeUnitVehicleAssignments().
bool mdtClLink::removeVehicleTypeLinks (const QList< mdtClVehicleTypeLinkData > & vtLinkList, bool handleTransaction)
Remove vehicle type links.
Definition at line 327 of file mdtClLink.cpp.
References mdtTtBase::beginTransaction(), mdtError::commit(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtTtBase::rollbackTransaction(), mdtError::setError(), mdtError::setSystemError(), mdtClVehicleTypeLinkData::unitConnectionEndId(), mdtClVehicleTypeLinkData::unitConnectionStartId(), mdtClVehicleTypeLinkData::vehicleTypeEndId(), and mdtClVehicleTypeLinkData::vehicleTypeStartId().
Referenced by removeVehicleTypeLinkByUnitId().
QString mdtClLink::sqlForConnectableUnitConnectorsSelection (const QVariant & unitConnectorId, const QVariant & unitId, bool * ok)
Get SQL statement for connectable unit connector selection.
SQL statement will select unit connectors that can be connected to given start unit connector ID. If given unit ID is not null, only connectors related to this unit will be included.
Returns
SQL statement, or empty string on error.
Definition at line 461 of file mdtClLink.cpp.
References canConnectConnectors(), mdtError::commit(), mdtTtBase::getData(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::Warning.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClLink.h
src/mdttools/mdttesttool/mdtcablelist/mdtClLink.cpp