Multi diag tools: mdtSortFilterProxyModel Class Reference
mdtSortFilterProxyModel Class Reference
Provide natural sort for Qt model/view.
#include <mdtSortFilterProxyModel.h>
Public Member Functions
mdtSortFilterProxyModel (QObject *parent=0)
Constructor.
~mdtSortFilterProxyModel ()
Destructor.
void clearColumnsSortOrder ()
Clear columns sort order.
void addColumnToSortOrder (int column, Qt::SortOrder order=Qt::AscendingOrder)
Add a column to columns sort order.
void addColumnToSortOrder (const QString &fieldName, Qt::SortOrder order=Qt::AscendingOrder)
Add a field to columns sort order.
void disableSorting ()
Disable sorting.
void enableSorting ()
Enable sorting.
bool hasColumnToSort () const
Check if some coulumn was set to sort order.
QVector< int > sortedColumns () const
Get list of indexes of columns that are in sort order.
Qt::SortOrder sortOrder (int column) const
Get sort order for given column.
void sort ()
Sort.
Detailed Description
Provide natural sort for Qt model/view.
Definition at line 32 of file mdtSortFilterProxyModel.h.
Constructor & Destructor Documentation
mdtSortFilterProxyModel::mdtSortFilterProxyModel (QObject * parent = 0)
Constructor.
Definition at line 30 of file mdtSortFilterProxyModel.cpp.
mdtSortFilterProxyModel::~mdtSortFilterProxyModel ()
Destructor.
Definition at line 36 of file mdtSortFilterProxyModel.cpp.
Member Function Documentation
void mdtSortFilterProxyModel::addColumnToSortOrder (int column, Qt::SortOrder order = Qt::AscendingOrder)
Add a column to columns sort order.
Columns sort order is similar meaning than SQL ORDER BY clause.
For example, to sort columns in order 0, 2, 1 all ascending, call:
clearColumnsSortOrder();
addColumnToSortOrder(0, Qt::AscendingOrder);
addColumnToSortOrder(2, Qt::AscendingOrder);
addColumnToSortOrder(1, Qt::AscendingOrder);
Note: if given column is out of bound, it will simply be ignored.
Definition at line 45 of file mdtSortFilterProxyModel.cpp.
Referenced by addColumnToSortOrder(), and mdtSqlSelectionDialog::addColumnToSortOrder().
void mdtSortFilterProxyModel::addColumnToSortOrder (const QString & fieldName, Qt::SortOrder order = Qt::AscendingOrder)
Add a field to columns sort order.
Here it's possible to define a field name. Note that this method does nothing if sourceModel is not based on QSqlQueryModel.
Definition at line 58 of file mdtSortFilterProxyModel.cpp.
References addColumnToSortOrder().
void mdtSortFilterProxyModel::clearColumnsSortOrder ()
Clear columns sort order.
See Also
addColumnToSortOrder()
Definition at line 40 of file mdtSortFilterProxyModel.cpp.
Referenced by mdtSqlSelectionDialog::clearColumnsSortOrder().
void mdtSortFilterProxyModel::disableSorting () inline
Disable sorting.
Usefull if sorting must be disabled temprary, without loosing setuped columns to sort.
Definition at line 81 of file mdtSortFilterProxyModel.h.
void mdtSortFilterProxyModel::enableSorting () inline
Enable sorting.
Definition at line 85 of file mdtSortFilterProxyModel.h.
bool mdtSortFilterProxyModel::hasColumnToSort () const
Check if some coulumn was set to sort order.
Definition at line 73 of file mdtSortFilterProxyModel.cpp.
void mdtSortFilterProxyModel::sort ()
Sort.
Definition at line 103 of file mdtSortFilterProxyModel.cpp.
QVector< int > mdtSortFilterProxyModel::sortedColumns () const
Get list of indexes of columns that are in sort order.
Note: each call of this method will rebuild the list.
Definition at line 78 of file mdtSortFilterProxyModel.cpp.
Qt::SortOrder mdtSortFilterProxyModel::sortOrder (int column) const
Get sort order for given column.
If column is not in sorted columns list, Qt::AscendingOrder is returnded
Definition at line 90 of file mdtSortFilterProxyModel.cpp.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSortFilterProxyModel.h
src/mdtutilsgui/mdtSortFilterProxyModel.cpp