Multi diag tools: mdtTtApplicationWidgets Class Reference
mdtTtApplicationWidgets Class Reference
Container for test tool editors and views.
#include <mdtTtApplicationWidgets.h>
Public Slots
void slotEditTestCables ()
Edit test cables.
Static Public Member Functions
static void editTestCable (const QVariant &testCableId)
Edit a specific test cable.
static void editTestCables ()
Edit test cables.
Static Public Member Functions inherited from mdtSqlApplicationWidgets< mdtTtApplicationWidgets >
static void setDatabase (QSqlDatabase db)
Set database to use.
static QSqlDatabase database ()
Get used database.
static bool closeOpenWidgets ()
Close all open widgets.
static void clear ()
Clear.
static mdtTtApplicationWidgets * instancePtr ()
Get pointer to instance.
Friends
class mdtSqlApplicationWidgets< mdtTtApplicationWidgets >
Additional Inherited Members
Protected Member Functions inherited from mdtSqlApplicationWidgets< mdtTtApplicationWidgets >
std::shared_ptr< mdtSqlWindow > setupEditorInSqlWindow (const std::shared_ptr< mdtSqlForm > &editor)
Setup given editor in mdtSqlWindow.
void showSqlWindow (const std::shared_ptr< mdtSqlForm > &form, bool enableNavigation, bool enableEdition)
Show open window that contains given sql form.
std::shared_ptr< mdtSqlWindow > getOpenSqlWindow (const std::shared_ptr< mdtSqlForm > &form)
Get open window for given sql form.
bool closeOpenSqlWindows ()
Close all open SQL windows.
virtual bool closeCustomWidgets ()
Close custom widgets.
void displayError (const mdtError &error)
Display a error to the user.
mdtSqlApplicationWidgets ()
Prevent multiple object instances.
Static Protected Member Functions inherited from mdtSqlApplicationWidgets< mdtTtApplicationWidgets >
static mdtTtApplicationWidgets & instance ()
Get the (unique) instance.
Protected Attributes inherited from mdtSqlApplicationWidgets< mdtTtApplicationWidgets >
QSqlDatabase pvDatabase
Detailed Description
Container for test tool editors and views.
Using this class helps to create editors and views. Most of time, only one instance of each editore or view is needed, but must be accessible from multiple places in application.
Definition at line 35 of file mdtTtApplicationWidgets.h.
Member Function Documentation
void mdtTtApplicationWidgets::editTestCable (const QVariant & testCableId) static
Edit a specific test cable.
Definition at line 27 of file mdtTtApplicationWidgets.cpp.
References mdtSqlApplicationWidgets< mdtTtApplicationWidgets >::instance().
void mdtTtApplicationWidgets::editTestCables () static
Edit test cables.
Definition at line 48 of file mdtTtApplicationWidgets.cpp.
References mdtSqlApplicationWidgets< mdtTtApplicationWidgets >::instance(), and slotEditTestCables().
void mdtTtApplicationWidgets::slotEditTestCables () slot
Edit test cables.
Definition at line 53 of file mdtTtApplicationWidgets.cpp.
References mdtSqlApplicationWidgets< mdtTtApplicationWidgets >::displayError(), and mdtSqlApplicationWidgets< mdtTtApplicationWidgets >::showSqlWindow().
Referenced by editTestCables().
Friends And Related Function Documentation
friend class mdtSqlApplicationWidgets< mdtTtApplicationWidgets > friend
Definition at line 40 of file mdtTtApplicationWidgets.h.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtApplicationWidgets.h
src/mdttools/mdttesttool/mdtTtApplicationWidgets.cpp