Multi diag tools: mdtPortTransaction Class Reference
mdtPortTransaction Class Reference
Store port transaction identifications data.
#include <mdtPortTransaction.h>
Public Member Functions
mdtPortTransaction ()
Construct a empty transaction.
~mdtPortTransaction ()
Destructor.
void clear ()
Clear transaction.
void setId (int id)
Set transaction identifer.
int id () const
Get id.
void setType (int type)
Set type.
int type () const
Get type.
void setIo (mdtAnalogIo *io, bool isInput)
Set the concerned analog I/O.
void setIo (mdtDigitalIo *io, bool isInput)
Set the concerned digital I/O.
mdtAnalogIo * analogIo ()
Get the concerned analog I/O.
mdtDigitalIo * digitalIo ()
Set the concerned digital I/O.
void setIsInput (bool isInput)
Set the isInput flag.
bool isInput () const
Get the isInput flag.
bool isOutput () const
Get the isOutput flag.
void setData (const QByteArray &data)
Set data by copy.
QByteArray data () const
Get stored data.
void setQueryReplyMode (bool mode)
Set query/reply mode.
bool isQueryReplyMode () const
Get the query/reply mode flag.
void setAddress (int address)
Set address.
int address () const
Get address.
void setIoCount (int n)
Set the number of I/Os concerned by transaction.
int ioCount () const
Get the number of I/Os concerned by transaction.
Detailed Description
Store port transaction identifications data.
After a query was sent to a device, a bit later a response will come back.
It's not allways easy, as decoder method, to know what type of query was sent in the past, witch I/O the answer will concern, ...
This class helps mdtPortManager and mdtDevice for that.
Definition at line 39 of file mdtPortTransaction.h.
Constructor & Destructor Documentation
mdtPortTransaction::mdtPortTransaction ()
Construct a empty transaction.
See clear() for details about empty transaction.
Definition at line 23 of file mdtPortTransaction.cpp.
References clear().
mdtPortTransaction::~mdtPortTransaction ()
Destructor.
Definition at line 28 of file mdtPortTransaction.cpp.
Member Function Documentation
int mdtPortTransaction::address () const
Get address.
Definition at line 136 of file mdtPortTransaction.cpp.
Referenced by mdtDeviceModbus::readAnalogInput(), mdtDeviceModbus::readAnalogInputs(), mdtDeviceModbus::readAnalogOutput(), mdtDeviceModbus::readAnalogOutputs(), mdtDeviceModbus::readDigitalInput(), mdtDeviceModbus::readDigitalInputs(), mdtDeviceModbus::readDigitalOutput(), mdtDeviceModbus::readDigitalOutputs(), setAddress(), mdtDeviceModbus::writeAnalogOutput(), and mdtDeviceModbus::writeDigitalOutput().
mdtAnalogIo * mdtPortTransaction::analogIo ()
Get the concerned analog I/O.
See setIo(mdtAnalogIo*) for details.
Definition at line 84 of file mdtPortTransaction.cpp.
void mdtPortTransaction::clear ()
Clear transaction.
A empty transaction has following values:
id: 0
type: 0
analogIo: Null
digitalIo: Null
ioCount: 0
isInput: false
isOutput: false
data: empty
isQueryReplyMode: false
address: 0
Definition at line 32 of file mdtPortTransaction.cpp.
Referenced by mdtPortManager::getNewTransaction(), and mdtPortTransaction().
QByteArray mdtPortTransaction::data () const
Get stored data.
Definition at line 116 of file mdtPortTransaction.cpp.
Referenced by mdtPortTerm::appendReadenData(), mdtPortManager::readenFrame(), mdtPortManager::readenFrames(), mdtModbusTcpPortManager::sendData(), and mdtPortManager::sendData().
mdtDigitalIo * mdtPortTransaction::digitalIo ()
Set the concerned digital I/O.
See setIo(mdtDigitalIo*) for details.
Definition at line 89 of file mdtPortTransaction.cpp.
int mdtPortTransaction::id () const
Get id.
See setId() for details.
Definition at line 51 of file mdtPortTransaction.cpp.
Referenced by mdtPortManager::addTransactionDone(), mdtPortManager::addTransactionPending(), mdtPortManager::fromThreadNewFrameReaden(), mdtModbusTcpPortManager::sendData(), mdtPortManager::sendData(), setId(), and mdtPortManager::transactionDone().
int mdtPortTransaction::ioCount () const
Get the number of I/Os concerned by transaction.
Definition at line 146 of file mdtPortTransaction.cpp.
Referenced by mdtDeviceModbus::readAnalogInputs(), mdtDeviceModbus::readAnalogOutputs(), mdtDeviceModbus::readDigitalInputs(), and mdtDeviceModbus::readDigitalOutputs().
bool mdtPortTransaction::isInput () const
Get the isInput flag.
Definition at line 100 of file mdtPortTransaction.cpp.
Referenced by setIo(), and setIsInput().
bool mdtPortTransaction::isOutput () const
Get the isOutput flag.
Definition at line 105 of file mdtPortTransaction.cpp.
bool mdtPortTransaction::isQueryReplyMode () const
Get the query/reply mode flag.
See setQueryReplyMode() for details.
Definition at line 126 of file mdtPortTransaction.cpp.
Referenced by mdtPortManager::commitFrames().
void mdtPortTransaction::setAddress (int address)
Set address.
Definition at line 131 of file mdtPortTransaction.cpp.
References address().
Referenced by mdtMultiIoDevice::getAnalogInputs(), mdtMultiIoDevice::getAnalogInputValue(), mdtMultiIoDevice::getAnalogOutputs(), mdtMultiIoDevice::getAnalogOutputValue(), mdtMultiIoDevice::getDigitalInputs(), mdtMultiIoDevice::getDigitalInputValue(), mdtMultiIoDevice::getDigitalOutputs(), mdtMultiIoDevice::getDigitalOutputValue(), mdtMultiIoDevice::setAnalogOutputs(), mdtMultiIoDevice::setAnalogOutputValue(), mdtMultiIoDevice::setDigitalOutputs(), and mdtMultiIoDevice::setDigitalOutputValue().
void mdtPortTransaction::setData (const QByteArray & data)
Set data by copy.
Definition at line 110 of file mdtPortTransaction.cpp.
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), mdtPortManager::fromThreadNewFrameReaden(), mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtModbusTcpPortManager::getRegisterValues(), mdtDeviceModbus::readAnalogInput(), mdtDeviceModbus::readAnalogInputs(), mdtDeviceModbus::readAnalogOutput(), mdtDeviceModbus::readAnalogOutputs(), mdtDeviceModbus::readDigitalInput(), mdtDeviceModbus::readDigitalInputs(), mdtDeviceModbus::readDigitalOutput(), mdtDeviceModbus::readDigitalOutputs(), mdtModbusTcpPortManager::sendData(), mdtPortManager::sendData(), mdtModbusTcpPortManager::setRegisterValues(), mdtDeviceModbus::writeAnalogOutput(), mdtDeviceModbus::writeAnalogOutputs(), mdtDeviceModbus::writeDigitalOutput(), and mdtDeviceModbus::writeDigitalOutputs().
void mdtPortTransaction::setId (int id)
Set transaction identifer.
Depending used protocol, id can be a transaction ID as defined in MODBUS/TCP, a bTag used in USBTMC or what else.
Definition at line 46 of file mdtPortTransaction.cpp.
References id().
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), mdtPortManager::fromThreadNewFrameReaden(), mdtModbusTcpPortManager::sendData(), and mdtPortManager::sendData().
void mdtPortTransaction::setIo (mdtAnalogIo * io, bool isInput)
Set the concerned analog I/O.
If a query concerns a specific I/O, it's possible to reference the I/O object here.
Definition at line 66 of file mdtPortTransaction.cpp.
References isInput().
Referenced by mdtMultiIoDevice::getAnalogInputValue(), mdtMultiIoDevice::getAnalogOutputValue(), mdtMultiIoDevice::getDigitalInputValue(), mdtMultiIoDevice::getDigitalOutputValue(), mdtMultiIoDevice::setAnalogOutputValue(), and mdtMultiIoDevice::setDigitalOutputValue().
void mdtPortTransaction::setIo (mdtDigitalIo * io, bool isInput)
Set the concerned digital I/O.
If a query concerns a specific I/O, it's possible to reference the I/O object here.
Definition at line 75 of file mdtPortTransaction.cpp.
References isInput().
void mdtPortTransaction::setIoCount (int n)
Set the number of I/Os concerned by transaction.
Definition at line 141 of file mdtPortTransaction.cpp.
Referenced by mdtMultiIoDevice::getAnalogInputs(), mdtMultiIoDevice::getAnalogOutputs(), mdtMultiIoDevice::getDigitalInputs(), mdtMultiIoDevice::getDigitalOutputs(), mdtMultiIoDevice::setAnalogOutputs(), and mdtMultiIoDevice::setDigitalOutputs().
void mdtPortTransaction::setIsInput (bool isInput)
Set the isInput flag.
Definition at line 94 of file mdtPortTransaction.cpp.
References isInput().
void mdtPortTransaction::setQueryReplyMode (bool mode)
Set query/reply mode.
In query/reply mode, port manager will not remove frame from done transactions queue just after signal was emited, but keep it until a read was made.
See mdtPortManager for details.
Definition at line 121 of file mdtPortTransaction.cpp.
Referenced by mdtMultiIoDevice::getAnalogInputs(), mdtMultiIoDevice::getAnalogInputValue(), mdtMultiIoDevice::getAnalogOutputs(), mdtMultiIoDevice::getAnalogOutputValue(), mdtMultiIoDevice::getDigitalInputs(), mdtMultiIoDevice::getDigitalInputValue(), mdtMultiIoDevice::getDigitalOutputs(), mdtMultiIoDevice::getDigitalOutputValue(), mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtModbusTcpPortManager::getRegisterValues(), mdtModbusTcpPortManager::sendData(), mdtPortManager::sendData(), mdtMultiIoDevice::setAnalogOutputs(), mdtMultiIoDevice::setAnalogOutputValue(), mdtMultiIoDevice::setDigitalOutputs(), mdtMultiIoDevice::setDigitalOutputValue(), and mdtModbusTcpPortManager::setRegisterValues().
void mdtPortTransaction::setType (int type)
Set type.
A typical usage is SCPI query/request type. See mdtFrameCodecScpi for details.
Definition at line 56 of file mdtPortTransaction.cpp.
References type().
int mdtPortTransaction::type () const
Get type.
See setType() for details
Definition at line 61 of file mdtPortTransaction.cpp.
Referenced by setType().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortTransaction.h
src/mdtport/mdtPortTransaction.cpp