Multi diag tools: mdtPort Class Reference
mdtPort Class Reference
#include <mdtPort.h>
Public Member Functions
mdtPort (QObject *parent=0)
~mdtPort ()
void setReadTimeout (int timeout)
Set the read data timeout.
void setWriteTimeout (int timeout)
Set the write data timeout.
error_t waitForReadyRead ()
Wait until data is available on port.
qint64 read (char *data, qint64 maxSize)
Read data from port.
error_t waitEventWriteReady ()
Wait until data can be written to port.
qint64 write (const char *data, qint64 maxSize)
Write data to port.
Public Member Functions inherited from mdtAbstractPort
mdtAbstractPort (QObject *parent=0)
virtual ~mdtAbstractPort ()
Destructor.
void setPortName (const QString &portName)
Set the port name.
QString & portName ()
Get port name.
error_t open ()
Open the port given by setPortName()
bool isOpen () const
Get port's open state.
virtual void close ()
Close the port.
void setConfig (mdtPortConfig *cfg)
Set configuration.
mdtPortConfig & config ()
Get the stored configuration.
error_t setup ()
Setup port with given configurations.
virtual error_t reconnect (int timeout)
Reconnect device/peer.
error_t waitForReadyRead (int msecs)
Wait until data is available on port.
virtual bool suspendTransmission ()
Request to suspend transmission.
virtual bool resumeTransmission ()
Request to resume transmission.
void flushIn ()
Flush read buffers.
bool flushInRequestPending ()
Check if a flush in request is pending.
void flushOut ()
Flush write buffers.
bool flushOutRequestPending ()
Check if a flush out request is pending.
void flush ()
Flush read/write buffers.
void initQueues ()
Init the read ans write queues.
QQueue< mdtFrame * > & readenFrames ()
Get the readen frames Queue.
QQueue< mdtFrame * > & readFramesPool ()
Get the read frames Queue pool.
virtual void addFrameToWrite (mdtFrame *frame)
Add a frame to write.
mdtFrame * getFrameToWrite ()
Wait until a frame to write is available and get it.
void abortFrameToWriteWait ()
Abort the frame tp write waiting.
QQueue< mdtFrame * > & writeFrames ()
Get the write frames Queue.
QQueue< mdtFrame * > & writeFramesPool ()
Get the write frames Queue pool.
void lockMutex ()
Lock the mutex.
void unlockMutex ()
Unlock the mutex.
Additional Inherited Members
Public Types inherited from mdtAbstractPort
enum error_t {
NoError = 0, PortLocked = -1000, PortNotFound, PortAccess,
SetupError, WriteCanceled, ReadCanceled, ControlCanceled,
ReadTimeout, WriteTimeout, MessageInTimeout, MessageInCanceled,
ControlTimeout, Disconnected, Connecting, ConnectionFailed,
UnhandledError, ReadPoolEmpty, WritePoolEmpty, ErrorHandled,
ReadWriteBusy, UsbWriteStall, UsbReadStall
}
Error.
Protected Attributes inherited from mdtAbstractPort
QQueue< mdtFrame * > pvReadenFrames
QQueue< mdtFrame * > pvReadFramesPool
QQueue< mdtFrame * > pvWriteFrames
QQueue< mdtFrame * > pvWriteFramesPool
mdtPortConfig * pvConfig
QString pvPortName
QMutex pvMutex
QWaitCondition pvWriteFrameAvailable
Detailed Description
Definition at line 34 of file mdtPort.h.
Constructor & Destructor Documentation
mdtPort::mdtPort (QObject * parent = 0)
Definition at line 34 of file mdtPort.cpp.
mdtPort::~mdtPort ()
Definition at line 42 of file mdtPort.cpp.
References mdtAbstractPort::close().
Member Function Documentation
qint64 mdtPort::read (char * data, qint64 maxSize) virtual
Read data from port.
This method is called from mdtPortReadThread , and should not be used directly.
Implements mdtAbstractPort.
Definition at line 109 of file mdtPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractPort::ReadTimeout, and mdtError::setSystemError().
void mdtPort::setReadTimeout (int timeout) virtual
Set the read data timeout.
Implements mdtAbstractPort.
Definition at line 48 of file mdtPort.cpp.
void mdtPort::setWriteTimeout (int timeout) virtual
Set the write data timeout.
Implements mdtAbstractPort.
Definition at line 59 of file mdtPort.cpp.
mdtAbstractPort::error_t mdtPort::waitEventWriteReady () virtual
Wait until data can be written to port.
This method is called from mdtPortWriteThread , and should not be used directly.
Mutex must be locked before calling this method with lockMutex(). The mutex is locked when method returns.
Implements mdtAbstractPort.
Definition at line 135 of file mdtPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractPort::NoError, mdtAbstractPort::pvMutex, mdtError::setSystemError(), mdtAbstractPort::UnhandledError, mdtAbstractPort::WriteCanceled, and mdtAbstractPort::WriteTimeout.
mdtAbstractPort::error_t mdtPort::waitForReadyRead () virtual
Wait until data is available on port.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex must be locked before calling this method with lockMutex(). The mutex is locked when method returns.
Implements mdtAbstractPort.
Definition at line 70 of file mdtPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractPort::NoError, mdtAbstractPort::pvMutex, mdtAbstractPort::ReadCanceled, mdtAbstractPort::ReadTimeout, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
qint64 mdtPort::write (const char * data, qint64 maxSize) virtual
Write data to port.
This method is called from mdtPortWriteThread , and should not be used directly. Mutex is not handled by this method.
Implements mdtAbstractPort.
Definition at line 174 of file mdtPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, and mdtError::setSystemError().
The documentation for this class was generated from the following files:
src/mdtport/linux/mdtPort.h
src/mdtport/linux/mdtPort.cpp