Multi diag tools: mdtUsbDeviceList Class Reference
mdtUsbDeviceList Class Reference
Helper class to enumerate and search USB devices that are attached on system.
#include <mdtUsbDeviceList.h>
Public Member Functions
mdtUsbDeviceList (libusb_context *ctx)
Constructor.
~mdtUsbDeviceList ()
Destructor.
bool scan ()
Enumerate any attached USB devices.
QList< mdtUsbDeviceDescriptor > deviceList () const
Get devices descriptors list.
QList< mdtUsbDeviceDescriptor > deviceList (uint8_t bDeviceClass, uint8_t bDeviceSubClass, uint8_t bDeviceProtocol) const
Get a list of devices of given class, sub class and protocol.
QList< mdtUsbDeviceDescriptor > usbtmcDeviceList () const
Get a list of attached USBTMC devices.
mdtUsbDeviceDescriptor findDevice (uint16_t idVendor, uint16_t idProduct, const QString &serialNumber=QString())
Find a device with given vendor ID, product ID and serial number if not empty.
mdtUsbDeviceDescriptor findFirstUsbtmcDevice () const
Get first device that is a USBTMC device.
void clear ()
Clear.
mdtError lastError () const
Open a device with given vendor ID, product ID and serial number if not empty.
Detailed Description
Helper class to enumerate and search USB devices that are attached on system.
Finding and opening a device can be done in several steps:
Build a list of attached devices by using scan()
Find interresting device with findDevice()
Setup system based on returned device descriptor (interfaces, endpoints, ...)
Open device with its mdtUsbDeviceDescriptor::open() function
Clear search result with clear()
Definition at line 39 of file mdtUsbDeviceList.h.
Constructor & Destructor Documentation
mdtUsbDeviceList::mdtUsbDeviceList (libusb_context * ctx)
Constructor.
Given contex must be initialized (see libusb_init()).
Definition at line 27 of file mdtUsbDeviceList.cpp.
mdtUsbDeviceList::~mdtUsbDeviceList ()
Destructor.
Todo:
Comment about to get device handle before this class dies.
Definition at line 33 of file mdtUsbDeviceList.cpp.
References clear().
Member Function Documentation
void mdtUsbDeviceList::clear ()
Clear.
Will clear devices list and call freeLibusbDeviceList()
Definition at line 129 of file mdtUsbDeviceList.cpp.
Referenced by findDevice(), mdtUsbtmcPort::openDevice(), scan(), mdtUsbtmcPort::scan(), and ~mdtUsbDeviceList().
QList<mdtUsbDeviceDescriptor> mdtUsbDeviceList::deviceList () const inline
Get devices descriptors list.
Will contain valid result after successfull scan.
Definition at line 63 of file mdtUsbDeviceList.h.
Referenced by usbtmcDeviceList().
QList< mdtUsbDeviceDescriptor > mdtUsbDeviceList::deviceList (uint8_t bDeviceClass, uint8_t bDeviceSubClass, uint8_t bDeviceProtocol) const
Get a list of devices of given class, sub class and protocol.
Definition at line 48 of file mdtUsbDeviceList.cpp.
mdtUsbDeviceDescriptor mdtUsbDeviceList::findDevice (uint16_t idVendor, uint16_t idProduct, const QString & serialNumber = QString())
Find a device with given vendor ID, product ID and serial number if not empty.
Note: serial number is not requeired for all class/subclass. For USBTMC, it is required (see USBTMC 1.0 spec, chap. 5.1)
Returns
A valid device descriptor on success, or a empty one on failure (use lastError() on this case).
Definition at line 76 of file mdtUsbDeviceList.cpp.
References clear(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and mdtError::setError().
Referenced by mdtUsbtmcPort::openDevice().
mdtUsbDeviceDescriptor mdtUsbDeviceList::findFirstUsbtmcDevice () const
Get first device that is a USBTMC device.
This function is mostly used by unit testing.
Definition at line 117 of file mdtUsbDeviceList.cpp.
References usbtmcDeviceList().
mdtError mdtUsbDeviceList::lastError () const inline
Open a device with given vendor ID, product ID and serial number if not empty.
Note: serial number is not requeired for all class/subclass. For USBTMC, it is required (see USBTMC 1.0 spec, chap. 5.1)
Returns
A valid handle on success, or a null pointer on error (on failure, use lastError()). Note: caller is responsible to free the handle with libusb_close() once not longer used.libusb_device_handle *openDevice(uint16_t idVendor, uint16_t idProduct, const QString & serialNumber = QString());
Get last error
Definition at line 111 of file mdtUsbDeviceList.h.
Referenced by mdtUsbtmcPort::openDevice(), and mdtUsbtmcPort::scan().
bool mdtUsbDeviceList::scan ()
Enumerate any attached USB devices.
Definition at line 38 of file mdtUsbDeviceList.cpp.
References clear().
Referenced by mdtUsbtmcPort::openDevice(), and mdtUsbtmcPort::scan().
QList< mdtUsbDeviceDescriptor > mdtUsbDeviceList::usbtmcDeviceList () const
Get a list of attached USBTMC devices.
Definition at line 61 of file mdtUsbDeviceList.cpp.
References deviceList().
Referenced by findFirstUsbtmcDevice(), and mdtUsbtmcPort::scan().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbDeviceList.h
src/mdtport/mdtUsbDeviceList.cpp