Multi diag tools: mdtUsbtmcInterruptTransfer Class Reference
mdtUsbtmcInterruptTransfer Class Reference
USBTMC interrupt transfer.
#include <mdtUsbtmcInterruptTransfer.h>
Public Types
enum bNotify1Format_t : uint8_t { bNotify1Format_t::Subclass = 2, bNotify1Format_t::VendorSpecific = 1, bNotify1Format_t::Usbtmc = 0 }
Format.
Public Member Functions
mdtUsbtmcInterruptTransfer (mdtUsbtmcTransferHandler &th, mdtUsbEndpointDescriptor endpointDescriptor, libusb_device_handle *dev_handle, int bufferSize=1024)
Constructor.
mdtUsbtmcInterruptTransfer (const mdtUsbtmcInterruptTransfer &rhs)=delete
mdtUsbtmcInterruptTransfer & operator= (const mdtUsbtmcInterruptTransfer &rhs)=delete
void setup (unsigned int timeout)
Setup transfer.
bNotify1Format_t bNotify1Format () const
Get bNotify1 format.
void setByteValue (unsigned int offset, uint8_t value)
Set value at offset.
uint8_t byteValue (unsigned int offset) const
Get value at offset.
mdtUsbtmcTransferHandler & transferHandler ()
Get transfer handler.
Public Member Functions inherited from mdtUsbTransfer
mdtUsbTransfer (libusb_device_handle *dev_handle, int isoPacketsCount=0)
Constructor.
~mdtUsbTransfer ()
Destructor.
mdtUsbTransfer (const mdtUsbTransfer &rhs)=delete
mdtUsbTransfer & operator= (const mdtUsbTransfer &rhs)=delete
bool allocOk () const
Check that allocation not failed.
uint8_t flags () const
Get transfer flags.
bool submit (bool sync=false)
Submit transfer.
bool cancel (bool sync=false)
Cancel transfer.
libusb_transfer_status status () const
Get transfer status.
int actualLength () const
Get actual length.
unsigned int timeout () const
Get timeout that was given to transfer.
mdtError lastError () const
Get last error.
bool isSync () const
Check if transfer is a synchronous transfer.
int * completedPointer ()
Access completed flag.
void setCompleted ()
Set completed flag.
bool isCompleted () const
Check completed flag.
Additional Inherited Members
Protected Member Functions inherited from mdtUsbTransfer
libusb_device_handle * deviceHandle ()
Get device handle.
libusb_transfer * transfer ()
Access libusb transfer.
Detailed Description
USBTMC interrupt transfer.
See USBTMC 1.0 specifications, section 3.4 and USBTMC-USB488 1.0 specifications, section 3.4
Definition at line 37 of file mdtUsbtmcInterruptTransfer.h.
Member Enumeration Documentation
enum mdtUsbtmcInterruptTransfer::bNotify1Format_t : uint8_t strong
Format.
Represents bits D7 and D6 in bNotify1 field.
See USBTMC 1.0 specifications, section 3.4, table 13 and USBTMC-USB488 1.0 specifications, section 3.4
Enumerator
Subclass
Defined in applicable subclass
VendorSpecific
Vendor specific format
Usbtmc
Reserved for USBTMC use
Definition at line 48 of file mdtUsbtmcInterruptTransfer.h.
Constructor & Destructor Documentation
mdtUsbtmcInterruptTransfer::mdtUsbtmcInterruptTransfer (mdtUsbtmcTransferHandler & th, mdtUsbEndpointDescriptor endpointDescriptor, libusb_device_handle * dev_handle, int bufferSize = 1024)
Constructor.
Todo:
Check for a realistic bufferSize
Parameters
th Transfer handler
endpointDescriptor Endpoint descriptor
dev_handle A handle to a open device
bufferSize Internal buffer size.
Precondition
endpointDescriptor must not be empty
Definition at line 24 of file mdtUsbtmcInterruptTransfer.cpp.
References mdtUsbEndpointDescriptor::isEmpty().
mdtUsbtmcInterruptTransfer::mdtUsbtmcInterruptTransfer (const mdtUsbtmcInterruptTransfer & rhs) delete
Member Function Documentation
bNotify1Format_t mdtUsbtmcInterruptTransfer::bNotify1Format () const inline
Get bNotify1 format.
Definition at line 77 of file mdtUsbtmcInterruptTransfer.h.
References Subclass.
uint8_t mdtUsbtmcInterruptTransfer::byteValue (unsigned int offset) const inline
Get value at offset.
Precondition
offset must be < internal buffer's capacity
Definition at line 101 of file mdtUsbtmcInterruptTransfer.h.
Referenced by mdtUsbtmcTransferHandler::handleInterruptInTransferComplete().
mdtUsbtmcInterruptTransfer& mdtUsbtmcInterruptTransfer::operator= (const mdtUsbtmcInterruptTransfer & rhs) delete
void mdtUsbtmcInterruptTransfer::setByteValue (unsigned int offset, uint8_t value) inline
Set value at offset.
Precondition
offset must be < internal buffer's capacity
Definition at line 91 of file mdtUsbtmcInterruptTransfer.h.
void mdtUsbtmcInterruptTransfer::setup (unsigned int timeout)
Setup transfer.
Definition at line 34 of file mdtUsbtmcInterruptTransfer.cpp.
References mdtUsbEndpointDescriptor::address(), mdtUsbTransfer::deviceHandle(), mdtUsbtmcTransferHandler::interruptInTransferCallback(), and mdtUsbTransfer::transfer().
Referenced by mdtUsbtmcTransferHandler::submitInterruptInTransfer().
mdtUsbtmcTransferHandler& mdtUsbtmcInterruptTransfer::transferHandler () inline
Get transfer handler.
Definition at line 109 of file mdtUsbtmcInterruptTransfer.h.
Referenced by mdtUsbtmcTransferHandler::interruptInTransferCallback().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbtmcInterruptTransfer.h
src/mdtport/mdtUsbtmcInterruptTransfer.cpp