Multi diag tools: mdtTtLogicalTestCableDutWidget Class Reference
mdtTtLogicalTestCableDutWidget Class Reference
Helper class for logical test cable generation.
#include <mdtTtLogicalTestCableDutWidget.h>
Public Member Functions
mdtTtLogicalTestCableDutWidget (QWidget *parent, QSqlDatabase db)
Constructor.
void setTestCableConnector (const QVariant &connectorId, const QString &name)
Set test cable connector.
void setTestCableConnection (const QVariant &connectionId, const QString &name)
Set test cable connection.
void setDutUnit (const QVariant &unitId)
Set DUT unit.
mdtTtLogicalTestCableDialog::cnType_t cnType () const
Get cn type.
QVariant cnId () const
Get cn ID.
QString testCableCnName () const
Get test cable cn name.
bool containsTestCableConnection (const QVariant &testCableConnectionId, bool &ok)
Check if this affectation contains given (physical) test cable connection.
QList< QVariant > getAffectedDutConnections (bool &ok)
Get list of unit connections.
Detailed Description
Helper class for logical test cable generation.
Definition at line 35 of file mdtTtLogicalTestCableDutWidget.h.
Constructor & Destructor Documentation
mdtTtLogicalTestCableDutWidget::mdtTtLogicalTestCableDutWidget (QWidget * parent, QSqlDatabase db)
Constructor.
Definition at line 35 of file mdtTtLogicalTestCableDutWidget.cpp.
Member Function Documentation
QVariant mdtTtLogicalTestCableDutWidget::cnId () const inline
Get cn ID.
Definition at line 66 of file mdtTtLogicalTestCableDutWidget.h.
mdtTtLogicalTestCableDialog::cnType_t mdtTtLogicalTestCableDutWidget::cnType () const inline
Get cn type.
Definition at line 59 of file mdtTtLogicalTestCableDutWidget.h.
bool mdtTtLogicalTestCableDutWidget::containsTestCableConnection (const QVariant & testCableConnectionId, bool & ok)
Check if this affectation contains given (physical) test cable connection.
Definition at line 93 of file mdtTtLogicalTestCableDutWidget.cpp.
References mdtTtLogicalTestCableDialog::Connection, mdtTtLogicalTestCableDialog::Connector, mdtTtBase::getDataList(), and mdtTtBase::lastError().
QList< QVariant > mdtTtLogicalTestCableDutWidget::getAffectedDutConnections (bool & ok)
Get list of unit connections.
If affectation's type is a connector, all connections that are part of affected DUT connector will be returned. If affectation's type is a connection, DUT affected connection will be returned.
Definition at line 122 of file mdtTtLogicalTestCableDutWidget.cpp.
References mdtTtLogicalTestCableDialog::Connection, mdtTtLogicalTestCableDialog::Connector, mdtTtBase::getDataList(), and mdtTtBase::lastError().
void mdtTtLogicalTestCableDutWidget::setDutUnit (const QVariant & unitId)
Set DUT unit.
Definition at line 65 of file mdtTtLogicalTestCableDutWidget.cpp.
References mdtTtBase::getDataList().
void mdtTtLogicalTestCableDutWidget::setTestCableConnection (const QVariant & connectionId, const QString & name)
Set test cable connection.
Definition at line 56 of file mdtTtLogicalTestCableDutWidget.cpp.
References mdtTtLogicalTestCableDialog::Connection.
Referenced by mdtTtLogicalTestCableDialog::setTestCable().
void mdtTtLogicalTestCableDutWidget::setTestCableConnector (const QVariant & connectorId, const QString & name)
Set test cable connector.
Definition at line 47 of file mdtTtLogicalTestCableDutWidget.cpp.
References mdtTtLogicalTestCableDialog::Connector.
Referenced by mdtTtLogicalTestCableDialog::setTestCable().
QString mdtTtLogicalTestCableDutWidget::testCableCnName () const inline
Get test cable cn name.
Definition at line 72 of file mdtTtLogicalTestCableDutWidget.h.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtLogicalTestCableDutWidget.h
src/mdttools/mdttesttool/mdtTtLogicalTestCableDutWidget.cpp