Multi diag tools: mdtPortManager Class Reference
mdtPortManager Class Reference
Port manager base class.
#include <mdtPortManager.h>
Public Types
enum state_t {
PortClosed = 0, Stopped, Starting, Stopping,
Running, PortError, PortReady, Disconnected,
Connecting, Connected, Ready, Busy
}
State of device.
Public Slots
virtual void abort ()
Cancel read and write operations.
Signals
void newTransactionDone (mdtPortTransaction *transaction)
Emitted each time a transaction is done.
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
void stateChanged (int stateId)
Emitted each time the state changed.
void stateChangedForUi (int stateId, const QString &stateText, int ledColorId, bool ledIsOn)
Emitted only if a state that must be notified is entered.
void pmPortClosedEvent ()
Sent when port was closed.
void pmStartThreadsEvent ()
Sent when threads must be started.
void pmStopThreadsEvent ()
Sent when threads must be stopped.
void pmAllThreadsReadyEvent ()
Sent when all threads are ready.
void pmAllThreadsStoppedEvent ()
Sent when all threads are stopped.
void pmUnhandledErrorEvent ()
Sent when a unhandled error occured.
void pmConnectingEvent ()
Sent when connection with device beginns.
void pmConnectedEvent ()
Sent when connection with device is established.
void pmDisconnectedEvent ()
Sent when connection with device was lost/closed.
void pmConnectionFailedEvent ()
Sent when connection failed on startup or after max try.
void pmBusyEvent ()
Sent when device is busy (or other slow down reason..)
void pmReadyEvent ()
Sent when device and communication becomes ready again.
void pmTransactionTimeoutEvent ()
Sent when a transaction timeout occured.
Public Member Functions
mdtPortManager (QObject *parent=0)
Contruct a port manager.
virtual ~mdtPortManager ()
Destructor.
virtual void setPort (mdtAbstractPort *port)
Scan for available ports.
void lockPortMutex ()
Lock the port's mutex.
void unlockPortMutex ()
Unlock port's mutex.
void detachPort (bool deletePort, bool deleteThreads)
Detach port.
void addThread (mdtPortThread *thread)
Add a thread and assign it to port.
mdtPortThread * readThread ()
Returns instance of reader thread.
mdtPortThread * writeThread ()
Returns instance of writer thread.
void removeThreads (bool releaseMemory)
Detach threads from port and remove threads.
virtual bool start ()
Start port manager.
void stop ()
Stop port manager.
void setPortName (const QString &portName)
Set port name.
void setPortInfo (mdtPortInfo info)
Set port info.
mdtPortInfo portInfo ()
Get current port info.
QString portName () const
Get current port name.
virtual mdtPortConfig & config ()
Get the port's config object.
mdtPortConfig & config () const
Get the port's config object.
void setKeepTransactionsDone (bool keep)
Force transactions done to be keeped.
bool keepTransactionsDone () const
Get the keepTransactionsDone flag.
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
virtual int sendData (mdtPortTransaction *transaction)
Send data on port.
virtual int sendData (const QByteArray &data, bool queryReplyMode=false)
Send data to port.
bool waitTransactionDone (int id)
Wait until a transaction is done.
bool waitOneTransactionDone ()
Wait until current transaction is done.
void wait (int ms)
Wait for some time.
QByteArray readenFrame (int id)
Get data by frame ID.
QList< QByteArray > readenFrames ()
Get all readen data.
virtual void flushIn (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush input buffers.
void flushIn ()
Flush input buffers.
virtual void flushOut (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush output buffers.
void flushOut ()
Flush output buffers.
void flush (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush I/O buffers.
void flush ()
Flush I/O buffers.
state_t currentState () const
Get current state.
void notifyCurrentState ()
Notify the current state.
virtual bool isReady () const
Check if port manager is ready.
bool isClosed () const
Check if port is closed.
mdtError lastError () const
Get last error.
Protected Slots
virtual void fromThreadNewFrameReaden ()
Called by the read thread whenn a complete frame was readen.
virtual void onThreadsErrorOccured (int error)
Manage errors comming from port threads.
Protected Member Functions
virtual bool openPort ()
Open the port.
void closePort ()
Close the port.
void setCurrentTransactionId (int id)
Set the current transaction ID.
int currentTransactionId () const
Get the current transaction ID.
void incrementCurrentTransactionId (int min=0, int max=INT_MAX)
Increment current transaction ID.
bool waitTransactionPossible ()
Wait until transaction pending queue has less than maximum possible items.
void addTransactionPending (mdtPortTransaction *transaction)
Add a transaction to pending queue.
mdtPortTransaction * transactionPending (int id)
Take pending transaction matching id.
void flushTransactionsPending ()
Restore all transactions pending to pool.
void addTransactionDone (mdtPortTransaction *transaction)
Add a transaction to the DONE queue.
bool transactionsDoneContains (int id) const
Check if a transaction with given ID exists in done queue.
mdtPortTransaction * transactionDone (int id)
Take transaction from DONE queue matching id.
void flushTransactionsDone ()
Restore all transactions done to pool.
void startTransactionTimer (int timeout)
Start transaction timer.
void stopTransactionTimer ()
Stop transaction timer.
bool transactionTimeoutOccured () const
Check if a transaction timeout occured.
void commitFrames ()
Emit signals for each done transactions.
Protected Attributes
mdtError pvLastError
Last error object.
mdtAbstractPort * pvPort
QList< mdtPortThread * > pvThreads
Detailed Description
Port manager base class.
Todo:
Port manager has no raison to inherit QThread -> make it inherit QObject
Manages a port based on mdtAbstractPort an several threads based on mdtPortThread. The goal is to hide the complexity of the port API.
Example:
mdtPortManager m;
mdtPort *port;
mdtPortConfig *config;
QList<QByteArray> responses;
// Setup
config = new mdtPortConfig;
config->setFrameType(mdtFrame::FT_ASCII);
config->setEndOfFrameSeq("$");
// Init port
port = new mdtPort;
port->setConfig(config);
// Init port manager - We wand blocking mode
m.setTransactionsDisabled(true);
m.setPort(port);
m.addThread(mew mdtPortWriteThread);
m.addThread(mew mdtPortReadThread);
m.setPortName("/dev/xyz"));
// Start port manager - Will open port, start threads and return once port manager is ready
if(!m.start()){
 // Handle error
}
// Send some data
if(!m.writeData("Test$")){
 // Handle error
}
// Wait on answer - Timout: 1500 [ms]
if(!m.waitReadenFrame(1500)){
 // Timout , handle error
}
// Do something with received data
responses = m.readenFrames();
for(int i=0; i<responses.size(); i++){
 qDebug() << responses.at(i);
}
// Stop port manager
m.stop();
// Cleanup - detachPort() will delete port and threads objects
m.detachPort(true, true);
delete config;
A (recommended) alternative is to disable frames enqueuing and use the newReadenFrame(QByteArray) signal.
Disable enqueuing with setTransactionsDisabled(false)
Connect newReadenFrame(QByteArray) to a slot
Manage a port based on mdtAbstractPort and related threads. Goal is to hide complexity of mdtAbstractPort API.
Depending on application, it's possible to use a event approach, or also a blocking approach with wait methods.
Some protocols support frame identifier (like MODBUS/TCP, USBTMC, or others), and other don't (for example raw bytes transfert on a serial port). For this reason, the concept of transactions is aodpted here. A transaction is based on mdtPortTransaction class. It was introduced for protocols that support identification, and can store some other meta data, usefull to decode a reply.
This base class can be used directly for ports that supports raw transfers. For specific protocol, it can be subclassed.
Todo:
Document init, open, close, ...
Now, we can see the data transfer workflow:
1) Wait until it's possible to send some data with waitOnWriteReady()
2) Get a new transaction with getNewTransaction() , and setup it as needed (see remarks below).
3) Send data using writeData(mdtPortTransaction*). This will set the currentTransactionId to the ID given in transaction.
4a) If you choosed a blocking approach, use waitTransactionDone().
4b) If you choosed a event approach, connect the transactionDone() signal to a slot. Each time a transaction is done, you will receive a transaction.
5) Get the transaction with transactionDone().
6) Restore transaction with restoreTransaction().
Steps 2) and 3) can be done once by using writeData(const QByteArray&, bool). Steps 5) and 6) can be done once by using getReadenData(int).
Here is a little example of the simple approach:
mdtPortManager m;
int transactionId;
// Setup...
// Wait until we can write
if(!waitOnWriteReady()){
  // Handle error
}
// Send data to port
transactionId = writeData("SomeData", true);
if(transactionId < 0){
  // Handle error
}
// Wait until data come in
if(waitTransactionDone(transactionId)){
  // Handle error
}
// Get only data for a specific transaction (should be used only for protocols that support transaction)
qDebug() << readenFrame(transactionId);
// Get all received data
qDebug() << readenFrames();
Internally, once data was send to port's write queue, the transaction is stored in the pending transactions queue.
Dealing with incomming data: In above example, 2 methods are shown to get incomming data:
readenFrame(int) : will work with protocols that support frame ID. See specific port manager subclass for details.
readenFrames() : see below.
If we are using a protocol that not support frame ID, it's possible that we receive data each time, also without sending any request. This must be handled in fromThreadNewFrameReaden() slot. In this mdtPortManager class, the following will happen:
When sending data with writeData(const QByteArray&, bool), current transaction ID will be incremented with incrementCurrentTransactionId().
In fromThreadNewFrameReaden() slot, currentTransactionId() is used to get pending transaction with transactionPending(). If it was found, frame's data is copied, and transaction is moved to done queue. If not found, a new transaction is taken with getNewTransaction(), frame's data is copied, and transaction is enqueued to done queue with addTransactionDone().
readenFrames() will return a list of data that comes from transactions Done list. Current transaction ID will be restet to 0.
The Query/Reply mode: port manager is able to handle event or blocking mode in same time. This cause a problem for done transactions handling. For example, when we choosed the event based aproach for a transaction, port manager will emit the newTransactionDone(mdtPortTransaction*) signal, then restore transaction back to pool. When we choosed blocking approach, port manager will also emit newTransactionDone(mdtPortTransaction*) signal, wich can be usefull to keep, for example, a GUI coherent in each mode. But here, the transaction must not be restored directly, but only once data was readen with readenFrame() or readenFrames(). To handle this, commitFrames() will use mdtPortTransaction::isQueryReplyMode().
Definition at line 197 of file mdtPortManager.h.
Member Enumeration Documentation
enum mdtPortManager::state_t
State of device.
States are handled by mdtPortManagerStateMachine
Enumerator
PortClosed
Port is closed
Stopped
Threads are stopped and port is closing
Starting
Threads are starting
Stopping
Threads are stopping
Running
Global state (sub machine)
PortError
A unhandled error occured - Threads will be stopped and port closed
PortReady
Port is open and threads are running. At this point, communication is possible if not connection is required (f.ex. serial port terminal)
Disconnected
Port is ready, but not connected to device
Connecting
Trying to connect to device
Connected
Global state (sub machine)
Ready
Port is ready and connection to device was made. Communication is possible
Busy
Port is up and device is connected but cannot accept requests for the moment
Definition at line 207 of file mdtPortManager.h.
Constructor & Destructor Documentation
mdtPortManager::mdtPortManager (QObject * parent = 0)
Contruct a port manager.
keepTransactionsDone flag will be unset (set false).
Definition at line 32 of file mdtPortManager.cpp.
References mdtPortManagerStateMachine::buildMainStateMachine(), pmTransactionTimeoutEvent(), pvPort, and setKeepTransactionsDone().
mdtPortManager::~mdtPortManager () virtual
Destructor.
If a port was set, the manager will stop (if running), and port will be closed (if open).
Note that port set by setPort() and threads are not deleted. This is because port and threads are set by subclass, or from application.
Definition at line 59 of file mdtPortManager.cpp.
References pvPort, and stop().
Member Function Documentation
void mdtPortManager::abort () virtual slot
Cancel read and write operations.
Default implementation calls mdtAbstractPort::flush().
Definition at line 598 of file mdtPortManager.cpp.
References mdtAbstractPort::flush(), and pvPort.
void mdtPortManager::addThread (mdtPortThread * thread)
Add a thread and assign it to port.
Precondition
Port must be set with setPort before using this method
Manager must no running
Port manager must be closed (see isClosed()).
Definition at line 124 of file mdtPortManager.cpp.
References fromThreadNewFrameReaden(), mdtPortThread::handlesTimeout(), isClosed(), mdtPortThread::isReader(), mdtPortThread::isWriter(), onThreadsErrorOccured(), pmConnectedEvent(), pvPort, pvThreads, and mdtPortThread::setPort().
Referenced by mdtModbusTcpPortManager::mdtModbusTcpPortManager(), and mdtSerialPortManager::mdtSerialPortManager().
void mdtPortManager::addTransactionDone (mdtPortTransaction * transaction) protected
Add a transaction to the DONE queue.
Precondition
transaction must be a valid pointer.
Definition at line 722 of file mdtPortManager.cpp.
References mdtPortTransaction::id(), and transactionsDoneContains().
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), and fromThreadNewFrameReaden().
void mdtPortManager::addTransactionPending (mdtPortTransaction * transaction) protected
Add a transaction to pending queue.
Add a existing transaction to the pending queue. A transaction can be requested with getNewTransaction().
Precondition
transaction must be a valid pointer.
transaction ID must not allready exist in queue.
Definition at line 677 of file mdtPortManager.cpp.
References mdtError::commit(), mdtError::Error, mdtPortTransaction::id(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, and pmUnhandledErrorEvent().
Referenced by mdtModbusTcpPortManager::sendData(), and sendData().
void mdtPortManager::closePort () protected
Close the port.
If port was never set (with setPort()), this method does nothing.
Definition at line 620 of file mdtPortManager.cpp.
References mdtAbstractPort::close(), flushTransactionsDone(), flushTransactionsPending(), and pvPort.
Referenced by stop().
void mdtPortManager::commitFrames () protected
Emit signals for each done transactions.
Will emit newTransactionDone(mdtPortTransaction*) for each transaction found in done queue.
If queryReplyMode and keepTransactionsDone are not set, the transaction is restored back to pool, else it will be restored only after a call of readenFrame() or readenFrames().
Definition at line 793 of file mdtPortManager.cpp.
References mdtPortTransaction::isQueryReplyMode(), keepTransactionsDone(), newTransactionDone(), and restoreTransaction().
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), and fromThreadNewFrameReaden().
mdtPortConfig & mdtPortManager::config () virtual
Get the port's config object.
Usefull to alter internal port configuration
Precondition
Port must be set with setPort() before use of this method.
Reimplemented in mdtSerialPortManager.
Definition at line 266 of file mdtPortManager.cpp.
References mdtAbstractPort::config(), and pvPort.
Referenced by mdtDeviceModbus::mdtDeviceModbus(), mdtModbusTcpPortManager::mdtModbusTcpPortManager(), openPort(), waitOneTransactionDone(), and waitTransactionDone().
mdtPortConfig & mdtPortManager::config () const
Get the port's config object.
Usefull to read internal port configuration
Precondition
Port must be set with setPort() before use of this method.
Definition at line 273 of file mdtPortManager.cpp.
References mdtAbstractPort::config(), and pvPort.
mdtPortManager::state_t mdtPortManager::currentState () const
Get current state.
Definition at line 570 of file mdtPortManager.cpp.
References mdtStateMachine::currentState().
Referenced by isClosed(), mdtModbusTcpPortManager::isReady(), isReady(), onThreadsErrorOccured(), start(), waitOneTransactionDone(), and waitTransactionDone().
int mdtPortManager::currentTransactionId () const protected
Get the current transaction ID.
Definition at line 638 of file mdtPortManager.cpp.
Referenced by fromThreadNewFrameReaden(), mdtModbusTcpPortManager::sendData(), and sendData().
void mdtPortManager::detachPort (bool deletePort, bool deleteThreads)
Detach port.
Will detach port from each thread and from port manager. If port was not set, this method does nothing. If manager is running, it will be stopped. If port is open, it will be closed.
Parameters
deletePort If true, the port object that was set with setPort() will be deleted.
deleteThreads If true, each thread added with addThread() will be deleted.
Definition at line 104 of file mdtPortManager.cpp.
References isClosed(), pvPort, removeThreads(), and stop().
Referenced by mdtModbusTcpPortManager::~mdtModbusTcpPortManager(), and mdtSerialPortManager::~mdtSerialPortManager().
void mdtPortManager::flush (bool flushPortManagerBuffers, bool flushPortBuffers)
Flush I/O buffers.
Parameters
flushPortManagerBuffers If true, port manager buffers will be cleared. (Has no effect in this implementation, but some subclass can have output buffers).
flushPortBuffers If true, port's buffers will be cleared.
Precondition
Port must be set with setPort() before calling this method.
Definition at line 554 of file mdtPortManager.cpp.
References mdtAbstractPort::flush(), flushIn(), flushOut(), and pvPort.
void mdtPortManager::flush ()
Flush I/O buffers.
Precondition
Port must be set with setPort() before calling this method.
Definition at line 565 of file mdtPortManager.cpp.
void mdtPortManager::flushIn (bool flushPortManagerBuffers, bool flushPortBuffers) virtual
Flush input buffers.
Parameters
flushPortManagerBuffers If true, port manager buffers (transactions done and pending) will be cleared.
flushPortBuffers If true, port's buffers will be cleared.
Precondition
Port must be set with setPort() before calling this method.
Definition at line 520 of file mdtPortManager.cpp.
References mdtAbstractPort::flushIn(), flushTransactionsDone(), flushTransactionsPending(), and pvPort.
void mdtPortManager::flushIn ()
Flush input buffers.
Will flush portmanger and port's buffers.
Internally, flushIn(bool, bool) is called.
Definition at line 537 of file mdtPortManager.cpp.
Referenced by flush().
void mdtPortManager::flushOut (bool flushPortManagerBuffers, bool flushPortBuffers) virtual
Flush output buffers.
Parameters
flushPortManagerBuffers If true, port manager buffers will be cleared. (Has no effect in this implementation, but some subclass can have output buffers).
flushPortBuffers If true, port's buffers will be cleared.
Precondition
Port must be set with setPort() before calling this method.
Definition at line 542 of file mdtPortManager.cpp.
References mdtAbstractPort::flushOut(), and pvPort.
void mdtPortManager::flushOut ()
Flush output buffers.
Will flush portmanger and port's buffers.
Internally, flushOut(bool, bool) is called.
Definition at line 549 of file mdtPortManager.cpp.
Referenced by flush().
void mdtPortManager::flushTransactionsDone () protected
Restore all transactions done to pool.
Definition at line 761 of file mdtPortManager.cpp.
References restoreTransaction().
Referenced by closePort(), flushIn(), and onThreadsErrorOccured().
void mdtPortManager::flushTransactionsPending () protected
Restore all transactions pending to pool.
Definition at line 708 of file mdtPortManager.cpp.
References restoreTransaction().
Referenced by closePort(), flushIn(), and onThreadsErrorOccured().
void mdtPortManager::fromThreadNewFrameReaden () protected virtual slot
Called by the read thread whenn a complete frame was readen.
This variant will add data to transactions done queue. If pending transactions queue contains currentTransactionId(), it will be removed.
For subclass that handle frames with IDs, this method must be reimplemented. The normal way is to get the frame in pending queue with transactionPending(). For frames with ID that not exists in pending queue, it must be choosen to discard them, or adopt another behaviour.
See Also
mdtPortThread
Todo:
A mditer:
Lock le mutex
Prendre les frames disponibles (-> sdans une liste ...)
Librer le mutex
Effectier les traitements
Lock le mutex
Restituer les frames
Librer le mutex
Definition at line 818 of file mdtPortManager.cpp.
References addTransactionDone(), mdtError::commit(), commitFrames(), currentTransactionId(), mdtError::Error, getNewTransaction(), mdtPortTransaction::id(), incrementCurrentTransactionId(), mdtFrame::isComplete(), lockPortMutex(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, pvPort, mdtAbstractPort::readenFrames(), mdtAbstractPort::readFramesPool(), mdtPortTransaction::setData(), mdtPortTransaction::setId(), transactionPending(), and unlockPortMutex().
Referenced by addThread(), and removeThreads().
mdtPortTransaction * mdtPortManager::getNewTransaction ()
Get a new transaction.
If transactions pool is empty, a new transaction is created. Note that each transaction should be put back in pool with restoreTransaction(). In most cases, if a method that uses transactions fails, the transaction must be restored with restoreTransaction(). See writeData(mdtPortTransaction*), writeData(const QByteArray&), flushTransactionsPending(), flushTransactionsDone(), readenFrame() and readenFrames() for details about restoration of transaction.
Returns
A empty transaction (mdtPortTransaction::clear() is called internally).
Postcondition
Returned transaction is valid (never Null).
Definition at line 290 of file mdtPortManager.cpp.
References mdtPortTransaction::clear(), mdtError::commit(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, and mdtError::Warning.
Referenced by fromThreadNewFrameReaden(), mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtMultiIoDevice::getNewTransaction(), mdtModbusTcpPortManager::getRegisterValues(), mdtModbusTcpPortManager::sendData(), sendData(), and mdtModbusTcpPortManager::setRegisterValues().
void mdtPortManager::incrementCurrentTransactionId (int min = 0, int max = INT_MAX) protected
Increment current transaction ID.
Definition at line 643 of file mdtPortManager.cpp.
Referenced by fromThreadNewFrameReaden(), mdtModbusTcpPortManager::sendData(), and sendData().
bool mdtPortManager::isClosed () const
Check if port is closed.
Returns true if threads are all stopped and port is closed
Definition at line 593 of file mdtPortManager.cpp.
References currentState(), and PortClosed.
Referenced by addThread(), mdtDeviceModbus::connectToDevice(), detachPort(), removeThreads(), mdtSerialPortManager::scan(), mdtModbusTcpPortManager::scan(), mdtModbusTcpPortManager::sendData(), sendData(), setPort(), setPortInfo(), setPortName(), start(), stop(), mdtModbusTcpPortManager::tryToConnect(), and waitTransactionPossible().
bool mdtPortManager::isReady () const virtual
Check if port manager is ready.
Internally, the currentState is used to check if port manager is ready. This implementation returns true if currentState is PortReady or Ready.
For some port type, it can be mandatory to be connected to device before any data can be transferred. In such case, reimplement this method.
Reimplemented in mdtModbusTcpPortManager.
Definition at line 584 of file mdtPortManager.cpp.
References currentState(), PortReady, and Ready.
Referenced by sendData(), start(), waitOneTransactionDone(), waitTransactionDone(), and waitTransactionPossible().
bool mdtPortManager::keepTransactionsDone () const
Get the keepTransactionsDone flag.
Definition at line 285 of file mdtPortManager.cpp.
Referenced by commitFrames().
mdtError mdtPortManager::lastError () const inline
Get last error.
Todo:
Not completly used currently, must be implemented in this class + subclasses .
Definition at line 631 of file mdtPortManager.h.
References pvLastError.
Referenced by mdtDeviceModbus::connectToDevice().
void mdtPortManager::lockPortMutex ()
Lock the port's mutex.
This method will check a internal flag before locking port's mutex. If the flag syas that mutex is allready locked, a warning is logged with mdtError system. Then, this method reurns without locking the port mutex again.
Precondition
Port must be set with setPort before using this method
Definition at line 82 of file mdtPortManager.cpp.
References mdtError::commit(), mdtAbstractPort::lockMutex(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, pvPort, and mdtError::Warning.
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), fromThreadNewFrameReaden(), mdtModbusTcpPortManager::sendData(), and sendData().
void mdtPortManager::newTransactionDone (mdtPortTransaction * transaction) signal
Emitted each time a transaction is done.
Note: the transaction pointer is only valid for one call, do not store it for later usage. Connect this signal to a slot that runs in GUI thread only.
This signal is emited by commitFrames().
Referenced by commitFrames().
void mdtPortManager::notifyCurrentState ()
Notify the current state.
Will force to emit stateChanged() and stateChangedForUi() .
Can be usefull during application setup, because some initial states (like PortClosed) are directly notified, probably before signals are connected to application slots.
Definition at line 577 of file mdtPortManager.cpp.
References mdtStateMachine::notifyCurrentState().
Referenced by mdtDeviceModbus::mdtDeviceModbus(), mdtModbusIoTool::mdtModbusIoTool(), and mdtAbstractPortSetupDialog::setPortManager().
void mdtPortManager::onThreadsErrorOccured (int error) protected virtual slot
Manage errors comming from port threads.
This implementation will handle some common errors, change the current state emiting transistion signal. If state has changed, stateChanged() signal is emited.
Handled errors are:
NoError: go to ready state.
WriteCanceled: flush pending transaction with flushTransactionsPending() and go to warning state.
WriteTimeout: flush pending transaction with flushTransactionsPending() and go to busy state.
WritePoolEmpty: go to busy state.
ReadCanceled: flush pending transaction with flushTransactionsPending(), done transactions with flushTransactionsDone() and go to warning state.
ReadTimeout: flush pending transaction with flushTransactionsPending(), done transactions with flushTransactionsDone() and go to busy state.
ReadPoolEmpty: go to busy state.
Disconnected: flush pending transaction with flushTransactionsPending(), done transactions with flushTransactionsDone() and go to disconnected state.
Connecting: go to connecting state.
For other errors, including UnhandledError, pending transactions are flushed with flushTransactionsPending(), done transactions are flushed with flushTransactionsDone() and state will become error state.
For other cases, the subclass can reimplement this method. Dont forget to emit transistion signals.
Definition at line 863 of file mdtPortManager.cpp.
References mdtAbstractPort::Connecting, mdtAbstractPort::ConnectionFailed, currentState(), mdtAbstractPort::Disconnected, flushTransactionsDone(), flushTransactionsPending(), mdtAbstractPort::NoError, pmBusyEvent(), pmConnectingEvent(), pmConnectionFailedEvent(), pmDisconnectedEvent(), pmReadyEvent(), pmTransactionTimeoutEvent(), pmUnhandledErrorEvent(), mdtAbstractPort::ReadCanceled, mdtAbstractPort::ReadPoolEmpty, mdtAbstractPort::ReadTimeout, mdtAbstractPort::ReadWriteBusy, mdtAbstractPort::WriteCanceled, mdtAbstractPort::WritePoolEmpty, and mdtAbstractPort::WriteTimeout.
Referenced by addThread(), and removeThreads().
bool mdtPortManager::openPort () protected virtual
Open the port.
Will try to open port defined with setPortName() or setPortInfo()
Returns
True on success, false else.
Precondition
Port must be set with setPort() before use of this method.
Todo:
Should return mdtAbstractPort::error_t
Definition at line 605 of file mdtPortManager.cpp.
References config(), mdtAbstractPort::NoError, pvPort, setCurrentTransactionId(), mdtAbstractPort::setup(), and mdtPortConfig::writeQueueSize().
Referenced by start().
void mdtPortManager::pmAllThreadsReadyEvent () signal
Sent when all threads are ready.
Used by state machine
void mdtPortManager::pmAllThreadsStoppedEvent () signal
Sent when all threads are stopped.
Used by state machine
void mdtPortManager::pmBusyEvent () signal
Sent when device is busy (or other slow down reason..)
Used by state machine
Referenced by onThreadsErrorOccured().
void mdtPortManager::pmConnectedEvent () signal
Sent when connection with device is established.
Used by state machine
Referenced by addThread(), and removeThreads().
void mdtPortManager::pmConnectingEvent () signal
Sent when connection with device beginns.
Used by state machine
Referenced by onThreadsErrorOccured().
void mdtPortManager::pmConnectionFailedEvent () signal
Sent when connection failed on startup or after max try.
Used by state machine
Referenced by onThreadsErrorOccured().
void mdtPortManager::pmDisconnectedEvent () signal
Sent when connection with device was lost/closed.
Used by state machine
Referenced by onThreadsErrorOccured().
void mdtPortManager::pmPortClosedEvent () signal
Sent when port was closed.
Used by state machine
Referenced by stop().
void mdtPortManager::pmReadyEvent () signal
Sent when device and communication becomes ready again.
Used by state machine
Referenced by onThreadsErrorOccured().
void mdtPortManager::pmStartThreadsEvent () signal
Sent when threads must be started.
Used by state machine
Referenced by start().
void mdtPortManager::pmStopThreadsEvent () signal
Sent when threads must be stopped.
Used by state machine
Referenced by stop().
void mdtPortManager::pmTransactionTimeoutEvent () signal
Sent when a transaction timeout occured.
A transaction timeout can be notified by a port thread, or/and internall transaction timer.
See Also
transactionTimeoutOccured()
onTransactionTimeoutOccured()
startTransactionTimer()
stopTransactionTimer()
Referenced by mdtPortManager(), and onThreadsErrorOccured().
void mdtPortManager::pmUnhandledErrorEvent () signal
Sent when a unhandled error occured.
Used by state machine
Referenced by addTransactionPending(), onThreadsErrorOccured(), and waitTransactionDone().
mdtPortInfo mdtPortManager::portInfo ()
Get current port info.
Definition at line 256 of file mdtPortManager.cpp.
Referenced by mdtSerialPortManager::scan().
QString mdtPortManager::portName () const
Get current port name.
Definition at line 261 of file mdtPortManager.cpp.
References mdtPortInfo::portName().
QByteArray mdtPortManager::readenFrame (int id)
Get data by frame ID.
The frame ID is a protocol specific identification. F.ex. in MODBUS/TCP, the transaction ID is used, or bTag for USBTMC.
If found, the frame is removed from done queue. (A second call with same ID will return a empty QByteArray).
If ID was not found, a empty QByteArray is returned.
Definition at line 490 of file mdtPortManager.cpp.
References mdtPortTransaction::data(), restoreTransaction(), and transactionDone().
Referenced by mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtModbusTcpPortManager::getRegisterValues(), mdtModbusTcpPortManager::setRegisterValues(), and mdtMultiIoDevice::waitTransactionDone().
QList< QByteArray > mdtPortManager::readenFrames ()
Get all readen data.
Note that calling this methode will clear the internal queue. (A second call will return a empty list).
Definition at line 503 of file mdtPortManager.cpp.
References mdtPortTransaction::data(), and restoreTransaction().
mdtPortThread * mdtPortManager::readThread ()
Returns instance of reader thread.
Note that a Null pointer can be returned
Definition at line 148 of file mdtPortManager.cpp.
void mdtPortManager::removeThreads (bool releaseMemory)
Detach threads from port and remove threads.
Parameters
releaseMemory If true, all threads are deleted
Precondition
Port manager must be closed (see isClosed()).
Definition at line 158 of file mdtPortManager.cpp.
References fromThreadNewFrameReaden(), isClosed(), mdtPortThread::isReader(), onThreadsErrorOccured(), pmConnectedEvent(), and pvThreads.
Referenced by detachPort().
void mdtPortManager::restoreTransaction (mdtPortTransaction * transaction)
Restore a transaction into pool.
Precondition
transaction must be a valid pointer (not Null)
One transaction must be commited once (avoid corrupted double free)
Definition at line 312 of file mdtPortManager.cpp.
Referenced by commitFrames(), flushTransactionsDone(), flushTransactionsPending(), readenFrame(), readenFrames(), mdtMultiIoDevice::restoreTransaction(), mdtModbusTcpPortManager::sendData(), and sendData().
int mdtPortManager::sendData (mdtPortTransaction * transaction) virtual
Send data on port.
At first, this method waits until the ready state is set calling isReady() , a frame is available in port's write frames pool, and until a transaction is possible (see waitTransactionPossible()). This wait will not break event loop, so no GUI freeze occurs. If port manager is stopped during this wait (unhandled error, stop request), this method returns.
Then, data contained in transaction will be passed to the mdtPort's write queue by copy. This method returns immediatly after enqueue, and don't wait until data was written.
Parameters
transaction Transaction used to send data. Following members are used by this method:
id : transaction will be added to pending transactions with this id, and currentTransactionId will be set with it.
data : will be sent to port.
isQueryReplyMode : if true, the transaction will be keeped in transactions done queue until readenFrame() or readenFrames() is called. Note: it's possible to force keeping all incomming data (wich also owerwrite this flag) by setting the global keepTransactionsDone flag.
Returns
Transaction ID on success or value < 0 on error. In this implementation, the only possible error is mdtAbstractPort::WriteCanceled, witch typically occurs when port manager stops. Some subclass can return a frame ID on success, or a other error. See subclass documentation for details. Note: on failure, the transaction is restored to pool.
Precondition
Port must be set with setPort() before use of this method.
transaction must be a valid pointer, and not allready exists in transactions pending or transactions done queue.
Subclass notes:
This method can be reimplemented in subclass if needed. Typically usefull if some encoding is needed before the frame is submitted to port. A frame must be taken from port's write frames pool with mdtAbstractPort::writeFramesPool() dequeue() method (see Qt's QQueue documentation for more details on dequeue()), then added to port's write queue with mdtAbstractPort::addFrameToWrite() . If protocol supports frame identification (like MODBUS's transaction ID or USBTMC's bTag), it should be returned here and incremented using incrementCurrentTransactionId().
Reimplemented in mdtModbusTcpPortManager.
Definition at line 321 of file mdtPortManager.cpp.
References mdtAbstractPort::addFrameToWrite(), addTransactionPending(), mdtFrame::clear(), mdtFrame::clearSub(), mdtPortTransaction::data(), mdtPortTransaction::id(), isClosed(), isReady(), lockPortMutex(), pvPort, restoreTransaction(), transactionsDoneContains(), unlockPortMutex(), waitTransactionPossible(), mdtAbstractPort::WriteCanceled, and mdtAbstractPort::writeFramesPool().
Referenced by mdtPortTerm::sendCommandToSerialPort(), and sendData().
int mdtPortManager::sendData (const QByteArray & data, bool queryReplyMode = false) virtual
Send data to port.
Will increment the current transaction ID, get a new transaction, setup it and finally send it with sendData(mdtPortTransaction*).
Parameters
data Data to write.
queryReplyMode If true, reply will be keeped in transactions done queue until readenFrame() or readenFrames() is called. If false, behaviour depends on keepTransactionsDone flag.
See Also
sendData(mdtPortTransaction*)
Reimplemented in mdtModbusTcpPortManager.
Definition at line 367 of file mdtPortManager.cpp.
References currentTransactionId(), getNewTransaction(), incrementCurrentTransactionId(), pvPort, sendData(), mdtPortTransaction::setData(), mdtPortTransaction::setId(), and mdtPortTransaction::setQueryReplyMode().
void mdtPortManager::setCurrentTransactionId (int id) protected
Set the current transaction ID.
Definition at line 633 of file mdtPortManager.cpp.
Referenced by openPort().
void mdtPortManager::setKeepTransactionsDone (bool keep)
Force transactions done to be keeped.
If keep is true, commitFrames() will ignore the mdtPortTransaction::isQueryReplyMode() and allways keep transactions in done queue until readenFrame() or readenFrames() is called.
Definition at line 280 of file mdtPortManager.cpp.
Referenced by mdtModbusTcpPortManager::mdtModbusTcpPortManager(), and mdtPortManager().
void mdtPortManager::setPort (mdtAbstractPort * port) virtual
Scan for available ports.
This method is implemented is port's specific subclass. Default implementation returns a empty list.
Note that returned list must be freed by user after usage. (for.ex. with qDeletAll() and QList::clear()).virtual QList<mdtPortInfo*> scan();
Set port object
Precondition
port must be a valid pointer to the expected class instance (for ex: mdtSerialPort).
Port manager must be closed (see isClosed()).
QList<mdtPortInfo*> mdtPortManager::scan() { return QList<mdtPortInfo*>(); }
Definition at line 74 of file mdtPortManager.cpp.
References isClosed(), and pvPort.
Referenced by mdtModbusTcpPortManager::mdtModbusTcpPortManager(), and mdtSerialPortManager::mdtSerialPortManager().
void mdtPortManager::setPortInfo (mdtPortInfo info)
Set port info.
Store given port info, and set port name to internall port object. (see mdtPortInfo::portName()).
Setting a port info can be usefull if other informations are needed later in application (f.ex. mdtPortInfo::displayText()). You can get port informations later with portInfo().
Precondition
Port must be set before with setPort()
Port manager must be closed (see isClosed()).
Definition at line 247 of file mdtPortManager.cpp.
References isClosed(), mdtPortInfo::portName(), pvPort, and mdtAbstractPort::setPortName().
void mdtPortManager::setPortName (const QString & portName)
Set port name.
Set the port name to internally port object. Does nothing else. To open the port, use start().
Precondition
Port must be set before with setPort()
Port manager must be closed (see isClosed()).
See Also
mdtAbstractPort
Definition at line 238 of file mdtPortManager.cpp.
References isClosed(), pvPort, and mdtAbstractPort::setPortName().
Referenced by mdtDeviceModbus::connectToDevice(), and mdtModbusTcpPortManager::scan().
bool mdtPortManager::start () virtual
Start port manager.
Will open port and start threads. This method returns once port manager is ready (see isReady()). Note: event loop continues to work during wait of ready state, GUI will also not freeze
Precondition
Port must be set with setPort() before use of this method.
Definition at line 184 of file mdtPortManager.cpp.
References currentState(), isClosed(), mdtAbstractPort::isOpen(), isReady(), openPort(), pmStartThreadsEvent(), PortError, pvPort, stop(), Stopped, and Stopping.
Referenced by mdtDeviceModbus::connectToDevice(), and mdtModbusTcpPortManager::scan().
void mdtPortManager::startTransactionTimer (int timeout) protected
Start transaction timer.
Parameters
timeout Timeout [ms]
See Also
transactionTimeoutOccured()
pmTransactionTimeoutEvent()
onTransactionTimeoutOccured()
stopTransactionTimer()
Definition at line 772 of file mdtPortManager.cpp.
Referenced by waitOneTransactionDone(), and waitTransactionDone().
void mdtPortManager::stateChanged (int stateId) signal
Emitted each time the state changed.
void mdtPortManager::stateChangedForUi (int stateId, const QString & stateText, int ledColorId, bool ledIsOn) signal
Emitted only if a state that must be notified is entered.
See Also
mdtStateMachine
void mdtPortManager::statusMessageChanged (const QString & message, const QString & details, int timeout) signal
Emitted when a new status message is to display.
Typically used with mdtDeviceStatusWidget.
Referenced by mdtModbusTcpPortManager::tryToConnect().
void mdtPortManager::stop ()
Stop port manager.
Will stop threads and close port. This method returns once port manager is closed (see isClosed()). Note: event loop continues to work during wait of ready state, GUI will also not freeze
Precondition
Port must be set with setPort() before use of this method.
Definition at line 215 of file mdtPortManager.cpp.
References closePort(), isClosed(), mdtAbstractPort::isOpen(), pmPortClosedEvent(), pmStopThreadsEvent(), PortClosed, pvPort, Stopped, stopTransactionTimer(), and mdtStateMachine::waitOnState().
Referenced by mdtDeviceModbus::connectToDevice(), detachPort(), mdtModbusTcpPortManager::scan(), start(), mdtDeviceModbus::~mdtDeviceModbus(), and ~mdtPortManager().
void mdtPortManager::stopTransactionTimer () protected
Stop transaction timer.
See Also
startTransactionTimer()
transactionTimeoutOccured()
pmTransactionTimeoutEvent()
onTransactionTimeoutOccured()
Definition at line 780 of file mdtPortManager.cpp.
Referenced by stop(), waitOneTransactionDone(), and waitTransactionDone().
mdtPortTransaction * mdtPortManager::transactionDone (int id) protected
Take transaction from DONE queue matching id.
Returns
A valid transaction if exists, else a Null pointer.
Definition at line 744 of file mdtPortManager.cpp.
References mdtPortTransaction::id().
Referenced by readenFrame().
mdtPortTransaction * mdtPortManager::transactionPending (int id) protected
Take pending transaction matching id.
Returns
A valid transaction if exists, else a Null pointer.
Definition at line 702 of file mdtPortManager.cpp.
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), and fromThreadNewFrameReaden().
bool mdtPortManager::transactionsDoneContains (int id) const protected
Check if a transaction with given ID exists in done queue.
Definition at line 730 of file mdtPortManager.cpp.
Referenced by addTransactionDone(), mdtModbusTcpPortManager::sendData(), sendData(), and waitTransactionDone().
bool mdtPortManager::transactionTimeoutOccured () const protected
Check if a transaction timeout occured.
See Also
pmTransactionTimeoutEvent()
onTransactionTimeoutOccured()
startTransactionTimer()
stopTransactionTimer()
Definition at line 788 of file mdtPortManager.cpp.
Referenced by waitOneTransactionDone(), and waitTransactionDone().
void mdtPortManager::unlockPortMutex ()
Unlock port's mutex.
Precondition
Port must be set with setPort before using this method
Definition at line 96 of file mdtPortManager.cpp.
References pvPort, and mdtAbstractPort::unlockMutex().
Referenced by mdtModbusTcpPortManager::fromThreadNewFrameReaden(), fromThreadNewFrameReaden(), mdtModbusTcpPortManager::sendData(), and sendData().
void mdtPortManager::wait (int ms)
Wait for some time.
This will block the caller until ms milliseconds elapsed. This will not block event loop, i.e. no GUI freeze occurs.
Such wait method can be usfull if, for example, a device needs some time between two requests.
Note: this method should not be used to wait on a specific event (frame received, ...). For such problem, please considere the transaction API (in this class) and mdtDevice witch give some helper methods and a API when developping new communication classes with devices.
Internally, a QTimer is used. Please considere Qt documentation about time precisions and limitations. Note: mdtPortManager is not designed for real time applications, but in mind to communicate in a easy way with devices.
For the story, a example with a Wago 750 I/O system: In multidiagtools test suite we do set/get tests on outputs. We wait confirmation of device for each request (see mdtDevice for details). Some times test failed because the get didn't return the value set just before. By mesuring set and get times, we could see that it can take about 2[ms] -> 40[ms]. This can be shorter than PLC needs to update its cache (read all I/O on bus, ...), and we had a old value in get reply.
Definition at line 481 of file mdtPortManager.cpp.
bool mdtPortManager::waitOneTransactionDone ()
Wait until current transaction is done.
Use this method if protocol does not support frame ID.
Internally, it will wait until one transaction is available in done queue.
Returns
True if Ok, false on timeout or other error.
Definition at line 438 of file mdtPortManager.cpp.
References Busy, config(), currentState(), isReady(), pvPort, startTransactionTimer(), stopTransactionTimer(), and transactionTimeoutOccured().
bool mdtPortManager::waitTransactionDone (int id)
Wait until a transaction is done.
Will return when transaction with given id is done or after timeout.
This wait method does not break Qt's event loop, no GUI freeze occurs.
This method can return if timeout occurs, or for other reason depending on specific port (port timeout, read cancelled, ...).
Parameters
id Frame ID. Depending on protocol, this can be a transaction ID or what else.
Returns
True if Ok, false on timeout or other error. If id was not found in transactions pending lists, a warning will be generated in mdtError system, and false will be returned. On failure, transaction is restored to pool (see onThreadsErrorOccured() for details).
Definition at line 383 of file mdtPortManager.cpp.
References Busy, mdtError::commit(), config(), currentState(), isReady(), MDT_ERROR_SET_SRC, MDT_PORT_IO_ERROR, pmUnhandledErrorEvent(), pvPort, startTransactionTimer(), stopTransactionTimer(), transactionsDoneContains(), transactionTimeoutOccured(), and mdtError::Warning.
Referenced by mdtModbusTcpPortManager::getHardwareNodeAddress(), mdtModbusTcpPortManager::getRegisterValues(), mdtModbusTcpPortManager::setRegisterValues(), and mdtMultiIoDevice::waitTransactionDone().
bool mdtPortManager::waitTransactionPossible () protected
Wait until transaction pending queue has less than maximum possible items.
Returns
True on success, false if wait was interrupted.
Definition at line 654 of file mdtPortManager.cpp.
References isClosed(), isReady(), and pvPort.
Referenced by mdtModbusTcpPortManager::sendData(), and sendData().
mdtPortThread * mdtPortManager::writeThread ()
Returns instance of writer thread.
Note that a Null pointer can be returned
Definition at line 153 of file mdtPortManager.cpp.
Member Data Documentation
mdtError mdtPortManager::pvLastError protected
Last error object.
Definition at line 760 of file mdtPortManager.h.
Referenced by mdtModbusTcpPortManager::getHardwareNodeAddress(), lastError(), mdtModbusTcpPortManager::readDeviceAddressList(), mdtModbusTcpPortManager::saveDeviceAddressList(), and mdtModbusTcpPortManager::scan().
mdtAbstractPort* mdtPortManager::pvPort protected
Definition at line 925 of file mdtPortManager.h.
Referenced by abort(), addThread(), closePort(), mdtSerialPortManager::config(), config(), detachPort(), flush(), flushIn(), flushOut(), mdtModbusTcpPortManager::fromThreadNewFrameReaden(), fromThreadNewFrameReaden(), lockPortMutex(), mdtPortManager(), openPort(), mdtSerialPortManager::port(), mdtModbusTcpPortManager::sendData(), sendData(), setPort(), setPortInfo(), setPortName(), start(), stop(), unlockPortMutex(), waitOneTransactionDone(), waitTransactionDone(), waitTransactionPossible(), mdtModbusTcpPortManager::~mdtModbusTcpPortManager(), ~mdtPortManager(), and mdtSerialPortManager::~mdtSerialPortManager().
QList<mdtPortThread*> mdtPortManager::pvThreads protected
Definition at line 926 of file mdtPortManager.h.
Referenced by addThread(), and removeThreads().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortManager.h
src/mdtport/mdtPortManager.cpp