Multi diag tools: mdtParentChildTableModel Class Reference
mdtParentChildTableModel Class Reference
#include <mdtParentChildTableModel.h>
Public Member Functions
mdtParentChildTableModel (QObject *parent=0)
~mdtParentChildTableModel ()
int rowCount (const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role) const
void setHeaderData (QList< QVariant > &headerData)
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Qt::ItemFlags flags (const QModelIndex &index) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index=QModelIndex()) const
Detailed Description
Definition at line 12 of file mdtParentChildTableModel.h.
Constructor & Destructor Documentation
mdtParentChildTableModel::mdtParentChildTableModel (QObject * parent = 0)
Definition at line 11 of file mdtParentChildTableModel.cpp.
mdtParentChildTableModel::~mdtParentChildTableModel ()
Definition at line 20 of file mdtParentChildTableModel.cpp.
Member Function Documentation
int mdtParentChildTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 42 of file mdtParentChildTableModel.cpp.
References mdtParentChildTableItem::child(), mdtParentChildTableItem::columnCount(), and mdtParentChildTableItem::row().
QVariant mdtParentChildTableModel::data (const QModelIndex & index, int role) const
Definition at line 61 of file mdtParentChildTableModel.cpp.
References mdtParentChildTableItem::data().
Qt::ItemFlags mdtParentChildTableModel::flags (const QModelIndex & index) const
Definition at line 95 of file mdtParentChildTableModel.cpp.
QVariant mdtParentChildTableModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Definition at line 81 of file mdtParentChildTableModel.cpp.
Referenced by setHeaderData().
QModelIndex mdtParentChildTableModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Definition at line 104 of file mdtParentChildTableModel.cpp.
References mdtParentChildTableItem::child().
QModelIndex mdtParentChildTableModel::parent (const QModelIndex & index = QModelIndex()) const
Definition at line 125 of file mdtParentChildTableModel.cpp.
References mdtParentChildTableItem::parent(), and mdtParentChildTableItem::row().
int mdtParentChildTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 25 of file mdtParentChildTableModel.cpp.
References mdtParentChildTableItem::childCount().
void mdtParentChildTableModel::setHeaderData (QList< QVariant > & headerData)
Definition at line 76 of file mdtParentChildTableModel.cpp.
References headerData().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtParentChildTableModel.h
src/mdtutilsgui/mdtParentChildTableModel.cpp