Multi diag tools: mdtAnalogIo Class Reference
mdtAnalogIo Class Reference
Representation of a analog I/O.
#include <mdtAnalogIo.h>
Public Slots
void setValue (const mdtValue &value, bool emitValueChanged=false)
Set the value to update display.
Public Slots inherited from mdtAbstractIo
virtual void setValue (const mdtValue &value, bool emitValueChanged=false)
Set the value to update display.
Signals
void unitChangedForUi (const QString &unit)
void rangeChangedForUi (double min, double max)
Signals inherited from mdtAbstractIo
void addressChangedForUi (int addressRead, int addressWrite)
void labelShortChangedForUi (const QString &text)
void labelChangedForUi (const QString &text)
void detailsChangedForUi (const QString &text)
void enabledStateChangedForUi (bool enabled)
void valueChanged (const mdtValue &value)
This signal is emitted whenever the value is changed.
void valueChanged (mdtAnalogIo *io)
This signal is emitted whenever the value is changed.
void valueChanged (mdtDigitalIo *io)
void valueChangedForUi (const mdtValue &value)
This signal is emitted whenever the value is changed.
Public Member Functions
mdtAnalogIo (QObject *parent=0)
Constructor.
~mdtAnalogIo ()
Destructor.
void setUnit (const QString &unit)
Set the unit (V, A, °C, ...)
QString unit () const
Get unit.
bool setRange (double min, double max, int intValueBitsCount, int intValueLsbIndex=0, bool intValueSigned=false, bool scaleFromMinToMax=true, double conversionFactor=1.0)
Specify the range of values and bits decode parameters.
double minimum () const
Get the minimum value of the range.
double maximum () const
Get the maximum value of the range.
void setValueInt (int value, bool isValid, bool emitValueChanged)
Set the integer value.
Public Member Functions inherited from mdtAbstractIo
mdtAbstractIo (QObject *parent=0)
Construct a empty I/O.
virtual ~mdtAbstractIo ()
void setAddress (int address)
Set the I/O address.
int address () const
Get the I/O address.
void setAddressRead (int address)
Set the I/O address for read.
int addressRead () const
Get the I/O address for read.
void setAddressWrite (int address)
Set the I/O address for write.
int addressWrite () const
Get the I/O address for write.
void setLabelShort (const QString &text)
Set the short I/O label.
QString labelShort () const
Get the short I/O label.
void setLabel (const QString &text)
Set the complete I/O label.
QString label () const
Get the complete I/O label.
void setDetails (const QString &text)
Set details about the I/O.
QString details () const
Get details about the I/O.
bool hasValidData () const
Returns true if a valid value or state was set.
void setEnabled (bool enabled)
Set enabled state.
const mdtValue & value () const
Get current value.
Additional Inherited Members
Protected Attributes inherited from mdtAbstractIo
mdtValue pvValue
bool pvNotifyUi
Detailed Description
Representation of a analog I/O.
On wide range of automation applications, it is usefull to display a I/O to the user. For example, a analog I/O module, with a 8 bit encoding could be displayed with this class togther with mdtAnalogInWidget or mdtAnalogOutWidget.
Definition at line 35 of file mdtAnalogIo.h.
Constructor & Destructor Documentation
mdtAnalogIo::mdtAnalogIo (QObject * parent = 0)
Constructor.
Definition at line 28 of file mdtAnalogIo.cpp.
mdtAnalogIo::~mdtAnalogIo ()
Destructor.
Definition at line 46 of file mdtAnalogIo.cpp.
Member Function Documentation
double mdtAnalogIo::maximum () const
Get the maximum value of the range.
Definition at line 127 of file mdtAnalogIo.cpp.
Referenced by mdtAnalogInWidget::setIo(), and mdtAnalogOutWidget::setIo().
double mdtAnalogIo::minimum () const
Get the minimum value of the range.
Definition at line 122 of file mdtAnalogIo.cpp.
Referenced by mdtAnalogInWidget::setIo(), and mdtAnalogOutWidget::setIo().
void mdtAnalogIo::rangeChangedForUi (double min, double max) signal
Definition at line 116 of file moc_mdtAnalogIo.cxx.
Referenced by setRange().
bool mdtAnalogIo::setRange (double min, double max, int intValueBitsCount, int intValueLsbIndex = 0, bool intValueSigned = false, bool scaleFromMinToMax = true, double conversionFactor = 1.0)
Specify the range of values and bits decode parameters.
Store the new range and set the value to the minimum. The valueChanged() signal is emitted.
It can happen that a I/O module returns, f.ex., a integer value in a 16 bits packet, but with some additional flags. (example: Wago 750-457). In such case, the value is, f.ex., encoded in 12 bits only.
Take example of Wago 750-457:
Value + flags are encoded in a 16 bits word
Value is encoded in 12 bits, from b3 to b14 + 1 sign bit, b15
Value is scaled from -10 V to 10 V
In this example, this method must be called with min = -10.0 , max = 10.0 , intValueBitsCount = 13 , intValueLsbIndex = 3 , intValueSigned = true , scaleFromMinToMax = true , conversionFactor = 1.0 .
Here is another example with Wago 750-464 with Pt100 sensor and normal format:
Value is encoded in 16 bits
Scaling is allready done by device
Value represents 0.1°C per digit -> we have to apply a conversion factor of 0.1
In this example, this method must be called with min = -200.0 , max = 850.0 , intValueBitsCount = 16 , intValueLsbIndex = 0 , intValueSigned = true , scaleFromMinToMax = false , conversionFactor = 0.1 .
Parameters
min Minimum value to display (f.ex. 0V, or 4mA)
max Maximum value to display (f.ex. 10V, or 20mA)
intValueBitsCount Number of bits used for the value, including sign bit.
intValueLsbIndex Index of first bit to use for value extraction.
intValueSigned If true, decoded value is considered as signed value, i.e. the most significant bit is the sign.
scaleFromMinToMax If true, given value INT will be scaled from min to max regarding LSB. LSB is determined from intValueBitsCount .
conversionFactor This factor is applied as follow (min, max scaling is ignored in this example):
ValueDouble = valueInt * LSB * conversionFactor
ValueInt = valueDouble / (LSB * conversionFactor)
LSB is determined from intValueBitsCount .
Returns
true on success. Some checks are done, and if one fails, false is returned and the previous settingsare used for conversion.
Precondition
max must be > min
Note for UI developpers:
The signal rangeChangedForUi() is emited
The signal valueChangedForUi() is emited
Definition at line 61 of file mdtAnalogIo.cpp.
References mdtValue::clear(), mdtError::commit(), MDT_ERROR_SET_SRC, MDT_PARSE_ERROR, mdtAbstractIo::pvNotifyUi, mdtAbstractIo::pvValue, rangeChangedForUi(), mdtValue::setDefaultValue(), mdtValue::valueDouble(), mdtValue::valueInt(), and mdtError::Warning.
void mdtAnalogIo::setUnit (const QString & unit)
Set the unit (V, A, °C, ...)
Definition at line 50 of file mdtAnalogIo.cpp.
References unit(), and unitChangedForUi().
void mdtAnalogIo::setValue (const mdtValue & value, bool emitValueChanged = false) slot
Set the value to update display.
See Also
mdtAbstractIo::setValue(const mdtValue&, bool)
Definition at line 143 of file mdtAnalogIo.cpp.
References mdtValue::hasValueDouble(), and mdtAbstractIo::pvNotifyUi.
Referenced by mdtDevice::getAnalogInputValue(), mdtDevice::getAnalogOutputValue(), and mdtDevice::setAnalogOutputValue().
void mdtAnalogIo::setValueInt (int value, bool isValid, bool emitValueChanged)
Set the integer value.
Will calculate the real value depending on resolution and update display. The resolution is set with setRange() (intValueBitsCount parameter)
The valueChanged() signal is emitted.
Parameters
value The value to store
isValid The validity flag. This flag is later avaliable with mdtAbstractIo::hasValidData()
emitValueChanged If true, valueChanged() will not be emitted
Note for UI developpers:
The signal valueChangedForUi() is emited
Definition at line 132 of file mdtAnalogIo.cpp.
References mdtAbstractIo::pvNotifyUi, and mdtValue::setValue().
QString mdtAnalogIo::unit () const
Get unit.
Definition at line 56 of file mdtAnalogIo.cpp.
Referenced by mdtAnalogInWidget::setIo(), mdtAnalogOutWidget::setIo(), and setUnit().
void mdtAnalogIo::unitChangedForUi (const QString & unit) signal
Definition at line 109 of file moc_mdtAnalogIo.cxx.
Referenced by setUnit().
The documentation for this class was generated from the following files:
src/mdtutils/mdtAnalogIo.h
src/mdtutils/mdtAnalogIo.cpp
src/mdtutils/moc_mdtAnalogIo.cxx