Multi diag tools: mdtValueIntegral< T > Class Template Reference
mdtValueIntegral< T > Class Template Reference
Integral type with Null attribute.
#include <mdtValue.h>
Public Member Functions
mdtValueIntegral ()
Construct a null value.
mdtValueIntegral (T value)
Construct value.
void clear ()
Clear value.
bool isNull () const
Check if value is null.
void setValue (T value)
Set value.
T value () const
Get value.
bool operator== (const mdtValueIntegral &other) const
Comparaison operator.
bool operator!= (const mdtValueIntegral &other) const
Comparaison operator.
bool operator< (const mdtValueIntegral &other) const
Comparison operator.
bool operator<= (const mdtValueIntegral &other) const
Comparison operator.
bool operator> (const mdtValueIntegral &other) const
Comparison operator.
bool operator>= (const mdtValueIntegral &other) const
Comparison operator.
mdtValueIntegral operator+ (const mdtValueIntegral &other) const
Addition operator.
mdtValueIntegral operator- (const mdtValueIntegral &other) const
Soustraction operator.
mdtValueIntegral operator* (const mdtValueIntegral &other) const
Multiplication operator.
Detailed Description
template<typename T>
class mdtValueIntegral< T >
Integral type with Null attribute.
Most of cases, using standard C++ types are sufficent. But, in some cases, its needed to test if a function returned a valid value or not. Here, the Null flag is used for that.
Definition at line 235 of file mdtValue.h.
Constructor & Destructor Documentation
template<typename T > mdtValueIntegral< T >::mdtValueIntegral () inline
Construct a null value.
Definition at line 241 of file mdtValue.h.
Referenced by mdtValueIntegral< T >::operator*(), mdtValueIntegral< T >::operator+(), and mdtValueIntegral< T >::operator-().
template<typename T > mdtValueIntegral< T >::mdtValueIntegral (T value) inline
Construct value.
Definition at line 249 of file mdtValue.h.
Member Function Documentation
template<typename T > void mdtValueIntegral< T >::clear () inline
Clear value.
Definition at line 257 of file mdtValue.h.
template<typename T > bool mdtValueIntegral< T >::isNull () const inline
Check if value is null.
Definition at line 265 of file mdtValue.h.
Referenced by operator<<().
template<typename T > bool mdtValueIntegral< T >::operator!= (const mdtValueIntegral< T > & other) const inline
Comparaison operator.
Definition at line 300 of file mdtValue.h.
template<typename T > mdtValueIntegral mdtValueIntegral< T >::operator* (const mdtValueIntegral< T > & other) const inline
Multiplication operator.
Note: if one (or both) value is null, a null value will be returned (Same rule as IEEE 754 NaN)
Definition at line 388 of file mdtValue.h.
References mdtValueIntegral< T >::mdtValueIntegral().
template<typename T > mdtValueIntegral mdtValueIntegral< T >::operator+ (const mdtValueIntegral< T > & other) const inline
Addition operator.
Note: if one (or both) value is null, a null value will be returned (Same rule as IEEE 754 NaN)
Definition at line 362 of file mdtValue.h.
References mdtValueIntegral< T >::mdtValueIntegral().
template<typename T > mdtValueIntegral mdtValueIntegral< T >::operator- (const mdtValueIntegral< T > & other) const inline
Soustraction operator.
Note: if one (or both) value is null, a null value will be returned (Same rule as IEEE 754 NaN)
Definition at line 375 of file mdtValue.h.
References mdtValueIntegral< T >::mdtValueIntegral().
template<typename T > bool mdtValueIntegral< T >::operator< (const mdtValueIntegral< T > & other) const inline
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Definition at line 310 of file mdtValue.h.
template<typename T > bool mdtValueIntegral< T >::operator<= (const mdtValueIntegral< T > & other) const inline
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Definition at line 323 of file mdtValue.h.
template<typename T > bool mdtValueIntegral< T >::operator== (const mdtValueIntegral< T > & other) const inline
Comparaison operator.
Note: if one (or both) value is null, they are not considered equal (Same rule as IEEE 754 NaN)
Definition at line 290 of file mdtValue.h.
template<typename T > bool mdtValueIntegral< T >::operator> (const mdtValueIntegral< T > & other) const inline
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Definition at line 336 of file mdtValue.h.
template<typename T > bool mdtValueIntegral< T >::operator>= (const mdtValueIntegral< T > & other) const inline
Comparison operator.
Note: if one (or both) value is null, comparison will allways be false (Same rule as IEEE 754 NaN)
Definition at line 349 of file mdtValue.h.
template<typename T > void mdtValueIntegral< T >::setValue (T value) inline
Set value.
Definition at line 272 of file mdtValue.h.
References mdtValueIntegral< T >::value().
template<typename T > T mdtValueIntegral< T >::value () const inline
Get value.
Definition at line 280 of file mdtValue.h.
Referenced by operator<<(), and mdtValueIntegral< T >::setValue().
The documentation for this class was generated from the following file:
src/mdtutils/mdtValue.h