Multi diag tools: mdtUsbPortThread Class Reference
mdtUsbPortThread Class Reference
#include <mdtUsbPortThread.h>
Signals
void controlResponseReaden ()
Emited when a new control response was readen.
void messageInReaden ()
Emited when a message IN was readen (from additionnal interrupt IN endpoint)
void readUntilShortPacketReceivedFinished ()
Emitted when the read until a short packet process is finished.
Signals inherited from mdtPortThread
void readProcessBegin ()
Emitted when a read process begins.
void writeProcessBegin ()
Emitted when a write process begins.
void newFrameReaden ()
Emited when a new frame is available.
void errorOccured (int error)
Emitted on error.
void ready (mdtPortThread *thread)
Emitted when thread is started and ready.
void finished (mdtPortThread *thread)
Emitted when thread has finished executing.
void connected ()
Emitted when connection with device is done.
Public Member Functions
mdtUsbPortThread (QObject *parent=0)
Constructor.
void setPort (mdtUsbPort *port)
Set the port instance.
mdtUsbPort * usbPort ()
Get USB port instance.
void detachPort (bool releaseMemory)
Detach the port from thread.
bool isReader () const
Returns true.
bool isWriter () const
Returns true.
bool handlesTimeout () const
Retunrs true.
Public Member Functions inherited from mdtPortThread
mdtPortThread (QObject *parent=0)
virtual ~mdtPortThread ()
virtual void setPort (mdtAbstractPort *port)
Set the port instance.
mdtAbstractPort * port ()
Get port instance.
void start ()
Start the thread.
virtual void stop ()
Stop the running thread.
void waitReady ()
Wait until thread is ready.
void waitFinished ()
Wait until thread is finished.
bool isRunning () const
Returns true if the thread is running.
void setRunningFlag (bool running)
Set the running flag.
bool runningFlagSet () const
Get the running flag.
bool isFinished () const
Returns false if the thread is running.
void notifyError (mdtAbstractPort::error_t error, bool renotifySameError=false)
Emit the errorOccured() signal if new error is different from current.
mdtAbstractPort::error_t currentError () const
Get current error.
Protected Member Functions
mdtAbstractPort::error_t waitOnControlTransferPossible (bool notifyOnControlTransferComplete)
Wait until a new control transfer is possible (i.e. when control frames pool is not empty)
mdtAbstractPort::error_t sendControlQuery (mdtFrameUsbControl *ctlFrame)
Send a control query and wait until response is available.
mdtAbstractPort::error_t readUntilShortPacketReceived (int maxReadTransfers)
Read until a short frame is received.
Protected Member Functions inherited from mdtPortThread
mdtAbstractPort::error_t reconnect (bool notify=true)
Try to reconnect to device/peer.
Additional Inherited Members
Static Protected Member Functions inherited from mdtPortThread
static void sigactionHandle (int signum)
Protected Attributes inherited from mdtPortThread
volatile bool pvRunning
mdtAbstractPort * pvPort
pthread_t pvNativePthreadObject
struct sigaction pvSigaction
Detailed Description
Definition at line 35 of file mdtUsbPortThread.h.
Constructor & Destructor Documentation
mdtUsbPortThread::mdtUsbPortThread (QObject * parent = 0)
Constructor.
Definition at line 30 of file mdtUsbPortThread.cpp.
Member Function Documentation
void mdtUsbPortThread::controlResponseReaden () signal
Emited when a new control response was readen.
Referenced by waitOnControlTransferPossible().
void mdtUsbPortThread::detachPort (bool releaseMemory) virtual
Detach the port from thread.
Parameters
releaseMemory If true, the port object that was set with setPort() will be deleted.
Precondition
The thread must not running
Reimplemented from mdtPortThread.
Definition at line 49 of file mdtUsbPortThread.cpp.
References mdtPortThread::detachPort().
bool mdtUsbPortThread::handlesTimeout () const virtual
Retunrs true.
Reimplemented from mdtPortThread.
Definition at line 65 of file mdtUsbPortThread.cpp.
bool mdtUsbPortThread::isReader () const virtual
Returns true.
Reimplemented from mdtPortThread.
Definition at line 55 of file mdtUsbPortThread.cpp.
bool mdtUsbPortThread::isWriter () const virtual
Returns true.
Reimplemented from mdtPortThread.
Definition at line 60 of file mdtUsbPortThread.cpp.
void mdtUsbPortThread::messageInReaden () signal
Emited when a message IN was readen (from additionnal interrupt IN endpoint)
mdtAbstractPort::error_t mdtUsbPortThread::readUntilShortPacketReceived (int maxReadTransfers) protected
Read until a short frame is received.
Parameters
maxReadTransfers Maximum of read transfers before return (If device returns never a short frame, this method will return after maxReadTransfers).
Returns
NoError or a error of type mdtAbstractPort::error_t. If maxReadTransfers is reached, ReadTimeout is returned.
Precondition
Port must be set with setPort() before using this method.
Definition at line 154 of file mdtUsbPortThread.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, mdtAbstractPort::NoError, mdtAbstractPort::ReadTimeout, and usbPort().
void mdtUsbPortThread::readUntilShortPacketReceivedFinished () signal
Emitted when the read until a short packet process is finished.
mdtAbstractPort::error_t mdtUsbPortThread::sendControlQuery (mdtFrameUsbControl * ctlFrame) protected
Send a control query and wait until response is available.
Definition at line 119 of file mdtUsbPortThread.cpp.
References mdtAbstractPort::NoError, mdtPortThread::pvRunning, and usbPort().
void mdtUsbPortThread::setPort (mdtUsbPort * port)
Set the port instance.
Precondition
port must be a valid pointer
The thread must not running
Definition at line 36 of file mdtUsbPortThread.cpp.
References mdtPortThread::port(), and mdtPortThread::setPort().
mdtUsbPort * mdtUsbPortThread::usbPort ()
Get USB port instance.
Returns
Port instance, or a null pointer if it was not set
Definition at line 44 of file mdtUsbPortThread.cpp.
Referenced by readUntilShortPacketReceived(), sendControlQuery(), and waitOnControlTransferPossible().
mdtAbstractPort::error_t mdtUsbPortThread::waitOnControlTransferPossible (bool notifyOnControlTransferComplete) protected
Wait until a new control transfer is possible (i.e. when control frames pool is not empty)
Definition at line 70 of file mdtUsbPortThread.cpp.
References mdtError::commit(), controlResponseReaden(), MDT_ERROR_SET_SRC, MDT_USB_IO_ERROR, msleep, mdtAbstractPort::NoError, mdtPortThread::pvRunning, usbPort(), and mdtError::Warning.
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbPortThread.h
src/mdtport/mdtUsbPortThread.cpp