Multi diag tools: mdtDeviceContainerWidget Class Reference
mdtDeviceContainerWidget Class Reference
Manage device status widget items.
#include <mdtDeviceContainerWidget.h>
Public Slots
void addDevice (std::shared_ptr< mdtDevice > device)
Add a device.
void clear ()
Clear.
Public Member Functions
mdtDeviceContainerWidget (QWidget *parent=0)
Constructor.
void setContainer (std::shared_ptr< mdtDeviceContainer > c)
Set device container.
Detailed Description
Manage device status widget items.
Definition at line 75 of file mdtDeviceContainerWidget.h.
Constructor & Destructor Documentation
mdtDeviceContainerWidget::mdtDeviceContainerWidget (QWidget * parent = 0)
Constructor.
Definition at line 83 of file mdtDeviceContainerWidget.cpp.
Member Function Documentation
void mdtDeviceContainerWidget::addDevice (std::shared_ptr< mdtDevice > device) slot
Add a device.
Definition at line 131 of file mdtDeviceContainerWidget.cpp.
Referenced by setContainer().
void mdtDeviceContainerWidget::clear () slot
Clear.
Definition at line 121 of file mdtDeviceContainerWidget.cpp.
Referenced by setContainer().
void mdtDeviceContainerWidget::setContainer (std::shared_ptr< mdtDeviceContainer > c)
Set device container.
Will clear widgets, then add all devices allready set in c. Then, signals from c are connected, so this widget will be updated each time a device is added/removed from container c.
Definition at line 103 of file mdtDeviceContainerWidget.cpp.
References addDevice(), and clear().
Referenced by mdtTtBasicTesterWindow::mdtTtBasicTesterWindow().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceContainerWidget.h
src/mdtdevice/mdtDeviceContainerWidget.cpp