Multi diag tools: mdtPortStatusWidget Class Reference
mdtPortStatusWidget Class Reference
Helper class to display port/device state and messages.
#include <mdtPortStatusWidget.h>
Public Slots
void setState (int id, const QString &text, int ledColorId, bool ledIsOn)
Set state.
void showMessage (const QString &message, const QString &details, int timeout=0)
Used to show a message and details.
Public Member Functions
mdtPortStatusWidget (QWidget *parent=0)
Build a status widget with default texts.
~mdtPortStatusWidget ()
Destructor.
void enableTxRxLeds (mdtPortThread *txThread, mdtPortThread *rxThread)
Enable the TX/RX LEDs.
void disableTxRxLeds ()
Disable the TX/RX LED's.
void addCustomWidget (QWidget *widget)
Add a custom widget.
void removeCustomWidget ()
Remove the custom widget.
void setPermanentText (const QString &text)
Set the permanent text.
void clearMessage ()
Clear current message.
Detailed Description
Helper class to display port/device state and messages.
This widget contains 4 parts:
A push button that opens a message box with details
A status region with a LED and a text area
A custom widget place holder
A fixed text area (typically usefull to display wich port is open, f.ex.)
Definition at line 43 of file mdtPortStatusWidget.h.
Constructor & Destructor Documentation
mdtPortStatusWidget::mdtPortStatusWidget (QWidget * parent = 0)
Build a status widget with default texts.
Definition at line 28 of file mdtPortStatusWidget.cpp.
References mdtLed::setFixedSize().
mdtPortStatusWidget::~mdtPortStatusWidget ()
Destructor.
Definition at line 65 of file mdtPortStatusWidget.cpp.
References disableTxRxLeds().
Member Function Documentation
void mdtPortStatusWidget::addCustomWidget (QWidget * widget)
Add a custom widget.
One custom widget can be added.
Definition at line 130 of file mdtPortStatusWidget.cpp.
References removeCustomWidget().
void mdtPortStatusWidget::clearMessage ()
Clear current message.
Clear message showed with showMessage()
After calling this method, netx call of setState() will update text.
Definition at line 155 of file mdtPortStatusWidget.cpp.
Referenced by showMessage().
void mdtPortStatusWidget::disableTxRxLeds ()
Disable the TX/RX LED's.
Definition at line 100 of file mdtPortStatusWidget.cpp.
Referenced by enableTxRxLeds(), and ~mdtPortStatusWidget().
void mdtPortStatusWidget::enableTxRxLeds (mdtPortThread * txThread, mdtPortThread * rxThread)
Enable the TX/RX LEDs.
Precondition
txThread and rxThread must be valid.
Definition at line 70 of file mdtPortStatusWidget.cpp.
References disableTxRxLeds(), mdtLed::setFixedSize(), and mdtLed::setGreen().
void mdtPortStatusWidget::removeCustomWidget ()
Remove the custom widget.
See Also
addCustomWidget().
Definition at line 140 of file mdtPortStatusWidget.cpp.
Referenced by addCustomWidget().
void mdtPortStatusWidget::setPermanentText (const QString & text)
Set the permanent text.
Note: permanent text is allways visible
Definition at line 150 of file mdtPortStatusWidget.cpp.
void mdtPortStatusWidget::setState (int id, const QString & text, int ledColorId, bool ledIsOn) slot
Set state.
States are defined in mdtPortManager
Definition at line 165 of file mdtPortStatusWidget.cpp.
References mdtLed::setColor(), and mdtBlinkLed::setOn().
void mdtPortStatusWidget::showMessage (const QString & message, const QString & details, int timeout = 0) slot
Used to show a message and details.
Note: calling this slot with a empty message has the same effect than clearMessage() .
Parameters
message Message to show.
details Details to show
timeout If > 0, message will be cleared after timeout [ms]
Definition at line 177 of file mdtPortStatusWidget.cpp.
References clearMessage().
Referenced by mdtAbstractPortSetupDialog::showStatusMessage().
The documentation for this class was generated from the following files:
src/mdtport/mdtPortStatusWidget.h
src/mdtport/mdtPortStatusWidget.cpp