Multi diag tools: mdtDeviceScpi Class Reference
mdtDeviceScpi Class Reference
Base class for SCPI based instruments.
#include <mdtDeviceScpi.h>
Public Member Functions
mdtDeviceScpi (QObject *parent=0)
Construct a SCPI device.
virtual ~mdtDeviceScpi ()
mdtPortManager * portManager ()
Get internal port manager instance.
mdtAbstractPort::error_t connectToDevice (const mdtDeviceInfo &devInfo)
Search and connect to physical device.
int sendCommand (const QByteArray &command)
Send a command to device.
QByteArray sendQuery (const QByteArray &query)
Send a query to device.
bool waitOperationComplete (int timeout, int interval)
Wait until operation is complete (Using *OPC? query)
int checkDeviceError ()
Query device about error.
Public Member Functions inherited from mdtDevice
mdtDevice (QObject *parent=0)
Construct a device object.
virtual ~mdtDevice ()
Destructor.
void setName (const QString &name)
Set the device name.
QString name () const
Get device name.
void setIdentification (const QVariant &id)
Set device identification.
QVariant identification () const
Get device identification.
virtual void disconnectFromDevice ()
Disconnect from device.
void addInput (mdtAnalogIo *analogInput)
Add a analog input.
void addInputs (const QList< mdtAnalogIo * > &analogInputs)
Add a list of analog inputs.
void addOutput (mdtAnalogIo *analogOutput)
Add a analog output.
void addOutputs (const QList< mdtAnalogIo * > &analogOutputs)
Add a list of analog outputs.
void addInput (mdtDigitalIo *digitalInput)
Add a digital input.
void addInputs (const QList< mdtDigitalIo * > &digitalInputs)
Add a list of digital inputs.
void addOutput (mdtDigitalIo *digitalOutput)
Add a digital output.
void addOutputs (const QList< mdtDigitalIo * > &digitalOutputs)
Add a list of digital outputs.
void deleteIos ()
Delete all I/O in container.
mdtDeviceIos * ios ()
Get the I/Os container.
void setBackToReadyStateTimeout (int timeout)
Set back to ready state timeout.
virtual bool isReady ()
Check if device is ready.
void start (int queryInterval)
Start periodic device querying.
void stop ()
Stop periodic device querying.
void wait (int ms)
Wait some time.
mdtError lastError () const
Get last error.
mdtValue getAnalogInputValue (mdtAnalogIo *analogInput, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (int address, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog input value.
mdtValue getAnalogInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogInputs (bool waitOnReply)
Read all analog inputs on physical device and update (G)UI representation.
mdtValue getAnalogOutputValue (mdtAnalogIo *analogOutput, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get analog output value.
mdtValue getAnalogOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getAnalogOutputs (bool waitOnReply)
Read all analog outputs on physical device and update (G)UI representation.
int setAnalogOutputValue (mdtAnalogIo *analogOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set analog output value.
int setAnalogOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
int setAnalogOutputs (bool waitOnReply)
Write all analog outputs on physical device and update (G)UI representation.
mdtValue getDigitalInputValue (mdtDigitalIo *digitalInput, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (int address, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital input value.
mdtValue getDigitalInputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalInputs (bool waitOnReply)
Read all digital inputs on physical device and update (G)UI representation.
mdtValue getDigitalOutputValue (mdtDigitalIo *digitalOutput, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (int addressRead, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValueAt (int position, bool queryDevice, bool waitOnReply)
Get digital output value.
mdtValue getDigitalOutputValue (const QString &labelShort, bool queryDevice, bool waitOnReply)
int getDigitalOutputs (bool waitOnReply)
Read all digital outputs on physical device and update (G)UI representation.
int setDigitalOutputValue (mdtDigitalIo *digitalOutput, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set a digital output value.
int setDigitalOutputValue (int addressWrite, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValueAt (int position, const mdtValue &value, bool sendToDevice, bool waitOnReply)
Set digital output value.
int setDigitalOutputValue (const QString &labelShort, const mdtValue &value, bool sendToDevice, bool waitOnReply)
int setDigitalOutputs (bool waitOnReply)
Write all digital outputs to physical device and update (G)UI representation.
mdtPortManager::state_t currentState ()
Get device state.
Protected Member Functions
void handleDeviceError (const QList< QVariant > &decodedValues)
Handle device error.
virtual void handleDeviceSpecificError (int errNum, const QString &errText, const QList< QString > &deviceSpecificTexts)
Handle device's specific error.
void logDeviceError (int errNum, const QString &errText, const QList< QString > &deviceSpecificTexts, mdtError::level_t level)
Log a device error with mdtError system.
Protected Member Functions inherited from mdtDevice
mdtError & lastErrorW ()
Get last error for write access.
virtual int readAnalogInput (mdtPortTransaction *transaction)
Read one analog input on physical device.
virtual int readAnalogInputs (mdtPortTransaction *transaction)
Read all analog inputs on physical device.
virtual int readAnalogOutput (mdtPortTransaction *transaction)
Read one analog output on physical device.
virtual int readAnalogOutputs (mdtPortTransaction *transaction)
Read all analog outputs on physical device.
virtual int writeAnalogOutput (int value, mdtPortTransaction *transaction)
Write value on a analog output to physical device.
virtual int writeAnalogOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all analog outputs to physical device.
virtual int readDigitalInput (mdtPortTransaction *transaction)
Read one digital input on physical device.
virtual int readDigitalInputs (mdtPortTransaction *transaction)
Read all digital inputs on physical device.
virtual int readDigitalOutput (mdtPortTransaction *transaction)
Read one digital output on physical device.
virtual int readDigitalOutputs (mdtPortTransaction *transaction)
Read all digital outputs on physical device.
virtual int writeDigitalOutput (bool state, mdtPortTransaction *transaction)
Write state on a digital output to physical device.
virtual int writeDigitalOutputs (mdtPortTransaction *transaction, mdtDeviceIosSegment *segment)
Write all digital outputs to physical device.
virtual bool queriesSequence ()
Sequence of queries to send periodically.
mdtPortTransaction * getNewTransaction ()
Get a new transaction.
void restoreTransaction (mdtPortTransaction *transaction)
Restore a transaction into pool.
bool waitTransactionDone (int id)
Wait until a transaction is done without break the GUI's event loop.
Protected Attributes
mdtUsbtmcPortManager * pvUsbtmcPortManager
Additional Inherited Members
Public Slots inherited from mdtDevice
void setAnalogOutputValue (mdtAnalogIo *analogOutput)
Set value on a analog output on physical device.
void setDigitalOutputValue (mdtDigitalIo *digitalOutput)
Set value on a digital output on physical device.
void runQueries ()
Queries to send periodically.
Signals inherited from mdtDevice
void stateChanged (int state)
mdtDeviceIos *pvIos; // I/O's container
void statusMessageChanged (const QString &message, const QString &details, int timeout)
Emitted when a new status message is to display.
Protected Slots inherited from mdtDevice
virtual void decodeReadenFrame (mdtPortTransaction *transaction)
Decode incoming frames.
Detailed Description
Base class for SCPI based instruments.
Most of current instruments (Agilent, NI, ...) support SCPI command format.
This class give some common functions requierd to handle such devices.
Currently, only USBTMC port is supported.
Definition at line 41 of file mdtDeviceScpi.h.
Constructor & Destructor Documentation
mdtDeviceScpi::mdtDeviceScpi (QObject * parent = 0)
Construct a SCPI device.
Will create and configure a USBTMC port manager.
Definition at line 32 of file mdtDeviceScpi.cpp.
References mdtPortManager::config(), pvUsbtmcPortManager, mdtPortConfig::readTimeout(), mdtDevice::setBackToReadyStateTimeout(), mdtPortConfig::setReadTimeout(), mdtDevice::stateChanged(), and mdtPortConfig::writeTimeout().
mdtDeviceScpi::~mdtDeviceScpi () virtual
Definition at line 55 of file mdtDeviceScpi.cpp.
References pvUsbtmcPortManager, and mdtDevice::stop().
Member Function Documentation
int mdtDeviceScpi::checkDeviceError ()
Query device about error.
Todo:
Buggy, review !
Will send the SYST:ERR? and return.
Subclass notes:
The SYST:ERR? query is sent to device. A new transaction is initalized, with type MDT_FC_SCPI_ERR. When subclass receives such transaction type, it should call handleDeviceError() without decoding frame.
Returns
0 if query could be sent or a error of type mdtAbstractPort::error_t else. Note: returned error is not device's error.
Definition at line 193 of file mdtDeviceScpi.cpp.
References mdtDevice::getNewTransaction(), pvUsbtmcPortManager, mdtFrameCodecScpi::QT_ERR, mdtUsbtmcPortManager::sendData(), mdtUsbtmcPortManager::sendReadRequest(), mdtPortTransaction::setQueryReplyMode(), and mdtPortTransaction::setType().
mdtAbstractPort::error_t mdtDeviceScpi::connectToDevice (const mdtDeviceInfo & devInfo) virtual
Search and connect to physical device.
Will scan available ports and open the first port that has device attached maching request.
Parameters
devInfo Requested device's informations.
Returns
A error listed in mdtAbstractPort::error_t (NoError on success)
Reimplemented from mdtDevice.
Reimplemented in mdtDeviceU3606A.
Definition at line 68 of file mdtDeviceScpi.cpp.
References mdtPortManager::isClosed(), mdtAbstractPort::NoError, portManager(), mdtAbstractPort::PortNotFound, mdtDeviceInfo::productId(), pvUsbtmcPortManager, mdtUsbtmcPortManager::scan(), mdtDeviceInfo::serialId(), mdtPortManager::setPortInfo(), mdtDevice::start(), mdtPortManager::stop(), mdtAbstractPort::UnhandledError, and mdtDeviceInfo::vendorId().
Referenced by mdtDeviceDSO1000A::connectToDevice(), and mdtDeviceU3606A::connectToDevice().
void mdtDeviceScpi::handleDeviceError (const QList< QVariant > & decodedValues) protected
Handle device error.
Todo:
Buggy, review !
This method is called from subclass's decodeReadenFrame(mdtPortTransaction) method when a frame of type MDT_FC_SCPI_ERR was received.
Errors <= 0 are handled directly. If error is > 0, handleDeviceSpecificError() is called.
See the SCPI99 standard for more details.
Parameters
decodedValues See mdtFrameCodecScpi::decodeError().
Postcondition
If internal codec has < 2 values, handleDeviceSpecificError() is not called.
Definition at line 218 of file mdtDeviceScpi.cpp.
References mdtError::commit(), mdtError::Error, handleDeviceSpecificError(), logDeviceError(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and mdtDevice::name().
void mdtDeviceScpi::handleDeviceSpecificError (int errNum, const QString & errText, const QList< QString > & deviceSpecificTexts) protected virtual
Handle device's specific error.
Todo:
Buggy, review !
This method is called from handleDeviceError().
This default implementation simply log the error (with mdtError system).
Parameters
errNum Error number
errText Error message
deviceSpecificTexts Device's specific informations
Precondition
Internal codec has at least 2 values.
Definition at line 268 of file mdtDeviceScpi.cpp.
References logDeviceError(), and mdtError::Warning.
Referenced by handleDeviceError().
void mdtDeviceScpi::logDeviceError (int errNum, const QString & errText, const QList< QString > & deviceSpecificTexts, mdtError::level_t level) protected
Log a device error with mdtError system.
Parameters
errNum Error number
errText Error message
deviceSpecificTexts Device's specific informations
Definition at line 275 of file mdtDeviceScpi.cpp.
References mdtError::commit(), MDT_DEVICE_ERROR, MDT_ERROR_SET_SRC, and mdtDevice::name().
Referenced by handleDeviceError(), and handleDeviceSpecificError().
mdtPortManager * mdtDeviceScpi::portManager () virtual
Get internal port manager instance.
Reimplemented from mdtDevice.
Definition at line 61 of file mdtDeviceScpi.cpp.
References pvUsbtmcPortManager.
Referenced by connectToDevice(), mdtDeviceU3606A::getMeasureConfiguration(), mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceU3606A::mdtDeviceU3606A(), and waitOperationComplete().
int mdtDeviceScpi::sendCommand (const QByteArray & command)
Send a command to device.
Wait until it's possible to write to device, then send the command.
Note that the wait will not break the GUI's event loop (see mdtPortManager::waitOnWriteReady() for details).
This method will not update internal device state. It's recommended to use mdtDevice functions if available.
Parameters
command Command to send.
Returns
bTag on success, or a error < 0 (see mdtUsbtmcPortManager::writeData() for details).
Definition at line 144 of file mdtDeviceScpi.cpp.
References pvUsbtmcPortManager, and mdtUsbtmcPortManager::sendCommand().
QByteArray mdtDeviceScpi::sendQuery (const QByteArray & query)
Send a query to device.
Wait until it's possible to write to device, send the query and wait until a response is available or timeout.
Note that the wait will not break the GUI's event loop.
This method will not update internal device and I/O states. It's recommended to use mdtDevice functions if available.
Parameters
query Query to send.
Returns
Result as string (empty string on error) Note that mdtFrameCodecScpi can be helpful to decode returned result.
Definition at line 149 of file mdtDeviceScpi.cpp.
References pvUsbtmcPortManager, and mdtUsbtmcPortManager::sendQuery().
Referenced by waitOperationComplete().
bool mdtDeviceScpi::waitOperationComplete (int timeout, int interval)
Wait until operation is complete (Using *OPC? query)
Currently, this method queries device with *OPC?.
Parameters
timeout Timeout [ms]
interval Interval between 2 *OPC? query [ms]
Precondition
interval > 0
Definition at line 154 of file mdtDeviceScpi.cpp.
References mdtDevice::isReady(), portManager(), and sendQuery().
Member Data Documentation
mdtUsbtmcPortManager* mdtDeviceScpi::pvUsbtmcPortManager protected
Definition at line 175 of file mdtDeviceScpi.h.
Referenced by checkDeviceError(), connectToDevice(), mdtDeviceDSO1000A::mdtDeviceDSO1000A(), mdtDeviceScpi(), mdtDeviceU3606A::mdtDeviceU3606A(), portManager(), sendCommand(), sendQuery(), and ~mdtDeviceScpi().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceScpi.h
src/mdtdevice/mdtDeviceScpi.cpp