Multi diag tools: mdtClArticleComponentDialog Class Reference
mdtClArticleComponentDialog Class Reference
#include <mdtClArticleComponentDialog.h>
Public Member Functions
mdtClArticleComponentDialog (QWidget *parent, QSqlDatabase db, QVariant articleId, QVariant componentId=QVariant())
Constructor.
~mdtClArticleComponentDialog ()
Destructor.
const QVariant & articleId () const
Get composite ID.
const QVariant & componentId () const
Get component ID.
const QVariant qty () const
Get qty of component.
const QVariant qtyUnit () const
Get qty unit.
Additional Inherited Members
Private Member Functions inherited from Ui_mdtClArticleComponentDialog
void setupUi (QDialog *mdtClArticleComponentDialog)
void retranslateUi (QDialog *mdtClArticleComponentDialog)
Private Attributes inherited from Ui_mdtClArticleComponentDialog
QVBoxLayout * verticalLayout
QHBoxLayout * horizontalLayout_2
QGroupBox * gbComponentData
QFormLayout * formLayout
QLabel * lbArticleCodeLabel
QLabel * lbArticleCode
QLabel * lbArticleDesignationENLabel
QLabel * lbArticleDesignationEN
QLabel * lbQty
QHBoxLayout * horizontalLayout
QDoubleSpinBox * sbQty
QLabel * lbUnit
QPushButton * pbSelect
QSpacerItem * horizontalSpacer
QDialogButtonBox * buttonBox
Detailed Description
Definition at line 34 of file mdtClArticleComponentDialog.h.
Constructor & Destructor Documentation
mdtClArticleComponentDialog::mdtClArticleComponentDialog (QWidget * parent, QSqlDatabase db, QVariant articleId, QVariant componentId = QVariant())
Constructor.
Definition at line 32 of file mdtClArticleComponentDialog.cpp.
References articleId(), mdtError::commit(), componentId(), mdtError::Error, MDT_DATABASE_ERROR, MDT_ERROR_SET_SRC, Ui_mdtClArticleComponentDialog::pbSelect, mdtError::setSystemError(), and Ui_mdtClArticleComponentDialog::setupUi().
mdtClArticleComponentDialog::~mdtClArticleComponentDialog ()
Destructor.
Definition at line 59 of file mdtClArticleComponentDialog.cpp.
Member Function Documentation
const QVariant & mdtClArticleComponentDialog::articleId () const
Get composite ID.
Definition at line 63 of file mdtClArticleComponentDialog.cpp.
Referenced by mdtClArticleComponentDialog().
const QVariant & mdtClArticleComponentDialog::componentId () const
Get component ID.
Definition at line 68 of file mdtClArticleComponentDialog.cpp.
Referenced by mdtClArticleComponentDialog().
const QVariant mdtClArticleComponentDialog::qty () const
Get qty of component.
Definition at line 73 of file mdtClArticleComponentDialog.cpp.
References Ui_mdtClArticleComponentDialog::sbQty.
const QVariant mdtClArticleComponentDialog::qtyUnit () const
Get qty unit.
Definition at line 78 of file mdtClArticleComponentDialog.cpp.
References Ui_mdtClArticleComponentDialog::lbUnit.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClArticleComponentDialog.h
src/mdttools/mdttesttool/mdtcablelist/mdtClArticleComponentDialog.cpp