Multi diag tools: mdtTtTestNode Class Reference
mdtTtTestNode Class Reference
#include <QModelIndex>
#include <mdtTtTestNode.h>
Public Member Functions
mdtTtTestNode (QObject *parent, QSqlDatabase db)
Constructor.
QString sqlForUnitSelection (const QVariant &VehicleTypeId)
Get SQL statement for units selection.
QString sqlForUnitSelectionByUnitIdList (const QList< QVariant > &unitIdList)
Get SQL statement for unit selection for given list of unit IDs.
QString sqlForUnitConnectionSelection (const QVariant &unitId)
Get SQL statement for unit connection selection.
QSqlRecord getTestNodeData (const QVariant &testNodeId, bool &ok)
Get test node data.
QList< QVariant > getIdListOfUnitConnectionsLinkedToUnitConnectionId (const QVariant &unitConnectionId)
Get a list of unit connection IDs that are linked (meaning wiered) to given unit connection ID.
QList< QVariant > getIdListOfUnitIdForUnitConnectionIdList (const QList< QVariant > &unitConnectionIdList)
Get a list of unit IDs for given list of unit connection IDs.
QList< QVariant > getIdListOfUnitConnectionsPartOfUnit (const QVariant &unitId)
Get a list of unit connection IDs that are part of given unit ID.
QList< QVariant > getChannelTestConnectionIdList (const QVariant &testNodeId, const QVariant &busName)
Get a list of channel test connections for given bus name and node ID.
bool addMissingConnections (const QVariant &testNodeId)
Update node unit connections of given test node.
bool addRelaysToGraph (const QVariant &testNodeId, mdtClPathGraph &graph, const QList< QVariant > &relaysToIgnoreIdList=QList< QVariant >())
Add (coupling and channel) relays to graph.
QList< mdtTtTestNodeUnitSetupData > getRelayPathSetupDataList (const QList< QVariant > &relayPathConnectionIdList, mdtClPathGraph &graph, bool &ok)
Get a list of test node unit setup data for a given path.
bool ensureAbsenceOfShortCircuit (const QVariant &connectionIdA, const QVariant &connectionIdB, const QList< mdtTtTestNodeUnitSetupData > &testNodeUnitSetupDataList, mdtClPathGraph &graph, bool &ok)
Check that enabling a set of coupling and channel relays does not produce a short circuit between connections A and B.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
bool addRecordList (const QList< mdtSqlRecord > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
#include <QModelIndex>
Helper class for test node edition
Definition at line 36 of file mdtTtTestNode.h.
Constructor & Destructor Documentation
mdtTtTestNode::mdtTtTestNode (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 29 of file mdtTtTestNode.cpp.
Member Function Documentation
bool mdtTtTestNode::addMissingConnections (const QVariant & testNodeId)
Update node unit connections of given test node.
For each unit contained in given test node, the missing connections (those that exist in UnitConnection_tbl but not in TestNodeUnitConnection_tbl) will be added in TestNodeUnitConnection_tbl.
Definition at line 214 of file mdtTtTestNode.cpp.
References mdtTtTestNodeUnit::addConnections(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtTtBase::getData(), mdtTtBase::lastError(), mdtTtBase::pvLastError, and mdtTtBase::rollbackTransaction().
bool mdtTtTestNode::addRelaysToGraph (const QVariant & testNodeId, mdtClPathGraph & graph, const QList< QVariant > & relaysToIgnoreIdList = QList<QVariant>())
Add (coupling and channel) relays to graph.
Will add all coupling and channel relays of given test node to graph as a link with a cost of 2. The user data will also contain unit ID of each relay.
Definition at line 246 of file mdtTtTestNode.cpp.
References mdtClPathGraph::addLink(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtClPathGraph::removeAddedLinks(), and mdtError::setError().
Referenced by mdtTtTestModel::generateTestModel().
bool mdtTtTestNode::ensureAbsenceOfShortCircuit (const QVariant & connectionIdA, const QVariant & connectionIdB, const QList< mdtTtTestNodeUnitSetupData > & testNodeUnitSetupDataList, mdtClPathGraph & graph, bool & ok)
Check that enabling a set of coupling and channel relays does not produce a short circuit between connections A and B.
Parameters
connectionIdA Fisrt connection from witch it must be checked about short circuit
connectionIdB Second connection from witch it must be checked about short circuit
testNodeUnitSetupDataList Test node unit setup data list of coupling and channel relays that will be turned on in given scenario
graph Graph object. Cable list must allready be loaded (see mdtClPathGraph::loadLinkList()).
ok Will be set false if a error occured, true else
Returns
True if a short circuit was detected, false if OK
Definition at line 328 of file mdtTtTestNode.cpp.
References mdtClPathGraph::addLink(), mdtError::commit(), mdtTtBase::database(), mdtError::Error, mdtTtTestNodeUnit::getConnectionIdListOfUnitId(), mdtClPathGraph::getShortestPath(), mdtTtBase::lastError(), mdtClPathGraph::lastError(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtClPathGraph::removeAddedLinks(), and mdtError::setError().
Referenced by mdtTtTestModel::generateTestModel().
QList< QVariant > mdtTtTestNode::getChannelTestConnectionIdList (const QVariant & testNodeId, const QVariant & busName)
Get a list of channel test connections for given bus name and node ID.
Definition at line 191 of file mdtTtTestNode.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QList< QVariant > mdtTtTestNode::getIdListOfUnitConnectionsLinkedToUnitConnectionId (const QVariant & unitConnectionId)
Get a list of unit connection IDs that are linked (meaning wiered) to given unit connection ID.
Definition at line 114 of file mdtTtTestNode.cpp.
References mdtTtBase::database(), and mdtTtBase::pvLastError.
QList< QVariant > mdtTtTestNode::getIdListOfUnitConnectionsPartOfUnit (const QVariant & unitId)
Get a list of unit connection IDs that are part of given unit ID.
Definition at line 168 of file mdtTtTestNode.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QList< QVariant > mdtTtTestNode::getIdListOfUnitIdForUnitConnectionIdList (const QList< QVariant > & unitConnectionIdList)
Get a list of unit IDs for given list of unit connection IDs.
Definition at line 135 of file mdtTtTestNode.cpp.
References mdtError::commit(), mdtTtBase::database(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
QList< mdtTtTestNodeUnitSetupData > mdtTtTestNode::getRelayPathSetupDataList (const QList< QVariant > & relayPathConnectionIdList, mdtClPathGraph & graph, bool & ok)
Get a list of test node unit setup data for a given path.
For each connection in given path, related test node unit id (i.e. relay ID) will be searched. For each relay that was found, a new setup data, with State set to true, is added to list.
Parameters
relayPathConnectionIdList List of connection ID of path (as returned by mdtClPathGraph::getShortestPath()).
graph Graph object. Relays must allready been loaded (see addRelaysToGraph()).
ok Will be set false if a error occured, true else
Definition at line 292 of file mdtTtTestNode.cpp.
References mdtSqlRecord::clearValues(), mdtError::commit(), mdtTtBase::database(), mdtError::Error, mdtClPathGraph::getUserData(), MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), mdtTtTestNodeUnitSetupData::setup(), and mdtSqlRecord::setValue().
Referenced by mdtTtTestModel::generateTestModel().
QSqlRecord mdtTtTestNode::getTestNodeData (const QVariant & testNodeId, bool & ok)
Get test node data.
Will include fields from TestNode_tbl and VehicleType_tbl.
Definition at line 90 of file mdtTtTestNode.cpp.
References mdtTtBase::getData().
QString mdtTtTestNode::sqlForUnitConnectionSelection (const QVariant & unitId)
Get SQL statement for unit connection selection.
Definition at line 70 of file mdtTtTestNode.cpp.
QString mdtTtTestNode::sqlForUnitSelection (const QVariant & VehicleTypeId)
Get SQL statement for units selection.
Give a list of units related to given TestNodeId (i.e. VehicleType ID) that are not currently linked to a TestNodeUnit .
Definition at line 34 of file mdtTtTestNode.cpp.
QString mdtTtTestNode::sqlForUnitSelectionByUnitIdList (const QList< QVariant > & unitIdList)
Get SQL statement for unit selection for given list of unit IDs.
Definition at line 51 of file mdtTtTestNode.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestNode.h
src/mdttools/mdttesttool/mdtTtTestNode.cpp