Multi diag tools: mdtUsbtmcTransferHandler Class Reference
mdtUsbtmcTransferHandler Class Reference
USBTMC transfer handler.
#include <mdtUsbtmcTransferHandler.h>
Public Member Functions
mdtUsbtmcTransferHandler (libusb_context *usbContext, mdtUsbtmcPort &port)
Constructor.
void setDeviceName (const QString &name)
Set device name.
bool setup (libusb_device_handle *handle, const mdtUsbDeviceDescriptor &descriptor, uint8_t bInterfaceNumber)
Setup handler.
void start ()
Start transfer handler.
void stop ()
Stop transfer handler.
bool hasInterruptInEndpoint () const
Check if current interface has a Interrupt-IN endpoint.
bool submitCommand (mdtUsbtmcTxMessage &message, bool responseExpected, unsigned int timeout)
Submit a command.
void getReceivedData (mdtUsbtmcRxMessage &message)
Get received data.
void submitStopRequest ()
Will cancel active transfers and change state to Stopping.
void submitBulkIoClear ()
Will cancel all pending bulk-OUT and bulk-IN transfers and request I/O buffer clear.
void beginBulkIoClear ()
Will cancel all pending bulk-OUT and bulk-IN transfers and request I/O buffer clear.
void dbgSubmitCustomBulkOutTransfer (uint8_t msgID, uint8_t bTag, uint8_t bTagInverse, uint32_t transferSize, uint8_t bmTransferAttributes, uint8_t termChar, bool responseExpected, int transferBufferLength, unsigned int timeout)
Submit a custom transfer.
void dbgSubmitAbortOnePendingBulkOutTransfer ()
Force to abort a pending Bulk-OUT transfer.
void dbgSubmitAbortOnePendingBulkInTransfer ()
Force to abort a pending Bulk-IN transfer.
void submitClearEndpointHalt (uint8_t endpointNumber, unsigned int timeout)
Submit a CLEAR_FEATURE control request with wValue = ENDPOINT_HALT for given endpoint.
void submitClearBulkOutEndpointHalt (unsigned int timeout)
Submit a CLEAR_FEATURE control request with wValue = ENDPOINT_HALT for Bulk-OUT endpoint.
void submitClearBulkInEndpointHalt (unsigned int timeout)
Submit a CLEAR_FEATURE control request with wValue = ENDPOINT_HALT for Bulk-IN endpoint.
void submitControlTransfersCancel ()
Submit control transfers cancellation.
mdtError lastError () const
Get last error.
bool mustBeStopped () const
Check if handler must be stopped.
void notifyError (const mdtError &error)
Notify error.
void notifyDeviceDisconnected ()
Notify device disconnected.
void notifyBulkIoDone ()
Notify Bulk I/O done.
void notifyBulkIoAborted ()
Notify Bulk I/O aborted.
template<typename EventType >
void sendEvent (EventType const &event)
Send a event to state machine.
bool hasPendingTransfers ()
Check if there are pending transfers.
void submitCancelAllTransfers ()
Submit cancellation of all pending transfers.
void restoreAllTransfers ()
Restore all pending transfers to their pool.
void handleControlTransferComplete (mdtUsbtmcControlTransfer *transfer)
Handle control transfer complete.
void restoreControlTransferToPool (mdtUsbtmcControlTransfer *transfer, bool lockMutex)
Restore control transfer to pool.
void handleBulkOutTransferComplete (mdtUsbtmcBulkTransfer *transfer)
Handle Bulk-OUT transfer complete.
bool hasPendingBulkOutTransfers ()
Check if there are pending Bulk-OUT transfers.
void restoreBulkOutTransferToPool (mdtUsbtmcBulkTransfer *transfer, bool lockMutex)
Restore bulk-OUT transfer to pool.
void restoreBulkOutTransferSA (mdtUsbtmcBulkTransfer *transfer)
Restore bulk-OUT transfer to pool.
void submitCancelAllBulkOutTransfers (bool lockMutex, mdtUsbtmcBulkTransfer::SplitAction_t action=mdtUsbtmcBulkTransfer::SplitAction_t::NoAction)
Submit cancel for all Bulk-OUT transfers.
void handleBulkInTransferComplete (mdtUsbtmcBulkTransfer *transfer)
Handle Bulk-IN transfer complete.
bool hasPendingBulkInTransfers ()
Check if there are pending Bulk-IN transfers.
void restoreBulkInTransferToPool (mdtUsbtmcBulkTransfer *transfer, bool lockMutex)
Restore bulk-IN transfer to pool.
void restoreBulkInTransferSA (mdtUsbtmcBulkTransfer *transfer)
Restore bulk-IN transfer to pool.
void submitCancelAllBulkInTransfers (bool lockMutex, mdtUsbtmcBulkTransfer::SplitAction_t action=mdtUsbtmcBulkTransfer::SplitAction_t::NoAction)
Submit cancel for all Bulk-IN transfers.
void submitInterruptInTransfer (unsigned int timeout, mdtUsbtmcInterruptTransfer *transfer=0)
Submit a Interrupt-IN transfer.
void handleInterruptInTransferComplete (mdtUsbtmcInterruptTransfer *transfer)
Handle Interrupt-IN transfer complete.
void restoreInterruptInTransferToPool (mdtUsbtmcInterruptTransfer *transfer, bool lockMutex)
Restore interrupt-IN transfer to pool.
void beginAbortBulkOut (mdtUsbtmcBulkTransfer *transfer)
Begin to abort bulk-OUT transfer.
void beginAbortBulkIn (mdtUsbtmcBulkTransfer *transfer)
Begin to abort bulk-IN transfer.
Static Public Member Functions
static void controlTransferCallback (libusb_transfer *transfer)
Control transfer callback.
static void bulkOutTransferCallback (libusb_transfer *transfer)
Bulk-OUT transfer callback.
static void bulkInTransferCallback (libusb_transfer *transfer)
Bulk-IN transfer callback.
static void interruptInTransferCallback (libusb_transfer *transfer)
Interrupt-IN transfer callback.
Detailed Description
USBTMC transfer handler.
Definition at line 50 of file mdtUsbtmcTransferHandler.h.
Constructor & Destructor Documentation
mdtUsbtmcTransferHandler::mdtUsbtmcTransferHandler (libusb_context * usbContext, mdtUsbtmcPort & port)
Constructor.
Definition at line 31 of file mdtUsbtmcTransferHandler.cpp.
Member Function Documentation
void mdtUsbtmcTransferHandler::beginAbortBulkIn (mdtUsbtmcBulkTransfer * transfer)
Begin to abort bulk-IN transfer.
At first, any pending Bulk-OUT transfers that expect a restonse will be cancelled (should be 0 or 1). Then, submitInitiateAbortBulkInRequest() is called.
See USBTMC 1.0 specifications, section 4.2.1.4 for details.
Definition at line 947 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::bTag(), and mdtUsbTransferPool< T >::getAllPendingTransfers().
void mdtUsbtmcTransferHandler::beginAbortBulkOut (mdtUsbtmcBulkTransfer * transfer)
Begin to abort bulk-OUT transfer.
Aborting will start, as mentionned in USBTMC 1.0, section 4.2.1.2, by cancelling the pending Bulk-OUT transfer, and passing INITIATE_ABORT_BULK_OUT split action, so that restoreBulkOutTransferSA knows that it must call submitInitiateAbortBulkOutRequest()
This function is called by state machine.
Definition at line 939 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::INITIATE_ABORT, and mdtUsbtmcBulkTransfer::setSplitAction().
void mdtUsbtmcTransferHandler::beginBulkIoClear ()
Will cancel all pending bulk-OUT and bulk-IN transfers and request I/O buffer clear.
Is called by state machine
Definition at line 230 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::INITIATE_CLEAR, mdtUsbTransferPool< T >::pendingTransferCount(), submitCancelAllBulkInTransfers(), and submitCancelAllBulkOutTransfers().
void mdtUsbtmcTransferHandler::bulkInTransferCallback (libusb_transfer * transfer) static
Bulk-IN transfer callback.
Definition at line 359 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::transferHandler().
Referenced by mdtUsbtmcBulkTransfer::setupBulkInRequest().
void mdtUsbtmcTransferHandler::bulkOutTransferCallback (libusb_transfer * transfer) static
Bulk-OUT transfer callback.
Definition at line 350 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::transferHandler().
Referenced by mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), and mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn().
void mdtUsbtmcTransferHandler::controlTransferCallback (libusb_transfer * transfer) static
Control transfer callback.
Definition at line 336 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransfer::isSync(), mdtUsbTransfer::setCompleted(), and mdtUsbtmcControlTransfer::transferHandler().
Referenced by mdtUsbtmcControlTransfer::setupCheckAbortBulkInStatus(), mdtUsbtmcControlTransfer::setupCheckAbortBulkOutStatus(), mdtUsbtmcControlTransfer::setupCheckClearStatus(), mdtUsbtmcControlTransfer::setupClearEndpointHalt(), mdtUsbtmcControlTransfer::setupGetCapabilities(), mdtUsbtmcControlTransfer::setupIndicatorPulse(), mdtUsbtmcControlTransfer::setupInitiateAbortBulkIn(), mdtUsbtmcControlTransfer::setupInitiateAbortBulkOut(), and mdtUsbtmcControlTransfer::setupInitiateClear().
void mdtUsbtmcTransferHandler::dbgSubmitAbortOnePendingBulkInTransfer ()
Force to abort a pending Bulk-IN transfer.
Will get a pending Bulk-IN transfer and proceed abort it. Used for debug and testing.
Definition at line 284 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::getPendingTransfer().
void mdtUsbtmcTransferHandler::dbgSubmitAbortOnePendingBulkOutTransfer ()
Force to abort a pending Bulk-OUT transfer.
Will get a pending Bulk-OUT transfer and proceed abort it. Used for debug and testing.
Definition at line 274 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::getPendingTransfer().
void mdtUsbtmcTransferHandler::dbgSubmitCustomBulkOutTransfer (uint8_t msgID, uint8_t bTag, uint8_t bTagInverse, uint32_t transferSize, uint8_t bmTransferAttributes, uint8_t termChar, bool responseExpected, int transferBufferLength, unsigned int timeout)
Submit a custom transfer.
Used for debug and testing.
Precondition
transferBufferLength must be <= Internal frame capacity
Definition at line 258 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::dbgSetupCustom(), mdtUsbTransferPool< T >::getTransfer(), mdtUsbTransfer::lastError(), and mdtUsbTransfer::submit().
void mdtUsbtmcTransferHandler::getReceivedData (mdtUsbtmcRxMessage & message)
Get received data.
Parameters
message USBTMC message in witch data will be appended.
Definition at line 208 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::getAllPendingTransfers(), and mdtUsbTransferPool< T >::restorePendingTransfers().
Referenced by mdtUsbtmcPort::sendQuery().
void mdtUsbtmcTransferHandler::handleBulkInTransferComplete (mdtUsbtmcBulkTransfer * transfer)
Handle Bulk-IN transfer complete.
Is called by state machine
Definition at line 698 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransfer::actualLength(), mdtUsbtmcBulkTransfer::bTag(), mdtUsbtmcBulkTransfer::bTagIsOk(), mdtUsbtmcBulkTransfer::CLEAR_ENDPOINT_HALT, mdtError::commit(), mdtError::Error, mdtUsbtmcBulkTransfer::isEOM(), MDT_ERROR_SET_SRC, mdtUsbTransferPool< T >::pendingTransferCount(), mdtUsbtmcBulkTransfer::receivedAllData(), mdtUsbTransferPool< T >::restorePendingTransfers(), mdtError::setError(), mdtUsbtmcPort::setError(), mdtError::setSystemError(), mdtUsbTransfer::status(), submitCancelAllBulkInTransfers(), mdtUsbtmcPort::thSetTransactionDone(), and mdtError::Warning.
void mdtUsbtmcTransferHandler::handleBulkOutTransferComplete (mdtUsbtmcBulkTransfer * transfer)
Handle Bulk-OUT transfer complete.
Is called by state machine
Definition at line 551 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::bTag(), mdtUsbtmcBulkTransfer::CLEAR_ENDPOINT_HALT, mdtUsbtmcFrame::DEV_DEP_MSG_IN, mdtUsbtmcFrame::DEV_DEP_MSG_OUT, mdtError::Error, MDT_ERROR_SET_SRC, mdtUsbtmcBulkTransfer::msgID(), mdtUsbtmcBulkTransfer::responseExpected(), restoreBulkOutTransferToPool(), mdtError::setSystemError(), mdtUsbTransfer::status(), submitCancelAllBulkOutTransfers(), mdtUsbtmcPort::thSetTransactionDone(), and mdtUsbTransfer::timeout().
void mdtUsbtmcTransferHandler::handleControlTransferComplete (mdtUsbtmcControlTransfer * transfer)
Handle control transfer complete.
Is called by state machine
Definition at line 460 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransfer::actualLength(), mdtUsbControlTransfer::bRequest(), mdtUsbtmcControlTransfer::CHECK_ABORT_BULK_IN_STATUS, mdtUsbtmcControlTransfer::CHECK_ABORT_BULK_OUT_STATUS, mdtUsbtmcControlTransfer::CHECK_CLEAR_STATUS, mdtError::Error, mdtUsbtmcControlTransfer::INITIATE_ABORT_BULK_IN, mdtUsbtmcControlTransfer::INITIATE_ABORT_BULK_OUT, mdtUsbtmcControlTransfer::INITIATE_CLEAR, MDT_ERROR_SET_SRC, mdtUsbTransferPool< T >::pendingTransferCount(), restoreControlTransferToPool(), mdtError::setSystemError(), mdtUsbTransfer::status(), mdtUsbtmcControlTransfer::usbtmcRequest(), and mdtUsbtmcControlTransfer::usbtmcRequestText().
void mdtUsbtmcTransferHandler::handleInterruptInTransferComplete (mdtUsbtmcInterruptTransfer * transfer)
Handle Interrupt-IN transfer complete.
Is called by state machine
Definition at line 892 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcInterruptTransfer::byteValue(), mdtError::Error, MDT_ERROR_SET_SRC, mdtError::setSystemError(), mdtUsbTransfer::status(), submitInterruptInTransfer(), and mdtUsbTransfer::timeout().
bool mdtUsbtmcTransferHandler::hasInterruptInEndpoint () const inline
Check if current interface has a Interrupt-IN endpoint.
Definition at line 79 of file mdtUsbtmcTransferHandler.h.
References mdtUsbEndpointDescriptor::isEmpty().
bool mdtUsbtmcTransferHandler::hasPendingBulkInTransfers () inline
Check if there are pending Bulk-IN transfers.
Is called by state machine
Definition at line 303 of file mdtUsbtmcTransferHandler.h.
References mdtUsbTransferPool< T >::pendingTransferCount().
bool mdtUsbtmcTransferHandler::hasPendingBulkOutTransfers () inline
Check if there are pending Bulk-OUT transfers.
Is called by state machine
Definition at line 264 of file mdtUsbtmcTransferHandler.h.
References mdtUsbTransferPool< T >::pendingTransferCount().
bool mdtUsbtmcTransferHandler::hasPendingTransfers ()
Check if there are pending transfers.
Is called by state machine
Definition at line 411 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::pendingTransferCount().
Referenced by restoreBulkInTransferSA(), and restoreBulkOutTransferSA().
void mdtUsbtmcTransferHandler::interruptInTransferCallback (libusb_transfer * transfer) static
Interrupt-IN transfer callback.
Definition at line 367 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcInterruptTransfer::transferHandler().
Referenced by mdtUsbtmcInterruptTransfer::setup().
mdtError mdtUsbtmcTransferHandler::lastError () const inline
Get last error.
Definition at line 178 of file mdtUsbtmcTransferHandler.h.
Referenced by mdtUsbtmcPort::openDevice(), mdtUsbtmcPort::sendCommand(), and mdtUsbtmcPort::sendQuery().
bool mdtUsbtmcTransferHandler::mustBeStopped () const
Check if handler must be stopped.
Is called by port thread to know if it must exit.
Definition at line 375 of file mdtUsbtmcTransferHandler.cpp.
void mdtUsbtmcTransferHandler::notifyBulkIoAborted ()
Notify Bulk I/O aborted.
Must be called only by state machine
Definition at line 400 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcPort::thSetTransactionAborted().
void mdtUsbtmcTransferHandler::notifyBulkIoDone ()
Notify Bulk I/O done.
Must be called only by state machine
Definition at line 395 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcPort::thSetTransactionDone().
void mdtUsbtmcTransferHandler::notifyDeviceDisconnected ()
Notify device disconnected.
Must be called only by state machine
Definition at line 390 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcPort::thSetDeviceDisconnected().
void mdtUsbtmcTransferHandler::notifyError (const mdtError & error)
Notify error.
Must be called only by state machine
Definition at line 380 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcPort::setError().
void mdtUsbtmcTransferHandler::restoreAllTransfers ()
Restore all pending transfers to their pool.
Is called by state machine
Definition at line 444 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::pendingTransferCount(), and mdtUsbTransferPool< T >::restorePendingTransfers().
void mdtUsbtmcTransferHandler::restoreBulkInTransferSA (mdtUsbtmcBulkTransfer * transfer)
Restore bulk-IN transfer to pool.
If, after transfer was restored, no more Bulk-IN transfer is pending, and given transfer contains a SplitAction, this action will be executed.
Is called by state machine
Definition at line 786 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::CHECK_ABORT_STATUS, mdtUsbtmcBulkTransfer::CHECK_CLEAR_STATUS, mdtUsbtmcBulkTransfer::CLEAR_ENDPOINT_HALT, mdtError::Error, hasPendingTransfers(), mdtUsbtmcBulkTransfer::INITIATE_ABORT, mdtUsbtmcBulkTransfer::INITIATE_CLEAR, MDT_ERROR_SET_SRC, mdtUsbtmcBulkTransfer::NoAction, mdtUsbTransferPool< T >::pendingTransferCount(), mdtUsbTransferPool< T >::restoreTransfer(), mdtError::setSystemError(), mdtUsbtmcBulkTransfer::splitAction(), and mdtUsbTransfer::status().
void mdtUsbtmcTransferHandler::restoreBulkInTransferToPool (mdtUsbtmcBulkTransfer * transfer, bool lockMutex)
Restore bulk-IN transfer to pool.
Definition at line 773 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::restoreTransfer().
void mdtUsbtmcTransferHandler::restoreBulkOutTransferSA (mdtUsbtmcBulkTransfer * transfer)
Restore bulk-OUT transfer to pool.
If, after transfer was restored, no more Bulk-OUT transfer is pending, and given transfer contains a SplitAction, this action will be executed.
Is called by state machine
Definition at line 612 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbtmcBulkTransfer::bTag(), mdtUsbtmcBulkTransfer::CHECK_ABORT_STATUS, mdtUsbtmcBulkTransfer::CHECK_CLEAR_STATUS, mdtUsbtmcBulkTransfer::CLEAR_ENDPOINT_HALT, mdtError::Error, hasPendingTransfers(), mdtUsbtmcBulkTransfer::INITIATE_ABORT, mdtUsbtmcBulkTransfer::INITIATE_CLEAR, MDT_ERROR_SET_SRC, mdtUsbtmcBulkTransfer::NoAction, mdtUsbTransferPool< T >::pendingTransferCount(), mdtUsbTransferPool< T >::restoreTransfer(), mdtError::setSystemError(), mdtUsbtmcBulkTransfer::splitAction(), and mdtUsbTransfer::status().
void mdtUsbtmcTransferHandler::restoreBulkOutTransferToPool (mdtUsbtmcBulkTransfer * transfer, bool lockMutex)
Restore bulk-OUT transfer to pool.
Is called by state machine
Definition at line 599 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::restoreTransfer().
Referenced by handleBulkOutTransferComplete().
void mdtUsbtmcTransferHandler::restoreControlTransferToPool (mdtUsbtmcControlTransfer * transfer, bool lockMutex)
Restore control transfer to pool.
Is called by state machine
Definition at line 538 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::restoreTransfer().
Referenced by handleControlTransferComplete().
void mdtUsbtmcTransferHandler::restoreInterruptInTransferToPool (mdtUsbtmcInterruptTransfer * transfer, bool lockMutex)
Restore interrupt-IN transfer to pool.
Is called by state machine
Definition at line 926 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::restoreTransfer().
template<typename EventType > void mdtUsbtmcTransferHandler::sendEvent (EventType const & event)
Send a event to state machine.
Used by internal state machine to send events.
This is needed, because only mdtUsbtmcTransferHandler instance contains a StateMachine object, witch locks the event mutex when calling process_event().
Definition at line 406 of file mdtUsbtmcTransferHandler.cpp.
void mdtUsbtmcTransferHandler::setDeviceName (const QString & name)
Set device name.
Device name is used to build error messages. See deviceIdString()
Definition at line 40 of file mdtUsbtmcTransferHandler.cpp.
Referenced by mdtUsbtmcPort::openDevice(), and mdtUsbtmcPort::setDeviceName().
bool mdtUsbtmcTransferHandler::setup (libusb_device_handle * handle, const mdtUsbDeviceDescriptor & descriptor, uint8_t bInterfaceNumber)
Setup handler.
Definition at line 46 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::allocTransfers(), mdtUsbInterfaceDescriptor::bInterfaceNumber(), mdtUsbInterfaceDescriptor::bulkInEndpoints(), mdtUsbInterfaceDescriptor::bulkOutEndpoints(), mdtError::commit(), mdtError::Error, mdtUsbInterfaceDescriptor::interruptInEndpoints(), mdtUsbInterfaceDescriptor::isEmpty(), mdtUsbDeviceDescriptor::isEmpty(), MDT_ERROR_SET_SRC, and mdtError::setError().
void mdtUsbtmcTransferHandler::start ()
Start transfer handler.
Definition at line 141 of file mdtUsbtmcTransferHandler.cpp.
void mdtUsbtmcTransferHandler::stop ()
Stop transfer handler.
Definition at line 146 of file mdtUsbtmcTransferHandler.cpp.
void mdtUsbtmcTransferHandler::submitBulkIoClear ()
Will cancel all pending bulk-OUT and bulk-IN transfers and request I/O buffer clear.
Once all transfers are cancelled, INITIATE_CLEAR and, if needed, CHECK_CLEAR_STATUS is sent to device.
Definition at line 225 of file mdtUsbtmcTransferHandler.cpp.
Referenced by mdtUsbtmcPort::clearBulkIo().
void mdtUsbtmcTransferHandler::submitCancelAllBulkInTransfers (bool lockMutex, mdtUsbtmcBulkTransfer::SplitAction_t action = mdtUsbtmcBulkTransfer::SplitAction_t::NoAction)
Submit cancel for all Bulk-IN transfers.
If a action is given as argument, it will be set to last transfer cancel request.
Is called by state machine
Definition at line 843 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::getAllPendingTransfers(), and mdtUsbtmcBulkTransfer::setSplitAction().
Referenced by beginBulkIoClear(), handleBulkInTransferComplete(), and submitCancelAllTransfers().
void mdtUsbtmcTransferHandler::submitCancelAllBulkOutTransfers (bool lockMutex, mdtUsbtmcBulkTransfer::SplitAction_t action = mdtUsbtmcBulkTransfer::SplitAction_t::NoAction)
Submit cancel for all Bulk-OUT transfers.
If a action is given as argument, it will be set to last transfer cancel request.
Is called by state machine
Definition at line 670 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::getAllPendingTransfers(), and mdtUsbtmcBulkTransfer::setSplitAction().
Referenced by beginBulkIoClear(), handleBulkOutTransferComplete(), and submitCancelAllTransfers().
void mdtUsbtmcTransferHandler::submitCancelAllTransfers ()
Submit cancellation of all pending transfers.
Is called by state machine
Definition at line 437 of file mdtUsbtmcTransferHandler.cpp.
References submitCancelAllBulkInTransfers(), and submitCancelAllBulkOutTransfers().
void mdtUsbtmcTransferHandler::submitClearBulkInEndpointHalt (unsigned int timeout) inline
Submit a CLEAR_FEATURE control request with wValue = ENDPOINT_HALT for Bulk-IN endpoint.
Definition at line 151 of file mdtUsbtmcTransferHandler.h.
References mdtUsbEndpointDescriptor::number(), and submitClearEndpointHalt().
void mdtUsbtmcTransferHandler::submitClearBulkOutEndpointHalt (unsigned int timeout) inline
Submit a CLEAR_FEATURE control request with wValue = ENDPOINT_HALT for Bulk-OUT endpoint.
Definition at line 144 of file mdtUsbtmcTransferHandler.h.
References mdtUsbEndpointDescriptor::number(), and submitClearEndpointHalt().
void mdtUsbtmcTransferHandler::submitClearEndpointHalt (uint8_t endpointNumber, unsigned int timeout)
Submit a CLEAR_FEATURE control request with wValue = ENDPOINT_HALT for given endpoint.
Definition at line 294 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::getTransfer(), mdtUsbTransfer::lastError(), mdtUsbtmcControlTransfer::setupClearEndpointHalt(), and mdtUsbTransfer::submit().
Referenced by submitClearBulkInEndpointHalt(), and submitClearBulkOutEndpointHalt().
bool mdtUsbtmcTransferHandler::submitCommand (mdtUsbtmcTxMessage & message, bool responseExpected, unsigned int timeout)
Submit a command.
Parameters
message USBTMC message that contains data to send. If all data are readen from message, EOM flag will be set in USBTMC transfer.
responseExpected If message is a query that expects a response, like *IDN?, set this flag.
timeout Timeout [ms]
Definition at line 151 of file mdtUsbtmcTransferHandler.cpp.
References mdtError::commit(), mdtError::Error, mdtUsbTransferPool< T >::getTransfer(), mdtUsbTransfer::lastError(), MDT_ERROR_SET_SRC, mdtUsbTransferPool< T >::pendingTransferCount(), mdtError::setError(), mdtUsbtmcBulkTransfer::setupDevDepMsgOut(), mdtUsbTransfer::submit(), and mdtError::Warning.
Referenced by mdtUsbtmcPort::sendCommand(), and mdtUsbtmcPort::sendQuery().
void mdtUsbtmcTransferHandler::submitControlTransfersCancel ()
Submit control transfers cancellation.
Definition at line 309 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransfer::cancel(), mdtUsbTransferPool< T >::getPendingTransfer(), and mdtUsbTransfer::lastError().
void mdtUsbtmcTransferHandler::submitInterruptInTransfer (unsigned int timeout, mdtUsbtmcInterruptTransfer * transfer = 0)
Submit a Interrupt-IN transfer.
Todo:
Check how to tell libusb that we want infinite timeout and adapt
Definition at line 872 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::getTransfer(), mdtUsbTransfer::lastError(), mdtUsbtmcInterruptTransfer::setup(), and mdtUsbTransfer::submit().
Referenced by handleInterruptInTransferComplete().
void mdtUsbtmcTransferHandler::submitStopRequest ()
Will cancel active transfers and change state to Stopping.
Definition at line 219 of file mdtUsbtmcTransferHandler.cpp.
References mdtUsbTransferPool< T >::pendingTransferCount().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbtmcTransferHandler.h
src/mdtport/mdtUsbtmcTransferHandler.cpp