Multi diag tools: mdtTtTest Class Reference
mdtTtTest Class Reference
Helper class to manipulate test data.
#include <mdtTtTest.h>
Public Member Functions
mdtTtTest (QObject *parent, QSqlDatabase db)
Constructor.
QVariant createTest (const QVariant &testModelId)
Set test data.
bool saveTest (const mdtSqlRecord &testRecord, const QList< mdtSqlRecord > &testItemRecords)
Save a test and related test items.
bool removeTest (const QVariant &testId)
Remove a test.
void resetTestItemCursor ()
Check if more test item is available.
mdtTtTestItemNodeSetupData getSetupData (const QVariant &testModelItemId, bool &ok)
Go to next test item.
mdtTtTestNodeSetupData getTestNodeSetupData (const QVariant &testModelItemId, const QString &nodeIdentification, bool &ok)
Get test node setup data for given testModelItemId and nodeIdentification.
QList< mdtClLinkData > getLinkDataListForRoute (const QVariant &connectionIdA, const QVariant &connectionIdB, const QList< mdtTtTestNodeUnitSetupData > &testNodeUnitSetupDataList, mdtClPathGraph &graph, bool &ok)
Get a list of links that are travsersed from connectionIdA to connectionIdB.
QList< mdtClLinkData > getLinkDataListForRoute (const mdtTtTestModelItemRouteData &routeData, mdtClPathGraph &graph, bool &ok)
Get a list of links that are travsersed for given route.
QList< mdtClLinkData > getLinkDataListForRoute (const QVariant &testNodeId, const QString &schemaPositionA, const QString &connectorA, const QString &contactA, const QString &schemaPositionB, const QString &connectorB, const QString &contactB, const QStringList &relaysToEnable, mdtClPathGraph &graph, bool &ok)
Get a list of links that are travsersed for given connections.
double linkPathResistance (const QList< mdtClLinkData > &linkDataList) const
Get link part resistance of a path.
QVariant getConnectionId (const QVariant &testNodeId, const QString &schemaPosition, const QString &connector, const QString &contact, bool &ok)
Get unit connection ID for given criteria.
Public Member Functions inherited from mdtTtBase
mdtTtBase (QObject *parent, QSqlDatabase db)
Constructor.
virtual ~mdtTtBase ()
Destructor.
QSqlDatabase database ()
Get database instance.
mdtError lastError ()
Get last error.
bool addRecord (const mdtSqlRecord &record, const QString &tableName)
Add a record to given table.
bool addRecord (const mdtSqlRecord &record, const QString &tableName, QSqlQuery &query)
Add a record to given table.
template<typename T >
bool addRecordList (const QList< T > &recordList, const QString &tableName, bool singleTransaction=false)
Add a list of records to given table.
QList< QSqlRecord > getData (const QString &sql, bool *ok=0, const QStringList &expectedFields=QStringList())
Get data for given sql statement.
template<typename T >
QList< T > getDataList (const QString &sql, bool &ok, const QStringList &expectedFields=QStringList())
Get data of type T for given sql statement.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QSqlRecord &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField, const QVariant &matchData)
Update data for given table.
bool updateRecord (const QString &tableName, const mdtSqlRecord &record, const QString &matchField1, const QVariant &key1, const QString &matchField2, const QVariant &key2)
Update data for given table.
bool removeData (const QString &tableName, const QStringList &fields, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QModelIndexList &indexes)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName, const QVariant &matchData)
Remove data from given table.
bool removeData (const QString &tableName, const QString &fieldName1, const QVariant &matchData1, const QString &fieldName2, const QVariant &matchData2)
Remove data from given table.
bool removeData (const QString &tableName, const mdtSqlTableSelection &s, bool handleTransaction)
Remove data in given selection from given table.
Static Public Member Functions
static bool isInRange (double x, double min, double max=std::numeric_limits< double >::max())
Set test item data.
static bool isInOkRange (double x, double limitMin, double limitMax)
Check if x is in OK range.
static bool isInLimitRange (double x, double limitMin, double limitMax, double failMin, double failMax)
Check if x is in limit range.
Additional Inherited Members
Protected Member Functions inherited from mdtTtBase
bool beginTransaction ()
Beginn manually a new transaction.
bool rollbackTransaction ()
Rollback manually a new transaction.
bool commitTransaction ()
Commit manually a new transaction.
QString sqlDataDelimiter (QVariant::Type type)
Get SQL data delimiter for given data type.
Protected Attributes inherited from mdtTtBase
mdtError pvLastError
Detailed Description
Helper class to manipulate test data.
Typical usage:
Do base initialization with setup()
Do signal/slot connections
Load data from database and start state machines with start()
Definition at line 58 of file mdtTtTest.h.
Constructor & Destructor Documentation
mdtTtTest::mdtTtTest (QObject * parent, QSqlDatabase db)
Constructor.
Definition at line 41 of file mdtTtTest.cpp.
Member Function Documentation
QVariant mdtTtTest::createTest (const QVariant & testModelId)
Set test data.
Will also emit testDataChanged()
Note: data are not sent to database.void setTestData(const mdtTtTestData & data);
Set test data value
Will also emit testDataChanged()
Note: value is not sent to database.void setTestDataValue(const QString & fieldName, const QVariant & value);
Get test data
Returns data from Test_viewQSqlRecord testData() const;
Get test data value for given fieldName
Note: return cached data (will not get them from database).QVariant testDataValue(const QString & fieldName) const;
Create a new test based on given testModelId
Will also create test items.
Returns
Test ID of created test or a Null value on error.
void mdtTtTest::setTestData(const mdtTtTestData& data) { bool newTestId;
newTestId = (data.value("Id_PK") != pvTestData.value("Id_PK")); pvTestData = data; pvTestDataAreSaved = false; if(newTestId){ /updateCurrentTestRow(data.value("Id_PK")); resetTestItemTableModels(); } /emit testDataChanged(pvTestData); } void mdtTtTest::setTestDataValue(const QString& fieldName, const QVariant& value) { bool newTestId = false;
if(fieldName == "Id_PK"){ newTestId = (value != pvTestData.value("Id_PK")); } pvTestData.setValue(fieldName, value); pvTestDataAreSaved = false; if(newTestId){ resetTestItemTableModels(); } /emit testDataChanged(pvTestData); } QSqlRecord mdtTtTest::testData() const { return pvTestViewTableModel->record(pvCurrentTestRow); }
Definition at line 88 of file mdtTtTest.cpp.
References mdtSqlRecord::addAllFields(), mdtTtBase::addRecord(), mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::database(), mdtSqlRecord::lastError(), mdtTtBase::pvLastError, mdtTtBase::rollbackTransaction(), and mdtSqlRecord::setValue().
QVariant mdtTtTest::getConnectionId (const QVariant & testNodeId, const QString & schemaPosition, const QString & connector, const QString & contact, bool & ok)
Get unit connection ID for given criteria.
Parameters
testNodeId ID of test node (primary key)
schemaPositionA Schema position that contains connection
connectorA Name of connector that contains connection
contactA Name of contact that contains connection
Definition at line 579 of file mdtTtTest.cpp.
References mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, mdtError::setError(), and mdtError::setSystemError().
Referenced by getLinkDataListForRoute().
QList< mdtClLinkData > mdtTtTest::getLinkDataListForRoute (const QVariant & connectionIdA, const QVariant & connectionIdB, const QList< mdtTtTestNodeUnitSetupData > & testNodeUnitSetupDataList, mdtClPathGraph & graph, bool & ok)
Get a list of links that are travsersed from connectionIdA to connectionIdB.
Usefull to get all links of a route in a coupler (test node), for example from a test connection to a measure connection.
Parameters
connectionIdA Starting connection (f.ex. a measure connection)
connectionIdB Ending connection (f.ex. a test connection)
testNodeUnitSetupDataList Test node unit setup data list of coupling and channel relays that are turned on
graph Graph object. Cable list must allready be loaded (see mdtClPathGraph::loadLinkList()).
ok Will be set false if a error occured, true else
Definition at line 507 of file mdtTtTest.cpp.
References mdtTtBase::database(), mdtTtTestNode::getLinkDataListForPath(), mdtTtBase::lastError(), and mdtTtBase::pvLastError.
Referenced by getLinkDataListForRoute().
QList< mdtClLinkData > mdtTtTest::getLinkDataListForRoute (const mdtTtTestModelItemRouteData & routeData, mdtClPathGraph & graph, bool & ok)
Get a list of links that are travsersed for given route.
Usefull to get all links of a route in a coupler (test node), for example from a test connection to a measure connection.
Parameters
routeData Data that contains route from test connection and measure connection. Must also include setup data list of relays to enable.
graph Graph object. Cable list must allready be loaded (see mdtClPathGraph::loadLinkList()).
ok Will be set false if a error occured, true else
Definition at line 522 of file mdtTtTest.cpp.
References getLinkDataListForRoute(), mdtTtTestModelItemRouteData::measureConnectionId(), mdtTtTestModelItemRouteData::setupDataList(), and mdtTtTestModelItemRouteData::testConnectionId().
QList< mdtClLinkData > mdtTtTest::getLinkDataListForRoute (const QVariant & testNodeId, const QString & schemaPositionA, const QString & connectorA, const QString & contactA, const QString & schemaPositionB, const QString & connectorB, const QString & contactB, const QStringList & relaysToEnable, mdtClPathGraph & graph, bool & ok)
Get a list of links that are travsersed for given connections.
Usefull to get all links of a route in a coupler (test node), for example from a test connection to a measure connection.
Parameters
testNodeId ID of test node (primary key)
schemaPositionA Schema position that contains connection A
connectorA Name of connector that contains connection A
contactA Name of contact that contains connection A
schemaPositionB Schema position that contains connection B
connectorB Name of connector that contains connection B
contactB Name of contact that contains connection B
relaysToEnable List of coupling and channel relays that are turned on (give schema position for each)
graph Graph object. Cable list must allready be loaded (see mdtClPathGraph::loadLinkList()).
ok Will be set false if a error occured, true else
Definition at line 527 of file mdtTtTest.cpp.
References getConnectionId(), and getLinkDataListForRoute().
mdtTtTestItemNodeSetupData mdtTtTest::getSetupData (const QVariant & testModelItemId, bool & ok)
Go to next test item.
Returns
The test item ID
Get setup data for given test model item ID
This version is usefull for complex test items with many nodes, and handle stepNumber.
Q_ASSERT(pvTestItemViewTableModel);
QModelIndex index; int col;
col = pvTestItemViewTableModel->fieldIndex("Id_PK"); Q_ASSERT(col >= 0); index = pvTestItemViewTableModel->index(pvCurrentTestItemRow, col);
///
Todo:
Provisoire ! col = pvTestItemViewTableModel->fieldIndex("SequenceNumber"); QModelIndex index2; index2 = pvTestItemViewTableModel->index(pvCurrentTestItemRow, col); qDebug() << "mdtTtTest - current seq #: " << pvTestItemViewTableModel->data(index2);
return pvTestItemViewTableModel->data(index); if(!addRouteDataToTestNodeSetupData(tnSetupData, testModelItemId, nodeIdList.at(i))){ ok = false; return tiSetupData; } if(!addNodeUnitSetupDataToTestNodeSetupData(tnSetupData, testModelItemId, nodeIdList.at(i))){ ok = false; return tiSetupData; } // Add all unit setup data that are part of current node for(k = 0; k < dataList.size(); ++k){ id = dataList.at(k).value("TestNode_Id_FK").toInt(); if(nodeIdList.at(i) == id){ tnuSetupData = dataList.at(k); if(tnSetupData.nodeIdentification().isEmpty()){ tnSetupData.setNodeIdentification(tnuSetupData.value("NodeIdentification").toString()); } tnSetupData.addUnitSetup(tnuSetupData); } }
Definition at line 454 of file mdtTtTest.cpp.
References mdtTtTestItemNodeSetupData::addNodeSetupData().
mdtTtTestNodeSetupData mdtTtTest::getTestNodeSetupData (const QVariant & testModelItemId, const QString & nodeIdentification, bool & ok)
Get test node setup data for given testModelItemId and nodeIdentification.
This version is usefull for single test items. StepNumber is not handled here.
Will also include related route data, and other setup data that are not related to any route.
Definition at line 480 of file mdtTtTest.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, mdtTtBase::pvLastError, and mdtError::setError().
bool mdtTtTest::isInLimitRange (double x, double limitMin, double limitMax, double failMin, double failMax) static
Check if x is in limit range.
Return true if x is in ]failMin;limitMin] or in [limitMax;failMax[
Definition at line 314 of file mdtTtTest.cpp.
bool mdtTtTest::isInOkRange (double x, double limitMin, double limitMax) static
Check if x is in OK range.
Return true if x is in ]limitMin;limitMax[
Definition at line 309 of file mdtTtTest.cpp.
bool mdtTtTest::isInRange (double x, double min, double max = std::numeric_limits<double>::max()) static
Set test item data.
Set current test item data
Note: will not save to database. Use saveCurrentTest() for that.
Get current test item data
Note: will return cached value.
Set measured value to current test item
Will first check if given value has -OL or +OL flag, and set resulting value to, respectiveley, -inf or +inf if true.
The resulting value is then compared to expected one, and result is alos determined.
Finally, all values are stored to current test item, but only cached (see setCurrentTestItemData()).
Note: instrumentRangeMin and instrumentRangeMax are only informative, they are stored as they are given. For proper limit evaluation, only mdtValue's flags are used.
Check if x is in range
Return true if x is in [min;max]
QVariant testItemId; int testItemViewCol; int testItemTableRow, testItemTableCol; QModelIndex index; if(pvTestItemViewTableModel->rowCount() < 1){ return; } // Get column index of fieldName testItemViewCol = pvTestItemViewTableModel->fieldIndex(fieldName); Q_ASSERT(testItemViewCol >= 0); testItemTableCol = pvTestItemTableModel->fieldIndex(fieldName); Q_ASSERT(testItemTableCol >= 0); // Get corresponding row in TestItem_view testItemId = pvTestItemViewTableModel->record(pvCurrentTestItemRow).value("Id_PK"); Q_ASSERT(!testItemId.isNull()); testItemTableRow = getTestItemTableModelIndexRow(testItemId); Q_ASSERT(testItemTableRow >= 0); // Set value index = pvTestItemViewTableModel->index(pvCurrentTestItemRow, testItemViewCol); pvTestItemViewTableModel->setData(index, data); index = pvTestItemTableModel->index(testItemTableRow, testItemTableCol); pvTestItemTableModel->setData(index, data); int testItemViewCol; QModelIndex index;
if(pvTestItemViewTableModel->rowCount() < 1){ return QVariant(); } testItemViewCol = pvTestItemViewTableModel->fieldIndex(fieldName); Q_ASSERT(testItemViewCol >= 0); index = pvTestItemViewTableModel->index(pvCurrentTestItemRow, testItemViewCol);
return pvTestItemViewTableModel->data(index);
Todo:
Use mdtAlgorithme !
Definition at line 303 of file mdtTtTest.cpp.
Referenced by mdtTtAbstractTestNodeCalibrationTool::isInRange().
double mdtTtTest::linkPathResistance (const QList< mdtClLinkData > & linkDataList) const
Get link part resistance of a path.
Definition at line 559 of file mdtTtTest.cpp.
References mdtClLinkData::endConnectionData(), mdtClLinkData::startConnectionData(), and mdtSqlRecord::value().
bool mdtTtTest::removeTest (const QVariant & testId)
Remove a test.
Will also remove test items.
Definition at line 147 of file mdtTtTest.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::removeData(), and mdtTtBase::rollbackTransaction().
void mdtTtTest::resetTestItemCursor ()
Check if more test item is available.
Reset the test item cursor
if(pvCurrentTestItemRow < (pvTestItemViewTableModel->rowCount() - 1)){ return true; } if(pvTestItemViewTableModel->canFetchMore()){ pvTestItemViewTableModel->fetchMore(); return true; }
Definition at line 340 of file mdtTtTest.cpp.
bool mdtTtTest::saveTest (const mdtSqlRecord & testRecord, const QList< mdtSqlRecord > & testItemRecords)
Save a test and related test items.
Definition at line 121 of file mdtTtTest.cpp.
References mdtTtBase::beginTransaction(), mdtTtBase::commitTransaction(), mdtTtBase::rollbackTransaction(), mdtTtBase::updateRecord(), and mdtSqlRecord::value().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTest.h
src/mdttools/mdttesttool/mdtTtTest.cpp