Multi diag tools: mdtUicNumberItem Class Reference
mdtUicNumberItem Class Reference
UIC Number item.
#include <mdtUicNumberItem.h>
Public Member Functions
mdtUicNumberItem ()
Create a unknow item.
~mdtUicNumberItem ()
void setNumber (int number)
Set numerical value.
bool setNumber (const QString &number)
Set numerical value.
int number ()
Get numerical value.
void setCode (const QString &code)
Set code string.
QString & code ()
Get code string.
void setNameFr (const QString &name)
Set the name string for french.
QString & nameFr ()
Get the name string in french.
void setNameEn (const QString &name)
Set the name string for english.
QString & nameEn ()
Get the name string in english.
void setNameDe (const QString &name)
Set the name string for german.
QString & nameDe ()
Get the name string in german.
QString & name (const QLocale &locale)
Get the name string in language given in locale.
Detailed Description
UIC Number item.
See Also
mdtUicNumber
Definition at line 30 of file mdtUicNumberItem.h.
Constructor & Destructor Documentation
mdtUicNumberItem::mdtUicNumberItem ()
Create a unknow item.
A unknow item has unknow names
Definition at line 25 of file mdtUicNumberItem.cpp.
mdtUicNumberItem::~mdtUicNumberItem ()
Definition at line 34 of file mdtUicNumberItem.cpp.
Member Function Documentation
QString & mdtUicNumberItem::code ()
Get code string.
See Also
setCode()
Definition at line 68 of file mdtUicNumberItem.cpp.
Referenced by setCode().
QString & mdtUicNumberItem::name (const QLocale & locale)
Get the name string in language given in locale.
If langugage given in locale not exists, english name is returned
Definition at line 109 of file mdtUicNumberItem.cpp.
References nameDe(), nameEn(), and nameFr().
Referenced by setNameDe(), setNameEn(), and setNameFr().
QString & mdtUicNumberItem::nameDe ()
Get the name string in german.
Definition at line 104 of file mdtUicNumberItem.cpp.
Referenced by name().
QString & mdtUicNumberItem::nameEn ()
Get the name string in english.
Definition at line 92 of file mdtUicNumberItem.cpp.
Referenced by name().
QString & mdtUicNumberItem::nameFr ()
Get the name string in french.
Definition at line 80 of file mdtUicNumberItem.cpp.
Referenced by name().
int mdtUicNumberItem::number ()
Get numerical value.
Definition at line 56 of file mdtUicNumberItem.cpp.
Referenced by mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), mdtUicNumber::loadUsagesDb(), and setNumber().
void mdtUicNumberItem::setCode (const QString & code)
Set code string.
Code string is used for country code (CH, FR, ...)
Definition at line 61 of file mdtUicNumberItem.cpp.
References code().
Referenced by mdtUicNumber::loadCountriesDb().
void mdtUicNumberItem::setNameDe (const QString & name)
Set the name string for german.
Definition at line 97 of file mdtUicNumberItem.cpp.
References name().
Referenced by mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), and mdtUicNumber::loadUsagesDb().
void mdtUicNumberItem::setNameEn (const QString & name)
Set the name string for english.
Definition at line 85 of file mdtUicNumberItem.cpp.
References name().
Referenced by mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), and mdtUicNumber::loadUsagesDb().
void mdtUicNumberItem::setNameFr (const QString & name)
Set the name string for french.
Definition at line 73 of file mdtUicNumberItem.cpp.
References name().
Referenced by mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), and mdtUicNumber::loadUsagesDb().
void mdtUicNumberItem::setNumber (int number)
Set numerical value.
Definition at line 38 of file mdtUicNumberItem.cpp.
References number().
Referenced by mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), and mdtUicNumber::loadUsagesDb().
bool mdtUicNumberItem::setNumber (const QString & number)
Set numerical value.
Overloaded method.
Returns
True if ok, false on conversion error
Definition at line 43 of file mdtUicNumberItem.cpp.
The documentation for this class was generated from the following files:
src/mdtutils/mdtUicNumberItem.h
src/mdtutils/mdtUicNumberItem.cpp