Multi diag tools: mdtSerialPortSetupDialog Class Reference
mdtSerialPortSetupDialog Class Reference
Setup dialog for serial port.
#include <mdtSerialPortSetupDialog.h>
Public Member Functions
mdtSerialPortSetupDialog (QWidget *parent=0)
void setPortManager (mdtSerialPortManager *manager)
Set the serial port manager instance.
Public Member Functions inherited from mdtAbstractPortSetupDialog
mdtAbstractPortSetupDialog (QWidget *parent=0)
Constructor.
~mdtAbstractPortSetupDialog ()
Destructor.
void setPortManager (mdtPortManager *portManager)
Set the port manager.
mdtPortManager * portManager ()
Get port manager.
Additional Inherited Members
Public Attributes inherited from Ui_mdtAbstractPortSetupDialog
QVBoxLayout * verticalLayout
QTabWidget * twOptions
QWidget * tab
QHBoxLayout * bottomLayout
QSpacerItem * horizontalSpacer
QDialogButtonBox * buttonBox
Protected Slots inherited from mdtAbstractPortSetupDialog
void showStatusMessage (const QString &message, int timeout=0)
Used to show a message in status widget.
void showStatusMessage (const QString &message, const QString &details, int timeout=0)
Used to show a message and details in status widget.
Protected Member Functions inherited from mdtAbstractPortSetupDialog
virtual void portManagerSet ()
Called by setPortManager()
void setHeaderWidget (QWidget *w)
Set the header widget.
void addOptionsTabWidget (QWidget *w, const QString &label)
Add a widget to the options tab.
void setOkButtonEnabled (bool enabled)
Enable/disable Ok button.
void setApplyButtonEnabled (bool enabled)
Enable/disable Apply button.
void setCancelButtonEnabled (bool enabled)
Enable/disable Cancel button.
Detailed Description
Setup dialog for serial port.
The first step before display this dialog is to set the port manager with setPortManager()
Definition at line 41 of file mdtSerialPortSetupDialog.h.
Constructor & Destructor Documentation
mdtSerialPortSetupDialog::mdtSerialPortSetupDialog (QWidget * parent = 0)
Definition at line 30 of file mdtSerialPortSetupDialog.cpp.
References mdtAbstractPortSetupDialog::addOptionsTabWidget(), mdtAbstractPortSetupDialog::setHeaderWidget(), and mdtPortInfoCbHandler::setPortsComboBox().
Member Function Documentation
void mdtSerialPortSetupDialog::setPortManager (mdtSerialPortManager * manager)
Set the serial port manager instance.
Precondition
manager must be a valid pointer
Definition at line 66 of file mdtSerialPortSetupDialog.cpp.
References mdtAbstractPortSetupDialog::setPortManager().
The documentation for this class was generated from the following files:
src/mdtserialport/mdtSerialPortSetupDialog.h
src/mdtserialport/mdtSerialPortSetupDialog.cpp