Multi diag tools: mdtDeviceIosSegment Class Reference
mdtDeviceIosSegment Class Reference
Store a segment of device I/O list.
#include <mdtDeviceIosSegment.h>
Public Member Functions
mdtDeviceIosSegment ()
Constructor.
~mdtDeviceIosSegment ()
Destructor.
void setIos (const QList< mdtAnalogIo * > &ios)
Set the I/O's values and address range for this segment.
void setIos (const QList< mdtDigitalIo * > &ios)
int startAddressRead () const
Get start address for read access.
int startAddressWrite () const
Get start address for write access.
int endAddressRead () const
Get end address for read access.
int endAddressWrite () const
Get end address for write access.
int ioCount () const
Get number of I/O's.
bool containsAddressRead (int address) const
Check if segment contains a address for read access.
QList< int > addressesRead () const
Get a list of contigous addresses for read access.
bool containsAddressWrite (int address) const
Check if segment contains a address for write access.
QList< int > addressesWrite () const
Get a list of contigous addresses for write access.
int setValues (const QList< mdtValue > &values, int max=-1)
Set values.
int setValues (const QList< QVariant > &values, int max=-1)
int updateValuesFromAddressRead (int startAddress, const QList< mdtValue > &values, int max=-1)
Update some values starting at address read.
int updateValuesFromAddressRead (int startAddress, const QList< QVariant > &values, int max=-1)
int updateValuesFromAddressWrite (int startAddress, const QList< mdtValue > &values, int max=-1)
Update some values starting at address write.
int updateValuesFromAddressWrite (int startAddress, const QList< QVariant > &values, int max=-1)
QList< mdtValue > values () const
Get list of stored I/O's values.
QList< int > valuesInt () const
Get list of stored I/O's values.
QList< double > valuesDouble () const
Get list of stored I/O's values.
QList< bool > valuesBool () const
Get list of stored I/O's values.
Detailed Description
Store a segment of device I/O list.
A physical device, such as a modular I/O controller (f.ex. Wago 750) can contain severa modules. Some of them can be analog I/O, digital I/O or more complex module.
This class is a container that helps mdtDevice and mdtDeviceIos to deal with I/O mapping for multiple I/O read/write. Typically, some I/O can be present in mdtDeviceIos, but are not data I/O (but, f.ex. configuration registers). A other problem is that it can happen that I/O are not present in contigous range, but in several segments (f.ex. analog inputs from 0x200 -> 0x500, then 0x3000 -> 0x3500, ...)
Definition at line 45 of file mdtDeviceIosSegment.h.
Constructor & Destructor Documentation
mdtDeviceIosSegment::mdtDeviceIosSegment ()
Constructor.
Will set default values:
startAddress : 0
endAddress : 0
ioCount : 0
Definition at line 26 of file mdtDeviceIosSegment.cpp.
mdtDeviceIosSegment::~mdtDeviceIosSegment ()
Destructor.
Definition at line 30 of file mdtDeviceIosSegment.cpp.
Member Function Documentation
QList< int > mdtDeviceIosSegment::addressesRead () const
Get a list of contigous addresses for read access.
Definition at line 124 of file mdtDeviceIosSegment.cpp.
QList< int > mdtDeviceIosSegment::addressesWrite () const
Get a list of contigous addresses for write access.
Definition at line 158 of file mdtDeviceIosSegment.cpp.
bool mdtDeviceIosSegment::containsAddressRead (int address) const
Check if segment contains a address for read access.
Definition at line 109 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDeviceIos::updateAnalogInputValues(), mdtDeviceIos::updateAnalogOutputValues(), mdtDeviceIos::updateDigitalInputValues(), and mdtDeviceIos::updateDigitalOutputValues().
bool mdtDeviceIosSegment::containsAddressWrite (int address) const
Check if segment contains a address for write access.
Definition at line 143 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDeviceIos::updateAnalogOutputValues(), and mdtDeviceIos::updateDigitalOutputValues().
int mdtDeviceIosSegment::endAddressRead () const
Get end address for read access.
Definition at line 86 of file mdtDeviceIosSegment.cpp.
int mdtDeviceIosSegment::endAddressWrite () const
Get end address for write access.
Definition at line 95 of file mdtDeviceIosSegment.cpp.
int mdtDeviceIosSegment::ioCount () const
Get number of I/O's.
Definition at line 104 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDevice::getAnalogInputs(), mdtDevice::getAnalogOutputs(), mdtDevice::getDigitalInputs(), mdtDevice::getDigitalOutputs(), mdtDevice::setAnalogOutputs(), mdtDevice::setDigitalOutputs(), mdtDeviceIos::updateAnalogInputValues(), mdtDeviceIos::updateAnalogOutputValues(), mdtDeviceIos::updateDigitalInputValues(), and mdtDeviceIos::updateDigitalOutputValues().
void mdtDeviceIosSegment::setIos (const QList< mdtAnalogIo * > & ios)
Set the I/O's values and address range for this segment.
Parameters
isInput If true, the I/O's readAddress will be used, else the writeAddress
Precondition
List of I/O's must be sorted by address and not contain holes (i.e. contigous address range)
Definition at line 34 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDeviceIos::addAnalogInput(), mdtDeviceIos::addAnalogOutput(), mdtDeviceIos::addDigitalInput(), and mdtDeviceIos::addDigitalOutput().
void mdtDeviceIosSegment::setIos (const QList< mdtDigitalIo * > & ios)
Definition at line 51 of file mdtDeviceIosSegment.cpp.
int mdtDeviceIosSegment::setValues (const QList< mdtValue > & values, int max = -1)
Set values.
This method assumes that values list is sorted exactly the same way than ios list set with setIos()
If values list contains less items than stored I/O's values, only the first ones will be updated. If values list contains more items than stored I/O's values, all I/O's values are updated, and rest of values are ignored. If max > -1, same rules but not more than max items are stored.
Returns
Number of I/O's updated
Definition at line 177 of file mdtDeviceIosSegment.cpp.
int mdtDeviceIosSegment::setValues (const QList< QVariant > & values, int max = -1)
Definition at line 195 of file mdtDeviceIosSegment.cpp.
int mdtDeviceIosSegment::startAddressRead () const
Get start address for read access.
Definition at line 68 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDevice::getAnalogInputs(), mdtDevice::getAnalogOutputs(), mdtDevice::getDigitalInputs(), mdtDevice::getDigitalOutputs(), mdtDeviceIos::updateAnalogInputValues(), mdtDeviceIos::updateAnalogOutputValues(), mdtDeviceIos::updateDigitalInputValues(), and mdtDeviceIos::updateDigitalOutputValues().
int mdtDeviceIosSegment::startAddressWrite () const
Get start address for write access.
Definition at line 77 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDevice::setAnalogOutputs(), mdtDevice::setDigitalOutputs(), mdtDeviceIos::updateAnalogOutputValues(), mdtDeviceIos::updateDigitalOutputValues(), mdtDeviceModbus::writeAnalogOutputs(), and mdtDeviceModbus::writeDigitalOutputs().
int mdtDeviceIosSegment::updateValuesFromAddressRead (int startAddress, const QList< mdtValue > & values, int max = -1)
Update some values starting at address read.
Note: some checking are made:
If startAddress was not found, 0 values will be updated
If values contains to much items, only items that can be stored are updated
If max > -1 , the minimum between values size, internall items count and max will be updated
Returns
Number of updated values
Definition at line 227 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDeviceIos::updateAnalogInputValues(), mdtDeviceIos::updateAnalogOutputValues(), mdtDeviceIos::updateDigitalInputValues(), and mdtDeviceIos::updateDigitalOutputValues().
int mdtDeviceIosSegment::updateValuesFromAddressRead (int startAddress, const QList< QVariant > & values, int max = -1)
Definition at line 261 of file mdtDeviceIosSegment.cpp.
int mdtDeviceIosSegment::updateValuesFromAddressWrite (int startAddress, const QList< mdtValue > & values, int max = -1)
Update some values starting at address write.
Note: some checking are made:
If startAddress was not found, 0 values will be updated
If values contains to much items, only items that can be stored are updated
If max > -1 , the minimum between values size, internall items count and max will be updated
Returns
Number of updated values
Definition at line 309 of file mdtDeviceIosSegment.cpp.
int mdtDeviceIosSegment::updateValuesFromAddressWrite (int startAddress, const QList< QVariant > & values, int max = -1)
Definition at line 343 of file mdtDeviceIosSegment.cpp.
QList< mdtValue > mdtDeviceIosSegment::values () const
Get list of stored I/O's values.
Definition at line 391 of file mdtDeviceIosSegment.cpp.
QList< bool > mdtDeviceIosSegment::valuesBool () const
Get list of stored I/O's values.
Definition at line 430 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDeviceModbus::writeDigitalOutputs().
QList< double > mdtDeviceIosSegment::valuesDouble () const
Get list of stored I/O's values.
Definition at line 417 of file mdtDeviceIosSegment.cpp.
QList< int > mdtDeviceIosSegment::valuesInt () const
Get list of stored I/O's values.
Definition at line 404 of file mdtDeviceIosSegment.cpp.
Referenced by mdtDeviceModbus::writeAnalogOutputs().
The documentation for this class was generated from the following files:
src/mdtdevice/mdtDeviceIosSegment.h
src/mdtdevice/mdtDeviceIosSegment.cpp