Multi diag tools: mdtTtTestLinkDialog Class Reference
mdtTtTestLinkDialog Class Reference
Dialog that provide test link edition.
#include <mdtTtTestLinkDialog.h>
Public Member Functions
mdtTtTestLinkDialog (QWidget *parent, QSqlDatabase db)
Constructor.
~mdtTtTestLinkDialog ()
void setTestNode (const QVariant &nodeId)
Set test node.
void setDutUnit (const QVariant &unitId)
Set DUT unit.
void setTestConnection (const QVariant &unitConnectionId)
Set test connection.
void setDutConnection (const QVariant &unitConnectionId)
Set DUT connection.
void setLinkData (const mdtTtTestLinkData &data)
Set link data.
mdtTtTestLinkData linkData () const
Get link data.
Additional Inherited Members
Public Attributes inherited from Ui_mdtTtTestLinkDialog
QVBoxLayout * verticalLayout_3
QFormLayout * formLayout_5
QLabel * lbIdentification
QLineEdit * leIdentification
QLabel * lbValue
QDoubleSpinBox * sbValue
QHBoxLayout * horizontalLayout_5
QGroupBox * gbTestConnection
QVBoxLayout * verticalLayout
QLabel * lbTestNodeLabel
QHBoxLayout * horizontalLayout
QFormLayout * formLayout
QLabel * lbTestNodeTypeLabel
QLabel * lbTestNodeType
QLabel * lbTestNodeSubTypeLabel
QLabel * lbTestNodeSubType
QLabel * lbTestNodeNodeIdLabel
QLabel * lbTestNodeNodeId
QSpacerItem * horizontalSpacer_2
QPushButton * pbSelectTestUnit
QLabel * lbTestConnection
QHBoxLayout * horizontalLayout_2
QFormLayout * formLayout_2
QLabel * lbTestConnectorLabel
QLabel * lbTestConnector
QLabel * lbTestContactLabel
QLabel * lbTestContact
QSpacerItem * horizontalSpacer
QPushButton * pbSelectTestConnection
QGroupBox * gbDutConnection
QVBoxLayout * verticalLayout_2
QLabel * lbDutUnitLabel
QHBoxLayout * horizontalLayout_3
QFormLayout * formLayout_3
QLabel * lbDutSchemaPositionLabel
QLabel * lbDutSchemaPosition
QLabel * lbDutAliasLabel
QLabel * lbDutAlias
QLabel * lbDutCabinetLabel
QLabel * lbDutCabinet
QSpacerItem * horizontalSpacer_3
QPushButton * pbSelectDutUnit
QLabel * lbDutConnection
QHBoxLayout * horizontalLayout_4
QFormLayout * formLayout_4
QLabel * lbDutConnectorLabel
QLabel * lbDutConnector
QLabel * lbDutContactLabel
QLabel * lbDutContact
QSpacerItem * horizontalSpacer_4
QPushButton * pbSelectDutConnection
QPushButton * pbLinkedConnectionsInfo
QSpacerItem * verticalSpacer
QDialogButtonBox * buttonBox
Detailed Description
Dialog that provide test link edition.
Definition at line 34 of file mdtTtTestLinkDialog.h.
Constructor & Destructor Documentation
mdtTtTestLinkDialog::mdtTtTestLinkDialog (QWidget * parent, QSqlDatabase db)
Constructor.
Definition at line 33 of file mdtTtTestLinkDialog.cpp.
References mdtSqlRecord::lastError(), Ui_mdtTtTestLinkDialog::pbLinkedConnectionsInfo, Ui_mdtTtTestLinkDialog::pbSelectDutConnection, Ui_mdtTtTestLinkDialog::pbSelectDutUnit, Ui_mdtTtTestLinkDialog::pbSelectTestConnection, Ui_mdtTtTestLinkDialog::pbSelectTestUnit, mdtTtTestLinkData::setup(), Ui_mdtTtTestLinkDialog::setupUi(), mdtError::systemText(), and mdtError::text().
mdtTtTestLinkDialog::~mdtTtTestLinkDialog ()
Definition at line 61 of file mdtTtTestLinkDialog.cpp.
Member Function Documentation
mdtTtTestLinkData mdtTtTestLinkDialog::linkData () const inline
Get link data.
Definition at line 72 of file mdtTtTestLinkDialog.h.
void mdtTtTestLinkDialog::setDutConnection (const QVariant & unitConnectionId)
Set DUT connection.
Definition at line 83 of file mdtTtTestLinkDialog.cpp.
References mdtSqlRecord::setValue().
void mdtTtTestLinkDialog::setDutUnit (const QVariant & unitId)
Set DUT unit.
Definition at line 71 of file mdtTtTestLinkDialog.cpp.
void mdtTtTestLinkDialog::setLinkData (const mdtTtTestLinkData & data)
Set link data.
Definition at line 89 of file mdtTtTestLinkDialog.cpp.
void mdtTtTestLinkDialog::setTestConnection (const QVariant & unitConnectionId)
Set test connection.
Definition at line 77 of file mdtTtTestLinkDialog.cpp.
References mdtSqlRecord::setValue().
void mdtTtTestLinkDialog::setTestNode (const QVariant & nodeId)
Set test node.
Note: node ID is the database identifier (PK)
Definition at line 65 of file mdtTtTestLinkDialog.cpp.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtTestLinkDialog.h
src/mdttools/mdttesttool/mdtTtTestLinkDialog.cpp