Multi diag tools: mdtUsbtmcBulkTransfer Class Reference
mdtUsbtmcBulkTransfer Class Reference
USBTMC bulk transfer.
#include <mdtUsbtmcBulkTransfer.h>
Public Types
enum SplitAction_t {
SplitAction_t::NoAction = 0, SplitAction_t::INITIATE_ABORT, SplitAction_t::CHECK_ABORT_STATUS, SplitAction_t::INITIATE_CLEAR,
SplitAction_t::CHECK_CLEAR_STATUS, SplitAction_t::CLEAR_ENDPOINT_HALT
}
USBTMC split action.
Public Member Functions
mdtUsbtmcBulkTransfer (mdtUsbtmcTransferHandler &th, mdtUsbEndpointDescriptor endpointDescriptor, libusb_device_handle *dev_handle, int bufferSize=4096)
Constructor.
mdtUsbtmcBulkTransfer (const mdtUsbtmcBulkTransfer &rhs)=delete
mdtUsbtmcBulkTransfer & operator= (const mdtUsbtmcBulkTransfer &rhs)=delete
void setupDevDepMsgOut (uint8_t bTag, mdtUsbtmcTxMessage &message, bool responseExpected, unsigned int timeout)
Setup DEV_DEP_MSG_OUT transfer.
void setupRequestDevDepMsgIn (uint8_t bTag, bool termCharEnabled, char termChar, unsigned int timeout)
Setup REQUEST_DEV_DEP_MSG_IN transfer.
void setupBulkInRequest (unsigned int timeout)
Setup bulk-IN transfer.
uint8_t bTag () const
Get bTag.
bool bTagIsOk () const
Check if bTagInverse is the innverse of bTag.
mdtUsbtmcFrame::msgId_t msgID () const
Get MsgID.
bool receivedAllData (int rxLength)
Check if all data anounced in TransferSize by device are available.
bool isEOM () const
Check if this transfer is the last in message.
void getData (mdtUsbtmcRxMessage &message)
Get data.
mdtUsbtmcTransferHandler & transferHandler ()
Get transfer handler.
bool responseExpected () const
Check if a response is expected.
void setSplitAction (SplitAction_t action)
Set split action.
void clearSplitAction ()
Clear split action.
bool splitActionRequired () const
Check if a split action is to be performed.
SplitAction_t splitAction () const
Get split action to perform.
void dbgSetupCustom (uint8_t msgID, uint8_t bTag, uint8_t bTagInverse, uint32_t transferSize, uint8_t bmTransferAttributes, uint8_t termChar, bool responseExpected, int transferBufferLength, unsigned int timeout)
Setup a custom transfer.
Public Member Functions inherited from mdtUsbTransfer
mdtUsbTransfer (libusb_device_handle *dev_handle, int isoPacketsCount=0)
Constructor.
~mdtUsbTransfer ()
Destructor.
mdtUsbTransfer (const mdtUsbTransfer &rhs)=delete
mdtUsbTransfer & operator= (const mdtUsbTransfer &rhs)=delete
bool allocOk () const
Check that allocation not failed.
uint8_t flags () const
Get transfer flags.
bool submit (bool sync=false)
Submit transfer.
bool cancel (bool sync=false)
Cancel transfer.
libusb_transfer_status status () const
Get transfer status.
int actualLength () const
Get actual length.
unsigned int timeout () const
Get timeout that was given to transfer.
mdtError lastError () const
Get last error.
bool isSync () const
Check if transfer is a synchronous transfer.
int * completedPointer ()
Access completed flag.
void setCompleted ()
Set completed flag.
bool isCompleted () const
Check completed flag.
Additional Inherited Members
Protected Member Functions inherited from mdtUsbTransfer
libusb_device_handle * deviceHandle ()
Get device handle.
libusb_transfer * transfer ()
Access libusb transfer.
Detailed Description
USBTMC bulk transfer.
Definition at line 34 of file mdtUsbtmcBulkTransfer.h.
Member Enumeration Documentation
enum mdtUsbtmcBulkTransfer::SplitAction_t strong
USBTMC split action.
Helps to deal with USBTMC split transaction defined in USBTMC 1.0 specification, section 4.2.1.1
This is used by bulk transfer callbacks to know if they have something to do (submit a INITIATE or a CHECK control query).
Enumerator
NoAction
No action to perform
INITIATE_ABORT
Begin aborting transfer with INITIATE_ABORT_BULK_[OUT/IN]
CHECK_ABORT_STATUS
Check status with CHECK_ABORT_BULK_[OUT/IN]_STATUS
INITIATE_CLEAR
Begin INITIATE_CLEAR
CHECK_CLEAR_STATUS
Send a CHECK_CLEAR_STATUS request
CLEAR_ENDPOINT_HALT
Send a CLEAR_FEATURE request with wValue = ENDPOINT_HALT
Definition at line 46 of file mdtUsbtmcBulkTransfer.h.
Constructor & Destructor Documentation
mdtUsbtmcBulkTransfer::mdtUsbtmcBulkTransfer (mdtUsbtmcTransferHandler & th, mdtUsbEndpointDescriptor endpointDescriptor, libusb_device_handle * dev_handle, int bufferSize = 4096)
Constructor.
Parameters
th Transfer handler
endpointDescriptor Endpoint descriptor
dev_handle A handle to a open device
bufferSize Internal USBTMC frame's buffer size.
Precondition
endpointDescriptor must not be empty
bufferSize must be at least 512 and a multiple of 4
Definition at line 25 of file mdtUsbtmcBulkTransfer.cpp.
References clearSplitAction(), and mdtUsbEndpointDescriptor::isEmpty().
mdtUsbtmcBulkTransfer::mdtUsbtmcBulkTransfer (const mdtUsbtmcBulkTransfer & rhs) delete
Member Function Documentation
uint8_t mdtUsbtmcBulkTransfer::bTag () const inline
Get bTag.
Definition at line 107 of file mdtUsbtmcBulkTransfer.h.
References mdtUsbtmcFrame::bTag().
Referenced by mdtUsbtmcTransferHandler::beginAbortBulkIn(), mdtUsbtmcTransferHandler::handleBulkInTransferComplete(), mdtUsbtmcTransferHandler::handleBulkOutTransferComplete(), and mdtUsbtmcTransferHandler::restoreBulkOutTransferSA().
bool mdtUsbtmcBulkTransfer::bTagIsOk () const inline
Check if bTagInverse is the innverse of bTag.
Uuseful to check bulk-IN transfers.
Definition at line 116 of file mdtUsbtmcBulkTransfer.h.
References mdtUsbtmcFrame::bTag(), and mdtUsbtmcFrame::bTagInverse().
Referenced by mdtUsbtmcTransferHandler::handleBulkInTransferComplete().
void mdtUsbtmcBulkTransfer::clearSplitAction () inline
Clear split action.
Definition at line 177 of file mdtUsbtmcBulkTransfer.h.
References NoAction.
Referenced by dbgSetupCustom(), mdtUsbtmcBulkTransfer(), setupBulkInRequest(), setupDevDepMsgOut(), and setupRequestDevDepMsgIn().
void mdtUsbtmcBulkTransfer::dbgSetupCustom (uint8_t msgID, uint8_t bTag, uint8_t bTagInverse, uint32_t transferSize, uint8_t bmTransferAttributes, uint8_t termChar, bool responseExpected, int transferBufferLength, unsigned int timeout)
Setup a custom transfer.
Used for debug and testing.
Precondition
transferBufferLength must be <= Internal frame capacity
Definition at line 83 of file mdtUsbtmcBulkTransfer.cpp.
References mdtUsbEndpointDescriptor::address(), mdtUsbtmcFrame::buffer(), mdtUsbtmcTransferHandler::bulkOutTransferCallback(), mdtUsbtmcFrame::capacity(), mdtUsbtmcFrame::clear(), clearSplitAction(), mdtUsbtmcFrame::dbgSetCustomValue(), mdtUsbTransfer::deviceHandle(), responseExpected(), mdtUsbtmcFrame::setbTag(), mdtUsbtmcFrame::setMsgID(), mdtUsbtmcFrame::setTransferSize(), and mdtUsbTransfer::transfer().
Referenced by mdtUsbtmcTransferHandler::dbgSubmitCustomBulkOutTransfer().
void mdtUsbtmcBulkTransfer::getData (mdtUsbtmcRxMessage & message) inline
Get data.
Will write (by copy) data part to given message.
Definition at line 150 of file mdtUsbtmcBulkTransfer.h.
References mdtUsbtmcFrame::getData().
bool mdtUsbtmcBulkTransfer::isEOM () const inline
Check if this transfer is the last in message.
Definition at line 141 of file mdtUsbtmcBulkTransfer.h.
References mdtUsbtmcFrame::EOMset().
Referenced by mdtUsbtmcTransferHandler::handleBulkInTransferComplete().
mdtUsbtmcFrame::msgId_t mdtUsbtmcBulkTransfer::msgID () const inline
Get MsgID.
See Table 2 in USBTMC 1.0 specifications for details.
Definition at line 125 of file mdtUsbtmcBulkTransfer.h.
References mdtUsbtmcFrame::msgID().
Referenced by mdtUsbtmcTransferHandler::handleBulkOutTransferComplete().
mdtUsbtmcBulkTransfer& mdtUsbtmcBulkTransfer::operator= (const mdtUsbtmcBulkTransfer & rhs) delete
bool mdtUsbtmcBulkTransfer::receivedAllData (int rxLength) inline
Check if all data anounced in TransferSize by device are available.
Parameters
rxLength The actual length that libusb set in transfer struct
Definition at line 134 of file mdtUsbtmcBulkTransfer.h.
References mdtUsbtmcFrame::isComplete().
Referenced by mdtUsbtmcTransferHandler::handleBulkInTransferComplete().
bool mdtUsbtmcBulkTransfer::responseExpected () const inline
Check if a response is expected.
Definition at line 164 of file mdtUsbtmcBulkTransfer.h.
Referenced by dbgSetupCustom(), mdtUsbtmcTransferHandler::handleBulkOutTransferComplete(), and setupDevDepMsgOut().
void mdtUsbtmcBulkTransfer::setSplitAction (SplitAction_t action) inline
Set split action.
Definition at line 171 of file mdtUsbtmcBulkTransfer.h.
Referenced by mdtUsbtmcTransferHandler::beginAbortBulkOut(), mdtUsbtmcTransferHandler::submitCancelAllBulkInTransfers(), and mdtUsbtmcTransferHandler::submitCancelAllBulkOutTransfers().
void mdtUsbtmcBulkTransfer::setupBulkInRequest (unsigned int timeout)
Setup bulk-IN transfer.
See USBTMC 1.0 specifications, section 3.3
Parameters
timeout Timeout [ms]
Definition at line 72 of file mdtUsbtmcBulkTransfer.cpp.
References mdtUsbEndpointDescriptor::address(), mdtUsbtmcFrame::buffer(), mdtUsbtmcTransferHandler::bulkInTransferCallback(), mdtUsbtmcFrame::capacity(), mdtUsbtmcFrame::clear(), clearSplitAction(), mdtUsbTransfer::deviceHandle(), and mdtUsbTransfer::transfer().
void mdtUsbtmcBulkTransfer::setupDevDepMsgOut (uint8_t bTag, mdtUsbtmcTxMessage & message, bool responseExpected, unsigned int timeout)
Setup DEV_DEP_MSG_OUT transfer.
See USBTMC 1.0 specifications, section 3.2.1.1
Parameters
bTag See USBTMC 1.0 specifications, Table 1 for details
message Message in witch data must be transferred.
responseExpected If message is a query that expects a response, like *IDN?, set this flag.
timeout Timeout [ms]
Precondition
bTag must be in range [1;255]
Definition at line 36 of file mdtUsbtmcBulkTransfer.cpp.
References mdtUsbEndpointDescriptor::address(), mdtUsbtmcFrame::buffer(), mdtUsbtmcFrame::bufferLength(), mdtUsbtmcTransferHandler::bulkOutTransferCallback(), mdtUsbtmcFrame::clear(), clearSplitAction(), mdtUsbtmcFrame::DEV_DEP_MSG_OUT, mdtUsbTransfer::deviceHandle(), mdtUsbtmcTxMessage::hasBytesToRead(), responseExpected(), mdtUsbtmcFrame::setbTag(), mdtUsbtmcFrame::setData(), mdtUsbtmcFrame::setEOM(), mdtUsbtmcFrame::setMsgID(), and mdtUsbTransfer::transfer().
Referenced by mdtUsbtmcTransferHandler::submitCommand().
void mdtUsbtmcBulkTransfer::setupRequestDevDepMsgIn (uint8_t bTag, bool termCharEnabled, char termChar, unsigned int timeout)
Setup REQUEST_DEV_DEP_MSG_IN transfer.
See USBTMC 1.0 specifications, section 3.2.1.2
Parameters
bTag See USBTMC 1.0 specifications, Table 1 for details
termCharEnabled Set true if required and device support it.
termChar Term char. Is ignored if termCharEnabled is false.
timeout Timeout [ms]
Precondition
bTag must be in range [1;255]
Definition at line 53 of file mdtUsbtmcBulkTransfer.cpp.
References mdtUsbEndpointDescriptor::address(), mdtUsbtmcFrame::buffer(), mdtUsbtmcTransferHandler::bulkOutTransferCallback(), mdtUsbtmcFrame::clear(), clearSplitAction(), mdtUsbtmcFrame::DEV_DEP_MSG_IN, mdtUsbTransfer::deviceHandle(), mdtUsbtmcFrame::setbTag(), mdtUsbtmcFrame::setMsgID(), mdtUsbtmcFrame::setTermChar(), mdtUsbtmcFrame::setTransferSizeToMax(), and mdtUsbTransfer::transfer().
SplitAction_t mdtUsbtmcBulkTransfer::splitAction () const inline
Get split action to perform.
Definition at line 191 of file mdtUsbtmcBulkTransfer.h.
Referenced by mdtUsbtmcTransferHandler::restoreBulkInTransferSA(), and mdtUsbtmcTransferHandler::restoreBulkOutTransferSA().
bool mdtUsbtmcBulkTransfer::splitActionRequired () const inline
Check if a split action is to be performed.
Definition at line 184 of file mdtUsbtmcBulkTransfer.h.
References NoAction.
mdtUsbtmcTransferHandler& mdtUsbtmcBulkTransfer::transferHandler () inline
Get transfer handler.
Definition at line 157 of file mdtUsbtmcBulkTransfer.h.
Referenced by mdtUsbtmcTransferHandler::bulkInTransferCallback(), and mdtUsbtmcTransferHandler::bulkOutTransferCallback().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbtmcBulkTransfer.h
src/mdtport/mdtUsbtmcBulkTransfer.cpp