Multi diag tools: mdtCsvFile Class Reference
mdtCsvFile Class Reference
Read and write CSV file.
#include <mdtCsvFile.h>
Public Member Functions
mdtCsvFile (QObject *parent=0, const QByteArray &fileEncoding="UTF-8")
Constructor.
~mdtCsvFile ()
void close ()
Close.
bool writeLine (const QStringList &line, const QString &separator=";", const QString &dataProtection="", const QChar &escapeChar=QChar(), QString eol="\n")
Write a line of data.
QStringList readHeader (const QString &separator=";", const QString &dataProtection="", const QString &comment="#", const QChar &escapeChar=QChar(), QByteArray eol="\n")
Get CSV file's header.
QByteArray readLine (const QString &dataProtection="", const QString &comment="#", const QChar &escapeChar=QChar(), QByteArray eol="\n")
Read a line of data.
QStringList readLine (const QString &separator=";", const QString &dataProtection="", const QString &comment="#", const QChar &escapeChar=QChar(), QByteArray eol="\n")
Read a line of data.
bool readLine (QByteArray &line, const QString &dataProtection, const QString &comment, const QChar &escapeChar, QByteArray eol)
Read a line of data.
bool hasMoreLines () const
Check if readLine() has more lines available.
bool readLines (const QString &separator=";", const QString &dataProtection="", const QString &comment="#", const QChar &escapeChar=QChar(), QString eol="\n")
Read the file and store data.
void clear ()
Parse a string (considered as a line in a CSV file)
QString valueAt (int line, int column)
Get a value.
QList< QStringList > & lines ()
Get content of entire file.
void setReadLineBufferSize (int size)
Set the readLine() method's buffer size.
Detailed Description
Read and write CSV file.
The default file encoding format is assumed UTF-8. If another format is to use, give it at constructor.
Definition at line 43 of file mdtCsvFile.h.
Constructor & Destructor Documentation
mdtCsvFile::mdtCsvFile (QObject * parent = 0, const QByteArray & fileEncoding = "UTF-8")
Constructor.
Parameters
fileEncoding File encoding format. Note that this does not affect QFile's methods.
Precondition
fileEncoding must be supported by the system.
Definition at line 28 of file mdtCsvFile.cpp.
mdtCsvFile::~mdtCsvFile ()
Definition at line 36 of file mdtCsvFile.cpp.
References clear().
Member Function Documentation
void mdtCsvFile::clear ()
Parse a string (considered as a line in a CSV file)
Parameters
separator Separator to use (typical: ;)
protection Data protection (typical: ")
Returns
The list of found fields
Todo:
Check new function in mdtAlgorithm
QStringList &parseLine(const QByteArray &line, const QByteArray &separator, const QByteArray &dataProtection);
Clear readen data
Definition at line 217 of file mdtCsvFile.cpp.
Referenced by readLines(), and ~mdtCsvFile().
void mdtCsvFile::close ()
Close.
Will do some cleanup and call QFile's close method.
Note: readen data are not cleared. Call clear() explicitly for this.
See Also
valueAt()
Definition at line 41 of file mdtCsvFile.cpp.
Referenced by mdtDataTableManager::importFromCsvFile(), mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), and mdtUicNumber::loadUsagesDb().
bool mdtCsvFile::hasMoreLines () const
Check if readLine() has more lines available.
Definition at line 172 of file mdtCsvFile.cpp.
Referenced by mdtDataTableManager::importFromCsvFile(), and readLines().
QList< QStringList > & mdtCsvFile::lines ()
Get content of entire file.
Definition at line 239 of file mdtCsvFile.cpp.
Referenced by mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), and mdtUicNumber::loadUsagesDb().
QStringList mdtCsvFile::readHeader (const QString & separator = ";", const QString & dataProtection = "", const QString & comment = "#", const QChar & escapeChar = QChar(), QByteArray eol = "\n")
Get CSV file's header.
Will read the first line and get it's fields. After this call, readLine() methods will begin at next line.
Parameters
separator Separator to use (typical: ;)
dataProtection Data protection (typical: ") Note: current version does not support protected EOL.
escapeChar Escape char (typical: \). Note: has only effect to escape dataProtection.
comment Comment (typical: #)
eol End of line sequence. Usefull if given file was not written from running platform. Note that file must not be open with Text flag if this parameter is needed (se QFile::open() for details).
Returns
A list containing the headers.
Definition at line 89 of file mdtCsvFile.cpp.
References readLine().
Referenced by mdtDataTableManager::importFromCsvFile().
QByteArray mdtCsvFile::readLine (const QString & dataProtection = "", const QString & comment = "#", const QChar & escapeChar = QChar(), QByteArray eol = "\n")
Read a line of data.
Note: do not use atEnd() to check if data are available anymore, but hasMoreLines().
Parameters
dataProtection Data protection (typical: ").
comment Comment (typical: #). Each line that beginns with comment is ignored.
escapeChar Escape char (typical: \). Note: has only effect to escape dataProtection.
eol End of line sequence. Usefull if given file was not written from running platform.
Returns
Line of data.
Definition at line 94 of file mdtCsvFile.cpp.
Referenced by mdtDataTableManager::importFromCsvFile(), readHeader(), readLine(), and readLines().
QStringList mdtCsvFile::readLine (const QString & separator = ";", const QString & dataProtection = "", const QString & comment = "#", const QChar & escapeChar = QChar(), QByteArray eol = "\n")
Read a line of data.
Note: do not use atEnd() to check if data are available anymore, but hasMoreLines().
Parameters
dataProtection Data protection (typical: ").
comment Comment (typical: #). Each line that beginns with comment is ignored.
escapeChar Escape char (typical: \). Note: has only effect to escape dataProtection.
eol End of line sequence. Usefull if given file was not written from running platform.
Returns
Line of data.
Definition at line 105 of file mdtCsvFile.cpp.
References readLine(), and mdtAlgorithms::splitString().
bool mdtCsvFile::readLine (QByteArray & line, const QString & dataProtection, const QString & comment, const QChar & escapeChar, QByteArray eol)
Read a line of data.
Note: do not use atEnd() to check if data are available anymore, but hasMoreLines().
Parameters
line Line data will be put into this array.
dataProtection Data protection (typical: ").
comment Comment (typical: #). Each line that beginns with comment is ignored.
escapeChar Escape char (typical: \). Note: has only effect to escape dataProtection.
eol End of line sequence. Usefull if given file was not written from running platform.
Returns
True on success.
Definition at line 117 of file mdtCsvFile.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FILE_IO_ERROR.
bool mdtCsvFile::readLines (const QString & separator = ";", const QString & dataProtection = "", const QString & comment = "#", const QChar & escapeChar = QChar(), QString eol = "\n")
Read the file and store data.
Parameters
separator Separator to use (typical: ;)
dataProtection Data protection (typical: ")
escapeChar Escape char (typical: \). Note: has only effect to escape dataProtection.
comment Comment (typical: #)
eol End of line sequence. Usefull if given file was not written from running platform. Note that file must not be open with Text flag if this parameter is needed (se QFile::open() for details).
Returns
True on success
Precondition
separator, dataProtection and comment must not be the same
Definition at line 180 of file mdtCsvFile.cpp.
References clear(), mdtError::commit(), mdtError::Error, hasMoreLines(), MDT_ERROR_SET_SRC, MDT_FILE_IO_ERROR, readLine(), and mdtAlgorithms::splitString().
Referenced by mdtUicNumber::loadCountriesDb(), mdtUicNumber::loadSpeedAndHeatsDb(), mdtUicNumber::loadTypesDb(), and mdtUicNumber::loadUsagesDb().
void mdtCsvFile::setReadLineBufferSize (int size)
Set the readLine() method's buffer size.
Used by unit testing. A value < 1 means default value (8192).
Definition at line 244 of file mdtCsvFile.cpp.
QString mdtCsvFile::valueAt (int line, int column)
Get a value.
No value is available before readLines() was called. If requested index (line, column) is empty, or does not exists, a empty string is returned. The index check is done internally.
Definition at line 222 of file mdtCsvFile.cpp.
bool mdtCsvFile::writeLine (const QStringList & line, const QString & separator = ";", const QString & dataProtection = "", const QChar & escapeChar = QChar(), QString eol = "\n")
Write a line of data.
Parameters
line List of strings containing line data.
separator Separator to use (typical: ;)
dataProtection Data protection (typical: "). Note: current version does not support protected EOL.
escapeChar Escape char (typical: \). If not empty, if a line item contains a same sequence than dataProtection will be prefixed with escapeChar. Note: separator is not escaped.
eol End of line sequence. Usefull if given file is not supposed to be readen from running platform. Note that file must not be open with Text flag if this parameter is needed (se QFile::open() for details).
Returns
True on success
Definition at line 47 of file mdtCsvFile.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and MDT_FILE_IO_ERROR.
The documentation for this class was generated from the following files:
src/mdtutils/mdtCsvFile.h
src/mdtutils/mdtCsvFile.cpp