Multi diag tools: mdtUsbDeviceDescriptor Class Reference
mdtUsbDeviceDescriptor Class Reference
USB device descriptor.
#include <mdtUsbDeviceDescriptor.h>
Public Member Functions
mdtUsbDeviceDescriptor ()
Construct a empty device descriptor.
void clear ()
Clear.
bool isEmpty () const
Check if descriptor is empty.
bool fetchAttributes (libusb_device *device, bool fetchActiveConfigOnly)
Fetch the device descriptor's attributes.
libusb_device_handle * open ()
Get libusb device.
uint8_t bDescriptorType () const
Device descriptor type.
uint16_t bcdUSB () const
USB Specification Release Number.
uint8_t bDeviceClass () const
Class code (assigned by the USB-IF)
uint8_t bDeviceSubClass () const
Subclass code (assigned by the USB-IF)
uint8_t bDeviceProtocol () const
Protocol code (assigned by the USB-IF)
uint8_t bMaxPacketSize0 () const
Maximum packet size for endpoint zero.
uint16_t idVendor () const
Vendor ID (assigned by the USB-IF)
QString vendorName () const
Vendor name (assigned by the USB-IF)
uint16_t idProduct () const
Product ID.
QString productName () const
Product name.
QString serialNumber () const
Get serial number.
QString idString () const
Get a string with vendor ID, product ID and serial number if available.
uint16_t bcdDevice () const
Device release number id.
QList< mdtUsbConfigDescriptor > configurations () const
Access configurations.
int interfacesCount (uint8_t bInterfaceClass, uint8_t bInterfaceSubClass) const
Get number of interface that is of given class and sub class.
QList< mdtUsbEndpointDescriptor > bulkInEndpoints () const
Get list of bulk IN endpoints.
QList< mdtUsbEndpointDescriptor > bulkOutEndpoints () const
Get list of bulk OUT endpoints.
QList< mdtUsbEndpointDescriptor > interruptInEndpoints () const
Get list of interrupt IN endpoints.
QList< mdtUsbEndpointDescriptor > interruptOutEndpoints () const
Get list of interrupt OUT endpoints.
mdtUsbInterfaceDescriptor interface (uint8_t bInterfaceNumber) const
Get a interface descriptor by bInterfaceNumber.
QList< mdtUsbInterfaceDescriptor > allInterfaces () const
Get all interfaces.
mdtUsbInterfaceDescriptor interface (int configIndex, int ifaceIndex)
Get a interface descriptor by index.
mdtUsbEndpointDescriptor endpoint (int configIndex, int ifaceIndex, int endpointIndex)
Get a endpoint descriptor by index.
mdtUsbEndpointDescriptor firstBulkOutEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first bulk transfert endpoint with OUT direction.
mdtUsbEndpointDescriptor firstBulkInEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first bulk transfert endpoint with IN direction.
mdtUsbEndpointDescriptor firstInterruptOutEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first interrupt transfert endpoint with OUT direction.
mdtUsbEndpointDescriptor firstInterruptInEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first interrupt transfert endpoint with IN direction.
mdtError lastError () const
Get last error.
Detailed Description
USB device descriptor.
Internally, once fetchAttributes() is called, device configuration(s) will be scanned, and, for each configuration, interfaces and finally endpoinds will be fetched.
This tree is represented by several classes:
Device descriptor: mdtUsbDeviceDescriptor (this class)
Configuration descriptor: mdtUsbConfigDescriptor
Interface descriptor: mdtUsbInterfaceDescriptor
Endpoint descriptor: mdtUsbEndpointDescriptor
Each "parent" class gives access to their child with a QList<> method. For example, configurations are available with configurations().
For current needed attributes, some helper methods are available:
interface(int, int) : to get a interface descriptor by indexes.
endpoint(int, int, int) : to get a endpoint descriptor by index.
When goal is to open a particular device for I/O, a simple way to get needed informations could be to call fetchAttributes() with fetchActiveConfigOnly set true, then get endpoints with firstBulkOutEndpoint() , firstBulkInEndpoint() , firstInterruptInEndpoint() with configIndex set to 0, and a valid ifaceIndex.
Definition at line 59 of file mdtUsbDeviceDescriptor.h.
Constructor & Destructor Documentation
mdtUsbDeviceDescriptor::mdtUsbDeviceDescriptor ()
Construct a empty device descriptor.
Definition at line 28 of file mdtUsbDeviceDescriptor.cpp.
Member Function Documentation
QList< mdtUsbInterfaceDescriptor > mdtUsbDeviceDescriptor::allInterfaces () const
Get all interfaces.
Definition at line 281 of file mdtUsbDeviceDescriptor.cpp.
uint16_t mdtUsbDeviceDescriptor::bcdDevice () const inline
Device release number id.
Coded in BCD.
Definition at line 203 of file mdtUsbDeviceDescriptor.h.
uint16_t mdtUsbDeviceDescriptor::bcdUSB () const inline
USB Specification Release Number.
Coded in BCD. F.ex. USB 2.0 will be 0x0200.
Definition at line 124 of file mdtUsbDeviceDescriptor.h.
uint8_t mdtUsbDeviceDescriptor::bDescriptorType () const inline
Device descriptor type.
Definition at line 115 of file mdtUsbDeviceDescriptor.h.
uint8_t mdtUsbDeviceDescriptor::bDeviceClass () const inline
Class code (assigned by the USB-IF)
Definition at line 131 of file mdtUsbDeviceDescriptor.h.
uint8_t mdtUsbDeviceDescriptor::bDeviceProtocol () const inline
Protocol code (assigned by the USB-IF)
Definition at line 145 of file mdtUsbDeviceDescriptor.h.
uint8_t mdtUsbDeviceDescriptor::bDeviceSubClass () const inline
Subclass code (assigned by the USB-IF)
Definition at line 138 of file mdtUsbDeviceDescriptor.h.
uint8_t mdtUsbDeviceDescriptor::bMaxPacketSize0 () const inline
Maximum packet size for endpoint zero.
(only 8, 16, 32, or 64 are valid)
Definition at line 154 of file mdtUsbDeviceDescriptor.h.
QList< mdtUsbEndpointDescriptor > mdtUsbDeviceDescriptor::bulkInEndpoints () const
Get list of bulk IN endpoints.
Note: if device contains many configuration/interfaces, returned result will probably be wrong.
Definition at line 217 of file mdtUsbDeviceDescriptor.cpp.
QList< mdtUsbEndpointDescriptor > mdtUsbDeviceDescriptor::bulkOutEndpoints () const
Get list of bulk OUT endpoints.
Note: if device contains many configuration/interfaces, returned result will probably be wrong.
Definition at line 230 of file mdtUsbDeviceDescriptor.cpp.
void mdtUsbDeviceDescriptor::clear ()
Clear.
Definition at line 35 of file mdtUsbDeviceDescriptor.cpp.
Referenced by fetchAttributes().
QList<mdtUsbConfigDescriptor> mdtUsbDeviceDescriptor::configurations () const inline
Access configurations.
Configurations are available after a call of fetchAttributes()
Definition at line 212 of file mdtUsbDeviceDescriptor.h.
Referenced by mdtUsbPortManager::scan().
mdtUsbEndpointDescriptor mdtUsbDeviceDescriptor::endpoint (int configIndex, int ifaceIndex, int endpointIndex)
Get a endpoint descriptor by index.
Index checking is done in this method, and a empty descriptor is returned on wrong index.
Parameters
configIndex Index of configuration (unsorted, ordered as during discovery)
ifaceIndex Index of interface (unsorted, ordered as during discovery)
endpointIndex Index of endpoint (unsorted, ordered as during discovery)
Returns
End point descriptor filled with devices values, or a empty one on error.
Definition at line 315 of file mdtUsbDeviceDescriptor.cpp.
References mdtUsbInterfaceDescriptor::endpoints(), interface(), and mdtUsbInterfaceDescriptor::isEmpty().
bool mdtUsbDeviceDescriptor::fetchAttributes (libusb_device * device, bool fetchActiveConfigOnly)
Fetch the device descriptor's attributes.
Parameters
fetchActiveConfigOnly If true, the interfaces and endpoints informations will be fetched only for active configuration. Else, all device's available configurations will be scanned. See USB (2.0 or 3.1) specifications, chap. 9.6.3 .
Returns
True on success. On error, isEmpty() will be true, and lastError() contains error.
Precondition
device must be a valid pointer
Definition at line 44 of file mdtUsbDeviceDescriptor.cpp.
References clear(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, serialNumber(), mdtError::setError(), mdtError::setSystemError(), and mdtError::Warning.
Referenced by mdtUsbPortManager::scan().
mdtUsbEndpointDescriptor mdtUsbDeviceDescriptor::firstBulkInEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first bulk transfert endpoint with IN direction.
Parameters
configIndex Index of configuration (unsorted, ordered as during discovery)
ifaceIndex Index of interface (unsorted, ordered as during discovery)
dataEndpointOnly If true, only data endpoints will be considered (feedback and other are ignored)
Returns
End point descriptor filled with devices values, or a empty one on error.
Definition at line 361 of file mdtUsbDeviceDescriptor.cpp.
References mdtUsbInterfaceDescriptor::endpoints(), interface(), mdtUsbEndpointDescriptor::isDataEndpoint(), mdtUsbEndpointDescriptor::isDirectionIN(), mdtUsbInterfaceDescriptor::isEmpty(), and mdtUsbEndpointDescriptor::isTransferTypeBulk().
mdtUsbEndpointDescriptor mdtUsbDeviceDescriptor::firstBulkOutEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first bulk transfert endpoint with OUT direction.
Parameters
configIndex Index of configuration (unsorted, ordered as during discovery)
ifaceIndex Index of interface (unsorted, ordered as during discovery)
dataEndpointOnly If true, only data endpoints will be considered (feedback and other are ignored)
Returns
End point descriptor filled with devices values, or a empty one on error.
Definition at line 331 of file mdtUsbDeviceDescriptor.cpp.
References mdtUsbInterfaceDescriptor::endpoints(), interface(), mdtUsbEndpointDescriptor::isDataEndpoint(), mdtUsbEndpointDescriptor::isDirectionOUT(), mdtUsbInterfaceDescriptor::isEmpty(), and mdtUsbEndpointDescriptor::isTransferTypeBulk().
mdtUsbEndpointDescriptor mdtUsbDeviceDescriptor::firstInterruptInEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first interrupt transfert endpoint with IN direction.
Parameters
configIndex Index of configuration (unsorted, ordered as during discovery)
ifaceIndex Index of interface (unsorted, ordered as during discovery)
dataEndpointOnly If true, only data endpoints will be considered (feedback and other are ignored)
Returns
End point descriptor filled with devices values, or a empty one on error.
Definition at line 421 of file mdtUsbDeviceDescriptor.cpp.
References mdtUsbInterfaceDescriptor::endpoints(), interface(), mdtUsbEndpointDescriptor::isDataEndpoint(), mdtUsbEndpointDescriptor::isDirectionIN(), mdtUsbInterfaceDescriptor::isEmpty(), and mdtUsbEndpointDescriptor::isTransferTypeInterrupt().
mdtUsbEndpointDescriptor mdtUsbDeviceDescriptor::firstInterruptOutEndpoint (int configIndex, int ifaceIndex, bool dataEndpointOnly)
Find the first interrupt transfert endpoint with OUT direction.
Parameters
configIndex Index of configuration (unsorted, ordered as during discovery)
ifaceIndex Index of interface (unsorted, ordered as during discovery)
dataEndpointOnly If true, only data endpoints will be considered (feedback and other are ignored)
Returns
End point descriptor filled with devices values, or a empty one on error.
Definition at line 391 of file mdtUsbDeviceDescriptor.cpp.
References mdtUsbInterfaceDescriptor::endpoints(), interface(), mdtUsbEndpointDescriptor::isDataEndpoint(), mdtUsbEndpointDescriptor::isDirectionOUT(), mdtUsbInterfaceDescriptor::isEmpty(), and mdtUsbEndpointDescriptor::isTransferTypeInterrupt().
uint16_t mdtUsbDeviceDescriptor::idProduct () const inline
Product ID.
Definition at line 177 of file mdtUsbDeviceDescriptor.h.
Referenced by mdtUsbPortManager::scan().
QString mdtUsbDeviceDescriptor::idString () const
Get a string with vendor ID, product ID and serial number if available.
Definition at line 186 of file mdtUsbDeviceDescriptor.cpp.
References productName(), and vendorName().
Referenced by open().
uint16_t mdtUsbDeviceDescriptor::idVendor () const inline
Vendor ID (assigned by the USB-IF)
Definition at line 161 of file mdtUsbDeviceDescriptor.h.
Referenced by mdtUsbPortManager::scan().
mdtUsbInterfaceDescriptor mdtUsbDeviceDescriptor::interface (uint8_t bInterfaceNumber) const
Get a interface descriptor by bInterfaceNumber.
Definition at line 269 of file mdtUsbDeviceDescriptor.cpp.
Referenced by endpoint(), firstBulkInEndpoint(), firstBulkOutEndpoint(), firstInterruptInEndpoint(), and firstInterruptOutEndpoint().
mdtUsbInterfaceDescriptor mdtUsbDeviceDescriptor::interface (int configIndex, int ifaceIndex)
Get a interface descriptor by index.
Index checking is done in this method, and empty descriptor is returned on wrong index.
Parameters
configIndex Index of configuration (unsorted, ordered as during discovery)
ifaceIndex Index of interface (unsorted, ordered as during discovery)
Returns
Interface descriptor filled with devices values, or a empty one on error.
Definition at line 296 of file mdtUsbDeviceDescriptor.cpp.
References mdtUsbConfigDescriptor::interfaces().
int mdtUsbDeviceDescriptor::interfacesCount (uint8_t bInterfaceClass, uint8_t bInterfaceSubClass) const
Get number of interface that is of given class and sub class.
Definition at line 204 of file mdtUsbDeviceDescriptor.cpp.
QList< mdtUsbEndpointDescriptor > mdtUsbDeviceDescriptor::interruptInEndpoints () const
Get list of interrupt IN endpoints.
Note: if device contains many configuration/interfaces, returned result will probably be wrong.
Definition at line 243 of file mdtUsbDeviceDescriptor.cpp.
QList< mdtUsbEndpointDescriptor > mdtUsbDeviceDescriptor::interruptOutEndpoints () const
Get list of interrupt OUT endpoints.
Note: if device contains many configuration/interfaces, returned result will probably be wrong.
Definition at line 256 of file mdtUsbDeviceDescriptor.cpp.
bool mdtUsbDeviceDescriptor::isEmpty () const inline
Check if descriptor is empty.
Definition at line 73 of file mdtUsbDeviceDescriptor.h.
Referenced by mdtUsbtmcPort::openDevice(), mdtUsbPortThreadNew::openDevice(), and mdtUsbtmcTransferHandler::setup().
mdtError mdtUsbDeviceDescriptor::lastError () const inline
Get last error.
Definition at line 319 of file mdtUsbDeviceDescriptor.h.
Referenced by mdtUsbPortThreadNew::openDevice().
libusb_device_handle * mdtUsbDeviceDescriptor::open ()
Get libusb device.
Will return the device passed to fetchAttributes(). libusb_device *libusbDevice() { return pvLibusbDevice; }
Open current device
After successfull open, I/O can be performed with returned handle (see libusb_open() for details).
Note: destroying current descriptor object will not invalidate handle.
Returns
A valid handle on success, or a null pointer on error (on failure, use lastError()). Note: caller is responsible to free the handle with libusb_close() once no longer used.
Precondition
Current descriptor mus be valid, i.e. fetchAttributes() must be successfull before calling this function.
Definition at line 123 of file mdtUsbDeviceDescriptor.cpp.
References mdtError::commit(), mdtError::Error, idString(), MDT_ERROR_SET_SRC, mdtError::setError(), and mdtError::setSystemError().
Referenced by mdtUsbPortThreadNew::openDevice().
QString mdtUsbDeviceDescriptor::productName () const
Product name.
If vendorID:productID is known the product name is returned, else a string containing PID:0xXXXX is returned
Todo:
Parsing the usb.ids (see http://www.linux-usb.org)
Definition at line 160 of file mdtUsbDeviceDescriptor.cpp.
Referenced by idString(), and mdtUsbPortManager::scan().
QString mdtUsbDeviceDescriptor::serialNumber () const
Get serial number.
Definition at line 181 of file mdtUsbDeviceDescriptor.cpp.
Referenced by fetchAttributes(), and mdtUsbPortManager::scan().
QString mdtUsbDeviceDescriptor::vendorName () const
Vendor name (assigned by the USB-IF)
If vendor ID is known it is returned, else a string containing VID:0xXXXX is returned
Todo:
Parsing the usb.ids (see http://www.linux-usb.org)
Definition at line 144 of file mdtUsbDeviceDescriptor.cpp.
Referenced by idString(), and mdtUsbPortManager::scan().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbDeviceDescriptor.h
src/mdtport/mdtUsbDeviceDescriptor.cpp