Multi diag tools: mdtUsbControlTransfer Class Reference
mdtUsbControlTransfer Class Reference
USB control transfer.
#include <mdtUsbControlTransfer.h>
Public Types
enum RequestRecipient_t : uint8_t { RequestRecipient_t::Device = 0, RequestRecipient_t::Interface = 1, RequestRecipient_t::Endpoint = 2, RequestRecipient_t::Other = 3 }
Request recipient.
enum StandardRequestCode_t : uint8_t { StandardRequestCode_t::GET_STATUS = 0, StandardRequestCode_t::CLEAR_FEATURE = 1 }
Standard Request Codes.
enum DescriptorType_t : uint8_t {
DescriptorType_t::DEVICE = 1, DescriptorType_t::CONFIGURATION = 2, DescriptorType_t::STRING = 3, DescriptorType_t::INTERFACE = 4,
DescriptorType_t::ENDPOINT = 5
}
Descriptor Types.
enum StandardFeatureSelector_t : uint16_t { StandardFeatureSelector_t::DEVICE_REMOTE_WAKEUP = 1, StandardFeatureSelector_t::ENDPOINT_HALT = 0, StandardFeatureSelector_t::TEST_MODE = 2 }
Standard Feature Selectors.
Public Member Functions
mdtUsbControlTransfer (libusb_device_handle *dev_handle, int bufferSize=1024)
Constructor.
mdtUsbControlTransfer (const mdtUsbControlTransfer &rhs)=delete
mdtUsbControlTransfer & operator= (const mdtUsbControlTransfer &rhs)=delete
void setByteValue (unsigned int offset, uint8_t value)
Set value at offset.
uint8_t byteValue (unsigned int offset) const
Get value at offset.
void setWordValue (unsigned int offset, uint16_t value)
Set value at offset.
uint16_t wordValue (unsigned int offset) const
Get value at offset.
uint8_t bmRequestType () const
Get bmRequestType part.
uint8_t bRequest () const
Get bRequest part.
uint16_t wValue () const
Get wValue.
uint16_t wIndex () const
Get wIndex.
uint16_t wLength () const
Get wLength.
void setupClearFeature (libusb_transfer_cb_fn callback, RequestRecipient_t recipient, StandardFeatureSelector_t feature, uint16_t recipientNumber, unsigned int timeout)
Setup a Clear feature transfer.
Public Member Functions inherited from mdtUsbTransfer
mdtUsbTransfer (libusb_device_handle *dev_handle, int isoPacketsCount=0)
Constructor.
~mdtUsbTransfer ()
Destructor.
mdtUsbTransfer (const mdtUsbTransfer &rhs)=delete
mdtUsbTransfer & operator= (const mdtUsbTransfer &rhs)=delete
bool allocOk () const
Check that allocation not failed.
uint8_t flags () const
Get transfer flags.
bool submit (bool sync=false)
Submit transfer.
bool cancel (bool sync=false)
Cancel transfer.
libusb_transfer_status status () const
Get transfer status.
int actualLength () const
Get actual length.
unsigned int timeout () const
Get timeout that was given to transfer.
mdtError lastError () const
Get last error.
bool isSync () const
Check if transfer is a synchronous transfer.
int * completedPointer ()
Access completed flag.
void setCompleted ()
Set completed flag.
bool isCompleted () const
Check completed flag.
Protected Member Functions
void fillTransfer (libusb_transfer_cb_fn callback, uint8_t bmRequestType, uint8_t bRequest, uint16_t wValue, uint16_t wIndex, uint16_t wLength, unsigned int timeout)
Fill transfer.
void fillTransfer (libusb_transfer_cb_fn callback, uint8_t bmRequestType, uint8_t bRequest, uint16_t wValue, uint16_t wIndex, const std::vector< unsigned char > &data, unsigned int timeout)
Fill transfer.
Protected Member Functions inherited from mdtUsbTransfer
libusb_device_handle * deviceHandle ()
Get device handle.
libusb_transfer * transfer ()
Access libusb transfer.
Detailed Description
USB control transfer.
Definition at line 32 of file mdtUsbControlTransfer.h.
Member Enumeration Documentation
enum mdtUsbControlTransfer::DescriptorType_t : uint8_t strong
Descriptor Types.
See Table 9-5 in USB 2.0 specifications, section 9.4, or Table 9-6 in USB 3.1 specifications,section 9.4 for details.
Todo:
Complete this enum.
Enumerator
DEVICE
CONFIGURATION
STRING
INTERFACE
ENDPOINT
Definition at line 71 of file mdtUsbControlTransfer.h.
enum mdtUsbControlTransfer::RequestRecipient_t : uint8_t strong
Request recipient.
Represents bits D4...0 in bmRequestType field.
See Table 9-2 in USB 2.0 specifications, section 9.3, or Table 9-3 in USB 3.1 specifications,section 9.3 for details.
Enumerator
Device
Recipient is device
Interface
Recipient is a interface
Endpoint
Recipient is a endpoint
Other
Other recipient
Definition at line 43 of file mdtUsbControlTransfer.h.
enum mdtUsbControlTransfer::StandardFeatureSelector_t : uint16_t strong
Standard Feature Selectors.
See Table 9-6 in USB 2.0 specifications, section 9.4, or Table 9-7 in USB 3.1 specifications,section 9.4 for details.
Todo:
Complete this enum (USB 3.1 missing)
Enumerator
DEVICE_REMOTE_WAKEUP
Recipient: Device
ENDPOINT_HALT
Recipient: Endpoint
TEST_MODE
Recipient: Device
Definition at line 87 of file mdtUsbControlTransfer.h.
enum mdtUsbControlTransfer::StandardRequestCode_t : uint8_t strong
Standard Request Codes.
See Table 9-4 in USB 2.0 specifications, section 9.4, or Table 9-5 in USB 3.1 specifications,section 9.4 for details.
Todo:
Complete this enum.
Enumerator
GET_STATUS
CLEAR_FEATURE
Clear feature. USB 2.0/3.1 spec. section 9.4.1
Definition at line 58 of file mdtUsbControlTransfer.h.
Constructor & Destructor Documentation
mdtUsbControlTransfer::mdtUsbControlTransfer (libusb_device_handle * dev_handle, int bufferSize = 1024)
Constructor.
Todo:
Fix a realistic bufferSize
Precondition
bufferSize must be >= 8.
Definition at line 23 of file mdtUsbControlTransfer.cpp.
mdtUsbControlTransfer::mdtUsbControlTransfer (const mdtUsbControlTransfer & rhs) delete
Member Function Documentation
uint8_t mdtUsbControlTransfer::bmRequestType () const inline
Get bmRequestType part.
Definition at line 149 of file mdtUsbControlTransfer.h.
Referenced by fillTransfer(), and mdtUsbtmcControlTransfer::isClearEndpointHaltRequest().
uint8_t mdtUsbControlTransfer::bRequest () const inline
Get bRequest part.
Definition at line 156 of file mdtUsbControlTransfer.h.
Referenced by fillTransfer(), mdtUsbtmcTransferHandler::handleControlTransferComplete(), and mdtUsbtmcControlTransfer::isClearEndpointHaltRequest().
uint8_t mdtUsbControlTransfer::byteValue (unsigned int offset) const inline
Get value at offset.
Precondition
offset must be < internal buffer's capacity
Definition at line 120 of file mdtUsbControlTransfer.h.
Referenced by mdtUsbtmcControlTransfer::deviceIsDT1Capable(), mdtUsbtmcControlTransfer::deviceIsRL1Capable(), mdtUsbtmcControlTransfer::deviceIsSR1Capable(), mdtUsbtmcControlTransfer::deviceSupportsAllMandatoryScpiCommands(), mdtUsbtmcControlTransfer::deviceSupportsTermChar(), mdtUsbtmcControlTransfer::interfaceAcceptsIndicatorPulse(), mdtUsbtmcControlTransfer::interfaceAcceptsRenControl(), mdtUsbtmcControlTransfer::interfaceAcceptsTrigger(), mdtUsbtmcControlTransfer::interfaceIsListenOnly(), mdtUsbtmcControlTransfer::interfaceIsTalkOnly(), mdtUsbtmcControlTransfer::interfaceIsUSB488(), mdtUsbtmcControlTransfer::usbtmcRequest(), and mdtUsbtmcControlTransfer::usbtmcStatus().
void mdtUsbControlTransfer::fillTransfer (libusb_transfer_cb_fn callback, uint8_t bmRequestType, uint8_t bRequest, uint16_t wValue, uint16_t wIndex, uint16_t wLength, unsigned int timeout) protected
Fill transfer.
This version is mostly usefull for queries without data, or with data sended from device to host.
For details about USB specific arguments, see USB 3.1 spec, chap. 9.3 .
Parameters
transferHandler Application specific transfer handler. Must provide a static function called controlTransferCallback(), with the libusb_transfer_cb_fn signature. This transferHandler will be passed to user_data in libusb_transfer.
callback A static function that will be called (by libusb) when transfer fihishes. As documented in libusb API, this callback will receive a instance of libusb_transfer struct. The user_data part of this struct will also contain current transfer class pointer (this pointer).
bmRequestType Request characteristics (direction, type, recipient). Must be set correctly by caller.
bRequest Specific request (see USB spec.)
wValue See USB spec.
wIndex See USB spec.
wLength Number of bytes to transfer. Has only sense for direction device-to-host (should be 0 else).
Precondition
Internal buffer size (witch was given to constructor) must be >= 8 + wLength.
Definition at line 31 of file mdtUsbControlTransfer.cpp.
References bmRequestType(), bRequest(), mdtUsbTransfer::deviceHandle(), mdtUsbTransfer::transfer(), wIndex(), wLength(), and wValue().
Referenced by mdtUsbtmcControlTransfer::setupCheckAbortBulkInStatus(), mdtUsbtmcControlTransfer::setupCheckAbortBulkOutStatus(), mdtUsbtmcControlTransfer::setupCheckClearStatus(), setupClearFeature(), mdtUsbtmcControlTransfer::setupGetCapabilities(), mdtUsbtmcControlTransfer::setupIndicatorPulse(), mdtUsbtmcControlTransfer::setupInitiateAbortBulkIn(), mdtUsbtmcControlTransfer::setupInitiateAbortBulkOut(), and mdtUsbtmcControlTransfer::setupInitiateClear().
void mdtUsbControlTransfer::fillTransfer (libusb_transfer_cb_fn callback, uint8_t bmRequestType, uint8_t bRequest, uint16_t wValue, uint16_t wIndex, const std::vector< unsigned char > & data, unsigned int timeout) protected
Fill transfer.
This version is mostly usefull for queries with data sended from host to device.
For details about USB specific arguments, see USB 3.1 spec, chap. 9.3 .
Parameters
transferHandler Application specific transfer handler. Must provide a static function called controlTransferCallback(), with the libusb_transfer_cb_fn signature. This transferHandler will be passed to user_data in libusb_transfer.
callback A static function that will be called (by libusb) when transfer fihishes. As documented in libusb API, this callback will receive a instance of libusb_transfer struct. The user_data part of this struct will also contain current transfer class pointer (this pointer).
bmRequestType Request characteristics (direction, type, recipient). Must be set correctly by caller.
bRequest Specific request (see USB spec.)
wValue See USB spec.
wIndex See USB spec.
data Data that will be transferred to the device. Note: will also set wLength regarding data length.
Precondition
Internal buffer size (witch was given to constructor) must be >= 8 + data length.
Definition at line 41 of file mdtUsbControlTransfer.cpp.
References bmRequestType(), bRequest(), mdtUsbTransfer::deviceHandle(), mdtUsbTransfer::transfer(), wIndex(), wLength(), and wValue().
mdtUsbControlTransfer& mdtUsbControlTransfer::operator= (const mdtUsbControlTransfer & rhs) delete
void mdtUsbControlTransfer::setByteValue (unsigned int offset, uint8_t value) inline
Set value at offset.
Precondition
offset must be < internal buffer's capacity
Definition at line 110 of file mdtUsbControlTransfer.h.
void mdtUsbControlTransfer::setupClearFeature (libusb_transfer_cb_fn callback, RequestRecipient_t recipient, StandardFeatureSelector_t feature, uint16_t recipientNumber, unsigned int timeout) inline
Setup a Clear feature transfer.
Parameters
transferHandler Application specific transfer handler. Must provide a static function called controlTransferCallback(), with the libusb_transfer_cb_fn signature. This transferHandler will be passed to user_data in libusb_transfer.
callback A static function that will be called (by libusb) when transfer fihishes. As documented in libusb API, this callback will receive a instance of libusb_transfer struct. The user_data part of this struct will also contain current transfer class pointer (this pointer).
recipient Recipient, can be Device, Interface or Endpoint.
feature Supported feature depends on recipient (see USB 2.0 standards, section 9.4.1).
recipientNumber Index/number of recipient (f.ex. endpoint number if recipient is a endpoint).
timeout timeout for the transfer in milliseconds.
Definition at line 197 of file mdtUsbControlTransfer.h.
References CLEAR_FEATURE, and fillTransfer().
Referenced by mdtUsbtmcControlTransfer::setupClearEndpointHalt().
void mdtUsbControlTransfer::setWordValue (unsigned int offset, uint16_t value) inline
Set value at offset.
Precondition
offset+1 must be < internal buffer's capacity
Definition at line 130 of file mdtUsbControlTransfer.h.
uint16_t mdtUsbControlTransfer::wIndex () const inline
Get wIndex.
Definition at line 170 of file mdtUsbControlTransfer.h.
References wordValue().
Referenced by fillTransfer(), and mdtUsbtmcControlTransfer::isClearEndpointHaltRequest().
uint16_t mdtUsbControlTransfer::wLength () const inline
Get wLength.
Definition at line 177 of file mdtUsbControlTransfer.h.
References wordValue().
Referenced by fillTransfer().
uint16_t mdtUsbControlTransfer::wordValue (unsigned int offset) const inline
Get value at offset.
Precondition
offset+1 must be < internal buffer's capacity
Definition at line 141 of file mdtUsbControlTransfer.h.
Referenced by mdtUsbtmcControlTransfer::bcdUSB488(), mdtUsbtmcControlTransfer::bcdUSBTMC(), wIndex(), wLength(), and wValue().
uint16_t mdtUsbControlTransfer::wValue () const inline
Get wValue.
Definition at line 163 of file mdtUsbControlTransfer.h.
References wordValue().
Referenced by fillTransfer(), and mdtUsbtmcControlTransfer::isClearEndpointHaltRequest().
The documentation for this class was generated from the following files:
src/mdtport/mdtUsbControlTransfer.h
src/mdtport/mdtUsbControlTransfer.cpp