Multi diag tools: mdtSqlRelationInfo Class Reference
mdtSqlRelationInfo Class Reference
Container for SQL relation informations.
#include <mdtSqlRelationInfo.h>
Public Member Functions
mdtSqlRelationInfo ()
Constructor.
void setParentTableName (const QString &tableName)
Set parent table name.
QString parentTableName () const
Get parent table name.
void setChildTableName (const QString &tableName)
Set child table name.
QString childTableName () const
Get child table name.
void setCopyParentToChildOnInsertion (bool enable)
Set copyParentToChildOnInsertion flag.
bool copyParentToChildOnInsertion () const
Get copyParentToChildOnInsertion flag.
void addRelation (const QString &parentFieldName, const QString &childFieldName, bool copyParentToChildOnInsertion, const QString &operatorWithPreviousItem="AND")
Add a relation.
const QList
< mdtSqlRelationInfoItem > & items () const
Get relation items list.
Detailed Description
Container for SQL relation informations.
Definition at line 39 of file mdtSqlRelationInfo.h.
Constructor & Destructor Documentation
mdtSqlRelationInfo::mdtSqlRelationInfo () inline
Constructor.
Definition at line 45 of file mdtSqlRelationInfo.h.
Member Function Documentation
void mdtSqlRelationInfo::addRelation (const QString & parentFieldName, const QString & childFieldName, bool copyParentToChildOnInsertion, const QString & operatorWithPreviousItem = "AND")
Add a relation.
The parentFieldName is a field name from the parent table (typically a field from primary key). The childFieldName is a field from child table (typically a field from foreing keys).
Parameters
parentFieldName Field of parent model to use in relation (usually PK)
childFieldName Field of child model to use in relation (usually FK)
copyParentToChildOnInsertion If true, data from parent model will be copied to child model for this fields. (See mdtSqlRelationItem for details).
operatorWithPreviousItem Most of cases, the operator between multiple relation items is AND. If another is needed (f.ex. OR), specify it here.
Definition at line 23 of file mdtSqlRelationInfo.cpp.
References mdtSqlRelationInfoItem::childFieldName, mdtSqlRelationInfoItem::copyParentToChildOnInsertion, copyParentToChildOnInsertion(), mdtSqlRelationInfoItem::parentFieldName, and mdtSqlRelationInfoItem::relationOperatorWithPreviousItem.
QString mdtSqlRelationInfo::childTableName () const inline
Get child table name.
Definition at line 61 of file mdtSqlRelationInfo.h.
Referenced by mdtSqlForm::addChildTable().
bool mdtSqlRelationInfo::copyParentToChildOnInsertion () const inline
Get copyParentToChildOnInsertion flag.
Definition at line 75 of file mdtSqlRelationInfo.h.
Referenced by addRelation().
const QList<mdtSqlRelationInfoItem>& mdtSqlRelationInfo::items () const inline
Get relation items list.
Definition at line 94 of file mdtSqlRelationInfo.h.
QString mdtSqlRelationInfo::parentTableName () const inline
Get parent table name.
Definition at line 53 of file mdtSqlRelationInfo.h.
void mdtSqlRelationInfo::setChildTableName (const QString & tableName) inline
Set child table name.
Definition at line 57 of file mdtSqlRelationInfo.h.
void mdtSqlRelationInfo::setCopyParentToChildOnInsertion (bool enable) inline
Set copyParentToChildOnInsertion flag.
Usually, a parent/child relation is based on a primary key in parent table and foreing key (that refers to parent PK) in child model. When inserting a new record in child table, parent table's primary key must be copied into foreing key fields in child table. Set this flag to true to enable this behaviour (see mdtSqlRelation for more details).
By default, this flag is false.
Definition at line 71 of file mdtSqlRelationInfo.h.
void mdtSqlRelationInfo::setParentTableName (const QString & tableName) inline
Set parent table name.
Definition at line 49 of file mdtSqlRelationInfo.h.
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlRelationInfo.h
src/mdtdatabase/mdtSqlRelationInfo.cpp