Multi diag tools: mdtSqlTableWidget Class Reference
mdtSqlTableWidget Class Reference
Table view based SQL widget.
#include <mdtSqlTableWidget.h>
Public Slots
void resizeViewToContents ()
Resize view to contents.
void refresh ()
Refresh data.
Public Member Functions
mdtSqlTableWidget (QWidget *parent=0)
Constructor.
~mdtSqlTableWidget ()
Destructor.
void setTableName (const QString &tableName, QSqlDatabase db, const QString &userFriendlyTableName=QString())
Set table name.
void setUserFriendlyTableName (const QString &name)
Set user friendly table name.
QString userFriendlyTableName () const
Get user friendly table name.
QString tableName () const
Get table name.
void setTableController (std::shared_ptr< mdtSqlTableViewController > controller)
Set table view controller.
bool addChildTable (const mdtSqlRelationInfo &relationInfo, QSqlDatabase db, const QString &userFriendlyChildTableName=QString())
Add a child table.
bool addChildTable (const mdtSqlRelationInfo &relationInfo, const QString &userFriendlyChildTableName=QString())
Add a child table.
std::shared_ptr
< mdtSqlTableViewController > tableController (const QString &tableName)
Get internal table controller for given tableName.
void start ()
Start internal state machine.
void stop ()
Stop internal state machine.
bool select ()
Select data in main table.
bool setFilter (const QString &filter)
Set a filter on main table.
bool setFilter (const QString &fieldName, const QVariant &matchData)
Set a filter on main table.
bool setFilter (const QString &fieldName, const QList< QVariant > &matchDataList)
Set a filter on main table.
void clearFilter ()
Clear filter.
int currentRow () const
Get the current row.
QVariant currentData (const QString &fieldName)
Get current data for given field name.
QVariant currentData (const QString &fieldName, bool &ok)
Get current data for given field name.
void setEditionEnabled (bool enable)
Set edition enabled/disabled.
void enableLocalEdition ()
Enable local edition.
void addWidgetToLocalBar (QWidget *widget)
Add a custom widget to local bar.
void addStretchToLocalBar ()
Add a strech to local bar.
QItemSelectionModel * selectionModel ()
Get internal table view's selection model.
QTableView * tableView ()
Get internal table view.
void setHeaderData (const QString &fieldName, const QString &data)
Set a user friendly name for a column.
void setColumnHidden (int column, bool hide)
Set a coulumn as hidden.
void setColumnHidden (const QString &fieldName, bool hide)
Set a coulumn as hidden.
void setDefaultColumnToSelect (int column)
Set default column to select.
void setDefaultColumnToSelect (const QString &fieldName)
Set default column to select.
void addColumnToSortOrder (const QString &fieldName, Qt::SortOrder order=Qt::AscendingOrder)
Add a column to columns sort order.
void clearColumnsSortOrder ()
Clear columns sort order.
void sort ()
Sort data.
mdtSqlTableSelection currentSelection (const QStringList &fieldList)
Get current selection.
mdtSqlTableSelection currentSelection (const QString &field)
Get current selection.
mdtError lastError () const
Get last error.
bool exportToCsvFile (const QFileInfo &csvFile, const mdtCsvFileSettings &csvSettings, bool includeHeader)
Export table to CSV file.
bool exportToCsvFile (const QFileInfo &csvFile, const mdtCsvFileSettings &csvSettings, bool includeHeader, const QStringList &fieldNames)
Export table to CSV file.
Detailed Description
Table view based SQL widget.
class mdtSqlTableWidgetKeyEventFilter : public QObject { Q_OBJECT
public: mdtSqlTableWidgetKeyEventFilter(QObject *parent);
signals: void knownKeyPressed(int key);
protected: bool eventFilter(QObject *obj, QEvent *event); };
Internally, QTableView is used. This class add some common needed methods, like insertion, removing, ...
Definition at line 73 of file mdtSqlTableWidget.h.
Constructor & Destructor Documentation
mdtSqlTableWidget::mdtSqlTableWidget (QWidget * parent = 0)
Constructor.
Setup a QTableView and init some other things. The table view will not be editable, use setEditionEnabled() to alter this.
mdtSqlTableWidgetKeyEventFilter::mdtSqlTableWidgetKeyEventFilter(QObject *parent) : QObject(parent) { }
bool mdtSqlTableWidgetKeyEventFilter::eventFilter(QObject *obj, QEvent *event) { Q_ASSERT(obj != 0); Q_ASSERT(event != 0);
if(event->type() == QEvent::KeyPress){ QKeyEvent keyEvent = static_cast<QKeyEvent>(event); emit signal if we have a known key switch(keyEvent->key()){ case Qt::Key_Enter: case Qt::Key_Return: case Qt::Key_Delete: case Qt::Key_Down: emit knownKeyPressed(keyEvent->key()); return true; default: return false; } }else{ return QObject::eventFilter(obj, event); } }
Definition at line 94 of file mdtSqlTableWidget.cpp.
References refresh(), resizeViewToContents(), and setEditionEnabled().
mdtSqlTableWidget::~mdtSqlTableWidget ()
Destructor.
Definition at line 143 of file mdtSqlTableWidget.cpp.
Member Function Documentation
bool mdtSqlTableWidget::addChildTable (const mdtSqlRelationInfo & relationInfo, QSqlDatabase db, const QString & userFriendlyChildTableName = QString())
Add a child table.
Parameters
relationInfo Informations of relation between current controller's table (parent) and child controller's table (child) Note: parent table name is ignored.
db QSqlDatabase object to use
userFriendlyChildTableName User friendly table name for child controller.
Precondition
Table model must be set with setTableName() begore calling this method.
Definition at line 162 of file mdtSqlTableWidget.cpp.
bool mdtSqlTableWidget::addChildTable (const mdtSqlRelationInfo & relationInfo, const QString & userFriendlyChildTableName = QString())
Add a child table.
Parameters
relationInfo Informations of relation between current controller's table (parent) and child controller's table (child) Note: parent table name is ignored.
userFriendlyChildTableName User friendly table name for child controller.
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Definition at line 167 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::addColumnToSortOrder (const QString & fieldName, Qt::SortOrder order = Qt::AscendingOrder) inline
Add a column to columns sort order.
Columns sort order is similar meaning than SQL ORDER BY clause.
Internally, mdtSortFilterProxyModel is used, witch provide a natural sort for strings.
For example, to sort columns in order "Id_PK", "FirstName", "LastName", all ascending, call:
clearColumnsSortOrder();
addColumnToSortOrder("Id_PK", Qt::AscendingOrder);
addColumnToSortOrder("FirstName", Qt::AscendingOrder);
addColumnToSortOrder("LastName", Qt::AscendingOrder);
Note: if given field not exists, it will simply be ignored.
Note: to apply sorting, call sort()
Precondition
Model must be set with setModel() before using this method.
Definition at line 326 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::addStretchToLocalBar ()
Add a strech to local bar.
Definition at line 206 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::addWidgetToLocalBar (QWidget * widget)
Add a custom widget to local bar.
Typical usage can be to add a QPushButton for custom usage (edit, select, ...)
Note: widget will be parented to layout, so Qt will delete it itself.
Precondition
widget must be a valid pointer.
Definition at line 198 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::clearColumnsSortOrder () inline
Clear columns sort order.
See Also
addColumnToSortOrder()
Definition at line 334 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::clearFilter () inline
Clear filter.
Definition at line 206 of file mdtSqlTableWidget.h.
QVariant mdtSqlTableWidget::currentData (const QString & fieldName) inline
Get current data for given field name.
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Definition at line 219 of file mdtSqlTableWidget.h.
QVariant mdtSqlTableWidget::currentData (const QString & fieldName, bool & ok) inline
Get current data for given field name.
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Definition at line 228 of file mdtSqlTableWidget.h.
int mdtSqlTableWidget::currentRow () const inline
Get the current row.
Definition at line 213 of file mdtSqlTableWidget.h.
mdtSqlTableSelection mdtSqlTableWidget::currentSelection (const QStringList & fieldList) inline
Get current selection.
The returned selection will only contain data related to given field list.
Precondition
Model must be set with setModel() before using this method.
Definition at line 349 of file mdtSqlTableWidget.h.
mdtSqlTableSelection mdtSqlTableWidget::currentSelection (const QString & field) inline
Get current selection.
The returned selection will only contain data related to given field.
Precondition
Model must be set with setModel() before using this method.
Definition at line 358 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::enableLocalEdition ()
Enable local edition.
Will add insert/revert/save/delete buttons.
In normal way, when using mdtSqlWindow, local navigation is not needed. In master/detail forms, if this widget is a details (child) widget and edition is needed, then call this method.
Definition at line 189 of file mdtSqlTableWidget.cpp.
References setEditionEnabled().
bool mdtSqlTableWidget::exportToCsvFile (const QFileInfo & csvFile, const mdtCsvFileSettings & csvSettings, bool includeHeader) inline
Export table to CSV file.
Will export visible fields to given CSV file, regarding sorting.
Definition at line 369 of file mdtSqlTableWidget.h.
Referenced by exportToCsvFile().
bool mdtSqlTableWidget::exportToCsvFile (const QFileInfo & csvFile, const mdtCsvFileSettings & csvSettings, bool includeHeader, const QStringList & fieldNames) inline
Export table to CSV file.
Will export given fields to given CSV file, regarding sorting.
Definition at line 379 of file mdtSqlTableWidget.h.
References exportToCsvFile().
mdtError mdtSqlTableWidget::lastError () const inline
Get last error.
Definition at line 362 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::refresh () slot
Refresh data.
Definition at line 328 of file mdtSqlTableWidget.cpp.
References mdtUiMessageHandler::displayToUser(), and mdtUiMessageHandler::setError().
Referenced by mdtSqlTableWidget().
void mdtSqlTableWidget::resizeViewToContents () slot
Resize view to contents.
Definition at line 320 of file mdtSqlTableWidget.cpp.
Referenced by mdtSqlTableWidget().
bool mdtSqlTableWidget::select () inline
Select data in main table.
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Internal state machine must run (see start()).
Definition at line 160 of file mdtSqlTableWidget.h.
QItemSelectionModel * mdtSqlTableWidget::selectionModel ()
Get internal table view's selection model.
Definition at line 213 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::setColumnHidden (int column, bool hide)
Set a coulumn as hidden.
Definition at line 228 of file mdtSqlTableWidget.cpp.
Referenced by setColumnHidden().
void mdtSqlTableWidget::setColumnHidden (const QString & fieldName, bool hide)
Set a coulumn as hidden.
Precondition
Model must be set with setModel() before using this method.
Definition at line 234 of file mdtSqlTableWidget.cpp.
References setColumnHidden().
void mdtSqlTableWidget::setDefaultColumnToSelect (int column)
Set default column to select.
Some methods have to update selection in table view. Here it's possible to define witch column must be selected in such case.
Precondition
Model must be set with setModel() before using this method.
Definition at line 239 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::setDefaultColumnToSelect (const QString & fieldName)
Set default column to select.
Same as setDefaultColumnToSelect(int), but you can give a field name.
Precondition
Model must be set with setModel() before using this method.
Definition at line 244 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::setEditionEnabled (bool enable)
Set edition enabled/disabled.
Definition at line 180 of file mdtSqlTableWidget.cpp.
Referenced by enableLocalEdition(), and mdtSqlTableWidget().
bool mdtSqlTableWidget::setFilter (const QString & filter) inline
Set a filter on main table.
Set filter based on SQL query WHERE part, without the WHERE keyword (f.ex. Id_PK = 15)
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Internal state machine must run (see start()).
Definition at line 169 of file mdtSqlTableWidget.h.
bool mdtSqlTableWidget::setFilter (const QString & fieldName, const QVariant & matchData) inline
Set a filter on main table.
Parameters
fieldName Field that must match data
matchData Match data
Internally, a SQL statement is generated linke: fieldName = matchData
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Internal state machine must run (see start()).
Definition at line 184 of file mdtSqlTableWidget.h.
bool mdtSqlTableWidget::setFilter (const QString & fieldName, const QList< QVariant > & matchDataList) inline
Set a filter on main table.
Parameters
fieldName Field that must match data
matchDataList A list of match data
Internally, a SQL statement is generated linke: fieldName IN (matchData[0], matchData[1], ...)
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Internal state machine must run (see start()).
Definition at line 199 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::setHeaderData (const QString & fieldName, const QString & data)
Set a user friendly name for a column.
Precondition
Model must be set with setModel() before using this method.
Definition at line 223 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::setTableController (std::shared_ptr< mdtSqlTableViewController > controller)
Set table view controller.
By default, a controller is created. For simple cases, use setTableName().
This method will replace internal controller with given one.
Definition at line 152 of file mdtSqlTableWidget.cpp.
Referenced by mdtSqlForm::addChildTable(), and mdtTtBasicTestNodeCalibrationWindow::init().
void mdtSqlTableWidget::setTableName (const QString & tableName, QSqlDatabase db, const QString & userFriendlyTableName = QString())
Set table name.
Definition at line 147 of file mdtSqlTableWidget.cpp.
void mdtSqlTableWidget::setUserFriendlyTableName (const QString & name) inline
Set user friendly table name.
Definition at line 96 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::sort () inline
Sort data.
See Also
addColumnToSortOrder()
Definition at line 340 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::start () inline
Start internal state machine.
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Definition at line 147 of file mdtSqlTableWidget.h.
void mdtSqlTableWidget::stop () inline
Stop internal state machine.
Precondition
Table controller must be set with setTableName() or setTableController() before calling this function.
Definition at line 153 of file mdtSqlTableWidget.h.
shared_ptr< mdtSqlTableViewController > mdtSqlTableWidget::tableController (const QString & tableName)
Get internal table controller for given tableName.
Can return a Null pointer if tableName was not found.
Definition at line 172 of file mdtSqlTableWidget.cpp.
References tableName().
QString mdtSqlTableWidget::tableName () const inline
Get table name.
Definition at line 104 of file mdtSqlTableWidget.h.
Referenced by tableController().
QTableView * mdtSqlTableWidget::tableView ()
Get internal table view.
Definition at line 218 of file mdtSqlTableWidget.cpp.
QString mdtSqlTableWidget::userFriendlyTableName () const inline
Get user friendly table name.
Definition at line 100 of file mdtSqlTableWidget.h.
Referenced by mdtSqlForm::addChildTable().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlTableWidget.h
src/mdtdatabase/mdtSqlTableWidget.cpp