Multi diag tools: mdtClPathGraph Class Reference
mdtClPathGraph Class Reference
Represents the link list in a graph.
#include <mdtClPathGraph.h>
Public Member Functions
mdtClPathGraph (QSqlDatabase db)
Constructor.
~mdtClPathGraph ()
Destructor.
bool loadLinkList ()
Load the link list.
QList< QVariant > getLinkedConnectionIdList (const QVariant &fromConnectionId)
Get a list of unit connections IDs that are linked to a given connection.
QList< QVariant > getLinkedConnectorIdList (const QVariant &fromConnectorId, bool *ok, const QList< QVariant > &connectionIdListToIgnore=QList< QVariant >())
Get a list of unit connector ID that are linked to given one.
bool drawPath (const QVariant &fromConnectionId)
Draw the graphic representation starting from a connection.
void attachView (QGraphicsView *view)
Attach a view to the scene of the path graph.
QStringList lastErrorMessage () const
Get last error message.
mdtError lastError () const
Get last error.
Detailed Description
Represents the link list in a graph.
Definition at line 98 of file mdtClPathGraph.h.
Constructor & Destructor Documentation
mdtClPathGraph::mdtClPathGraph (QSqlDatabase db)
Constructor.
Definition at line 68 of file mdtClPathGraph.cpp.
mdtClPathGraph::~mdtClPathGraph ()
Destructor.
Definition at line 75 of file mdtClPathGraph.cpp.
Member Function Documentation
void mdtClPathGraph::attachView (QGraphicsView * view)
Attach a view to the scene of the path graph.
Definition at line 316 of file mdtClPathGraph.cpp.
Referenced by mdtClPathGraphDialog::mdtClPathGraphDialog().
bool mdtClPathGraph::drawPath (const QVariant & fromConnectionId)
Draw the graphic representation starting from a connection.
Definition at line 255 of file mdtClPathGraph.cpp.
References mdtClPathGraphPrivate::mdtClPathGraphEdgeData::endConnectionId, mdtError::Error, mdtClPathGraphPrivate::mdtClPathGraphEdgeData::isComplement, MDT_ERROR_SET_SRC, and mdtClPathGraphPrivate::mdtClPathGraphEdgeData::startConnectionId.
Referenced by mdtClPathGraphDialog::drawPath().
QList< QVariant > mdtClPathGraph::getLinkedConnectionIdList (const QVariant & fromConnectionId)
Get a list of unit connections IDs that are linked to a given connection.
Note: fromConnectionId is not included in result.
Definition at line 171 of file mdtClPathGraph.cpp.
References mdtClPathGraphPrivate::mdtClPathGraphEdgeData::endConnectionId, mdtError::Error, mdtClPathGraphPrivate::mdtClPathGraphEdgeData::isComplement, MDT_ERROR_SET_SRC, and mdtClPathGraphPrivate::mdtClPathGraphEdgeData::startConnectionId.
Referenced by mdtClDirectLink::addLinksByUnitConnector(), mdtTtTestNodeUnit::getConnectionIdListLinkedToConnectionIdList(), mdtTtTestConnectionCable::getToUnitConnectionIdLinkedUnitConnectionIdListPartOfUnitConnector(), and mdtTtTestConnectionCable::getToUnitConnectionLinkedUnitConnectorIdList().
QList< QVariant > mdtClPathGraph::getLinkedConnectorIdList (const QVariant & fromConnectorId, bool * ok, const QList< QVariant > & connectionIdListToIgnore = QList<QVariant>())
Get a list of unit connector ID that are linked to given one.
Parameters
fromConnectorId Connector from witch linked ones will be searched
connectionIdListToIgnore For example, if each connector has a GND, probably are they all connected together. In such case, this method has no sense. If given fromConnectorId contains such special connections, give their IDs here.
Note: fromConnectorId is not included in result.
Definition at line 210 of file mdtClPathGraph.cpp.
References mdtClUnit::getConnectionIdListPartOfConnectorId(), mdtClUnit::getConnectorIdOfConnectionId(), and mdtTtBase::lastError().
mdtError mdtClPathGraph::lastError () const
Get last error.
Definition at line 332 of file mdtClPathGraph.cpp.
Referenced by mdtTtTestNodeUnit::getConnectionIdListLinkedToConnectionIdList(), and mdtTtTestConnectionCable::loadLinkList().
QStringList mdtClPathGraph::lastErrorMessage () const
Get last error message.
The returned list is ready to be used with a QMessageBox . The first string contains also the text, second the informativeText and last the detailedText .
Postcondition
Returned list has allways a size of 3 (detailedText can simply contain a empty string)
Todo:
Should become Obselete .
Definition at line 323 of file mdtClPathGraph.cpp.
Referenced by mdtClPathGraphDialog::drawPath(), and mdtClPathGraphDialog::loadLinkList().
bool mdtClPathGraph::loadLinkList ()
Load the link list.
Definition at line 81 of file mdtClPathGraph.cpp.
References mdtClPathGraphPrivate::mdtClPathGraphEdgeData::endConnectionId, mdtError::Error, mdtClPathGraphPrivate::mdtClPathGraphEdgeData::isComplement, MDT_ERROR_SET_SRC, and mdtClPathGraphPrivate::mdtClPathGraphEdgeData::startConnectionId.
Referenced by mdtTtTestNodeUnit::getConnectionIdListLinkedToConnectionIdList(), mdtClPathGraphDialog::loadLinkList(), and mdtTtTestConnectionCable::loadLinkList().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClPathGraph.h
src/mdttools/mdttesttool/mdtcablelist/mdtClPathGraph.cpp