Multi diag tools: mdtSqlTableViewControllerItemDelegate Class Reference
mdtSqlTableViewControllerItemDelegate Class Reference
Item delegate for SQL table view controller.
#include <mdtSqlTableViewController.h>
Signals
void dataEditionBegins () const
Emited when data edition begins.
void dataEditionDone () const
Emited when data edition begins.
Public Member Functions
mdtSqlTableViewControllerItemDelegate (QObject *parent)
Constructor.
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
Re-implementation to emit dataEditionBegins()
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
Re-implementation to emit dataEditionDone()
Detailed Description
Item delegate for SQL table view controller.
To handle internal state machine correctly we need a signal that indicates that user begins to edit a item. We create a custom delegate that provide this signal.
Definition at line 41 of file mdtSqlTableViewController.h.
Constructor & Destructor Documentation
mdtSqlTableViewControllerItemDelegate::mdtSqlTableViewControllerItemDelegate (QObject * parent)
Constructor.
Definition at line 37 of file mdtSqlTableViewController.cpp.
Member Function Documentation
QWidget * mdtSqlTableViewControllerItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const
Re-implementation to emit dataEditionBegins()
Definition at line 42 of file mdtSqlTableViewController.cpp.
References dataEditionBegins(), and dataEditionDone().
void mdtSqlTableViewControllerItemDelegate::dataEditionBegins () const signal
Emited when data edition begins.
Referenced by createEditor().
void mdtSqlTableViewControllerItemDelegate::dataEditionDone () const signal
Emited when data edition begins.
Referenced by createEditor(), and setModelData().
void mdtSqlTableViewControllerItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const
Re-implementation to emit dataEditionDone()
Definition at line 54 of file mdtSqlTableViewController.cpp.
References dataEditionDone().
The documentation for this class was generated from the following files:
src/mdtdatabase/mdtSqlTableViewController.h
src/mdtdatabase/mdtSqlTableViewController.cpp