Multi diag tools: mdtSqlRelation Class Reference
mdtSqlRelation Class Reference
Handle parent/child relations between 2 QSqlTableModels.
#include <mdtSqlRelation.h>
Public Slots
void setParentCurrentRow (int row)
Set parent current row.
void setParentCurrentIndex (int index)
Update child model.
void setParentCurrentIndex (const QModelIndex &index)
Update child model.
void setParentCurrentIndex (const QModelIndex &current, const QModelIndex &previous)
Update child model.
Signals
void childModelFilterApplied ()
This signal is emitted once setFilter() was called on child model.
void childModelIsEmpty ()
This signal is emitted after childModelFilterApplied() if child model becomes empty.
Public Member Functions
mdtSqlRelation (QObject *parent=0)
Create a empty relation.
~mdtSqlRelation ()
Destructor.
void setParentModel (QSqlTableModel *model)
Set the parent model.
void setChildModel (QSqlTableModel *model)
Set the child model.
bool addRelation (const mdtSqlRelationInfoItem &relationInfoItem)
Add a relation.
bool addRelation (const QString &parentFieldName, const QString &childFieldName, bool copyParentToChildOnInsertion, const QString &operatorWithPreviousItem="AND")
Add a relation.
bool addRelations (const mdtSqlRelationInfo &relationInfo)
Add all relations contained in given relationInfo.
void clear ()
Clear relations.
mdtError lastError () const
Get last error.
Detailed Description
Handle parent/child relations between 2 QSqlTableModels.
This is usefull to create data/details forms.
Typical usage:
Set the parent and child models, using setParentModel() and setChildModel()
Add parent/child tables fields that must match with addRelation()
Connect the parent view's currentXyChanged() signal to setParentCurrentIndex() slot. If you use a QTableView, this signal is in its selectionModel(). For QDataWidgetMapper, the currentIndexChanged() signal is directly available.
If a QDataWidgetMapper is used directly on a child model, connect childModelFilterApplied() signal to QDataWidgetMapper's toFirst() slot.
Definition at line 48 of file mdtSqlRelation.h.
Constructor & Destructor Documentation
mdtSqlRelation::mdtSqlRelation (QObject * parent = 0)
Create a empty relation.
Definition at line 27 of file mdtSqlRelation.cpp.
mdtSqlRelation::~mdtSqlRelation ()
Destructor.
Definition at line 35 of file mdtSqlRelation.cpp.
References clear().
Member Function Documentation
bool mdtSqlRelation::addRelation (const mdtSqlRelationInfoItem & relationInfoItem)
Add a relation.
Note that this method will fetch some information about fields in parent and child model (data type, field index, ...), so parent and child models must be set before.
Returns
True on succes, false if a field could not be found.
Precondition
Parent model must be set with setParentModel() before using this method.
Child model must be set with setChildModel() before using this method.
Definition at line 55 of file mdtSqlRelation.cpp.
References mdtSqlRelationInfoItem::childFieldName, mdtError::commit(), mdtSqlRelationInfoItem::copyParentToChildOnInsertion, mdtError::Error, MDT_ERROR_SET_SRC, mdtSqlRelationInfoItem::parentFieldName, mdtSqlRelationInfoItem::relationOperatorWithPreviousItem, mdtSqlRelationItem::setChildField(), mdtSqlRelationItem::setChildFieldIndex(), mdtSqlRelationItem::setCopyParentToChildOnInsertion(), mdtError::setError(), mdtSqlRelationItem::setParentField(), mdtSqlRelationItem::setParentFieldIndex(), and mdtSqlRelationItem::setRelationOperatorWithPreviousItem().
Referenced by addRelation(), and addRelations().
bool mdtSqlRelation::addRelation (const QString & parentFieldName, const QString & childFieldName, bool copyParentToChildOnInsertion, const QString & operatorWithPreviousItem = "AND")
Add a relation.
The parentFieldName is a field name from the parent table (typically a field from primary key). The childFieldName is a field from child table (typically a field from foreing keys).
Note that this method will fetch some information about fields in parent and child model (data type, field index, ...), so parent and child models must be set before.
Parameters
parentFieldName Field of parent model to use in relation (usually PK)
childFieldName Field of child model to use in relation (usually FK)
copyParentToChildOnInsertion If true, data from parent model will be copied to child model for this fields. (See mdtSqlRelationItem for details).
operatorWithPreviousItem Most of cases, the operator between multiple relation items is AND. If another is needed (f.ex. OR), specify it here.
Returns
True on succes, false if a field could not be found.
Precondition
Parent model must be set with setParentModel() before using this method.
Child model must be set with setChildModel() before using this method.
Definition at line 99 of file mdtSqlRelation.cpp.
References addRelation(), mdtSqlRelationInfoItem::childFieldName, mdtSqlRelationInfoItem::copyParentToChildOnInsertion, mdtSqlRelationInfoItem::parentFieldName, and mdtSqlRelationInfoItem::relationOperatorWithPreviousItem.
bool mdtSqlRelation::addRelations (const mdtSqlRelationInfo & relationInfo)
Add all relations contained in given relationInfo.
See Also
addRelation(const mdtSqlRelationInfoItem&).
Definition at line 114 of file mdtSqlRelation.cpp.
References addRelation(), and mdtSqlRelationInfo::items().
void mdtSqlRelation::childModelFilterApplied () signal
This signal is emitted once setFilter() was called on child model.
This can be usefull when update must be done after child model was updated. For example, when using a QDataWidgetMapper, connect this signal to QDataWidgetMapper's toFirst() slot.
void mdtSqlRelation::childModelIsEmpty () signal
This signal is emitted after childModelFilterApplied() if child model becomes empty.
Connect this signal to QDataWidgetMapper's revert() slot. QDataWidgetMapper will not clear widgets if model becomes empty, so using this signal is a workaround..
void mdtSqlRelation::clear ()
Clear relations.
Will clear all added relations and references to parent and child models. (will not delete models).
Definition at line 130 of file mdtSqlRelation.cpp.
Referenced by ~mdtSqlRelation().
mdtError mdtSqlRelation::lastError () const inline
Get last error.
Definition at line 127 of file mdtSqlRelation.h.
void mdtSqlRelation::setChildModel (QSqlTableModel * model)
Set the child model.
Will be used internally to get some informations about fields and get values to generate relation filters.
Precondition
model must be a valid pointer.
Definition at line 47 of file mdtSqlRelation.cpp.
void mdtSqlRelation::setParentCurrentIndex (int index) slot
Update child model.
Precondition
Parent model must be set with setParentModel() before using this method.
Child model must be set with setChildModel() before using this method.
Definition at line 147 of file mdtSqlRelation.cpp.
Referenced by setParentCurrentIndex().
void mdtSqlRelation::setParentCurrentIndex (const QModelIndex & index) slot
Update child model.
Precondition
Parent model must be set with setParentModel() before using this method.
Child model must be set with setChildModel() before using this method.
Definition at line 156 of file mdtSqlRelation.cpp.
References setParentCurrentIndex().
void mdtSqlRelation::setParentCurrentIndex (const QModelIndex & current, const QModelIndex & previous) slot
Update child model.
Precondition
Parent model must be set with setParentModel() before using this method.
Child model must be set with setChildModel() before using this method.
Definition at line 168 of file mdtSqlRelation.cpp.
References setParentCurrentIndex().
void mdtSqlRelation::setParentCurrentRow (int row) slot
Set parent current row.
Parameters
row The new current row for parent model
Precondition
Parent model must be set with setParentModel() before using this method.
Child model must be set with setChildModel() before using this method.
Definition at line 138 of file mdtSqlRelation.cpp.
void mdtSqlRelation::setParentModel (QSqlTableModel * model)
Set the parent model.
Will be used internally to get some informations about fields and get values to generate relation filters.
Precondition
model must be a valid pointer.
Definition at line 40 of file mdtSqlRelation.cpp.
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSqlRelation.h
src/mdtutilsgui/mdtSqlRelation.cpp