Multi diag tools: mdtSqlFieldHandlerAbstractDataWidget Class Reference
mdtSqlFieldHandlerAbstractDataWidget Class Reference abstract
#include <mdtSqlFieldHandler.h>
Public Member Functions
virtual ~mdtSqlFieldHandlerAbstractDataWidget ()
virtual void setData (const QVariant &data)=0
virtual QVariant data () const =0
virtual bool isNull () const =0
virtual void clear ()=0
virtual QWidget * widget ()=0
virtual void setReadOnly (bool readOnly)=0
virtual void setMaxLength (int maxLength)
virtual void setRange (qreal min, qreal max)
virtual bool validate ()
Detailed Description
Definition at line 49 of file mdtSqlFieldHandler.h.
Constructor & Destructor Documentation
virtual mdtSqlFieldHandlerAbstractDataWidget::~mdtSqlFieldHandlerAbstractDataWidget () inline virtual
Definition at line 52 of file mdtSqlFieldHandler.h.
Member Function Documentation
virtual void mdtSqlFieldHandlerAbstractDataWidget::clear () pure virtual
Implemented in mdtSqlFieldHandlerDateTimeEdit, mdtSqlFieldHandlerMdtDoubleEdit, mdtSqlFieldHandlerComboBox, mdtSqlFieldHandlerLineEdit, mdtSqlFieldHandlerPlainTextEdit, and mdtSqlFieldHandlerLabel.
Referenced by mdtSqlFieldHandler::clearWidgetData().
virtual QVariant mdtSqlFieldHandlerAbstractDataWidget::data () const pure virtual
Implemented in mdtSqlFieldHandlerDateTimeEdit, mdtSqlFieldHandlerMdtDoubleEdit, mdtSqlFieldHandlerComboBox, mdtSqlFieldHandlerLineEdit, mdtSqlFieldHandlerPlainTextEdit, and mdtSqlFieldHandlerLabel.
virtual bool mdtSqlFieldHandlerAbstractDataWidget::isNull () const pure virtual
Implemented in mdtSqlFieldHandlerDateTimeEdit, mdtSqlFieldHandlerMdtDoubleEdit, mdtSqlFieldHandlerComboBox, mdtSqlFieldHandlerLineEdit, mdtSqlFieldHandlerPlainTextEdit, and mdtSqlFieldHandlerLabel.
Referenced by mdtSqlFieldHandler::isNull().
virtual void mdtSqlFieldHandlerAbstractDataWidget::setData (const QVariant & data) pure virtual
Implemented in mdtSqlFieldHandlerDateTimeEdit, mdtSqlFieldHandlerMdtDoubleEdit, mdtSqlFieldHandlerComboBox, mdtSqlFieldHandlerLineEdit, mdtSqlFieldHandlerPlainTextEdit, and mdtSqlFieldHandlerLabel.
Referenced by mdtSqlFieldHandler::setData().
virtual void mdtSqlFieldHandlerAbstractDataWidget::setMaxLength (int maxLength) inline virtual
Reimplemented in mdtSqlFieldHandlerMdtDoubleEdit, mdtSqlFieldHandlerComboBox, mdtSqlFieldHandlerLineEdit, and mdtSqlFieldHandlerPlainTextEdit.
Definition at line 59 of file mdtSqlFieldHandler.h.
virtual void mdtSqlFieldHandlerAbstractDataWidget::setRange (qreal min, qreal max) inline virtual
Definition at line 60 of file mdtSqlFieldHandler.h.
virtual void mdtSqlFieldHandlerAbstractDataWidget::setReadOnly (bool readOnly) pure virtual
Implemented in mdtSqlFieldHandlerDateTimeEdit, mdtSqlFieldHandlerMdtDoubleEdit, mdtSqlFieldHandlerComboBox, mdtSqlFieldHandlerLineEdit, mdtSqlFieldHandlerPlainTextEdit, and mdtSqlFieldHandlerLabel.
virtual bool mdtSqlFieldHandlerAbstractDataWidget::validate () inline virtual
Reimplemented in mdtSqlFieldHandlerMdtDoubleEdit.
Definition at line 61 of file mdtSqlFieldHandler.h.
Referenced by mdtSqlFieldHandler::checkBeforeSubmit().
virtual QWidget* mdtSqlFieldHandlerAbstractDataWidget::widget () pure virtual
Implemented in mdtSqlFieldHandlerDateTimeEdit, mdtSqlFieldHandlerMdtDoubleEdit, mdtSqlFieldHandlerComboBox, mdtSqlFieldHandlerLineEdit, mdtSqlFieldHandlerPlainTextEdit, and mdtSqlFieldHandlerLabel.
Referenced by mdtSqlFieldHandler::dataWidget().
The documentation for this class was generated from the following file:
src/mdtdatabase/mdtSqlFieldHandler.h