Multi diag tools: mdtSqlSchemaTable Class Reference
mdtSqlSchemaTable Class Reference
Helper class that generate SQL table creation string.
#include <mdtSqlSchemaTable.h>
Public Types
enum foreignKeyAction_t { Cascade, SetNull, NoAction, Restrict }
Action on update or on delete.
Public Member Functions
mdtSqlSchemaTable ()
Constructor.
~mdtSqlSchemaTable ()
Destructor.
void clear ()
Clear.
void setDriverName (const QString &name)
Set the driver name.
void setDatabaseName (const QString &name)
Set database name.
void setTableName (const QString &name, const QString &charset=QString(), Qt::CaseSensitivity cs=Qt::CaseInsensitive)
Set table name.
QString tableName () const
Get table name.
void setStorageEngineName (const QString &name)
Set the Maria DB/MySQL storage engine (XtraDB, Inno DB, ...)
void addField (const QSqlField &field, bool isPartOfPrimaryKey)
Add a field.
int fieldCount () const
Get number of fields.
void addIndex (const QString &name, bool unique)
Add a index.
bool addFieldToIndex (const QString &indexName, const QString &fieldName)
Add a field to a index.
void addForeignKey (const QString &name, const QString &referingTableName, const foreignKeyAction_t &actionOnDelete, const foreignKeyAction_t &actionOnUpdate)
Add a foreign key contraint.
bool addFieldToForeignKey (const QString &foreignKeyName, const QString &fieldName, const QString &referingFieldName)
Add a field to a foreign key.
QString sqlForCreateTable () const
Get SQL statement for table creation.
QString sqlForDropTable () const
Get SQL statement for table deleteion.
mdtError lastError () const
Get last error.
Detailed Description
Helper class that generate SQL table creation string.
Definition at line 46 of file mdtSqlSchemaTable.h.
Member Enumeration Documentation
enum mdtSqlSchemaTable::foreignKeyAction_t
Action on update or on delete.
Enumerator
Cascade
Cascade
SetNull
Set null
NoAction
No action
Restrict
Restrict
Definition at line 52 of file mdtSqlSchemaTable.h.
Constructor & Destructor Documentation
mdtSqlSchemaTable::mdtSqlSchemaTable ()
Constructor.
Definition at line 25 of file mdtSqlSchemaTable.cpp.
mdtSqlSchemaTable::~mdtSqlSchemaTable ()
Destructor.
Definition at line 29 of file mdtSqlSchemaTable.cpp.
Member Function Documentation
void mdtSqlSchemaTable::addField (const QSqlField & field, bool isPartOfPrimaryKey)
Add a field.
Definition at line 75 of file mdtSqlSchemaTable.cpp.
Referenced by mdtDataTableManager::copyTable(), and mdtDataTableManager::importFromCsvFile().
bool mdtSqlSchemaTable::addFieldToForeignKey (const QString & foreignKeyName, const QString & fieldName, const QString & referingFieldName)
Add a field to a foreign key.
Field must allready be created with addField() and foreign key also with addForeignKey() . If foreign key with name foreignKeyName does not exists, or field with fieldName not exists, this method returns false.
Definition at line 140 of file mdtSqlSchemaTable.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and mdtError::setError().
bool mdtSqlSchemaTable::addFieldToIndex (const QString & indexName, const QString & fieldName)
Add a field to a index.
Field must allready be created with addField() and index also with addIndex() . If index with name indexName does not exists, or field with fieldName not exists, this method returns false.
Definition at line 97 of file mdtSqlSchemaTable.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, and mdtError::setError().
void mdtSqlSchemaTable::addForeignKey (const QString & name, const QString & referingTableName, const foreignKeyAction_t & actionOnDelete, const foreignKeyAction_t & actionOnUpdate)
Add a foreign key contraint.
Definition at line 127 of file mdtSqlSchemaTable.cpp.
References mdtSqlSchemaTableForeignKeyInfo::actionOnDelete, mdtSqlSchemaTableForeignKeyInfo::actionOnUpdate, and mdtSqlSchemaTableForeignKeyInfo::referingTableName.
void mdtSqlSchemaTable::addIndex (const QString & name, bool unique)
Add a index.
If name allready exists, it will not be appended
Definition at line 88 of file mdtSqlSchemaTable.cpp.
void mdtSqlSchemaTable::clear ()
Clear.
Definition at line 33 of file mdtSqlSchemaTable.cpp.
int mdtSqlSchemaTable::fieldCount () const
Get number of fields.
Definition at line 83 of file mdtSqlSchemaTable.cpp.
Referenced by mdtDataTableManager::importFromCsvFile().
mdtError mdtSqlSchemaTable::lastError () const
Get last error.
Definition at line 219 of file mdtSqlSchemaTable.cpp.
void mdtSqlSchemaTable::setDatabaseName (const QString & name)
Set database name.
Definition at line 53 of file mdtSqlSchemaTable.cpp.
void mdtSqlSchemaTable::setDriverName (const QString & name)
Set the driver name.
Driver name must be given in format returned by QSqlDatabase::driverName() .
Definition at line 48 of file mdtSqlSchemaTable.cpp.
Referenced by mdtSqlDatabaseManager::createTable().
void mdtSqlSchemaTable::setStorageEngineName (const QString & name)
Set the Maria DB/MySQL storage engine (XtraDB, Inno DB, ...)
Definition at line 70 of file mdtSqlSchemaTable.cpp.
void mdtSqlSchemaTable::setTableName (const QString & name, const QString & charset = QString(), Qt::CaseSensitivity cs = Qt::CaseInsensitive)
Set table name.
Definition at line 58 of file mdtSqlSchemaTable.cpp.
Referenced by mdtDataTableManager::copyTable(), and mdtDataTableManager::createDataSet().
QString mdtSqlSchemaTable::sqlForCreateTable () const
Get SQL statement for table creation.
Definition at line 171 of file mdtSqlSchemaTable.cpp.
References mdtError::commit(), mdtError::Error, MDT_DATABASE_ERROR, and MDT_ERROR_SET_SRC.
Referenced by mdtSqlDatabaseManager::createTable().
QString mdtSqlSchemaTable::sqlForDropTable () const
Get SQL statement for table deleteion.
Definition at line 197 of file mdtSqlSchemaTable.cpp.
Referenced by mdtSqlDatabaseManager::createTable().
QString mdtSqlSchemaTable::tableName () const
Get table name.
Definition at line 65 of file mdtSqlSchemaTable.cpp.
Referenced by mdtSqlDatabaseManager::createTable().
The documentation for this class was generated from the following files:
src/mdtutilsgui/mdtSqlSchemaTable.h
src/mdtutilsgui/mdtSqlSchemaTable.cpp