Multi diag tools: mdtTtLogicalTestCableTsWidget Class Reference
mdtTtLogicalTestCableTsWidget Class Reference
Helper class for logical test cable generation.
#include <mdtTtLogicalTestCableTsWidget.h>
Public Member Functions
mdtTtLogicalTestCableTsWidget (QWidget *parent, QSqlDatabase db)
Constructor.
void setTestCableConnector (const QVariant &connectorId, const QString &name)
Set test cable connector.
void setTestCableConnection (const QVariant &connectionId, const QString &name)
Set test cable connection.
void setTestSystem (const QVariant &tsVtId)
Set test system.
mdtTtLogicalTestCableDialog::cnType_t cnType () const
Get cn type.
QVariant cnId () const
Get cn ID.
QString testCableCnName () const
Get test cable cn name.
bool containsTestCableConnection (const QVariant &testCableConnectionId, bool &ok)
Check if this affectation contains given (physical) test cable connection.
QList< QVariant > getAffectedTsConnections (bool &ok)
Get list of unit connections.
Detailed Description
Helper class for logical test cable generation.
Definition at line 35 of file mdtTtLogicalTestCableTsWidget.h.
Constructor & Destructor Documentation
mdtTtLogicalTestCableTsWidget::mdtTtLogicalTestCableTsWidget (QWidget * parent, QSqlDatabase db)
Constructor.
Definition at line 34 of file mdtTtLogicalTestCableTsWidget.cpp.
Member Function Documentation
QVariant mdtTtLogicalTestCableTsWidget::cnId () const inline
Get cn ID.
Definition at line 66 of file mdtTtLogicalTestCableTsWidget.h.
mdtTtLogicalTestCableDialog::cnType_t mdtTtLogicalTestCableTsWidget::cnType () const inline
Get cn type.
Definition at line 59 of file mdtTtLogicalTestCableTsWidget.h.
bool mdtTtLogicalTestCableTsWidget::containsTestCableConnection (const QVariant & testCableConnectionId, bool & ok)
Check if this affectation contains given (physical) test cable connection.
Definition at line 114 of file mdtTtLogicalTestCableTsWidget.cpp.
References mdtTtLogicalTestCableDialog::Connection, mdtTtLogicalTestCableDialog::Connector, mdtTtBase::getDataList(), and mdtTtBase::lastError().
QList< QVariant > mdtTtLogicalTestCableTsWidget::getAffectedTsConnections (bool & ok)
Get list of unit connections.
If affectation's type is a connector, all connections that are part of affected test system connector will be returned. If affectation's type is a connection, test system affected connection will be returned.
Definition at line 92 of file mdtTtLogicalTestCableTsWidget.cpp.
References mdtTtLogicalTestCableDialog::Connection, mdtTtLogicalTestCableDialog::Connector, mdtTtBase::getDataList(), and mdtTtBase::lastError().
void mdtTtLogicalTestCableTsWidget::setTestCableConnection (const QVariant & connectionId, const QString & name)
Set test cable connection.
Definition at line 55 of file mdtTtLogicalTestCableTsWidget.cpp.
References mdtTtLogicalTestCableDialog::Connection.
Referenced by mdtTtLogicalTestCableDialog::setTestCable().
void mdtTtLogicalTestCableTsWidget::setTestCableConnector (const QVariant & connectorId, const QString & name)
Set test cable connector.
Definition at line 46 of file mdtTtLogicalTestCableTsWidget.cpp.
References mdtTtLogicalTestCableDialog::Connector.
Referenced by mdtTtLogicalTestCableDialog::setTestCable().
void mdtTtLogicalTestCableTsWidget::setTestSystem (const QVariant & tsVtId)
Set test system.
Definition at line 64 of file mdtTtLogicalTestCableTsWidget.cpp.
References mdtTtBase::getDataList().
QString mdtTtLogicalTestCableTsWidget::testCableCnName () const inline
Get test cable cn name.
Definition at line 72 of file mdtTtLogicalTestCableTsWidget.h.
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtTtLogicalTestCableTsWidget.h
src/mdttools/mdttesttool/mdtTtLogicalTestCableTsWidget.cpp