Multi diag tools: mdtSerialPortConfig Class Reference
mdtSerialPortConfig Class Reference
#include <mdtSerialPortConfig.h>
Public Types
enum parity_t { NoParity, ParityOdd, ParityEven }
Public Member Functions
mdtSerialPortConfig ()
~mdtSerialPortConfig ()
void setDefault ()
Set default configuration Default configuration is:
void setBaudRate (int baudRate)
int baudRate () const
void setParity (parity_t parity)
parity_t parity () const
void setDataBitsCount (int n)
int dataBitsCount () const
void setStopBitsCount (int n)
int stopBitsCount () const
void enableFlowCtlRtsCts ()
void diseableFlowCtlRtsCts ()
bool flowCtlRtsCtsEnabled () const
void enableFlowCtlXonXoff (char _xonChar=0x11, char _xoffChar=0x13)
void diseableFlowCtlXonXoff ()
bool flowCtlXonXoffEnabled () const
char xonChar () const
char xoffChar () const
bool isValid () const
bool operator== (const mdtSerialPortConfig &other)
NOTE: pas claire (héritage.. + test passe toujours..)
bool operator!= (const mdtSerialPortConfig &other)
Public Member Functions inherited from mdtPortConfig
mdtPortConfig ()
virtual ~mdtPortConfig ()
void setReadFrameSize (int size)
Set the read frame size.
int readFrameSize () const
Get the read frame size.
void setReadQueueSize (int size)
Set the read Queue size.
int readQueueSize () const
Get the read Queue size.
void setUseReadTimeoutProtocol (bool use)
Use the read timeout protocol.
bool useReadTimeoutProtocol () const
Know if read timeout protocol must be used.
void setReadTimeout (int timeout)
Set the read timeout.
int readTimeout () const
Get read timeout.
void setWriteInterframeTime (int time)
Set the write interframe time.
int writeInterframeTime () const
Get the write interframe time [ms].
void setWriteTimeout (int timeout)
Set the write timeout.
int writeTimeout () const
Get write timeout.
void setWriteFrameSize (int size)
Set the write frame size.
int writeFrameSize () const
Get the read frame size.
void setWriteQueueSize (int size)
Set the read Queue size.
int writeQueueSize () const
Get the write Queue size.
void setFrameType (const mdtFrame::type_t type)
Set frame type.
mdtFrame::type_t frameType () const
Get frame type.
void setEndOfFrameSeq (const QByteArray &seq)
Set the end of frame sequence (applies on ASCII frames)
void setEndOfFrameSeq (char c)
Set the end of frame sequence (applies on ASCII frames)
QByteArray endOfFrameSeq () const
Get the end of frame sequence.
void setBytePerByteWrite (bool on, int waitTime)
Set the byte per byte write On/Off.
bool bytePerByteWrite () const
Get byte per byte write flag (On/Off)
int writeInterbyteTime () const
Get the write time between bytes [ms].
void setConnectTimeout (int timeout)
Set the connection timeout.
int connectTimeout () const
Get the connection timeout.
void setConnectMaxTry (int maxTry)
Set the maximum connection try.
int connectMaxTry () const
Get the maximum connection try.
bool operator== (const mdtPortConfig &other)
bool operator!= (const mdtPortConfig &other)
Additional Inherited Members
Protected Member Functions inherited from mdtPortConfig
bool matches (const mdtPortConfig &other)
Protected Attributes inherited from mdtPortConfig
int pvReadFrameSize
int pvReadQueueSize
bool pvUseReadTimeoutProtocol
int pvReadTimeout
int pvWriteFrameSize
int pvWriteQueueSize
int pvWriteInterbyteTime
int pvWriteInterframeTime
int pvWriteTimeout
mdtFrame::type_t pvFrameType
QByteArray pvEndOfFrameSeq
bool pvBytePerByteWrite
int pvConnectMaxTry
int pvConnectTimeout
Detailed Description
Definition at line 33 of file mdtSerialPortConfig.h.
Member Enumeration Documentation
enum mdtSerialPortConfig::parity_t
Enumerator
NoParity
ParityOdd
ParityEven
Definition at line 37 of file mdtSerialPortConfig.h.
Constructor & Destructor Documentation
mdtSerialPortConfig::mdtSerialPortConfig ()
Definition at line 25 of file mdtSerialPortConfig.cpp.
References setDefault().
mdtSerialPortConfig::~mdtSerialPortConfig ()
Definition at line 30 of file mdtSerialPortConfig.cpp.
Member Function Documentation
int mdtSerialPortConfig::baudRate () const
Definition at line 53 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig(), and setBaudRate().
int mdtSerialPortConfig::dataBitsCount () const
Definition at line 73 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig().
void mdtSerialPortConfig::diseableFlowCtlRtsCts ()
Definition at line 93 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::updateConfig().
void mdtSerialPortConfig::diseableFlowCtlXonXoff ()
Definition at line 110 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::updateConfig().
void mdtSerialPortConfig::enableFlowCtlRtsCts ()
Definition at line 88 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::updateConfig().
void mdtSerialPortConfig::enableFlowCtlXonXoff (char _xonChar = 0x11, char _xoffChar = 0x13)
Definition at line 103 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::updateConfig().
bool mdtSerialPortConfig::flowCtlRtsCtsEnabled () const
Definition at line 98 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig().
bool mdtSerialPortConfig::flowCtlXonXoffEnabled () const
Definition at line 115 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig().
bool mdtSerialPortConfig::isValid () const
Definition at line 130 of file mdtSerialPortConfig.cpp.
bool mdtSerialPortConfig::operator!= (const mdtSerialPortConfig & other)
Definition at line 140 of file mdtSerialPortConfig.cpp.
bool mdtSerialPortConfig::operator== (const mdtSerialPortConfig & other)
NOTE: pas claire (héritage.. + test passe toujours..)
Definition at line 135 of file mdtSerialPortConfig.cpp.
mdtSerialPortConfig::parity_t mdtSerialPortConfig::parity () const
Definition at line 63 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig().
void mdtSerialPortConfig::setBaudRate (int baudRate)
Definition at line 48 of file mdtSerialPortConfig.cpp.
References baudRate().
Referenced by mdtSerialPortConfigWidget::updateConfig().
void mdtSerialPortConfig::setDataBitsCount (int n)
Definition at line 68 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::updateConfig().
void mdtSerialPortConfig::setDefault () virtual
Set default configuration Default configuration is:
Interface: /dev/ttyS0 (Posix) or COM1 (Windows)
Baud rate: 9600
Data bits: 8
Stop bits: 1
Parity: none
Flow control: none
Reimplemented from mdtPortConfig.
Definition at line 34 of file mdtSerialPortConfig.cpp.
References MDT_DEF_XOFF, MDT_DEF_XON, NoParity, and mdtPortConfig::setDefault().
Referenced by mdtSerialPortConfig().
void mdtSerialPortConfig::setParity (mdtSerialPortConfig::parity_t _parity)
Definition at line 58 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::updateConfig().
void mdtSerialPortConfig::setStopBitsCount (int n)
Definition at line 78 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::updateConfig().
int mdtSerialPortConfig::stopBitsCount () const
Definition at line 83 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig().
char mdtSerialPortConfig::xoffChar () const
Definition at line 125 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig().
char mdtSerialPortConfig::xonChar () const
Definition at line 120 of file mdtSerialPortConfig.cpp.
Referenced by mdtSerialPortConfigWidget::displayConfig().
The documentation for this class was generated from the following files:
src/mdtserialport/mdtSerialPortConfig.h
src/mdtserialport/mdtSerialPortConfig.cpp