Multi diag tools: mdtClArticleLinkDialog Class Reference
mdtClArticleLinkDialog Class Reference
Dialog that let the user edit a article link.
#include <mdtClArticleLinkDialog.h>
Public Member Functions
mdtClArticleLinkDialog (QWidget *parent, QSqlDatabase db, QVariant articleId)
Constructor.
~mdtClArticleLinkDialog ()
Destructor.
void setLinkTypeCode (const QVariant &code)
Display link type in combobox.
void setLinkDirectionCode (const QVariant &code)
Display link direction in combobox.
void setValue (const QVariant &value)
Display value.
void setStartConnectionId (const QVariant &id)
Store id as current selected start connection and display it.
void setEndConnectionId (const QVariant &id)
Store id as current selected end connection and display it.
mdtSqlRecord linkData () const
Get link data.
Additional Inherited Members
Public Attributes inherited from Ui_mdtClArticleLinkDialog
QVBoxLayout * verticalLayout
QFormLayout * formLayout_3
QLabel * lbLinkType
QComboBox * cbLinkType
QLabel * lbLinkDirection
QHBoxLayout * horizontalLayout_3
QComboBox * cbLinkDirection
QLabel * lbLinkDirectionAsciiPicture
QLabel * lbValue
QHBoxLayout * horizontalLayout
QDoubleSpinBox * sbValue
QLabel * lbUnit
QHBoxLayout * horizontalLayout_2
QGroupBox * gbStartConnection
QFormLayout * formLayout
QLabel * lbStartConnectorNameLabel
QLabel * lbStartConnectorName
QLabel * lbStartContactNameLabel
QLabel * lbStartContactName
QPushButton * pbStartConnection
QGroupBox * gbEndConnection
QFormLayout * formLayout_2
QLabel * lbEndConnectorNameLabel
QLabel * lbEndConnectorName
QLabel * lbEndContactNameLabel
QLabel * lbEndContactName
QPushButton * pbEndConnection
QDialogButtonBox * buttonBox
Detailed Description
Dialog that let the user edit a article link.
Definition at line 35 of file mdtClArticleLinkDialog.h.
Constructor & Destructor Documentation
mdtClArticleLinkDialog::mdtClArticleLinkDialog (QWidget * parent, QSqlDatabase db, QVariant articleId)
Constructor.
Definition at line 36 of file mdtClArticleLinkDialog.cpp.
References mdtSqlRecord::addAllFields(), Ui_mdtClArticleLinkDialog::cbLinkDirection, Ui_mdtClArticleLinkDialog::cbLinkType, mdtSqlRecord::lastError(), Ui_mdtClArticleLinkDialog::lbEndConnectorName, Ui_mdtClArticleLinkDialog::lbEndContactName, Ui_mdtClArticleLinkDialog::lbStartConnectorName, Ui_mdtClArticleLinkDialog::lbStartContactName, Ui_mdtClArticleLinkDialog::lbUnit, Ui_mdtClArticleLinkDialog::pbEndConnection, Ui_mdtClArticleLinkDialog::pbStartConnection, Ui_mdtClArticleLinkDialog::setupUi(), mdtError::systemText(), and mdtError::text().
mdtClArticleLinkDialog::~mdtClArticleLinkDialog ()
Destructor.
Definition at line 82 of file mdtClArticleLinkDialog.cpp.
Member Function Documentation
mdtSqlRecord mdtClArticleLinkDialog::linkData () const
Get link data.
Definition at line 138 of file mdtClArticleLinkDialog.cpp.
void mdtClArticleLinkDialog::setEndConnectionId (const QVariant & id)
Store id as current selected end connection and display it.
Definition at line 132 of file mdtClArticleLinkDialog.cpp.
References mdtSqlRecord::setValue().
void mdtClArticleLinkDialog::setLinkDirectionCode (const QVariant & code)
Display link direction in combobox.
Definition at line 103 of file mdtClArticleLinkDialog.cpp.
References Ui_mdtClArticleLinkDialog::cbLinkDirection, and mdtSqlRecord::setValue().
void mdtClArticleLinkDialog::setLinkTypeCode (const QVariant & code)
Display link type in combobox.
Definition at line 86 of file mdtClArticleLinkDialog.cpp.
References Ui_mdtClArticleLinkDialog::cbLinkType, and mdtSqlRecord::setValue().
void mdtClArticleLinkDialog::setStartConnectionId (const QVariant & id)
Store id as current selected start connection and display it.
Definition at line 126 of file mdtClArticleLinkDialog.cpp.
References mdtSqlRecord::setValue().
void mdtClArticleLinkDialog::setValue (const QVariant & value)
Display value.
Definition at line 120 of file mdtClArticleLinkDialog.cpp.
References Ui_mdtClArticleLinkDialog::sbValue, and mdtSqlRecord::setValue().
The documentation for this class was generated from the following files:
src/mdttools/mdttesttool/mdtcablelist/mdtClArticleLinkDialog.h
src/mdttools/mdttesttool/mdtcablelist/mdtClArticleLinkDialog.cpp