Multi diag tools: QtLockedFile Class Reference
QtLockedFile Class Reference
namespace QtLP_Private {
#include <qtlockedfile.h>
Public Types
enum LockMode { NoLock = 0, ReadLock, WriteLock }
Public Member Functions
QtLockedFile ()
QtLockedFile (const QString &name)
~QtLockedFile ()
bool open (OpenMode mode)
bool lock (LockMode mode, bool block=true)
using namespace QtLP_Private;
bool unlock ()
bool isLocked () const
LockMode lockMode () const
Detailed Description
namespace QtLP_Private {
using namespace QtLP_Private;
The QtLockedFile class extends QFile with advisory locking functions.
A file may be locked in read or write mode. Multiple instances of QtLockedFile, created in multiple processes running on the same machine, may have a file locked in read mode. Exactly one instance may have it locked in write mode. A read and a write lock cannot exist simultaneously on the same file.
The file locks are advisory. This means that nothing prevents another process from manipulating a locked file using QFile or file system functions offered by the OS. Serialization is only guaranteed if all processes that access the file use QLockedFile. Also, while holding a lock on a file, a process must not open the same file again (through any API), or locks can be unexpectedly lost.
The lock provided by an instance of QtLockedFile is released whenever the program terminates. This is true even when the program crashes and no destructors are called.
Definition at line 66 of file qtlockedfile.h.
Member Enumeration Documentation
enum QtLockedFile::LockMode
This enum describes the available lock modes.
ReadLock A read lock. WriteLock A write lock. NoLock Neither a read lock nor a write lock.
Enumerator
NoLock
ReadLock
WriteLock
Definition at line 69 of file qtlockedfile.h.
Constructor & Destructor Documentation
QtLockedFile::QtLockedFile ()
Constructs an unlocked QtLockedFile object. This constructor behaves in the same way as QFile::QFile().
See Also
QFile::QFile()
Definition at line 84 of file qtlockedfile.cpp.
References NoLock.
QtLockedFile::QtLockedFile (const QString & name)
Constructs an unlocked QtLockedFile object with file name. This constructor behaves in the same way as QFile::QFile(const QString&).
See Also
QFile::QFile()
Definition at line 101 of file qtlockedfile.cpp.
References NoLock.
QtLockedFile::~QtLockedFile ()
Destroys the QtLockedFile object. If any locks were held, they are released.
Definition at line 110 of file qtlockedfile_unix.cpp.
References unlock().
Member Function Documentation
bool QtLockedFile::isLocked () const
Returns true if this object has a in read or write lock; otherwise returns false.
See Also
lockMode()
Definition at line 139 of file qtlockedfile.cpp.
References NoLock.
Referenced by QtLocalPeer::isClient(), and unlock().
bool QtLockedFile::lock (LockMode mode, bool block = true)
using namespace QtLP_Private;
Obtains a lock of type mode. The file must be opened before it can be locked.
If block is true, this function will block until the lock is aquired. If block is false, this function returns false immediately if the lock cannot be aquired.
If this object already has a lock of type mode, this function returns true immediately. If this object has a lock of a different type than mode, the lock is first released and then a new lock is obtained.
This function returns true if, after it executes, the file is locked by this object, and false otherwise.
See Also
unlock(), isLocked(), lockMode()
Definition at line 49 of file qtlockedfile_unix.cpp.
References NoLock, ReadLock, and unlock().
Referenced by QtLocalPeer::isClient().
QtLockedFile::LockMode QtLockedFile::lockMode () const
Returns the type of lock currently held by this object, or QtLockedFile::NoLock.
See Also
isLocked()
Definition at line 150 of file qtlockedfile.cpp.
bool QtLockedFile::open (OpenMode mode)
Opens the file in OpenMode mode.
This is identical to QFile::open(), with the one exception that the Truncate mode flag is disallowed. Truncation would conflict with the advisory file locking, since the file would be modified before the write lock is obtained. If truncation is required, use resize(0) after obtaining the write lock.
Returns true if successful; otherwise false.
See Also
QFile::open(), QFile::resize()
Definition at line 124 of file qtlockedfile.cpp.
Referenced by QtLocalPeer::QtLocalPeer().
bool QtLockedFile::unlock ()
Releases a lock.
If the object has no lock, this function returns immediately.
This function returns true if, after it executes, the file is not locked by this object, and false otherwise.
See Also
lock(), isLocked(), lockMode()
Definition at line 84 of file qtlockedfile_unix.cpp.
References isLocked(), and NoLock.
Referenced by lock(), and ~QtLockedFile().
The documentation for this class was generated from the following files:
src/qt-solutions/qtsingleapplication/qtlockedfile.h
src/qt-solutions/qtsingleapplication/qtlockedfile.cpp
src/qt-solutions/qtsingleapplication/qtlockedfile_unix.cpp
src/qt-solutions/qtsingleapplication/qtlockedfile_win.cpp