Multi diag tools: mdtUsbtmcTxMessage Class Reference
mdtUsbtmcTxMessage Class Reference
USBTMC message.
#include <mdtUsbtmcMessage.h>
Public Member Functions
mdtUsbtmcTxMessage (const QByteArray &ba)
Construct a message that acts on given byte array.
void reset ()
Reset internal cursor to the beginning of byte array.
int bytesToRead () const
Get amount of bytes that are to read.
bool hasBytesToRead () const
Check if there are bytes to read from byte array.
int read (uint8_t *dest, int max)
Copy data from byte array to buffer.
Detailed Description
USBTMC message.
For concept of USBTMC message, see USBTMC 1.0 specifications, section 3.2.1.1 and 3.3.1
Construct a message that acts on given byte array
Reset internal cursor to the beginning of byte array
Get amount of bytes that are to read
Check if there are bytes to read from byte array
Copy data from byte array to buffer
Parameters
dest Pointer to destination buffer
max Maximum count of bytes to copy
Returns
Number of bytes that was copied
Precondition
dest must be valid
Postcondition
Will never copy more than max bytes
Copy data from buffer to byte array
Will resize byte array so that all data can be copied.
Parameters
src Pointer to source buffer
n Number of bytes to copy
Precondition
src must be valid
n must be >= 0
USBTMC message for sending data to device
For concept of USBTMC message, see USBTMC 1.0 specifications, section 3.2.1.1 and 3.3.1
Definition at line 138 of file mdtUsbtmcMessage.h.
Constructor & Destructor Documentation
mdtUsbtmcTxMessage::mdtUsbtmcTxMessage (const QByteArray & ba) inline
Construct a message that acts on given byte array.
Definition at line 144 of file mdtUsbtmcMessage.h.
Member Function Documentation
int mdtUsbtmcTxMessage::bytesToRead () const inline
Get amount of bytes that are to read.
Definition at line 159 of file mdtUsbtmcMessage.h.
Referenced by hasBytesToRead(), read(), and mdtUsbtmcFrame::setData().
bool mdtUsbtmcTxMessage::hasBytesToRead () const inline
Check if there are bytes to read from byte array.
Definition at line 170 of file mdtUsbtmcMessage.h.
References bytesToRead().
Referenced by mdtUsbtmcPort::sendCommand(), and mdtUsbtmcBulkTransfer::setupDevDepMsgOut().
int mdtUsbtmcTxMessage::read (uint8_t * dest, int max) inline
Copy data from byte array to buffer.
Parameters
dest Pointer to destination buffer
max Maximum count of bytes to copy
Returns
Number of bytes that was copied
Precondition
dest must be valid
Postcondition
Will never copy more than max bytes
Definition at line 183 of file mdtUsbtmcMessage.h.
References bytesToRead(), and reset().
Referenced by mdtUsbtmcFrame::setData().
void mdtUsbtmcTxMessage::reset () inline
Reset internal cursor to the beginning of byte array.
Definition at line 152 of file mdtUsbtmcMessage.h.
Referenced by read().
The documentation for this class was generated from the following file:
src/mdtport/mdtUsbtmcMessage.h