Multi diag tools: mdtSerialPort Class Reference
mdtSerialPort Class Reference
#include <mdtSerialPort.h>
Public Member Functions
mdtSerialPort (QObject *parent=0)
~mdtSerialPort ()
bool setBaudRate (int rate)
Set the baud rate.
int baudRate ()
Get the baud rate.
bool setDataBits (int n)
Set number of data bits.
int dataBits ()
Get number of data bits.
bool setStopBits (int n)
Set number of stop bits.
int stopBits ()
Get number of stop bits.
bool setParity (mdtSerialPortConfig::parity_t p)
Set parity check.
mdtSerialPortConfig::parity_t parity ()
Get configured parity.
bool setFlowCtlRtsCts (bool on)
Enable/diseable RTS/CTS flow control.
bool flowCtlRtsCtsOn ()
Get configured state of RTS/CTS flow control.
bool setFlowCtlXonXoff (bool on, char xonChar, char xoffChar)
Enable/diseable Xon/Xoff flow control.
bool flowCtlXonXoffOn ()
Get configured state of Xon/Xoff flow control.
void setReadTimeout (int timeout)
Set the read data timeout.
void setWriteTimeout (int timeout)
Set the write data timeout.
error_t waitForReadyRead ()
Wait until data is available on port.
qint64 read (char *data, qint64 maxSize)
Read data from port.
bool suspendTransmission ()
Request to suspend transmission.
bool resumeTransmission ()
Request to resume transmission.
error_t waitEventWriteReady ()
void flushIn();
qint64 write (const char *data, qint64 maxSize)
Write data to port.
error_t waitEventCtl ()
void flushOut();
bool getCtlStates ()
NOTE:
void setRts (bool on)
Enable/diseable the RTS (Request To Send) signal.
void setDtr (bool on)
Enable/diseable the DTR (Data Terminal Ready) signal.
Public Member Functions inherited from mdtAbstractSerialPort
mdtAbstractSerialPort (QObject *parent=0)
virtual ~mdtAbstractSerialPort ()
void close ()
Close the serial port.
mdtSerialPortConfig & config ()
Get the stored configuration.
sp_uart_type_t uartType ()
Get UART type.
QString uartTypeStr ()
QList< int > & availableBaudRates ()
Get the list of available baud rates.
bool carIsOn ()
Get the CAR (CD) state.
bool dsrIsOn ()
Get the DSR state.
bool ctsIsOn ()
Get the CTS state.
bool rngIsOn ()
Get the RNG (RI) state.
Public Member Functions inherited from mdtAbstractPort
mdtAbstractPort (QObject *parent=0)
virtual ~mdtAbstractPort ()
Destructor.
void setPortName (const QString &portName)
Set the port name.
QString & portName ()
Get port name.
error_t open ()
Open the port given by setPortName()
bool isOpen () const
Get port's open state.
void setConfig (mdtPortConfig *cfg)
Set configuration.
mdtPortConfig & config ()
Get the stored configuration.
error_t setup ()
Setup port with given configurations.
virtual error_t reconnect (int timeout)
Reconnect device/peer.
error_t waitForReadyRead (int msecs)
Wait until data is available on port.
void flushIn ()
Flush read buffers.
bool flushInRequestPending ()
Check if a flush in request is pending.
void flushOut ()
Flush write buffers.
bool flushOutRequestPending ()
Check if a flush out request is pending.
void flush ()
Flush read/write buffers.
void initQueues ()
Init the read ans write queues.
QQueue< mdtFrame * > & readenFrames ()
Get the readen frames Queue.
QQueue< mdtFrame * > & readFramesPool ()
Get the read frames Queue pool.
virtual void addFrameToWrite (mdtFrame *frame)
Add a frame to write.
mdtFrame * getFrameToWrite ()
Wait until a frame to write is available and get it.
void abortFrameToWriteWait ()
Abort the frame tp write waiting.
QQueue< mdtFrame * > & writeFrames ()
Get the write frames Queue.
QQueue< mdtFrame * > & writeFramesPool ()
Get the write frames Queue pool.
void lockMutex ()
Lock the mutex.
void unlockMutex ()
Unlock the mutex.
Additional Inherited Members
Public Types inherited from mdtAbstractSerialPort
enum sp_uart_type_t {
UT_UNKNOW, UT_8250, UT_16450, UT_16550,
UT_16550A, UT_CIRRUS, UT_16650, UT_16650V2,
UT_16750, UT_STARTECH, UT_16C950, UT_16654,
UT_16850, UT_RSA
}
UART type.
Public Slots inherited from mdtAbstractSerialPort
Signals inherited from mdtAbstractSerialPort
void carChanged (bool on)
Emited whenn CAR (CD) status changed.
void dsrChanged (bool on)
Emited whenn DSR status changed.
void ctsChanged (bool on)
Emited whenn CTS status changed.
void rngChanged (bool on)
Emited whenn RNG (RI) status changed.
Protected Attributes inherited from mdtAbstractSerialPort
bool pvCarIsOn
bool pvDsrIsOn
bool pvCtsIsOn
bool pvRngIsOn
sp_uart_type_t pvUartType
QList< int > pvAvailableBaudRates
Detailed Description
Definition at line 40 of file mdtSerialPort.h.
Constructor & Destructor Documentation
mdtSerialPort::mdtSerialPort (QObject * parent = 0)
Definition at line 35 of file mdtSerialPort.cpp.
mdtSerialPort::~mdtSerialPort ()
Definition at line 47 of file mdtSerialPort.cpp.
References mdtAbstractSerialPort::close().
Member Function Documentation
int mdtSerialPort::baudRate () virtual
Get the baud rate.
The mutex is not handled by this method.
Returns
Configured baud rate, or 0 on error.
Implements mdtAbstractSerialPort.
Definition at line 210 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
Referenced by setBaudRate().
int mdtSerialPort::dataBits () virtual
Get number of data bits.
The mutex is not handled by this method.
Returns
Configured data bits count or 0 on error.
Implements mdtAbstractSerialPort.
Definition at line 400 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
Referenced by setDataBits().
bool mdtSerialPort::flowCtlRtsCtsOn () virtual
Get configured state of RTS/CTS flow control.
The mutex is not handled by this method.
Returns
True if RTS/CTS flow control is enabled (and no error occured).
Implements mdtAbstractSerialPort.
Definition at line 543 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
Referenced by resumeTransmission(), setFlowCtlRtsCts(), and suspendTransmission().
bool mdtSerialPort::flowCtlXonXoffOn () virtual
Get configured state of Xon/Xoff flow control.
The mutex is not handled by this method.
Returns
True if Xon/Xoff flow control is enabled (and no error occured).
Implements mdtAbstractSerialPort.
Definition at line 582 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
Referenced by resumeTransmission(), setFlowCtlXonXoff(), and suspendTransmission().
bool mdtSerialPort::getCtlStates () virtual
NOTE:
Todo:
Update name to : updateCtlStates ?
Get the control (modem line) signal states and update member flags
This method must be re-implemented in plateform specific subclass.
Returns
False on error, in this case, the thread will be stopped.
Implements mdtAbstractSerialPort.
Definition at line 818 of file mdtSerialPort.cpp.
References mdtAbstractSerialPort::carChanged(), mdtError::commit(), mdtAbstractSerialPort::ctsChanged(), mdtAbstractSerialPort::dsrChanged(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractSerialPort::pvCarIsOn, mdtAbstractSerialPort::pvCtsIsOn, mdtAbstractSerialPort::pvDsrIsOn, mdtAbstractSerialPort::pvRngIsOn, mdtAbstractSerialPort::rngChanged(), and mdtError::setSystemError().
mdtSerialPortConfig::parity_t mdtSerialPort::parity () virtual
Get configured parity.
The mutex is not handled by this method.
Returns
Configured parity or NoParity on error.
Implements mdtAbstractSerialPort.
Definition at line 500 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, mdtSerialPortConfig::NoParity, mdtSerialPortConfig::ParityEven, mdtSerialPortConfig::ParityOdd, and mdtError::setSystemError().
Referenced by setParity().
qint64 mdtSerialPort::read (char * data, qint64 maxSize) virtual
Read data from port.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex is not handled by this method.
Implements mdtAbstractPort.
Definition at line 657 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, mdtAbstractPort::ReadTimeout, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
bool mdtSerialPort::resumeTransmission () virtual
Request to resume transmission.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex is not handled by this method.
Subclass notes:
This method must be implemented in subclass if requierd.
Note about serial port subclass:
the right flow control must be used regarding enabled flow control.
Default implementation does nothing.
Returns
False on error, in this case, the reader thread will be stopped.
Reimplemented from mdtAbstractPort.
Definition at line 706 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, flowCtlRtsCtsOn(), flowCtlXonXoffOn(), MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
bool mdtSerialPort::setBaudRate (int rate) virtual
Set the baud rate.
The mutex is not handled by this method.
Returns
True if baud rate is supported and could be set.
Implements mdtAbstractSerialPort.
Definition at line 53 of file mdtSerialPort.cpp.
References baudRate(), mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
bool mdtSerialPort::setDataBits (int n) virtual
Set number of data bits.
The mutex is not handled by this method.
Returns
True if data bits count is supported and could be set.
Implements mdtAbstractSerialPort.
Definition at line 362 of file mdtSerialPort.cpp.
References mdtError::commit(), dataBits(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
void mdtSerialPort::setDtr (bool on) virtual
Enable/diseable the DTR (Data Terminal Ready) signal.
This method must be re-implemented in plateform specific subclass.
If port is not open, this method must make no system call.
The mutex is handled in this method.
Parameters
on If true, DTR will be enabled, diseabled else
Implements mdtAbstractSerialPort.
Definition at line 893 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, mdtAbstractPort::isOpen(), MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractPort::pvMutex, and mdtError::setSystemError().
bool mdtSerialPort::setFlowCtlRtsCts (bool on) virtual
Enable/diseable RTS/CTS flow control.
The mutex is not handled by this method.
Returns
True if RTS/CTS flow control is supported and could be set.
Implements mdtAbstractSerialPort.
Definition at line 520 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, flowCtlRtsCtsOn(), MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
bool mdtSerialPort::setFlowCtlXonXoff (bool on, char xonChar, char xoffChar) virtual
Enable/diseable Xon/Xoff flow control.
The mutex is not handled by this method.
Returns
True if Xon/Xoff flow control is supported and could be set.
Implements mdtAbstractSerialPort.
Definition at line 557 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, flowCtlXonXoffOn(), MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
bool mdtSerialPort::setParity (mdtSerialPortConfig::parity_t p) virtual
Set parity check.
The mutex is not handled by this method.
Returns
True if parity check is supported and could be set.
Implements mdtAbstractSerialPort.
Definition at line 468 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, mdtSerialPortConfig::NoParity, parity(), mdtSerialPortConfig::ParityOdd, and mdtError::setSystemError().
void mdtSerialPort::setReadTimeout (int timeout) virtual
Set the read data timeout.
The mutex is not handled by this method.
Implements mdtAbstractPort.
Definition at line 596 of file mdtSerialPort.cpp.
void mdtSerialPort::setRts (bool on) virtual
Enable/diseable the RTS (Request To Send) signal.
This method must be re-implemented in plateform specific subclass.
If port is not open, this method must make no system call.
The mutex is handled in this method.
Parameters
on If true, RTS will be enabled, diseabled else
Implements mdtAbstractSerialPort.
Definition at line 879 of file mdtSerialPort.cpp.
References mdtAbstractPort::isOpen(), and mdtAbstractPort::pvMutex.
bool mdtSerialPort::setStopBits (int n) virtual
Set number of stop bits.
The mutex is not handled by this method.
Returns
True if stop bits count is supported and could be set.
Implements mdtAbstractSerialPort.
Definition at line 427 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, mdtError::setSystemError(), and stopBits().
void mdtSerialPort::setWriteTimeout (int timeout) virtual
Set the write data timeout.
The mutex is not handled by this method.
Implements mdtAbstractPort.
Definition at line 607 of file mdtSerialPort.cpp.
int mdtSerialPort::stopBits () virtual
Get number of stop bits.
The mutex is not handled by this method.
Returns
Configured stop bits count or -1 on error.
Implements mdtAbstractSerialPort.
Definition at line 452 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
Referenced by setStopBits().
bool mdtSerialPort::suspendTransmission () virtual
Request to suspend transmission.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex is not handled by this method.
Subclass notes:
This method must be implemented in subclass if requierd.
Note about serial port subclass:
the right flow control must be used regarding enabled flow control.
Default implementation does nothing.
Returns
False on error, in this case, the reader thread will be stopped.
Reimplemented from mdtAbstractPort.
Definition at line 683 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, flowCtlRtsCtsOn(), flowCtlXonXoffOn(), MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, and mdtError::setSystemError().
mdtAbstractPort::error_t mdtSerialPort::waitEventCtl () virtual
void flushOut();
Wait until a control (modem line) signal state changes
This method is called from mdtSerialPortCtlThread , and should not be used directly.
Mutex must be locked before calling this method with lockMutex(). The mutex is locked when method returns.
Implements mdtAbstractSerialPort.
Definition at line 792 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtAbstractPort::ControlCanceled, mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractPort::NoError, mdtAbstractPort::pvMutex, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
mdtAbstractPort::error_t mdtSerialPort::waitEventWriteReady () virtual
void flushIn();
Wait until data can be written to port.
This method is called from mdtPortWriteThread , and should not be used directly.
Mutex must be locked before calling this method with lockMutex(). The mutex is locked when method returns.
Implements mdtAbstractPort.
Definition at line 729 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractPort::NoError, mdtAbstractPort::pvMutex, mdtError::setSystemError(), mdtAbstractPort::UnhandledError, mdtAbstractPort::WriteCanceled, and mdtAbstractPort::WriteTimeout.
mdtAbstractPort::error_t mdtSerialPort::waitForReadyRead () virtual
Wait until data is available on port.
This method is called from mdtPortReadThread , and should not be used directly.
Mutex must be locked before calling this method with lockMutex(). The mutex is locked when method returns.
Implements mdtAbstractPort.
Definition at line 618 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_UNDEFINED_ERROR, mdtAbstractPort::NoError, mdtAbstractPort::pvMutex, mdtAbstractPort::ReadCanceled, mdtAbstractPort::ReadTimeout, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
qint64 mdtSerialPort::write (const char * data, qint64 maxSize) virtual
Write data to port.
This method is called from mdtPortWriteThread , and should not be used directly.
Mutex is not handled by this method.
Subclass notes:
This method must be implemented in subclass.
Returns
Number of bytes written, or error < 0 (see error_t)
Implements mdtAbstractPort.
Definition at line 768 of file mdtSerialPort.cpp.
References mdtError::commit(), mdtError::Error, MDT_ERROR_SET_SRC, MDT_SERIAL_PORT_IO_ERROR, mdtError::setSystemError(), and mdtAbstractPort::UnhandledError.
The documentation for this class was generated from the following files:
src/mdtserialport/linux/mdtSerialPort.h
src/mdtserialport/linux/mdtSerialPort.cpp