Multi diag tools: src/mdtutils/mdtValue.h File Reference
mdtValue.h File Reference
#include <QMetaType>
Classes
class mdtValueDouble
Contains a floating (double) value with some attributes.
class mdtValueIntegral< T >
Integral type with Null attribute.
class mdtValueBool
Boolean type with Null attribute.
class mdtValue
Conatins a value with some attributes.
Typedefs
typedef mdtValueIntegral< int > mdtValueInt
mdtValueIntegral with int type value
Functions
QDebug operator<< (QDebug dbg, const mdtValueBool &value)
QDebug operator<< (QDebug dbg, const mdtValueInt &value)
QDebug operator<< (QDebug dbg, const mdtValueDouble &value)
QDebug operator<< (QDebug dbg, const mdtValue &value)
Typedef Documentation
typedef mdtValueIntegral<int> mdtValueInt
mdtValueIntegral with int type value
Definition at line 408 of file mdtValue.h.
Function Documentation
QDebug operator<< (QDebug dbg, const mdtValueBool & value)
Definition at line 133 of file mdtValue.cpp.
References mdtValueBool::isNull(), and mdtValueBool::value().
QDebug operator<< (QDebug dbg, const mdtValueInt & value)
Definition at line 121 of file mdtValue.cpp.
References mdtValueIntegral< T >::isNull(), and mdtValueIntegral< T >::value().
QDebug operator<< (QDebug dbg, const mdtValueDouble & value)
Definition at line 100 of file mdtValue.cpp.
References mdtValueDouble::isMinusOl(), mdtValueDouble::isNaN(), mdtValueDouble::isNull(), mdtValueDouble::isPlusOl(), and mdtValueDouble::value().
QDebug operator<< (QDebug dbg, const mdtValue & value)
Definition at line 318 of file mdtValue.cpp.
References mdtValue::isMinusOl(), mdtValue::isPlusOl(), mdtValue::isValid(), mdtValue::valueBool(), mdtValue::valueDouble(), and mdtValue::valueInt().