Multi diag tools: src/mdtutils/mdtValue.cpp File Reference
mdtValue.cpp File Reference
#include "mdtValue.h"
#include <cfloat>
#include <cmath>
#include <limits>
#include <QtGlobal>
#include <QDebug>
Functions
QDebug operator<< (QDebug dbg, const mdtValueDouble &value)
QDebug operator<< (QDebug dbg, const mdtValueInt &value)
QDebug operator<< (QDebug dbg, const mdtValueBool &value)
QDebug operator<< (QDebug dbg, const mdtValue &value)
Function Documentation
QDebug operator<< (QDebug dbg, const mdtValueDouble & value)
Definition at line 100 of file mdtValue.cpp.
References mdtValueDouble::isMinusOl(), mdtValueDouble::isNaN(), mdtValueDouble::isNull(), mdtValueDouble::isPlusOl(), and mdtValueDouble::value().
QDebug operator<< (QDebug dbg, const mdtValueInt & value)
Definition at line 121 of file mdtValue.cpp.
References mdtValueIntegral< T >::isNull(), and mdtValueIntegral< T >::value().
QDebug operator<< (QDebug dbg, const mdtValueBool & value)
Definition at line 133 of file mdtValue.cpp.
References mdtValueBool::isNull(), and mdtValueBool::value().
QDebug operator<< (QDebug dbg, const mdtValue & value)
Definition at line 318 of file mdtValue.cpp.
References mdtValue::isMinusOl(), mdtValue::isPlusOl(), mdtValue::isValid(), mdtValue::valueBool(), mdtValue::valueDouble(), and mdtValue::valueInt().