Multi diag tools: mdtUsbtmcTransferHandlerStateMachine::StateMachine_ Struct Reference
mdtUsbtmcTransferHandlerStateMachine::StateMachine_ Struct Reference
Main state machine definition class.
#include <mdtUsbtmcTransferHandlerStateMachine.h>
Classes
struct Disconnected
Disconnected state.
struct Error
Error state.
struct Stopped
Stopped state.
struct Stopping
Stopping state.
struct transition_table
Main state machine transition table.
Public Types
typedef Running initial_state
Initial state of main state machine.
typedef StateMachine_ sm
Public Member Functions
StateMachine_ ()
State machine def Constructor.
void setTh (mdtUsbtmcTransferHandler *th)
Set transfer handler.
template<typename EventType >
void restoreAllTransfers (EventType const &)
Restore all transfers to pools action.
void cleanupAndNotifyError (ErrorOccuredEvent const &event)
Restore all transfers to pools + notify error action.
void handleControlTransferCompleted (ControlTransferCompletedEvent const &event)
Handle Control transfer completed action.
void restoreControlTransferNNMTP (ControlTransferCompletedEvent const &event)
Restore Control transfer to pool action.
void restoreBulkOutTransferNNMTP (BulkOutTransferCompletedEvent const &event)
Restore Bulk-OUT transfer to pool action.
void restoreBulkInTransferNNMTP (BulkInTransferCompletedEvent const &event)
Restore Bulk-IN transfer to pool action.
void handleInterruptInTransferCompleted (InterruptInTransferCompletedEvent const &event)
Handle Interrupt-IN transfer completed action.
void restoreInterruptInTransferNNMTP (InterruptInTransferCompletedEvent const &event)
Restore Interrupt-IN transfer to pool action.
bool isUnhandledError (ErrorOccuredEvent const &evt)
Notify that Bulk I/O was aborted.
bool isDeviceDisconnectedError (ErrorOccuredEvent const &evt)
Check if ErrorOccuredEvent contains a device disconnected error.
template<typename EventType >
bool hasNoPendingTransfers (EventType const &)
Check if transfer handler has pending transfers.
template<typename Event , typename FSM >
void on_entry (Event const &, FSM &)
Main state machine entry/ action.
template<typename Event , typename FSM >
void on_exit (Event const &, FSM &)
Main state machine exit/ action.
template<class FSM , class Event >
void no_transition (Event const &e, FSM &, int state)
Called when no transition exists.
Public Attributes
mdtUsbtmcTransferHandler * transferHandler
Detailed Description
Main state machine definition class.
Definition at line 541 of file mdtUsbtmcTransferHandlerStateMachine.h.
Member Typedef Documentation
typedef Running mdtUsbtmcTransferHandlerStateMachine::StateMachine_::initial_state
Initial state of main state machine.
Definition at line 843 of file mdtUsbtmcTransferHandlerStateMachine.h.
typedef StateMachine_ mdtUsbtmcTransferHandlerStateMachine::StateMachine_::sm
Definition at line 846 of file mdtUsbtmcTransferHandlerStateMachine.h.
Constructor & Destructor Documentation
mdtUsbtmcTransferHandlerStateMachine::StateMachine_::StateMachine_ () inline
State machine def Constructor.
Definition at line 545 of file mdtUsbtmcTransferHandlerStateMachine.h.
Member Function Documentation
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::cleanupAndNotifyError (ErrorOccuredEvent const & event) inline
Restore all transfers to pools + notify error action.
Definition at line 575 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::ErrorOccuredEvent::error.
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::handleControlTransferCompleted (ControlTransferCompletedEvent const & event) inline
Handle Control transfer completed action.
Definition at line 585 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::ControlTransferCompletedEvent::transfer.
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::handleInterruptInTransferCompleted (InterruptInTransferCompletedEvent const & event) inline
Handle Interrupt-IN transfer completed action.
Definition at line 635 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::InterruptInTransferCompletedEvent::transfer.
template<typename EventType > bool mdtUsbtmcTransferHandlerStateMachine::StateMachine_::hasNoPendingTransfers (EventType const &) inline
Check if transfer handler has pending transfers.
Definition at line 722 of file mdtUsbtmcTransferHandlerStateMachine.h.
bool mdtUsbtmcTransferHandlerStateMachine::StateMachine_::isDeviceDisconnectedError (ErrorOccuredEvent const & evt) inline
Check if ErrorOccuredEvent contains a device disconnected error.
Definition at line 708 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::ErrorOccuredEvent::error, and mdtError::systemNumber().
bool mdtUsbtmcTransferHandlerStateMachine::StateMachine_::isUnhandledError (ErrorOccuredEvent const & evt) inline
Notify that Bulk I/O was aborted.
Check if ErrorOccuredEvent contains a unhandled error
Definition at line 670 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::ErrorOccuredEvent::error, and mdtError::systemNumber().
template<class FSM , class Event > void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::no_transition (Event const & e, FSM & , int state) inline
Called when no transition exists.
Definition at line 872 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtError::commit(), MDT_ERROR_SET_SRC, and mdtError::Warning.
template<typename Event , typename FSM > void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::on_entry (Event const & , FSM &) inline
Main state machine entry/ action.
Definition at line 731 of file mdtUsbtmcTransferHandlerStateMachine.h.
template<typename Event , typename FSM > void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::on_exit (Event const & , FSM &) inline
Main state machine exit/ action.
Definition at line 739 of file mdtUsbtmcTransferHandlerStateMachine.h.
template<typename EventType > void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::restoreAllTransfers (EventType const &) inline
Restore all transfers to pools action.
Definition at line 566 of file mdtUsbtmcTransferHandlerStateMachine.h.
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::restoreBulkInTransferNNMTP (BulkInTransferCompletedEvent const & event) inline
Restore Bulk-IN transfer to pool action.
This version will send NoMoreTransferPendingEvent if transfer handler has no more pending transfers. (NNMTP: Notify NoMoreTransferPending)
Definition at line 624 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::BulkInTransferCompletedEvent::transfer.
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::restoreBulkOutTransferNNMTP (BulkOutTransferCompletedEvent const & event) inline
Restore Bulk-OUT transfer to pool action.
This version will send NoMoreTransferPendingEvent if transfer handler has no more pending transfers. (NNMTP: Notify NoMoreTransferPending)
Definition at line 610 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::BulkOutTransferCompletedEvent::transfer.
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::restoreControlTransferNNMTP (ControlTransferCompletedEvent const & event) inline
Restore Control transfer to pool action.
This version will send NoMoreTransferPendingEvent if transfer handler has no more pending transfers. (NNMTP: Notify NoMoreTransferPending)
Definition at line 596 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::ControlTransferCompletedEvent::transfer.
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::restoreInterruptInTransferNNMTP (InterruptInTransferCompletedEvent const & event) inline
Restore Interrupt-IN transfer to pool action.
This version will send NoMoreTransferPendingEvent if transfer handler has no more pending transfers. (NNMTP: Notify NoMoreTransferPending)
Definition at line 646 of file mdtUsbtmcTransferHandlerStateMachine.h.
References mdtUsbtmcTransferHandlerStateMachine::InterruptInTransferCompletedEvent::transfer.
void mdtUsbtmcTransferHandlerStateMachine::StateMachine_::setTh (mdtUsbtmcTransferHandler * th) inline
Set transfer handler.
Must be called before starting the state machine
Definition at line 554 of file mdtUsbtmcTransferHandlerStateMachine.h.
Member Data Documentation
mdtUsbtmcTransferHandler* mdtUsbtmcTransferHandlerStateMachine::StateMachine_::transferHandler
Definition at line 880 of file mdtUsbtmcTransferHandlerStateMachine.h.
The documentation for this struct was generated from the following file:
src/mdtport/mdtUsbtmcTransferHandlerStateMachine.h