# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdtcsv/../../translations/mdtutils_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdtcsv/../../translations/mdtutils_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvStringParser.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileParser.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvStringGenerator.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileGenerator.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvRecordFormat.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvGeneratorSettingsWidget.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileGeneratorSettingsDialog.cpp
