# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdtcsv/../../translations/mdtutils_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdtcsv/../../translations/mdtutils_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvStringParser.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileParser.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvStringGenerator.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileGenerator.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvSourceInfo.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvStringInfo.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileInfo.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvRecordFormat.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvGeneratorSettingsWidget.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileSettingsWidget.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvFileGeneratorSettingsDialog.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvTableViewDataMapper.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvTableViewExportThread.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtcsv/mdtCsvTableViewExportDialog.cpp
