# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdterror/../../translations/mdtutils_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdterror/../../translations/mdtutils_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdterror/mdtErrorV2.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdterror/mdt/error/Logger.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdterror/mdt/error/LoggerBackend.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdterror/mdt/error/LoggerConsoleBackend.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdterror/mdt/error/LoggerFileBackend.cpp
