# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdterrorgui/../../translations/mdtutils_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdterrorgui/../../translations/mdtutils_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdterrorgui/mdtErrorDialog.cpp
