# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdtport/../../translations/mdtport_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdtport/../../translations/mdtport_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtAbstractPort.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPort.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPortThread.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPortReadThread.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPortWriteThread.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtTcpSocket.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtTcpSocketThread.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPortManager.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPortConfig.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPortConfigWidget.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/linux/mdtPortPosix.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/linux/mdtPortLock.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/linux/mdtUsbtmcPort.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/linux/mdtUsbtmcPortManager.h
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtport/linux/mdtUsbtmcPortManager.cpp
FORMS += /home/philippe/programmation/multiDiagTools/src/mdtport/mdtPortConfigWidget.ui
