# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdttools/../../translations/mdttools_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdttools/../../translations/mdttools_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdtPortTerm.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdtModbusIoTool.cpp
