# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/../../../translations/mdttesttool_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/../../../translations/mdttesttool_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtBase.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtDatabaseSchema.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestLinkData.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestLinkDialog.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestConnectionCable.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestConnectionCableEditor.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestNode.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestNodeEditor.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestNodeUnit.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestNodeUnitData.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestNodeUnitDialog.cpp
FORMS += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestConnectionCableEditor.ui
FORMS += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestLinkDialog.ui
FORMS += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestNodeEditor.ui
FORMS += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtTestNodeUnitDialog.ui
