# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS = /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/../../../translations/mdttesttool_fr.ts
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/../../../translations/mdttesttool_de.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtBase.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdttools/mdttesttool/mdtTtDatabaseSchema.cpp
