/****************************************************************************
 **
 ** Copyright (C) 2011-2018 Philippe Steinmann.
 **
 ** This file is part of Mdt library.
 **
 ** Mdt is free software: you can redistribute it and/or modify
 ** it under the terms of the GNU Lesser General Public License as published by
 ** the Free Software Foundation, either version 3 of the License, or
 ** (at your option) any later version.
 **
 ** Mdt is distributed in the hope that it will be useful,
 ** but WITHOUT ANY WARRANTY; without even the implied warranty of
 ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 ** GNU Lesser General Public License for more details.
 **
 ** You should have received a copy of the GNU Lesser General Public License
 ** along with Mdt.  If not, see <http://www.gnu.org/licenses/>.
 **
 ****************************************************************************/
#ifndef MDT_ENTITY_UNIQUE_CONSTRAINT_H
#define MDT_ENTITY_UNIQUE_CONSTRAINT_H

#include "TypeTraits/UniqueConstraintTag.h"
#include "TypeTraits/IsEntity.h"

namespace Mdt{ namespace Entity{

  /*! \brief Define a unique constraint on one or more fields in a entity
   *
   * For example, define a %Person entity:
   * \code
   * struct PersonDataStruct
   * {
   *   int id;
   *   QString firstName;
   *   QString lastName;
   * };
   *
   * MDT_ENTITY_DEF(
   *   (PersonDataStruct),
   *   Person,
   *   (id, FieldFlag::IsPrimaryKey),
   *   (firstName),
   *   (lastName)
   * )
   * \endcode
   *
   * To define a unique constraint on first name and last name:
   * \code
   * using PersonNameUniqueConstraint = Mdt::Entity::UniqueConstraint<PersonEntity, PersonDef::firstNameField, PersonDef::lastNameField>;
   * \endcode
   *
   * \todo Would like a better syntax:
   * \code
   * using PersonNameUniqueConstraint = Mdt::Entity::UniqueConstraint<PersonEntity, PersonEntity::firstName, PersonEntity::lastName>;
   * \endcode
   *
   * \pre \a Entity must be entities based on EntityTemplate ( generated by MDT_ENTITY_DEF() )
   * \pre The count of fields in the constraint must be at least 1
   */
  template<typename Entity, typename ...Fields>
  class UniqueConstraint : TypeTraits::UniqueConstraintTag
  {
    static_assert( TypeTraits::IsEntity<Entity>::value, "Entity must be a entity type" );
    static_assert( sizeof...(Fields) >= 1, "A unique constraint must refer to at least 1 field Entity" );

   public:

    using entity = Entity;
  };

}} // namespace Mdt{ namespace Entity{

#endif // #ifndef MDT_ENTITY_UNIQUE_CONSTRAINT_H
