# Translations project file for lupdate/lrelease
# This file is generated by CMake, all changes will be lost
TRANSLATIONS += /home/philippe/programmation/multiDiagTools/src/mdtutils/../../data/i18n/mdtutils_fr.ts
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtAlgorithms.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtBuffer.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrame.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrameAscii.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrameModbusTcp.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtTime.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrameCodec.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrameCodecAscii.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrameCodecScpi.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrameCodecScpiU3606A.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFrameCodecModbus.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtError.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtErrorOut.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtCsvFile.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtUicNumber.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtUicNumberItem.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtUicNumberWidget.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtUicNumberValidator.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtPartitionAttributes.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFileCopier.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtFileCopierItem.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtApplication.cpp
SOURCES += /home/philippe/programmation/multiDiagTools/src/mdtutils/linux/mdtPartitionAttributesPosix.cpp
FORMS += /home/philippe/programmation/multiDiagTools/src/mdtutils/mdtUicNumberWidget.ui
